// Logical Reasoning Questions Bank - Set 29
// High-quality LSAT-style questions covering all question types

import { Question } from "../lsat-types";

export const lrQuestionsSet29: Question[] = [
  {
    id: "lr-bank29-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor: Students who attend every lecture perform better on exams than students who miss lectures frequently. Therefore, the lectures themselves must be the primary cause of better exam performance.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that all students who attend lectures have equal aptitude" },
      { letter: "B", text: "overlooks the possibility that a common factor causes both lecture attendance and good exam performance" },
      { letter: "C", text: "fails to consider whether some lectures are more valuable than others" },
      { letter: "D", text: "generalizes from too small a sample of students" },
      { letter: "E", text: "ignores the role of teaching assistants in student success" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits a causal reasoning flaw. Students who attend every lecture might do so because they are more motivated, disciplined, or academically engaged—traits that would independently lead to better exam performance. The argument mistakenly concludes that lectures cause better performance when a third factor (such as conscientiousness) could cause both phenomena.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Organic produce is healthier than conventionally grown produce because organic farming prohibits the use of synthetic pesticides. Synthetic pesticides are harmful to human health. Therefore, anyone who eats conventionally grown produce is exposing themselves to significant health risks.`,
    questionStem: "The nutritionist's reasoning is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that organic farming produces no harmful residues" },
      { letter: "B", text: "fails to consider whether pesticide residues remain on produce in quantities significant enough to cause harm" },
      { letter: "C", text: "does not specify which synthetic pesticides are most dangerous" },
      { letter: "D", text: "overlooks the nutritional differences between organic and conventional produce" },
      { letter: "E", text: "assumes that all consumers prefer organic produce" },
    ],
    correctAnswer: "B",
    explanation: "The argument jumps from 'synthetic pesticides are harmful' to 'eating conventional produce causes significant health risks' without establishing that pesticide residues on produce exist in harmful quantities. A substance can be harmful in large doses but harmless at trace levels. The argument fails to bridge this quantitative gap.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `City Planner: The new highway expansion will reduce traffic congestion because it will provide additional lanes for vehicles. Critics who oppose the expansion based on environmental concerns are simply being obstructionist. If they truly cared about air quality, they would support reducing congestion, since idling in traffic produces more pollution than smooth-flowing traffic.`,
    questionStem: "The city planner's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "attacks the character of the critics rather than addressing their arguments" },
      { letter: "B", text: "assumes that all highway expansions reduce congestion" },
      { letter: "C", text: "fails to consider that highway expansion might induce additional traffic, ultimately maintaining or increasing congestion" },
      { letter: "D", text: "ignores the costs of highway construction" },
      { letter: "E", text: "relies on an unqualified assertion about pollution levels" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that adding lanes will reduce congestion, but this ignores the well-documented phenomenon of induced demand—when road capacity increases, more people choose to drive, often resulting in similar or worse congestion levels. The planner's dismissal of environmental critics is also problematic, but the core logical flaw is the failure to consider induced demand.",
    difficulty: "hard",
  },
  {
    id: "lr-bank29-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: Ancient peoples must have believed in an afterlife because they buried their dead with valuable objects. No one would bury valuable objects unless they believed the deceased could use them in another existence.`,
    questionStem: "Which one of the following most accurately describes a flaw in the archaeologist's reasoning?",
    answerChoices: [
      { letter: "A", text: "It assumes that ancient peoples valued the same objects modern people value" },
      { letter: "B", text: "It fails to consider alternative explanations for the burial of objects with the dead" },
      { letter: "C", text: "It generalizes from burial practices of one culture to all ancient peoples" },
      { letter: "D", text: "It relies on circular reasoning by assuming what it sets out to prove" },
      { letter: "E", text: "It treats a necessary condition as if it were sufficient" },
    ],
    correctAnswer: "B",
    explanation: "The archaeologist assumes that burial with objects implies belief in an afterlife, but there are other possible explanations: honoring the deceased, removing objects associated with death from the living community, displaying social status, or following tradition without literal belief. The argument fails to consider these alternatives.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Political Analyst: The incumbent senator will certainly win reelection. Her approval rating among her constituents is 62 percent, which is higher than any of her predecessors at this point in their terms. Every previous senator with approval ratings above 55 percent at this stage has won reelection.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "treats a correlation as if it were a cause" },
      { letter: "B", text: "assumes past patterns will necessarily continue in the future" },
      { letter: "C", text: "fails to consider the approval ratings of the challengers" },
      { letter: "D", text: "relies on a sample that may be too small to support the conclusion" },
      { letter: "E", text: "confuses a sufficient condition with a necessary one" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that because previous senators with similar approval ratings won, this senator will certainly win. This commits the fallacy of assuming past patterns guarantee future results. Political circumstances, opponents, and voter turnout can vary significantly, making historical patterns imperfect predictors.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Some philosophers argue that lying is always morally wrong. But surely a lie told to protect someone from harm—such as lying to a murderer about the location of their intended victim—cannot be considered immoral. Therefore, those philosophers are entirely wrong about the ethics of lying.`,
    questionStem: "The ethicist's argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "assumes without justification that protecting someone from harm is morally permissible" },
      { letter: "B", text: "treats a counterexample to a universal claim as evidence that the claim is entirely wrong rather than merely overstated" },
      { letter: "C", text: "fails to consider that different types of lies might have different moral statuses" },
      { letter: "D", text: "relies on an extreme example that is unlikely to occur in practice" },
      { letter: "E", text: "attacks a position that the philosophers may not actually hold" },
    ],
    correctAnswer: "B",
    explanation: "The ethicist shows that lying is not ALWAYS wrong by providing a counterexample, but then concludes that the philosophers are ENTIRELY wrong. This is an overreach—finding an exception to a universal claim only proves the claim is overstated, not that it is completely false. The philosophers might still be largely correct that lying is generally wrong.",
    difficulty: "hard",
  },
  {
    id: "lr-bank29-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `CEO: Our company's profits have increased every year since we implemented our new management strategy five years ago. Clearly, the new management strategy is responsible for our financial success.`,
    questionStem: "The reasoning in the CEO's argument is flawed because the argument",
    answerChoices: [
      { letter: "A", text: "fails to establish that the management strategy was implemented correctly" },
      { letter: "B", text: "does not consider other factors that might have contributed to increased profits" },
      { letter: "C", text: "assumes that all profitable companies use similar management strategies" },
      { letter: "D", text: "relies on an inappropriate measure of financial success" },
      { letter: "E", text: "ignores the possibility that profits would have increased even more without the strategy" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the post hoc ergo propter hoc fallacy—assuming that because profits increased after the management strategy was implemented, the strategy caused the increase. Many other factors could explain the profit growth: economic conditions, industry trends, competitor failures, or other company initiatives. The argument fails to control for these alternatives.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The Roman Empire fell because of moral decay among its citizens. The evidence for this is clear: in the decades before the fall, Roman literature contained increasingly frequent references to corruption and moral failings in society.`,
    questionStem: "The historian's reasoning is most vulnerable to the criticism that it",
    answerChoices: [
      { letter: "A", text: "assumes that literary references accurately reflect actual social conditions" },
      { letter: "B", text: "ignores the military factors that contributed to Rome's fall" },
      { letter: "C", text: "fails to define what constitutes moral decay" },
      { letter: "D", text: "relies on translations of ancient texts that may be inaccurate" },
      { letter: "E", text: "assumes that earlier Roman literature never mentioned corruption" },
    ],
    correctAnswer: "A",
    explanation: "The historian uses literary references to moral failings as evidence of actual moral decay in society. This assumes that literature accurately mirrors social reality, which is problematic. Literature might reflect changing artistic conventions, increased willingness to discuss such topics, or the perspectives of particular authors rather than objective social conditions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-009",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Restaurant Critic: This restaurant must have excellent food because it has been in business for over thirty years. A restaurant could not survive that long without serving high-quality meals.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that food quality is the only factor in restaurant longevity" },
      { letter: "B", text: "fails to consider whether the restaurant's quality has declined over time" },
      { letter: "C", text: "relies on the unwarranted assumption that older restaurants are better" },
      { letter: "D", text: "ignores the possibility that the restaurant may have recently changed ownership" },
      { letter: "E", text: "does not specify what constitutes excellent food" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that the only reason a restaurant could survive for thirty years is excellent food quality. However, restaurants can succeed for many reasons: prime location, loyal customer base, lack of competition, low prices, sentimental value, or effective marketing. The argument overlooks these alternative explanations for longevity.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-010",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Defense Attorney: My client cannot be guilty of the robbery. The prosecution's case relies entirely on eyewitness testimony, and psychological research has repeatedly shown that eyewitness testimony is often unreliable. Therefore, the eyewitnesses in this case must be mistaken.`,
    questionStem: "The defense attorney's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "attacks the prosecution rather than addressing the evidence" },
      { letter: "B", text: "treats a general tendency as if it applies necessarily to a specific case" },
      { letter: "C", text: "assumes that psychological research is always accurate" },
      { letter: "D", text: "fails to provide an alternative explanation for the crime" },
      { letter: "E", text: "ignores the possibility that multiple eyewitnesses corroborated each other" },
    ],
    correctAnswer: "B",
    explanation: "The attorney moves from the general claim that eyewitness testimony is 'often unreliable' to the specific conclusion that these particular eyewitnesses 'must be mistaken.' This is a fallacy of division—applying a statistical tendency to a specific instance as if it were certain. Even if eyewitnesses are often wrong, they are not always wrong.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-011",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Medical Researcher: A new study found that patients who took vitamin D supplements had a 30% lower rate of respiratory infections than those who did not. This suggests that vitamin D supplementation can help prevent respiratory infections in the general population.`,
    questionStem: "Which one of the following, if true, most strengthens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Vitamin D is essential for bone health" },
      { letter: "B", text: "The study participants who took supplements had similar baseline vitamin D levels to those who did not" },
      { letter: "C", text: "Respiratory infections are most common during winter months" },
      { letter: "D", text: "Vitamin D can be obtained from sunlight exposure" },
      { letter: "E", text: "The study was conducted by a well-respected university" },
    ],
    correctAnswer: "B",
    explanation: "If the supplement group had similar baseline vitamin D levels to the control group, this rules out the possibility that the supplement group was already healthier or had better vitamin D status to begin with. This strengthens the causal claim that the supplements themselves, rather than pre-existing differences, caused the lower infection rate.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Urban neighborhoods with more public parks have lower crime rates than neighborhoods with fewer parks. Therefore, building more parks in high-crime areas would likely reduce crime in those areas.`,
    questionStem: "Which one of the following, if true, would most strengthen the sociologist's argument?",
    answerChoices: [
      { letter: "A", text: "High-crime areas tend to have fewer public amenities of all types" },
      { letter: "B", text: "When parks were added to several high-crime neighborhoods, crime rates in those neighborhoods subsequently declined" },
      { letter: "C", text: "Parks provide recreational opportunities for young people" },
      { letter: "D", text: "Wealthier neighborhoods tend to have more parks" },
      { letter: "E", text: "Most crimes occur in areas away from public parks" },
    ],
    correctAnswer: "B",
    explanation: "The original argument is correlational—neighborhoods with more parks have less crime. Answer B provides direct evidence of a causal relationship: when parks were added, crime declined. This intervention-based evidence is much stronger support for the claim that adding parks would reduce crime than the mere correlation cited in the argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art Historian: The painting attributed to Vermeer cannot be authentic. Vermeer was known to have used only natural ultramarine blue pigment, which was extremely expensive. Chemical analysis of this painting reveals the presence of Prussian blue, a synthetic pigment not invented until decades after Vermeer's death.`,
    questionStem: "Which one of the following, if true, most strengthens the art historian's argument?",
    answerChoices: [
      { letter: "A", text: "Prussian blue was widely used by painters in the eighteenth century" },
      { letter: "B", text: "No known restoration of the painting could account for the presence of Prussian blue" },
      { letter: "C", text: "Vermeer's paintings are among the most valuable in the world" },
      { letter: "D", text: "Natural ultramarine blue has a distinctive appearance under X-ray analysis" },
      { letter: "E", text: "Several other paintings attributed to Vermeer have been proven to be forgeries" },
    ],
    correctAnswer: "B",
    explanation: "The main weakness in the argument is that Prussian blue could have been added during a later restoration rather than being part of the original painting. Answer B eliminates this objection by establishing that restoration cannot explain the Prussian blue, thereby strengthening the conclusion that the painting is not authentic.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Countries that invest heavily in education tend to have higher rates of economic growth. Therefore, the most effective way for developing countries to stimulate economic growth is to increase spending on education.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Many factors contribute to economic growth besides education" },
      { letter: "B", text: "Countries with higher economic growth can afford to spend more on education" },
      { letter: "C", text: "Education spending in developing countries has increased over the past decade" },
      { letter: "D", text: "When developing countries increased education spending, their economic growth rates subsequently improved regardless of other factors" },
      { letter: "E", text: "Developed countries spend a higher percentage of their budgets on education than developing countries" },
    ],
    correctAnswer: "D",
    explanation: "The economist argues from correlation to causation. Answer D provides direct evidence of a causal relationship specifically in developing countries—when they increased education spending, growth improved regardless of other factors. This directly supports the conclusion that education spending is an effective way for developing countries to stimulate growth.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Biologist: The newly discovered species of frog must have evolved in isolation on this island. It shares only 60% of its DNA with the most closely related mainland species, indicating millions of years of separate evolution.`,
    questionStem: "Which one of the following, if true, most strengthens the biologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Many species have evolved in isolation on islands" },
      { letter: "B", text: "The island has been separated from the mainland by deep ocean water for at least 20 million years" },
      { letter: "C", text: "Frogs cannot survive long periods in salt water" },
      { letter: "D", text: "The frog has unique physical features not found in any mainland species" },
      { letter: "E", text: "DNA analysis is a reliable method for determining evolutionary relationships" },
    ],
    correctAnswer: "C",
    explanation: "For the frog to have evolved in isolation on the island, it must not have been able to travel to or from the mainland. Answer C establishes that frogs cannot survive in salt water, meaning they could not have crossed the ocean to reach the island after it separated from the mainland. This strongly supports the isolation hypothesis.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Legal Scholar: Mandatory minimum sentences for drug offenses have not reduced drug use rates, which have remained stable for decades. Furthermore, these sentences have dramatically increased prison populations and costs. Therefore, mandatory minimum sentences for drug offenses should be eliminated.`,
    questionStem: "Which one of the following, if true, would most strengthen the legal scholar's argument?",
    answerChoices: [
      { letter: "A", text: "Drug use rates are difficult to measure accurately" },
      { letter: "B", text: "States that have eliminated mandatory minimums have not seen increases in drug use" },
      { letter: "C", text: "Mandatory minimum sentences were originally intended to reduce drug use" },
      { letter: "D", text: "Prison costs have become a significant portion of state budgets" },
      { letter: "E", text: "Some judges have criticized mandatory minimum sentences" },
    ],
    correctAnswer: "B",
    explanation: "The scholar argues that mandatory minimums should be eliminated because they haven't reduced drug use. A key concern with elimination would be whether drug use might increase. Answer B addresses this directly by showing that states that eliminated mandatory minimums did not see drug use increases, supporting the conclusion that elimination is a viable policy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Environmental Scientist: Coral reef ecosystems are being devastated by rising ocean temperatures. Without significant intervention, most coral reefs will be extinct within 30 years. We must take immediate action to reduce carbon emissions to save these ecosystems.`,
    questionStem: "Which one of the following, if true, most strengthens the scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Coral reefs are home to thousands of marine species" },
      { letter: "B", text: "Ocean temperatures have risen steadily over the past century" },
      { letter: "C", text: "Coral reefs can partially recover from bleaching events if temperatures decrease" },
      { letter: "D", text: "Some species of coral are more heat-resistant than others" },
      { letter: "E", text: "Previous mass extinctions have been caused by climate change" },
    ],
    correctAnswer: "C",
    explanation: "The scientist argues that reducing carbon emissions is necessary to save coral reefs. Answer C strengthens this by showing that action can make a difference—if temperatures decrease, corals can recover. This establishes that the proposed solution (reducing emissions to lower temperatures) could actually work to save the reefs.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-018",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Employees who are given autonomy in how they complete their tasks report higher job satisfaction than those who are micromanaged. Companies should therefore give employees more autonomy to improve overall workplace morale.`,
    questionStem: "Which one of the following, if true, most strengthens the psychologist's recommendation?",
    answerChoices: [
      { letter: "A", text: "Job satisfaction is an important factor in employee retention" },
      { letter: "B", text: "Most companies currently micromanage their employees" },
      { letter: "C", text: "Employees with autonomy also tend to be more productive" },
      { letter: "D", text: "Higher job satisfaction leads to higher overall workplace morale" },
      { letter: "E", text: "Some tasks require close supervision to be completed correctly" },
    ],
    correctAnswer: "D",
    explanation: "The psychologist concludes that autonomy will improve workplace morale based on evidence that it increases job satisfaction. This argument assumes that higher job satisfaction leads to higher morale. Answer D explicitly confirms this connection, strengthening the link between the evidence (satisfaction) and the conclusion (morale).",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-019",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Marketing Executive: Our new advertising campaign must be effective because sales increased by 15% in the month after we launched it. The campaign's creative messaging clearly resonated with consumers.`,
    questionStem: "Which one of the following, if true, most weakens the executive's argument?",
    answerChoices: [
      { letter: "A", text: "The company's main competitor went out of business the month before the campaign launched" },
      { letter: "B", text: "The advertising campaign cost more than previous campaigns" },
      { letter: "C", text: "Some consumers reported not seeing the advertisements" },
      { letter: "D", text: "Sales had been declining in the months before the campaign" },
      { letter: "E", text: "The campaign featured a popular celebrity endorser" },
    ],
    correctAnswer: "A",
    explanation: "The executive claims the advertising campaign caused the sales increase. Answer A provides an alternative explanation—a major competitor went out of business. This could easily explain the 15% sales increase regardless of the advertising campaign, significantly weakening the claim that the campaign was effective.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The Industrial Revolution began in Britain rather than elsewhere because Britain had abundant coal deposits. Coal was essential for powering the steam engines that drove industrial production.`,
    questionStem: "Which one of the following, if true, most weakens the historian's explanation?",
    answerChoices: [
      { letter: "A", text: "Germany and France also had significant coal deposits but industrialized later than Britain" },
      { letter: "B", text: "British coal deposits were of particularly high quality" },
      { letter: "C", text: "The steam engine was invented in Britain" },
      { letter: "D", text: "Other energy sources, such as water power, were also used in early industrialization" },
      { letter: "E", text: "Britain had a well-developed banking system during the Industrial Revolution" },
    ],
    correctAnswer: "A",
    explanation: "The historian argues that coal abundance explains why the Industrial Revolution began in Britain. Answer A undermines this by pointing out that other countries had significant coal deposits but did not industrialize first. If coal abundance were the key factor, these countries should have industrialized at similar times. The existence of coal-rich late industrializers suggests coal alone cannot explain Britain's primacy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Fitness Expert: High-intensity interval training (HIIT) is superior to steady-state cardio for weight loss. Studies show that participants who engaged in HIIT lost more weight over a 12-week period than those who did traditional cardio exercises.`,
    questionStem: "Which one of the following, if true, most weakens the fitness expert's argument?",
    answerChoices: [
      { letter: "A", text: "HIIT workouts are typically shorter than steady-state cardio sessions" },
      { letter: "B", text: "The HIIT participants in the studies also followed stricter diets than the steady-state cardio participants" },
      { letter: "C", text: "HIIT has cardiovascular benefits beyond weight loss" },
      { letter: "D", text: "Some participants dropped out of the HIIT program due to its intensity" },
      { letter: "E", text: "Steady-state cardio is easier for beginners to perform" },
    ],
    correctAnswer: "B",
    explanation: "The expert concludes that HIIT is superior for weight loss based on study results. Answer B reveals a confounding variable—the HIIT group followed stricter diets. This means the weight loss difference could be due to dietary differences rather than the exercise type, seriously weakening the claim that HIIT itself is superior for weight loss.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Raising the minimum wage will not increase unemployment. Historical data shows that in states where the minimum wage was increased, unemployment rates remained stable or even decreased in the following year.`,
    questionStem: "Which one of the following, if true, most seriously undermines the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Some employers respond to minimum wage increases by reducing workers' hours" },
      { letter: "B", text: "The minimum wage increases in those states were accompanied by periods of strong economic growth" },
      { letter: "C", text: "Not all workers earn the minimum wage" },
      { letter: "D", text: "Some states have higher minimum wages than others" },
      { letter: "E", text: "Inflation erodes the real value of minimum wage increases over time" },
    ],
    correctAnswer: "B",
    explanation: "The economist uses stable or decreasing unemployment after minimum wage increases as evidence. Answer B provides an alternative explanation—those states experienced strong economic growth, which would independently reduce unemployment. The employment stability might be due to economic conditions rather than the minimum wage having no negative effect.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: The ancient city must have had a highly organized government because the ruins show evidence of large-scale public works projects, including roads, aqueducts, and temples. Such projects could only have been completed under centralized direction.`,
    questionStem: "Which one of the following, if true, most weakens the archaeologist's reasoning?",
    answerChoices: [
      { letter: "A", text: "The ruins date back over 3,000 years" },
      { letter: "B", text: "Other ancient cities with organized governments had similar public works" },
      { letter: "C", text: "Some ancient societies completed large public works through voluntary community cooperation without centralized government" },
      { letter: "D", text: "The ancient city had a population of approximately 50,000 people" },
      { letter: "E", text: "Many of the ruins have deteriorated significantly over time" },
    ],
    correctAnswer: "C",
    explanation: "The archaeologist assumes that large-scale public works require centralized government direction. Answer C directly challenges this assumption by providing examples of societies that completed such projects through voluntary cooperation without centralized government. This shows that the premise 'only centralized direction could complete such projects' is false.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-024",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Technology Analyst: Smartphones have made people less social. Before smartphones, people would talk to strangers in public spaces. Now, everyone just stares at their screens.`,
    questionStem: "Which one of the following, if true, most weakens the analyst's conclusion?",
    answerChoices: [
      { letter: "A", text: "Smartphone usage has increased every year since their introduction" },
      { letter: "B", text: "Research shows that smartphone users maintain more social connections and communicate more frequently than non-users" },
      { letter: "C", text: "Some public spaces now have designated phone-free zones" },
      { letter: "D", text: "Older adults are less likely to use smartphones than younger adults" },
      { letter: "E", text: "Newspapers and books served similar functions before smartphones existed" },
    ],
    correctAnswer: "B",
    explanation: "The analyst concludes that smartphones make people less social based on observations of reduced in-person interaction in public spaces. Answer B challenges this by showing that smartphone users actually maintain more social connections and communicate more frequently. Reduced public space interactions may not indicate reduced sociality overall if digital communication is counted.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-025",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Criminologist: Longer prison sentences do not deter crime. Countries with longer average sentences do not have lower crime rates than countries with shorter sentences. If longer sentences deterred crime, we would expect to see lower crime rates in countries with longer sentences.`,
    questionStem: "Which one of the following, if true, most weakens the criminologist's argument?",
    answerChoices: [
      { letter: "A", text: "Crime rates are influenced by many factors besides sentencing length" },
      { letter: "B", text: "Countries with longer sentences typically impose them in response to higher crime rates, which makes cross-country comparisons misleading" },
      { letter: "C", text: "Most criminals are unaware of the specific sentences for various crimes" },
      { letter: "D", text: "Some countries have both long sentences and high recidivism rates" },
      { letter: "E", text: "Public opinion generally supports longer sentences for serious crimes" },
    ],
    correctAnswer: "B",
    explanation: "The criminologist's argument is based on comparing countries with different sentence lengths. Answer B reveals a serious methodological problem: countries might have longer sentences precisely because they have higher crime rates. This reverse causation makes the comparison invalid—you cannot conclude sentences don't deter crime if the countries with longer sentences started with higher crime rates.",
    difficulty: "hard",
  },
  {
    id: "lr-bank29-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Business Consultant: Open-plan offices boost productivity by facilitating collaboration and communication. Companies that have switched to open-plan layouts report increased employee interaction.`,
    questionStem: "Which one of the following, if true, most weakens the consultant's conclusion?",
    answerChoices: [
      { letter: "A", text: "Open-plan offices are less expensive to build than traditional offices" },
      { letter: "B", text: "Studies show that while face-to-face interactions increase in open offices, most are social rather than work-related, and overall productivity often declines due to noise and interruptions" },
      { letter: "C", text: "Some employees prefer open-plan offices" },
      { letter: "D", text: "Many technology companies use open-plan offices" },
      { letter: "E", text: "Private offices provide more space for personal belongings" },
    ],
    correctAnswer: "B",
    explanation: "The consultant assumes that increased employee interaction leads to increased productivity. Answer B undermines this by showing that while interactions increase, they are mostly social rather than work-related, and productivity often declines due to noise and interruptions. More interaction does not equal more productive interaction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Ethics Professor: Students who take ethics courses become more ethical in their professional lives. Therefore, universities should require all business majors to take at least one ethics course before graduation.`,
    questionStem: "The ethics professor's argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Business majors are less ethical than other students" },
      { letter: "B", text: "Ethics courses are not already required for business majors" },
      { letter: "C", text: "Being more ethical in professional life is desirable for business majors" },
      { letter: "D", text: "Ethics professors are themselves ethical in their professional conduct" },
      { letter: "E", text: "All universities offer ethics courses" },
    ],
    correctAnswer: "C",
    explanation: "The professor argues that ethics courses should be required because they make students more ethical professionally. This conclusion only follows if being more ethical professionally is actually desirable for business majors. If there were no benefit to business majors being more ethical, there would be no reason to require the course. This assumption is necessary for the argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Environmentalist: We must protect endangered species from extinction. If a species goes extinct, we lose the potential benefits it might provide, such as compounds that could be developed into medicines. Therefore, protecting endangered species is essential for human well-being.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "All endangered species contain compounds useful for medicine" },
      { letter: "B", text: "Protecting endangered species is the only way to preserve potential medical benefits" },
      { letter: "C", text: "At least some endangered species might provide benefits that contribute to human well-being" },
      { letter: "D", text: "Human well-being should be the primary consideration in environmental policy" },
      { letter: "E", text: "Scientists have already discovered medicines derived from endangered species" },
    ],
    correctAnswer: "C",
    explanation: "The argument links species protection to human well-being through potential benefits like medicines. For this link to hold, at least some endangered species must actually have the potential to provide such benefits. If no endangered species could provide any benefits, the stated reason for protecting them would be invalidated. Note that the argument doesn't require all species to have benefits (A is too strong), just some.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Urban Planner: To reduce traffic congestion, the city should invest in improved public transportation rather than building new roads. When cities build new roads, traffic volume increases to fill the new capacity, leaving congestion unchanged.`,
    questionStem: "The urban planner's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Public transportation is always more cost-effective than road construction" },
      { letter: "B", text: "Improved public transportation will not also lead to increased usage that recreates congestion" },
      { letter: "C", text: "Most commuters would prefer public transportation to driving" },
      { letter: "D", text: "The city has sufficient funds to improve public transportation" },
      { letter: "E", text: "Traffic congestion has negative effects on the city's economy" },
    ],
    correctAnswer: "B",
    explanation: "The planner argues against new roads because induced demand fills new capacity, leaving congestion unchanged. For public transportation to be a better solution, it must not suffer from the same problem. The argument assumes that improved public transportation won't also induce enough new demand to recreate congestion. Otherwise, both solutions would fail equally.",
    difficulty: "hard",
  },
  {
    id: "lr-bank29-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Literary Critic: Shakespeare's plays contain themes that resonate with audiences today as much as they did four centuries ago. This proves that human nature is fundamentally unchanging across time and cultures.`,
    questionStem: "Which one of the following is an assumption required by the literary critic's argument?",
    answerChoices: [
      { letter: "A", text: "Shakespeare's plays are the only works that resonate across centuries" },
      { letter: "B", text: "The themes in Shakespeare's plays that resonate today are the same themes that resonated with original audiences" },
      { letter: "C", text: "Shakespeare intended his plays to reveal truths about human nature" },
      { letter: "D", text: "Modern audiences interpret Shakespeare's plays correctly" },
      { letter: "E", text: "No other explanation could account for the continued popularity of Shakespeare's plays" },
    ],
    correctAnswer: "B",
    explanation: "The critic argues that the plays' continued resonance proves unchanging human nature. This only works if the themes that resonate today are the same ones that resonated originally. If modern audiences respond to entirely different aspects of the plays than original audiences did, the continued popularity would not demonstrate that human nature is unchanged—it might instead show that the plays are versatile enough to mean different things to different eras.",
    difficulty: "hard",
  },
  {
    id: "lr-bank29-031",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Neurologist: Brain scans show that people who regularly practice meditation have increased gray matter density in areas associated with self-awareness and compassion. Therefore, meditation causes positive changes in brain structure.`,
    questionStem: "The neurologist's argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Gray matter density is correlated with intelligence" },
      { letter: "B", text: "The observed structural differences are not due to pre-existing traits that made certain people more likely to take up meditation" },
      { letter: "C", text: "All forms of meditation produce identical brain changes" },
      { letter: "D", text: "Brain structure cannot change in adulthood" },
      { letter: "E", text: "Self-awareness and compassion are universally considered positive traits" },
    ],
    correctAnswer: "B",
    explanation: "The neurologist concludes that meditation causes brain changes based on observed differences between meditators and non-meditators. This assumes the differences result from meditation rather than pre-existing differences. People who have naturally higher gray matter in certain areas might be more inclined to meditate in the first place. The argument requires assuming this selection effect is not responsible for the observed differences.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Political Commentator: Democracies are more peaceful than authoritarian regimes because the public bears the costs of war. Since citizens in democracies can vote leaders out of office, democratic leaders are less likely to engage in military conflicts that would be unpopular with voters.`,
    questionStem: "The commentator's argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Authoritarian regimes are always aggressive" },
      { letter: "B", text: "Citizens in democracies are generally informed about military conflicts" },
      { letter: "C", text: "Military conflicts are generally unpopular with voters in democracies" },
      { letter: "D", text: "Democratic leaders always follow the will of the majority" },
      { letter: "E", text: "All democracies have identical voting systems" },
    ],
    correctAnswer: "C",
    explanation: "The argument claims democratic leaders avoid conflicts because they would be 'unpopular with voters.' This reasoning only works if military conflicts are actually unpopular with voters. If wars were popular with democratic citizens, the electoral pressure would push toward conflict, not peace. The assumption that military conflicts are generally unpopular is necessary for the argument's logic.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Free will is an illusion because all our actions are determined by prior causes—our genetics, upbringing, and circumstances. Since we did not choose these factors, we cannot truly be said to choose our actions.`,
    questionStem: "The philosopher's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Genetics is the most important factor determining behavior" },
      { letter: "B", text: "True choice requires that our decisions not be fully determined by prior factors" },
      { letter: "C", text: "Most people believe they have free will" },
      { letter: "D", text: "Science can explain all human behavior" },
      { letter: "E", text: "Moral responsibility requires the existence of free will" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher argues that because our actions are determined by prior causes we didn't choose, we don't truly choose our actions (no free will). This reasoning assumes a particular definition of 'choice' or 'free will'—namely, that genuine choice requires our decisions not be fully determined by prior factors. A compatibilist might argue that choice is consistent with determinism, so this assumption is necessary for the argument.",
    difficulty: "hard",
  },
  {
    id: "lr-bank29-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Health Official: The flu vaccine is safe and everyone should get vaccinated. While a small percentage of people experience mild side effects like soreness at the injection site, these are minor compared to the severe illness that the flu can cause.`,
    questionStem: "Which one of the following is an assumption on which the health official's argument depends?",
    answerChoices: [
      { letter: "A", text: "Everyone is at equal risk of contracting the flu" },
      { letter: "B", text: "The flu vaccine is 100 percent effective at preventing illness" },
      { letter: "C", text: "The mild side effects from the vaccine are not worse than the flu itself for most people" },
      { letter: "D", text: "No alternative methods of flu prevention exist" },
      { letter: "E", text: "Vaccines have never caused serious adverse reactions" },
    ],
    correctAnswer: "C",
    explanation: "The official argues everyone should be vaccinated because the minor side effects are outweighed by protection from severe flu illness. This comparison assumes that the side effects are indeed minor relative to the flu for most recipients. If the side effects were as bad as or worse than the flu for many people, the argument's cost-benefit analysis would fail.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Many believe that government regulation stifles economic innovation. However, some of the most innovative periods in American history coincided with significant regulatory oversight. The pharmaceutical industry, for instance, developed groundbreaking treatments while operating under strict FDA regulations. Regulation can actually channel innovation in productive directions by setting standards that companies must creatively meet.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the economist's argument?",
    answerChoices: [
      { letter: "A", text: "The pharmaceutical industry developed important treatments under FDA regulation" },
      { letter: "B", text: "Government regulation does not necessarily stifle economic innovation" },
      { letter: "C", text: "Some of the most innovative periods in American history involved significant regulation" },
      { letter: "D", text: "Regulation sets standards that companies must meet" },
      { letter: "E", text: "Many people believe regulation harms innovation" },
    ],
    correctAnswer: "B",
    explanation: "The economist begins by noting a common belief (regulation stifles innovation) and then argues against it using examples and reasoning. The main conclusion is that regulation does not necessarily stifle innovation—it can even channel innovation productively. The examples about the pharmaceutical industry and historical periods are supporting evidence, not the main conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Some philosophers argue that we have stronger moral obligations to those who are geographically closer to us. But geography is morally arbitrary—a person's location is a matter of chance, not moral desert. The suffering of a child on another continent is no less significant than the suffering of a child in our own neighborhood. Therefore, we should give equal moral weight to the needs of all people, regardless of their physical proximity to us.`,
    questionStem: "The main conclusion of the ethicist's argument is that",
    answerChoices: [
      { letter: "A", text: "geography is morally arbitrary" },
      { letter: "B", text: "some philosophers believe we have stronger obligations to those nearby" },
      { letter: "C", text: "children suffer regardless of their location" },
      { letter: "D", text: "we should give equal moral consideration to all people regardless of their proximity" },
      { letter: "E", text: "a person's location is determined by chance" },
    ],
    correctAnswer: "D",
    explanation: "The ethicist builds an argument: geography is morally arbitrary, suffering is equally significant regardless of location, therefore we should give equal moral weight to all people regardless of proximity. The word 'therefore' signals the main conclusion—the normative claim about how we should act. The other statements are premises supporting this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: Climate models have consistently underestimated the rate of ice sheet melting in Greenland and Antarctica. The latest satellite data shows melting occurring decades ahead of model predictions. Since these models form the basis for our climate projections, we may be significantly underestimating the pace and severity of future climate change impacts.`,
    questionStem: "Which one of the following most accurately expresses the main point of the scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Climate models have underestimated ice sheet melting rates" },
      { letter: "B", text: "Satellite data provides more accurate measurements than climate models" },
      { letter: "C", text: "Our projections may significantly underestimate future climate change impacts" },
      { letter: "D", text: "Ice sheets in Greenland and Antarctica are melting faster than expected" },
      { letter: "E", text: "Climate models need to be updated with new data" },
    ],
    correctAnswer: "C",
    explanation: "The scientist presents a chain of reasoning: models underestimate melting, these models inform our projections, therefore our projections may underestimate future impacts. The main conclusion is the ultimate implication—that we may be underestimating future climate change impacts. The information about models and melting provides the evidence for this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Music Critic: Popular music has not declined in quality over the decades, despite common complaints. What has changed is the sheer volume of music being released. With more music available, the proportion of excellent work relative to mediocre work may seem smaller, even if the absolute number of great songs has not decreased. Those who claim music was better in the past are comparing the best of previous eras to the average of today.`,
    questionStem: "The music critic's main conclusion is that",
    answerChoices: [
      { letter: "A", text: "more music is being released now than in the past" },
      { letter: "B", text: "people who prefer older music are making an unfair comparison" },
      { letter: "C", text: "popular music has not declined in quality over time" },
      { letter: "D", text: "the absolute number of great songs has not decreased" },
      { letter: "E", text: "excellent music represents a smaller proportion of all music today" },
    ],
    correctAnswer: "C",
    explanation: "The critic's opening statement—'Popular music has not declined in quality over the decades'—is the main conclusion. Everything that follows explains why this is true despite appearances: the volume of music has increased, making excellent work seem proportionally rarer, and critics unfairly compare past bests to present averages. These are all supporting reasons for the main claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Doctor: Some patients believe that antibiotics can cure viral infections like the common cold. But antibiotics work by targeting bacterial cell structures that viruses don't possess. Viruses are fundamentally different from bacteria in their structure and reproduction. Therefore, prescribing antibiotics for viral infections is ineffective and can contribute to antibiotic resistance.`,
    questionStem: "The doctor's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "citing statistical evidence about treatment outcomes" },
      { letter: "B", text: "explaining the scientific mechanism that makes the common belief incorrect" },
      { letter: "C", text: "appealing to the authority of medical experts" },
      { letter: "D", text: "providing examples of cases where antibiotics failed to cure viral infections" },
      { letter: "E", text: "questioning the motives of those who hold the opposing view" },
    ],
    correctAnswer: "B",
    explanation: "The doctor refutes the common belief by explaining why it's wrong scientifically: antibiotics target bacterial structures that viruses lack. This is an appeal to mechanism—explaining the underlying science of how antibiotics work to show why they cannot work against viruses. No statistics, authorities, examples, or motive questioning is involved.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Many people assume that if something cannot be measured scientifically, it cannot be real. But love, justice, and beauty cannot be quantified in a laboratory, yet few would deny their reality. The assumption that reality is limited to the measurable is itself not a claim that can be scientifically measured—it is a philosophical position that must be argued for on other grounds.`,
    questionStem: "The philosopher's argument employs which one of the following reasoning techniques?",
    answerChoices: [
      { letter: "A", text: "showing that a position leads to conclusions its proponents would reject" },
      { letter: "B", text: "demonstrating that a claim is internally inconsistent or self-undermining" },
      { letter: "C", text: "providing a comprehensive definition of the concept in question" },
      { letter: "D", text: "drawing an analogy between two similar situations" },
      { letter: "E", text: "citing expert opinion to support the main conclusion" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher argues that the claim 'only measurable things are real' is self-undermining because this very claim cannot itself be scientifically measured—it's a philosophical position. The argument shows that the position fails by its own standard, making it internally inconsistent. This is a self-refutation argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Some have argued that social media causes depression among teenagers. But consider: teenagers who are already prone to depression may simply use social media more as a way of coping with social isolation. The correlation between social media use and depression does not tell us which is causing which, or whether both are effects of some third factor.`,
    questionStem: "The sociologist's response to the argument proceeds by",
    answerChoices: [
      { letter: "A", text: "presenting statistical evidence that contradicts the original claim" },
      { letter: "B", text: "demonstrating that the original argument's conclusion is factually incorrect" },
      { letter: "C", text: "offering alternative explanations for the observed correlation" },
      { letter: "D", text: "showing that the original argument relies on a false premise" },
      { letter: "E", text: "arguing that the concept of depression is poorly defined" },
    ],
    correctAnswer: "C",
    explanation: "The sociologist does not dispute that a correlation exists between social media use and depression. Instead, the sociologist offers alternative causal explanations: depression might cause social media use (reverse causation), or both might be effects of a third factor. By providing these alternatives, the sociologist shows that the correlation does not establish the claimed causal direction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense Attorney: The prosecution claims my client robbed the bank at 3 PM on Tuesday. But the bank's own security footage shows the robber was approximately 5'6" tall. My client is 6'2". The prosecution's witness identified my client from a photo lineup, but such identifications are notoriously unreliable, especially across racial lines. Given the physical impossibility of my client being the robber and the unreliability of the identification, my client must be innocent.`,
    questionStem: "The defense attorney's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "establishing an alibi showing the defendant was elsewhere" },
      { letter: "B", text: "challenging the prosecution's evidence on multiple independent grounds" },
      { letter: "C", text: "arguing that the prosecution has violated proper legal procedures" },
      { letter: "D", text: "presenting character witnesses who testify to the defendant's honesty" },
      { letter: "E", text: "demonstrating that the crime did not actually occur" },
    ],
    correctAnswer: "B",
    explanation: "The attorney attacks the prosecution's case on two independent grounds: (1) physical evidence (height discrepancy) makes it impossible for the client to be the robber, and (2) the eyewitness identification is unreliable. By undermining multiple pieces of evidence independently, the attorney builds a stronger case for innocence than attacking just one element would provide.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Journalist: The government's new surveillance program, while potentially useful for preventing terrorism, represents an unacceptable invasion of citizens' privacy. The potential for abuse is too great, and history has shown that surveillance powers, once granted, are rarely relinquished.

Security Analyst: The surveillance program is essential for national security. Privacy concerns, while legitimate, must be balanced against the need to protect citizens from terrorist attacks. The program includes oversight mechanisms designed to prevent abuse.`,
    questionStem: "The journalist and the security analyst disagree about whether",
    answerChoices: [
      { letter: "A", text: "the surveillance program could be useful for preventing terrorism" },
      { letter: "B", text: "privacy concerns about surveillance are legitimate" },
      { letter: "C", text: "the benefits of the surveillance program outweigh its costs to privacy" },
      { letter: "D", text: "surveillance powers have historically been abused" },
      { letter: "E", text: "oversight mechanisms can be designed for surveillance programs" },
    ],
    correctAnswer: "C",
    explanation: "The journalist acknowledges the program is 'potentially useful' (so not A), and the analyst calls privacy concerns 'legitimate' (so not B). Both agree surveillance can be useful and that privacy matters. They disagree on the ultimate balance: the journalist finds the privacy invasion 'unacceptable' despite the benefits, while the analyst believes national security benefits justify the privacy costs.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Art Critic: Abstract expressionist paintings, whatever their artistic merit, cannot be considered truly great art because they lack representational content. Great art must depict recognizable subjects that connect viewers to shared human experiences.

Gallery Director: Abstract expressionism represents one of the highest achievements in art history. The emotional power conveyed through color, form, and gesture speaks directly to human experience without the mediation of representational imagery. Representational content is not necessary for artistic greatness.`,
    questionStem: "The main point of disagreement between the art critic and the gallery director is whether",
    answerChoices: [
      { letter: "A", text: "abstract expressionist paintings have artistic merit" },
      { letter: "B", text: "great art must contain representational content" },
      { letter: "C", text: "abstract expressionism conveys emotional power" },
      { letter: "D", text: "shared human experiences are relevant to evaluating art" },
      { letter: "E", text: "color and form can convey meaning" },
    ],
    correctAnswer: "B",
    explanation: "The critic explicitly states great art 'must depict recognizable subjects' (must have representational content), while the director explicitly states 'representational content is not necessary for artistic greatness.' This is a direct, explicit disagreement about whether representation is required for great art. Both connect art to human experience (just differently), so D is not their point of disagreement.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Economist A: Raising the minimum wage to $15 per hour would harm the very workers it aims to help. Businesses would respond by cutting jobs or hours, leaving low-wage workers worse off. Economic theory clearly predicts this outcome.

Economist B: A $15 minimum wage would benefit low-wage workers substantially. Studies of past minimum wage increases have found little evidence of significant job losses, and workers who keep their jobs see meaningful income gains. The theoretical predictions have not been borne out empirically.`,
    questionStem: "Economist A and Economist B disagree about which one of the following?",
    answerChoices: [
      { letter: "A", text: "whether economic theory predicts job losses from minimum wage increases" },
      { letter: "B", text: "whether the minimum wage should be raised" },
      { letter: "C", text: "whether a $15 minimum wage would have a net positive effect on low-wage workers" },
      { letter: "D", text: "whether any workers would see income gains from a minimum wage increase" },
      { letter: "E", text: "whether businesses respond to increased labor costs by cutting hours" },
    ],
    correctAnswer: "C",
    explanation: "Economist A argues the wage increase would leave low-wage workers 'worse off' (net negative effect), while Economist B argues it would 'benefit low-wage workers substantially' (net positive effect). Both agree some workers might gain income—they disagree about the overall net effect when job losses are considered. A is not in dispute (both acknowledge the theory); they disagree about whether the prediction is accurate.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All licensed physicians have completed medical school. Dr. Chen is a licensed physician. Therefore, Dr. Chen has completed medical school.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All roses are flowers. This plant is a flower. Therefore, this plant is a rose." },
      { letter: "B", text: "Some athletes are wealthy. Jordan is an athlete. Therefore, Jordan might be wealthy." },
      { letter: "C", text: "All mammals are warm-blooded. Whales are mammals. Therefore, whales are warm-blooded." },
      { letter: "D", text: "No reptiles can fly. Birds can fly. Therefore, birds are not reptiles." },
      { letter: "E", text: "Most doctors are well-paid. Kim is a doctor. Therefore, Kim is probably well-paid." },
    ],
    correctAnswer: "C",
    explanation: "The original argument has the structure: All A are B, X is A, therefore X is B. This is valid deductive reasoning (affirming the antecedent with a universal premise). Answer C follows the identical structure: All mammals are warm-blooded, whales are mammals, therefore whales are warm-blooded. Answer A commits the fallacy of affirming the consequent; B and E involve probabilistic rather than universal conclusions; D involves a negative premise.",
    difficulty: "easy",
  },
  {
    id: "lr-bank29-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy improves, unemployment will decrease. Unemployment has not decreased. Therefore, the economy has not improved.`,
    questionStem: "Which one of the following arguments has a pattern of reasoning most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "If it rains, the streets will be wet. It is raining. Therefore, the streets are wet." },
      { letter: "B", text: "If the alarm sounds, there is a fire. The alarm has sounded. Therefore, there is a fire." },
      { letter: "C", text: "If a student passes all exams, the student will graduate. This student did not graduate. Therefore, this student did not pass all exams." },
      { letter: "D", text: "If interest rates fall, housing prices will rise. Interest rates have not fallen. Therefore, housing prices will not rise." },
      { letter: "E", text: "If the bridge is closed, traffic will increase on Main Street. Traffic has increased on Main Street. Therefore, the bridge is closed." },
    ],
    correctAnswer: "C",
    explanation: "The original argument uses modus tollens: If P then Q; not Q; therefore not P. This is valid reasoning. Answer C follows the same pattern: If passing all exams then graduation; no graduation; therefore no passing all exams. Answer A and B are modus ponens; D denies the antecedent (fallacy); E affirms the consequent (fallacy).",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Either the company will expand into Asian markets or it will focus on strengthening its domestic position. The company has decided not to expand into Asian markets. Therefore, the company will focus on strengthening its domestic position.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "Either the concert will be held outdoors or it will be held in the auditorium. The concert was not held in the auditorium. Therefore, the concert was held outdoors." },
      { letter: "B", text: "The play will be performed either on Friday or on Saturday. The play was performed on Friday. Therefore, the play was not performed on Saturday." },
      { letter: "C", text: "Either the museum is open today or it is a holiday. It is a holiday. Therefore, the museum is not open today." },
      { letter: "D", text: "The defendant is either guilty or innocent. The jury found the defendant guilty. Therefore, the defendant is not innocent." },
      { letter: "E", text: "Either the package will arrive today or we will need to reschedule the meeting. The package did not arrive today. Therefore, we will need to reschedule the meeting." },
    ],
    correctAnswer: "E",
    explanation: "The original argument uses disjunctive syllogism: P or Q; not P; therefore Q. Answer E follows the same pattern: package arrives or reschedule meeting; package did not arrive; therefore reschedule meeting. Answer A also uses disjunctive syllogism but negates the second option rather than the first—still valid but the order differs. Answer E is the closest parallel with the same structure of negating the first disjunct.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Every employee who completes the advanced training program receives a promotion within one year. Some employees in the marketing department have completed the advanced training program. No employee has received more than one promotion in a single year.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All employees in the marketing department will receive promotions" },
      { letter: "B", text: "Some employees in the marketing department will receive promotions within one year" },
      { letter: "C", text: "No employee in the marketing department has completed the basic training program" },
      { letter: "D", text: "Some employees who complete the advanced training program work in the marketing department" },
      { letter: "E", text: "The marketing department has the most employees who have completed the advanced training program" },
    ],
    correctAnswer: "B",
    explanation: "We know: (1) Everyone who completes advanced training gets promoted within a year, and (2) Some marketing employees have completed advanced training. It follows necessarily that some marketing employees will receive promotions within a year. Answer A is too strong (only 'some' completed training, not all). D is true but just restates a premise. B is the valid inference from combining the two premises.",
    difficulty: "medium",
  },
  {
    id: "lr-bank29-050",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `In a recent survey of consumer preferences, respondents who described themselves as environmentally conscious were more likely to purchase products with eco-friendly packaging. However, sales data from retail stores shows that products with eco-friendly packaging often sell at lower rates than conventionally packaged alternatives in the same product category.`,
    questionStem: "If the statements above are true, which one of the following can be properly inferred?",
    answerChoices: [
      { letter: "A", text: "Consumers who describe themselves as environmentally conscious are not being truthful about their preferences" },
      { letter: "B", text: "Eco-friendly packaging is more expensive than conventional packaging" },
      { letter: "C", text: "Survey responses about purchasing preferences do not always predict actual purchasing behavior" },
      { letter: "D", text: "Retailers should stop offering products with eco-friendly packaging" },
      { letter: "E", text: "Most consumers do not consider themselves environmentally conscious" },
    ],
    correctAnswer: "C",
    explanation: "The survey shows a stated preference for eco-friendly packaging among environmentally conscious consumers, but actual sales data shows these products often sell at lower rates. This gap between stated preference and actual behavior demonstrates that survey responses about purchasing preferences don't always predict actual purchasing behavior. Answer A is too strong (they might be sincere but act differently); B and E are not supported by the information given; D is a recommendation not supported by the facts.",
    difficulty: "hard",
  },
];
