// Logical Reasoning Questions Bank - Set 2
// High-quality LSAT-style questions covering all question types

import { Question } from "../lsat-types";

export const lrQuestionsSet2: Question[] = [
  // FLAW QUESTIONS
  {
    id: "lr-bank2-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Journalist: The governor claims the economy is improving because unemployment has dropped. But unemployment statistics only count people actively seeking work. Many discouraged workers have simply stopped looking for jobs. Therefore, the economy is not actually improving.`,
    questionStem: "The journalist's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider other economic indicators beyond unemployment" },
      { letter: "B", text: "assumes that discouraged workers would find jobs if they continued looking" },
      { letter: "C", text: "treats one weakness in an argument as sufficient to disprove the conclusion entirely" },
      { letter: "D", text: "presumes that the governor is intentionally being misleading" },
      { letter: "E", text: "conflates different types of unemployment statistics" },
    ],
    correctAnswer: "C",
    explanation: "The journalist shows that unemployment statistics have a limitation but concludes the economy is NOT improving. Even if unemployment data is imperfect, other indicators could support economic improvement. One weakness doesn't disprove the whole conclusion.",
    difficulty: "hard",
  },
  {
    id: "lr-bank2-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Dietician: People who eat organic food live longer than those who don't. This proves that eating organic food extends your lifespan.`,
    questionStem: "The dietician's argument is most vulnerable to criticism on which of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It assumes all organic food is equally nutritious" },
      { letter: "B", text: "It fails to specify what types of organic food were eaten" },
      { letter: "C", text: "It ignores the possibility that people who eat organic food share other health-promoting characteristics" },
      { letter: "D", text: "It does not consider that organic food is more expensive" },
      { letter: "E", text: "It relies on a small sample size" },
    ],
    correctAnswer: "C",
    explanation: "Classic correlation vs. causation flaw. People who eat organic may also exercise more, have higher incomes, better healthcare access, or be more health-conscious generally. These confounding variables could explain the longevity difference rather than organic food itself.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Politician: My opponent argues we should reduce military spending to fund education. But my opponent never served in the military, so clearly their opinion on military funding should be disregarded.`,
    questionStem: "The reasoning in the politician's argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "attacks the opponent's qualifications rather than addressing the substance of the proposal" },
      { letter: "B", text: "assumes that military experience is necessary to have valid opinions on any topic" },
      { letter: "C", text: "ignores evidence that supports the opponent's position" },
      { letter: "D", text: "presumes that education funding is not important" },
      { letter: "E", text: "fails to consider that the speaker also lacks relevant experience" },
    ],
    correctAnswer: "A",
    explanation: "This is an ad hominem fallacy. Rather than addressing whether the proposal to shift funding from military to education has merit, the politician attacks the opponent's lack of military service. A proposal's validity is independent of the proposer's background.",
    difficulty: "easy",
  },
  {
    id: "lr-bank2-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Manager: Our department's productivity increased after we instituted casual dress Fridays. Therefore, casual dress improves worker productivity.`,
    questionStem: "Which one of the following indicates a flaw in the manager's reasoning?",
    answerChoices: [
      { letter: "A", text: "The conclusion is based on evidence from only one department" },
      { letter: "B", text: "Productivity might have increased for reasons unrelated to dress code" },
      { letter: "C", text: "Not all employees may enjoy casual dress" },
      { letter: "D", text: "The manager has a personal preference for casual dress" },
      { letter: "E", text: "Productivity is difficult to measure accurately" },
    ],
    correctAnswer: "B",
    explanation: "Post hoc ergo propter hoc fallacy. Just because productivity increased after the change doesn't mean the change caused the increase. New equipment, seasonal variations, different projects, or other factors could explain the improvement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Restaurant reviewer: This restaurant received a perfect health inspection score, so the food must be delicious.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that all restaurants with perfect health scores have delicious food" },
      { letter: "B", text: "confuses safety and cleanliness standards with culinary quality" },
      { letter: "C", text: "relies on a single inspection rather than multiple inspections" },
      { letter: "D", text: "does not consider the cost of dining at the restaurant" },
      { letter: "E", text: "presumes health inspectors are experts on food taste" },
    ],
    correctAnswer: "B",
    explanation: "The argument confuses two distinct qualities. Health inspection scores measure food safety, proper storage, and cleanliness—not taste, creativity, or culinary skill. A restaurant can be perfectly safe but serve mediocre food.",
    difficulty: "easy",
  },

  // STRENGTHEN QUESTIONS
  {
    id: "lr-bank2-006",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The collapse of the Bronze Age civilizations around 1200 BCE was primarily caused by a prolonged drought. Archaeological evidence shows that agricultural production declined sharply across the Eastern Mediterranean during this period.`,
    questionStem: "Which one of the following, if true, most strengthens the historian's argument?",
    answerChoices: [
      { letter: "A", text: "Climate data from lake sediments shows significantly reduced rainfall in the region during the relevant period" },
      { letter: "B", text: "Bronze Age civilizations had advanced agricultural techniques" },
      { letter: "C", text: "Some Bronze Age cities show evidence of destruction by fire" },
      { letter: "D", text: "Population levels in the region had been increasing before the collapse" },
      { letter: "E", text: "Trade networks between Bronze Age civilizations were extensive" },
    ],
    correctAnswer: "A",
    explanation: "Independent climate evidence confirming drought directly supports the hypothesis. Lake sediment data provides proxy evidence of rainfall levels, corroborating the argument that drought caused agricultural decline and civilization collapse.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-007",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Practicing gratitude improves mental health. People who kept gratitude journals for eight weeks reported significantly lower levels of anxiety and depression than those who did not.`,
    questionStem: "Which one of the following, if true, most strengthens the psychologist's argument?",
    answerChoices: [
      { letter: "A", text: "Participants were randomly assigned to gratitude journal or control groups" },
      { letter: "B", text: "Gratitude journals are inexpensive and easy to maintain" },
      { letter: "C", text: "The participants were all adults between 25 and 45 years old" },
      { letter: "D", text: "Similar studies have been conducted in other countries" },
      { letter: "E", text: "Depression and anxiety are common mental health concerns" },
    ],
    correctAnswer: "A",
    explanation: "Random assignment rules out selection bias. If people chose which group to join, those predisposed to optimism might choose gratitude journals and show improvement regardless. Random assignment means the groups were comparable, strengthening the causal claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Environmentalist: The decline in songbird populations in North America is caused by the widespread use of neonicotinoid pesticides. These pesticides have increased dramatically in use over the same period that songbird populations have declined.`,
    questionStem: "Which one of the following, if true, most strengthens the environmentalist's argument?",
    answerChoices: [
      { letter: "A", text: "Neonicotinoid pesticides are more effective than older pesticides at controlling crop pests" },
      { letter: "B", text: "Songbirds that feed primarily on insects contaminated with neonicotinoids show the steepest population declines" },
      { letter: "C", text: "Some European countries have banned neonicotinoid pesticides" },
      { letter: "D", text: "Songbird populations also declined in the mid-20th century before rebounding" },
      { letter: "E", text: "Climate change has altered the migration patterns of many songbird species" },
    ],
    correctAnswer: "B",
    explanation: "This strengthens the causal link by showing a dose-response relationship. If birds with higher exposure (insect-eaters) show greater decline than those with less exposure, this supports the pesticide hypothesis and weakens alternative explanations.",
    difficulty: "hard",
  },
  {
    id: "lr-bank2-009",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Marketing analyst: Our social media advertising campaign has increased brand awareness. Survey data shows that 40% of consumers now recognize our brand, up from 25% before the campaign.`,
    questionStem: "Which one of the following, if true, most strengthens the analyst's conclusion?",
    answerChoices: [
      { letter: "A", text: "The company did not run any other marketing campaigns during this period" },
      { letter: "B", text: "Social media advertising is less expensive than television advertising" },
      { letter: "C", text: "The survey methodology was the same before and after the campaign" },
      { letter: "D", text: "Competing brands also increased their advertising during this period" },
      { letter: "E", text: "The company's sales have not increased significantly" },
    ],
    correctAnswer: "A",
    explanation: "If no other marketing occurred, the social media campaign is the most likely cause of increased brand recognition. This rules out alternative explanations like TV ads, sponsorships, or PR events that could have caused the improvement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-010",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Eating breakfast helps children perform better in school. Studies consistently show that children who eat breakfast score higher on tests of concentration and problem-solving than children who skip breakfast.`,
    questionStem: "Which one of the following, if true, provides the most support for the nutritionist's claim?",
    answerChoices: [
      { letter: "A", text: "The same children score better on tests administered after eating breakfast than on tests administered when they haven't eaten" },
      { letter: "B", text: "Children who eat breakfast also tend to get more sleep" },
      { letter: "C", text: "Breakfast provides essential nutrients for growing children" },
      { letter: "D", text: "Many schools now offer free breakfast programs" },
      { letter: "E", text: "Parents who provide breakfast are more likely to be involved in their children's education" },
    ],
    correctAnswer: "A",
    explanation: "Within-subject comparison controls for individual differences. Showing the same child performs better with breakfast than without isolates breakfast as the variable, unlike between-group comparisons that might reflect pre-existing differences between breakfast-eaters and skippers.",
    difficulty: "hard",
  },

  // WEAKEN QUESTIONS
  {
    id: "lr-bank2-011",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `City planner: Building a new sports stadium downtown will revitalize the urban core. Cities that have built downtown stadiums have seen increased economic activity in surrounding areas.`,
    questionStem: "Which one of the following, if true, most weakens the city planner's argument?",
    answerChoices: [
      { letter: "A", text: "The proposed stadium would be funded primarily by taxpayers" },
      { letter: "B", text: "Economic studies show stadium spending mostly displaces spending that would have occurred elsewhere in the city" },
      { letter: "C", text: "Some downtown stadiums have been criticized for their architectural design" },
      { letter: "D", text: "Professional sports teams sometimes relocate even after new stadiums are built" },
      { letter: "E", text: "Downtown parking is often limited near stadiums" },
    ],
    correctAnswer: "B",
    explanation: "If stadium spending displaces rather than creates economic activity, the 'revitalization' is illusory. Money spent at stadium events would have been spent at restaurants, theaters, or shops elsewhere. The total economic activity doesn't increase—it just moves.",
    difficulty: "hard",
  },
  {
    id: "lr-bank2-012",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Physician: Vitamin D supplements reduce the risk of respiratory infections. Patients who took vitamin D supplements had 25% fewer respiratory infections than patients who did not.`,
    questionStem: "Which one of the following, if true, most weakens the physician's argument?",
    answerChoices: [
      { letter: "A", text: "Vitamin D supplements are widely available without prescription" },
      { letter: "B", text: "Patients who chose to take supplements were generally more health-conscious and had better overall health habits" },
      { letter: "C", text: "Vitamin D is naturally produced by the body when exposed to sunlight" },
      { letter: "D", text: "Some patients experienced mild side effects from the supplements" },
      { letter: "E", text: "The study lasted only six months" },
    ],
    correctAnswer: "B",
    explanation: "Selection bias: if patients self-selected to take supplements, and those who did were already healthier with better habits, the reduced infections might reflect their overall health-consciousness rather than the supplements themselves.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-013",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `CEO: Our company's commitment to environmental sustainability has improved our profits. Since implementing our green initiatives three years ago, our profits have increased by 30%.`,
    questionStem: "Which one of the following, if true, casts the most doubt on the CEO's claim?",
    answerChoices: [
      { letter: "A", text: "Some employees were initially skeptical about the green initiatives" },
      { letter: "B", text: "The company's main competitors have not implemented similar sustainability programs" },
      { letter: "C", text: "The industry as a whole has experienced significant profit growth over the past three years" },
      { letter: "D", text: "The green initiatives required substantial initial investment" },
      { letter: "E", text: "Consumer surveys show that environmental concerns influence purchasing decisions" },
    ],
    correctAnswer: "C",
    explanation: "If the entire industry grew by a similar amount, the company's profit increase would be explained by industry-wide factors rather than the green initiatives. The comparison undermines the causal claim by providing an alternative explanation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-014",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Technology expert: Voice recognition software has become sophisticated enough to replace traditional keyboard typing. The error rate in voice recognition has dropped to just 5%, making it as accurate as average typing.`,
    questionStem: "Which one of the following, if true, most weakens the expert's conclusion?",
    answerChoices: [
      { letter: "A", text: "Voice recognition software requires expensive hardware" },
      { letter: "B", text: "Voice recognition errors often produce words that are contextually inappropriate and harder to detect than typos" },
      { letter: "C", text: "Some people speak with accents that software has difficulty processing" },
      { letter: "D", text: "Typing allows for easier editing and formatting of text" },
      { letter: "E", text: "Most office environments are not quiet enough for optimal voice recognition" },
    ],
    correctAnswer: "B",
    explanation: "Not all errors are equal. A typo like 'teh' is easy to spot and fix, but voice errors that produce real words ('their' vs 'there') may go undetected. Even at the same error rate, voice recognition errors could be more problematic, making it not a true replacement.",
    difficulty: "hard",
  },
  {
    id: "lr-bank2-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Television watching reduces children's reading ability. Studies show that children who watch more than three hours of television daily have lower reading scores than those who watch less.`,
    questionStem: "Which one of the following, if true, most seriously weakens the sociologist's argument?",
    answerChoices: [
      { letter: "A", text: "Many television programs are educational" },
      { letter: "B", text: "Children with learning difficulties may watch more television because reading is difficult for them" },
      { letter: "C", text: "Reading scores have been declining nationwide for decades" },
      { letter: "D", text: "Some children watch television while also reading" },
      { letter: "E", text: "Parents of heavy television watchers tend to watch more television themselves" },
    ],
    correctAnswer: "B",
    explanation: "This reverses the causation. If children with reading difficulties turn to television as an easier entertainment option, the correlation is explained by reading problems causing TV watching, not TV watching causing reading problems.",
    difficulty: "hard",
  },

  // NECESSARY ASSUMPTION QUESTIONS
  {
    id: "lr-bank2-016",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Publisher: Our new e-book pricing strategy will increase revenue. By lowering prices by 40%, we will more than double our sales volume, resulting in higher total revenue.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Customers prefer e-books to print books" },
      { letter: "B", text: "The production cost of e-books is negligible" },
      { letter: "C", text: "The increase in sales volume will not result in significantly higher costs" },
      { letter: "D", text: "Competitors will not lower their prices in response" },
      { letter: "E", text: "E-book sales have been declining recently" },
    ],
    correctAnswer: "C",
    explanation: "Revenue = sales minus costs. The argument claims increased total revenue from more sales. If doubling sales doubles customer service costs, payment processing fees, or other variable costs, the revenue increase might be offset. The argument assumes costs won't eat the gains.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-017",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Zoologist: The new wildlife corridor connecting the two forest preserves will help endangered lynx populations recover. Lynx need large territories, and the corridor will allow them to expand their range.`,
    questionStem: "The zoologist's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Lynx populations in both preserves are currently stable" },
      { letter: "B", text: "The wildlife corridor will be free from human development" },
      { letter: "C", text: "Lynx will actually use the corridor to move between preserves" },
      { letter: "D", text: "Other endangered species will also benefit from the corridor" },
      { letter: "E", text: "The corridor is wider than the lynx's typical territory" },
    ],
    correctAnswer: "C",
    explanation: "Negation test: if lynx won't use the corridor, it won't help them. The argument assumes the corridor will actually be used by lynx. Just building it doesn't guarantee they'll recognize and traverse it—they might avoid unfamiliar territory or face obstacles.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-018",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Music teacher: Learning to play a musical instrument improves mathematical ability. Students who take music lessons perform better in math classes than those who don't.`,
    questionStem: "Which one of the following is an assumption required by the argument?",
    answerChoices: [
      { letter: "A", text: "Musical instruments require mathematical understanding to play" },
      { letter: "B", text: "The improvement in math performance is not entirely due to factors other than music lessons" },
      { letter: "C", text: "All students who take music lessons show improvement in math" },
      { letter: "D", text: "Music teachers incorporate mathematical concepts into their instruction" },
      { letter: "E", text: "Students who are good at math are not more likely to take music lessons" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that music lessons cause math improvement. It must assume the correlation isn't entirely explained by confounding factors like parental involvement, general cognitive ability, or socioeconomic advantages that lead to both music lessons and math success.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-019",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Food critic: This restaurant deserves its three-star rating. The chef has won numerous culinary awards, and the menu features innovative dishes using premium ingredients.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "three-star ratings are the highest possible rating" },
      { letter: "B", text: "culinary awards and ingredient quality are relevant to restaurant ratings" },
      { letter: "C", text: "other three-star restaurants have similar characteristics" },
      { letter: "D", text: "the restaurant has been open for at least one year" },
      { letter: "E", text: "premium ingredients are always better than standard ingredients" },
    ],
    correctAnswer: "B",
    explanation: "The argument uses awards and ingredient quality as reasons for the rating. It must assume these factors are actually relevant to how restaurants should be rated. If ratings were based on service or ambiance instead, the evidence wouldn't support the conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-020",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Financial advisor: You should invest in index funds rather than actively managed funds. Index funds have lower fees, and after accounting for fees, most actively managed funds do not outperform index funds.`,
    questionStem: "The advisor's recommendation depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Index funds never lose money" },
      { letter: "B", text: "It is impossible to identify in advance which actively managed funds will outperform" },
      { letter: "C", text: "All index funds have the same fee structure" },
      { letter: "D", text: "Actively managed funds require more investor involvement" },
      { letter: "E", text: "Past performance of funds predicts future performance" },
    ],
    correctAnswer: "B",
    explanation: "The advisor notes most active funds underperform. But if one could identify the winners in advance, active funds might still be preferable. The advice assumes you can't reliably pick the outperforming active funds, making index funds the better default choice.",
    difficulty: "hard",
  },

  // INFERENCE QUESTIONS
  {
    id: "lr-bank2-021",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Every member of the debate team has won at least one award. No member of the debate team is also on the basketball team. Some students who have won awards are on the basketball team.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Some students on the basketball team have not won any awards" },
      { letter: "B", text: "Some students who have won awards are not on either team" },
      { letter: "C", text: "No student on the basketball team has won as many awards as any debate team member" },
      { letter: "D", text: "Some award winners are not on the debate team" },
      { letter: "E", text: "The debate team has more members than the basketball team" },
    ],
    correctAnswer: "D",
    explanation: "Some award winners are on the basketball team. No debate team members are on the basketball team. Therefore, the basketball-playing award winners cannot be on the debate team. Thus, some award winners are not on the debate team.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-022",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Professor Kim only gives A grades to students who attend every class and submit every assignment. Marcus received an A in Professor Kim's class. Several students who submitted every assignment did not receive an A.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Marcus attended every class and submitted every assignment" },
      { letter: "B", text: "Some students who attended every class did not submit every assignment" },
      { letter: "C", text: "Marcus was the only student who received an A" },
      { letter: "D", text: "Some students who submitted every assignment did not attend every class" },
      { letter: "E", text: "Attending every class is more important than submitting every assignment" },
    ],
    correctAnswer: "A",
    explanation: "The first statement gives a necessary condition: A grade → attended all AND submitted all. Marcus got an A, so by necessity he met both conditions. This is contrapositive reasoning applied to the individual case.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-023",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The committee will approve the project only if it meets all safety standards. The project does not meet the environmental review requirement, which is one of the safety standards.`,
    questionStem: "Which one of the following can be properly inferred from the statements above?",
    answerChoices: [
      { letter: "A", text: "The committee will not approve the project" },
      { letter: "B", text: "The project fails to meet multiple safety standards" },
      { letter: "C", text: "Environmental reviews are the most important safety standard" },
      { letter: "D", text: "The project will eventually meet all safety standards" },
      { letter: "E", text: "The committee has rejected similar projects in the past" },
    ],
    correctAnswer: "A",
    explanation: "Approval requires meeting ALL safety standards. Environmental review is a safety standard. The project doesn't meet environmental review. Therefore, it doesn't meet all safety standards. Therefore, the committee will not approve it.",
    difficulty: "easy",
  },
  {
    id: "lr-bank2-024",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All of the paintings in the main gallery are from the 19th century. Some of the paintings in the main gallery are landscapes. None of the portraits in the museum are from the 19th century.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "None of the paintings in the main gallery are portraits" },
      { letter: "B", text: "All landscapes in the museum are from the 19th century" },
      { letter: "C", text: "Some 19th century paintings are not in the main gallery" },
      { letter: "D", text: "The museum has more landscapes than portraits" },
      { letter: "E", text: "All 19th century paintings in the museum are in the main gallery" },
    ],
    correctAnswer: "A",
    explanation: "All main gallery paintings are from the 19th century. No portraits are from the 19th century. Therefore, no portraits can be in the main gallery (if they were, they'd have to be 19th century, but no portraits are).",
    difficulty: "hard",
  },
  {
    id: "lr-bank2-025",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The library is open until 9 PM on weekdays and until 5 PM on weekends. Today is Saturday, and it is currently 4 PM.`,
    questionStem: "Which one of the following can be properly concluded from the information above?",
    answerChoices: [
      { letter: "A", text: "The library will close in exactly one hour" },
      { letter: "B", text: "The library is currently open" },
      { letter: "C", text: "The library opens later on weekends than on weekdays" },
      { letter: "D", text: "The library was open at 3 PM today" },
      { letter: "E", text: "The library will be open for four more hours tomorrow" },
    ],
    correctAnswer: "B",
    explanation: "Saturday is a weekend day. The library is open until 5 PM on weekends. It is currently 4 PM. Since 4 PM is before 5 PM, the library is currently open. We cannot determine opening times, so we can't conclude C or D for certain.",
    difficulty: "easy",
  },

  // SUFFICIENT ASSUMPTION QUESTIONS
  {
    id: "lr-bank2-026",
    type: "sufficient-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The scholarship will be awarded to whoever has the highest GPA. Jamie has a 4.0 GPA. Therefore, Jamie will receive the scholarship.`,
    questionStem: "The conclusion follows logically if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "A 4.0 GPA is a perfect score" },
      { letter: "B", text: "No other applicant has a GPA as high as Jamie's" },
      { letter: "C", text: "Jamie applied for the scholarship" },
      { letter: "D", text: "GPA is the most important factor in scholarship decisions" },
      { letter: "E", text: "Jamie has maintained a 4.0 GPA throughout college" },
    ],
    correctAnswer: "B",
    explanation: "The scholarship goes to the highest GPA. Jamie has 4.0. To conclude Jamie wins, we need to assume no one else has 4.0 or higher—i.e., Jamie's GPA is highest. Answer C is tempting but irrelevant if not applying would disqualify Jamie entirely (implicit).",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-027",
    type: "sufficient-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Employees who receive positive performance reviews are eligible for bonuses. Chen is eligible for a bonus. Therefore, Chen received a positive performance review.`,
    questionStem: "The conclusion is properly drawn if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "Chen is the only employee eligible for a bonus" },
      { letter: "B", text: "All employees who are eligible for bonuses received positive performance reviews" },
      { letter: "C", text: "Chen's performance exceeded expectations" },
      { letter: "D", text: "Bonuses are only given for exceptional performance" },
      { letter: "E", text: "The performance review process is fair and objective" },
    ],
    correctAnswer: "B",
    explanation: "We know: positive review → eligible for bonus. Chen is eligible. To conclude Chen had a positive review, we need the converse or something that makes eligibility sufficient for having had a positive review. B states: eligible → positive review, completing the logic.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-028",
    type: "sufficient-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All licensed contractors must carry liability insurance. Henderson Construction is based in this state. Therefore, Henderson Construction carries liability insurance.`,
    questionStem: "The conclusion would be properly drawn if which one of the following were assumed?",
    answerChoices: [
      { letter: "A", text: "Henderson Construction performs work outside this state" },
      { letter: "B", text: "Henderson Construction is a licensed contractor" },
      { letter: "C", text: "All construction companies in this state are licensed contractors" },
      { letter: "D", text: "Liability insurance is required for all businesses in this state" },
      { letter: "E", text: "Henderson Construction has never had an insurance claim" },
    ],
    correctAnswer: "B",
    explanation: "We know licensed contractors must have insurance. We know Henderson is in this state (but that's irrelevant to the logical structure). We need to know Henderson is a licensed contractor to apply the rule. B provides exactly this premise.",
    difficulty: "easy",
  },
  {
    id: "lr-bank2-029",
    type: "sufficient-assumption",
    sectionType: "logical-reasoning",
    stimulus: `We should not adopt this policy. Any policy that would harm the most vulnerable members of society should not be adopted.`,
    questionStem: "The conclusion follows logically if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "This policy has been tried before and failed" },
      { letter: "B", text: "This policy would harm the most vulnerable members of society" },
      { letter: "C", text: "No policy can help everyone equally" },
      { letter: "D", text: "The most vulnerable members of society oppose this policy" },
      { letter: "E", text: "This policy would benefit some members of society" },
    ],
    correctAnswer: "B",
    explanation: "The principle states: harms vulnerable → should not adopt. The conclusion is: should not adopt this policy. The missing link is: this policy harms vulnerable. B provides exactly this premise, allowing the conclusion to follow.",
    difficulty: "easy",
  },
  {
    id: "lr-bank2-030",
    type: "sufficient-assumption",
    sectionType: "logical-reasoning",
    stimulus: `If the train is delayed, we will miss the connecting flight. We will catch the connecting flight. Therefore, the train was not delayed.`,
    questionStem: "The pattern of reasoning in the argument above is valid. What logical principle does it demonstrate?",
    answerChoices: [
      { letter: "A", text: "Affirming the consequent" },
      { letter: "B", text: "Denying the antecedent" },
      { letter: "C", text: "Modus ponens" },
      { letter: "D", text: "Modus tollens" },
      { letter: "E", text: "Hypothetical syllogism" },
    ],
    correctAnswer: "D",
    explanation: "Modus tollens: If P then Q; not Q; therefore not P. Here: If delayed then miss flight; didn't miss flight; therefore not delayed. We deny the consequent (missing the flight) to conclude the denial of the antecedent (the train being delayed).",
    difficulty: "medium",
  },

  // RESOLVE PARADOX QUESTIONS
  {
    id: "lr-bank2-031",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `Although the city's population has decreased by 15% over the past decade, traffic congestion during rush hour has become significantly worse.`,
    questionStem: "Which one of the following, if true, most helps to resolve the apparent paradox?",
    answerChoices: [
      { letter: "A", text: "Public transportation ridership has also decreased over the past decade" },
      { letter: "B", text: "Many businesses have relocated from the city center to suburbs that are accessible only by car" },
      { letter: "C", text: "The city has improved many of its major roadways" },
      { letter: "D", text: "Housing prices in the city have increased despite the population decline" },
      { letter: "E", text: "The city has implemented new traffic light timing systems" },
    ],
    correctAnswer: "B",
    explanation: "If jobs moved to car-only suburbs, fewer people live in the city but more people drive through it for work. The remaining population plus suburban commuters could create more rush-hour traffic than the larger but more self-contained previous population.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-032",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `A study found that patients who received a new experimental drug showed no greater recovery rate than patients who received a placebo. However, the pharmaceutical company maintains that the drug is effective.`,
    questionStem: "Which one of the following, if true, most helps to reconcile the study results with the company's position?",
    answerChoices: [
      { letter: "A", text: "The study was conducted by independent researchers" },
      { letter: "B", text: "The placebo effect was unusually strong in this study because patients believed they were receiving a promising new treatment" },
      { letter: "C", text: "Some patients in the drug group experienced side effects" },
      { letter: "D", text: "The company has invested heavily in developing the drug" },
      { letter: "E", text: "Similar drugs from other companies have also shown mixed results" },
    ],
    correctAnswer: "B",
    explanation: "If the placebo group showed unusually high recovery rates because of heightened expectations, both groups might show similar rates while the drug is actually effective. The drug works, but the placebo group's belief-driven improvement masked the drug's advantage.",
    difficulty: "hard",
  },
  {
    id: "lr-bank2-033",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `Bookstore sales of printed books have declined steadily over the past five years. Yet the number of bookstores has actually increased during the same period.`,
    questionStem: "Which one of the following, if true, most helps to explain the discrepancy?",
    answerChoices: [
      { letter: "A", text: "Online retailers now sell a large portion of all printed books" },
      { letter: "B", text: "Many new bookstores have diversified to sell coffee, gifts, and host events, relying less on book sales for revenue" },
      { letter: "C", text: "E-book sales have increased significantly over the past five years" },
      { letter: "D", text: "The overall reading population has remained relatively stable" },
      { letter: "E", text: "Some independent bookstores have developed strong customer loyalty" },
    ],
    correctAnswer: "B",
    explanation: "If bookstores no longer depend primarily on book sales, they can survive and even proliferate despite declining book sales. Coffee shops, event venues, and gift stores that happen to also sell books can succeed when pure bookstores might fail.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-034",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `A poll showed that 80% of residents support building a new community center, but the ballot measure to fund the center was defeated by a 60% majority.`,
    questionStem: "Which one of the following, if true, most helps to explain the discrepancy?",
    answerChoices: [
      { letter: "A", text: "The poll was conducted by telephone and may not have reached all residents" },
      { letter: "B", text: "The ballot measure would have funded the center through a property tax increase" },
      { letter: "C", text: "Similar measures have been defeated in neighboring communities" },
      { letter: "D", text: "Voter turnout for the election was lower than usual" },
      { letter: "E", text: "The proposed community center would be built on the site of a popular park" },
    ],
    correctAnswer: "B",
    explanation: "People can support a project in principle but oppose a specific funding mechanism. If the ballot measure required a property tax increase, residents might support the center but vote against having to pay for it through higher taxes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-035",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `Experienced chess players often perform worse than beginners when the chess pieces are randomly placed rather than in strategic positions.`,
    questionStem: "Which one of the following, if true, most helps to explain the finding?",
    answerChoices: [
      { letter: "A", text: "Experienced players have more knowledge of chess openings" },
      { letter: "B", text: "Beginners are more likely to make random moves" },
      { letter: "C", text: "Experienced players rely heavily on pattern recognition that is disrupted by random positions" },
      { letter: "D", text: "Chess tournaments never feature randomly placed pieces" },
      { letter: "E", text: "Beginners spend more time analyzing each potential move" },
    ],
    correctAnswer: "C",
    explanation: "Expert chess players develop pattern recognition—they 'see' positions as meaningful chunks rather than individual pieces. Random positions disrupt this advantage, while beginners who analyze piece-by-piece aren't affected. Experts' strength becomes a weakness.",
    difficulty: "hard",
  },

  // METHOD OF REASONING QUESTIONS
  {
    id: "lr-bank2-036",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Skeptic: You claim that this herbal remedy cures headaches, but you've provided no controlled studies supporting this claim. Personal testimonials prove nothing because people often feel better regardless of treatment due to the placebo effect and natural recovery.`,
    questionStem: "The skeptic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "demonstrating that the remedy is actually harmful" },
      { letter: "B", text: "questioning the adequacy of the evidence offered for the claim" },
      { letter: "C", text: "providing alternative evidence that contradicts the original claim" },
      { letter: "D", text: "showing that the person making the claim is not a medical expert" },
      { letter: "E", text: "arguing that all herbal remedies are ineffective" },
    ],
    correctAnswer: "B",
    explanation: "The skeptic doesn't claim the remedy fails or provide contrary evidence. Rather, they argue that the evidence offered (testimonials) is inadequate because testimonials can't distinguish between real effects and placebo/natural recovery. This is challenging evidence quality.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-037",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution claims my client was at the scene of the crime. But my client was seen by three witnesses at a restaurant across town at the time of the crime. Since my client cannot be in two places at once, he could not have been at the scene.`,
    questionStem: "The defense attorney's argument relies on which method of reasoning?",
    answerChoices: [
      { letter: "A", text: "Attacking the credibility of the prosecution's witnesses" },
      { letter: "B", text: "Establishing an alibi that is logically incompatible with guilt" },
      { letter: "C", text: "Suggesting an alternative suspect for the crime" },
      { letter: "D", text: "Challenging the reliability of eyewitness testimony in general" },
      { letter: "E", text: "Arguing that the prosecution has failed to prove motive" },
    ],
    correctAnswer: "B",
    explanation: "The attorney provides evidence that the client was elsewhere, then uses the logical impossibility of being in two places at once to conclude the client couldn't have been at the crime scene. This is establishing an alibi through logical incompatibility.",
    difficulty: "easy",
  },
  {
    id: "lr-bank2-038",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Environmentalist: Critics say that banning plastic straws won't solve the ocean plastic problem because straws represent less than 1% of ocean plastic. But this argument could be applied to every individual plastic product. By that logic, we should never ban any single plastic product, and therefore do nothing about plastic pollution at all.`,
    questionStem: "The environmentalist responds to the critics by",
    answerChoices: [
      { letter: "A", text: "providing evidence that plastic straws cause more harm than critics acknowledge" },
      { letter: "B", text: "showing that the critics' reasoning leads to an unacceptable conclusion" },
      { letter: "C", text: "questioning the accuracy of the statistics cited by critics" },
      { letter: "D", text: "arguing that symbolic actions have value beyond their direct impact" },
      { letter: "E", text: "demonstrating that straws are the most practical type of plastic to ban" },
    ],
    correctAnswer: "B",
    explanation: "This is a reductio ad absurdum. The environmentalist shows that the critics' logic, if consistently applied, would prohibit any individual action against plastic pollution—an absurd conclusion. Therefore, the reasoning must be flawed.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Manager: We should not hire any more marketing staff this quarter. Our marketing budget is already stretched thin, and adding staff without increasing the budget would reduce the resources available per person, likely decreasing overall productivity rather than increasing it.`,
    questionStem: "The manager's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "presenting evidence that current marketing staff are underperforming" },
      { letter: "B", text: "predicting that a proposed action would have counterproductive results" },
      { letter: "C", text: "comparing the company's marketing strategy to that of competitors" },
      { letter: "D", text: "appealing to company policy regarding staffing decisions" },
      { letter: "E", text: "questioning whether marketing is important to the company's success" },
    ],
    correctAnswer: "B",
    explanation: "The manager argues against hiring by predicting negative consequences: more staff with the same budget would stretch resources thinner and reduce per-person productivity. This is arguing against a proposal by forecasting counterproductive outcomes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank2-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that free will is an illusion because all our decisions are determined by prior brain states. But consider: if free will is truly an illusion, then the person making this argument had no choice but to make it, and we have no choice but to accept or reject it. The very act of arguing presupposes the reality of free choice.`,
    questionStem: "The philosopher's argumentative strategy is to",
    answerChoices: [
      { letter: "A", text: "provide neuroscientific evidence supporting the existence of free will" },
      { letter: "B", text: "show that denying free will is self-undermining because it relies on what it denies" },
      { letter: "C", text: "define free will in a way that makes it compatible with determinism" },
      { letter: "D", text: "argue that the consequences of believing in determinism are harmful" },
      { letter: "E", text: "claim that the question of free will cannot be answered by science" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher argues that making arguments presupposes choice—you choose your words, premises, and conclusions. If determinism denies all choice, then the argument for determinism undermines itself by relying on what it claims doesn't exist.",
    difficulty: "hard",
  },

  // PARALLEL REASONING QUESTIONS
  {
    id: "lr-bank2-041",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Only citizens can vote in federal elections. Maria is not a citizen. Therefore, Maria cannot vote in federal elections.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to which one of the following?",
    answerChoices: [
      { letter: "A", text: "Only members can use the pool. Chen is not a member. Therefore, Chen cannot use the pool." },
      { letter: "B", text: "All managers must attend the meeting. Rodriguez is a manager. Therefore, Rodriguez must attend the meeting." },
      { letter: "C", text: "Some professors have tenure. Dr. Park is a professor. Therefore, Dr. Park might have tenure." },
      { letter: "D", text: "If it rains, the event will be cancelled. The event was not cancelled. Therefore, it did not rain." },
      { letter: "E", text: "Only birds can fly. Bats can fly. Therefore, bats are birds." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments have the form: Only P can Q. X is not P. Therefore, X cannot Q. 'Only citizens can vote' means being a citizen is necessary for voting. Not meeting the necessary condition means the conclusion cannot occur.",
    difficulty: "easy",
  },
  {
    id: "lr-bank2-042",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Either the delivery arrived today or it will arrive tomorrow. The delivery did not arrive today. So it will arrive tomorrow.`,
    questionStem: "Which one of the following most closely parallels the reasoning in the argument above?",
    answerChoices: [
      { letter: "A", text: "Either the train is late or it has been cancelled. The train is late. So it has not been cancelled." },
      { letter: "B", text: "Either Tom or Lisa will present first. Tom will not present first. So Lisa will present first." },
      { letter: "C", text: "If it's cold, I'll wear a jacket. It's cold. So I'll wear a jacket." },
      { letter: "D", text: "Either Alex passed or failed. Alex passed. So Alex did not fail." },
      { letter: "E", text: "Either all or none of the students will attend. Some students will attend. So all students will attend." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments use disjunctive syllogism with exclusive or: Either P or Q; not P; therefore Q. The original: either today or tomorrow, not today, so tomorrow. B: either Tom or Lisa, not Tom, so Lisa. A affirms one disjunct, which is different.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-043",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If a restaurant serves seafood, it must pass monthly health inspections. Riverside Grill does not pass monthly health inspections. Therefore, Riverside Grill does not serve seafood.`,
    questionStem: "Which one of the following arguments is most similar in its pattern of reasoning to the argument above?",
    answerChoices: [
      { letter: "A", text: "If a car is electric, it needs no oil changes. This car needs oil changes. Therefore, this car is not electric." },
      { letter: "B", text: "If a building is historic, it cannot be demolished. This building can be demolished. Therefore, this building is historic." },
      { letter: "C", text: "If an employee works overtime, they receive extra pay. Smith received extra pay. Therefore, Smith worked overtime." },
      { letter: "D", text: "If a product is defective, it should be recalled. This product is defective. Therefore, this product should be recalled." },
      { letter: "E", text: "If you study hard, you will succeed. You succeeded. Therefore, you studied hard." },
    ],
    correctAnswer: "A",
    explanation: "Both use modus tollens: If P then Q; not Q; therefore not P. Original: If seafood, then monthly inspections; no monthly inspections; therefore no seafood. A: If electric, then no oil changes; needs oil changes; therefore not electric.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-044",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some doctors are researchers. All researchers publish papers. Therefore, some doctors publish papers.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some athletes are students. Some students receive scholarships. Therefore, some athletes receive scholarships." },
      { letter: "B", text: "Some musicians are composers. All composers understand music theory. Therefore, some musicians understand music theory." },
      { letter: "C", text: "All lawyers are professionals. Some professionals are wealthy. Therefore, all lawyers are wealthy." },
      { letter: "D", text: "Some teachers are strict. Some strict people are unpopular. Therefore, some teachers are unpopular." },
      { letter: "E", text: "All birds are animals. All animals need food. Therefore, all birds need food." },
    ],
    correctAnswer: "B",
    explanation: "Pattern: Some A are B. All B are C. Therefore, some A are C. Original: Some doctors are researchers, all researchers publish, so some doctors publish. B: Some musicians are composers, all composers know theory, so some musicians know theory.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-045",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Every great leader has faced significant challenges. Lincoln faced significant challenges. Therefore, Lincoln was a great leader.`,
    questionStem: "The flawed reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All champions train daily. Jordan trains daily. Therefore, Jordan is a champion." },
      { letter: "B", text: "No successful person gives up easily. Martinez doesn't give up easily. Therefore, Martinez is successful." },
      { letter: "C", text: "Every genius thinks creatively. Not everyone who thinks creatively is a genius. Therefore, some creative thinkers are not geniuses." },
      { letter: "D", text: "All diamonds are hard. This stone is hard. Therefore, this stone is a diamond." },
      { letter: "E", text: "Every doctor has medical training. Anderson has medical training. Therefore, Anderson might be a doctor." },
    ],
    correctAnswer: "D",
    explanation: "Both commit affirming the consequent: All A are B; X is B; therefore X is A. Original: All great leaders faced challenges; Lincoln faced challenges; therefore Lincoln was a great leader. D: All diamonds are hard; stone is hard; therefore stone is a diamond.",
    difficulty: "medium",
  },

  // PRINCIPLE QUESTIONS
  {
    id: "lr-bank2-046",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: Actions are morally praiseworthy only if they are performed out of a sense of duty rather than self-interest.\n\nApplication: Although Jackson donated millions to charity, his actions are not morally praiseworthy.`,
    questionStem: "The application of the principle is most justified if which one of the following is true?",
    answerChoices: [
      { letter: "A", text: "Jackson could have donated more than he did" },
      { letter: "B", text: "Jackson made the donations primarily to improve his public image" },
      { letter: "C", text: "The charities Jackson donated to were not well-known" },
      { letter: "D", text: "Other wealthy individuals have made similar donations" },
      { letter: "E", text: "Jackson's donations helped many people in need" },
    ],
    correctAnswer: "B",
    explanation: "The principle requires actions be done from duty, not self-interest, to be praiseworthy. If Jackson donated primarily for reputation (self-interest), not from a sense of duty, then per the principle his donations aren't praiseworthy—even though they had good effects.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-047",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: A promise should be kept unless keeping it would cause more harm than breaking it.`,
    questionStem: "Which one of the following judgments most closely conforms to the principle above?",
    answerChoices: [
      { letter: "A", text: "Chen promised to keep a secret but told the secret because doing so was entertaining at a party" },
      { letter: "B", text: "Martinez promised to attend a meeting but didn't attend because she forgot about it" },
      { letter: "C", text: "Park promised to return a friend's knife but instead turned it over to police when he learned the friend planned to harm someone" },
      { letter: "D", text: "Williams promised to lend money but refused when he discovered the borrower would use it for gambling" },
      { letter: "E", text: "Thompson promised to be honest but lied to avoid hurting a friend's feelings about her new haircut" },
    ],
    correctAnswer: "C",
    explanation: "The principle permits breaking promises only when keeping them causes more harm. Park's situation fits: keeping the promise (returning the knife) would enable serious harm to someone. Breaking the promise by involving police prevents greater harm.",
    difficulty: "medium",
  },
  {
    id: "lr-bank2-048",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: Companies should not collect personal data from users unless that data is necessary for providing the service the user requested.`,
    questionStem: "Which one of the following company practices violates the principle?",
    answerChoices: [
      { letter: "A", text: "A GPS app collecting location data to provide navigation directions" },
      { letter: "B", text: "A shopping website collecting payment information for purchases" },
      { letter: "C", text: "A weather app collecting browsing history to sell to advertisers" },
      { letter: "D", text: "A medical portal collecting health information for patient care" },
      { letter: "E", text: "An email service collecting recipient addresses to send messages" },
    ],
    correctAnswer: "C",
    explanation: "The principle prohibits collecting unnecessary data. A, B, D, and E collect data directly necessary for their services. But browsing history is not necessary for providing weather information—it's collected for advertising purposes, violating the principle.",
    difficulty: "easy",
  },
  {
    id: "lr-bank2-049",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: An action that has good consequences can still be morally wrong if the person performing it intended to cause harm.`,
    questionStem: "Which one of the following situations best illustrates the principle?",
    answerChoices: [
      { letter: "A", text: "A doctor performs surgery that saves a patient's life but causes permanent scarring" },
      { letter: "B", text: "A thief steals from a corrupt company, inadvertently exposing fraud that helps investors" },
      { letter: "C", text: "A driver accidentally runs over debris on the road, clearing it for other drivers" },
      { letter: "D", text: "A competitor sabotages a rival's product, but the recall leads to safety improvements" },
      { letter: "E", text: "A student cheats on an exam but later learns the material thoroughly" },
    ],
    correctAnswer: "D",
    explanation: "The principle says good outcomes don't make harmful intentions moral. D fits perfectly: the sabotage was intended to cause harm (morally wrong), but coincidentally led to safety improvements (good consequences). The good outcome doesn't justify the malicious intent.",
    difficulty: "hard",
  },
  {
    id: "lr-bank2-050",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: You should give priority to helping those closest to you before helping strangers, other things being equal.`,
    questionStem: "Which one of the following actions is most consistent with the principle?",
    answerChoices: [
      { letter: "A", text: "Donating to an international charity rather than helping a struggling neighbor" },
      { letter: "B", text: "Volunteering at a local school rather than sending money to schools abroad" },
      { letter: "C", text: "Refusing to help a family member because you disagree with their choices" },
      { letter: "D", text: "Helping a stranger in immediate danger rather than a friend with a minor problem" },
      { letter: "E", text: "Giving equal amounts to local and international causes" },
    ],
    correctAnswer: "B",
    explanation: "The principle prioritizes helping those closer to you when other factors are equal. B shows prioritizing local (closer) help over distant help. D involves unequal situations (emergency vs. minor problem). C refuses to help family, contrary to the principle.",
    difficulty: "medium",
  },
];
