// Logical Reasoning Questions Bank - Set 68
import { Question } from "../lsat-types";

export const lrQuestionsSet68: Question[] = [
  {
    id: "lr-bank68-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent survey found that 80 percent of employees who work from home report higher job satisfaction than those who work in an office. Therefore, companies should allow all employees to work from home in order to maximize overall job satisfaction.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that job satisfaction is the only factor relevant to company productivity" },
      { letter: "B", text: "fails to consider that employees who chose to work from home may have had higher job satisfaction to begin with" },
      { letter: "C", text: "overlooks the possibility that some employees prefer working in an office" },
      { letter: "D", text: "relies on a survey that may not have been conducted properly" },
      { letter: "E", text: "does not define what constitutes job satisfaction" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits a selection bias flaw. Employees who currently work from home likely chose that arrangement because it suits them, so their higher satisfaction may not indicate that all employees would be equally satisfied working from home.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martinez has argued that the university should increase funding for the arts program. However, Professor Martinez teaches in the arts department and would directly benefit from such an increase. Therefore, her argument should be dismissed.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that Professor Martinez's motives are purely self-interested" },
      { letter: "B", text: "attacks the source of an argument rather than addressing its merits" },
      { letter: "C", text: "fails to consider that the arts program may genuinely need more funding" },
      { letter: "D", text: "presumes that professors cannot make objective assessments about their own departments" },
      { letter: "E", text: "ignores evidence that might support increased arts funding" },
    ],
    correctAnswer: "B",
    explanation: "This is an ad hominem fallacy. The argument attacks Professor Martinez's potential bias rather than evaluating the actual reasons she may have provided for increasing arts funding. A person's potential conflict of interest does not automatically invalidate their argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-003",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers found that patients who received the experimental drug showed a 40 percent reduction in symptoms compared to those who received a placebo. The researchers concluded that the drug is effective at treating the condition.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "The experimental drug has been approved for use in treating similar conditions" },
      { letter: "B", text: "Neither the patients nor the researchers knew who received the drug and who received the placebo" },
      { letter: "C", text: "The drug has minimal side effects compared to existing treatments" },
      { letter: "D", text: "Patients in the study were all diagnosed with severe forms of the condition" },
      { letter: "E", text: "The placebo used in the study was identical in appearance to the actual drug" },
    ],
    correctAnswer: "B",
    explanation: "A double-blind study design (where neither patients nor researchers know who receives treatment) eliminates bias from both expectations and researcher interpretation, strengthening the validity of the observed effect.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-004",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `City officials argue that the new traffic light system has reduced accidents at major intersections by 25 percent. They point to accident data from the six months after installation compared to the same period the previous year as evidence of the system's success.`,
    questionStem: "Which one of the following, if true, most weakens the officials' argument?",
    answerChoices: [
      { letter: "A", text: "Some intersections without the new system also showed reduced accidents" },
      { letter: "B", text: "The new traffic light system was significantly more expensive than the previous system" },
      { letter: "C", text: "During the comparison period, a major highway was closed for construction, reducing overall traffic volume by 30 percent" },
      { letter: "D", text: "The previous traffic light system was over 20 years old" },
      { letter: "E", text: "Not all drivers are aware that the traffic light system has been changed" },
    ],
    correctAnswer: "C",
    explanation: "If overall traffic volume decreased by 30 percent due to highway construction, the reduction in accidents could be attributable to fewer cars on the road rather than to the effectiveness of the new traffic light system.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-005",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All successful entrepreneurs possess exceptional risk tolerance. Maria has started three businesses, each of which has been profitable. Therefore, Maria must have exceptional risk tolerance.`,
    questionStem: "The conclusion follows logically if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "Risk tolerance is the only trait needed for entrepreneurial success" },
      { letter: "B", text: "Anyone who starts a profitable business is a successful entrepreneur" },
      { letter: "C", text: "Maria started her businesses with the intention of making a profit" },
      { letter: "D", text: "Most entrepreneurs who take risks are eventually successful" },
      { letter: "E", text: "Exceptional risk tolerance guarantees business success" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'Maria has started profitable businesses' to 'Maria is a successful entrepreneur' to 'Maria has exceptional risk tolerance.' For this reasoning to work, the argument must assume that having profitable businesses makes one a successful entrepreneur.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-006",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some legal scholars argue that mandatory minimum sentences reduce judicial discretion unfairly. But judges sometimes impose sentences that are far too lenient for serious crimes. Without mandatory minimums, there would be no guarantee of consistent punishment for similar offenses. Clearly, mandatory minimum sentences serve an important function in ensuring justice is applied uniformly.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Mandatory minimum sentences reduce judicial discretion unfairly" },
      { letter: "B", text: "Judges sometimes impose sentences that are too lenient" },
      { letter: "C", text: "Without mandatory minimums, punishment would be inconsistent" },
      { letter: "D", text: "Mandatory minimum sentences play an important role in ensuring uniform justice" },
      { letter: "E", text: "Legal scholars are wrong to criticize mandatory minimum sentences" },
    ],
    correctAnswer: "D",
    explanation: "The phrase 'Clearly' signals the main conclusion. The argument builds a case for why mandatory minimums are beneficial (preventing lenient sentences, ensuring consistency) and concludes they serve an important function in uniform justice application.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-007",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The museum director claims that the new abstract art exhibit will attract more visitors than any previous exhibit. But the director made similar claims about the last three exhibits, and attendance for each was below projections. There is no reason to believe this prediction will be any more accurate.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "questioning the reliability of the evidence used to support the director's claim" },
      { letter: "B", text: "demonstrating that the director's past predictions have been consistently inaccurate" },
      { letter: "C", text: "arguing that abstract art is less popular than the director assumes" },
      { letter: "D", text: "suggesting that museum attendance is impossible to predict accurately" },
      { letter: "E", text: "pointing out that the director has a financial interest in making optimistic predictions" },
    ],
    correctAnswer: "B",
    explanation: "The critic undermines the director's current prediction by establishing a pattern of the director's past predictions being wrong. This is an attack on the director's track record as a predictor.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every member of the city council who voted against the housing development project received campaign contributions from environmental groups. Therefore, the council members who voted against the project did so because of these contributions rather than because of genuine environmental concerns.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that campaign contributions always influence voting behavior" },
      { letter: "B", text: "overlooks the possibility that environmental groups contributed to council members who share their values" },
      { letter: "C", text: "fails to consider that some council members may have had other reasons for opposing the project" },
      { letter: "D", text: "does not establish that the contributions were made before the vote" },
      { letter: "E", text: "ignores the possibility that the housing development had no environmental impact" },
    ],
    correctAnswer: "B",
    explanation: "The argument confuses correlation with causation. Environmental groups likely contributed to candidates who already shared their environmental values, so the contributions did not necessarily cause the votes—both the contributions and the votes may stem from shared genuine environmental concerns.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-009",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have discovered that ancient settlements in the region were abandoned around 1200 BCE. Soil analysis shows significant salt deposits in agricultural areas dating to that period. The archaeologists hypothesize that over-irrigation led to soil salinization, making farming impossible and forcing inhabitants to leave.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologists' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Similar patterns of soil salinization and abandonment have been documented in other ancient agricultural societies" },
      { letter: "B", text: "The region experienced a period of drought around 1200 BCE" },
      { letter: "C", text: "Artifacts found at the sites indicate that the inhabitants were skilled farmers" },
      { letter: "D", text: "No evidence of warfare or invasion has been found at the abandoned settlements" },
      { letter: "E", text: "The settlements were located near rivers that could provide water for irrigation" },
    ],
    correctAnswer: "A",
    explanation: "Evidence that the same pattern (irrigation leading to salinization leading to abandonment) occurred in other ancient societies supports the hypothesis by showing this is a documented phenomenon with precedent.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Countries that invest heavily in education consistently have higher rates of economic growth. Therefore, the best way for developing nations to achieve economic growth is to significantly increase education spending.`,
    questionStem: "Which one of the following, if true, most seriously weakens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Some developing nations have limited resources to devote to education" },
      { letter: "B", text: "Economic growth typically provides the additional tax revenue that funds increased education spending" },
      { letter: "C", text: "Not all types of education spending are equally effective at promoting economic growth" },
      { letter: "D", text: "Some developed nations have recently reduced their education budgets" },
      { letter: "E", text: "Private education can be as effective as public education in promoting economic development" },
    ],
    correctAnswer: "B",
    explanation: "This suggests reverse causation: rather than education spending causing economic growth, economic growth causes increased education spending. If the causal direction is reversed, simply increasing education spending would not necessarily lead to growth.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-011",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The proposed legislation would require all food products to display clear nutritional labels. Since consumers who understand the nutritional content of foods make healthier purchasing decisions, this legislation will improve public health.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "All consumers are capable of understanding nutritional labels" },
      { letter: "B", text: "Consumers will actually read the nutritional labels on food products" },
      { letter: "C", text: "Nutritional labels are more effective than other forms of health education" },
      { letter: "D", text: "Food manufacturers will accurately report nutritional information" },
      { letter: "E", text: "Current food labeling is inadequate for consumer needs" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that consumers will read the labels. Even if labels help those who read them make better choices, if consumers ignore the labels entirely, the legislation would not improve public health.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Hayes: Artificial intelligence will eventually surpass human intelligence in all domains. As computational power increases, there is no task that machines will not be able to perform better than humans.

Dr. Patel: While AI excels at specific tasks, genuine intelligence requires consciousness and subjective experience. Machines process information but do not truly understand or experience anything, so they cannot achieve real intelligence.`,
    questionStem: "The main point at issue between Dr. Hayes and Dr. Patel is whether",
    answerChoices: [
      { letter: "A", text: "computational power will continue to increase in the future" },
      { letter: "B", text: "machines can perform specific tasks better than humans" },
      { letter: "C", text: "consciousness is necessary for genuine intelligence" },
      { letter: "D", text: "AI has made significant advances in recent years" },
      { letter: "E", text: "human intelligence is limited in certain domains" },
    ],
    correctAnswer: "C",
    explanation: "Dr. Hayes believes that task performance equals intelligence, while Dr. Patel argues that true intelligence requires consciousness and subjective experience that machines lack. They disagree about whether consciousness is a necessary component of intelligence.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All licensed physicians must complete continuing education requirements. Dr. Chen has not completed her continuing education requirements this year. Therefore, Dr. Chen is not currently a licensed physician.`,
    questionStem: "Which one of the following exhibits a pattern of reasoning most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All members of the orchestra must attend rehearsals. Jenkins attends all rehearsals. Therefore, Jenkins is a member of the orchestra." },
      { letter: "B", text: "All certified accountants must pass the licensing exam. Thompson has not passed the licensing exam. Therefore, Thompson is not a certified accountant." },
      { letter: "C", text: "All employees must submit timesheets. Garcia submitted her timesheet. Therefore, Garcia is an employee." },
      { letter: "D", text: "All voters must be registered. Many citizens are registered. Therefore, many citizens are voters." },
      { letter: "E", text: "All managers must approve expenses. No expenses were approved. Therefore, there are no managers." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow the pattern: All X must do Y. Z has not done Y. Therefore, Z is not X. This is a valid application of modus tollens (denying the consequent).",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-014",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Studies show that students who eat breakfast perform better on standardized tests than students who skip breakfast. Therefore, schools should provide free breakfast to all students to improve test scores.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider the cost of providing free breakfast" },
      { letter: "B", text: "assumes that what is true of some students is true of all students" },
      { letter: "C", text: "overlooks the possibility that factors correlated with eating breakfast, rather than breakfast itself, explain the better performance" },
      { letter: "D", text: "does not specify what types of breakfast foods would be provided" },
      { letter: "E", text: "ignores the possibility that some students have dietary restrictions" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes breakfast causes better performance, but the correlation might be explained by confounding factors. Students who eat breakfast may come from more stable homes, have better sleep habits, or have other advantages that actually explain their better performance.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company argues that its new medication for chronic pain is safer than existing alternatives because clinical trials showed fewer side effects. The company recommends that doctors prescribe this new medication to patients currently using older pain medications.`,
    questionStem: "Which one of the following, if true, most strengthens the company's recommendation?",
    answerChoices: [
      { letter: "A", text: "The new medication is more expensive than existing alternatives" },
      { letter: "B", text: "The clinical trials included patients with various types of chronic pain conditions" },
      { letter: "C", text: "Long-term studies confirmed that the reduced side effects persist over extended use" },
      { letter: "D", text: "The company has developed other successful medications in the past" },
      { letter: "E", text: "Some patients in the trials reported that the medication was easy to take" },
    ],
    correctAnswer: "C",
    explanation: "Since chronic pain requires long-term treatment, evidence that the safety benefits persist over extended use directly supports recommending the new medication for ongoing patient care.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-016",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The decline of the Roman Empire was primarily caused by moral decay among its citizens. Historical accounts describe increasing decadence and corruption in Roman society during the centuries leading to the empire's fall.`,
    questionStem: "Which one of the following, if true, most seriously weakens the historian's argument?",
    answerChoices: [
      { letter: "A", text: "Some Roman emperors attempted to implement moral reforms" },
      { letter: "B", text: "Similar accounts of moral decay were written during earlier periods when the empire was thriving" },
      { letter: "C", text: "The definition of moral behavior has changed significantly since Roman times" },
      { letter: "D", text: "Other ancient empires also experienced periods of moral decline" },
      { letter: "E", text: "Modern historians have access to more Roman texts than earlier scholars" },
    ],
    correctAnswer: "B",
    explanation: "If accounts of moral decay also appear during Rome's thriving periods, then such accounts cannot be reliable evidence that moral decay specifically caused the decline. The correlation between moral decay descriptions and decline may be coincidental.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-017",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city's new recycling program will be successful because residents strongly support environmental initiatives. A recent survey found that 75 percent of residents believe recycling is important for environmental protection.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "recycling is the most effective way to protect the environment" },
      { letter: "B", text: "residents who believe recycling is important will actually participate in the recycling program" },
      { letter: "C", text: "the survey accurately measured residents' attitudes toward recycling" },
      { letter: "D", text: "75 percent participation is sufficient for the program to be successful" },
      { letter: "E", text: "previous recycling programs in other cities have been successful" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'residents believe recycling is important' to 'the program will be successful.' This requires assuming that belief in the importance of recycling will translate into actual participation in the program.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-018",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Critics of social media argue that it decreases face-to-face interaction. However, research indicates that people who use social media frequently also engage in more in-person social activities. Furthermore, social media enables people to maintain relationships across distances that would otherwise fade. Social media therefore actually enhances rather than diminishes social connection.`,
    questionStem: "The main conclusion of the argument is that",
    answerChoices: [
      { letter: "A", text: "social media users engage in more in-person activities" },
      { letter: "B", text: "critics of social media are misinformed" },
      { letter: "C", text: "social media helps maintain long-distance relationships" },
      { letter: "D", text: "social media improves rather than harms social connection" },
      { letter: "E", text: "research on social media contradicts popular assumptions" },
    ],
    correctAnswer: "D",
    explanation: "The word 'therefore' signals the conclusion. The argument presents evidence (frequent users have more in-person activities, social media maintains distant relationships) to support the conclusion that social media enhances social connection.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-019",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some argue that the minimum wage should not be increased because it would lead to job losses. But when the minimum wage was last increased, employment levels actually rose. Therefore, we should not assume that increasing the minimum wage will cause job losses.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing a counterexample to challenge a general claim" },
      { letter: "B", text: "showing that a predicted consequence did not occur" },
      { letter: "C", text: "arguing that past trends will continue in the future" },
      { letter: "D", text: "questioning the motives of those who oppose minimum wage increases" },
      { letter: "E", text: "demonstrating that minimum wage increases benefit workers" },
    ],
    correctAnswer: "B",
    explanation: "The argument counters the claim that minimum wage increases cause job losses by pointing to a specific instance where this predicted consequence did not occur—employment rose after the last increase.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-020",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Novelist: My latest book has received mixed reviews from critics. However, it has sold over one million copies in just three months. Clearly, critics are out of touch with what readers actually want, and their reviews should be disregarded.`,
    questionStem: "The novelist's argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "assumes that commercial success is the only measure of a book's quality" },
      { letter: "B", text: "fails to consider that critics may have valid aesthetic concerns despite the book's popularity" },
      { letter: "C", text: "does not provide evidence about what specific criticisms were made" },
      { letter: "D", text: "overlooks the role of marketing in book sales" },
      { letter: "E", text: "presumes that all critics share the same opinions" },
    ],
    correctAnswer: "B",
    explanation: "The novelist equates popularity with quality and dismisses critics entirely because the book sold well. However, a book can be popular for reasons unrelated to the qualities critics evaluate, and critical assessments may still have merit regardless of sales figures.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-021",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `The law firm implemented a four-day workweek for all employees while maintaining full salaries. After six months, the firm reported a 20 percent increase in productivity. The firm's management concluded that compressed work schedules improve employee output.`,
    questionStem: "Which one of the following, if true, most strengthens the management's conclusion?",
    answerChoices: [
      { letter: "A", text: "Employees reported higher job satisfaction under the new schedule" },
      { letter: "B", text: "Similar productivity gains were observed when other companies adopted four-day workweeks" },
      { letter: "C", text: "The firm did not hire additional employees during the six-month period" },
      { letter: "D", text: "Client satisfaction remained high during the trial period" },
      { letter: "E", text: "The firm's competitors continue to use traditional five-day schedules" },
    ],
    correctAnswer: "B",
    explanation: "Evidence that other companies experienced similar productivity gains from four-day workweeks supports the conclusion that the schedule change itself, rather than some factor unique to this firm, improves employee output.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Political scientist: Voter turnout in local elections has declined significantly over the past two decades. This decline is primarily due to increasing voter apathy. When citizens stop caring about political outcomes, they stop participating in the democratic process.`,
    questionStem: "Which one of the following, if true, most weakens the political scientist's explanation?",
    answerChoices: [
      { letter: "A", text: "National election turnout has remained relatively stable over the same period" },
      { letter: "B", text: "Surveys show that citizens who do not vote in local elections often cite practical barriers such as inconvenient polling times and locations" },
      { letter: "C", text: "Some local jurisdictions have experimented with online voting" },
      { letter: "D", text: "Local elections typically receive less media coverage than national elections" },
      { letter: "E", text: "Voter registration requirements vary significantly across jurisdictions" },
    ],
    correctAnswer: "B",
    explanation: "If non-voters cite practical barriers rather than lack of interest, this suggests that declining turnout may be due to logistical obstacles rather than voter apathy, directly challenging the political scientist's explanation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-023",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of embezzlement because embezzlement requires intent to permanently deprive the owner of property. The defendant always intended to return the money once his investment scheme paid off.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The defendant's investment scheme was likely to succeed" },
      { letter: "B", text: "Intent to temporarily take property does not constitute embezzlement" },
      { letter: "C", text: "The defendant actually took money from the owner" },
      { letter: "D", text: "The defendant has no history of financial crimes" },
      { letter: "E", text: "The owner did not give permission for the money to be used" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims the defendant is not guilty because he intended to return the money (temporary deprivation). This reasoning only works if temporary deprivation does not satisfy the legal definition of embezzlement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-024",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the executive committee must have at least ten years of experience in the industry. Some members of the executive committee have advanced degrees in business administration. Every person with an advanced degree in business administration has studied financial management.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All members of the executive committee have studied financial management" },
      { letter: "B", text: "Some people with ten years of industry experience have studied financial management" },
      { letter: "C", text: "Everyone who has studied financial management has an advanced business degree" },
      { letter: "D", text: "Some people with advanced business degrees are not on the executive committee" },
      { letter: "E", text: "All people who have studied financial management are on the executive committee" },
    ],
    correctAnswer: "B",
    explanation: "Some executive committee members have advanced business degrees, and all people with such degrees have studied financial management. All committee members have ten years of experience. Therefore, some people with ten years of experience (those committee members with advanced degrees) have studied financial management.",
    difficulty: "hard",
  },
  {
    id: "lr-bank68-025",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist A: Wealthy nations have a moral obligation to provide humanitarian aid to developing countries. Those with resources should help those without, as this reduces suffering and promotes global equality.

Ethicist B: While helping others is admirable, wealthy nations should prioritize their own citizens' needs first. Redirecting resources abroad when domestic problems persist is ethically questionable.`,
    questionStem: "Ethicist A and Ethicist B disagree about whether",
    answerChoices: [
      { letter: "A", text: "humanitarian aid reduces suffering in developing countries" },
      { letter: "B", text: "wealthy nations have resources that could be used for aid" },
      { letter: "C", text: "wealthy nations are morally required to prioritize foreign aid over domestic concerns" },
      { letter: "D", text: "domestic problems exist in wealthy nations" },
      { letter: "E", text: "it is sometimes admirable to help others" },
    ],
    correctAnswer: "C",
    explanation: "Ethicist A argues that wealthy nations have a moral obligation to provide aid abroad, while Ethicist B argues that domestic needs should take priority. They disagree about the relative moral weight of foreign aid versus domestic obligations.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-026",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The proposal to ban single-use plastic bags has been endorsed by several major environmental organizations. These organizations have consistently advocated for environmental protection over the past fifty years. Therefore, banning single-use plastic bags must be beneficial for the environment.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that organizations with good track records are never wrong" },
      { letter: "B", text: "fails to consider alternative methods of reducing plastic waste" },
      { letter: "C", text: "does not evaluate the specific environmental impact of plastic bag bans" },
      { letter: "D", text: "appeals to the authority of the organizations rather than the evidence for the proposal" },
      { letter: "E", text: "ignores the possibility that plastic bags have some beneficial uses" },
    ],
    correctAnswer: "D",
    explanation: "The argument relies on the credibility of environmental organizations rather than examining the actual evidence about whether banning plastic bags would benefit the environment. This is an appeal to authority fallacy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-027",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Early childhood experiences significantly influence adult personality development. Children who experience consistent emotional support develop more secure attachment styles, which in turn leads to healthier adult relationships.`,
    questionStem: "Which one of the following, if true, most strengthens the psychologist's claim?",
    answerChoices: [
      { letter: "A", text: "Adults who report childhood emotional support score higher on measures of relationship satisfaction" },
      { letter: "B", text: "Personality traits remain relatively stable throughout adulthood" },
      { letter: "C", text: "Longitudinal studies tracking children into adulthood show strong correlations between early emotional support and later secure attachment" },
      { letter: "D", text: "Many adults cannot accurately remember their childhood experiences" },
      { letter: "E", text: "Some children are more resilient to negative early experiences than others" },
    ],
    correctAnswer: "C",
    explanation: "Longitudinal studies following the same individuals from childhood to adulthood provide the strongest evidence for a causal connection between early emotional support and later attachment styles, directly supporting the psychologist's claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-028",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Company executives argue that their generous parental leave policy attracts top talent. They point out that since implementing the policy three years ago, applications from highly qualified candidates have increased by 50 percent.`,
    questionStem: "Which one of the following, if true, most weakens the executives' argument?",
    answerChoices: [
      { letter: "A", text: "Some competitors have also implemented parental leave policies" },
      { letter: "B", text: "The company simultaneously increased salaries and expanded to new markets where it had not previously recruited" },
      { letter: "C", text: "The parental leave policy applies to all employees regardless of tenure" },
      { letter: "D", text: "Not all highly qualified candidates end up accepting job offers from the company" },
      { letter: "E", text: "The cost of the parental leave policy has exceeded initial projections" },
    ],
    correctAnswer: "B",
    explanation: "If the company also increased salaries and expanded to new recruiting markets, the increase in qualified applicants could be attributed to these factors rather than the parental leave policy, undermining the claimed causal connection.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Recent discoveries of ancient human remains in South America date to approximately 15,000 years ago. Since humans are believed to have migrated from Asia across the Bering land bridge, which was passable 15,000 years ago, these discoveries confirm the established timeline of human migration to the Americas.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The dating of the remains is accurate" },
      { letter: "B", text: "Humans migrating from the Bering land bridge could have reached South America within a very short time period" },
      { letter: "C", text: "No earlier human remains will be discovered in the Americas" },
      { letter: "D", text: "The Bering land bridge was the only route by which humans could have reached the Americas" },
      { letter: "E", text: "Human migration patterns have remained consistent throughout history" },
    ],
    correctAnswer: "B",
    explanation: "For 15,000-year-old South American remains to confirm migration via a land bridge passable 15,000 years ago, the argument must assume that humans could have traveled from the bridge to South America essentially instantly, which is the hidden assumption being made.",
    difficulty: "hard",
  },
  {
    id: "lr-bank68-030",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some people claim that artistic talent is entirely innate. But consider child prodigies in music: even the most talented require years of intensive practice to develop their abilities. Natural aptitude provides a foundation, but skill development requires dedicated effort.`,
    questionStem: "The argument employs which one of the following methods of reasoning?",
    answerChoices: [
      { letter: "A", text: "Using a specific example to challenge an absolute claim" },
      { letter: "B", text: "Establishing a general principle from multiple observations" },
      { letter: "C", text: "Demonstrating that a phenomenon has multiple causes" },
      { letter: "D", text: "Appealing to expert testimony to support a conclusion" },
      { letter: "E", text: "Showing that a concept is internally contradictory" },
    ],
    correctAnswer: "A",
    explanation: "The argument challenges the absolute claim that talent is 'entirely innate' by using the specific example of child prodigies who still need practice, showing that even exceptional natural talent requires development through effort.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Many successful technology companies were started in garages. My cousin has been working on a technology project in his garage for the past year. Therefore, my cousin's project is likely to become a successful technology company.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "generalizes from an unrepresentative sample of technology companies" },
      { letter: "B", text: "confuses a necessary condition with a sufficient condition for success" },
      { letter: "C", text: "overlooks the fact that many garage projects fail" },
      { letter: "D", text: "assumes that past trends will continue into the future" },
      { letter: "E", text: "fails to define what constitutes a successful technology company" },
    ],
    correctAnswer: "C",
    explanation: "The argument focuses on successful companies started in garages but ignores the base rate—many more garage projects fail than succeed. Starting in a garage is not a reliable predictor of success; it's simply where some successful companies happened to begin.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Marine biologists have observed that coral reefs near coastal cities exhibit significantly more bleaching than reefs in remote locations. They hypothesize that urban water pollution is a major contributor to coral reef degradation.`,
    questionStem: "Which one of the following, if true, most strengthens the marine biologists' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Coral bleaching has been observed in reefs around the world" },
      { letter: "B", text: "Water samples from areas near cities show elevated levels of pollutants known to harm coral" },
      { letter: "C", text: "Some coral species are more resistant to bleaching than others" },
      { letter: "D", text: "Remote reefs are generally located in cooler waters" },
      { letter: "E", text: "Coastal cities have grown significantly in recent decades" },
    ],
    correctAnswer: "B",
    explanation: "Evidence that water near cities contains elevated levels of pollutants specifically known to harm coral directly supports the hypothesis that urban pollution causes coral bleaching, by establishing both the presence of pollutants and their harmful effects.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-033",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Editorial: The city should convert its bus fleet from diesel to electric vehicles. While electric buses have a higher upfront cost, the long-term savings in fuel and maintenance make them more economical over the life of the vehicles.`,
    questionStem: "Which one of the following, if true, most weakens the editorial's argument?",
    answerChoices: [
      { letter: "A", text: "Electric vehicle technology continues to improve each year" },
      { letter: "B", text: "The city's electricity grid relies primarily on fossil fuel power plants" },
      { letter: "C", text: "Battery replacement costs for electric buses are substantial and battery life is shorter than the expected lifespan of the buses" },
      { letter: "D", text: "Other cities have successfully transitioned to electric bus fleets" },
      { letter: "E", text: "Diesel fuel prices have been relatively stable in recent years" },
    ],
    correctAnswer: "C",
    explanation: "If electric buses require expensive battery replacements during their lifespan, this additional cost undermines the claim that electric buses are more economical over the life of the vehicles, directly weakening the economic argument for conversion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The mayor argues that the new sports stadium will generate millions of dollars in economic activity for the city. Local restaurants, hotels, and shops near the stadium will see increased business from visitors attending events. Therefore, the city should invest public funds in building the stadium.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The economic benefits of the stadium will outweigh the public investment required to build it" },
      { letter: "B", text: "Local businesses support the construction of the stadium" },
      { letter: "C", text: "Other cities have benefited economically from building sports stadiums" },
      { letter: "D", text: "The stadium will host events throughout the year" },
      { letter: "E", text: "Public funds are available for stadium construction" },
    ],
    correctAnswer: "A",
    explanation: "The argument moves from 'the stadium will generate economic activity' to 'the city should invest public funds.' This requires assuming the economic benefits will exceed the investment, otherwise the investment would not be justified.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-035",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy enters a recession, unemployment will rise. If unemployment rises, consumer spending will decrease. Therefore, if the economy enters a recession, consumer spending will decrease.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If it rains, the ground gets wet. The ground is wet. Therefore, it rained." },
      { letter: "B", text: "If the temperature drops below freezing, the pipes will freeze. If the pipes freeze, they may burst. Therefore, if the temperature drops below freezing, the pipes may burst." },
      { letter: "C", text: "All cats are mammals. All mammals are warm-blooded. Therefore, all cats are warm-blooded." },
      { letter: "D", text: "Either the package was delivered or it was lost. The package was not delivered. Therefore, it was lost." },
      { letter: "E", text: "If traffic is heavy, I will be late. I was not late. Therefore, traffic was not heavy." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow a hypothetical syllogism pattern: If A then B; If B then C; Therefore, if A then C. This is a valid chain of conditional reasoning.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-036",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Laboratory studies have shown that high doses of a particular vitamin can slow cancer cell growth in mice. Therefore, people who take supplements of this vitamin will reduce their risk of developing cancer.`,
    questionStem: "The argument is most vulnerable to criticism on which of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It assumes that what is effective at high doses is also effective at lower doses" },
      { letter: "B", text: "It generalizes from mouse studies to human outcomes without justification" },
      { letter: "C", text: "It confuses preventing cancer with slowing cancer cell growth" },
      { letter: "D", text: "It overlooks potential side effects of vitamin supplementation" },
      { letter: "E", text: "All of the above are significant flaws in the argument" },
    ],
    correctAnswer: "E",
    explanation: "The argument commits multiple flaws: it applies mouse study results to humans, it equates slowing cancer growth with preventing cancer, and it assumes supplement doses will have the same effect as high laboratory doses. All listed criticisms are valid.",
    difficulty: "hard",
  },
  {
    id: "lr-bank68-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some philosophers argue that free will is incompatible with determinism. However, we hold people morally responsible for their actions every day. If we did not believe people could have acted otherwise, such responsibility would make no sense. Since our practices of moral responsibility are coherent and justified, we must reject strict determinism.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Free will is incompatible with determinism" },
      { letter: "B", text: "We hold people morally responsible for their actions" },
      { letter: "C", text: "Moral responsibility requires the ability to act otherwise" },
      { letter: "D", text: "We must reject strict determinism" },
      { letter: "E", text: "Our practices of moral responsibility are coherent and justified" },
    ],
    correctAnswer: "D",
    explanation: "The argument builds from premises about moral responsibility (we practice it, it requires free will, it is justified) to reach the conclusion that strict determinism must be rejected. The phrase 'we must reject' signals the conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-038",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Opposing counsel argues that my client cannot be held liable because she was following standard industry practices. But the fact that an entire industry engages in negligent behavior does not excuse any individual participant. Standard practice can still be negligent practice.`,
    questionStem: "The speaker responds to opposing counsel by",
    answerChoices: [
      { letter: "A", text: "questioning whether the client actually followed standard practices" },
      { letter: "B", text: "arguing that the industry standard has recently changed" },
      { letter: "C", text: "challenging the assumption that conformity to industry practice precludes liability" },
      { letter: "D", text: "presenting evidence that the industry has a history of negligence" },
      { letter: "E", text: "suggesting that the client was aware of the negligent nature of the practice" },
    ],
    correctAnswer: "C",
    explanation: "The speaker attacks the underlying assumption in opposing counsel's argument—that following industry practices shields one from liability. The speaker argues that industry-wide negligence doesn't excuse individual negligence.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-039",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The painting attributed to the 17th-century Dutch master shows technical characteristics inconsistent with his other works. The brushwork is unusually rough, and the composition lacks his typical precision. I believe this painting is the work of a lesser-known contemporary who imitated his style.`,
    questionStem: "Which one of the following, if true, would most strengthen the art historian's conclusion?",
    answerChoices: [
      { letter: "A", text: "The painting was acquired by a collector who specialized in Dutch masters" },
      { letter: "B", text: "Chemical analysis of the paint shows it is consistent with materials available in the 17th century" },
      { letter: "C", text: "Documents from the period mention a specific artist known for producing imitations of the Dutch master's work" },
      { letter: "D", text: "The painting was not documented in the Dutch master's workshop records" },
      { letter: "E", text: "Other art historians have expressed skepticism about the attribution" },
    ],
    correctAnswer: "C",
    explanation: "Historical documentation that a specific artist was known for imitating this Dutch master's style supports the hypothesis that the painting is an imitation rather than an original, directly strengthening the art historian's conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-040",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Nutrition researcher: Our study found that participants who followed a Mediterranean diet for one year showed improved cardiovascular health markers compared to their baseline measurements. This demonstrates that the Mediterranean diet is effective at improving heart health.`,
    questionStem: "Which one of the following, if true, most weakens the researcher's conclusion?",
    answerChoices: [
      { letter: "A", text: "Some participants found the Mediterranean diet difficult to follow consistently" },
      { letter: "B", text: "The Mediterranean diet has been associated with other health benefits beyond cardiovascular health" },
      { letter: "C", text: "Participants who did not change their diet but increased their exercise showed similar improvements in cardiovascular markers" },
      { letter: "D", text: "The study did not measure participants' overall caloric intake" },
      { letter: "E", text: "Previous studies on the Mediterranean diet had smaller sample sizes" },
    ],
    correctAnswer: "C",
    explanation: "If similar cardiovascular improvements occurred in people who only exercised more without changing their diet, this suggests that factors other than the Mediterranean diet specifically might explain the improvements, weakening the causal claim about the diet.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-041",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new policy requires all visitors to store large bags in lockers before entering the galleries. This policy will reduce the risk of accidental damage to artworks, since visitors with large bags are more likely to bump into displays.`,
    questionStem: "The argument's conclusion depends on assuming that",
    answerChoices: [
      { letter: "A", text: "visitors will comply with the new bag storage policy" },
      { letter: "B", text: "small bags cannot cause damage to artworks" },
      { letter: "C", text: "the lockers are large enough to accommodate various bag sizes" },
      { letter: "D", text: "visitors prefer to carry large bags when visiting museums" },
      { letter: "E", text: "other museums have successfully implemented similar policies" },
    ],
    correctAnswer: "A",
    explanation: "The policy can only reduce damage if visitors actually follow it. If visitors ignore the policy and bring large bags into galleries anyway, the risk of damage would not be reduced. Compliance is therefore a necessary assumption.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-042",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher X: Knowledge requires certainty. If you cannot be absolutely certain of something, you do not truly know it—you merely believe it.

Philosopher Y: That standard is impossibly high. We can have genuine knowledge even when some small possibility of error remains. What matters is having strong evidence and justified true belief.`,
    questionStem: "The point at issue between Philosopher X and Philosopher Y is whether",
    answerChoices: [
      { letter: "A", text: "belief is a component of knowledge" },
      { letter: "B", text: "evidence is relevant to knowledge claims" },
      { letter: "C", text: "absolute certainty is required for genuine knowledge" },
      { letter: "D", text: "truth is objective or subjective" },
      { letter: "E", text: "some beliefs are more justified than others" },
    ],
    correctAnswer: "C",
    explanation: "Philosopher X argues that knowledge requires absolute certainty, while Philosopher Y argues that knowledge is possible without absolute certainty. They directly disagree about whether certainty is a necessary condition for knowledge.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-043",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Recent polls show that 60 percent of voters support stricter regulations on the financial industry. Therefore, the legislature should immediately pass the proposed financial regulation bill that has been under consideration.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that what the majority supports is necessarily good policy" },
      { letter: "B", text: "fails to establish that the specific bill under consideration reflects what voters support" },
      { letter: "C", text: "does not consider the views of the 40 percent who oppose stricter regulation" },
      { letter: "D", text: "relies on polls which may not accurately represent voter sentiment" },
      { letter: "E", text: "overlooks the complexity of financial regulation" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from general support for 'stricter regulations' to support for a specific bill. Voters might support stricter regulation in principle but not support this particular bill's approach. The argument fails to connect general sentiment to the specific legislation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-044",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All of the company's senior managers attended the leadership retreat. The leadership retreat focused exclusively on developing strategic planning skills. No employees who lack strategic planning skills are eligible for promotion to executive positions.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All senior managers are eligible for promotion to executive positions" },
      { letter: "B", text: "Everyone who attended the leadership retreat is a senior manager" },
      { letter: "C", text: "All senior managers have been exposed to training on strategic planning skills" },
      { letter: "D", text: "Anyone who develops strategic planning skills will be promoted" },
      { letter: "E", text: "Executive positions require attendance at leadership retreats" },
    ],
    correctAnswer: "C",
    explanation: "All senior managers attended the retreat, and the retreat focused exclusively on developing strategic planning skills. Therefore, all senior managers have been exposed to strategic planning training. Note that this does not guarantee they developed the skills or are eligible for promotion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-045",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Social media has fundamentally changed how people form and maintain relationships. Unlike previous generations, young adults today maintain larger networks of acquaintances but report fewer close friendships. I contend that the quantity of connections has come at the expense of their depth.`,
    questionStem: "Which one of the following, if true, most strengthens the sociologist's contention?",
    answerChoices: [
      { letter: "A", text: "Young adults spend an average of three hours per day on social media platforms" },
      { letter: "B", text: "Studies show that time spent on social media correlates negatively with time spent in face-to-face interactions, which are essential for developing close friendships" },
      { letter: "C", text: "Previous generations relied on letters and phone calls to maintain long-distance relationships" },
      { letter: "D", text: "Some young adults report that social media has helped them reconnect with old friends" },
      { letter: "E", text: "The definition of friendship has varied across different cultures and time periods" },
    ],
    correctAnswer: "B",
    explanation: "This directly supports the claim that quantity comes at the expense of depth by showing that social media time reduces face-to-face interaction, and that face-to-face interaction is necessary for close friendships.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-046",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Company spokesperson: Our new factory will bring economic prosperity to this rural community. Once we begin operations, we will employ 500 local residents, and those workers will spend their wages at local businesses, stimulating the entire regional economy.`,
    questionStem: "Which one of the following, if true, most seriously weakens the spokesperson's argument?",
    answerChoices: [
      { letter: "A", text: "The factory will produce goods primarily for export to other regions" },
      { letter: "B", text: "Some local residents have expressed concerns about potential environmental impacts" },
      { letter: "C", text: "The jobs at the factory require specialized technical skills that few local residents currently possess, necessitating recruitment from outside the region" },
      { letter: "D", text: "The company has built similar factories in other rural communities" },
      { letter: "E", text: "The factory will operate around the clock in three shifts" },
    ],
    correctAnswer: "C",
    explanation: "If the jobs require skills that local residents lack, the company will need to hire workers from outside the region. These workers may not live locally or spend their wages locally, undermining the predicted economic benefits for the community.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-047",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The symphony orchestra should prioritize performing works by contemporary composers. Classical music attendance is declining, particularly among younger audiences. By programming more new music, the orchestra can attract younger listeners and ensure its long-term survival.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Contemporary compositions are of equal artistic quality to classical masterworks" },
      { letter: "B", text: "Younger audiences are more interested in contemporary music than in traditional classical repertoire" },
      { letter: "C", text: "The orchestra has access to scores of contemporary compositions" },
      { letter: "D", text: "Declining attendance is the orchestra's most serious problem" },
      { letter: "E", text: "Other orchestras have successfully attracted younger audiences with contemporary programming" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims that programming contemporary music will attract younger listeners. This reasoning requires assuming that younger audiences actually prefer contemporary music to traditional classical works—otherwise, the programming change wouldn't attract them.",
    difficulty: "medium",
  },
  {
    id: "lr-bank68-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No responsible pet owner would leave their animal in a hot car. Jenkins left his dog in a hot car. Therefore, Jenkins is not a responsible pet owner.`,
    questionStem: "The pattern of reasoning in the argument is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All good teachers explain concepts clearly. Dr. Smith explains concepts clearly. Therefore, Dr. Smith is a good teacher." },
      { letter: "B", text: "No honest person would cheat on their taxes. Martinez cheated on his taxes. Therefore, Martinez is not an honest person." },
      { letter: "C", text: "Some athletes train every day. Jones is an athlete. Therefore, Jones might train every day." },
      { letter: "D", text: "All squares have four sides. This shape has four sides. Therefore, this shape is a square." },
      { letter: "E", text: "If it rains, the game will be canceled. It did not rain. Therefore, the game was not canceled." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow the pattern: No X would do Y. Z did Y. Therefore, Z is not X. This is a valid form of reasoning using the contrapositive of a universal negative statement.",
    difficulty: "easy",
  },
  {
    id: "lr-bank68-049",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The ancient Egyptians built the pyramids without modern construction equipment. Therefore, the construction techniques they used must have been simple enough for anyone to replicate today.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that the Egyptians may have had sophisticated techniques that have been lost" },
      { letter: "B", text: "assumes that ancient civilizations were less intelligent than modern people" },
      { letter: "C", text: "overlooks the possibility that the pyramids were not built by Egyptians" },
      { letter: "D", text: "does not specify which pyramids are being discussed" },
      { letter: "E", text: "confuses the absence of modern equipment with the absence of complex methods" },
    ],
    correctAnswer: "E",
    explanation: "The argument wrongly equates 'without modern equipment' with 'simple techniques.' The Egyptians could have used highly sophisticated methods, organization, and knowledge even without modern technology. Lack of modern tools does not imply simplicity.",
    difficulty: "hard",
  },
  {
    id: "lr-bank68-050",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Technological progress often eliminates certain jobs. However, throughout history, new technologies have consistently created more jobs than they destroyed by enabling entirely new industries. Those who fear that automation will lead to mass unemployment are therefore likely mistaken, as they underestimate the economy's capacity to generate new forms of employment.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Technological progress eliminates certain jobs" },
      { letter: "B", text: "New technologies create more jobs than they destroy" },
      { letter: "C", text: "Fears about automation causing mass unemployment are probably unfounded" },
      { letter: "D", text: "The economy can generate new forms of employment" },
      { letter: "E", text: "Automation will not eliminate any jobs" },
    ],
    correctAnswer: "C",
    explanation: "The word 'therefore' signals the conclusion. The argument uses the historical pattern of technology creating more jobs than it destroys to conclude that current fears about automation causing mass unemployment are likely mistaken.",
    difficulty: "easy",
  },
];
