// Logical Reasoning Questions Bank - Set 36
import { Question } from "../lsat-types";

export const lrQuestionsSet36: Question[] = [
  {
    id: "lr-bank36-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular lunch breaks are more productive than those who eat at their desks. Therefore, companies should mandate that all employees take lunch breaks away from their workstations to maximize overall productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that what is true of some employees is true of all employees" },
      { letter: "B", text: "confuses correlation with causation" },
      { letter: "C", text: "relies on an inappropriate sample size" },
      { letter: "D", text: "ignores the costs of implementing the proposed policy" },
      { letter: "E", text: "fails to consider alternative explanations for the study's findings" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that taking lunch breaks causes increased productivity, when the study only shows a correlation. It could be that more productive employees simply tend to take breaks, or that a third factor causes both.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that the new stadium will benefit all residents because it will increase property values in the surrounding neighborhoods. However, the council members themselves own property near the proposed stadium site. Clearly, their support for the stadium is motivated purely by self-interest, and the stadium will not actually benefit the general public.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "attacks the character of the council members rather than addressing their argument" },
      { letter: "B", text: "assumes that increased property values never benefit the general public" },
      { letter: "C", text: "fails to consider that the council members might have multiple motivations" },
      { letter: "D", text: "presumes that self-interested actions cannot also benefit others" },
      { letter: "E", text: "ignores evidence that similar stadiums have benefited other communities" },
    ],
    correctAnswer: "A",
    explanation: "This is an ad hominem fallacy. The argument attacks the council members' motivations rather than addressing whether their claim about increased property values benefiting residents is actually true or false.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every successful entrepreneur I have interviewed credits hard work as the primary factor in their success. Therefore, anyone who works hard enough will become a successful entrepreneur.`,
    questionStem: "The reasoning in the argument is flawed in that the argument",
    answerChoices: [
      { letter: "A", text: "relies on an unrepresentative sample of entrepreneurs" },
      { letter: "B", text: "fails to consider that hard work might be necessary but not sufficient for success" },
      { letter: "C", text: "assumes that entrepreneurs are the only people who work hard" },
      { letter: "D", text: "ignores the role of luck in entrepreneurial success" },
      { letter: "E", text: "equivocates on the meaning of 'hard work'" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the fallacy of confusing a necessary condition with a sufficient condition. Just because all successful entrepreneurs worked hard does not mean that everyone who works hard will succeed. Hard work may be necessary but not sufficient for success.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company claims its new drug is safe because clinical trials showed no serious side effects. However, the trials only lasted six months and involved just 500 participants. Given that the drug will be used by millions of people for years, we cannot conclude that it is safe.`,
    questionStem: "The argument is most vulnerable to criticism on which of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It assumes that longer trials would necessarily reveal additional side effects" },
      { letter: "B", text: "It ignores the possibility that the drug's benefits outweigh its risks" },
      { letter: "C", text: "It fails to specify what would constitute adequate evidence of safety" },
      { letter: "D", text: "It presumes that all drugs have serious side effects that emerge over time" },
      { letter: "E", text: "It does not consider that regulatory agencies approved the trial methodology" },
    ],
    correctAnswer: "C",
    explanation: "While the argument raises legitimate concerns about the trial's limitations, it is vulnerable because it does not establish what level of testing would be sufficient to demonstrate safety. Without such a standard, the criticism is incomplete.",
    difficulty: "hard",
  },
  {
    id: "lr-bank36-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Parents who read to their children every day have children with larger vocabularies than parents who do not. This proves that daily reading is essential for vocabulary development in children.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "generalizes from an unrepresentative sample" },
      { letter: "B", text: "treats a correlation as if it were a causal relationship" },
      { letter: "C", text: "uses ambiguous language" },
      { letter: "D", text: "appeals to an inappropriate authority" },
      { letter: "E", text: "draws a conclusion that is broader than the evidence warrants" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that reading causes larger vocabularies, but correlation does not prove causation. Parents who read to their children may also engage in other vocabulary-building activities, or may themselves have larger vocabularies that they pass on genetically or through general conversation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The governor claims that the state's economy has improved under her leadership because unemployment has dropped by two percent. But this decrease merely reflects a national economic recovery that has affected all states regardless of their governors' policies. The governor's policies have had no positive effect on the economy.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that the governor's policies might have contributed to the improvement alongside national trends" },
      { letter: "B", text: "assumes that unemployment is the only measure of economic health" },
      { letter: "C", text: "does not provide evidence that other states experienced similar improvements" },
      { letter: "D", text: "ignores the possibility that the national recovery was caused by policies similar to the governor's" },
      { letter: "E", text: "relies on an appeal to authority rather than evidence" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits an either/or fallacy. Just because national trends contributed to the improvement does not mean the governor's policies had no effect. Both factors could have contributed to the economic improvement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Critics of the proposed environmental regulation argue that it will hurt business. But these critics are mostly representatives of industries that would have to change their practices under the new rules. Since they have a financial interest in opposing the regulation, their arguments should be dismissed.`,
    questionStem: "The reasoning in this argument is flawed because the argument",
    answerChoices: [
      { letter: "A", text: "fails to establish that environmental regulations generally benefit businesses" },
      { letter: "B", text: "assumes that all industry representatives oppose environmental regulations" },
      { letter: "C", text: "rejects a claim based on its source rather than its merits" },
      { letter: "D", text: "overlooks the possibility that some regulations do hurt businesses" },
      { letter: "E", text: "confuses a sufficient condition with a necessary condition" },
    ],
    correctAnswer: "C",
    explanation: "This is a genetic fallacy or ad hominem attack. The argument dismisses the critics' claims based on who they are and their motivations, rather than addressing whether their arguments about harm to business are actually valid.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of the robbery because she was seen at a restaurant at 7:00 PM, which is when the robbery occurred. The witness who claims to have seen her at the crime scene must be mistaken.`,
    questionStem: "The reasoning in the argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "assumes that the robbery occurred exactly at 7:00 PM and lasted only a moment" },
      { letter: "B", text: "fails to consider that multiple witnesses might have different perspectives" },
      { letter: "C", text: "relies on testimony that has not been verified" },
      { letter: "D", text: "presumes the defendant's innocence rather than proving it" },
      { letter: "E", text: "ignores the possibility that the restaurant witness is lying" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes the robbery occurred at precisely 7:00 PM and was instantaneous. In reality, the robbery could have occurred before or after 7:00 PM, or the defendant could have been at the restaurant briefly before or after committing the crime.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-009",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor Williams argues that standardized testing should be eliminated because it causes stress for students. But Professor Williams struggled with test anxiety as a student and failed several important exams. Obviously, his opposition to standardized testing is merely a personal vendetta and not based on sound educational principles.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "fails to address whether standardized testing actually causes harmful stress" },
      { letter: "B", text: "assumes that personal experience invalidates professional judgment" },
      { letter: "C", text: "ignores evidence supporting the use of standardized testing" },
      { letter: "D", text: "does not consider that the professor might have other reasons for his position" },
      { letter: "E", text: "presumes that only people without test anxiety can fairly evaluate testing" },
    ],
    correctAnswer: "A",
    explanation: "The argument attacks Professor Williams's motivations rather than addressing his actual claim about testing causing stress. Even if the professor has personal reasons for his view, that does not mean his argument is wrong. The argument fails to engage with the substance of his claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-010",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Studies show that people who volunteer regularly report higher levels of happiness than those who do not volunteer. The city should therefore establish mandatory volunteer service requirements to increase the overall happiness of its citizens.`,
    questionStem: "Which one of the following most accurately describes a flaw in the argument's reasoning?",
    answerChoices: [
      { letter: "A", text: "It assumes that mandatory activities produce the same benefits as voluntary activities" },
      { letter: "B", text: "It fails to consider that unhappy people might be less likely to volunteer" },
      { letter: "C", text: "It ignores the costs of implementing mandatory volunteer programs" },
      { letter: "D", text: "It generalizes from studies without knowing their methodology" },
      { letter: "E", text: "It confuses individual happiness with collective welfare" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that forcing people to volunteer will produce the same happiness benefits as choosing to volunteer. However, the voluntary nature of the activity may be essential to its psychological benefits. Mandatory service is fundamentally different from voluntary service.",
    difficulty: "hard",
  },
  {
    id: "lr-bank36-011",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A new study suggests that drinking coffee may reduce the risk of developing Type 2 diabetes. Researchers followed 10,000 adults for ten years and found that those who drank three or more cups of coffee daily were 25 percent less likely to develop diabetes than those who drank no coffee.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "The study participants who drank coffee had similar diets and exercise habits to those who did not" },
      { letter: "B", text: "Coffee contains antioxidants that have been shown to improve cellular function" },
      { letter: "C", text: "Previous studies have shown mixed results regarding coffee and diabetes" },
      { letter: "D", text: "The participants who drank coffee were generally younger than those who did not" },
      { letter: "E", text: "Decaffeinated coffee did not show the same protective effect" },
    ],
    correctAnswer: "A",
    explanation: "If coffee drinkers had similar diets and exercise habits to non-drinkers, this rules out the possibility that the reduced diabetes risk was due to these lifestyle factors rather than the coffee itself. This strengthens the causal claim about coffee.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `The city council is considering banning single-use plastic bags to reduce environmental pollution. Opponents argue that shoppers will simply use more paper bags, which require more energy to produce. However, the ban should still be implemented because it will lead to an overall reduction in environmental harm.`,
    questionStem: "Which one of the following, if true, most strengthens the argument in favor of the ban?",
    answerChoices: [
      { letter: "A", text: "Paper bags are biodegradable and do not persist in the environment like plastic" },
      { letter: "B", text: "Many cities that have banned plastic bags have seen no increase in paper bag usage" },
      { letter: "C", text: "The production of paper bags creates fewer greenhouse gas emissions than previously thought" },
      { letter: "D", text: "Reusable bag usage typically increases significantly after plastic bag bans" },
      { letter: "E", text: "Plastic bags are responsible for the deaths of thousands of marine animals each year" },
    ],
    correctAnswer: "D",
    explanation: "If reusable bag usage increases after bans, this directly addresses the opponents' concern that shoppers will simply switch to paper bags. Reusable bags would reduce the need for both single-use plastic and paper bags, supporting the claim of overall environmental benefit.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeological evidence suggests that the ancient city of Carthage was destroyed by a massive fire around 146 BCE. Historians have long attributed this destruction to the Roman army, which besieged the city that year. The Romans must have intentionally set the fires to ensure Carthage could never again threaten Rome.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "Roman historical records from the period describe orders to completely destroy Carthage" },
      { letter: "B", text: "The fire damage appears to have occurred simultaneously across all parts of the city" },
      { letter: "C", text: "Similar destruction patterns have been found at other cities conquered by Rome" },
      { letter: "D", text: "Carthage had been a major trading competitor with Rome for over a century" },
      { letter: "E", text: "The archaeological evidence is consistent with fires set at multiple points by organized forces" },
    ],
    correctAnswer: "E",
    explanation: "Evidence that fires were set at multiple points by organized forces supports the claim that the Romans intentionally set the fires, rather than the fire being accidental or resulting from combat. This pattern is consistent with deliberate destruction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Companies that invest heavily in employee training programs tend to have higher retention rates. Therefore, investing in training programs is an effective strategy for reducing employee turnover.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "Employee turnover is costly for companies in terms of both time and money" },
      { letter: "B", text: "Employees consistently cite professional development opportunities as a major factor in their decision to stay with a company" },
      { letter: "C", text: "Companies that invest in training also tend to offer higher salaries" },
      { letter: "D", text: "Some companies with high turnover have recently begun investing in training" },
      { letter: "E", text: "Training programs vary widely in their quality and effectiveness" },
    ],
    correctAnswer: "B",
    explanation: "If employees cite professional development as a major factor in staying, this supports a causal connection between training and retention. It suggests that training directly influences employee decisions rather than the correlation being due to other factors.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Recent experiments have shown that certain bacteria can break down plastic polymers into harmless compounds. Scientists propose using these bacteria to clean up plastic pollution in the oceans. This biological approach could be more effective than mechanical cleanup methods currently in use.`,
    questionStem: "Which one of the following, if true, most strengthens the scientists' proposal?",
    answerChoices: [
      { letter: "A", text: "The bacteria can survive and reproduce in saltwater environments at various temperatures" },
      { letter: "B", text: "Mechanical cleanup methods have removed millions of tons of plastic from the oceans" },
      { letter: "C", text: "The bacteria were originally discovered in a laboratory setting" },
      { letter: "D", text: "Plastic pollution is increasing faster than current cleanup efforts can address" },
      { letter: "E", text: "Some plastics are more resistant to bacterial degradation than others" },
    ],
    correctAnswer: "A",
    explanation: "For the bacteria to be effective in cleaning up ocean plastic, they must be able to survive in ocean conditions. Confirmation that they can survive and reproduce in saltwater at various temperatures directly supports the feasibility of the proposal.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Autonomous vehicles should be programmed to minimize total harm in accident scenarios, even if this means the vehicle might sometimes sacrifice its passengers to save a greater number of pedestrians. This utilitarian approach will result in the best outcomes for society as a whole.`,
    questionStem: "Which one of the following, if true, most strengthens the ethicist's argument?",
    answerChoices: [
      { letter: "A", text: "Most people believe that saving more lives is more important than saving fewer lives" },
      { letter: "B", text: "Studies show that utilitarian programming would significantly reduce total traffic fatalities" },
      { letter: "C", text: "Vehicle manufacturers are concerned about liability for accident outcomes" },
      { letter: "D", text: "Passengers can choose whether to purchase vehicles with utilitarian programming" },
      { letter: "E", text: "Autonomous vehicles are already safer than human-driven vehicles" },
    ],
    correctAnswer: "B",
    explanation: "The ethicist's argument is that utilitarian programming will produce the best outcomes. Evidence that this approach would significantly reduce total traffic fatalities directly supports this claim by showing the beneficial consequences of the proposed policy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Small businesses that adopt e-commerce platforms see an average revenue increase of 30 percent within two years. The government should therefore provide subsidies to help small businesses establish online sales channels, as this will boost the overall economy.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "The cost of the proposed subsidies would be less than the expected increase in tax revenue from business growth" },
      { letter: "B", text: "Large corporations already have well-established e-commerce operations" },
      { letter: "C", text: "Some small businesses have failed despite adopting e-commerce platforms" },
      { letter: "D", text: "E-commerce adoption rates among small businesses have been steadily increasing" },
      { letter: "E", text: "The 30 percent revenue increase is an average, with some businesses seeing larger gains" },
    ],
    correctAnswer: "A",
    explanation: "This strengthens the argument by showing that the subsidies would be a sound investment—the government would recoup more in tax revenue than it spends. This addresses potential concerns about the cost-effectiveness of the policy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-018",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Linguist: The indigenous language of the Korvak people will likely become extinct within two generations unless significant preservation efforts are undertaken. Currently, only about 200 native speakers remain, all of whom are over the age of 60. Young people in the community prefer to speak the dominant national language.`,
    questionStem: "Which one of the following, if true, most strengthens the linguist's prediction?",
    answerChoices: [
      { letter: "A", text: "The Korvak language has no written form and exists only in oral tradition" },
      { letter: "B", text: "Government policies discourage the teaching of minority languages in schools" },
      { letter: "C", text: "Some Korvak cultural practices require knowledge of the indigenous language" },
      { letter: "D", text: "Other indigenous languages with similar speaker demographics have gone extinct" },
      { letter: "E", text: "The Korvak people live in a geographically isolated region" },
    ],
    correctAnswer: "D",
    explanation: "If other indigenous languages with similar demographics (few elderly speakers, young people preferring dominant languages) have gone extinct, this pattern supports the prediction that the same fate awaits the Korvak language without intervention.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-019",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company argues that its new pain medication is superior to existing treatments because patients in clinical trials reported higher satisfaction rates. The company concludes that hospitals should switch to this new medication for all pain management.`,
    questionStem: "Which one of the following, if true, most weakens the company's argument?",
    answerChoices: [
      { letter: "A", text: "The clinical trials were conducted by researchers employed by the pharmaceutical company" },
      { letter: "B", text: "Patients in the trials knew they were receiving a new experimental treatment" },
      { letter: "C", text: "The new medication costs significantly more than existing treatments" },
      { letter: "D", text: "Some patients in the trials experienced minor side effects" },
      { letter: "E", text: "The trials compared the new medication to placebos rather than existing treatments" },
    ],
    correctAnswer: "E",
    explanation: "If the trials compared the new medication to placebos rather than existing treatments, the higher satisfaction rates do not demonstrate superiority over current medications. The comparison is irrelevant to the claim that hospitals should switch from existing treatments.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Urban planners argue that building more highways will reduce traffic congestion by providing additional capacity for vehicles. The city council is therefore considering approving a major highway expansion project to address the growing congestion problem.`,
    questionStem: "Which one of the following, if true, most weakens the urban planners' argument?",
    answerChoices: [
      { letter: "A", text: "Highway construction projects typically take several years to complete" },
      { letter: "B", text: "Public transportation ridership has been declining in recent years" },
      { letter: "C", text: "Studies show that new highway capacity induces additional driving, often restoring congestion to previous levels" },
      { letter: "D", text: "The proposed highway would pass through several residential neighborhoods" },
      { letter: "E", text: "Many commuters prefer driving to using public transportation" },
    ],
    correctAnswer: "C",
    explanation: "If new highway capacity induces additional driving that restores congestion to previous levels (induced demand), then building more highways will not actually reduce congestion. This directly undermines the planners' argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Critics of organic farming argue that it cannot feed the world's growing population because organic yields are lower than conventional farming. Therefore, we must continue to rely primarily on conventional agriculture with its use of synthetic fertilizers and pesticides.`,
    questionStem: "Which one of the following, if true, most weakens the critics' argument?",
    answerChoices: [
      { letter: "A", text: "Organic farming methods have been used successfully for thousands of years" },
      { letter: "B", text: "Consumer demand for organic products has increased substantially in recent years" },
      { letter: "C", text: "Approximately one-third of all food produced worldwide is wasted before consumption" },
      { letter: "D", text: "Organic farms require more land to produce the same amount of food" },
      { letter: "E", text: "Some organic farms have achieved yields comparable to conventional farms" },
    ],
    correctAnswer: "C",
    explanation: "If one-third of food is wasted, the problem may not be production capacity but distribution and consumption. Even with lower yields, organic farming might be sufficient if waste were reduced, weakening the argument that we must rely on conventional agriculture.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The mayor argues that the city's new bike-sharing program has been a success because usage has increased by 50 percent since its launch. This demonstrates that residents support sustainable transportation options and that the program should be expanded.`,
    questionStem: "Which one of the following, if true, most weakens the mayor's argument?",
    answerChoices: [
      { letter: "A", text: "The bike-sharing program operates in only a small portion of the city" },
      { letter: "B", text: "Similar programs in other cities have experienced declining usage after initial enthusiasm" },
      { letter: "C", text: "The 50 percent increase is largely due to tourists, while resident usage has remained flat" },
      { letter: "D", text: "The program requires significant subsidies from the city budget" },
      { letter: "E", text: "Some of the bikes have been damaged or stolen" },
    ],
    correctAnswer: "C",
    explanation: "The mayor claims the program shows resident support for sustainable transportation. If the increased usage is mostly from tourists while resident usage is flat, this undermines the claim that residents support the program and want it expanded.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A technology company claims that its artificial intelligence hiring system is fairer than human recruiters because it makes decisions based solely on qualifications and experience, without being influenced by factors like appearance or personal rapport. The company recommends that other businesses adopt similar systems.`,
    questionStem: "Which one of the following, if true, most seriously weakens the company's claim?",
    answerChoices: [
      { letter: "A", text: "Human recruiters often disagree with each other about which candidates are best" },
      { letter: "B", text: "The AI system was trained on historical hiring data that reflected human biases" },
      { letter: "C", text: "Some qualified candidates prefer interacting with human recruiters" },
      { letter: "D", text: "The AI system occasionally makes errors in parsing resume information" },
      { letter: "E", text: "Implementing AI hiring systems is expensive for small businesses" },
    ],
    correctAnswer: "B",
    explanation: "If the AI was trained on biased historical data, it will perpetuate those biases in its decisions. This directly undermines the claim that the AI is fairer than human recruiters, since it would be replicating human biases rather than eliminating them.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-024",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Countries with lower corporate tax rates attract more foreign investment and experience higher economic growth. Therefore, our country should reduce its corporate tax rate to stimulate the economy and create more jobs.`,
    questionStem: "Which one of the following, if true, most weakens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Some countries with low tax rates have experienced economic stagnation" },
      { letter: "B", text: "Corporate tax revenue funds public services that contribute to economic productivity" },
      { letter: "C", text: "Many corporations already use legal strategies to minimize their tax burden" },
      { letter: "D", text: "Individual income taxes make up a larger portion of government revenue than corporate taxes" },
      { letter: "E", text: "Economic growth is influenced by many factors beyond tax policy" },
    ],
    correctAnswer: "B",
    explanation: "If corporate tax revenue funds public services that contribute to economic productivity, then reducing taxes might harm the economy by reducing these services. The argument ignores this potential negative consequence of lower tax rates.",
    difficulty: "hard",
  },
  {
    id: "lr-bank36-025",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Proponents of year-round schooling argue that it improves academic performance by reducing the learning loss that occurs during long summer breaks. Several school districts that have adopted year-round calendars report improved test scores, suggesting that all districts should consider this approach.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Teachers in year-round schools report higher levels of burnout" },
      { letter: "B", text: "Some students in year-round schools participate in enrichment programs during breaks" },
      { letter: "C", text: "The districts that adopted year-round schooling also implemented other academic reforms simultaneously" },
      { letter: "D", text: "Year-round schooling changes the timing but not the total number of school days" },
      { letter: "E", text: "Some parents prefer traditional school calendars for family scheduling reasons" },
    ],
    correctAnswer: "C",
    explanation: "If the districts also implemented other reforms, the improved test scores might be due to those reforms rather than the year-round calendar. This alternative explanation weakens the claim that year-round schooling caused the improvement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Medical researcher: A new gene therapy treatment has shown remarkable success in laboratory trials, eliminating cancer cells in over 90 percent of test subjects. This treatment should be fast-tracked for human trials because it offers hope to millions of cancer patients.`,
    questionStem: "Which one of the following, if true, most weakens the argument for fast-tracking?",
    answerChoices: [
      { letter: "A", text: "The laboratory trials were conducted on mice, whose physiology differs significantly from humans" },
      { letter: "B", text: "Gene therapy is an expensive treatment that may not be accessible to all patients" },
      { letter: "C", text: "Some cancer patients have found success with existing treatments" },
      { letter: "D", text: "The research team has applied for additional funding to continue their work" },
      { letter: "E", text: "Other gene therapy treatments are already in human trials" },
    ],
    correctAnswer: "A",
    explanation: "If the trials were on mice rather than humans, the 90 percent success rate may not translate to human patients. This significantly weakens the argument for fast-tracking human trials based on these laboratory results.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The restaurant's new menu has been receiving negative reviews from food critics. Unless the restaurant changes the menu, it will go out of business within a year.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Food critics' opinions influence the dining choices of the restaurant's customers" },
      { letter: "B", text: "The restaurant has received negative reviews before" },
      { letter: "C", text: "All restaurants that receive negative reviews go out of business" },
      { letter: "D", text: "The restaurant's menu is the only factor affecting its success" },
      { letter: "E", text: "Food critics have more refined tastes than average diners" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that negative reviews from food critics will affect the restaurant's business. If critics' opinions don't influence customer behavior, then the negative reviews wouldn't lead to the restaurant closing.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `University professor: Students who participate in study groups perform better on exams than those who study alone. Therefore, universities should encourage the formation of study groups to improve overall academic outcomes.`,
    questionStem: "Which one of the following is an assumption required by the professor's argument?",
    answerChoices: [
      { letter: "A", text: "Study groups are the most effective way to prepare for exams" },
      { letter: "B", text: "Students who perform better on exams were not already more academically prepared before joining study groups" },
      { letter: "C", text: "All students are equally comfortable participating in group settings" },
      { letter: "D", text: "Universities have the resources to facilitate the formation of study groups" },
      { letter: "E", text: "Exam performance is the most important measure of academic success" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that study groups cause better performance, not that better-prepared students simply choose to form study groups. If the latter were true, encouraging study groups wouldn't improve outcomes for other students.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city council should approve the new public park project. Parks increase property values in surrounding neighborhoods, which will generate more tax revenue for the city.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The cost of building and maintaining the park will not exceed the additional tax revenue generated" },
      { letter: "B", text: "Property values are the only factor that determines tax revenue" },
      { letter: "C", text: "All residents of the city want more public parks" },
      { letter: "D", text: "The city has never built a public park before" },
      { letter: "E", text: "Private developers would not build a park in the same location" },
    ],
    correctAnswer: "A",
    explanation: "For the argument to work, the additional tax revenue from increased property values must exceed the cost of the park. Otherwise, the park would not be financially beneficial for the city, even if it increases property values.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: The incumbent senator will likely win reelection because she has a substantial lead in the polls. Her opponent has failed to gain traction with voters despite significant campaign spending.`,
    questionStem: "Which one of the following is an assumption on which the analyst's reasoning depends?",
    answerChoices: [
      { letter: "A", text: "The polls accurately reflect how voters will actually vote on election day" },
      { letter: "B", text: "Campaign spending is the most important factor in winning elections" },
      { letter: "C", text: "The senator has served multiple terms already" },
      { letter: "D", text: "Voters always prefer incumbent candidates" },
      { letter: "E", text: "The opponent's campaign has been poorly managed" },
    ],
    correctAnswer: "A",
    explanation: "The argument relies on current poll numbers to predict the election outcome. This assumes that polls are reliable predictors of actual voting behavior. If polls are inaccurate, the lead might not translate to victory.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-031",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The decline of the Roman Empire was primarily caused by economic factors, including inflation, excessive taxation, and trade imbalances. Military defeats and political instability were merely symptoms of these underlying economic problems.`,
    questionStem: "The historian's argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "economic factors have caused the decline of all major empires throughout history" },
      { letter: "B", text: "military defeats and political instability did not independently contribute to Rome's decline" },
      { letter: "C", text: "Rome's economic problems were more severe than those of other ancient civilizations" },
      { letter: "D", text: "modern economists can accurately assess ancient economic conditions" },
      { letter: "E", text: "the Roman Empire could have survived if it had addressed its economic problems" },
    ],
    correctAnswer: "B",
    explanation: "The historian claims that military and political problems were merely symptoms of economic issues. This requires assuming that these factors did not independently cause Rome's decline, but were entirely derivative of economic problems.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `A new study shows that employees who work from home are more productive than those who work in traditional office settings. Companies should therefore allow all employees to work from home to maximize productivity.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "All jobs can be performed effectively from home" },
      { letter: "B", text: "Employees prefer working from home to working in offices" },
      { letter: "C", text: "The study's findings would hold true for employees at all companies" },
      { letter: "D", text: "Productivity is the only factor companies should consider in workplace decisions" },
      { letter: "E", text: "Working from home reduces operational costs for companies" },
    ],
    correctAnswer: "A",
    explanation: "The argument recommends that all employees work from home. This assumes that all jobs can be performed from home. If some jobs require physical presence, the recommendation would not apply universally.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Environmental scientist: The proposed wind farm will provide clean energy for 50,000 homes without producing greenhouse gas emissions. This makes it clearly superior to the natural gas plant that was the alternative proposal.`,
    questionStem: "Which one of the following is an assumption required by the scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Wind energy is more reliable than natural gas for power generation" },
      { letter: "B", text: "The environmental impact of constructing and maintaining the wind farm is less significant than the emissions from the gas plant" },
      { letter: "C", text: "Fifty thousand homes represents a significant portion of the region's energy needs" },
      { letter: "D", text: "Natural gas is the most polluting form of fossil fuel" },
      { letter: "E", text: "The wind farm will operate for at least as long as the natural gas plant would have" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims superiority based on zero emissions during operation. However, wind farms have environmental impacts from construction and materials. The argument assumes these impacts are less than the gas plant's emissions, or the comparison is incomplete.",
    difficulty: "hard",
  },
  {
    id: "lr-bank36-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Philosophy professor: Moral relativism—the view that moral truths vary between cultures—cannot be correct. If it were true, we could not criticize the moral practices of other cultures, including practices we find abhorrent. But clearly, some practices deserve moral condemnation regardless of cultural context.`,
    questionStem: "The professor's argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "All cultures share some fundamental moral values" },
      { letter: "B", text: "It is possible to identify practices that are objectively wrong" },
      { letter: "C", text: "Moral relativism is a widely held philosophical position" },
      { letter: "D", text: "Cultural practices evolve over time in response to moral criticism" },
      { letter: "E", text: "Moral condemnation is effective in changing cultural practices" },
    ],
    correctAnswer: "B",
    explanation: "The professor argues that some practices deserve condemnation regardless of culture. This assumes we can identify objectively wrong practices. If we cannot, then the inability to criticize practices under relativism would not be a problem.",
    difficulty: "hard",
  },
  {
    id: "lr-bank36-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Recent archaeological discoveries suggest that ancient humans were capable of symbolic thinking far earlier than previously believed. Cave paintings dating back 65,000 years have been found in Spain, and shell beads used for personal ornamentation are even older. This evidence challenges the traditional view that symbolic thought emerged only 40,000 years ago with the arrival of modern humans in Europe. We must revise our understanding of cognitive evolution.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Cave paintings in Spain date back 65,000 years" },
      { letter: "B", text: "Shell beads were used for personal ornamentation before cave paintings were created" },
      { letter: "C", text: "Symbolic thought did not emerge only 40,000 years ago" },
      { letter: "D", text: "Our understanding of cognitive evolution needs to be revised" },
      { letter: "E", text: "Modern humans arrived in Europe 40,000 years ago" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is that we must revise our understanding of cognitive evolution. The archaeological evidence and the challenge to traditional views are presented as support for this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Many educators argue that homework reinforces classroom learning and teaches responsibility. However, studies show that excessive homework can lead to stress, sleep deprivation, and decreased interest in learning. Moreover, the correlation between homework and academic achievement is weak in elementary school and only moderate in high school. Schools should therefore limit homework assignments to a reasonable amount that balances potential benefits against documented harms.`,
    questionStem: "Which one of the following best expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Homework reinforces classroom learning and teaches responsibility" },
      { letter: "B", text: "Excessive homework can lead to stress and sleep deprivation" },
      { letter: "C", text: "The correlation between homework and achievement is weak in elementary school" },
      { letter: "D", text: "Schools should limit homework to a reasonable amount" },
      { letter: "E", text: "The benefits of homework are outweighed by its harms" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is the recommendation that schools should limit homework. The evidence about harms and weak correlations with achievement supports this prescriptive conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The notion that great artists must suffer for their art is a romantic myth. Many celebrated artists, including Shakespeare and Mozart, were financially successful during their lifetimes. Others who did experience hardship, like Van Gogh, produced their greatest works during periods of relative stability. Creativity does not require suffering; rather, it flourishes when basic needs are met and artists have the freedom to pursue their vision.`,
    questionStem: "The main point of the argument is that",
    answerChoices: [
      { letter: "A", text: "Shakespeare and Mozart were financially successful" },
      { letter: "B", text: "Van Gogh produced his greatest works during periods of stability" },
      { letter: "C", text: "the belief that artists must suffer is unfounded" },
      { letter: "D", text: "creativity flourishes when basic needs are met" },
      { letter: "E", text: "romantic myths about artists should be rejected" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is that the idea that great artists must suffer is a romantic myth (i.e., unfounded). The examples of successful artists and the claim about creativity flourishing are evidence supporting this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Consumer advocate: Many people believe that extended warranties are a good investment because they provide protection against expensive repairs. However, studies show that the cost of extended warranties typically exceeds the expected value of repairs they cover. Additionally, many products are already covered by manufacturer warranties for the most likely failure period. Consumers are usually better off declining extended warranties and saving the money for potential repairs.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the consumer advocate's argument?",
    answerChoices: [
      { letter: "A", text: "Extended warranties cost more than the expected value of the repairs they cover" },
      { letter: "B", text: "Many products are covered by manufacturer warranties during the most likely failure period" },
      { letter: "C", text: "Consumers should usually decline extended warranties" },
      { letter: "D", text: "People mistakenly believe extended warranties are a good investment" },
      { letter: "E", text: "Saving money for potential repairs is wiser than buying warranties" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is the prescriptive claim that consumers are usually better off declining extended warranties. The evidence about costs exceeding value and manufacturer coverage supports this recommendation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The mayor claims that the new transit system will reduce traffic congestion. But the mayor made similar promises about the last two transit projects, and neither delivered the promised congestion relief. There is no reason to think this project will be any different.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing evidence that the new transit system is technically flawed" },
      { letter: "B", text: "citing past failures to cast doubt on a current prediction" },
      { letter: "C", text: "questioning the mayor's expertise in transportation planning" },
      { letter: "D", text: "demonstrating that transit systems never reduce congestion" },
      { letter: "E", text: "analyzing the specific features of the proposed transit system" },
    ],
    correctAnswer: "B",
    explanation: "The argument uses the mayor's past failed predictions to suggest that the current prediction is also unreliable. This is an argument from precedent, using past failures to cast doubt on current claims.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Those who claim that morality is merely a social construct cannot consistently advocate for any moral position. For if morality is just a social construct, then their advocacy is simply an expression of their society's values, not a claim about what is truly right. But they clearly do advocate for moral positions, which means they implicitly believe some things are truly right or wrong. Therefore, consistent moral relativism is impossible.`,
    questionStem: "The philosopher's argument employs which one of the following argumentative strategies?",
    answerChoices: [
      { letter: "A", text: "Showing that a position leads to practical contradictions in the behavior of those who hold it" },
      { letter: "B", text: "Demonstrating that a position is based on factual errors" },
      { letter: "C", text: "Arguing that a position is unpopular and therefore likely to be wrong" },
      { letter: "D", text: "Proving that a position contradicts established scientific findings" },
      { letter: "E", text: "Showing that a position cannot account for certain undeniable phenomena" },
    ],
    correctAnswer: "A",
    explanation: "The philosopher argues that moral relativists cannot consistently advocate for moral positions because their advocacy implicitly contradicts their stated relativist views. This shows a practical contradiction in their behavior.",
    difficulty: "hard",
  },
  {
    id: "lr-bank36-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Some people argue that all processed foods are unhealthy. But consider bread—it is processed from wheat, yet has been a dietary staple for thousands of years and is part of many healthy diets. Clearly, the processing of food does not automatically make it unhealthy.`,
    questionStem: "The nutritionist's argument uses which one of the following techniques?",
    answerChoices: [
      { letter: "A", text: "Presenting statistical evidence to refute a generalization" },
      { letter: "B", text: "Offering a counterexample to challenge a universal claim" },
      { letter: "C", text: "Appealing to expert authority to establish a conclusion" },
      { letter: "D", text: "Showing that a claim is based on an ambiguous use of a key term" },
      { letter: "E", text: "Demonstrating that a position leads to absurd consequences" },
    ],
    correctAnswer: "B",
    explanation: "The nutritionist challenges the universal claim that all processed foods are unhealthy by providing bread as a counterexample—a processed food that is part of healthy diets. One counterexample can refute a universal claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution argues that my client had the opportunity and motive to commit the crime. But opportunity and motive are not proof of guilt. Many people may have had opportunity and motive, yet only one person actually committed the crime. Without direct evidence linking my client to the crime scene, the prosecution's case fails to establish guilt beyond a reasonable doubt.`,
    questionStem: "The defense attorney's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing an alibi for the defendant" },
      { letter: "B", text: "attacking the credibility of prosecution witnesses" },
      { letter: "C", text: "arguing that the prosecution's evidence does not meet the required standard of proof" },
      { letter: "D", text: "suggesting alternative suspects for the crime" },
      { letter: "E", text: "demonstrating that the defendant lacked motive" },
    ],
    correctAnswer: "C",
    explanation: "The attorney argues that even if the prosecution's claims about opportunity and motive are true, they are insufficient to prove guilt beyond reasonable doubt. The argument challenges the adequacy of the evidence, not its accuracy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Marcus: Artists should create work that challenges social norms and provokes thought, even if the public finds it uncomfortable or offensive. Art that merely pleases audiences fails to fulfill its higher purpose of advancing culture and consciousness.

Elena: The value of art lies in its ability to connect with people and bring beauty into their lives. Artists who deliberately alienate their audiences through provocative work are prioritizing their own egos over the genuine human need for aesthetic pleasure.`,
    questionStem: "Marcus and Elena disagree about whether",
    answerChoices: [
      { letter: "A", text: "some art is designed to provoke rather than please" },
      { letter: "B", text: "artists have an obligation to consider their audiences" },
      { letter: "C", text: "challenging social norms is a legitimate purpose of art" },
      { letter: "D", text: "aesthetic pleasure is a human need" },
      { letter: "E", text: "contemporary art has become too provocative" },
    ],
    correctAnswer: "C",
    explanation: "Marcus believes art should challenge social norms (its 'higher purpose'), while Elena suggests that deliberately provocative work represents ego over genuine purpose. They disagree about whether challenging norms is a legitimate artistic purpose.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Chen: Online education cannot replace traditional classroom instruction. The spontaneous discussions, immediate feedback, and personal connections that occur in physical classrooms are essential to deep learning and cannot be replicated digitally.

Professor Walsh: Research shows that students in well-designed online courses perform just as well as students in traditional classrooms on standardized assessments. The flexibility of online education also allows students to learn at their own pace, which can enhance understanding.`,
    questionStem: "The professors' statements provide the most support for the claim that they disagree about",
    answerChoices: [
      { letter: "A", text: "whether online courses offer flexibility that traditional courses lack" },
      { letter: "B", text: "whether standardized assessments are good measures of learning" },
      { letter: "C", text: "whether online education can provide learning outcomes comparable to traditional instruction" },
      { letter: "D", text: "whether personal connections are valuable in educational settings" },
      { letter: "E", text: "whether all students learn best at their own pace" },
    ],
    correctAnswer: "C",
    explanation: "Professor Chen claims online education cannot replace traditional instruction (implying inferior outcomes), while Professor Walsh cites research showing comparable performance. They directly disagree about whether online education can match traditional instruction in learning outcomes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Rivera: Genetic testing for disease risk should be made widely available to the public. When people know their genetic predispositions, they can take preventive measures to reduce their risk of developing serious illnesses.

Dr. Patel: Making genetic testing widely available is problematic. Many people lack the scientific literacy to properly interpret genetic risk information, which may lead to unnecessary anxiety, medical interventions, or a false sense of security.`,
    questionStem: "Dr. Rivera and Dr. Patel disagree about whether",
    answerChoices: [
      { letter: "A", text: "genetic testing can identify disease risk" },
      { letter: "B", text: "preventive measures can reduce the risk of illness" },
      { letter: "C", text: "the general public should have broad access to genetic testing" },
      { letter: "D", text: "some people lack scientific literacy" },
      { letter: "E", text: "genetic information can cause anxiety in some individuals" },
    ],
    correctAnswer: "C",
    explanation: "Dr. Rivera advocates for making genetic testing widely available, while Dr. Patel argues this is problematic. They directly disagree about whether the general public should have broad access to genetic testing.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All licensed physicians have completed medical school. Some licensed physicians specialize in pediatrics. Therefore, some people who have completed medical school specialize in pediatrics.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All certified teachers have bachelor's degrees. Some certified teachers work in elementary schools. Therefore, some people with bachelor's degrees work in elementary schools." },
      { letter: "B", text: "All birds have feathers. All eagles are birds. Therefore, all eagles have feathers." },
      { letter: "C", text: "Some athletes are highly paid. All professional basketball players are athletes. Therefore, all professional basketball players are highly paid." },
      { letter: "D", text: "No reptiles are mammals. Some reptiles live in deserts. Therefore, no mammals live in deserts." },
      { letter: "E", text: "Most doctors work long hours. Most nurses work in hospitals. Therefore, most people who work long hours work in hospitals." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments follow the same valid pattern: All A are B. Some A are C. Therefore, some B are C. The structure matches exactly: licensed physicians/certified teachers (A), medical school/bachelor's degrees (B), pediatrics/elementary schools (C).",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Whenever the factory exceeds its production quota, workers receive bonuses. The factory did not exceed its quota last month. Therefore, workers did not receive bonuses last month.`,
    questionStem: "Which one of the following exhibits a flawed pattern of reasoning most similar to that exhibited by the argument above?",
    answerChoices: [
      { letter: "A", text: "Whenever it rains, the streets get wet. It rained yesterday. Therefore, the streets were wet yesterday." },
      { letter: "B", text: "Whenever the alarm sounds, employees evacuate the building. The alarm did not sound today. Therefore, employees did not evacuate the building today." },
      { letter: "C", text: "All employees who meet their targets receive raises. John received a raise. Therefore, John met his targets." },
      { letter: "D", text: "If the package arrives by noon, we can complete the project. The package did not arrive by noon. Therefore, we cannot complete the project." },
      { letter: "E", text: "Whenever traffic is heavy, commuters are late. Commuters were late this morning. Therefore, traffic was heavy this morning." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments commit the fallacy of denying the antecedent: If A then B; not A; therefore not B. This is invalid because B could occur for other reasons. Workers might receive bonuses for other reasons; employees might evacuate for other reasons.",
    difficulty: "hard",
  },
  {
    id: "lr-bank36-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The city cannot both reduce taxes and increase public services. The city has decided to increase public services. Therefore, the city cannot reduce taxes.`,
    questionStem: "The reasoning in the argument above is most closely paralleled by which one of the following?",
    answerChoices: [
      { letter: "A", text: "The company cannot both expand internationally and focus on the domestic market. The company has chosen to expand internationally. Therefore, the company cannot focus on the domestic market." },
      { letter: "B", text: "Students can either study engineering or study business. Maria is studying engineering. Therefore, Maria will become an engineer." },
      { letter: "C", text: "The restaurant must either raise prices or reduce portions. The restaurant will not raise prices. Therefore, the restaurant might reduce portions." },
      { letter: "D", text: "We can either take the highway or take the local roads. If we take the highway, we will arrive early. Therefore, we should take the highway." },
      { letter: "E", text: "The team cannot win if the star player is injured. The star player is injured. Therefore, the team cannot win." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments follow valid disjunctive syllogism with incompatible options: Cannot do both A and B; doing B; therefore not A. The city and company face mutually exclusive choices, and selecting one eliminates the other.",
    difficulty: "medium",
  },
  {
    id: "lr-bank36-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `A recent survey of hiring managers found that 70 percent consider a candidate's social media presence when making hiring decisions. Of those who consider social media, 60 percent have rejected candidates based on what they found online. The most common reasons for rejection were inappropriate photographs, evidence of drug use, and discriminatory comments.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "More than half of all candidates are rejected due to their social media presence" },
      { letter: "B", text: "Candidates should delete their social media accounts before applying for jobs" },
      { letter: "C", text: "Some hiring managers have rejected candidates based on social media content" },
      { letter: "D", text: "Inappropriate photographs are the most common content on social media" },
      { letter: "E", text: "Hiring managers who do not consider social media make better hiring decisions" },
    ],
    correctAnswer: "C",
    explanation: "If 70% of hiring managers consider social media and 60% of those have rejected candidates based on it, then some hiring managers (specifically, 42% of all hiring managers) have rejected candidates based on social media. This must be true.",
    difficulty: "easy",
  },
  {
    id: "lr-bank36-050",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `In Greendale County, property taxes fund local schools. Properties are reassessed every five years, and tax rates are adjusted annually to meet the school budget. Last year, many commercial properties were converted to residential use, reducing the commercial tax base. Residential properties are taxed at a lower rate than commercial properties. The school budget has not decreased.`,
    questionStem: "If all of the statements above are true, which one of the following can be properly inferred?",
    answerChoices: [
      { letter: "A", text: "Residential property owners in Greendale County now pay more in taxes than commercial property owners" },
      { letter: "B", text: "The conversion of commercial properties to residential use has caused financial problems for schools" },
      { letter: "C", text: "Tax rates on at least some properties in Greendale County must have increased" },
      { letter: "D", text: "Commercial property values in Greendale County have declined" },
      { letter: "E", text: "The school budget in Greendale County has increased" },
    ],
    correctAnswer: "C",
    explanation: "With fewer commercial properties (taxed at higher rates) and more residential properties (taxed at lower rates), but the school budget unchanged, the total tax revenue must remain constant. Since the tax base shifted to lower-rate properties, rates must have increased somewhere to maintain revenue.",
    difficulty: "hard",
  },
];
