// Logical Reasoning Questions Bank - Set 69
import { Question } from "../lsat-types";

export const lrQuestionsSet69: Question[] = [
  {
    id: "lr-bank69-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during the workday are more productive than those who work continuously. Therefore, employers should require all employees to take mandatory breaks every two hours, as this will certainly increase overall company productivity.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that productivity might be measured differently across industries" },
      { letter: "B", text: "assumes that what correlates with higher productivity will cause higher productivity when mandated" },
      { letter: "C", text: "relies on a study without specifying the sample size" },
      { letter: "D", text: "ignores the possibility that some employees already take regular breaks" },
      { letter: "E", text: "does not define what constitutes a 'regular' break" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the correlation-causation fallacy. Just because employees who choose to take breaks are more productive doesn't mean that forcing breaks on all employees will increase productivity. The voluntary nature of the breaks might be what makes them effective, or productive employees might simply tend to take breaks.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers have discovered that a newly identified species of deep-sea fish can survive at depths previously thought impossible for vertebrates. The fish possesses a unique protein that prevents cellular damage from extreme pressure. Scientists believe this protein could be synthesized and used to develop new treatments for human conditions caused by cellular stress.`,
    questionStem: "Which one of the following, if true, most strengthens the scientists' belief?",
    answerChoices: [
      { letter: "A", text: "The deep-sea fish is extremely rare and difficult to study in laboratory conditions" },
      { letter: "B", text: "Similar proteins found in other marine organisms have been successfully adapted for human medical applications" },
      { letter: "C", text: "Human cells experience pressure-related stress only under very unusual circumstances" },
      { letter: "D", text: "The protein is produced by the fish only when exposed to extreme depths" },
      { letter: "E", text: "Other deep-sea creatures use different mechanisms to survive at extreme depths" },
    ],
    correctAnswer: "B",
    explanation: "If similar proteins from marine organisms have already been successfully adapted for human medical use, this provides precedent suggesting the scientists' belief is reasonable. This strengthens the argument by showing that the proposed approach has worked before with comparable biological materials.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that installing speed cameras on Main Street will reduce traffic accidents. They point to a neighboring city where accidents decreased by 30% after speed cameras were installed. The council concludes that similar results can be expected here.`,
    questionStem: "Which one of the following, if true, most weakens the council's argument?",
    answerChoices: [
      { letter: "A", text: "Speed cameras are expensive to install and maintain" },
      { letter: "B", text: "The neighboring city also implemented road redesigns and increased police patrols at the same time as the cameras" },
      { letter: "C", text: "Some drivers may simply take alternate routes to avoid the cameras" },
      { letter: "D", text: "Main Street has a lower speed limit than the roads in the neighboring city" },
      { letter: "E", text: "Traffic accidents have been decreasing nationally over the past decade" },
    ],
    correctAnswer: "B",
    explanation: "If the neighboring city implemented multiple safety measures simultaneously, we cannot attribute the accident reduction solely to speed cameras. This weakens the conclusion that speed cameras alone will produce similar results, as other factors may have been responsible for the improvement.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All great philosophers have grappled with questions about the nature of consciousness. Dr. Martinez has spent her entire career studying consciousness and has published extensively on the subject. Therefore, Dr. Martinez must be a great philosopher.`,
    questionStem: "The argument's conclusion follows logically if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "Only great philosophers study consciousness" },
      { letter: "B", text: "Anyone who studies consciousness extensively becomes a great philosopher" },
      { letter: "C", text: "Dr. Martinez's publications on consciousness are highly regarded" },
      { letter: "D", text: "Great philosophers are recognized primarily for their work on consciousness" },
      { letter: "E", text: "Studying consciousness is more difficult than studying other philosophical topics" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'great philosophers study consciousness' to 'Martinez studies consciousness, therefore she is a great philosopher.' This commits a logical error unless we assume that extensively studying consciousness is sufficient to make someone a great philosopher—that the relationship works in both directions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical ethicists have long debated whether patients have an absolute right to refuse treatment. While autonomy is a fundamental principle in medical ethics, there are cases where a patient's refusal could harm others—such as refusing vaccination during an epidemic. In such cases, the community's welfare may outweigh individual autonomy. Thus, the right to refuse treatment, while important, cannot be considered absolute.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Autonomy is a fundamental principle in medical ethics" },
      { letter: "B", text: "Patients sometimes refuse treatment in ways that harm others" },
      { letter: "C", text: "The right to refuse medical treatment is not an absolute right" },
      { letter: "D", text: "Community welfare should always take precedence over individual rights" },
      { letter: "E", text: "Medical ethicists have debated patient rights for a long time" },
    ],
    correctAnswer: "C",
    explanation: "The conclusion is signaled by 'Thus' and states that the right to refuse treatment 'cannot be considered absolute.' The other statements are premises or background information used to support this conclusion, not the main point being argued.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The museum director claims that the new modern art exhibit will attract younger visitors. But the director made the same prediction about the contemporary sculpture exhibit last year, which failed to draw young audiences. There's no reason to think this prediction will be any more accurate.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing a counterexample to a general claim made by the director" },
      { letter: "B", text: "questioning the director's credibility based on a past inaccurate prediction" },
      { letter: "C", text: "arguing that modern art is not appealing to younger audiences" },
      { letter: "D", text: "suggesting that the museum should focus on attracting older visitors instead" },
      { letter: "E", text: "demonstrating that the sculpture exhibit was similar in all respects to the new exhibit" },
    ],
    correctAnswer: "B",
    explanation: "The critic challenges the director's current prediction by pointing out that a similar prediction in the past proved inaccurate. This is an attack on the director's reliability as a predictor, using past performance to cast doubt on the current claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Senator Walsh opposes the proposed environmental regulations, claiming they would harm businesses. But Senator Walsh has received substantial campaign contributions from major industrial polluters. Clearly, her opposition to the regulations is not based on genuine concern for businesses but rather on her desire to please her donors.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that the regulations might actually harm businesses" },
      { letter: "B", text: "assumes that anyone who receives campaign contributions cannot have independent views" },
      { letter: "C", text: "attacks the senator's motives rather than addressing the merits of her argument" },
      { letter: "D", text: "presumes that all industrial companies are polluters" },
      { letter: "E", text: "ignores the possibility that the senator's donors might also be concerned about businesses" },
    ],
    correctAnswer: "C",
    explanation: "This is an ad hominem fallacy. Instead of addressing whether the regulations would actually harm businesses, the argument attacks Senator Walsh's motives. Even if the senator's motives are questionable, this doesn't prove her argument about the regulations is wrong.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company claims that its new medication reduces the risk of heart attacks by 50% compared to a placebo. Consumer advocates are skeptical, noting that the company has a financial interest in promoting positive results. However, the study was conducted by independent researchers at a major university, and the results were published in a peer-reviewed journal.`,
    questionStem: "Which one of the following, if true, most strengthens the case for accepting the study's findings?",
    answerChoices: [
      { letter: "A", text: "The pharmaceutical company funded the research through an unrestricted grant with no control over the study design" },
      { letter: "B", text: "The medication has been approved by regulatory authorities in several countries" },
      { letter: "C", text: "Previous medications by the same company have proven effective" },
      { letter: "D", text: "The peer-reviewed journal has a reputation for publishing groundbreaking research" },
      { letter: "E", text: "Consumer advocates often express skepticism about pharmaceutical research" },
    ],
    correctAnswer: "A",
    explanation: "The consumer advocates' concern is about the company's financial interest influencing results. If the company provided funding but had no control over study design, this addresses the concern about bias while explaining the independence of the research. This strengthens confidence in the objectivity of the findings.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-009",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Business analyst: Companies that offer flexible work arrangements consistently report higher employee satisfaction scores. Therefore, businesses that want to improve employee morale should implement flexible work policies.`,
    questionStem: "Which one of the following, if true, most seriously weakens the analyst's argument?",
    answerChoices: [
      { letter: "A", text: "Some employees prefer traditional fixed schedules" },
      { letter: "B", text: "Flexible work arrangements can make team coordination more difficult" },
      { letter: "C", text: "Companies with high employee satisfaction are more likely to be able to afford flexible arrangements" },
      { letter: "D", text: "Employee satisfaction is influenced by many factors besides work arrangements" },
      { letter: "E", text: "Not all types of businesses can offer flexible work arrangements" },
    ],
    correctAnswer: "C",
    explanation: "This answer suggests reverse causation: rather than flexible arrangements causing high satisfaction, high satisfaction (or the factors that create it, like financial success) enables companies to offer flexibility. This weakens the claim that implementing flexibility will improve morale.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-010",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should not build a new sports stadium using public funds. Professional sports teams generate enormous revenues and their owners are typically wealthy individuals or corporations. There is no justification for ordinary taxpayers to subsidize enterprises that can easily afford to finance their own facilities.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "public funding for stadiums never benefits ordinary taxpayers" },
      { letter: "B", text: "wealthy individuals should not receive any form of public assistance" },
      { letter: "C", text: "the ability to pay for something oneself is relevant to whether public funding is justified" },
      { letter: "D", text: "sports stadiums do not generate significant economic benefits for host cities" },
      { letter: "E", text: "all professional sports team owners are wealthy" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that public funding isn't justified because the teams can afford to pay themselves. This reasoning only works if we assume that the ability to self-finance is a relevant consideration in determining whether public funding is appropriate—otherwise, the premise about wealth wouldn't support the conclusion.",
    difficulty: "hard",
  },
  {
    id: "lr-bank69-011",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Chen: Universities should require all students to take courses in formal logic. Logical reasoning skills are essential for success in any field, and formal training in logic is the most effective way to develop these skills.

Professor Davis: I disagree. While logical reasoning is important, students can develop these skills through various disciplines, including mathematics, philosophy, and even literature. A specific logic requirement is unnecessarily restrictive.`,
    questionStem: "The main point at issue between Professor Chen and Professor Davis is whether",
    answerChoices: [
      { letter: "A", text: "logical reasoning skills are essential for success" },
      { letter: "B", text: "formal logic courses are the best or only way to develop logical reasoning skills" },
      { letter: "C", text: "universities should have any course requirements at all" },
      { letter: "D", text: "mathematics courses teach logical reasoning" },
      { letter: "E", text: "philosophy is a valuable discipline for students to study" },
    ],
    correctAnswer: "B",
    explanation: "Both professors agree that logical reasoning is important. Their disagreement is about whether formal logic courses are necessary to develop these skills—Chen says formal training is 'most effective,' while Davis argues various disciplines can achieve the same goal, making a specific requirement 'unnecessarily restrictive.'",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-012",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Every member of the chess club is either a student or a faculty member. No faculty members attended last night's tournament. Therefore, everyone who attended last night's tournament is a student.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All vegetables are either root vegetables or leafy vegetables. These carrots are root vegetables. Therefore, these carrots are not leafy vegetables." },
      { letter: "B", text: "Every employee is either full-time or part-time. No part-time employees received bonuses. Therefore, everyone who received a bonus is a full-time employee." },
      { letter: "C", text: "All birds can either fly or swim. Penguins cannot fly. Therefore, penguins can swim." },
      { letter: "D", text: "Every book in the library is either fiction or nonfiction. This book is fiction. Therefore, this book is in the library." },
      { letter: "E", text: "All desserts contain either sugar or artificial sweeteners. This cake contains sugar. Therefore, this cake does not contain artificial sweeteners." },
    ],
    correctAnswer: "B",
    explanation: "The original argument has the structure: All X are either A or B; No B did Y; Therefore, all who did Y are A. Answer B matches exactly: All employees are either full-time or part-time; No part-time received bonuses; Therefore, all who received bonuses are full-time.",
    difficulty: "hard",
  },
  {
    id: "lr-bank69-013",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Studies have shown that students who eat breakfast perform better academically than those who skip breakfast. My daughter has been struggling in school, so I've started making sure she eats a nutritious breakfast every morning. Her grades are bound to improve now.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that correlation between breakfast and performance proves causation" },
      { letter: "B", text: "ignores the possibility that the daughter might not like breakfast" },
      { letter: "C", text: "fails to specify what constitutes a 'nutritious' breakfast" },
      { letter: "D", text: "overlooks other factors that might affect academic performance" },
      { letter: "E", text: "relies on studies that may have used different definitions of academic success" },
    ],
    correctAnswer: "D",
    explanation: "While the argument correctly notes a correlation, it assumes that eating breakfast will necessarily improve the daughter's grades, ignoring other factors that could be causing her academic struggles—such as learning difficulties, social problems, or inadequate sleep. Breakfast alone may not address these issues.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have found evidence of a sophisticated astronomical observatory at an ancient site dating back 5,000 years. The structures are precisely aligned with celestial events such as solstices and equinoxes. The researchers conclude that this ancient civilization possessed advanced mathematical and astronomical knowledge.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Similar structures have been found at other ancient sites around the world" },
      { letter: "B", text: "The alignments could not have occurred by chance and require precise calculations to achieve" },
      { letter: "C", text: "Modern astronomers are impressed by the sophistication of ancient observatories" },
      { letter: "D", text: "The ancient civilization left no written records of their astronomical observations" },
      { letter: "E", text: "Other ancient civilizations are known to have possessed astronomical knowledge" },
    ],
    correctAnswer: "B",
    explanation: "If the precise alignments require sophisticated calculations and couldn't occur by accident, this directly supports the conclusion that the builders possessed advanced mathematical and astronomical knowledge. It rules out the alternative explanation that the alignments might be coincidental.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Educational reformers argue that replacing textbooks with tablets will improve student learning outcomes. They point to studies showing that students using tablets score higher on tests than those using traditional textbooks.`,
    questionStem: "Which one of the following, if true, most weakens the reformers' argument?",
    answerChoices: [
      { letter: "A", text: "Tablets are more expensive than textbooks" },
      { letter: "B", text: "The studies were conducted in well-funded schools where students also received additional tutoring and smaller class sizes" },
      { letter: "C", text: "Some teachers prefer using traditional textbooks" },
      { letter: "D", text: "Tablets require regular software updates to function properly" },
      { letter: "E", text: "Not all subjects are equally well-suited to tablet-based learning" },
    ],
    correctAnswer: "B",
    explanation: "If the studies were conducted in schools with additional advantages like tutoring and smaller classes, the improved test scores might be due to these factors rather than the tablets themselves. This confounding variable weakens the claim that tablets specifically cause better learning outcomes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-016",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The proposed law would require all cyclists to wear helmets while riding on public roads. Since the law would reduce head injuries among cyclists, it should be enacted.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Cyclists who currently wear helmets would continue to do so" },
      { letter: "B", text: "Reducing head injuries is sufficient reason to enact a law" },
      { letter: "C", text: "Most cyclists currently do not wear helmets" },
      { letter: "D", text: "Head injuries are the most common type of cycling injury" },
      { letter: "E", text: "Helmets are effective at preventing all types of cycling injuries" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'the law would reduce head injuries' to 'the law should be enacted.' This assumes that reducing head injuries is a sufficient justification for the law, without considering whether other factors (personal freedom, enforcement costs, etc.) might outweigh this benefit.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-017",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All of the paintings in the west wing of the museum were created in the 19th century. Some of the paintings in the west wing are by French artists. The museum's most valuable painting is in the east wing.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "The museum's most valuable painting was not created in the 19th century" },
      { letter: "B", text: "Some paintings by French artists were created in the 19th century" },
      { letter: "C", text: "All French paintings in the museum are in the west wing" },
      { letter: "D", text: "The museum has no 19th-century paintings in the east wing" },
      { letter: "E", text: "The most valuable painting is not by a French artist" },
    ],
    correctAnswer: "B",
    explanation: "We know: (1) All west wing paintings are from the 19th century, and (2) Some west wing paintings are by French artists. It necessarily follows that some paintings by French artists were created in the 19th century (those French paintings in the west wing).",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-018",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Politician: My opponent claims we need to increase funding for public transportation. But public transportation ridership has been declining for years. Why should we throw more money at a system that fewer and fewer people want to use?`,
    questionStem: "The politician's argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that increased funding might reverse the ridership decline" },
      { letter: "B", text: "assumes the opponent's only reason for supporting funding is current ridership levels" },
      { letter: "C", text: "does not provide specific data about ridership trends" },
      { letter: "D", text: "ignores the environmental benefits of public transportation" },
      { letter: "E", text: "attacks the opponent personally rather than addressing the policy" },
    ],
    correctAnswer: "A",
    explanation: "The politician assumes that declining ridership is a reason not to fund public transportation, but fails to consider that the decline might be caused by inadequate funding in the first place. Increased funding could improve service quality and reverse the decline, making current ridership trends an inadequate basis for the conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-019",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The ancient texts describe a powerful earthquake that destroyed the city around 1500 BCE. However, geological surveys have found no evidence of seismic activity in the region during that period. I believe the texts are describing a different type of disaster—possibly a massive fire or invasion—using metaphorical language that later readers interpreted literally.`,
    questionStem: "Which one of the following, if true, most strengthens the historian's interpretation?",
    answerChoices: [
      { letter: "A", text: "Archaeological evidence shows extensive fire damage to buildings from that era" },
      { letter: "B", text: "The ancient language used in the texts is difficult to translate accurately" },
      { letter: "C", text: "Other ancient civilizations used similar metaphorical descriptions of disasters" },
      { letter: "D", text: "Geological surveys sometimes fail to detect ancient seismic activity" },
      { letter: "E", text: "The city was eventually rebuilt in a different location" },
    ],
    correctAnswer: "A",
    explanation: "If archaeological evidence shows fire damage from the relevant period, this directly supports the historian's hypothesis that the 'earthquake' described in the texts was actually a fire interpreted metaphorically. This provides positive evidence for the alternative explanation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A technology company argues that its facial recognition software should be used by law enforcement because it has a 99% accuracy rate in controlled testing conditions. This high accuracy rate, they claim, ensures that innocent people will rarely be misidentified.`,
    questionStem: "Which one of the following, if true, most seriously weakens the company's argument?",
    answerChoices: [
      { letter: "A", text: "Other facial recognition systems have lower accuracy rates" },
      { letter: "B", text: "The software performs significantly worse on faces of certain demographic groups" },
      { letter: "C", text: "Some law enforcement agencies have already adopted similar technology" },
      { letter: "D", text: "Controlled testing conditions are designed to optimize software performance" },
      { letter: "E", text: "Privacy advocates have raised concerns about facial recognition technology" },
    ],
    correctAnswer: "B",
    explanation: "If the software performs worse on certain demographic groups, then the 99% overall accuracy rate masks significant disparities. Some groups would face much higher rates of misidentification, undermining the claim that 'innocent people will rarely be misidentified' and raising serious fairness concerns.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-021",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Wildlife biologist: The wolf population in the northern region has doubled over the past decade. Since wolves prey primarily on deer, and the deer population has remained stable during this period, the wolves must be obtaining food from other sources.`,
    questionStem: "The biologist's argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "wolves cannot survive without preying on deer" },
      { letter: "B", text: "a doubled wolf population would normally reduce the deer population" },
      { letter: "C", text: "the deer population would have increased if not for wolf predation" },
      { letter: "D", text: "other predators have not moved into the region" },
      { letter: "E", text: "the deer population data is accurate" },
    ],
    correctAnswer: "B",
    explanation: "The biologist reasons that since wolves doubled but deer stayed stable, wolves must have other food sources. This only follows if we assume that a doubled wolf population eating primarily deer would normally cause the deer population to decline. Otherwise, the stable deer population wouldn't be surprising.",
    difficulty: "hard",
  },
  {
    id: "lr-bank69-022",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some philosophers argue that free will is an illusion because all our actions are determined by prior causes. However, our legal system is built on the assumption that people are responsible for their choices. If free will were truly an illusion, it would make no sense to punish anyone for their actions. Since we do hold people responsible and this practice serves important social functions, we have pragmatic reasons to act as if free will exists, regardless of the metaphysical truth.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Free will is not actually an illusion" },
      { letter: "B", text: "The legal system assumes people are responsible for their choices" },
      { letter: "C", text: "We have practical reasons to treat free will as real even if its existence is uncertain" },
      { letter: "D", text: "Punishment makes no sense if determinism is true" },
      { letter: "E", text: "Some philosophers believe all actions are determined by prior causes" },
    ],
    correctAnswer: "C",
    explanation: "The argument doesn't claim to resolve whether free will exists metaphysically. Instead, it concludes that we have 'pragmatic reasons to act as if free will exists, regardless of the metaphysical truth'—essentially arguing for a practical stance rather than making a claim about ultimate reality.",
    difficulty: "hard",
  },
  {
    id: "lr-bank69-023",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution claims my client committed the robbery at 9 PM because a witness saw someone matching his description near the scene. But my client was at a restaurant five miles away at 9 PM, as confirmed by credit card records and testimony from the restaurant staff. Therefore, the witness must have seen someone else.`,
    questionStem: "The defense attorney's argument employs which one of the following methods of reasoning?",
    answerChoices: [
      { letter: "A", text: "Providing an alternative explanation for the evidence presented by the prosecution" },
      { letter: "B", text: "Showing that the prosecution's evidence is internally contradictory" },
      { letter: "C", text: "Establishing an alibi that makes the prosecution's claim impossible" },
      { letter: "D", text: "Attacking the credibility of the prosecution's witness" },
      { letter: "E", text: "Arguing that the prosecution has the burden of proof" },
    ],
    correctAnswer: "C",
    explanation: "The attorney presents evidence that the client was elsewhere at the time of the crime, making it physically impossible for the client to have been the person seen near the scene. This is establishing an alibi, which logically refutes the prosecution's claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-024",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Music critic: Jazz music is clearly superior to pop music. Jazz requires years of training to perform well, while anyone can produce a pop song with basic equipment. The complexity of jazz harmonies and improvisational demands make it a more sophisticated art form.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that technical difficulty is the primary measure of artistic merit" },
      { letter: "B", text: "ignores the commercial success of pop music" },
      { letter: "C", text: "fails to define what constitutes 'sophistication' in music" },
      { letter: "D", text: "overlooks the historical development of jazz from simpler forms" },
      { letter: "E", text: "does not consider the opinions of jazz and pop musicians themselves" },
    ],
    correctAnswer: "A",
    explanation: "The critic equates technical difficulty and complexity with artistic superiority. However, this assumes that the difficulty of creation determines the value of art, which is a contestable assumption. Art can be profound, moving, or beautiful without being technically complex.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-025",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: People who regularly consume fermented foods like yogurt and kimchi tend to have healthier gut microbiomes. A healthy gut microbiome has been linked to improved mental health outcomes. Therefore, eating fermented foods may help reduce symptoms of depression and anxiety.`,
    questionStem: "Which one of the following, if true, most strengthens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Fermented foods have been consumed by humans for thousands of years" },
      { letter: "B", text: "Clinical trials have shown that probiotic supplements can reduce anxiety symptoms in some patients" },
      { letter: "C", text: "Many people find fermented foods to be an acquired taste" },
      { letter: "D", text: "The gut microbiome can be affected by many factors besides diet" },
      { letter: "E", text: "Depression and anxiety are complex conditions with multiple causes" },
    ],
    correctAnswer: "B",
    explanation: "The nutritionist's argument connects fermented foods to gut health to mental health. If clinical trials show that probiotics (which are the beneficial bacteria in fermented foods) can reduce anxiety, this provides direct evidence supporting the causal chain the nutritionist proposes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Company executive: Our new open-office design will improve collaboration among employees. When workers can see and easily communicate with their colleagues, they share ideas more freely and work together more effectively.`,
    questionStem: "Which one of the following, if true, most weakens the executive's argument?",
    answerChoices: [
      { letter: "A", text: "Open offices cost less to build than traditional office designs" },
      { letter: "B", text: "Some employees prefer having private offices" },
      { letter: "C", text: "Studies show that employees in open offices communicate less in person and more through email to avoid disturbing others" },
      { letter: "D", text: "Not all types of work require collaboration" },
      { letter: "E", text: "The company has used traditional office designs for many years" },
    ],
    correctAnswer: "C",
    explanation: "The executive assumes that physical proximity leads to more face-to-face collaboration. If studies show that open offices actually decrease in-person communication because people avoid disturbing colleagues, this directly contradicts the executive's reasoning and weakens the argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city council should approve the new housing development. The project will create hundreds of construction jobs and bring new residents who will support local businesses. Critics who oppose the development on environmental grounds are simply ignoring the economic needs of our community.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Economic benefits always outweigh environmental concerns" },
      { letter: "B", text: "The construction jobs will be filled by local residents" },
      { letter: "C", text: "The critics have not considered the economic benefits" },
      { letter: "D", text: "All housing developments provide economic benefits" },
      { letter: "E", text: "Environmental concerns cannot coexist with economic development" },
    ],
    correctAnswer: "C",
    explanation: "The argument accuses critics of 'ignoring the economic needs.' This assumes that the critics haven't considered the economic benefits. But critics might have considered these benefits and still concluded that environmental concerns outweigh them—the argument assumes they haven't done this analysis.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-028",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Patel: Gene editing technology should be prohibited in human embryos. The long-term effects are unknown, and we risk creating unforeseen genetic problems that could affect future generations.

Dr. Roberts: The potential benefits of eliminating hereditary diseases justify careful research into gene editing. With proper oversight, we can develop this technology safely and help countless families avoid devastating genetic conditions.`,
    questionStem: "Dr. Patel and Dr. Roberts disagree about whether",
    answerChoices: [
      { letter: "A", text: "gene editing technology has potential medical benefits" },
      { letter: "B", text: "the risks of gene editing technology can be managed to permit research" },
      { letter: "C", text: "hereditary diseases cause suffering for families" },
      { letter: "D", text: "the long-term effects of gene editing are fully understood" },
      { letter: "E", text: "gene editing research requires oversight" },
    ],
    correctAnswer: "B",
    explanation: "Dr. Patel believes the risks require prohibition, while Dr. Roberts believes proper oversight can make research safe. They agree that there are risks (Patel explicitly, Roberts implicitly through calling for oversight), but disagree about whether those risks can be managed to allow research to proceed.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-029",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If a restaurant receives a health code violation, it must close for inspection. Café Luna did not close for inspection last month. Therefore, Café Luna did not receive a health code violation last month.`,
    questionStem: "The pattern of reasoning in the argument is most closely paralleled by which one of the following?",
    answerChoices: [
      { letter: "A", text: "If a student misses the final exam, they fail the course. Jordan failed the course. Therefore, Jordan missed the final exam." },
      { letter: "B", text: "If an employee is promoted, they receive a raise. Chen received a raise. Therefore, Chen was promoted." },
      { letter: "C", text: "If a package is fragile, it requires special handling. This package doesn't require special handling. Therefore, this package is not fragile." },
      { letter: "D", text: "If it rains, the game is canceled. It rained yesterday. Therefore, the game was canceled." },
      { letter: "E", text: "If a plant gets enough water, it will thrive. This plant is not thriving. Therefore, this plant is getting enough water." },
    ],
    correctAnswer: "C",
    explanation: "The original argument uses modus tollens: If P then Q; Not Q; Therefore, not P. Answer C follows the same valid form: If package is fragile, then special handling; No special handling; Therefore, not fragile.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-030",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `CEO: Investing in renewable energy is a waste of resources for our company. Our competitor, Acme Industries, invested heavily in solar power five years ago, and their stock price has underperformed the market since then. Clearly, renewable energy investments hurt company performance.`,
    questionStem: "The CEO's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "ignores the environmental benefits of renewable energy" },
      { letter: "B", text: "generalizes from a single example that may not be representative" },
      { letter: "C", text: "assumes that stock price is the only measure of company performance" },
      { letter: "D", text: "fails to consider the long-term benefits of renewable energy" },
      { letter: "E", text: "does not explain why Acme Industries chose to invest in solar power" },
    ],
    correctAnswer: "B",
    explanation: "The CEO draws a broad conclusion about renewable energy investments based solely on one company's experience. This single example could be unrepresentative due to factors specific to Acme Industries, and many other companies may have had different results. The sample size is far too small to support the general claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-031",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Anthropologist: Ancient cave paintings found across Europe depict remarkably similar symbols despite being created thousands of miles apart by groups with no known contact. These shared symbols suggest the existence of a common ancestral culture that predates the migration of humans across Europe.`,
    questionStem: "Which one of the following, if true, most strengthens the anthropologist's argument?",
    answerChoices: [
      { letter: "A", text: "The cave paintings were created using similar pigments derived from local materials" },
      { letter: "B", text: "Genetic evidence shows that European populations share a common ancestor from approximately the same period as the oldest paintings" },
      { letter: "C", text: "Some symbols appear more frequently in certain regions than others" },
      { letter: "D", text: "Modern artists sometimes independently create similar designs" },
      { letter: "E", text: "The caves were used for habitation as well as artistic purposes" },
    ],
    correctAnswer: "B",
    explanation: "Genetic evidence of a common ancestor from the same time period as the paintings supports the anthropologist's hypothesis that the shared symbols derive from a common ancestral culture. This provides independent evidence confirming the proposed cultural connection.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-032",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Editorial: The rise in childhood obesity can be attributed to increased screen time. Children today spend far more time watching television and playing video games than children did thirty years ago, and obesity rates have risen in parallel.`,
    questionStem: "Which one of the following, if true, most weakens the editorial's argument?",
    answerChoices: [
      { letter: "A", text: "Some children who spend significant time on screens maintain healthy weights" },
      { letter: "B", text: "Screen time has increased among adults as well as children" },
      { letter: "C", text: "Children's dietary patterns have changed significantly over the same period, with increased consumption of processed foods" },
      { letter: "D", text: "Physical education requirements in schools have not changed substantially" },
      { letter: "E", text: "Obesity rates vary across different demographic groups" },
    ],
    correctAnswer: "C",
    explanation: "The editorial assumes that the parallel increase in screen time and obesity means screen time causes obesity. But if dietary patterns also changed significantly during the same period, the increased consumption of processed foods could be the real cause—or a major contributing factor—making screen time a mere correlation, not a cause.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Autonomous vehicles should be programmed to minimize total harm in accident scenarios, even if this means sacrificing the vehicle's passengers to save a larger number of pedestrians. Moral philosophy teaches us that we should act to produce the greatest good for the greatest number.`,
    questionStem: "The ethicist's argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "autonomous vehicles will eventually be safer than human-driven vehicles" },
      { letter: "B", text: "utilitarian principles should govern the programming of autonomous vehicles" },
      { letter: "C", text: "pedestrians are more valuable than vehicle passengers" },
      { letter: "D", text: "autonomous vehicles can accurately assess the number of people at risk" },
      { letter: "E", text: "manufacturers of autonomous vehicles agree with this ethical approach" },
    ],
    correctAnswer: "B",
    explanation: "The ethicist applies utilitarian reasoning ('greatest good for the greatest number') to conclude how vehicles should be programmed. This assumes that utilitarian principles are the correct moral framework to apply to this situation. Other ethical frameworks might prioritize the passengers' rights or reject the calculation of harm in this way.",
    difficulty: "hard",
  },
  {
    id: "lr-bank69-034",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Literary critic: Some scholars dismiss genre fiction as unworthy of serious study. But consider that many works now considered literary classics, such as Frankenstein and Dracula, were originally published as popular genre novels. The distinction between 'literary' and 'genre' fiction is arbitrary and shifts over time based on cultural attitudes rather than intrinsic qualities of the works.`,
    questionStem: "The literary critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "demonstrating that the scholars' position is self-contradictory" },
      { letter: "B", text: "using historical examples to challenge a categorical distinction" },
      { letter: "C", text: "appealing to the authority of past literary judgments" },
      { letter: "D", text: "arguing that popularity is a reliable indicator of literary merit" },
      { letter: "E", text: "showing that scholars disagree among themselves about genre fiction" },
    ],
    correctAnswer: "B",
    explanation: "The critic uses historical examples (Frankenstein, Dracula) of works that moved from 'genre' to 'classic' status to argue that the literary/genre distinction is not based on fixed qualities but changes with cultural attitudes. This challenges the scholars' categorical dismissal of genre fiction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-035",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The unemployment rate has decreased every quarter for the past two years. The government's economic policies are therefore working effectively to create jobs.`,
    questionStem: "The economist's argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes the government's policies are the cause of the unemployment decrease" },
      { letter: "B", text: "fails to consider whether the unemployment data is accurate" },
      { letter: "C", text: "does not specify which government policies are being discussed" },
      { letter: "D", text: "ignores the possibility that unemployment could increase in the future" },
      { letter: "E", text: "equates low unemployment with overall economic health" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes causation from correlation. Just because unemployment decreased while the government's policies were in effect doesn't prove the policies caused the decrease. Other factors—global economic trends, technological changes, demographic shifts—could be responsible.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-036",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Political scientist: Mandatory voting laws increase political participation and lead to governments that better represent the interests of all citizens, not just those motivated to vote voluntarily. Countries with mandatory voting consistently have higher turnout rates and policies that favor a broader range of social interests.`,
    questionStem: "Which one of the following, if true, most strengthens the political scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Countries with mandatory voting have different historical and cultural traditions than those without" },
      { letter: "B", text: "Voter turnout in countries without mandatory voting has been declining" },
      { letter: "C", text: "Research shows that non-voters in voluntary systems tend to have systematically different policy preferences than voters" },
      { letter: "D", text: "Mandatory voting laws include provisions for those who cannot physically get to polling places" },
      { letter: "E", text: "Some citizens in countries with mandatory voting cast blank ballots" },
    ],
    correctAnswer: "C",
    explanation: "If non-voters have systematically different preferences than voters, then a voluntary system produces governments that represent only voters' interests, not all citizens'. Mandatory voting would therefore ensure these excluded perspectives are represented, directly supporting the claim that such laws lead to more representative governments.",
    difficulty: "hard",
  },
  {
    id: "lr-bank69-037",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Marketing analyst: Our customer survey shows that 85% of respondents prefer our brand over competitors. This demonstrates strong customer loyalty and suggests our market position is secure.`,
    questionStem: "Which one of the following, if true, most seriously weakens the analyst's conclusion?",
    answerChoices: [
      { letter: "A", text: "The survey was conducted only among customers who had recently made purchases from the company" },
      { letter: "B", text: "Some respondents may have misunderstood the survey questions" },
      { letter: "C", text: "The company has been in business for over twenty years" },
      { letter: "D", text: "Customer preferences can change quickly in response to new products" },
      { letter: "E", text: "The survey included customers from multiple regions" },
    ],
    correctAnswer: "A",
    explanation: "If the survey only included recent customers, it's sampling from people who already chose this brand—a biased sample that would naturally show high preference. Former customers who switched to competitors and potential customers who never chose the brand are excluded, making the 85% figure misleading about actual market position.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-038",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `School board member: We should eliminate the physical education requirement for high school students. Many students participate in sports or other physical activities outside of school, making the requirement redundant. Moreover, students could use that time to take additional academic courses.`,
    questionStem: "The school board member's argument assumes that",
    answerChoices: [
      { letter: "A", text: "all students who would be affected already participate in outside physical activities" },
      { letter: "B", text: "academic courses are more valuable than physical education" },
      { letter: "C", text: "students would choose to take additional academic courses if given the option" },
      { letter: "D", text: "physical education classes are currently not well taught" },
      { letter: "E", text: "sports teams provide the same benefits as physical education classes" },
    ],
    correctAnswer: "A",
    explanation: "The argument claims the requirement is redundant because 'many students' participate in outside activities. But for the requirement to be truly redundant for all students, all students (or at least all who would be affected) would need such outside activities. If only 'many' but not all do, some students would lose their only source of physical education.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-039",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Social media platforms claim to support free expression, yet they regularly remove content that violates their community standards. Critics call this censorship, but private companies have no legal obligation to host all speech. The First Amendment protects against government censorship, not actions by private entities. So while users may disagree with content moderation decisions, these actions are not censorship in any legally meaningful sense.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Social media platforms support free expression" },
      { letter: "B", text: "Private companies are not legally required to host all speech" },
      { letter: "C", text: "Social media content moderation does not constitute censorship in a legal sense" },
      { letter: "D", text: "The First Amendment only applies to government actions" },
      { letter: "E", text: "Users often disagree with content moderation decisions" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion, signaled by 'So,' is that social media content moderation is 'not censorship in any legally meaningful sense.' The preceding statements about the First Amendment and private companies' lack of legal obligations serve as premises supporting this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: My colleague suggests that the decline in amphibian populations is caused by increased ultraviolet radiation due to ozone depletion. However, amphibian declines have been documented in heavily forested areas where UV radiation cannot penetrate the canopy. This shows that UV radiation cannot be the primary cause of the decline.`,
    questionStem: "The scientist responds to the colleague's hypothesis by",
    answerChoices: [
      { letter: "A", text: "proposing an alternative explanation for the phenomenon" },
      { letter: "B", text: "questioning the reliability of the data on amphibian decline" },
      { letter: "C", text: "citing evidence that is inconsistent with the proposed cause" },
      { letter: "D", text: "arguing that correlation does not imply causation" },
      { letter: "E", text: "demonstrating that the colleague's research methods were flawed" },
    ],
    correctAnswer: "C",
    explanation: "The scientist presents evidence (declines in forested areas without UV penetration) that contradicts the colleague's UV hypothesis. If UV radiation were the primary cause, we wouldn't expect to see declines in areas protected from UV—but we do, which is inconsistent with the proposed cause.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-041",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Letters to the editor show overwhelming opposition to the proposed highway expansion—over 90% of published letters argue against the project. The newspaper should acknowledge that the community does not support this plan.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that newspaper readers represent the entire community" },
      { letter: "B", text: "overlooks the possibility that supporters may be less likely to write letters" },
      { letter: "C", text: "fails to consider the environmental impact of the highway expansion" },
      { letter: "D", text: "does not specify how many letters were published" },
      { letter: "E", text: "ignores the newspaper's own editorial position on the project" },
    ],
    correctAnswer: "B",
    explanation: "The argument uses letters to the editor as evidence of community opinion, but people opposed to something are often more motivated to write than supporters. This self-selection bias means the letters may not represent overall community sentiment—supporters may simply not be writing.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-042",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Veterinarian: Pet owners often resist having their animals vaccinated, citing concerns about side effects. However, the diseases prevented by vaccines are far more dangerous than any potential side effects. Vaccination is essential for protecting not only individual pets but also the broader animal population through herd immunity.`,
    questionStem: "Which one of the following, if true, most strengthens the veterinarian's argument?",
    answerChoices: [
      { letter: "A", text: "Vaccine side effects in pets are typically mild and temporary, while the diseases they prevent are often fatal" },
      { letter: "B", text: "Some pet owners cannot afford regular veterinary care including vaccinations" },
      { letter: "C", text: "Pet vaccination rates have declined in recent years" },
      { letter: "D", text: "Veterinarians receive training in vaccine administration" },
      { letter: "E", text: "Wild animals can also carry diseases that affect domestic pets" },
    ],
    correctAnswer: "A",
    explanation: "The veterinarian claims vaccines' benefits outweigh their risks. Evidence that side effects are 'mild and temporary' while prevented diseases are 'often fatal' directly supports this risk-benefit comparison, strengthening the argument for vaccination.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-043",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Art dealer: Paintings created during an artist's final years are typically more valuable than their earlier works. Van Gogh's late paintings sell for far more than his early pieces. This is because collectors recognize that an artist's mature style represents the culmination of their creative development.`,
    questionStem: "Which one of the following, if true, most weakens the art dealer's explanation?",
    answerChoices: [
      { letter: "A", text: "Some artists produce their most innovative work early in their careers" },
      { letter: "B", text: "Van Gogh's early works are more numerous than his late works" },
      { letter: "C", text: "Art dealers often have an incentive to sell late works at higher prices" },
      { letter: "D", text: "Late works are more valuable primarily because artists typically produce fewer works at the end of their careers, making them rarer" },
      { letter: "E", text: "Some collectors prefer to specialize in acquiring artists' early works" },
    ],
    correctAnswer: "D",
    explanation: "The dealer explains higher prices for late works as recognition of 'mature style' and 'creative culmination.' But if the real reason is simply scarcity—artists produce fewer works late in their careers—then the explanation about artistic development is incorrect. This alternative explanation weakens the dealer's argument.",
    difficulty: "hard",
  },
  {
    id: "lr-bank69-044",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The new traffic law requires all cyclists to use bike lanes where available. This law will reduce accidents between cyclists and motorists because it separates the two groups into different parts of the roadway.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Most accidents between cyclists and motorists occur where bike lanes exist" },
      { letter: "B", text: "Cyclists will comply with the new law" },
      { letter: "C", text: "Bike lanes are safer than regular traffic lanes for cyclists" },
      { letter: "D", text: "The new law will be strictly enforced" },
      { letter: "E", text: "Motorists prefer not to share the road with cyclists" },
    ],
    correctAnswer: "B",
    explanation: "The argument predicts that requiring cyclists to use bike lanes will reduce accidents. This conclusion depends on cyclists actually following the law. If cyclists don't comply, the separation won't occur and accidents won't decrease, so compliance is a necessary assumption.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Harrison: Academic research should be made freely available to the public. Taxpayers fund much of this research, so they should have access to the results without paying additional fees to publishers.

Publisher representative: While public access is a worthy goal, publishers provide essential services including peer review coordination and quality control. Without subscription revenue, these services could not be maintained, ultimately harming the quality of research.`,
    questionStem: "Professor Harrison and the publisher representative disagree about whether",
    answerChoices: [
      { letter: "A", text: "taxpayers fund academic research" },
      { letter: "B", text: "publishers provide valuable services to the research community" },
      { letter: "C", text: "the current publishing model should be changed to provide free public access" },
      { letter: "D", text: "peer review is an essential component of academic publishing" },
      { letter: "E", text: "research quality is important to maintain" },
    ],
    correctAnswer: "C",
    explanation: "Professor Harrison argues research should be freely available (implying the current model should change), while the publisher representative argues against removing subscription revenue (defending the current model). Both might agree publishers provide services and that quality matters, but they disagree about whether to change the access model.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All of the evidence presented at the trial was circumstantial. Some circumstantial evidence can be compelling. Therefore, some of the evidence presented at the trial might have been compelling.`,
    questionStem: "The reasoning in the argument is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All of the students in the class are freshmen. Some freshmen struggle with the coursework. Therefore, some students in the class might struggle with the coursework." },
      { letter: "B", text: "Every dish at the restaurant is vegetarian. Some vegetarian dishes are delicious. Therefore, every dish at the restaurant is delicious." },
      { letter: "C", text: "All employees received a bonus. All bonuses were substantial. Therefore, all employees received a substantial bonus." },
      { letter: "D", text: "Some of the paintings in the gallery are abstract. All abstract paintings are modern. Therefore, some paintings in the gallery are modern." },
      { letter: "E", text: "None of the candidates were qualified. Some unqualified candidates can still succeed. Therefore, some candidates will succeed." },
    ],
    correctAnswer: "A",
    explanation: "The original argument: All X are Y; Some Y are Z; Therefore, some X might be Z. Answer A follows the same pattern: All class students are freshmen; Some freshmen struggle; Therefore, some class students might struggle. Both correctly note that the possibility exists without certainty.",
    difficulty: "hard",
  },
  {
    id: "lr-bank69-047",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Researcher: Our study found no statistically significant evidence that the new treatment is effective. Therefore, we can conclude that the treatment does not work.`,
    questionStem: "The researcher's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on a single study rather than multiple studies" },
      { letter: "B", text: "confuses the absence of evidence for an effect with evidence that there is no effect" },
      { letter: "C", text: "fails to consider whether the treatment might have harmful side effects" },
      { letter: "D", text: "does not specify the sample size used in the study" },
      { letter: "E", text: "assumes that statistical significance is the only measure of treatment effectiveness" },
    ],
    correctAnswer: "B",
    explanation: "The researcher commits the fallacy of interpreting 'no significant evidence of effectiveness' as 'evidence of no effectiveness.' A study might fail to detect an effect due to small sample size, measurement issues, or other factors—absence of evidence is not the same as evidence of absence.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-048",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Urban planner: Converting downtown parking lots into parks and green spaces will revitalize the city center. Other cities that have made similar conversions have seen increased foot traffic, new business openings, and rising property values in surrounding areas.`,
    questionStem: "Which one of the following, if true, most strengthens the urban planner's argument?",
    answerChoices: [
      { letter: "A", text: "Downtown areas in general have experienced decline over the past several decades" },
      { letter: "B", text: "The cities cited by the planner are similar in size, demographics, and economic conditions to this city" },
      { letter: "C", text: "Some downtown business owners prefer having nearby parking for their customers" },
      { letter: "D", text: "Parks require ongoing maintenance that can be expensive for city budgets" },
      { letter: "E", text: "The parking lots in question are currently underutilized" },
    ],
    correctAnswer: "B",
    explanation: "The planner argues from examples of other cities. If those cities are similar to this one in relevant ways (size, demographics, economics), the comparison is more valid and the prediction more likely to hold. This strengthens the analogical reasoning.",
    difficulty: "medium",
  },
  {
    id: "lr-bank69-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The library's special collections include rare books that cannot be checked out. All items in special collections must be viewed in the reading room under staff supervision. The manuscript collection is part of special collections. Visitors may access the reading room only during specific hours.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All rare books in the library are in special collections" },
      { letter: "B", text: "Manuscripts in the collection cannot be checked out" },
      { letter: "C", text: "The reading room is only used for viewing special collections" },
      { letter: "D", text: "Staff supervision is available during all library hours" },
      { letter: "E", text: "Visitors may not touch items in special collections" },
    ],
    correctAnswer: "B",
    explanation: "We know: (1) Special collections items cannot be checked out, and (2) The manuscript collection is part of special collections. It follows necessarily that manuscripts cannot be checked out, since they belong to a category (special collections) whose items cannot be checked out.",
    difficulty: "easy",
  },
  {
    id: "lr-bank69-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Citizens should not be concerned about the government's new surveillance program. The program only collects metadata—information about communications rather than their content. Since the government isn't listening to your conversations, your privacy is not being violated.`,
    questionStem: "The argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that metadata collection might deter people from exercising free speech" },
      { letter: "B", text: "assumes that privacy can only be violated by accessing the content of communications" },
      { letter: "C", text: "ignores the possibility that the surveillance program might be expanded in the future" },
      { letter: "D", text: "does not address whether the surveillance program is effective at achieving its goals" },
      { letter: "E", text: "relies on a technical distinction that ordinary citizens may not understand" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that privacy violation requires accessing content, not just metadata. However, metadata can reveal highly personal information—who you contact, when, how often, your location patterns. The argument's definition of privacy is too narrow, assuming content access is necessary for privacy violation.",
    difficulty: "hard",
  },
];
