// Logical Reasoning Questions Bank - Set 46
import { Question } from "../lsat-types";

export const lrQuestionsSet46: Question[] = [
  {
    id: "lr-bank46-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during work are more productive than those who work continuously. Therefore, companies should require all employees to take mandatory breaks every hour, as this will certainly increase overall productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that productivity might be measured differently across industries" },
      { letter: "B", text: "assumes that what is true of voluntary behavior will also be true when that behavior is mandated" },
      { letter: "C", text: "relies on a study without specifying the number of participants" },
      { letter: "D", text: "overlooks the possibility that some employees already take regular breaks" },
      { letter: "E", text: "confuses correlation between two events with a causal relationship" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that mandatory breaks will have the same positive effect as voluntary breaks. However, when behavior is required rather than chosen, the psychological and practical effects may differ significantly. Employees who voluntarily take breaks may do so because they recognize their own need for rest, while mandatory breaks might interrupt employees during peak productivity periods.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeological evidence suggests that the ancient city of Tarum was abandoned suddenly around 1200 BCE. Researchers have proposed that a severe drought caused the abandonment. Soil samples from the region show significantly decreased rainfall during that period, and many wells in the area appear to have been deepened multiple times before being abandoned entirely.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Other cities in the region that had access to river water continued to thrive during the same period" },
      { letter: "B", text: "The city of Tarum was known to be a major trading center before its abandonment" },
      { letter: "C", text: "Archaeological evidence of warfare has been found at several sites from this era" },
      { letter: "D", text: "The population of Tarum had been growing rapidly in the century before the abandonment" },
      { letter: "E", text: "Similar soil conditions have been found at other abandoned cities from different time periods" },
    ],
    correctAnswer: "A",
    explanation: "If cities with access to river water survived while Tarum (presumably dependent on rainfall and wells) was abandoned, this supports the drought hypothesis. It shows that water availability was the critical factor, and those with alternative water sources were able to survive the drought conditions that forced Tarum's abandonment.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company argues that its new medication is safe because clinical trials showed no serious side effects in any of the 500 participants over the six-month study period. Since the trials were conducted according to standard protocols and monitored by independent physicians, we can be confident that the medication poses no significant health risks to patients.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "The medication is intended to treat a chronic condition that typically requires years of continuous treatment" },
      { letter: "B", text: "Some participants reported minor headaches during the first week of the trial" },
      { letter: "C", text: "The independent physicians were compensated for their monitoring services" },
      { letter: "D", text: "Similar medications produced by other companies have been approved using comparable trial protocols" },
      { letter: "E", text: "The clinical trials were conducted at multiple sites across different countries" },
    ],
    correctAnswer: "A",
    explanation: "If the medication is meant for long-term chronic treatment but was only tested for six months, the trials may not have been long enough to detect side effects that emerge with prolonged use. This significantly weakens the claim that the medication poses no significant health risks, as many adverse effects only become apparent after extended periods of use.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Professor Hayes argues that universities should eliminate tenure for faculty members. She points out that tenured professors have less incentive to remain productive researchers and effective teachers because they cannot be easily dismissed. Without tenure, professors would need to continuously demonstrate their value, leading to better educational outcomes for students.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Most tenured professors are currently unproductive researchers" },
      { letter: "B", text: "Job security is the primary factor that motivates professors to be productive" },
      { letter: "C", text: "Students are the best judges of educational quality" },
      { letter: "D", text: "The threat of dismissal would not cause professors to avoid controversial research topics" },
      { letter: "E", text: "Universities would save money by eliminating tenure" },
    ],
    correctAnswer: "D",
    explanation: "The argument assumes that removing tenure would lead to better outcomes without considering potential negative consequences. One major purpose of tenure is to protect academic freedom by allowing professors to pursue controversial research without fear of being fired. The argument assumes this protection is unnecessary or that its loss would not negatively impact educational outcomes.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Digital books have become increasingly popular, with sales rising by 20% annually over the past five years. However, studies consistently show that readers retain information better when reading physical books. Furthermore, many readers report that they find physical books more enjoyable to read. Thus, despite the convenience of digital books, physical books will likely remain an important part of the publishing industry for decades to come.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Digital book sales have been increasing significantly" },
      { letter: "B", text: "Physical books provide better information retention than digital books" },
      { letter: "C", text: "Many readers prefer reading physical books" },
      { letter: "D", text: "Physical books will likely remain important in publishing for a long time" },
      { letter: "E", text: "Digital books are more convenient than physical books" },
    ],
    correctAnswer: "D",
    explanation: "The conclusion is signaled by 'Thus' and states that physical books will likely remain important in publishing for decades. The other statements about digital book sales, information retention, reader preferences, and convenience are all premises supporting this main conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The city council claims that the new downtown development will revitalize the local economy. But consider their track record: they made the same promise about the stadium project five years ago, and that brought no measurable economic benefit. They also promised the convention center would boost tourism, yet hotel occupancy rates have remained flat. Why should we believe them now?`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "presenting statistical evidence that contradicts the council's economic projections" },
      { letter: "B", text: "questioning the council's credibility based on the outcomes of their previous predictions" },
      { letter: "C", text: "arguing that downtown development is generally ineffective at stimulating economic growth" },
      { letter: "D", text: "demonstrating that the council has financial incentives to exaggerate the project's benefits" },
      { letter: "E", text: "showing that the new development is similar in structure to the previous failed projects" },
    ],
    correctAnswer: "B",
    explanation: "The critic attacks the council's credibility by pointing to two previous instances where their predictions of economic benefits did not materialize. This is an ad hominem argument based on track record, questioning whether the council's current claims should be trusted given their history of inaccurate predictions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every successful entrepreneur I have interviewed has mentioned the importance of taking risks. My neighbor frequently takes financial risks with his investments. Therefore, my neighbor is likely to become a successful entrepreneur.`,
    questionStem: "The reasoning in the argument is flawed because the argument",
    answerChoices: [
      { letter: "A", text: "bases a conclusion on an insufficiently representative sample" },
      { letter: "B", text: "treats a characteristic common to successful entrepreneurs as sufficient for success" },
      { letter: "C", text: "fails to consider that different types of risks may have different outcomes" },
      { letter: "D", text: "assumes without justification that financial success leads to entrepreneurial success" },
      { letter: "E", text: "ignores the possibility that the interviewed entrepreneurs were being dishonest" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the fallacy of affirming the consequent. It establishes that successful entrepreneurs take risks, then assumes that anyone who takes risks will be successful. However, risk-taking is presented as a necessary condition for entrepreneurial success, not a sufficient one. Many people take risks without becoming successful entrepreneurs.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A new law requires all food products to display their sugar content prominently on packaging. Supporters argue this will reduce sugar consumption because consumers will make healthier choices when they are aware of how much sugar products contain. Early data from pilot programs in select cities shows a slight decrease in purchases of high-sugar items.`,
    questionStem: "Which one of the following, if true, most strengthens the supporters' argument?",
    answerChoices: [
      { letter: "A", text: "The pilot program cities had higher than average rates of diabetes before the program began" },
      { letter: "B", text: "Surveys show that consumers in pilot cities report paying more attention to nutritional information when shopping" },
      { letter: "C", text: "Food manufacturers have begun reformulating some products to reduce sugar content" },
      { letter: "D", text: "The price of high-sugar items remained stable during the pilot program" },
      { letter: "E", text: "Health organizations endorsed the labeling requirement before it was implemented" },
    ],
    correctAnswer: "D",
    explanation: "If prices remained stable, then the decrease in high-sugar purchases cannot be attributed to price changes and is more likely due to the labeling itself. This rules out an alternative explanation and strengthens the causal connection between prominent sugar labeling and reduced purchases of high-sugar items.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-009",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Studies have shown that students who participate in extracurricular activities tend to have higher grade point averages than students who do not participate in any activities. Clearly, schools should require all students to participate in at least one extracurricular activity to improve overall academic achievement.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some extracurricular activities are more time-consuming than others" },
      { letter: "B", text: "Students with higher academic motivation tend to self-select into extracurricular activities" },
      { letter: "C", text: "Many schools already strongly encourage participation in extracurricular activities" },
      { letter: "D", text: "Some students participate in activities outside of school rather than school-sponsored programs" },
      { letter: "E", text: "Teachers who sponsor extracurricular activities report high levels of job satisfaction" },
    ],
    correctAnswer: "B",
    explanation: "This answer suggests that the correlation between activities and grades is due to self-selection rather than causation. If academically motivated students are more likely to choose to participate in activities, then the activities themselves may not be causing the higher grades. Requiring unmotivated students to participate would not necessarily improve their academic achievement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-010",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should not build the proposed light rail system. The construction would take at least five years, during which time major roads would be closed, causing significant disruption to businesses along the route. Many of these businesses operate on thin margins and could not survive five years of reduced customer traffic.`,
    questionStem: "The argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "the light rail system would not provide significant benefits after completion" },
      { letter: "B", text: "there are no alternative construction methods that would reduce road closures" },
      { letter: "C", text: "the businesses along the route cannot adapt to temporary changes in customer access" },
      { letter: "D", text: "public transportation is not a priority for city residents" },
      { letter: "E", text: "the city has insufficient funds to compensate affected businesses" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that the road closures described are unavoidable. If alternative construction methods existed that could minimize or eliminate road closures, the main premise about business disruption would be undermined. The argument depends on the implicit assumption that there is no way to build the light rail without the extensive road closures mentioned.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-011",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Maria: Artificial intelligence will eventually replace most human workers, including those in creative fields. AI systems are already producing artwork and music that experts cannot distinguish from human-created works. The logical endpoint is machines that exceed human capabilities in every domain.

James: While AI has made impressive advances in pattern recognition and generation, true creativity requires consciousness and lived experience. An AI can mimic creative outputs but cannot understand the meaning behind them. Human creativity will always be distinct from machine imitation.`,
    questionStem: "Maria and James disagree about whether",
    answerChoices: [
      { letter: "A", text: "AI systems can currently produce works indistinguishable from human creations" },
      { letter: "B", text: "pattern recognition is a component of creative work" },
      { letter: "C", text: "AI will eventually be capable of genuine creativity" },
      { letter: "D", text: "consciousness plays a role in human creative processes" },
      { letter: "E", text: "AI has made impressive advances in recent years" },
    ],
    correctAnswer: "C",
    explanation: "Maria believes AI will eventually exceed human capabilities in all domains, including creative ones. James believes that genuine creativity requires consciousness and lived experience, which AI lacks. The core disagreement is whether AI can ever achieve true creativity, not just imitate creative outputs.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-012",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All licensed physicians have completed medical school. Dr. Patterson is a licensed physician. Therefore, Dr. Patterson has completed medical school.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All managers have leadership skills. Sarah wants to be a manager. Therefore, Sarah must develop leadership skills." },
      { letter: "B", text: "All planets orbit stars. Jupiter is a planet. Therefore, Jupiter orbits a star." },
      { letter: "C", text: "All musicians practice regularly. Tom practices regularly. Therefore, Tom is a musician." },
      { letter: "D", text: "All successful businesses have customers. This restaurant has customers. Therefore, this restaurant is successful." },
      { letter: "E", text: "All cats are mammals. Some mammals are domestic. Therefore, some cats are domestic." },
    ],
    correctAnswer: "B",
    explanation: "The original argument follows the valid form: All A are B, X is A, therefore X is B. Answer B follows the same structure: All planets orbit stars (All A are B), Jupiter is a planet (X is A), therefore Jupiter orbits a star (X is B). The other options either reverse the reasoning or introduce additional elements not present in the original argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-013",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The governor claims that the new tax policy will be beneficial because it will encourage business investment in the state. However, the governor received substantial campaign contributions from business owners who would benefit from this policy. This reveals that the governor is simply trying to reward campaign donors rather than help the state's economy.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that a policy could benefit both campaign donors and the general public" },
      { letter: "B", text: "assumes without evidence that all business owners supported the governor's campaign" },
      { letter: "C", text: "treats a correlation between campaign contributions and policy positions as definitive proof of corruption" },
      { letter: "D", text: "ignores the possibility that the tax policy might have unintended negative consequences" },
      { letter: "E", text: "presumes that campaign contributors always expect direct benefits in return for their support" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits a false dilemma by assuming that the policy must either be a genuine economic benefit OR a reward for donors, but not both. It's possible that the policy genuinely encourages business investment (benefiting the state's economy) while also benefiting the donors. The motives and the effects are not mutually exclusive.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers hypothesize that the decline in bee populations over the past two decades is primarily caused by a class of pesticides called neonicotinoids. These pesticides are applied to seeds and become systemic in plants, appearing in pollen and nectar. Studies have shown that even low doses of neonicotinoids impair bees' navigation abilities and immune systems.`,
    questionStem: "Which one of the following, if true, provides the most support for the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Bee populations have declined more rapidly in agricultural areas where neonicotinoids are heavily used than in areas where they are banned" },
      { letter: "B", text: "Neonicotinoids were introduced to the market approximately twenty-five years ago" },
      { letter: "C", text: "Some bee species have shown more resilience to population decline than others" },
      { letter: "D", text: "Alternative pesticides are generally more expensive than neonicotinoids" },
      { letter: "E", text: "Climate change has also been proposed as a factor in bee population decline" },
    ],
    correctAnswer: "A",
    explanation: "This answer provides direct comparative evidence supporting the causal hypothesis. If bee populations decline more in areas with heavy neonicotinoid use and less in areas where they are banned, this correlation between pesticide use and population decline supports the claim that neonicotinoids are the primary cause.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A philosopher argues that free will is an illusion because all of our decisions are determined by prior causes. Brain scanning studies show that neural activity associated with a decision occurs several seconds before a person becomes consciously aware of making that decision. This proves that our conscious experience of choosing is merely an afterthought to processes that have already determined our behavior.`,
    questionStem: "Which one of the following, if true, most weakens the philosopher's argument?",
    answerChoices: [
      { letter: "A", text: "Many philosophical traditions have questioned the existence of free will for centuries" },
      { letter: "B", text: "The brain scans only measured simple motor decisions, not complex moral or life choices" },
      { letter: "C", text: "Some neuroscientists dispute the methodology used in the brain scanning studies" },
      { letter: "D", text: "People generally believe they have free will regardless of scientific evidence" },
      { letter: "E", text: "The concept of moral responsibility may not require libertarian free will" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher generalizes from brain scanning studies to all decisions. If the studies only measured simple motor decisions (like moving a finger), they may not apply to complex decisions involving moral reasoning, long-term planning, or weighing multiple considerations. The argument would be weakened because the evidence base is too narrow to support the sweeping conclusion.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-016",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The company should switch to renewable energy sources for its manufacturing operations. While the initial investment is substantial, renewable energy costs are declining rapidly, and within ten years the company will actually save money compared to continuing with fossil fuels. Additionally, customers increasingly prefer to buy from environmentally responsible companies.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "All of the company's competitors have already switched to renewable energy" },
      { letter: "B", text: "The company will still be in operation ten years from now" },
      { letter: "C", text: "Fossil fuel prices will increase over the next decade" },
      { letter: "D", text: "Customer preferences are the most important factor in business decisions" },
      { letter: "E", text: "Renewable energy technology will continue to improve" },
    ],
    correctAnswer: "B",
    explanation: "The argument's economic justification depends on savings that will materialize in ten years. This implicitly assumes the company will still exist and be operating at that point. If the company were to close or significantly change operations before then, the long-term savings would never be realized, undermining the economic rationale for the switch.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-017",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `In the country of Valdoria, all citizens over age 18 are required by law to vote in national elections. Failure to vote results in a fine equivalent to approximately $50. Despite this requirement, voter turnout in the most recent election was only 78%. The election commission reported that all non-voters were assessed the mandatory fine.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Some Valdorian citizens prefer paying the fine to participating in elections" },
      { letter: "B", text: "The fine is not large enough to effectively encourage voting" },
      { letter: "C", text: "At least some eligible Valdorian voters did not vote in the most recent election despite the legal requirement" },
      { letter: "D", text: "Mandatory voting laws are ineffective at increasing democratic participation" },
      { letter: "E", text: "The 22% who did not vote were all first-time eligible voters" },
    ],
    correctAnswer: "C",
    explanation: "If voter turnout was only 78%, then 22% of eligible voters did not vote. Since all citizens over 18 are required to vote, this means some eligible voters failed to fulfill their legal obligation. This is a direct logical inference from the stated facts. The other options go beyond what can be definitively concluded from the given information.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-018",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The city's traffic engineer claims that adding more lanes to the highway will reduce congestion. But history shows otherwise. When the highway was expanded from four to six lanes in 2005, traffic congestion actually increased over the following years. And when the crosstown expressway was widened in 2012, the same pattern emerged. Adding lanes simply attracts more drivers until congestion returns to previous levels.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "using specific historical examples to challenge a general claim about cause and effect" },
      { letter: "B", text: "demonstrating that the traffic engineer lacks the credentials to make reliable predictions" },
      { letter: "C", text: "showing that the proposed solution would be too expensive to implement effectively" },
      { letter: "D", text: "arguing that traffic congestion is an inevitable consequence of urban development" },
      { letter: "E", text: "establishing that past highway expansions were implemented incorrectly" },
    ],
    correctAnswer: "A",
    explanation: "The argument uses two specific historical examples (the 2005 highway expansion and the 2012 expressway widening) to counter the traffic engineer's general claim that adding lanes reduces congestion. These examples are used to support the alternative principle that adding lanes attracts more drivers, returning congestion to original levels.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-019",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Critics of space exploration argue that the money would be better spent on solving problems here on Earth. However, numerous technologies developed for space programs have had important applications in medicine, communications, and environmental monitoring. Therefore, critics are wrong to suggest that space exploration funding does not benefit people on Earth.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to acknowledge that some space exploration technologies have not had practical applications" },
      { letter: "B", text: "misrepresents the critics' position by addressing a claim they did not make" },
      { letter: "C", text: "assumes that all critics of space exploration share identical views" },
      { letter: "D", text: "provides no evidence that space-derived technologies could not have been developed otherwise" },
      { letter: "E", text: "ignores the possibility that critics might value technological benefits" },
    ],
    correctAnswer: "B",
    explanation: "This is a straw man fallacy. The critics argue that the money would be BETTER spent on Earth-based problems, not that space exploration provides NO benefit to people on Earth. By refuting the claim that space exploration doesn't benefit Earth at all, the argument attacks a position the critics never actually held.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-020",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Paleontologists have discovered fossils of a previously unknown dinosaur species in a region that was coastal during the Cretaceous period. The dinosaur's bone structure shows adaptations similar to those found in modern diving birds, including dense bones and a streamlined body shape. Researchers conclude that this dinosaur species was semi-aquatic and hunted fish in coastal waters.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "The fossils were found in sedimentary rock that also contained fossilized fish scales and shells" },
      { letter: "B", text: "Several other dinosaur species from the same period have been found in the same region" },
      { letter: "C", text: "Modern diving birds evolved their adaptations independently of this dinosaur species" },
      { letter: "D", text: "The dinosaur's teeth were small and numerous, unlike those of most carnivorous dinosaurs" },
      { letter: "E", text: "Dense bones are also found in some land-dwelling animals" },
    ],
    correctAnswer: "A",
    explanation: "Finding the dinosaur fossils alongside fish scales and shells provides environmental evidence that supports the semi-aquatic hypothesis. It suggests the dinosaur lived in proximity to fish and other marine life, which is consistent with the conclusion that it hunted fish in coastal waters.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Market research shows that consumers who are exposed to a brand's advertisements more frequently develop stronger brand loyalty. Our company's advertisements are currently shown an average of twice per week to our target audience. By increasing ad frequency to five times per week, we can significantly strengthen customer loyalty to our brand.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some competitors advertise more frequently than five times per week" },
      { letter: "B", text: "Consumer research indicates that ad frequency beyond a certain threshold creates irritation and negative brand associations" },
      { letter: "C", text: "Television advertising is more expensive than online advertising" },
      { letter: "D", text: "Brand loyalty is only one of many factors that influence purchasing decisions" },
      { letter: "E", text: "The company's current customer base is already highly loyal" },
    ],
    correctAnswer: "B",
    explanation: "This answer suggests that the relationship between ad frequency and brand loyalty is not linear and may even reverse at higher frequencies. If excessive advertising creates irritation and negative associations, then increasing from twice to five times per week might actually decrease brand loyalty rather than strengthen it.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-022",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The mayor argues that the city must build a new convention center to remain economically competitive with neighboring cities. Three nearby cities have recently built convention centers, and they have been successful in attracting major conferences and events. Without a comparable facility, businesses and tourists will increasingly choose these other destinations.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Convention centers are the only way to attract business travelers and tourists" },
      { letter: "B", text: "The city has sufficient funds to build a convention center" },
      { letter: "C", text: "The demand for convention space in the region is sufficient to support an additional facility" },
      { letter: "D", text: "The neighboring cities' convention centers are operating at full capacity" },
      { letter: "E", text: "Conferences and events generate more economic benefit than other forms of tourism" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes there is enough demand for convention space that a new center would actually attract conferences. If the regional market for convention space is already satisfied by the existing centers, a new facility might not succeed in attracting events, undermining the economic competitiveness argument.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-023",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some ethicists argue that we have stronger moral obligations to people who are physically near us than to those who are far away. However, modern technology has made physical distance increasingly irrelevant. We can now communicate instantly with people on the other side of the world and transfer resources globally with ease. Physical proximity, therefore, can no longer serve as a basis for determining the strength of our moral obligations.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Technology has made global communication and resource transfer possible" },
      { letter: "B", text: "Some ethicists believe proximity determines the strength of moral obligations" },
      { letter: "C", text: "Physical distance should not be used to determine the strength of our moral obligations" },
      { letter: "D", text: "We have the same moral obligations to all people regardless of where they live" },
      { letter: "E", text: "Modern technology has made physical distance irrelevant" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion, signaled by 'therefore,' is that physical proximity can no longer serve as a basis for determining moral obligation strength. The points about technology and communication are premises supporting this conclusion. Answer D goes too far - the argument only claims proximity shouldn't matter, not that all obligations are equal.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-024",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of the crime because she has an excellent reputation in the community. She has volunteered at the local hospital for ten years, regularly donates to charity, and has never before been accused of any wrongdoing. A person of such outstanding character simply would not commit such an act.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "assumes that charitable behavior is always motivated by genuine altruism" },
      { letter: "B", text: "fails to consider evidence regarding the specific crime in question" },
      { letter: "C", text: "presumes that a person's past behavior determines their future actions with certainty" },
      { letter: "D", text: "overlooks the possibility that the defendant might have accomplices" },
      { letter: "E", text: "ignores the legal presumption of innocence" },
    ],
    correctAnswer: "B",
    explanation: "The argument relies entirely on character evidence and reputation without addressing any evidence about the actual crime. Good character does not logically preclude the possibility of committing a crime, and the argument should consider the specific evidence regarding the incident in question rather than making assumptions based solely on general reputation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-025",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying ancient climate patterns analyzed ice cores from Greenland containing air bubbles trapped thousands of years ago. They found that methane levels in the atmosphere dropped significantly during a period when human agricultural activity was expanding rapidly. The researchers hypothesize that early farmers drained wetlands for agriculture, which reduced the natural methane emissions from these ecosystems.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Methane is a more potent greenhouse gas than carbon dioxide" },
      { letter: "B", text: "Archaeological evidence shows that wetland drainage for farming was widespread during this period" },
      { letter: "C", text: "Ice core analysis is considered a reliable method for measuring historical atmospheric composition" },
      { letter: "D", text: "Modern wetlands are significant sources of atmospheric methane" },
      { letter: "E", text: "Human population grew substantially during this period" },
    ],
    correctAnswer: "B",
    explanation: "The hypothesis claims that farmers draining wetlands caused the methane decline. Archaeological evidence of widespread wetland drainage during this exact period would provide independent corroboration of the proposed mechanism, directly supporting the causal connection between agricultural activity and reduced methane emissions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A technology company claims that its new employee wellness program has reduced sick days by 25%. The program, implemented last year, includes gym memberships, healthy cafeteria options, and stress management workshops. The company cites the reduction in sick days as proof that workplace wellness programs are effective investments.`,
    questionStem: "Which one of the following, if true, most seriously weakens the company's claim?",
    answerChoices: [
      { letter: "A", text: "The wellness program cost more to implement than the company had initially budgeted" },
      { letter: "B", text: "Other companies in the same industry did not implement similar programs last year" },
      { letter: "C", text: "Last year the company changed its sick leave policy to require doctor's notes for absences" },
      { letter: "D", text: "Some employees have not participated in any components of the wellness program" },
      { letter: "E", text: "The company also implemented a new remote work policy last year" },
    ],
    correctAnswer: "C",
    explanation: "The change in sick leave policy requiring doctor's notes provides an alternative explanation for the reduction in sick days. Employees might simply be taking fewer official sick days because of the documentation requirement, not because they are actually healthier. This undermines the causal connection between the wellness program and reduced sick days.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Literary critics who dismiss genre fiction as inferior to literary fiction are misguided. Many works now considered classics, including the novels of Charles Dickens, were originally published as popular entertainment. If we apply the same standards to contemporary popular fiction, some of today's genre novels may well be recognized as great literature by future generations.`,
    questionStem: "The argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "Charles Dickens intentionally wrote works that would be considered literary classics" },
      { letter: "B", text: "contemporary genre fiction has qualities comparable to those found in Dickens' works" },
      { letter: "C", text: "the standards by which literature is judged remain constant over time" },
      { letter: "D", text: "popular entertainment cannot simultaneously be great literature" },
      { letter: "E", text: "future generations will have better literary judgment than current critics" },
    ],
    correctAnswer: "B",
    explanation: "The argument draws a parallel between Dickens' popular works (now classics) and contemporary genre fiction. For this parallel to be valid, the argument must assume that today's genre fiction has the literary qualities that enabled Dickens' work to be recognized as great literature. Without this assumption, the comparison fails.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-028",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Chen: Universities should require all students to complete a core curriculum including courses in science, humanities, and social sciences. A broad education develops critical thinking skills and produces well-rounded graduates prepared for citizenship in a complex world.

Professor Walsh: Requiring a standardized core curriculum treats students as identical rather than as individuals with unique goals and talents. Students should have maximum flexibility to design their own educational paths based on their interests and career objectives.`,
    questionStem: "The main point at issue between Professor Chen and Professor Walsh is whether",
    answerChoices: [
      { letter: "A", text: "critical thinking is an important educational outcome" },
      { letter: "B", text: "students have diverse interests and career objectives" },
      { letter: "C", text: "universities should mandate a broad educational foundation for all students" },
      { letter: "D", text: "graduates need to be prepared for citizenship responsibilities" },
      { letter: "E", text: "science, humanities, and social sciences are all valuable disciplines" },
    ],
    correctAnswer: "C",
    explanation: "Professor Chen explicitly argues for required core curriculum, while Professor Walsh explicitly argues against standardized requirements and for student flexibility. The central disagreement is whether universities should mandate a broad educational foundation. The other topics are either agreed upon or not directly contested by both professors.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-029",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No responsible journalist would publish unverified information. Thompson published the unverified rumor about the senator. Therefore, Thompson is not a responsible journalist.`,
    questionStem: "The pattern of reasoning in the argument is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "No good teacher ignores struggling students. Ms. Rivera always helps struggling students. Therefore, Ms. Rivera is a good teacher." },
      { letter: "B", text: "All effective managers delegate appropriately. Mr. Kim is an effective manager. Therefore, Mr. Kim delegates appropriately." },
      { letter: "C", text: "No ethical lawyer would misrepresent evidence. Davis misrepresented evidence in court. Therefore, Davis is not an ethical lawyer." },
      { letter: "D", text: "Some successful entrepreneurs take risks. Janet takes risks. Therefore, Janet might be a successful entrepreneur." },
      { letter: "E", text: "All experienced chefs can prepare complex dishes. This dish is complex. Therefore, an experienced chef prepared it." },
    ],
    correctAnswer: "C",
    explanation: "The original argument follows the pattern: No A would do B. X did B. Therefore, X is not A. Answer C follows the same pattern: No ethical lawyer would misrepresent evidence. Davis misrepresented evidence. Therefore, Davis is not an ethical lawyer. This is a valid modus tollens argument structure.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-030",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The government should not fund research into renewable energy sources. After all, private companies are already investing billions of dollars in developing solar, wind, and battery technologies. If these technologies were truly promising, the private sector would fund all necessary research without government assistance.`,
    questionStem: "The argument's reasoning is questionable because it",
    answerChoices: [
      { letter: "A", text: "assumes that private sector investment indicates a technology's promise while also arguing that promising technologies don't need government funding" },
      { letter: "B", text: "fails to consider that government and private sector funding might serve different purposes" },
      { letter: "C", text: "overlooks the possibility that renewable energy research could benefit society in non-economic ways" },
      { letter: "D", text: "presumes without justification that all private investment is motivated by profit" },
      { letter: "E", text: "ignores the fact that some renewable technologies are already commercially viable" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that private funding and government funding are interchangeable. However, government funding often supports basic research that has long-term benefits but uncertain commercial returns, which private companies may not pursue. The argument fails to consider that government funding might address research gaps that private investment leaves unfilled.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-031",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A study of urban planning found that cities with more mixed-use zoning, which allows residential and commercial buildings in the same areas, have lower carbon emissions per capita than cities with strict separation of residential and commercial zones. Urban planners conclude that mixed-use zoning reduces carbon emissions by decreasing the distances people need to travel for daily activities.`,
    questionStem: "Which one of the following, if true, most strengthens the urban planners' conclusion?",
    answerChoices: [
      { letter: "A", text: "Cities with mixed-use zoning tend to have older infrastructure than cities with separated zones" },
      { letter: "B", text: "Residents of mixed-use neighborhoods are more likely to walk or bike for errands than residents of single-use zones" },
      { letter: "C", text: "Mixed-use zoning is more common in European cities than in American cities" },
      { letter: "D", text: "Some cities with separated zones have implemented successful public transit systems" },
      { letter: "E", text: "Property values are generally higher in mixed-use areas" },
    ],
    correctAnswer: "B",
    explanation: "The planners' conclusion proposes a specific mechanism: mixed-use zoning reduces emissions by reducing travel distances. If residents of mixed-use areas actually walk or bike more for errands (rather than driving), this directly supports the proposed mechanism connecting mixed-use zoning to reduced emissions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-032",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The school board proposes extending the school day by one hour to improve student academic performance. They cite research showing that countries with longer school days consistently outperform the United States on international assessments. Adding instructional time will allow teachers to cover more material and give students additional practice with difficult concepts.`,
    questionStem: "Which one of the following, if true, most seriously weakens the school board's argument?",
    answerChoices: [
      { letter: "A", text: "Some high-performing countries actually have shorter school days than the United States" },
      { letter: "B", text: "Teachers' unions have expressed concerns about the proposed extension" },
      { letter: "C", text: "The additional hour would significantly increase the school's operating costs" },
      { letter: "D", text: "Student attention and learning efficiency decline significantly during extended classroom sessions" },
      { letter: "E", text: "Many parents rely on their children to be home at a certain time for after-school care" },
    ],
    correctAnswer: "D",
    explanation: "If student attention and learning efficiency decline during longer sessions, then the additional hour might not actually provide effective learning time. This directly undermines the assumption that more instructional time leads to better academic performance, as the quality of learning during that time would be compromised.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The preservation of old-growth forests should be our highest environmental priority. These ecosystems have developed over centuries and harbor unique biodiversity that cannot be replicated. Once destroyed, old-growth forests cannot be restored within any reasonable timeframe. We must therefore prohibit all logging in old-growth areas.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "old-growth forests provide more ecosystem services than younger forests" },
      { letter: "B", text: "logging is the only significant threat to old-growth forests" },
      { letter: "C", text: "the economic value of timber is less than the ecological value of old-growth forests" },
      { letter: "D", text: "prohibiting logging will effectively preserve old-growth forests" },
      { letter: "E", text: "all old-growth forests contain the same types of biodiversity" },
    ],
    correctAnswer: "D",
    explanation: "The argument concludes that prohibiting logging will achieve preservation. This assumes that banning logging will actually result in the forests being preserved. If other factors (such as climate change, disease, fire, or development) also threaten old-growth forests, then prohibiting logging alone might not preserve them.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-034",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some philosophers argue that consciousness is fundamentally mysterious and will never be fully explained by neuroscience. They point to the "hard problem" of consciousness: even if we map every neural connection and process, this would not explain why there is subjective experience at all. But this argument proves too much. By the same reasoning, we could have argued that digestion would never be explained by chemistry because knowing the chemical reactions would not explain why they constitute digestion. Yet we now understand digestion as a chemical process.`,
    questionStem: "The argument responds to the philosophers' position by",
    answerChoices: [
      { letter: "A", text: "providing evidence that consciousness has already been partially explained by neuroscience" },
      { letter: "B", text: "showing that the logic used would also incorrectly predict failure to explain another phenomenon" },
      { letter: "C", text: "demonstrating that consciousness and digestion are fundamentally similar processes" },
      { letter: "D", text: "arguing that subjective experience is not a genuine phenomenon requiring explanation" },
      { letter: "E", text: "establishing that chemistry provides a complete explanation of all biological processes" },
    ],
    correctAnswer: "B",
    explanation: "The argument uses a reductio ad absurdum or parallel case strategy. It shows that the same type of reasoning the philosophers use would also predict that digestion could never be explained by chemistry, but this prediction proved false. If the reasoning leads to a demonstrably incorrect conclusion in one case, it suggests the reasoning itself is flawed.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-035",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The committee voted to reject the proposal after members expressed concerns about its cost. However, the cost estimates were prepared by the same consulting firm that would profit from the proposal being rejected and a competing project being approved. Therefore, the concerns about cost are unfounded and the proposal should be reconsidered.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that a source with a conflict of interest necessarily produces inaccurate information" },
      { letter: "B", text: "fails to specify the exact nature of the consulting firm's conflict of interest" },
      { letter: "C", text: "overlooks the possibility that committee members had other concerns beyond cost" },
      { letter: "D", text: "presumes that all consulting firms are motivated primarily by profit" },
      { letter: "E", text: "does not consider whether the cost estimates were reviewed by independent experts" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits the genetic fallacy by assuming that because the source has a potential conflict of interest, the information must be wrong. While the conflict of interest is a reason to be skeptical and verify the estimates, it does not prove the estimates are inaccurate. The cost concerns could still be valid even if the source had ulterior motives.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-036",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Medical researchers have observed that patients who maintain strong social connections recover more quickly from major surgeries than patients who are socially isolated. The researchers hypothesize that positive social interactions trigger the release of hormones that promote healing and reduce inflammation. They are now designing studies to test this biological mechanism.`,
    questionStem: "Which one of the following, if true, provides the most support for the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Socially connected patients tend to have better access to post-surgical care resources" },
      { letter: "B", text: "Laboratory studies show that the hormones associated with positive social interaction reduce inflammatory markers in cell cultures" },
      { letter: "C", text: "Patients who are socially isolated often experience depression, which can impair recovery" },
      { letter: "D", text: "Recovery time varies significantly among patients with similar social connection levels" },
      { letter: "E", text: "Strong social connections are correlated with overall better health before surgery" },
    ],
    correctAnswer: "B",
    explanation: "The hypothesis specifically proposes that social interaction triggers hormones that reduce inflammation. Laboratory evidence showing that these hormones do reduce inflammatory markers directly supports this proposed mechanism. The other options either provide alternative explanations or do not address the specific biological pathway proposed.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-037",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The city's new recycling program requires residents to separate recyclables into three categories: paper, plastics, and metals. The program guide states that any recyclable item placed in the wrong category will be discarded rather than recycled. According to the sanitation department, approximately 30% of items placed in recycling bins are in the wrong category. The department also reports that 10% of items in recycling bins are non-recyclable materials that should have been placed in regular trash.`,
    questionStem: "If all the statements above are true, which one of the following can be properly inferred?",
    answerChoices: [
      { letter: "A", text: "Fewer than 70% of items placed in recycling bins are actually recycled" },
      { letter: "B", text: "Most residents do not understand the recycling categories" },
      { letter: "C", text: "The recycling program has been unsuccessful" },
      { letter: "D", text: "More paper is incorrectly sorted than metals or plastics" },
      { letter: "E", text: "The sanitation department should provide clearer guidelines" },
    ],
    correctAnswer: "A",
    explanation: "If 30% of recyclable items are in the wrong category (and thus discarded) and 10% are non-recyclable (and thus should be discarded), then at least 40% of items in recycling bins are not properly recycled. However, there may be overlap, so we can only conclude that fewer than 70% (100% minus at least 30%) of recyclable items are actually recycled.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-038",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A survey of successful CEOs found that 85% of them wake up before 6 AM. This clearly demonstrates that waking up early is a key factor in achieving professional success. If you want to advance in your career, you should start waking up early.`,
    questionStem: "The argument is most vulnerable to which of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It fails to define what constitutes professional success" },
      { letter: "B", text: "It does not consider what time unsuccessful people typically wake up" },
      { letter: "C", text: "It assumes that all careers require the same qualities for advancement" },
      { letter: "D", text: "It relies on a self-reported survey which may be unreliable" },
      { letter: "E", text: "It does not account for differences in individual sleep needs" },
    ],
    correctAnswer: "B",
    explanation: "The argument draws a conclusion about causation from data about only successful CEOs. To establish that early waking contributes to success, we would need to know whether unsuccessful people also wake up early at similar rates. If they do, early waking is not a distinguishing factor. This is a sampling bias/comparison group flaw.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-039",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Many people believe that higher prices always indicate higher quality. Marketers exploit this belief by pricing products higher than competitors even when quality is comparable. Studies have confirmed that consumers often rate identical products as superior when told one costs more. This demonstrates that perceived value is as much a psychological construction as it is an objective assessment of product attributes.`,
    questionStem: "Which one of the following most accurately expresses the main point of the argument?",
    answerChoices: [
      { letter: "A", text: "Marketers often price products higher than their quality warrants" },
      { letter: "B", text: "Consumers frequently believe that higher prices indicate higher quality" },
      { letter: "C", text: "Studies have shown that price affects consumers' quality perceptions" },
      { letter: "D", text: "Perceived value involves psychological factors, not just objective product characteristics" },
      { letter: "E", text: "Products with identical features can command different prices based on marketing" },
    ],
    correctAnswer: "D",
    explanation: "The conclusion, signaled by 'This demonstrates,' is that perceived value is as much psychological as objective. The statements about consumer beliefs, marketer exploitation, and studies are all premises leading to this conclusion about the nature of perceived value.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-040",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city's bicycle-sharing program has been declared a success based on its high usage rates. Over one million rides were taken using shared bicycles last year, representing a significant portion of short-distance trips in the downtown area. City officials point to this as evidence that the program is achieving its goal of reducing traffic congestion.`,
    questionStem: "Which one of the following, if true, most weakens the city officials' conclusion?",
    answerChoices: [
      { letter: "A", text: "The bicycle-sharing program required a substantial initial investment from the city" },
      { letter: "B", text: "Survey data shows that most bicycle-sharing users previously walked or used public transit for these trips" },
      { letter: "C", text: "Several other cities have implemented similar bicycle-sharing programs" },
      { letter: "D", text: "Some neighborhoods in the city do not have convenient access to bicycle-sharing stations" },
      { letter: "E", text: "The number of registered users has increased each year since the program began" },
    ],
    correctAnswer: "B",
    explanation: "If most bicycle-sharing users previously walked or used public transit, then these trips are not replacing car trips. Reducing traffic congestion requires removing cars from the road, but if bicycles are replacing walking and transit rather than driving, the program is not achieving this goal despite its high usage rates.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-041",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Educational technology companies claim their products improve learning outcomes. However, a review of studies on educational software found that most were funded by the companies selling the products. We cannot trust the claims about learning improvements because research funded by parties with financial interests tends to produce favorable results.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "no independent studies of educational technology have been conducted" },
      { letter: "B", text: "companies should not be permitted to fund research on their own products" },
      { letter: "C", text: "the company-funded studies were methodologically flawed" },
      { letter: "D", text: "the studies claiming learning improvements are among those funded by the companies" },
      { letter: "E", text: "educational technology never actually improves learning outcomes" },
    ],
    correctAnswer: "D",
    explanation: "The argument moves from the claim that most studies were company-funded to the conclusion that we cannot trust the improvement claims. This reasoning only works if the studies showing improvements are among the company-funded ones. If the improvement claims came from independent studies, the funding bias would not undermine them.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-042",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Allen: Genetically modified crops are essential for feeding the world's growing population. Traditional breeding methods cannot produce the yield increases necessary to meet projected food demands, and GM technology allows us to develop crops that are more productive and nutritious.

Dr. Singh: The focus on GM technology diverts resources from more sustainable approaches. Agroecological methods that work with natural systems have been shown to increase yields significantly while also improving soil health and biodiversity. These approaches should be our priority.`,
    questionStem: "Dr. Allen and Dr. Singh disagree about whether",
    answerChoices: [
      { letter: "A", text: "the world's population is growing" },
      { letter: "B", text: "agricultural yields need to increase to meet future food demands" },
      { letter: "C", text: "genetically modified crops should be the primary strategy for increasing food production" },
      { letter: "D", text: "traditional breeding methods can improve crop yields" },
      { letter: "E", text: "soil health is important for sustainable agriculture" },
    ],
    correctAnswer: "C",
    explanation: "Dr. Allen argues GM crops are essential and necessary for meeting food demands, making them the priority. Dr. Singh argues that resources should go to agroecological methods instead, implying GM technology should not be the priority. They disagree about whether GM crops should be the primary strategy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-043",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some forms of civil disobedience are morally justified. Protests that draw attention to unjust laws without causing harm to others fall into this category. The lunch counter sit-ins during the civil rights movement were such protests. Therefore, those sit-ins were morally justified.`,
    questionStem: "The pattern of reasoning in the argument is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some investments are financially sound. Bonds with high credit ratings are financially sound investments. Government bonds have high credit ratings. Therefore, government bonds are financially sound investments." },
      { letter: "B", text: "Some medications have serious side effects. This medication is commonly prescribed. Commonly prescribed medications are often safe. Therefore, this medication is safe." },
      { letter: "C", text: "Some speeches are protected by free speech laws. Political speeches are protected. This speech is about politics. Therefore, this speech is probably protected." },
      { letter: "D", text: "Some trees are deciduous. Oak trees are deciduous. This is an oak tree. Therefore, this tree is deciduous." },
      { letter: "E", text: "Some athletes become professional. Talented athletes often become professional. This athlete is talented. Therefore, this athlete will become professional." },
    ],
    correctAnswer: "A",
    explanation: "The original argument: Some civil disobedience is justified. Protests that draw attention to unjust laws without harm are justified. The sit-ins were such protests. Therefore, the sit-ins were justified. Answer A follows the same structure: Some investments are sound. High-rated bonds are sound. Government bonds are high-rated. Therefore, government bonds are sound.",
    difficulty: "hard",
  },
  {
    id: "lr-bank46-044",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The theory that humans evolved from apes must be wrong. My grandfather was a minister who devoted his entire life to understanding the nature of humanity, and he rejected this theory. Someone with such deep knowledge of human nature would surely recognize the truth about human origins.`,
    questionStem: "The reasoning in the argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "attacks the character of those who support the theory of evolution" },
      { letter: "B", text: "relies on an authority whose expertise is not relevant to the claim in question" },
      { letter: "C", text: "fails to provide any scientific evidence against the theory" },
      { letter: "D", text: "assumes that theories about human origins cannot change over time" },
      { letter: "E", text: "confuses philosophical questions about human nature with biological questions" },
    ],
    correctAnswer: "B",
    explanation: "The argument appeals to the grandfather's authority as a minister and student of human nature to reject a biological claim about human evolution. However, expertise in theology or philosophy of human nature does not translate to expertise in evolutionary biology. This is an appeal to irrelevant authority.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-045",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historians have long debated why the Roman Empire declined. A new analysis suggests that lead poisoning from water pipes may have contributed significantly. Lead was widely used in Roman plumbing, and historical records describe symptoms among Roman elites that are consistent with chronic lead exposure, including cognitive impairment and infertility.`,
    questionStem: "Which one of the following, if true, most strengthens the argument that lead poisoning contributed to Rome's decline?",
    answerChoices: [
      { letter: "A", text: "Lead pipes were more common in Rome than in other ancient cities" },
      { letter: "B", text: "Modern analysis of Roman skeletal remains shows significantly elevated lead levels compared to pre-Roman populations" },
      { letter: "C", text: "The symptoms described in historical records could also be caused by other conditions" },
      { letter: "D", text: "Not all Roman water was delivered through lead pipes" },
      { letter: "E", text: "The Roman Empire's decline occurred over several centuries" },
    ],
    correctAnswer: "B",
    explanation: "Physical evidence of elevated lead levels in Roman remains would provide direct confirmation that Romans were indeed exposed to significant amounts of lead. This strengthens the hypothesis by establishing that the proposed mechanism (lead exposure from pipes) actually resulted in lead accumulation in the population.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-046",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Economists argue that raising the minimum wage will lead to job losses because employers will not be able to afford as many workers. However, when the city of Millfield raised its minimum wage by 15% last year, employment in low-wage sectors actually increased by 3%. This proves that minimum wage increases do not cause unemployment.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Millfield's economy was experiencing strong overall growth during the same period" },
      { letter: "B", text: "Some workers in Millfield earn more than the minimum wage" },
      { letter: "C", text: "Other cities that raised minimum wages had similar employment results" },
      { letter: "D", text: "Millfield's minimum wage is now higher than the federal minimum" },
      { letter: "E", text: "The cost of living in Millfield increased during the same period" },
    ],
    correctAnswer: "A",
    explanation: "If Millfield's economy was experiencing strong overall growth, this provides an alternative explanation for the employment increase. Strong economic growth could have created jobs despite the minimum wage increase, not because of it. This undermines the causal conclusion that minimum wage increases do not cause unemployment.",
    difficulty: "easy",
  },
  {
    id: "lr-bank46-047",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Art museums should stop charging admission fees. Studies show that people who regularly visit museums develop greater cultural awareness and civic engagement. By eliminating fees, museums would attract more visitors from lower-income communities, ultimately benefiting society as a whole.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Lower-income individuals are currently underrepresented among museum visitors" },
      { letter: "B", text: "Museums can operate effectively without admission fee revenue" },
      { letter: "C", text: "Cultural awareness is more valuable than other benefits museums provide" },
      { letter: "D", text: "All museum visitors develop increased civic engagement" },
      { letter: "E", text: "Admission fees are the only barrier preventing lower-income individuals from visiting museums" },
    ],
    correctAnswer: "B",
    explanation: "The argument recommends eliminating admission fees without considering how museums would replace this revenue. For this recommendation to be practical, the argument must assume that museums can continue to function without fee income. If they cannot, the recommendation would undermine the museums' ability to operate.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-048",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Opponent: The proposed solar farm will destroy valuable agricultural land and harm local wildlife. We should not sacrifice our farmland and natural environment for energy production.

Advocate: Your concern for agriculture and wildlife is admirable, but consider this: climate change poses a far greater threat to both farming and wildlife than any individual solar project. By generating clean energy, this solar farm will help mitigate the very threats you are worried about.`,
    questionStem: "The advocate responds to the opponent by",
    answerChoices: [
      { letter: "A", text: "questioning the accuracy of the opponent's claims about the project's impacts" },
      { letter: "B", text: "arguing that the opponent's own priorities support the advocate's position" },
      { letter: "C", text: "providing economic arguments that outweigh environmental concerns" },
      { letter: "D", text: "suggesting that the opponent is motivated by personal financial interests" },
      { letter: "E", text: "demonstrating that the opponent has misunderstood the project's design" },
    ],
    correctAnswer: "B",
    explanation: "The advocate turns the opponent's concerns about farmland and wildlife into an argument for the solar farm by pointing out that climate change poses a greater threat to these same interests. By framing the solar farm as climate mitigation, the advocate argues that the opponent's own priorities (protecting agriculture and wildlife) actually support building the project.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-049",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent poll found that 72% of respondents support stricter regulations on industrial pollution. A majority of Americans therefore favor increased environmental protection. Since our democracy is based on majority rule, the government should implement these stricter regulations.`,
    questionStem: "The reasoning in the argument is questionable because it",
    answerChoices: [
      { letter: "A", text: "generalizes from support for one specific policy to support for environmental protection broadly" },
      { letter: "B", text: "assumes that poll respondents' stated preferences reflect their actual behavior" },
      { letter: "C", text: "presumes that all forms of environmental protection are equally desirable" },
      { letter: "D", text: "fails to specify what forms stricter regulations should take" },
      { letter: "E", text: "overlooks the possibility that the poll sample was not representative" },
    ],
    correctAnswer: "A",
    explanation: "The argument conflates support for one specific policy (stricter pollution regulations) with support for environmental protection generally. Someone might support pollution regulations for reasons unrelated to environmental protection (such as public health) or might oppose other environmental measures. The specific finding does not justify the broader generalization.",
    difficulty: "medium",
  },
  {
    id: "lr-bank46-050",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The human brain consumes approximately 20% of the body's energy despite comprising only 2% of body mass. This disproportionate energy consumption reflects the brain's complexity and the constant neural activity required for consciousness, memory, and bodily regulation. Given these enormous energy demands, it is not surprising that brain function is highly sensitive to disruptions in blood sugar and oxygen supply.`,
    questionStem: "The statement that brain function is sensitive to disruptions in blood sugar and oxygen supply serves as",
    answerChoices: [
      { letter: "A", text: "a premise that supports the claim about the brain's energy consumption" },
      { letter: "B", text: "a conclusion that follows from the brain's high energy demands" },
      { letter: "C", text: "evidence that contradicts the claim about neural activity" },
      { letter: "D", text: "an example of the complexity of brain function" },
      { letter: "E", text: "a qualification of the claim about energy consumption" },
    ],
    correctAnswer: "B",
    explanation: "The phrase 'it is not surprising that' signals that the sensitivity to blood sugar and oxygen disruption is presented as a conclusion following from the previously established facts about high energy demands. The brain's disproportionate energy consumption explains why it would be particularly vulnerable to disruptions in energy supply.",
    difficulty: "easy",
  },
];
