// Logical Reasoning Questions Bank - Set 38
import { Question } from "../lsat-types";

export const lrQuestionsSet38: Question[] = [
  {
    id: "lr-bank38-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A new study shows that employees who work from home are 20% more productive than those who work in the office. Therefore, all companies should immediately switch to a fully remote work model to maximize productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that productivity is not the only factor relevant to a company's success" },
      { letter: "B", text: "assumes that what is true on average will be true in every individual case" },
      { letter: "C", text: "relies on a study without questioning its methodology" },
      { letter: "D", text: "ignores the possibility that some employees prefer working in an office" },
      { letter: "E", text: "fails to define what constitutes productivity" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that productivity is the sole consideration for company decisions, ignoring other factors like collaboration, company culture, client needs, and employee preferences that might make a fully remote model inadvisable despite productivity gains.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The city council claims that the new highway expansion will reduce traffic congestion. However, Councilwoman Martinez owns property near the proposed highway route that would increase in value after the expansion. Clearly, the highway expansion will not actually reduce congestion.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "attacks the character of an opponent rather than addressing the merits of the claim" },
      { letter: "B", text: "assumes that a policy is bad because someone benefits from it" },
      { letter: "C", text: "fails to provide evidence that the highway expansion would increase property values" },
      { letter: "D", text: "ignores the possibility that the councilwoman recused herself from the vote" },
      { letter: "E", text: "presumes that all city council members share the same motivations" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the fallacy of assuming that because someone has a personal interest in a policy, the policy must be flawed. The fact that Councilwoman Martinez might benefit does not logically demonstrate that the highway expansion won't reduce congestion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-003",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers have observed that communities with higher rates of bicycle commuting have lower rates of obesity. The researchers concluded that cycling to work helps prevent obesity.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "People who cycle to work report higher levels of overall life satisfaction" },
      { letter: "B", text: "The communities studied had similar dietary habits and access to healthy food options" },
      { letter: "C", text: "Bicycle commuting has increased in popularity over the past decade" },
      { letter: "D", text: "Many people who cycle to work also engage in other forms of exercise" },
      { letter: "E", text: "The communities with high cycling rates have better bike infrastructure" },
    ],
    correctAnswer: "B",
    explanation: "By establishing that dietary habits and food access were similar across communities, choice B rules out a major alternative explanation for the difference in obesity rates, thereby strengthening the causal link between cycling and lower obesity.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-004",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company argues that their new medication is safe because clinical trials showed no serious side effects in any of the 500 participants over a six-month period.`,
    questionStem: "Which one of the following, if true, most seriously weakens the pharmaceutical company's argument?",
    answerChoices: [
      { letter: "A", text: "The medication is intended to treat a condition that is not life-threatening" },
      { letter: "B", text: "Some participants reported mild headaches during the trial" },
      { letter: "C", text: "The most serious side effects of similar medications typically emerge after two years of use" },
      { letter: "D", text: "The clinical trial was conducted at multiple locations across the country" },
      { letter: "E", text: "The medication has not yet been approved by regulatory authorities" },
    ],
    correctAnswer: "C",
    explanation: "If serious side effects of similar medications typically emerge after two years, then a six-month trial would be insufficient to detect them. This undermines the conclusion that the medication is safe.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-005",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new policy requires all visitors to check their bags at the entrance. Since purses are bags, all visitors carrying purses will be required to check them.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "The museum has adequate facilities for checking all visitors' bags" },
      { letter: "B", text: "Most museum visitors carry purses" },
      { letter: "C", text: "The policy does not include exceptions for certain types of bags" },
      { letter: "D", text: "Visitors who check their bags will have a better museum experience" },
      { letter: "E", text: "The primary purpose of the policy is to prevent theft" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that the bag-checking policy applies universally without exceptions. If there were exceptions for certain types of bags like purses, the conclusion that purse-carriers must check them would not follow.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-006",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Critics argue that social media platforms should not moderate content because doing so infringes on free speech. However, these platforms are private companies with terms of service that users agree to. Private companies have the right to set rules for their platforms. Therefore, content moderation by social media platforms does not violate free speech principles.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Social media platforms are private companies" },
      { letter: "B", text: "Users agree to terms of service when joining platforms" },
      { letter: "C", text: "Private companies have the right to set rules for their platforms" },
      { letter: "D", text: "Content moderation by social media platforms does not violate free speech principles" },
      { letter: "E", text: "Critics are wrong to argue against content moderation" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is the claim that content moderation does not violate free speech principles. The other statements about private companies and terms of service serve as premises supporting this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-007",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that moral truths are objective facts that exist independently of human beliefs. But consider: if moral truths were objective facts, we would expect widespread agreement on moral questions, just as there is widespread agreement on mathematical truths. Yet moral disagreement persists across cultures and throughout history. This suggests that moral truths are not objective facts.`,
    questionStem: "The philosopher's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "demonstrating that a position leads to a logical contradiction" },
      { letter: "B", text: "showing that an expected consequence of a hypothesis does not obtain" },
      { letter: "C", text: "establishing that a claim is supported by insufficient evidence" },
      { letter: "D", text: "arguing that a position should be rejected because its proponents are biased" },
      { letter: "E", text: "proving that two concepts are logically equivalent" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher argues that if moral truths were objective (hypothesis), we would expect widespread agreement (expected consequence). Since this agreement doesn't exist, the hypothesis is questioned. This is a classic modus tollens structure.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every successful entrepreneur I know wakes up before 6 AM. Therefore, if you want to be a successful entrepreneur, you should start waking up before 6 AM.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on an insufficient sample of successful entrepreneurs" },
      { letter: "B", text: "confuses a correlation with a cause" },
      { letter: "C", text: "assumes that a characteristic of successful entrepreneurs is necessary for success" },
      { letter: "D", text: "fails to consider that some unsuccessful people also wake up before 6 AM" },
      { letter: "E", text: "ignores the possibility that the speaker's acquaintances are not representative" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that because successful entrepreneurs share a trait (early waking), that trait is necessary or sufficient for success. This confuses correlation with causation and assumes a necessary condition where there may be none.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-009",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A new therapy for treating depression involves exposure to bright light for 30 minutes each morning. Proponents claim this therapy is effective because it regulates the body's circadian rhythm, which affects mood.`,
    questionStem: "Which one of the following, if true, most strengthens the proponents' claim?",
    answerChoices: [
      { letter: "A", text: "Many patients prefer light therapy to traditional antidepressant medications" },
      { letter: "B", text: "Depression rates are higher in regions with less natural sunlight during winter months" },
      { letter: "C", text: "Patients who undergo light therapy report feeling more energetic" },
      { letter: "D", text: "The therapy was developed by a team of respected neuroscientists" },
      { letter: "E", text: "Light therapy has been used for decades to treat various conditions" },
    ],
    correctAnswer: "B",
    explanation: "If depression rates are higher where there is less sunlight, this supports the connection between light exposure and mood regulation, thereby strengthening the claim that light therapy works by affecting circadian rhythm and mood.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The school board argues that implementing a later start time for high schools will improve student academic performance because students will be more alert and focused with additional sleep.`,
    questionStem: "Which one of the following, if true, most weakens the school board's argument?",
    answerChoices: [
      { letter: "A", text: "Some students prefer to study late at night rather than early in the morning" },
      { letter: "B", text: "When start times were moved later at other schools, students simply went to bed later, getting the same amount of sleep" },
      { letter: "C", text: "Teachers report that afternoon classes are generally less productive than morning classes" },
      { letter: "D", text: "Athletic programs would need to adjust their practice schedules" },
      { letter: "E", text: "Parents have expressed concerns about the later start time affecting their work schedules" },
    ],
    correctAnswer: "B",
    explanation: "If students respond to later start times by staying up later, they won't get additional sleep. This undermines the argument's premise that a later start time will lead to more sleep and thus better performance.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-011",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of the crime because she was at a business conference in another city at the time of the crime. Her colleague testified that he saw her at the conference.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The defendant did not have an accomplice who committed the crime" },
      { letter: "B", text: "The colleague's testimony is accurate and reliable" },
      { letter: "C", text: "The crime could only have been committed in person at the scene" },
      { letter: "D", text: "The defendant had no motive to commit the crime" },
      { letter: "E", text: "Business conferences always have attendance records" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that committing the crime required physical presence at the scene. If the crime could have been committed remotely, the defendant's alibi would not prove innocence.",
    difficulty: "hard",
  },
  {
    id: "lr-bank38-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Patel: Genetically modified crops are essential for feeding the world's growing population. They produce higher yields and can be engineered to resist pests and drought.

Dr. Nakamura: The long-term environmental effects of genetically modified crops are unknown. We should rely on traditional farming methods and reduce food waste instead of embracing genetic modification.`,
    questionStem: "Dr. Patel and Dr. Nakamura disagree about whether",
    answerChoices: [
      { letter: "A", text: "the world's population is growing" },
      { letter: "B", text: "genetically modified crops can produce higher yields" },
      { letter: "C", text: "reducing food waste is a worthwhile goal" },
      { letter: "D", text: "genetically modified crops should be a key strategy for addressing food security" },
      { letter: "E", text: "traditional farming methods have environmental effects" },
    ],
    correctAnswer: "D",
    explanation: "The central disagreement is about whether genetically modified crops should be relied upon to address food needs. Dr. Patel says yes (essential), while Dr. Nakamura suggests alternative approaches are preferable.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All licensed attorneys have passed the bar exam. Maria has not passed the bar exam. Therefore, Maria is not a licensed attorney.`,
    questionStem: "Which one of the following exhibits a pattern of reasoning most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All mammals are warm-blooded. Dogs are mammals. Therefore, dogs are warm-blooded." },
      { letter: "B", text: "All certified teachers have completed a teaching program. John has not completed a teaching program. Therefore, John is not a certified teacher." },
      { letter: "C", text: "Some scientists are philosophers. Karen is a scientist. Therefore, Karen might be a philosopher." },
      { letter: "D", text: "All birds have feathers. Penguins have feathers. Therefore, penguins are birds." },
      { letter: "E", text: "No reptiles are warm-blooded. Snakes are reptiles. Therefore, snakes are not warm-blooded." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow the same valid logical pattern: All A are B. X is not B. Therefore, X is not A. This is a valid modus tollens inference.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-014",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The city's public transportation system runs buses every 15 minutes during peak hours and every 30 minutes during off-peak hours. Peak hours are from 7 AM to 9 AM and from 5 PM to 7 PM on weekdays. The system does not operate between midnight and 5 AM.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Buses run every 15 minutes at 8 AM on Saturdays" },
      { letter: "B", text: "Buses run every 30 minutes at 10 AM on Wednesdays" },
      { letter: "C", text: "No buses operate at 6 PM on Sundays" },
      { letter: "D", text: "More buses operate during morning peak hours than evening peak hours" },
      { letter: "E", text: "The longest wait time for a bus is 30 minutes" },
    ],
    correctAnswer: "B",
    explanation: "The passage states that off-peak hours (which includes 10 AM) have buses every 30 minutes on weekdays. Wednesday is a weekday and 10 AM is outside the stated peak hours, so buses must run every 30 minutes then.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-015",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The proposed regulations on carbon emissions will hurt businesses and cost jobs. If these regulations pass, factories will close and unemployment will rise. We cannot afford to damage our economy. Therefore, we should not be concerned about climate change.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that some regulations might help businesses" },
      { letter: "B", text: "assumes that all climate regulations will have the same effects" },
      { letter: "C", text: "concludes that a problem does not exist because a proposed solution has drawbacks" },
      { letter: "D", text: "ignores the economic costs of not addressing climate change" },
      { letter: "E", text: "relies on predictions about the future that may not come true" },
    ],
    correctAnswer: "C",
    explanation: "The argument fallaciously moves from 'this solution to climate change is problematic' to 'we shouldn't be concerned about climate change.' The validity of a problem is independent of whether a particular solution is desirable.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historians argue that the decline of the Roman Empire was primarily caused by economic factors, including inflation, heavy taxation, and the disruption of trade routes. Military threats from outside groups were merely a secondary factor that exploited existing weaknesses.`,
    questionStem: "Which one of the following, if true, most strengthens the historians' argument?",
    answerChoices: [
      { letter: "A", text: "The Roman military had successfully defended against external threats for centuries before the empire's decline" },
      { letter: "B", text: "Other ancient empires also faced military threats but did not collapse" },
      { letter: "C", text: "Records show severe currency debasement and declining tax revenues for decades before the major military invasions" },
      { letter: "D", text: "Many historians have studied the fall of Rome extensively" },
      { letter: "E", text: "The Roman Empire had a complex and sophisticated economy" },
    ],
    correctAnswer: "C",
    explanation: "Evidence that economic problems existed for decades before the military invasions supports the claim that economic factors were primary and that military threats exploited pre-existing weaknesses.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-017",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A study found that students who took handwritten notes in class performed better on exams than students who typed notes on laptops. The researchers concluded that handwriting notes improves learning and retention of material.`,
    questionStem: "Which one of the following, if true, most weakens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "The study was conducted at multiple universities" },
      { letter: "B", text: "Students who typed notes also had access to internet browsers and were frequently observed off-task" },
      { letter: "C", text: "Handwritten notes tend to be shorter than typed notes" },
      { letter: "D", text: "Some students prefer typing because they can take notes faster" },
      { letter: "E", text: "The exams tested factual recall rather than analytical thinking" },
    ],
    correctAnswer: "B",
    explanation: "If laptop users were distracted by internet browsing, their poorer performance could be due to distraction rather than the method of note-taking itself. This alternative explanation weakens the causal conclusion about handwriting.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-018",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The new building code requires all commercial buildings to have wheelchair-accessible entrances. Since the restaurant is a commercial building, it will need to install a ramp or elevator at its entrance.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The restaurant does not already have a wheelchair-accessible entrance" },
      { letter: "B", text: "Installing a ramp is less expensive than installing an elevator" },
      { letter: "C", text: "The new building code applies to existing buildings, not just new construction" },
      { letter: "D", text: "Wheelchair users frequently visit restaurants" },
      { letter: "E", text: "The restaurant owner supports the new building code" },
    ],
    correctAnswer: "A",
    explanation: "The conclusion that the restaurant needs to install accessibility features assumes it doesn't already have them. If the restaurant already has an accessible entrance, no installation would be necessary.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-019",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Manager: You claim that our company should switch to renewable energy sources because it's better for the environment. But you drive a gasoline-powered car to work every day. How can you advocate for environmental policies when you don't practice what you preach?`,
    questionStem: "The manager responds to the claim by",
    answerChoices: [
      { letter: "A", text: "questioning the accuracy of the data supporting the claim" },
      { letter: "B", text: "showing that the claim leads to impractical consequences" },
      { letter: "C", text: "attacking the credibility of the person making the claim rather than addressing the claim itself" },
      { letter: "D", text: "demonstrating that the claim is internally inconsistent" },
      { letter: "E", text: "providing evidence that contradicts the claim" },
    ],
    correctAnswer: "C",
    explanation: "The manager commits the ad hominem fallacy by attacking the advocate's personal behavior rather than addressing the merits of the argument for renewable energy. Personal hypocrisy doesn't make an argument invalid.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-020",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Studies have shown that people who meditate regularly report lower levels of stress. Meditation is therefore an effective treatment for stress-related disorders such as anxiety and high blood pressure.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on self-reported data that may not be accurate" },
      { letter: "B", text: "assumes that lower perceived stress translates to improved physical health conditions" },
      { letter: "C", text: "fails to consider that people with low stress may be more likely to meditate" },
      { letter: "D", text: "ignores other factors that might reduce stress" },
      { letter: "E", text: "does not define what constitutes regular meditation" },
    ],
    correctAnswer: "B",
    explanation: "The argument jumps from lower self-reported stress levels to effectiveness in treating medical conditions like anxiety disorders and high blood pressure. Feeling less stressed does not necessarily mean clinical conditions are being treated effectively.",
    difficulty: "hard",
  },
  {
    id: "lr-bank38-021",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The mayor argues that building a new sports stadium will boost the local economy by attracting visitors who will spend money at local businesses. However, the stadium will be funded by taxpayer money that could otherwise be used for education and infrastructure. Therefore, building the stadium is not in the public interest.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Sports stadiums never generate enough revenue to justify their costs" },
      { letter: "B", text: "The economic benefits from the stadium will be less than the benefits from spending on education and infrastructure" },
      { letter: "C", text: "Most local residents oppose the construction of the stadium" },
      { letter: "D", text: "Taxpayer money should never be used for recreational facilities" },
      { letter: "E", text: "Private investors are unwilling to fund the stadium" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that the stadium is not in the public interest because the money could be spent on education and infrastructure. This assumes that those alternative uses would provide greater benefits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-022",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Marine biologists have proposed that the decline in coral reef populations is primarily due to rising ocean temperatures caused by climate change. They argue that corals expel the symbiotic algae that provide them with nutrients when water temperatures exceed certain thresholds, leading to coral bleaching and death.`,
    questionStem: "Which one of the following, if true, most strengthens the marine biologists' argument?",
    answerChoices: [
      { letter: "A", text: "Coral reefs are home to a diverse array of marine species" },
      { letter: "B", text: "Some coral species are more resistant to temperature changes than others" },
      { letter: "C", text: "Coral bleaching events have increased in frequency and severity as average ocean temperatures have risen" },
      { letter: "D", text: "Pollution from agricultural runoff also damages coral reefs" },
      { letter: "E", text: "Scientists have been studying coral reefs for decades" },
    ],
    correctAnswer: "C",
    explanation: "A correlation between rising temperatures and increased bleaching events directly supports the claim that temperature increases cause coral decline through the bleaching mechanism described.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The CEO argues that the company's new open-office layout will improve collaboration and innovation because employees will interact more frequently with colleagues from different departments.`,
    questionStem: "Which one of the following, if true, most weakens the CEO's argument?",
    answerChoices: [
      { letter: "A", text: "Some employees prefer to work in private offices" },
      { letter: "B", text: "Research shows that employees in open offices tend to use headphones and electronic communication to avoid face-to-face interactions" },
      { letter: "C", text: "The open-office layout will reduce the company's real estate costs" },
      { letter: "D", text: "Not all employees work in the same physical location" },
      { letter: "E", text: "The previous office layout had some shared spaces" },
    ],
    correctAnswer: "B",
    explanation: "If employees in open offices actually reduce face-to-face interaction by using headphones and electronic communication, this undermines the premise that the open layout will increase interaction and thus improve collaboration.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-024",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Opponents of the proposed tax increase argue that it will harm small businesses. But these opponents are themselves small business owners who would have to pay higher taxes. Their opposition is clearly motivated by self-interest, so we can dismiss their concerns about the tax increase.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to provide evidence that the tax increase will not harm small businesses" },
      { letter: "B", text: "assumes that all small business owners oppose the tax increase" },
      { letter: "C", text: "rejects a claim based on the motives of those making it rather than the merits of the claim" },
      { letter: "D", text: "ignores the possibility that small businesses might benefit from how the tax revenue is spent" },
      { letter: "E", text: "presumes that self-interested parties cannot provide accurate information" },
    ],
    correctAnswer: "C",
    explanation: "The argument commits the genetic fallacy by dismissing the opponents' concerns based on their alleged motives rather than examining whether their concerns about harm to small businesses are valid.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-025",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The new artificial intelligence system can diagnose certain cancers more accurately than experienced physicians. Some worry this will lead to doctors being replaced by machines. However, medical practice involves much more than diagnosis—it requires empathy, ethical judgment, and the ability to communicate complex information to patients. While AI can assist with diagnosis, it cannot replace the human elements of medical care.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "AI systems are more accurate at diagnosis than human physicians" },
      { letter: "B", text: "Medical practice requires empathy and ethical judgment" },
      { letter: "C", text: "AI systems cannot replace the human elements of medical care" },
      { letter: "D", text: "Some people worry that AI will replace doctors" },
      { letter: "E", text: "AI can assist physicians with diagnosis" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is that AI cannot replace human elements of medical care. The discussion of empathy, ethical judgment, and communication skills serves as supporting premises for this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-026",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Chen: Universities should prioritize research that has immediate practical applications. Research that doesn't address real-world problems is an inefficient use of limited resources.

Professor Williams: Basic research without obvious immediate applications has historically led to the most transformative discoveries. Penicillin and the internet both emerged from research that wasn't initially aimed at practical goals.`,
    questionStem: "Professor Chen and Professor Williams disagree about whether",
    answerChoices: [
      { letter: "A", text: "university resources are limited" },
      { letter: "B", text: "the internet was a transformative discovery" },
      { letter: "C", text: "research without immediate practical applications is a worthwhile investment for universities" },
      { letter: "D", text: "penicillin emerged from basic research" },
      { letter: "E", text: "universities currently conduct basic research" },
    ],
    correctAnswer: "C",
    explanation: "Professor Chen believes research should focus on immediate applications (implying basic research is not worthwhile), while Professor Williams argues that basic research without obvious applications has great value.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The preservation of endangered languages is crucial because each language contains unique knowledge about the natural world and human experience that cannot be fully captured in translation. When a language dies, this irreplaceable knowledge is lost forever.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Most endangered languages are spoken by small communities" },
      { letter: "B", text: "The knowledge contained in endangered languages is valuable and worth preserving" },
      { letter: "C", text: "Translation technologies will never become sophisticated enough to capture all nuances" },
      { letter: "D", text: "All languages contain equal amounts of unique knowledge" },
      { letter: "E", text: "Language preservation efforts are always successful" },
    ],
    correctAnswer: "B",
    explanation: "The argument's conclusion that preservation is 'crucial' depends on the assumption that the unique knowledge in these languages is valuable enough to warrant preservation efforts.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-028",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Criminologists argue that mandatory minimum sentences for drug offenses do not effectively deter drug-related crimes. They point to the fact that drug offense rates have remained relatively stable in states that implemented such sentences.`,
    questionStem: "Which one of the following, if true, most strengthens the criminologists' argument?",
    answerChoices: [
      { letter: "A", text: "Drug offenders often do not know the specific penalties for their crimes before committing them" },
      { letter: "B", text: "Mandatory minimum sentences have been criticized by civil liberties organizations" },
      { letter: "C", text: "Some states have recently begun to reconsider their mandatory minimum sentencing policies" },
      { letter: "D", text: "Drug offenses encompass a wide range of activities" },
      { letter: "E", text: "Prison overcrowding has increased in states with mandatory minimum sentences" },
    ],
    correctAnswer: "A",
    explanation: "If potential offenders don't know the penalties, they cannot be deterred by them. This supports the conclusion that mandatory minimums don't effectively deter crime.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-029",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Art critics argue that the recent increase in art prices is due to the genuine artistic merit of contemporary works. As collectors become more sophisticated, they are willing to pay premium prices for truly exceptional art.`,
    questionStem: "Which one of the following, if true, most weakens the art critics' argument?",
    answerChoices: [
      { letter: "A", text: "Many art collectors have advanced degrees in art history" },
      { letter: "B", text: "The increase in art prices closely correlates with an influx of investment funds treating art as an alternative asset class" },
      { letter: "C", text: "Art prices have increased across all categories, not just contemporary works" },
      { letter: "D", text: "Some art critics have financial interests in the art market" },
      { letter: "E", text: "The number of art galleries has increased significantly" },
    ],
    correctAnswer: "B",
    explanation: "If art prices rose because investment funds treat art as an investment vehicle, this provides an alternative explanation unrelated to artistic merit, thereby weakening the critics' argument.",
    difficulty: "hard",
  },
  {
    id: "lr-bank38-030",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A survey of gym members found that 80% of respondents exercise at least three times per week. This demonstrates that Americans are becoming more committed to regular exercise.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on self-reported data that may be inaccurate" },
      { letter: "B", text: "draws a conclusion about a general population from a sample that is not representative of that population" },
      { letter: "C", text: "fails to define what counts as exercise" },
      { letter: "D", text: "assumes that exercise frequency indicates commitment" },
      { letter: "E", text: "ignores the possibility that gym membership has declined" },
    ],
    correctAnswer: "B",
    explanation: "Gym members are not representative of Americans generally; they are people who have already chosen to join a gym. Drawing conclusions about all Americans from this biased sample is a significant flaw.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-031",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy improves, unemployment will decrease. The economy has not improved. Therefore, unemployment has not decreased.`,
    questionStem: "The flawed pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If it rains, the ground will be wet. It rained. Therefore, the ground is wet." },
      { letter: "B", text: "If the alarm sounds, there is a fire. The alarm did not sound. Therefore, there is no fire." },
      { letter: "C", text: "All doctors have medical degrees. Smith is a doctor. Therefore, Smith has a medical degree." },
      { letter: "D", text: "If the car won't start, the battery is dead. The battery is not dead. Therefore, the car will start." },
      { letter: "E", text: "Some teachers are strict. Jones is a teacher. Therefore, Jones might be strict." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments commit the fallacy of denying the antecedent. The original argument has the form: If P then Q. Not P. Therefore, not Q. This is invalid because Q could occur for reasons other than P.",
    difficulty: "hard",
  },
  {
    id: "lr-bank38-032",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Many people believe that eating fat causes weight gain and should be avoided. However, recent research shows that the body needs healthy fats for proper brain function, hormone production, and nutrient absorption. The key is choosing the right kinds of fats. Therefore, eliminating all fat from one's diet is actually counterproductive to health.`,
    questionStem: "The nutritionist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "citing expert opinion to support a controversial claim" },
      { letter: "B", text: "challenging a popular assumption by presenting evidence of its negative consequences" },
      { letter: "C", text: "drawing an analogy between fat consumption and other dietary choices" },
      { letter: "D", text: "demonstrating that a belief is based on outdated information" },
      { letter: "E", text: "showing that a practice contradicts the goals of those who follow it" },
    ],
    correctAnswer: "E",
    explanation: "The nutritionist argues that people who eliminate fat to improve health are actually harming their health, thus showing that the practice contradicts their own goals.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should install more streetlights in the downtown area. Studies show that well-lit areas experience less crime than poorly lit areas, and reducing crime downtown will encourage more people to visit shops and restaurants in the evening.`,
    questionStem: "Which one of the following is an assumption required by the argument?",
    answerChoices: [
      { letter: "A", text: "The downtown area is currently not well lit" },
      { letter: "B", text: "Shops and restaurants want more evening customers" },
      { letter: "C", text: "Installing streetlights is less expensive than other crime reduction measures" },
      { letter: "D", text: "People avoid downtown in the evening primarily because of crime concerns" },
      { letter: "E", text: "Crime rates downtown are currently higher than in other parts of the city" },
    ],
    correctAnswer: "A",
    explanation: "The argument for installing more streetlights assumes the current lighting is inadequate. If downtown is already well lit, adding more lights would not reduce crime through better lighting.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-034",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Either we invest heavily in renewable energy now, or we face catastrophic climate change in the future. Since the government has not invested heavily in renewable energy, catastrophic climate change is inevitable.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that government is the only entity capable of investing in renewable energy" },
      { letter: "B", text: "fails to consider that moderate investment might also prevent climate change" },
      { letter: "C", text: "presents only two options when others may exist" },
      { letter: "D", text: "exaggerates the consequences of not investing in renewable energy" },
      { letter: "E", text: "assumes that renewable energy is the only solution to climate change" },
    ],
    correctAnswer: "C",
    explanation: "The argument presents a false dilemma by suggesting only two options exist: heavy investment or catastrophe. It ignores possibilities such as moderate investment, other technologies, or international cooperation that might prevent catastrophe.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-035",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologists contend that childhood experiences significantly shape adult personality. They argue that individuals who experienced secure attachment with caregivers in early childhood are more likely to form healthy relationships as adults.`,
    questionStem: "Which one of the following, if true, most strengthens the psychologists' contention?",
    answerChoices: [
      { letter: "A", text: "Adults who report having secure childhood attachments also report higher levels of life satisfaction" },
      { letter: "B", text: "Longitudinal studies following individuals from infancy to adulthood show strong correlations between early attachment patterns and adult relationship styles" },
      { letter: "C", text: "Many people who had difficult childhoods go on to lead successful adult lives" },
      { letter: "D", text: "Attachment theory was developed in the mid-twentieth century" },
      { letter: "E", text: "Some adults are able to overcome the effects of insecure childhood attachments through therapy" },
    ],
    correctAnswer: "B",
    explanation: "Longitudinal studies that follow the same individuals over time provide the strongest evidence for a causal relationship between childhood attachment and adult relationship patterns.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-036",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A technology company claims that its facial recognition software improves public safety by helping law enforcement quickly identify suspects. The company points to several cases where the technology helped apprehend dangerous criminals.`,
    questionStem: "Which one of the following, if true, most weakens the company's claim?",
    answerChoices: [
      { letter: "A", text: "The software requires significant computing power to operate" },
      { letter: "B", text: "Studies show the software has a high rate of false positives, particularly for certain demographic groups, leading to wrongful detentions" },
      { letter: "C", text: "Not all law enforcement agencies have adopted the technology" },
      { letter: "D", text: "The company has contracts with numerous government agencies" },
      { letter: "E", text: "Some civil liberties groups have expressed concerns about privacy" },
    ],
    correctAnswer: "B",
    explanation: "If the software frequently misidentifies innocent people, leading to wrongful detentions, this undermines the claim that it improves public safety, as wrongful detention is a harm to public safety.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-037",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All of the candidates for the managerial position have at least a bachelor's degree. Some of the candidates have MBAs. Every candidate with an MBA has at least five years of management experience. No candidates with fewer than three years of experience were invited to interview.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All candidates invited to interview have at least a bachelor's degree" },
      { letter: "B", text: "All candidates with five years of experience have MBAs" },
      { letter: "C", text: "No candidates with MBAs were excluded from the interview" },
      { letter: "D", text: "Some candidates without MBAs have management experience" },
      { letter: "E", text: "All candidates invited to interview have MBAs" },
    ],
    correctAnswer: "A",
    explanation: "Since all candidates have at least a bachelor's degree, any subset of candidates (including those invited to interview) must also have at least a bachelor's degree.",
    difficulty: "hard",
  },
  {
    id: "lr-bank38-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Many educators advocate for teaching coding in elementary schools, arguing that it prepares students for the digital economy. But programming languages become obsolete quickly, and the specific skills taught today may be irrelevant in a decade. What truly prepares students is developing logical thinking and problem-solving abilities. Elementary schools should focus on these fundamental skills rather than specific programming languages.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Programming languages become obsolete quickly" },
      { letter: "B", text: "Logical thinking and problem-solving abilities are more important than coding skills" },
      { letter: "C", text: "Elementary schools should focus on fundamental thinking skills rather than specific programming languages" },
      { letter: "D", text: "Many educators advocate for teaching coding in elementary schools" },
      { letter: "E", text: "The digital economy requires workers with coding skills" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is the recommendation that elementary schools should focus on fundamental skills rather than programming languages. The points about obsolescence and the importance of logical thinking support this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-039",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Attorney Franklin: Eyewitness testimony should be given significant weight in criminal trials. Eyewitnesses observed the events in question and can provide detailed accounts that other evidence cannot match.

Attorney Garcia: Research has consistently shown that eyewitness memory is highly susceptible to distortion and suggestion. Juries often overvalue eyewitness testimony, leading to wrongful convictions. Courts should treat such testimony with skepticism.`,
    questionStem: "The point at issue between Attorney Franklin and Attorney Garcia is",
    answerChoices: [
      { letter: "A", text: "whether eyewitnesses can provide detailed accounts of events" },
      { letter: "B", text: "whether research on eyewitness memory has been conducted" },
      { letter: "C", text: "how much weight eyewitness testimony should be given in criminal trials" },
      { letter: "D", text: "whether wrongful convictions ever occur" },
      { letter: "E", text: "whether juries understand the limitations of eyewitness testimony" },
    ],
    correctAnswer: "C",
    explanation: "Franklin argues eyewitness testimony deserves significant weight, while Garcia argues it should be treated with skepticism. Their core disagreement is about how much credibility to give such testimony.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-040",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The school principal announced that the new dress code policy has been successful. She cited as evidence that complaints about the policy have decreased significantly since it was implemented. This proves that students and parents now support the dress code.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on the authority of the principal rather than independent evidence" },
      { letter: "B", text: "assumes that a decrease in complaints indicates acceptance rather than resignation" },
      { letter: "C", text: "fails to specify how much complaints have decreased" },
      { letter: "D", text: "ignores the possibility that some students like the dress code" },
      { letter: "E", text: "does not consider the opinions of teachers" },
    ],
    correctAnswer: "B",
    explanation: "A decrease in complaints does not necessarily indicate support. People may have stopped complaining because they feel it's futile, not because they accept the policy. The argument conflates silence with approval.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Journalist: The senator claims she has always supported environmental protection. Yet in 2018, she voted against the Clean Water Act. In 2020, she accepted campaign contributions from oil companies. And just last year, she opposed the carbon tax proposal. Her claim of environmental support simply does not hold up.`,
    questionStem: "The journalist's argument employs which one of the following methods of reasoning?",
    answerChoices: [
      { letter: "A", text: "Appealing to expert opinion to refute a claim" },
      { letter: "B", text: "Citing specific instances that contradict a general claim" },
      { letter: "C", text: "Demonstrating that a claim is logically impossible" },
      { letter: "D", text: "Showing that the claim is based on false assumptions" },
      { letter: "E", text: "Arguing that the claimant has a motive to be dishonest" },
    ],
    correctAnswer: "B",
    explanation: "The journalist refutes the senator's general claim of environmental support by providing specific examples (votes, contributions) that contradict it.",
    difficulty: "easy",
  },
  {
    id: "lr-bank38-042",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `If housing prices continue to rise at the current rate, young families will be unable to afford homes in this city. The city council must implement rent control measures to ensure affordable housing remains available.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Young families prefer to own rather than rent homes" },
      { letter: "B", text: "Rent control measures will effectively make housing more affordable" },
      { letter: "C", text: "Housing prices have been rising for several years" },
      { letter: "D", text: "The city council has the authority to implement rent control" },
      { letter: "E", text: "Other cities have successfully implemented rent control" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that rent control is needed to ensure affordability. This assumes rent control will actually achieve that goal. If rent control is ineffective, the recommendation fails.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-043",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeological evidence suggests that ancient Polynesians navigated thousands of miles across the Pacific Ocean using only the stars, ocean currents, and bird migrations as guides. Researchers believe these navigators must have possessed sophisticated knowledge of astronomy and oceanography.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' belief?",
    answerChoices: [
      { letter: "A", text: "Modern sailors often use GPS technology for navigation" },
      { letter: "B", text: "Oral traditions of Polynesian cultures include detailed descriptions of star patterns and their movements throughout the year" },
      { letter: "C", text: "The islands of Polynesia are scattered across millions of square miles of ocean" },
      { letter: "D", text: "Some ancient cultures developed writing systems to record their knowledge" },
      { letter: "E", text: "Ocean currents in the Pacific are complex and variable" },
    ],
    correctAnswer: "B",
    explanation: "Oral traditions containing detailed astronomical knowledge support the claim that Polynesians possessed sophisticated astronomical knowledge necessary for navigation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-044",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Economists predict that automation will lead to widespread unemployment as machines replace human workers. They argue that unlike previous technological revolutions, artificial intelligence will eliminate jobs faster than new ones can be created.`,
    questionStem: "Which one of the following, if true, most weakens the economists' prediction?",
    answerChoices: [
      { letter: "A", text: "Some jobs require uniquely human skills like empathy and creativity that machines cannot replicate" },
      { letter: "B", text: "Previous predictions of technological unemployment have consistently overestimated job losses and underestimated the creation of new job categories" },
      { letter: "C", text: "Automation technologies are becoming more sophisticated each year" },
      { letter: "D", text: "Many workers are concerned about losing their jobs to automation" },
      { letter: "E", text: "The pace of technological change has accelerated in recent decades" },
    ],
    correctAnswer: "B",
    explanation: "If past predictions about technology-driven unemployment were wrong, this gives reason to doubt current predictions, which weakens the economists' argument.",
    difficulty: "hard",
  },
  {
    id: "lr-bank38-045",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Decades ago, when crime rates were lower, there was less media coverage of crime. Now, with extensive media coverage of criminal activity, crime rates have increased. The media's constant reporting on crime is clearly responsible for the increase in criminal behavior.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that increased crime might lead to increased coverage" },
      { letter: "B", text: "ignores the possibility that both increased crime and increased coverage result from a third factor" },
      { letter: "C", text: "assumes that correlation establishes causation without ruling out other explanations" },
      { letter: "D", text: "does not define what constitutes extensive media coverage" },
      { letter: "E", text: "relies on an inappropriate comparison between two different time periods" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that because media coverage and crime rates both increased, one caused the other. This classic correlation-causation fallacy ignores alternative explanations and the possibility of reverse causation or confounding factors.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some great artists were not recognized during their lifetimes. Vincent van Gogh was a great artist. Therefore, Vincent van Gogh might not have been recognized during his lifetime.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some physicians are researchers. Dr. Kim is a physician. Therefore, Dr. Kim might be a researcher." },
      { letter: "B", text: "All great leaders are decisive. Churchill was decisive. Therefore, Churchill was a great leader." },
      { letter: "C", text: "No true philosophers ignore logic. Aristotle was a true philosopher. Therefore, Aristotle did not ignore logic." },
      { letter: "D", text: "Most successful entrepreneurs take risks. Sarah takes risks. Therefore, Sarah is a successful entrepreneur." },
      { letter: "E", text: "Some mammals live in the ocean. All whales are mammals. Therefore, all whales live in the ocean." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments have the same structure: Some A are B. X is A. Therefore, X might be B. This is valid reasoning that draws a possible conclusion from a premise about some members of a category.",
    difficulty: "hard",
  },
  {
    id: "lr-bank38-047",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new exhibit on ancient Egypt has attracted record numbers of visitors. Clearly, the public has a strong interest in ancient Egyptian history. We should develop more exhibits focusing on ancient civilizations.`,
    questionStem: "The reasoning above assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Ancient Egypt is more interesting than other ancient civilizations" },
      { letter: "B", text: "The museum has sufficient resources to develop new exhibits" },
      { letter: "C", text: "The success of the Egyptian exhibit indicates interest in ancient civilizations generally, not just Egypt specifically" },
      { letter: "D", text: "Previous exhibits at the museum were not as successful" },
      { letter: "E", text: "Visitors came specifically for the Egyptian exhibit rather than other museum attractions" },
    ],
    correctAnswer: "C",
    explanation: "The argument moves from interest in ancient Egypt to a recommendation for exhibits on ancient civilizations generally. This assumes the interest extends beyond Egypt to other ancient civilizations.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-048",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Neuroscientists have discovered that bilingual individuals who regularly use both languages have more gray matter in brain regions associated with executive function. They hypothesize that the mental effort of constantly switching between languages strengthens these brain regions.`,
    questionStem: "Which one of the following, if true, most strengthens the neuroscientists' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Gray matter density in the brain can be affected by cognitive activities" },
      { letter: "B", text: "Bilinguals who learned their second language as adults show similar brain patterns to those who learned as children" },
      { letter: "C", text: "Bilinguals who use only one language in their daily lives do not show the same increase in gray matter" },
      { letter: "D", text: "Executive function is important for many cognitive tasks" },
      { letter: "E", text: "The brain regions studied are known to be involved in language processing" },
    ],
    correctAnswer: "C",
    explanation: "If bilinguals who don't regularly switch languages don't show increased gray matter, this supports the hypothesis that it's the switching itself (not just knowing two languages) that strengthens the brain.",
    difficulty: "hard",
  },
  {
    id: "lr-bank38-049",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city installed red-light cameras at twenty intersections last year. Traffic violations at those intersections decreased by 30%. The red-light camera program has clearly been effective at improving driver behavior.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some drivers received multiple tickets from the cameras" },
      { letter: "B", text: "Traffic violations at intersections without cameras also decreased by a similar amount due to a citywide public safety campaign" },
      { letter: "C", text: "The cameras have generated significant revenue from ticket fines" },
      { letter: "D", text: "Not all drivers are aware that the cameras have been installed" },
      { letter: "E", text: "Rear-end collisions increased at some camera-equipped intersections" },
    ],
    correctAnswer: "B",
    explanation: "If violations decreased citywide, including at intersections without cameras, then the decrease at camera locations might be due to the public safety campaign rather than the cameras themselves.",
    difficulty: "medium",
  },
  {
    id: "lr-bank38-050",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Historians have traditionally attributed the Industrial Revolution to specific inventors and their technological innovations. However, recent scholarship emphasizes the role of broader social and economic conditions, such as access to capital, available labor, and natural resources. While individual inventors were certainly important, the Industrial Revolution could not have occurred without these underlying conditions being in place. Understanding historical change requires examining systemic factors, not just individual contributions.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Individual inventors were not important to the Industrial Revolution" },
      { letter: "B", text: "Recent scholarship has shifted focus to social and economic conditions" },
      { letter: "C", text: "Understanding historical change requires examining systemic factors, not just individual contributions" },
      { letter: "D", text: "The Industrial Revolution required access to capital and natural resources" },
      { letter: "E", text: "Traditional historians overemphasized the role of inventors" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is the general methodological point that understanding historical change requires examining systemic factors. The discussion of the Industrial Revolution serves as an illustration supporting this broader conclusion.",
    difficulty: "hard",
  },
];
