// Logical Reasoning Questions Bank - Set 25
// High-quality LSAT-style questions covering all question types

import { Question } from "../lsat-types";

export const lrQuestionsSet25: Question[] = [
  // FLAW QUESTIONS (10 questions: lr-bank25-001 to lr-bank25-010)
  {
    id: "lr-bank25-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: The Constitution protects freedom of speech, and this protection has been interpreted by courts to include symbolic speech such as flag burning. Critics who argue that flag burning should be prohibited because it is offensive fail to recognize that the entire purpose of free speech protections is to protect speech that others may find offensive. After all, popular speech rarely needs constitutional protection.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that all forms of offensive expression deserve equal protection" },
      { letter: "B", text: "fails to distinguish between speech that is merely offensive and speech that causes direct harm" },
      { letter: "C", text: "ignores the possibility that some offensive speech may not qualify as symbolic speech" },
      { letter: "D", text: "presupposes that constitutional protections should never be subject to revision" },
      { letter: "E", text: "conflates the purpose of protecting speech with the conclusion that all offensive speech must be protected" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that because free speech protections exist to protect offensive speech, all offensive speech should be protected. However, it fails to address the distinction between speech that is merely offensive and speech that may cause direct harm (such as incitement to violence). The critics' concern might be about harm rather than mere offense, which the argument does not adequately address.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Many people believe that organic foods are more nutritious than conventionally grown foods. However, recent studies have found no significant nutritional differences between organic and conventional produce. Therefore, there is no reason to pay more for organic foods.`,
    questionStem: "The nutritionist's reasoning is vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "ignores the possibility that organic farming may have environmental benefits" },
      { letter: "B", text: "assumes that nutrition is the only consideration relevant to food purchasing decisions" },
      { letter: "C", text: "fails to define what constitutes a significant nutritional difference" },
      { letter: "D", text: "overlooks the fact that some organic foods may indeed be more nutritious" },
      { letter: "E", text: "relies on studies that may have been funded by conventional agriculture interests" },
    ],
    correctAnswer: "B",
    explanation: "The nutritionist concludes there is no reason to pay more for organic foods solely based on nutritional equivalence. However, consumers may have other reasons to prefer organic foods, such as concerns about pesticide residues, environmental impact, animal welfare, or supporting sustainable farming practices. The argument wrongly assumes nutrition is the only relevant factor.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `City planner: Our city's traffic congestion has decreased by 20 percent since we implemented congestion pricing two years ago. This clearly demonstrates that congestion pricing is an effective solution to urban traffic problems and should be adopted by other cities facing similar challenges.`,
    questionStem: "The city planner's argument is most vulnerable to which of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It fails to consider whether the reduction in congestion has had negative economic effects on businesses" },
      { letter: "B", text: "It does not account for other factors that may have contributed to the reduction in traffic" },
      { letter: "C", text: "It assumes that what works in one city will necessarily work in all cities" },
      { letter: "D", text: "It does not provide data on traffic patterns before the implementation of congestion pricing" },
      { letter: "E", text: "It fails to explain how congestion pricing works to reduce traffic" },
    ],
    correctAnswer: "B",
    explanation: "The city planner attributes the 20 percent reduction in congestion solely to congestion pricing without considering other factors that might have contributed, such as changes in remote work patterns, public transit improvements, economic conditions affecting driving, or seasonal variations. The argument commits the post hoc fallacy by assuming correlation implies causation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Those who advocate for vegetarianism on ethical grounds argue that it is wrong to cause unnecessary suffering to animals. But humans have eaten meat for thousands of years, and this practice is deeply embedded in virtually every culture on Earth. Therefore, eating meat cannot be considered unethical.`,
    questionStem: "The reasoning in the philosopher's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to define what constitutes unnecessary suffering" },
      { letter: "B", text: "assumes that widespread cultural practices are necessarily ethical" },
      { letter: "C", text: "ignores scientific evidence about the health effects of vegetarianism" },
      { letter: "D", text: "presupposes that ancient practices are superior to modern ones" },
      { letter: "E", text: "conflates the frequency of a practice with its moral justification" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher commits the appeal to tradition fallacy by arguing that because meat-eating has been practiced for thousands of years across many cultures, it must be ethical. However, the duration or prevalence of a practice does not determine its moral status. Many practices once considered acceptable (such as slavery or denying women the right to vote) have been recognized as unethical despite their historical prevalence.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Marketing executive: Our competitor's new advertising campaign has been widely criticized by consumer advocacy groups for being misleading. This criticism proves that our competitor is acting unethically and that their products are inferior to ours.`,
    questionStem: "The marketing executive's argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "assumes that consumer advocacy groups are always correct in their assessments" },
      { letter: "B", text: "draws two conclusions that are not supported by the evidence provided" },
      { letter: "C", text: "fails to acknowledge that the executive's own company might engage in similar practices" },
      { letter: "D", text: "relies on criticism from groups that may have ulterior motives" },
      { letter: "E", text: "does not specify what aspects of the advertising were criticized as misleading" },
    ],
    correctAnswer: "B",
    explanation: "The argument draws two unsupported conclusions from the premise about advertising criticism. First, criticism of advertising does not prove unethical behavior by the company overall. Second, and more significantly, the quality of a company's advertising has no logical connection to the quality of its products. The argument conflates advertising practices with both corporate ethics and product quality.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Medical researcher: A study of 500 patients showed that those who took vitamin D supplements had a 30 percent lower rate of bone fractures than those who did not take supplements. This proves that vitamin D supplementation prevents bone fractures in the general population.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on which of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It generalizes from a sample that may not be representative of the general population" },
      { letter: "B", text: "It fails to consider the dosage of vitamin D used in the study" },
      { letter: "C", text: "It does not address potential side effects of vitamin D supplementation" },
      { letter: "D", text: "It assumes that correlation between supplementation and fracture rates indicates causation" },
      { letter: "E", text: "It overlooks the possibility that some participants may not have taken their supplements as directed" },
    ],
    correctAnswer: "D",
    explanation: "While answer A identifies a legitimate concern, the most fundamental flaw is assuming causation from correlation (D). The study shows an association between vitamin D supplementation and lower fracture rates, but this doesn't prove supplementation causes the reduction. People who take supplements may also engage in other health-promoting behaviors, have better access to healthcare, or differ in other ways that affect fracture risk.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: Senator Martinez opposes the proposed environmental legislation. Her opposition is clearly motivated by the substantial campaign contributions she has received from oil and gas companies. Since her position is influenced by financial interests rather than genuine concern for policy, her arguments against the legislation should be dismissed.`,
    questionStem: "The political analyst's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that all politicians who receive industry contributions are corrupt" },
      { letter: "B", text: "attacks the senator's motives rather than addressing the substance of her arguments" },
      { letter: "C", text: "fails to consider that the senator may have legitimate policy concerns" },
      { letter: "D", text: "overlooks the possibility that oil and gas companies may have valid perspectives" },
      { letter: "E", text: "presumes that campaign contributions necessarily influence voting behavior" },
    ],
    correctAnswer: "B",
    explanation: "The analyst commits the ad hominem fallacy by attacking the senator's alleged motives rather than addressing the actual arguments she makes against the legislation. Even if her motives were influenced by campaign contributions, her arguments might still be valid. The quality of an argument is independent of the motivations of the person making it.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Proponents of raising the minimum wage claim it will help low-income workers. But raising the minimum wage will increase labor costs for businesses, which will lead to higher prices for consumers. Higher prices will hurt low-income workers more than the wage increase will help them. Therefore, raising the minimum wage will ultimately harm the very people it is intended to help.`,
    questionStem: "The economist's argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes without justification that businesses will necessarily raise prices in response to higher labor costs" },
      { letter: "B", text: "fails to consider that businesses might reduce profits rather than raise prices" },
      { letter: "C", text: "ignores the possibility that increased wages might boost consumer spending" },
      { letter: "D", text: "treats a possible outcome as if it were certain and ignores other possible effects" },
      { letter: "E", text: "does not address the moral arguments for raising the minimum wage" },
    ],
    correctAnswer: "D",
    explanation: "The economist presents a chain of events as if each step were inevitable: wage increase leads to higher prices leads to net harm. However, each link in this chain is a possibility, not a certainty. Businesses might absorb costs, reduce other expenses, or see increased productivity. The argument also ignores potentially positive effects like reduced employee turnover or increased consumer spending from workers with higher wages.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-009",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The Renaissance marked a period of unprecedented artistic achievement. Artists of this era, such as Leonardo da Vinci and Michelangelo, created works of unparalleled beauty and technical mastery. Modern art, by contrast, often abandons traditional techniques and aesthetic standards. Therefore, modern art represents a decline in artistic quality.`,
    questionStem: "The art historian's reasoning is flawed in that it",
    answerChoices: [
      { letter: "A", text: "compares artists from different eras without acknowledging changes in artistic goals" },
      { letter: "B", text: "assumes that technical mastery and traditional aesthetics are the only valid measures of artistic quality" },
      { letter: "C", text: "fails to identify specific modern artists whose work demonstrates decline" },
      { letter: "D", text: "overlooks the influence of Renaissance artists on modern art movements" },
      { letter: "E", text: "presupposes that all modern art abandons traditional techniques" },
    ],
    correctAnswer: "B",
    explanation: "The art historian judges modern art by Renaissance standards (technical mastery and traditional aesthetics) without considering that modern art may be pursuing different valid artistic goals, such as emotional expression, conceptual exploration, or social commentary. This imposes one era's criteria onto another without justifying why those criteria should be universal.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-010",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Software developer: Users have complained that our application crashes frequently on older devices. Since we have limited development resources, we should focus on improving performance for newer devices, where most of our user base is located. Investing in compatibility with older devices would divert resources from features that benefit the majority of users.`,
    questionStem: "The software developer's argument is most vulnerable to which of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It assumes that users with older devices are less important than users with newer devices" },
      { letter: "B", text: "It fails to consider that fixing crashes on older devices might also improve performance on newer devices" },
      { letter: "C", text: "It does not address the possibility that users with older devices might upgrade" },
      { letter: "D", text: "It overlooks the reputational damage caused by application crashes" },
      { letter: "E", text: "It presents a false dichotomy between supporting older devices and developing new features" },
    ],
    correctAnswer: "E",
    explanation: "The developer presents the choice as binary: either support older devices or develop new features. However, these options are not necessarily mutually exclusive. Resources might be allocated to both, the stability fix might require minimal resources, or fixing the underlying issue might benefit all users. The argument creates a false dichotomy that oversimplifies the actual options available.",
    difficulty: "medium",
  },

  // STRENGTHEN QUESTIONS (8 questions: lr-bank25-011 to lr-bank25-018)
  {
    id: "lr-bank25-011",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: The ancient city of Morana was likely destroyed by a volcanic eruption rather than by invasion. Excavations have revealed that the city was buried under a thick layer of volcanic ash, and the skeletal remains found show no evidence of violent trauma typical of warfare.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologist's argument?",
    answerChoices: [
      { letter: "A", text: "Written records from neighboring civilizations make no mention of military campaigns against Morana" },
      { letter: "B", text: "The positions of the skeletal remains suggest that people died suddenly while engaged in daily activities" },
      { letter: "C", text: "Volcanic ash from a known eruption has been carbon-dated to the same period as Morana's destruction" },
      { letter: "D", text: "Other cities in the region show evidence of invasion during the same era" },
      { letter: "E", text: "The volcanic ash layer is composed of materials consistent with a nearby volcano" },
    ],
    correctAnswer: "C",
    explanation: "Answer C provides independent evidence linking a specific volcanic eruption to the time of Morana's destruction, corroborating the volcanic hypothesis. While E provides circumstantial support, C directly connects the timeline of a known eruption to the city's destruction, offering stronger confirmation of the archaeologist's theory.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Childhood music education improves cognitive development. Children who receive formal music instruction score higher on tests of mathematical reasoning than children who do not receive such instruction.`,
    questionStem: "Which one of the following, if true, most strengthens the psychologist's argument?",
    answerChoices: [
      { letter: "A", text: "Music instruction requires counting and pattern recognition, skills also used in mathematics" },
      { letter: "B", text: "Children with higher mathematical ability are more likely to be enrolled in music programs" },
      { letter: "C", text: "Studies that randomly assigned children to music instruction found improved cognitive test scores compared to control groups" },
      { letter: "D", text: "Many successful mathematicians also have musical training" },
      { letter: "E", text: "Parents who value education are more likely to enroll their children in music programs" },
    ],
    correctAnswer: "C",
    explanation: "Answer C describes randomized controlled studies, which are the gold standard for establishing causation. By randomly assigning children to receive music instruction, the study eliminates selection bias (addressed in B and E) and demonstrates that music instruction itself causes cognitive improvement, not just that cognitively gifted children choose music.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Environmental scientist: The recent increase in jellyfish populations in coastal waters is likely due to overfishing. When fish populations decline due to overfishing, jellyfish face less competition for plankton and fewer predators, allowing their numbers to increase dramatically.`,
    questionStem: "Which one of the following, if true, most strengthens the environmental scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Jellyfish populations have been increasing in coastal waters around the world" },
      { letter: "B", text: "Some species of fish that prey on jellyfish have seen population declines of over 90 percent in heavily fished areas" },
      { letter: "C", text: "Jellyfish can reproduce rapidly when environmental conditions are favorable" },
      { letter: "D", text: "Rising ocean temperatures may also contribute to jellyfish population growth" },
      { letter: "E", text: "Jellyfish populations tend to fluctuate naturally over multi-year cycles" },
    ],
    correctAnswer: "B",
    explanation: "Answer B directly supports the causal mechanism proposed by the scientist. If fish that prey on jellyfish have declined by 90 percent in heavily fished areas, this strongly supports the claim that overfishing has reduced predation pressure on jellyfish, allowing their populations to increase.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The decline of the Roman Empire was primarily caused by internal political instability rather than external military threats. During the third century, the empire experienced over fifty different emperors, most of whom were assassinated or overthrown. This constant turmoil weakened the empire's ability to respond effectively to any challenges.`,
    questionStem: "Which one of the following, if true, most supports the historian's conclusion?",
    answerChoices: [
      { letter: "A", text: "External invasions became more frequent after periods of internal political crisis" },
      { letter: "B", text: "The Roman military remained formidable even during periods of political instability" },
      { letter: "C", text: "Provinces that maintained stable local governance fared better than those that did not" },
      { letter: "D", text: "The eastern half of the empire, which had more political stability, survived longer than the western half" },
      { letter: "E", text: "Roman citizens became increasingly apathetic about imperial politics" },
    ],
    correctAnswer: "D",
    explanation: "Answer D provides comparative evidence that directly supports the causal claim. If the more politically stable eastern empire survived longer while the less stable western empire fell, this strongly suggests that internal political stability was a crucial factor in the empire's survival, supporting the historian's thesis that internal instability was the primary cause of decline.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The proposed universal basic income program would actually increase employment rather than decrease it. When people have a guaranteed income floor, they are more willing to take risks like starting businesses or pursuing education, which ultimately leads to more productive economic activity.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Countries with stronger social safety nets tend to have higher rates of entrepreneurship" },
      { letter: "B", text: "Most people report that they would continue working even if they received a basic income" },
      { letter: "C", text: "Basic income programs are less administratively costly than traditional welfare programs" },
      { letter: "D", text: "Pilot programs of basic income have generally been popular with participants" },
      { letter: "E", text: "Economic uncertainty causes many potential entrepreneurs to remain in stable employment" },
    ],
    correctAnswer: "A",
    explanation: "Answer A provides empirical evidence supporting the economist's theoretical claim. If countries with stronger safety nets actually have higher entrepreneurship rates, this suggests that income security does indeed encourage risk-taking and productive economic activity, directly supporting the argument that basic income could increase rather than decrease employment.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Urban planner: Converting some downtown streets to pedestrian-only zones will benefit local businesses. When people walk rather than drive, they spend more time in an area and are more likely to make impulse purchases at nearby shops.`,
    questionStem: "Which one of the following, if true, most strengthens the urban planner's argument?",
    answerChoices: [
      { letter: "A", text: "Cities that have implemented pedestrian zones have seen increased tourism" },
      { letter: "B", text: "Studies show that pedestrians spend an average of 40 percent more per visit than drivers at downtown shops" },
      { letter: "C", text: "Pedestrian zones reduce air pollution and noise in downtown areas" },
      { letter: "D", text: "Some business owners initially oppose pedestrian zones due to concerns about customer access" },
      { letter: "E", text: "Pedestrian zones require less maintenance than roads designed for vehicle traffic" },
    ],
    correctAnswer: "B",
    explanation: "Answer B provides direct quantitative evidence for the economist's key claim that pedestrians spend more than drivers. A 40 percent increase in spending per visit directly supports the argument that pedestrian zones will benefit local businesses through increased customer expenditure.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Criminologist: Rehabilitation programs for non-violent offenders are more effective at reducing recidivism than incarceration alone. Offenders who participate in education and job training programs while serving their sentences are less likely to commit crimes after release.`,
    questionStem: "Which one of the following, if true, most strengthens the criminologist's argument?",
    answerChoices: [
      { letter: "A", text: "Many non-violent offenders come from disadvantaged backgrounds with limited educational opportunities" },
      { letter: "B", text: "Recidivism rates for program participants remain lower even when controlling for prior criminal history and sentence length" },
      { letter: "C", text: "Rehabilitation programs are less expensive than extended incarceration" },
      { letter: "D", text: "Public opinion increasingly favors rehabilitation over punishment for non-violent crimes" },
      { letter: "E", text: "Some violent offenders have also benefited from rehabilitation programs" },
    ],
    correctAnswer: "B",
    explanation: "Answer B strengthens the argument by showing that the lower recidivism rates persist even when controlling for other variables. This addresses the potential objection that program participants might have lower recidivism simply because they were less serious offenders to begin with, not because of the programs themselves.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-018",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Botanist: The unusual growth pattern observed in these oak trees is caused by a specific soil fungus. Trees in areas where this fungus is present consistently show the distinctive branching pattern, while trees in fungus-free areas develop normally.`,
    questionStem: "Which one of the following, if true, most strengthens the botanist's conclusion?",
    answerChoices: [
      { letter: "A", text: "The fungus has been found in soil samples taken from the base of affected trees" },
      { letter: "B", text: "When the fungus was introduced to previously unaffected trees, they developed the unusual growth pattern" },
      { letter: "C", text: "Other species of trees in the same area do not show the unusual growth pattern" },
      { letter: "D", text: "The unusual growth pattern has been observed in oak trees across multiple geographic regions" },
      { letter: "E", text: "Trees showing the unusual pattern are otherwise healthy" },
    ],
    correctAnswer: "B",
    explanation: "Answer B describes an experimental manipulation that demonstrates causation. By introducing the fungus to healthy trees and observing that they develop the growth pattern, this provides direct evidence that the fungus causes the pattern, rather than merely being associated with it. This is the strongest type of evidence for a causal claim.",
    difficulty: "medium",
  },

  // WEAKEN QUESTIONS (8 questions: lr-bank25-019 to lr-bank25-026)
  {
    id: "lr-bank25-019",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Health researcher: A study found that people who drink three or more cups of coffee per day have a 15 percent lower risk of developing type 2 diabetes than non-coffee drinkers. This suggests that coffee consumption helps prevent diabetes.`,
    questionStem: "Which one of the following, if true, most weakens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Decaffeinated coffee shows similar associations with reduced diabetes risk" },
      { letter: "B", text: "People who drink large amounts of coffee tend to be more health-conscious overall and exercise more regularly" },
      { letter: "C", text: "The study did not control for the amount of sugar added to coffee" },
      { letter: "D", text: "Some people experience adverse effects from high coffee consumption" },
      { letter: "E", text: "Coffee contains antioxidants that have been shown to have health benefits" },
    ],
    correctAnswer: "B",
    explanation: "Answer B suggests that the correlation between coffee drinking and lower diabetes risk may be due to confounding factors. If coffee drinkers are more health-conscious and exercise more, these lifestyle factors rather than coffee itself might explain the reduced diabetes risk. This alternative explanation undermines the causal claim that coffee prevents diabetes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Marketing director: Our new advertising campaign has been highly successful. Since we launched the campaign three months ago, sales have increased by 25 percent.`,
    questionStem: "Which one of the following, if true, most seriously weakens the marketing director's conclusion?",
    answerChoices: [
      { letter: "A", text: "The company's main competitor withdrew from the market two months ago" },
      { letter: "B", text: "The advertising campaign cost significantly more than previous campaigns" },
      { letter: "C", text: "Consumer surveys indicate high awareness of the new advertising" },
      { letter: "D", text: "The company also improved its customer service during the same period" },
      { letter: "E", text: "Sales typically increase during the quarter when the campaign was launched" },
    ],
    correctAnswer: "A",
    explanation: "Answer A provides an alternative explanation for the sales increase. If the main competitor left the market, customers would naturally shift to remaining companies regardless of advertising. This seriously undermines the claim that the advertising campaign caused the sales increase.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Education policy analyst: Increasing teacher salaries will improve educational outcomes. Countries that pay teachers higher salaries consistently rank higher on international student achievement tests.`,
    questionStem: "Which one of the following, if true, most weakens the analyst's argument?",
    answerChoices: [
      { letter: "A", text: "Some teachers report that factors other than salary affect their job performance" },
      { letter: "B", text: "Countries with higher teacher salaries also tend to have more selective teacher training programs" },
      { letter: "C", text: "Teacher salary increases in some districts have not been accompanied by improved test scores" },
      { letter: "D", text: "The correlation between teacher salaries and student achievement is not perfect" },
      { letter: "E", text: "Many factors influence student performance on achievement tests" },
    ],
    correctAnswer: "B",
    explanation: "Answer B suggests that teacher training selectivity, not salary, might be the causal factor. Countries might have both high salaries and high achievement because they have rigorous teacher training that attracts talented candidates. Salary itself might just be correlated with, but not causing, the achievement difference.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Social media use increases feelings of loneliness and isolation. Surveys show that people who spend more than three hours per day on social media report significantly higher levels of loneliness than those who spend less time online.`,
    questionStem: "Which one of the following, if true, most weakens the sociologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Social media platforms are designed to maximize user engagement and time spent on the platform" },
      { letter: "B", text: "People who feel lonely are more likely to turn to social media as a source of connection" },
      { letter: "C", text: "Some users report that social media helps them maintain relationships with distant friends" },
      { letter: "D", text: "The survey relied on self-reported measures of loneliness" },
      { letter: "E", text: "Social media use has increased dramatically over the past decade" },
    ],
    correctAnswer: "B",
    explanation: "Answer B suggests reverse causation: lonely people might use more social media rather than social media causing loneliness. If loneliness drives people to seek connection online, the correlation would exist without social media being the cause. This fundamental challenge to the direction of causation seriously weakens the argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Energy consultant: Installing solar panels is a wise investment for homeowners. A typical residential solar installation pays for itself within eight years through savings on electricity bills, and solar panels have a lifespan of 25 to 30 years.`,
    questionStem: "Which one of the following, if true, most weakens the consultant's argument?",
    answerChoices: [
      { letter: "A", text: "Solar panel efficiency decreases by approximately 0.5 percent per year" },
      { letter: "B", text: "Government incentives for solar installation may be reduced in coming years" },
      { letter: "C", text: "Many homeowners sell their homes within five years of purchasing them" },
      { letter: "D", text: "Electricity rates have been relatively stable in recent years" },
      { letter: "E", text: "Solar panel installation requires a significant upfront investment" },
    ],
    correctAnswer: "C",
    explanation: "Answer C undermines the investment argument by pointing out that many homeowners won't stay long enough to realize the payback. If the investment takes eight years to recoup but many homeowners move within five years, they may not benefit from the savings, making it a poor investment for those individuals.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-024",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Veterinarian: Dogs that are fed a raw food diet are healthier than dogs fed conventional kibble. In my practice, dogs on raw diets have shinier coats, more energy, and fewer digestive problems.`,
    questionStem: "Which one of the following, if true, most undermines the veterinarian's conclusion?",
    answerChoices: [
      { letter: "A", text: "Raw food diets for dogs are more expensive than conventional kibble" },
      { letter: "B", text: "Some dogs experience digestive issues when transitioning to a raw diet" },
      { letter: "C", text: "Pet owners who feed raw diets also tend to provide more exercise and veterinary care" },
      { letter: "D", text: "The veterinarian has not conducted controlled scientific studies comparing the diets" },
      { letter: "E", text: "Raw diets may contain harmful bacteria if not handled properly" },
    ],
    correctAnswer: "C",
    explanation: "Answer C identifies a confounding variable. If owners who choose raw diets also provide more exercise and veterinary care, the improved health might be due to these other factors rather than the diet itself. This alternative explanation undermines the conclusion that the raw diet is causing the health benefits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-025",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Business analyst: The four-day workweek improves employee productivity. Companies that have implemented four-day workweeks report that their employees accomplish the same amount of work in fewer days.`,
    questionStem: "Which one of the following, if true, most weakens the analyst's argument?",
    answerChoices: [
      { letter: "A", text: "Employees at companies with four-day workweeks report higher job satisfaction" },
      { letter: "B", text: "Companies that implement four-day workweeks tend to be well-managed organizations that already had highly motivated employees" },
      { letter: "C", text: "Some industries are not well-suited to four-day workweek arrangements" },
      { letter: "D", text: "Four-day workweeks can create scheduling challenges for client-facing roles" },
      { letter: "E", text: "Productivity is difficult to measure in some types of work" },
    ],
    correctAnswer: "B",
    explanation: "Answer B suggests selection bias. If only well-managed companies with already motivated employees implement four-day workweeks, the productivity results might reflect these pre-existing conditions rather than the schedule change itself. The four-day workweek might not improve productivity at average companies.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Public health official: Our new anti-smoking campaign has been effective. Smoking rates among teenagers have declined by 20 percent since the campaign launched last year.`,
    questionStem: "Which one of the following, if true, most seriously weakens the official's conclusion?",
    answerChoices: [
      { letter: "A", text: "The campaign received positive feedback from focus groups before launch" },
      { letter: "B", text: "Adult smoking rates have remained unchanged over the same period" },
      { letter: "C", text: "Teen vaping rates increased by 35 percent during the same period" },
      { letter: "D", text: "Similar campaigns in other regions have shown mixed results" },
      { letter: "E", text: "The decline in teen smoking began two years before the campaign started" },
    ],
    correctAnswer: "E",
    explanation: "Answer E indicates that the trend of declining teen smoking predates the campaign, suggesting the campaign is not responsible for the decline. If smoking rates were already falling before the campaign launched, the continuation of that decline cannot be attributed to the campaign.",
    difficulty: "easy",
  },

  // ASSUMPTION QUESTIONS (8 questions: lr-bank25-027 to lr-bank25-034)
  {
    id: "lr-bank25-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Publisher: We should stop printing textbooks and move entirely to digital formats. Students today are comfortable with digital technology, and digital textbooks can be updated more easily than printed ones.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Digital textbooks are less expensive to produce than printed textbooks" },
      { letter: "B", text: "All students have reliable access to devices capable of displaying digital textbooks" },
      { letter: "C", text: "Students learn equally well from digital materials as from printed materials" },
      { letter: "D", text: "Printed textbooks will eventually become obsolete" },
      { letter: "E", text: "Publishers have the technical capability to produce digital textbooks" },
    ],
    correctAnswer: "C",
    explanation: "Using the negation test: if students learn worse from digital materials than printed ones, the move to digital-only would harm students, undermining the recommendation. The argument must assume that digital formats are at least as effective for learning as printed ones, or the recommendation would be counterproductive for education.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Film critic: Director Chen's new film cannot be considered a commercial success. Although it received excellent reviews, it earned only $50 million at the box office, far less than the average earnings of other films in its genre.`,
    questionStem: "Which one of the following is an assumption on which the critic's argument relies?",
    answerChoices: [
      { letter: "A", text: "Critical acclaim is not relevant to determining commercial success" },
      { letter: "B", text: "The film's production and marketing budget was comparable to other films in its genre" },
      { letter: "C", text: "Box office earnings are the sole measure of commercial success" },
      { letter: "D", text: "The average earnings of other films in the genre is an appropriate benchmark" },
      { letter: "E", text: "Director Chen's previous films were commercially successful" },
    ],
    correctAnswer: "B",
    explanation: "The argument compares box office earnings to genre averages to conclude the film wasn't successful. However, if the film had a much smaller budget than typical films in its genre, $50 million might represent an excellent return on investment. The argument assumes the film's budget was comparable, making the comparison meaningful.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Environmental activist: We must ban plastic straws to protect marine life. Millions of straws end up in the ocean each year, where they harm sea turtles and other marine animals.`,
    questionStem: "The activist's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Plastic straws are the primary source of ocean plastic pollution" },
      { letter: "B", text: "A ban on plastic straws would significantly reduce the harm to marine animals" },
      { letter: "C", text: "Consumers are unable to reduce straw use without a ban" },
      { letter: "D", text: "There are no environmentally friendly alternatives to plastic straws" },
      { letter: "E", text: "All plastic waste in the ocean harms marine animals" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that we must ban straws to protect marine life. For this to make sense, banning straws must actually reduce harm to marine animals. If straws are a negligible source of harm, or if alternatives would be equally harmful, the ban wouldn't achieve its purpose. The argument must assume the ban would make a meaningful difference.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Linguist: The Piraha language has no words for specific numbers, only terms meaning roughly 'few' and 'many.' This explains why speakers of Piraha have difficulty with mathematical concepts that require precise numerical thinking.`,
    questionStem: "The linguist's argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "all languages must have words for specific numbers to enable mathematical thinking" },
      { letter: "B", text: "the structure of language influences cognitive abilities" },
      { letter: "C", text: "speakers of Piraha are less intelligent than speakers of other languages" },
      { letter: "D", text: "mathematical concepts require formal education to understand" },
      { letter: "E", text: "other languages have developed number words because they are necessary for survival" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims that the lack of number words explains difficulty with mathematical thinking. This requires assuming that language structure influences thought (the Sapir-Whorf hypothesis). If language doesn't influence cognition, the lack of number words couldn't explain the mathematical difficulty.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-031",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Chef: This restaurant should source all ingredients locally. Local ingredients are fresher than those shipped from distant locations, and fresher ingredients produce better-tasting dishes.`,
    questionStem: "The chef's argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "locally sourced ingredients are less expensive than shipped ingredients" },
      { letter: "B", text: "customers prefer dishes made with fresher ingredients" },
      { letter: "C", text: "all necessary ingredients can be obtained from local sources" },
      { letter: "D", text: "shipping ingredients over long distances harms the environment" },
      { letter: "E", text: "local farmers use organic growing methods" },
    ],
    correctAnswer: "C",
    explanation: "The chef recommends sourcing ALL ingredients locally. This is only possible if all necessary ingredients are available locally. If the restaurant needs ingredients that cannot be sourced locally (tropical spices, certain seafood, etc.), the recommendation cannot be fully implemented.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Technology executive: Our company should not develop artificial general intelligence. Such technology could eventually surpass human intelligence and pose existential risks to humanity.`,
    questionStem: "The executive's argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Artificial general intelligence is technically possible to develop" },
      { letter: "B", text: "Other companies will also refrain from developing this technology" },
      { letter: "C", text: "The benefits of artificial general intelligence would not outweigh its risks" },
      { letter: "D", text: "Humanity is incapable of controlling superintelligent AI" },
      { letter: "E", text: "The company has the capability to develop artificial general intelligence" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes the company should not develop AGI because of existential risks. However, if the benefits of AGI vastly outweighed the risks (such as solving disease, climate change, etc.), development might still be justified despite risks. The argument assumes the risks are not outweighed by benefits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Sports analyst: Thompson is the best basketball player in the league. He has the highest scoring average and leads the league in assists.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "scoring and assists are more important measures of player quality than other statistics" },
      { letter: "B", text: "Thompson has no significant weaknesses in his game" },
      { letter: "C", text: "no other player leads the league in both scoring and assists" },
      { letter: "D", text: "Thompson's team has the best record in the league" },
      { letter: "E", text: "individual statistics accurately reflect a player's contribution to team success" },
    ],
    correctAnswer: "A",
    explanation: "The analyst bases the conclusion on two statistics: scoring and assists. For this evidence to support the conclusion that Thompson is the best player, these statistics must be particularly important measures of player quality. If defense, leadership, or other factors are equally or more important, leading in scoring and assists wouldn't necessarily make someone the best player.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Museum director: The museum should deaccession some works from its collection to raise funds for building maintenance. Works that are rarely displayed and have minimal educational value can be sold without significantly diminishing the museum's cultural mission.`,
    questionStem: "The director's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The museum has works in its collection that meet the criteria for deaccessioning" },
      { letter: "B", text: "Selling works from the collection is legal in the museum's jurisdiction" },
      { letter: "C", text: "Other funding sources for building maintenance are not available" },
      { letter: "D", text: "Museums regularly sell works from their collections" },
      { letter: "E", text: "The works to be sold would fetch prices sufficient to cover maintenance costs" },
    ],
    correctAnswer: "A",
    explanation: "The director proposes selling works that are rarely displayed and have minimal educational value. For this plan to be feasible, such works must actually exist in the collection. If all works are regularly displayed or have significant educational value, there would be nothing that meets the criteria for sale.",
    difficulty: "easy",
  },

  // MAIN CONCLUSION QUESTIONS (4 questions: lr-bank25-035 to lr-bank25-038)
  {
    id: "lr-bank25-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Many people believe that success in business requires ruthless competition and a willingness to exploit others. However, research on successful entrepreneurs shows that they typically succeed by building strong relationships and creating value for customers and partners. Cooperation, not exploitation, is the true foundation of sustainable business success.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Many people have mistaken beliefs about what leads to business success" },
      { letter: "B", text: "Research on entrepreneurs provides insight into the nature of business success" },
      { letter: "C", text: "Successful entrepreneurs build strong relationships" },
      { letter: "D", text: "Sustainable business success is based on cooperation rather than exploitation" },
      { letter: "E", text: "Creating value for customers and partners leads to business success" },
    ],
    correctAnswer: "D",
    explanation: "The final sentence states the main conclusion: 'Cooperation, not exploitation, is the true foundation of sustainable business success.' The argument sets up a contrast between popular belief (ruthless competition) and what research shows (relationship-building), leading to this conclusion about what actually drives success.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Critics of social media argue that it promotes superficial relationships. Yet social media allows people to maintain connections with friends and family across great distances, connections that might otherwise fade entirely. Moreover, online communities provide support for people with rare conditions or interests who might otherwise feel isolated. The critics fail to recognize social media's capacity to foster meaningful human connection.`,
    questionStem: "The main point of the argument is that",
    answerChoices: [
      { letter: "A", text: "social media allows people to maintain long-distance relationships" },
      { letter: "B", text: "online communities support people with rare conditions or interests" },
      { letter: "C", text: "critics of social media have overlooked its potential for meaningful connection" },
      { letter: "D", text: "social media promotes both superficial and meaningful relationships" },
      { letter: "E", text: "the benefits of social media outweigh its drawbacks" },
    ],
    correctAnswer: "C",
    explanation: "The argument's structure is: critics say X, but here are counterexamples, therefore the critics are wrong. The main conclusion is that critics fail to recognize social media's capacity for meaningful connection. The examples about long-distance relationships and online communities serve as supporting evidence for this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The government should not subsidize ethanol production. Producing ethanol from corn diverts agricultural resources from food production, contributing to higher food prices. Additionally, when the full production cycle is considered, corn-based ethanol may produce as much greenhouse gas as conventional gasoline. The supposed environmental benefits do not justify the economic costs.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Ethanol production diverts agricultural resources from food production" },
      { letter: "B", text: "Corn-based ethanol may not reduce greenhouse gas emissions" },
      { letter: "C", text: "Ethanol subsidies are not justified by their supposed environmental benefits" },
      { letter: "D", text: "The government should end subsidies for ethanol production" },
      { letter: "E", text: "Higher food prices are an unacceptable consequence of ethanol production" },
    ],
    correctAnswer: "D",
    explanation: "The first sentence states the main conclusion directly: 'The government should not subsidize ethanol production.' The subsequent sentences about food prices, greenhouse gases, and the cost-benefit analysis all serve as reasons supporting this recommendation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Neuroscience has made remarkable progress in understanding how the brain processes information. However, understanding the neural correlates of mental states is not the same as understanding consciousness itself. We can map brain activity during experiences of pain, pleasure, or contemplation, but this tells us nothing about why these physical processes are accompanied by subjective experience. The nature of consciousness remains fundamentally mysterious.`,
    questionStem: "The argument's main conclusion is that",
    answerChoices: [
      { letter: "A", text: "neuroscience has made significant advances in understanding brain function" },
      { letter: "B", text: "neural correlates of mental states are different from consciousness itself" },
      { letter: "C", text: "we can map brain activity during various experiences" },
      { letter: "D", text: "physical brain processes are accompanied by subjective experience" },
      { letter: "E", text: "consciousness remains fundamentally unexplained" },
    ],
    correctAnswer: "E",
    explanation: "The final sentence expresses the main conclusion: 'The nature of consciousness remains fundamentally mysterious.' The argument progresses from acknowledging neuroscience's achievements to distinguishing neural correlates from consciousness itself, leading to the conclusion that despite progress, consciousness itself is not understood.",
    difficulty: "medium",
  },

  // METHOD OF REASONING QUESTIONS (4 questions: lr-bank25-039 to lr-bank25-042)
  {
    id: "lr-bank25-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Naturalist: Some argue that wolves should not be reintroduced to the region because they will kill livestock. However, in Yellowstone National Park, where wolves were reintroduced in 1995, livestock losses have been minimal, and the ecosystem has benefited enormously from the wolves' presence. The fears about livestock are therefore exaggerated.`,
    questionStem: "The naturalist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "challenging the motives of those who oppose wolf reintroduction" },
      { letter: "B", text: "citing a case study to counter predictions about negative consequences" },
      { letter: "C", text: "arguing that environmental benefits justify economic costs" },
      { letter: "D", text: "demonstrating that the opposition's claims are logically inconsistent" },
      { letter: "E", text: "appealing to scientific authority to resolve a factual dispute" },
    ],
    correctAnswer: "B",
    explanation: "The naturalist uses the Yellowstone reintroduction as a real-world case study to argue against predicted negative consequences (livestock losses). By showing that actual experience contradicts the feared outcomes, the argument uses empirical evidence from a specific case to challenge general predictions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Art dealer: This painting is certainly not a genuine Monet. Monet always signed his works in the lower right corner, but this painting has a signature in the lower left corner. Furthermore, the canvas uses a synthetic fiber that was not available during Monet's lifetime.`,
    questionStem: "The art dealer's argument employs which of the following reasoning strategies?",
    answerChoices: [
      { letter: "A", text: "Establishing a general rule and then applying it to a specific case" },
      { letter: "B", text: "Providing multiple independent pieces of evidence that support the same conclusion" },
      { letter: "C", text: "Arguing that the absence of certain features proves the presence of others" },
      { letter: "D", text: "Demonstrating that an alternative explanation is more plausible" },
      { letter: "E", text: "Using expert testimony to establish the authenticity of an artwork" },
    ],
    correctAnswer: "B",
    explanation: "The art dealer offers two separate reasons why the painting is not genuine: the unusual signature placement and the anachronistic canvas material. Each piece of evidence independently supports the conclusion that the painting is not authentic. Neither reason depends on the other.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Political theorist: Those who argue that democracy is the best form of government often point to the prosperity and stability of democratic nations. But this reasoning is flawed. Democratic nations are prosperous and stable because they tend to have strong institutions, rule of law, and educated populations—factors that would promote success under any form of government. Democracy itself may not be the cause of this success.`,
    questionStem: "The political theorist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "accepting an opponent's premise while rejecting their conclusion" },
      { letter: "B", text: "showing that an observed correlation may not indicate causation" },
      { letter: "C", text: "providing counterexamples to a general claim" },
      { letter: "D", text: "arguing that democracy is actually inferior to other forms of government" },
      { letter: "E", text: "demonstrating that the opponent's argument is internally inconsistent" },
    ],
    correctAnswer: "B",
    explanation: "The theorist accepts that democratic nations are prosperous and stable but argues this doesn't prove democracy causes these outcomes. By identifying alternative explanatory factors (institutions, rule of law, education), the theorist challenges the causal inference, showing that correlation doesn't necessarily indicate causation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some believe that we can never truly understand another person's subjective experience. Consider this: I can describe the color red to a blind person using scientific terms—wavelengths, photoreceptors, brain regions—but none of this conveys what it is actually like to experience red. Similarly, no amount of third-person description can capture the first-person nature of any experience.`,
    questionStem: "The philosopher's reasoning relies on",
    answerChoices: [
      { letter: "A", text: "using an analogy to illustrate a broader philosophical point" },
      { letter: "B", text: "refuting an objection by showing it leads to absurd consequences" },
      { letter: "C", text: "establishing a general principle through inductive reasoning" },
      { letter: "D", text: "appealing to scientific evidence to support a philosophical claim" },
      { letter: "E", text: "demonstrating a logical contradiction in the opposing view" },
    ],
    correctAnswer: "A",
    explanation: "The philosopher uses the specific example of describing color to a blind person as an analogy for the general difficulty of conveying subjective experience. The example illustrates the broader claim that third-person descriptions cannot capture first-person experience, using a vivid case to make an abstract point concrete.",
    difficulty: "hard",
  },

  // POINT AT ISSUE QUESTIONS (3 questions: lr-bank25-043 to lr-bank25-045)
  {
    id: "lr-bank25-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Greta: Mandatory voting laws would strengthen democracy by ensuring that election outcomes reflect the will of the entire population, not just those motivated enough to vote voluntarily.\n\nHarold: Mandatory voting would actually weaken democracy because forcing people to vote violates their freedom of political expression. The right to vote includes the right not to vote.`,
    questionStem: "Greta and Harold disagree about whether",
    answerChoices: [
      { letter: "A", text: "mandatory voting laws exist in other democratic countries" },
      { letter: "B", text: "some citizens currently choose not to vote" },
      { letter: "C", text: "election outcomes should reflect the will of the entire population" },
      { letter: "D", text: "mandatory voting would benefit democracy overall" },
      { letter: "E", text: "freedom of expression is important in a democracy" },
    ],
    correctAnswer: "D",
    explanation: "Greta claims mandatory voting would strengthen democracy; Harold claims it would weaken democracy. They directly disagree about the overall effect on democracy. Both would likely agree on C (desirable goal) and E (importance), but disagree about whether mandatory voting achieves democratic aims.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Patel: Medical research using animal subjects is ethically justified because it has led to treatments that save millions of human lives. The benefits to humanity outweigh the harm to the animals.\n\nDr. Wilson: The suffering of research animals cannot be justified merely by benefits to humans. Animals have inherent moral value, and causing them pain for our benefit is wrong regardless of the outcomes.`,
    questionStem: "The main point of disagreement between Dr. Patel and Dr. Wilson is whether",
    answerChoices: [
      { letter: "A", text: "animal research has produced beneficial medical treatments" },
      { letter: "B", text: "animals experience suffering during research" },
      { letter: "C", text: "benefits to humans can morally justify harm to animals" },
      { letter: "D", text: "animals have any moral value" },
      { letter: "E", text: "medical research should continue to advance" },
    ],
    correctAnswer: "C",
    explanation: "Dr. Patel argues that benefits to humanity justify animal suffering, while Dr. Wilson explicitly rejects this, saying animal suffering cannot be justified by human benefits. The core disagreement is about whether a utilitarian calculation (benefits vs. harms) can morally justify using animals in research.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Economist A: Carbon taxes are the most efficient way to reduce greenhouse gas emissions. By making pollution costly, they incentivize businesses and consumers to reduce emissions without requiring specific mandates.\n\nEconomist B: Carbon taxes place an unfair burden on lower-income households who spend a larger proportion of their income on energy. Regulations that require emissions reductions from major industrial polluters would be more equitable.`,
    questionStem: "Economist A and Economist B disagree about",
    answerChoices: [
      { letter: "A", text: "whether greenhouse gas emissions need to be reduced" },
      { letter: "B", text: "whether economic incentives can influence behavior" },
      { letter: "C", text: "the best policy approach for reducing emissions" },
      { letter: "D", text: "whether lower-income households spend more on energy proportionally" },
      { letter: "E", text: "whether industrial polluters contribute significantly to emissions" },
    ],
    correctAnswer: "C",
    explanation: "Both economists want to reduce emissions but disagree about the best method. Economist A favors carbon taxes for their efficiency, while Economist B prefers industrial regulations for equity reasons. The disagreement is about which policy approach is preferable, not about whether action is needed.",
    difficulty: "easy",
  },

  // PARALLEL REASONING QUESTIONS (3 questions: lr-bank25-046 to lr-bank25-048)
  {
    id: "lr-bank25-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No responsible pet owner would leave their dog alone for more than eight hours. Sarah leaves her dog alone for ten hours while she is at work. Therefore, Sarah is not a responsible pet owner.`,
    questionStem: "Which one of the following arguments is most similar in its pattern of reasoning to the argument above?",
    answerChoices: [
      { letter: "A", text: "All qualified candidates have graduate degrees. Thompson has a graduate degree. Therefore, Thompson is a qualified candidate." },
      { letter: "B", text: "No ethical journalist would publish unverified information. This article contains unverified claims. Therefore, the journalist who wrote it acted unethically." },
      { letter: "C", text: "Most successful athletes train daily. Garcia trains daily. Therefore, Garcia is probably a successful athlete." },
      { letter: "D", text: "Some experienced hikers use trekking poles. Martinez is an experienced hiker. Therefore, Martinez might use trekking poles." },
      { letter: "E", text: "All nutritious foods contain vitamins. This snack contains vitamins. Therefore, this snack is nutritious." },
    ],
    correctAnswer: "B",
    explanation: "The original argument has the form: No X would do Y. This person does Y. Therefore, this person is not X. Answer B follows the same pattern: No ethical journalist would publish unverified information. This journalist published unverified information. Therefore, this journalist is not ethical.",
    difficulty: "medium",
  },
  {
    id: "lr-bank25-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy improves, unemployment will decrease. If unemployment decreases, consumer spending will increase. Therefore, if the economy improves, consumer spending will increase.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If plants receive sunlight, they produce chlorophyll. If plants produce chlorophyll, they appear green. Therefore, if plants receive sunlight, they appear green." },
      { letter: "B", text: "If taxes increase, revenue grows. Revenue has grown. Therefore, taxes must have increased." },
      { letter: "C", text: "If the temperature drops, water freezes. The temperature has not dropped. Therefore, the water has not frozen." },
      { letter: "D", text: "Some students who study pass exams. Jamie is a student who studies. Therefore, Jamie will pass exams." },
      { letter: "E", text: "All mammals are warm-blooded. All whales are mammals. Therefore, all whales are warm-blooded." },
    ],
    correctAnswer: "A",
    explanation: "The original argument uses hypothetical syllogism (chain reasoning): If P then Q; If Q then R; Therefore, if P then R. Answer A follows this same pattern: If sunlight then chlorophyll; If chlorophyll then green; Therefore, if sunlight then green. Both chain conditional statements to reach a conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank25-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Either the company will expand into new markets or it will increase investment in existing operations. The company has decided not to expand into new markets. Therefore, it will increase investment in existing operations.`,
    questionStem: "Which one of the following arguments exhibits reasoning most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "Either the defendant was at the scene or has an alibi. The defendant was at the scene. Therefore, the defendant does not have an alibi." },
      { letter: "B", text: "Either the contract will be signed today or negotiations will continue. Negotiations will not continue. Therefore, the contract will be signed today." },
      { letter: "C", text: "Either all employees received bonuses or some received raises. All employees received bonuses. Therefore, no employees received raises." },
      { letter: "D", text: "The project will succeed only if funding is approved. Funding was approved. Therefore, the project will succeed." },
      { letter: "E", text: "If the weather is good, the event will be outdoors. The event was outdoors. Therefore, the weather was good." },
    ],
    correctAnswer: "B",
    explanation: "The original uses disjunctive syllogism: Either P or Q; Not P; Therefore Q. Answer B follows the same form: Either contract signed or negotiations continue; Not continue; Therefore signed. Both eliminate one disjunct to affirm the other.",
    difficulty: "easy",
  },

  // INFERENCE QUESTIONS (2 questions: lr-bank25-049 to lr-bank25-050)
  {
    id: "lr-bank25-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the debate team are either seniors or juniors. No freshman is eligible for the scholarship competition. Some members of the debate team are eligible for the scholarship competition.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All seniors on the debate team are eligible for the scholarship competition" },
      { letter: "B", text: "No member of the debate team is a freshman" },
      { letter: "C", text: "Some seniors or juniors are eligible for the scholarship competition" },
      { letter: "D", text: "All members eligible for the scholarship competition are on the debate team" },
      { letter: "E", text: "Most debate team members are juniors" },
    ],
    correctAnswer: "C",
    explanation: "We know: (1) All debate team members are seniors or juniors, (2) No freshman can compete for the scholarship, (3) Some debate team members can compete. From (1) and (3), some seniors or juniors (specifically those on the debate team) are scholarship-eligible. Therefore, C must be true.",
    difficulty: "hard",
  },
  {
    id: "lr-bank25-050",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The museum is open every day except Mondays and holidays. The first Monday of each month is always a holiday. The museum offers free admission on the last Sunday of each month.`,
    questionStem: "Which one of the following can be properly inferred from the statements above?",
    answerChoices: [
      { letter: "A", text: "The museum is never open on the first Monday of any month" },
      { letter: "B", text: "The museum offers free admission exactly once per month" },
      { letter: "C", text: "The museum is always open on the last Sunday of each month" },
      { letter: "D", text: "The museum is closed more days in months with more holidays" },
      { letter: "E", text: "Free admission is only offered on Sundays" },
    ],
    correctAnswer: "A",
    explanation: "The museum is closed on Mondays and holidays. The first Monday of each month is always a holiday. Therefore, the first Monday is always a day the museum would be closed (it's both a Monday AND a holiday). Answer C is not necessarily true because the last Sunday might fall on a holiday, when the museum would be closed.",
    difficulty: "medium",
  },
];
