// Logical Reasoning Questions Bank - Set 43
import { Question } from "../lsat-types";

export const lrQuestionsSet43: Question[] = [
  {
    id: "lr-bank43-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that students who eat breakfast perform better on standardized tests than students who skip breakfast. Therefore, eating breakfast must cause improved academic performance.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that students who eat breakfast may also get more sleep" },
      { letter: "B", text: "assumes that correlation between two factors establishes a causal relationship" },
      { letter: "C", text: "relies on a sample that is too small to be representative" },
      { letter: "D", text: "ignores the possibility that some students prefer not to eat in the morning" },
      { letter: "E", text: "fails to define what constitutes a proper breakfast" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the classic correlation-causation fallacy. Just because two things occur together (eating breakfast and better test performance) does not mean one causes the other. There could be a third factor, such as socioeconomic status or parental involvement, that influences both.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martinez argues that we should increase funding for the arts in public schools. But Professor Martinez is a painter who sells her work for thousands of dollars. Clearly, her argument should be dismissed as self-serving.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that Professor Martinez might have valid reasons for her position" },
      { letter: "B", text: "attacks the person making the argument rather than addressing the argument itself" },
      { letter: "C", text: "assumes that all artists benefit equally from arts education funding" },
      { letter: "D", text: "ignores evidence that arts education has measurable benefits" },
      { letter: "E", text: "confuses a necessary condition with a sufficient condition" },
    ],
    correctAnswer: "B",
    explanation: "This is an ad hominem fallacy. The argument attacks Professor Martinez's character and potential motivations rather than addressing the merits of her argument about arts funding. Even if she has a personal interest, her argument could still be valid.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-003",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Pharmaceutical company executives argue that high drug prices are necessary to fund research and development of new medications. However, critics point out that these companies spend more on marketing than on research. The executives respond that without premium pricing, many life-saving drugs would never be developed.`,
    questionStem: "Which one of the following, if true, most strengthens the executives' argument?",
    answerChoices: [
      { letter: "A", text: "Marketing expenses have decreased over the past decade" },
      { letter: "B", text: "The average cost of bringing a new drug to market has increased tenfold in the past twenty years" },
      { letter: "C", text: "Some pharmaceutical companies have higher profit margins than others" },
      { letter: "D", text: "Generic drug manufacturers also conduct research and development" },
      { letter: "E", text: "Government regulations require extensive testing before drugs can be sold" },
    ],
    correctAnswer: "B",
    explanation: "If the cost of developing new drugs has increased dramatically, this supports the executives' claim that high prices are needed to fund research and development. The tenfold increase suggests that significant revenue is indeed necessary to bring new medications to market.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-004",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `City officials claim that the new traffic light system has reduced accidents at major intersections. They cite data showing a 30% decrease in accidents at intersections where the new lights were installed. Based on this, they recommend expanding the system citywide.`,
    questionStem: "Which one of the following, if true, most seriously weakens the officials' argument?",
    answerChoices: [
      { letter: "A", text: "The new traffic lights are more expensive to maintain than the old ones" },
      { letter: "B", text: "Accidents at intersections without the new lights decreased by 35% during the same period" },
      { letter: "C", text: "Some drivers have complained that the new lights are confusing" },
      { letter: "D", text: "The new lights use more energy than the previous system" },
      { letter: "E", text: "Traffic volume has remained constant over the past year" },
    ],
    correctAnswer: "B",
    explanation: "If accidents decreased even more at intersections without the new lights, this suggests the reduction wasn't caused by the new system. Some other factor, such as decreased traffic or improved driver education, might be responsible for the overall decline in accidents.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-005",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All successful entrepreneurs are willing to take calculated risks. Maria is willing to take calculated risks. Therefore, Maria will be a successful entrepreneur.`,
    questionStem: "The conclusion follows logically if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "Taking calculated risks is the only factor in entrepreneurial success" },
      { letter: "B", text: "Maria has other qualities common to successful entrepreneurs" },
      { letter: "C", text: "Anyone willing to take calculated risks will be a successful entrepreneur" },
      { letter: "D", text: "Most people who take calculated risks become successful" },
      { letter: "E", text: "Maria has experience in business management" },
    ],
    correctAnswer: "C",
    explanation: "The argument confuses a necessary condition with a sufficient condition. The premise states that all successful entrepreneurs take risks (necessary condition), but concludes that taking risks leads to success. For the conclusion to follow, we must assume that risk-taking is sufficient for success, not just necessary.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-006",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Many people believe that organic foods are healthier than conventionally grown foods. However, numerous scientific studies have found no significant nutritional differences between them. While organic farming may have environmental benefits, consumers who pay premium prices for organic foods solely for health reasons are not getting what they pay for.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Organic foods are not nutritionally superior to conventional foods" },
      { letter: "B", text: "Consumers should not purchase organic foods" },
      { letter: "C", text: "People who buy organic foods for health benefits are not receiving additional value" },
      { letter: "D", text: "Organic farming has environmental benefits" },
      { letter: "E", text: "Scientific studies are the best way to evaluate food quality" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is that consumers paying premium prices for organic foods solely for health reasons are not getting what they pay for. The lack of nutritional difference is evidence supporting this conclusion, and the environmental benefits are acknowledged as a separate consideration.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-007",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The novelist claims her work is entirely original. But Chapter 3 of her latest book contains a scene remarkably similar to one in a classic novel published fifty years ago. Either she plagiarized or she was unconsciously influenced by that earlier work. In neither case is her work entirely original.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing an example that contradicts a general claim" },
      { letter: "B", text: "presenting two alternatives and showing both lead to the same conclusion" },
      { letter: "C", text: "questioning the novelist's expertise in literary matters" },
      { letter: "D", text: "appealing to the authority of earlier literary works" },
      { letter: "E", text: "arguing that the novelist's intentions are irrelevant to the quality of her work" },
    ],
    correctAnswer: "B",
    explanation: "The critic presents a dilemma: either the novelist plagiarized or was unconsciously influenced. The critic then shows that either alternative leads to the same conclusion—that the work is not entirely original. This is a classic disjunctive syllogism approach.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The government should not regulate carbon emissions from factories. After all, if we start regulating carbon emissions, next we'll be regulating what cars people can drive, then what they can eat, and eventually the government will control every aspect of our lives.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to provide evidence that carbon emissions are harmful" },
      { letter: "B", text: "assumes without justification that one action will inevitably lead to extreme consequences" },
      { letter: "C", text: "ignores the economic benefits of environmental regulation" },
      { letter: "D", text: "relies on an inappropriate appeal to popular opinion" },
      { letter: "E", text: "confuses a cause with an effect" },
    ],
    correctAnswer: "B",
    explanation: "This is a slippery slope fallacy. The argument assumes that regulating carbon emissions will inevitably lead to a series of increasingly extreme regulations without providing evidence for this chain of events. Each step in the progression is assumed without justification.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-009",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers have discovered that people who regularly practice meditation show increased gray matter density in brain regions associated with learning, memory, and emotional regulation. Based on this finding, the researchers concluded that meditation enhances cognitive function.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Gray matter density in these regions correlates strongly with performance on cognitive tests" },
      { letter: "B", text: "Meditation has been practiced for thousands of years" },
      { letter: "C", text: "Some forms of meditation are easier to learn than others" },
      { letter: "D", text: "The study participants had been meditating for varying lengths of time" },
      { letter: "E", text: "Other activities, such as exercise, also increase gray matter density" },
    ],
    correctAnswer: "A",
    explanation: "The argument claims meditation enhances cognitive function based on increased gray matter. If gray matter density correlates strongly with cognitive performance, this establishes the link between the observed physical change and the claimed benefit, strengthening the conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city's new recycling program has been a success. Since its implementation six months ago, the amount of recyclable material collected has increased by 40%. This demonstrates that residents are committed to environmental responsibility.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "The new program includes curbside pickup, whereas the old program required residents to transport recyclables themselves" },
      { letter: "B", text: "Neighboring cities have also seen increases in recycling" },
      { letter: "C", text: "The cost of the new program is higher than the previous one" },
      { letter: "D", text: "Some residents have complained about the new recycling bins" },
      { letter: "E", text: "The city's population has remained stable over the past six months" },
    ],
    correctAnswer: "A",
    explanation: "If the new program made recycling more convenient through curbside pickup, the increase might reflect convenience rather than increased environmental commitment. Residents may have always been willing to recycle but were deterred by the inconvenience of the old system.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-011",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The defendant could not have committed the crime because she was seen at a restaurant across town at 8:00 PM, which is exactly when the crime occurred. Therefore, she has an airtight alibi.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The witnesses who saw the defendant at the restaurant are telling the truth" },
      { letter: "B", text: "It was impossible for the defendant to travel from the restaurant to the crime scene and back without being noticed" },
      { letter: "C", text: "The crime could only have been committed at exactly 8:00 PM" },
      { letter: "D", text: "The defendant has no history of criminal behavior" },
      { letter: "E", text: "No one else could have committed the crime" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes the crime occurred at exactly 8:00 PM and could only have been committed at that precise time. If the crime could have occurred at a different time, the alibi for 8:00 PM would not clear the defendant.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Chen: Artificial intelligence will never truly replicate human consciousness because consciousness requires subjective experience, which cannot be programmed into a machine.

Dr. Patel: I disagree. As AI systems become more sophisticated, they will eventually develop emergent properties, including something functionally equivalent to consciousness.`,
    questionStem: "The main point at issue between Dr. Chen and Dr. Patel is",
    answerChoices: [
      { letter: "A", text: "whether current AI systems exhibit any form of consciousness" },
      { letter: "B", text: "whether subjective experience can be defined precisely" },
      { letter: "C", text: "whether machines can ever achieve something equivalent to human consciousness" },
      { letter: "D", text: "whether programming is the only way to create artificial intelligence" },
      { letter: "E", text: "whether emergent properties are scientifically valid phenomena" },
    ],
    correctAnswer: "C",
    explanation: "Dr. Chen claims AI can never replicate consciousness, while Dr. Patel believes sophisticated AI will develop functional consciousness. Their disagreement centers on whether machines can ever achieve something equivalent to human consciousness.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All mammals are warm-blooded. All whales are mammals. Therefore, all whales are warm-blooded.`,
    questionStem: "Which one of the following arguments is most similar in its pattern of reasoning to the argument above?",
    answerChoices: [
      { letter: "A", text: "All roses are flowers. Some flowers are red. Therefore, some roses are red." },
      { letter: "B", text: "All attorneys must pass the bar exam. All public defenders are attorneys. Therefore, all public defenders must pass the bar exam." },
      { letter: "C", text: "Most birds can fly. Penguins are birds. Therefore, penguins can probably fly." },
      { letter: "D", text: "Some politicians are dishonest. All dishonest people should be criticized. Therefore, some politicians should be criticized." },
      { letter: "E", text: "All vegetables are nutritious. Carrots are orange. Therefore, orange things are nutritious." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow the same valid syllogistic pattern: All A are B, All C are A, Therefore all C are B. The original and answer B both establish a characteristic of a category and then apply it to a subset of that category.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-014",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `A recent survey of employees at a large corporation found that 80% of those who work from home at least three days per week report high job satisfaction. Only 45% of those who work entirely in the office report the same level of satisfaction. The survey also found that employees with high job satisfaction are twice as likely to remain with the company for more than five years.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Working from home causes increased job satisfaction" },
      { letter: "B", text: "Most employees prefer working from home" },
      { letter: "C", text: "Employees who work from home are more productive than those in the office" },
      { letter: "D", text: "Some employees who work entirely in the office report high job satisfaction" },
      { letter: "E", text: "All employees with high job satisfaction work from home" },
    ],
    correctAnswer: "D",
    explanation: "Since 45% of office workers report high job satisfaction, some office workers must report high satisfaction. This is the only statement that must be true based on the given information. The other options either overstate the findings or infer causation from correlation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-015",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `No one has ever proven that ghosts don't exist. Therefore, ghosts must exist.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on evidence that is outdated" },
      { letter: "B", text: "treats the absence of proof against a claim as proof of that claim" },
      { letter: "C", text: "uses ambiguous language that could be interpreted in multiple ways" },
      { letter: "D", text: "generalizes from a single instance to a broad conclusion" },
      { letter: "E", text: "assumes that what is true of a part is true of the whole" },
    ],
    correctAnswer: "B",
    explanation: "This is an argument from ignorance (argumentum ad ignorantiam). The argument incorrectly assumes that because something hasn't been disproven, it must be true. The lack of evidence against a claim is not evidence for that claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The ancient city of Xanadu fell not because of military conquest but because of environmental degradation. Archaeological evidence shows that the surrounding forests were completely depleted in the century before the city's abandonment. Without wood for fuel and construction, the city became unsustainable.`,
    questionStem: "Which one of the following, if true, most strengthens the historian's argument?",
    answerChoices: [
      { letter: "A", text: "Other ancient cities in the region survived despite similar military threats" },
      { letter: "B", text: "The city's population declined gradually rather than suddenly, consistent with resource depletion" },
      { letter: "C", text: "Ancient texts mention the city's beautiful forests" },
      { letter: "D", text: "The city had strong defensive walls" },
      { letter: "E", text: "Modern cities face similar environmental challenges" },
    ],
    correctAnswer: "B",
    explanation: "A gradual population decline supports the environmental degradation theory, as military conquest typically causes sudden abandonment. The gradual decline is consistent with slowly depleting resources making the city increasingly difficult to sustain.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-017",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Mandatory minimum sentences for drug offenses have failed to reduce drug use. Despite decades of harsh penalties, drug use rates remain relatively stable. Therefore, we should eliminate mandatory minimums and focus on treatment and rehabilitation instead.`,
    questionStem: "Which one of the following, if true, most weakens the legal scholar's argument?",
    answerChoices: [
      { letter: "A", text: "Some countries with lenient drug policies have lower drug use rates" },
      { letter: "B", text: "Drug use rates would have increased significantly without mandatory minimums" },
      { letter: "C", text: "Treatment programs are more expensive than incarceration" },
      { letter: "D", text: "Mandatory minimums were originally implemented to address a drug crisis" },
      { letter: "E", text: "Some judges oppose mandatory minimum sentences" },
    ],
    correctAnswer: "B",
    explanation: "If drug use would have increased without mandatory minimums, then the stable rates actually represent a success, not a failure. The policy may have prevented an increase even if it didn't cause a decrease, weakening the argument that it has failed.",
    difficulty: "hard",
  },
  {
    id: "lr-bank43-018",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Companies that invest heavily in employee training have lower turnover rates. Our company has high turnover. Therefore, we need to increase our investment in employee training.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "employee training is the only factor affecting turnover rates" },
      { letter: "B", text: "increased training investment would lead to lower turnover at this company" },
      { letter: "C", text: "the company currently invests nothing in employee training" },
      { letter: "D", text: "all companies with high turnover lack training programs" },
      { letter: "E", text: "lower turnover is always beneficial for a company" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that what works generally (training reduces turnover) will work for this specific company. Without this assumption, the recommendation to increase training investment wouldn't follow from the general observation about training and turnover.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-019",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Critics argue that social media platforms should not moderate content because doing so infringes on free speech. However, these platforms are private companies, not government entities, and the First Amendment only restricts government action. Private companies have the right to establish and enforce their own rules. Therefore, content moderation by social media companies does not violate free speech principles.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Social media platforms are private companies" },
      { letter: "B", text: "The First Amendment only applies to government action" },
      { letter: "C", text: "Content moderation by social media companies is not a free speech violation" },
      { letter: "D", text: "Private companies have the right to make their own rules" },
      { letter: "E", text: "Critics of content moderation misunderstand constitutional law" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion, signaled by 'Therefore,' is that content moderation by social media companies does not violate free speech principles. The other statements are premises supporting this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-020",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Some argue that raising the minimum wage will lead to job losses. But when the minimum wage was raised in 1997, 2007, and 2009, employment actually increased in the following years. This shows that raising the minimum wage does not cause unemployment.`,
    questionStem: "The economist's argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on too few examples to establish a general pattern" },
      { letter: "B", text: "fails to consider that employment might have increased even more without wage increases" },
      { letter: "C", text: "assumes that what happened in the past will happen in the future" },
      { letter: "D", text: "ignores the views of those who disagree with raising the minimum wage" },
      { letter: "E", text: "confuses correlation with causation" },
    ],
    correctAnswer: "B",
    explanation: "The economist's argument is flawed because it doesn't consider the counterfactual: employment might have increased even more if the minimum wage hadn't been raised. The fact that employment increased doesn't prove the wage increase didn't limit employment growth.",
    difficulty: "hard",
  },
  {
    id: "lr-bank43-021",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The government's new education initiative must be effective because the Secretary of Education, who has a doctorate in educational psychology and thirty years of experience, personally endorsed it.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "appeals to an authority's endorsement rather than evaluating the initiative on its merits" },
      { letter: "B", text: "fails to define what would constitute an effective education initiative" },
      { letter: "C", text: "ignores the possibility that other experts might disagree" },
      { letter: "D", text: "assumes that past success guarantees future results" },
      { letter: "E", text: "generalizes from one person's experience to all education professionals" },
    ],
    correctAnswer: "A",
    explanation: "This is an appeal to authority fallacy. While the Secretary has relevant credentials, the argument relies solely on her endorsement rather than evaluating the actual merits of the initiative. Credentials don't guarantee that every opinion or endorsement is correct.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-022",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Biologist: The decline in the monarch butterfly population is primarily caused by the reduction of milkweed plants, which are the only food source for monarch caterpillars. Agricultural herbicides have eliminated milkweed from millions of acres of farmland. To save the monarch, we must restore milkweed habitats.`,
    questionStem: "Which one of the following, if true, most strengthens the biologist's argument?",
    answerChoices: [
      { letter: "A", text: "Monarch butterfly populations have declined by over 80% in the past two decades" },
      { letter: "B", text: "Areas where milkweed has been deliberately replanted show increased monarch butterfly populations" },
      { letter: "C", text: "Milkweed is considered a nuisance plant by many farmers" },
      { letter: "D", text: "Climate change is also affecting monarch butterfly migration patterns" },
      { letter: "E", text: "Some pesticides directly harm adult monarch butterflies" },
    ],
    correctAnswer: "B",
    explanation: "Evidence that replanting milkweed leads to increased monarch populations directly supports the claim that milkweed loss is the primary cause of decline and that restoring habitats is the solution. This provides empirical support for the proposed remedy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A study of 500 executives found that those who exercise regularly are more likely to receive promotions. The researchers concluded that exercise improves leadership qualities that lead to career advancement.`,
    questionStem: "Which one of the following, if true, most weakens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Some executives who don't exercise have also received promotions" },
      { letter: "B", text: "Higher-ranking executives often have more leisure time and resources for exercise" },
      { letter: "C", text: "The study did not control for the type of exercise performed" },
      { letter: "D", text: "Regular exercise has been shown to improve cognitive function" },
      { letter: "E", text: "Most of the executives in the study worked at large corporations" },
    ],
    correctAnswer: "B",
    explanation: "This suggests reverse causation: rather than exercise leading to promotions, promotions (higher rank) lead to more time and resources for exercise. The correlation might be explained by career success enabling exercise rather than exercise enabling success.",
    difficulty: "hard",
  },
  {
    id: "lr-bank43-024",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new interactive exhibit has been visited by over 100,000 people in its first month. Clearly, the museum's decision to invest in interactive technology was wise.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Interactive exhibits are more educational than traditional displays" },
      { letter: "B", text: "High visitor numbers indicate a wise investment" },
      { letter: "C", text: "The museum had never invested in technology before" },
      { letter: "D", text: "All 100,000 visitors enjoyed the interactive exhibit" },
      { letter: "E", text: "The exhibit will continue to attract visitors" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from high visitor numbers to the conclusion that the investment was wise. This assumes that visitor numbers are a good measure of investment wisdom. Without this assumption, high attendance wouldn't necessarily indicate a wise decision.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-025",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Yamamoto: Universities should prioritize research over teaching because research advances human knowledge and brings prestige and funding to institutions.

Professor Wilson: On the contrary, teaching should be the primary mission of universities. Research is valuable, but educating the next generation of thinkers is what truly benefits society.`,
    questionStem: "Professor Yamamoto and Professor Wilson disagree about",
    answerChoices: [
      { letter: "A", text: "whether research advances human knowledge" },
      { letter: "B", text: "whether teaching benefits society" },
      { letter: "C", text: "which function should be the primary focus of universities" },
      { letter: "D", text: "whether universities can pursue both research and teaching" },
      { letter: "E", text: "whether prestige is important for universities" },
    ],
    correctAnswer: "C",
    explanation: "The professors explicitly disagree about what should be universities' primary focus—research or teaching. Both seem to acknowledge that both activities have value, but they disagree about which should take priority.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-026",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy improves, consumer spending will increase. If consumer spending increases, retail profits will rise. Therefore, if the economy improves, retail profits will rise.`,
    questionStem: "Which one of the following arguments is most similar in its pattern of reasoning?",
    answerChoices: [
      { letter: "A", text: "If it rains, the ground will be wet. The ground is wet. Therefore, it rained." },
      { letter: "B", text: "If the temperature drops below freezing, the pipes will burst. If the pipes burst, we will have water damage. Therefore, if the temperature drops below freezing, we will have water damage." },
      { letter: "C", text: "Either we leave now or we will be late. We are not leaving now. Therefore, we will be late." },
      { letter: "D", text: "All doctors have medical degrees. Smith is a doctor. Therefore, Smith has a medical degree." },
      { letter: "E", text: "Most students who study pass the exam. John studied. Therefore, John probably passed." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments are hypothetical syllogisms (chain arguments): If A then B, If B then C, Therefore if A then C. The original connects economy to spending to profits; answer B connects temperature to pipes to water damage using the same logical structure.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-027",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Mayor Thompson's proposed highway expansion should be rejected. After all, construction companies that would benefit from the project have donated heavily to his campaign. His motivation is clearly to reward his donors, not to improve transportation.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "presents no evidence that the highway expansion would fail to improve transportation" },
      { letter: "B", text: "assumes that all campaign donations are corrupt" },
      { letter: "C", text: "fails to consider that other mayors have also received campaign donations" },
      { letter: "D", text: "ignores the possibility that the proposal could benefit both donors and the public" },
      { letter: "E", text: "relies on speculation about the Mayor's motivations rather than the merits of the proposal" },
    ],
    correctAnswer: "E",
    explanation: "The argument attacks the Mayor's alleged motivations without addressing whether the highway expansion would actually benefit the city. Even if the Mayor were motivated by donor relationships, the proposal could still be a good one. This is a variant of the ad hominem fallacy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-028",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Moral truths are not culturally relative but universal. The fact that virtually every society throughout history has prohibited murder, theft, and lying demonstrates that some moral principles transcend cultural boundaries.`,
    questionStem: "Which one of the following, if true, most strengthens the philosopher's argument?",
    answerChoices: [
      { letter: "A", text: "Some societies have had more permissive attitudes toward violence than others" },
      { letter: "B", text: "These moral prohibitions emerged independently in isolated cultures with no contact with each other" },
      { letter: "C", text: "Modern international law reflects these universal moral principles" },
      { letter: "D", text: "Philosophers have debated moral relativism for centuries" },
      { letter: "E", text: "Some individuals in every society violate these moral prohibitions" },
    ],
    correctAnswer: "B",
    explanation: "If these moral prohibitions emerged independently in isolated cultures, this supports the idea that they reflect universal truths rather than cultural transmission. Independent discovery suggests an inherent quality to these principles rather than mere convention.",
    difficulty: "hard",
  },
  {
    id: "lr-bank43-029",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Eating chocolate is good for heart health. Studies show that people who eat chocolate regularly have a 37% lower risk of heart disease than those who rarely eat chocolate.`,
    questionStem: "Which one of the following, if true, most seriously weakens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Chocolate contains sugar, which is unhealthy in large quantities" },
      { letter: "B", text: "People with existing heart conditions are often advised to avoid chocolate" },
      { letter: "C", text: "Dark chocolate contains more antioxidants than milk chocolate" },
      { letter: "D", text: "The studies were funded by chocolate manufacturers" },
      { letter: "E", text: "Regular chocolate eaters in the studies also had healthier overall lifestyles" },
    ],
    correctAnswer: "E",
    explanation: "If regular chocolate eaters also had healthier overall lifestyles, the lower heart disease risk might be due to these other factors rather than chocolate consumption. This is a confounding variable that undermines the causal claim about chocolate.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city council voted to ban plastic bags because they harm marine life. Councilwoman Rodriguez voted against the ban. Therefore, Councilwoman Rodriguez does not care about marine life.`,
    questionStem: "The argument's conclusion depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Plastic bags are the only threat to marine life" },
      { letter: "B", text: "Voting against the ban is the only indication of not caring about marine life" },
      { letter: "C", text: "The only reason to vote against the ban would be indifference to marine life" },
      { letter: "D", text: "The city council should always vote unanimously on environmental issues" },
      { letter: "E", text: "Councilwoman Rodriguez uses plastic bags regularly" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes there could be no other reason for opposing the ban besides indifference to marine life. The councilwoman might have voted against it for other reasons—concerns about economic impact, enforcement difficulties, or preference for alternative solutions—while still caring about marine life.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-031",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: Some claim that negative campaign advertisements are effective because candidates who use them often win. But this overlooks the fact that candidates who are already ahead in polls are more likely to have opponents who run negative ads against them. The winning candidates' success may have nothing to do with their own negative advertising.`,
    questionStem: "The political analyst responds to the claim by",
    answerChoices: [
      { letter: "A", text: "questioning the integrity of those who make the claim" },
      { letter: "B", text: "offering an alternative explanation for the observed correlation" },
      { letter: "C", text: "presenting statistical evidence that contradicts the claim" },
      { letter: "D", text: "arguing that the claim is based on too few examples" },
      { letter: "E", text: "demonstrating that the claim leads to a logical contradiction" },
    ],
    correctAnswer: "B",
    explanation: "The analyst offers an alternative explanation for why candidates using negative ads often win—they were already ahead and attracted negative ads from opponents. This provides a different causal story that doesn't require negative ads to be effective.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-032",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Our city's public transit system is excellent. I take the downtown express bus to work every day, and it's always clean, punctual, and uncrowded.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on evidence that may not be representative of the entire system" },
      { letter: "B", text: "fails to compare the city's transit system to those of other cities" },
      { letter: "C", text: "assumes that what is true today will remain true in the future" },
      { letter: "D", text: "does not consider the cost of public transit" },
      { letter: "E", text: "ignores the environmental benefits of public transit" },
    ],
    correctAnswer: "A",
    explanation: "The speaker generalizes about the entire transit system based only on experience with one bus route. Other routes might be crowded, dirty, or frequently delayed. This is a hasty generalization from a limited, possibly unrepresentative sample.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-033",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Criminologist: Longer prison sentences do not effectively deter crime. Countries with shorter average sentences often have lower crime rates than countries with longer sentences. Resources would be better spent on education and social services that address the root causes of criminal behavior.`,
    questionStem: "Which one of the following, if true, most strengthens the criminologist's argument?",
    answerChoices: [
      { letter: "A", text: "Prisoners who serve longer sentences are more likely to commit crimes after release" },
      { letter: "B", text: "Public opinion strongly favors long sentences for violent criminals" },
      { letter: "C", text: "Some countries with short sentences also have well-funded social programs" },
      { letter: "D", text: "The cost of incarceration has increased dramatically in recent years" },
      { letter: "E", text: "Most criminals do not research sentencing laws before committing crimes" },
    ],
    correctAnswer: "E",
    explanation: "If criminals don't research sentencing laws before committing crimes, they can't be deterred by longer sentences because they're unaware of them. This directly supports the claim that longer sentences don't effectively deter crime.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-034",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The new superintendent has improved our school district. Test scores have risen 15% since she took office three years ago.`,
    questionStem: "Which one of the following, if true, most weakens this argument?",
    answerChoices: [
      { letter: "A", text: "The superintendent was hired specifically because of her reputation for improving schools" },
      { letter: "B", text: "Teacher salaries have remained unchanged during her tenure" },
      { letter: "C", text: "Statewide test scores increased by 20% over the same period due to curriculum changes mandated by the state" },
      { letter: "D", text: "Some parents have criticized the superintendent's policies" },
      { letter: "E", text: "The superintendent previously worked in a larger school district" },
    ],
    correctAnswer: "C",
    explanation: "If statewide scores increased even more (20%) than the district's (15%), the improvement in this district might be due to the state curriculum changes rather than the superintendent's leadership. The district actually underperformed compared to the state average.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-035",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All of the candidates who passed the written examination were invited to interview. Some candidates who were invited to interview did not accept positions with the company. Everyone who accepted a position had relevant work experience.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "All candidates with relevant work experience passed the written examination" },
      { letter: "B", text: "Some candidates who passed the written examination had relevant work experience" },
      { letter: "C", text: "Everyone who accepted a position passed the written examination" },
      { letter: "D", text: "No candidate without relevant work experience was invited to interview" },
      { letter: "E", text: "Some candidates who had relevant work experience were not invited to interview" },
    ],
    correctAnswer: "C",
    explanation: "We know: Pass exam → Interview invitation. Accept position → Had work experience. Since accepting a position implies having been interviewed (you can't accept without being offered, which requires an interview), and being interviewed implies passing the exam, everyone who accepted a position must have passed the written examination.",
    difficulty: "hard",
  },
  {
    id: "lr-bank43-036",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The restaurant must be excellent because it has been in business for over fifty years. No restaurant could survive that long unless it served high-quality food.`,
    questionStem: "Which one of the following is an assumption on which the argument depends?",
    answerChoices: [
      { letter: "A", text: "The restaurant has had the same owner for fifty years" },
      { letter: "B", text: "Quality of food is the primary factor determining a restaurant's longevity" },
      { letter: "C", text: "Newer restaurants cannot be as good as older ones" },
      { letter: "D", text: "The restaurant has never changed its menu" },
      { letter: "E", text: "Customers prefer older restaurants to newer ones" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that survival depends primarily on food quality. If other factors like location, price, lack of competition, or family tradition could explain longevity, then survival wouldn't necessarily indicate quality. The argument needs food quality to be the key survival factor.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Opponents of the proposed dam argue it will harm endangered fish species. Supporters counter that the dam will provide clean energy and reduce reliance on fossil fuels. Both sides make valid points, but environmental protection and energy needs are not mutually exclusive. With proper fish ladders and seasonal water management, the dam can generate power while protecting wildlife.`,
    questionStem: "The main conclusion of the argument is that",
    answerChoices: [
      { letter: "A", text: "fish ladders can help endangered species navigate dams" },
      { letter: "B", text: "opponents and supporters of the dam both make valid points" },
      { letter: "C", text: "the dam can be built in a way that addresses both environmental and energy concerns" },
      { letter: "D", text: "clean energy is an important goal" },
      { letter: "E", text: "endangered fish species must be protected" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is that the dam can generate power while protecting wildlife—in other words, both goals can be achieved simultaneously. The acknowledgment that both sides have valid points and the specific solutions mentioned are supporting points leading to this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-038",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Reyes claims that the new medication is safe because clinical trials showed no serious side effects. However, the trials lasted only six months. We cannot know the long-term effects without long-term studies. Therefore, we cannot yet conclude that the medication is safe.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "attacking Dr. Reyes's qualifications to evaluate medical research" },
      { letter: "B", text: "presenting new evidence that contradicts the clinical trial results" },
      { letter: "C", text: "arguing that the evidence supporting the conclusion is insufficient" },
      { letter: "D", text: "claiming that all new medications are inherently dangerous" },
      { letter: "E", text: "questioning the methodology used in the clinical trials" },
    ],
    correctAnswer: "C",
    explanation: "The argument challenges the conclusion not by presenting contrary evidence but by arguing that the six-month trials are insufficient to establish long-term safety. It attacks the adequacy of the evidence rather than providing counter-evidence.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-039",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Either we invest in renewable energy now, or we will face catastrophic climate change. We cannot afford catastrophic climate change. Therefore, we must invest in renewable energy now.`,
    questionStem: "The reasoning in this argument is vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "presents a false dichotomy by ignoring other possible solutions" },
      { letter: "B", text: "appeals to fear rather than logic" },
      { letter: "C", text: "fails to define what constitutes catastrophic climate change" },
      { letter: "D", text: "assumes that renewable energy investment would prevent climate change" },
      { letter: "E", text: "ignores the economic costs of renewable energy investment" },
    ],
    correctAnswer: "A",
    explanation: "The argument presents only two options: invest in renewable energy or face catastrophe. This is a false dichotomy because other options exist, such as nuclear energy, improved efficiency, carbon capture technology, or combinations of approaches. The argument artificially limits the choices.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-040",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The painting attributed to Vermeer is actually a forgery. Chemical analysis shows that one of the pigments used was not available until the twentieth century—over two hundred years after Vermeer's death.`,
    questionStem: "Which one of the following, if true, most strengthens the art historian's argument?",
    answerChoices: [
      { letter: "A", text: "The painting was purchased from a dealer known to have sold other forgeries" },
      { letter: "B", text: "The pigment in question appears in the original paint layer, not in later restorations" },
      { letter: "C", text: "Vermeer's authentic works are extremely valuable" },
      { letter: "D", text: "Some art historians initially believed the painting was genuine" },
      { letter: "E", text: "The forger who may have created the painting was skilled at imitating Dutch masters" },
    ],
    correctAnswer: "B",
    explanation: "If the modern pigment is in the original paint layer rather than later restorations, this eliminates the possibility that the anachronistic pigment was added during conservation efforts. The modern pigment must have been used when the painting was created, confirming it's a forgery.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-041",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Manager: Our team's productivity declined after we implemented the open office plan. Clearly, the lack of private spaces makes it difficult for employees to concentrate. We should return to private offices.`,
    questionStem: "Which one of the following, if true, most weakens the manager's argument?",
    answerChoices: [
      { letter: "A", text: "Some employees prefer the open office environment" },
      { letter: "B", text: "The productivity decline coincided with the departure of several high-performing team members" },
      { letter: "C", text: "Other companies have successfully implemented open office plans" },
      { letter: "D", text: "Private offices cost more than open workspaces" },
      { letter: "E", text: "The open office plan was implemented gradually over several months" },
    ],
    correctAnswer: "B",
    explanation: "If high-performing team members left around the same time the open office was implemented, their departure rather than the office layout might explain the productivity decline. This provides an alternative explanation that weakens the causal claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-042",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Autonomous vehicles should be programmed to minimize total harm in accident scenarios. If an accident is unavoidable, the vehicle should take the action that results in the fewest injuries, even if that means sacrificing the passenger.`,
    questionStem: "The ethicist's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Passengers who purchase autonomous vehicles accept this risk" },
      { letter: "B", text: "The total number of injuries is the appropriate measure for evaluating ethical outcomes" },
      { letter: "C", text: "Autonomous vehicles will be involved in more accidents than human-driven vehicles" },
      { letter: "D", text: "Vehicle manufacturers can accurately predict all accident scenarios" },
      { letter: "E", text: "Human drivers do not consider ethical implications during accidents" },
    ],
    correctAnswer: "B",
    explanation: "The ethicist's conclusion follows only if minimizing total injuries is the correct ethical framework. Other ethical frameworks might prioritize the passenger's life (who chose the vehicle) or argue it's wrong to use anyone as a means to save others. The argument assumes utilitarian ethics is correct.",
    difficulty: "hard",
  },
  {
    id: "lr-bank43-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Lawyer A: The defendant's confession should be admitted as evidence. While police questioning was lengthy, the defendant was read her rights and chose to speak without an attorney present.

Lawyer B: The confession must be excluded. The fifteen-hour interrogation without breaks created coercive conditions that rendered any waiver of rights involuntary.`,
    questionStem: "The point at issue between Lawyer A and Lawyer B is whether",
    answerChoices: [
      { letter: "A", text: "the defendant was read her rights" },
      { letter: "B", text: "the interrogation lasted fifteen hours" },
      { letter: "C", text: "the conditions of the interrogation made the confession involuntary" },
      { letter: "D", text: "confessions are generally reliable evidence" },
      { letter: "E", text: "defendants should always have an attorney present during questioning" },
    ],
    correctAnswer: "C",
    explanation: "Both lawyers agree on the facts: the defendant was read her rights and questioned for a long time without an attorney. They disagree about whether these conditions made her waiver of rights and subsequent confession involuntary.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-044",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some medications have serious side effects. All medications with serious side effects require a prescription. Therefore, some medications that require a prescription have serious side effects.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some athletes are vegetarians. All vegetarians eat vegetables. Therefore, some athletes eat vegetables." },
      { letter: "B", text: "All cars need fuel. Some vehicles are cars. Therefore, some vehicles need fuel." },
      { letter: "C", text: "Some professors are researchers. All researchers publish papers. Therefore, some professors publish papers." },
      { letter: "D", text: "No reptiles are mammals. Some pets are mammals. Therefore, no pets are reptiles." },
      { letter: "E", text: "All dogs are loyal. Rover is loyal. Therefore, Rover is a dog." },
    ],
    correctAnswer: "C",
    explanation: "Both arguments follow this pattern: Some A are B. All B are C. Therefore, some C are B (or equivalently, some A are C). The original: Some meds have side effects, all those require prescriptions, so some prescription meds have side effects. Answer C: Some professors are researchers, all researchers publish, so some professors publish.",
    difficulty: "hard",
  },
  {
    id: "lr-bank43-045",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The average income in our town has increased by 10% over the past five years. Therefore, every family in our town is financially better off now than they were five years ago.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to account for inflation" },
      { letter: "B", text: "assumes that what is true of a group as a whole is true of each member of that group" },
      { letter: "C", text: "relies on data that may be inaccurate" },
      { letter: "D", text: "ignores other factors that affect financial well-being" },
      { letter: "E", text: "draws a conclusion about the future based on past trends" },
    ],
    correctAnswer: "B",
    explanation: "This is the fallacy of division—assuming that what is true of the whole (average income increased) must be true of each part (every family is better off). The average could increase while some families' incomes decreased, if high earners' incomes increased significantly.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-046",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Social media use correlates with increased rates of anxiety and depression among teenagers. While some argue this is because anxious teens seek social connection online, I believe the causation runs the other way: social media use triggers anxiety by encouraging constant comparison with others' curated highlight reels.`,
    questionStem: "Which one of the following, if true, most strengthens the sociologist's argument?",
    answerChoices: [
      { letter: "A", text: "Teenagers who limit their social media use report lower levels of anxiety" },
      { letter: "B", text: "Adults who use social media also experience anxiety" },
      { letter: "C", text: "Teenagers who were not anxious before using social media developed anxiety after sustained use" },
      { letter: "D", text: "Social media companies design their platforms to be addictive" },
      { letter: "E", text: "Some teenagers use social media without experiencing any negative effects" },
    ],
    correctAnswer: "C",
    explanation: "If previously non-anxious teenagers developed anxiety after using social media, this supports the claim that social media causes anxiety rather than anxious teens seeking out social media. The temporal sequence (use preceded anxiety) supports the sociologist's direction of causation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-047",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Free trade agreements benefit all participating countries. When tariffs are removed, countries specialize in producing goods where they have a comparative advantage, leading to greater overall efficiency and wealth creation.`,
    questionStem: "Which one of the following, if true, most weakens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Some industries in participating countries experience job losses due to increased competition" },
      { letter: "B", text: "The benefits of free trade are not equally distributed among all countries or groups within countries" },
      { letter: "C", text: "Free trade agreements typically take years to negotiate" },
      { letter: "D", text: "Some countries choose not to participate in free trade agreements" },
      { letter: "E", text: "Comparative advantage can shift over time as economies develop" },
    ],
    correctAnswer: "B",
    explanation: "The economist claims free trade benefits all participating countries. If benefits are unequally distributed—with some countries or groups worse off—this weakens the claim that all benefit. Some parties might actually be harmed even if aggregate efficiency increases.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-048",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The library should extend its evening hours because many working adults cannot visit during current hours. Extended hours would make the library accessible to this underserved population.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Working adults would use the library if it were open during evening hours" },
      { letter: "B", text: "The library currently has no evening hours" },
      { letter: "C", text: "All working adults have the same schedule" },
      { letter: "D", text: "The library is the only source of books for working adults" },
      { letter: "E", text: "Extended hours would not significantly increase operating costs" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that if evening hours were extended, working adults would actually use the library. If they wouldn't come even with extended hours (perhaps due to fatigue, other commitments, or preference for digital resources), extending hours wouldn't achieve the stated goal.",
    difficulty: "easy",
  },
  {
    id: "lr-bank43-049",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: Our study found that 90% of people with heart disease eat red meat regularly. This proves that red meat consumption causes heart disease.`,
    questionStem: "The scientist's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "ignores the possibility that 90% of people without heart disease also eat red meat regularly" },
      { letter: "B", text: "fails to consider that some red meat may be healthier than others" },
      { letter: "C", text: "relies on self-reported dietary information" },
      { letter: "D", text: "does not account for genetic factors in heart disease" },
      { letter: "E", text: "assumes that diet is the only factor affecting heart health" },
    ],
    correctAnswer: "A",
    explanation: "The argument ignores the base rate. If 90% of people with heart disease eat red meat, but 90% of people without heart disease also eat red meat, then red meat consumption doesn't distinguish between the groups and likely isn't causing the disease.",
    difficulty: "medium",
  },
  {
    id: "lr-bank43-050",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Educational researcher: Students learn better when they take handwritten notes rather than typing on laptops. Handwriting is slower, which forces students to process information and summarize key points rather than transcribing lectures verbatim.`,
    questionStem: "Which one of the following, if true, most strengthens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Students who type notes often report that they prefer this method" },
      { letter: "B", text: "Tests show that students who handwrite notes perform better on conceptual questions than those who type notes" },
      { letter: "C", text: "Many schools have adopted policies allowing laptop use in classrooms" },
      { letter: "D", text: "Handwriting speed varies significantly among students" },
      { letter: "E", text: "Some students type notes and then rewrite them by hand later" },
    ],
    correctAnswer: "B",
    explanation: "If students who handwrite notes perform better on conceptual questions, this directly supports the claim that handwriting leads to better learning. Conceptual questions test deep understanding, which the researcher claims is enhanced by the processing required for handwriting.",
    difficulty: "easy",
  },
];
