// Logical Reasoning Questions Bank - Set 18
// High-quality LSAT-style questions covering all question types

import { Question } from "../lsat-types";

export const lrQuestionsSet18: Question[] = [
  {
    id: "lr-bank18-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The city council claims that the new downtown parking garage will reduce traffic congestion because it will encourage people to drive downtown rather than avoiding it due to lack of parking. However, traffic studies from other cities show that adding parking capacity often increases the number of cars driving into an area. The council's plan is therefore certain to make congestion worse, not better.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that some people may use public transit instead of driving" },
      { letter: "B", text: "treats evidence that a result is likely as proof that the result is certain" },
      { letter: "C", text: "assumes without justification that all cities have similar traffic patterns" },
      { letter: "D", text: "ignores the possibility that the parking garage might have other benefits" },
      { letter: "E", text: "relies on the opinions of traffic experts without citing specific data" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'often increases' (evidence of likelihood) to 'certain to make congestion worse' (a claim of certainty). This overstates the strength of the evidence. The studies show a tendency, not an invariable result, so concluding certainty is unwarranted.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Pharmaceutical researchers have discovered that a compound found in a rare Amazonian plant shows promise in treating antibiotic-resistant infections. The compound appears to disrupt bacterial cell walls through a mechanism unlike any existing antibiotic. Researchers believe this compound could form the basis for a new class of antibiotics that bacteria would be unable to resist.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "The plant is found only in remote areas that are difficult to access" },
      { letter: "B", text: "Bacteria develop resistance primarily by adapting to familiar chemical mechanisms" },
      { letter: "C", text: "Several other compounds from Amazonian plants have shown antimicrobial properties" },
      { letter: "D", text: "Current antibiotics are becoming less effective at an alarming rate" },
      { letter: "E", text: "The pharmaceutical company has experience developing new drug classes" },
    ],
    correctAnswer: "B",
    explanation: "If bacteria develop resistance by adapting to familiar mechanisms, and this compound uses an unfamiliar mechanism, then bacteria would have difficulty developing resistance to it. This directly supports the claim that bacteria would be 'unable to resist' this new class of antibiotics.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A study found that students who took handwritten notes during lectures performed better on subsequent exams than students who typed their notes on laptops. The researchers concluded that handwriting notes leads to deeper cognitive processing because it forces students to summarize and paraphrase rather than transcribe verbatim.`,
    questionStem: "Which one of the following, if true, most weakens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Some students who typed notes performed as well as the top handwriting group" },
      { letter: "B", text: "Students who typed notes spent more time reviewing them before the exam" },
      { letter: "C", text: "Students who preferred handwriting were already higher-performing students before the study began" },
      { letter: "D", text: "The exams tested factual recall rather than conceptual understanding" },
      { letter: "E", text: "Typing notes allows students to capture more information from lectures" },
    ],
    correctAnswer: "C",
    explanation: "If students who chose handwriting were already higher-performing, then the better exam performance might reflect pre-existing differences in ability rather than the effect of handwriting on cognitive processing. This is a classic selection bias that undermines the causal conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The governor argues that the state should not fund a high-speed rail project because private investors have declined to invest in it. If the project were financially viable, private investors would have provided funding. Therefore, public investment would simply waste taxpayer money on a project doomed to fail.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Private investors have access to accurate information about the project's viability" },
      { letter: "B", text: "The state has previously funded transportation projects that failed" },
      { letter: "C", text: "Financial viability for private investors is the same as financial viability for public investment" },
      { letter: "D", text: "High-speed rail projects in other states have been successful" },
      { letter: "E", text: "Private investors always make correct decisions about investments" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that what is not viable for private investors is also not viable for public investment. But public investments may have different criteria for success (long-term benefits, social returns, reduced externalities) that private investors would not consider. If this assumption fails, the argument collapses.",
    difficulty: "hard",
  },
  {
    id: "lr-bank18-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Philosophy departments have experienced declining enrollment over the past decade. Some administrators attribute this to students' preference for vocational majors that lead directly to employment. However, studies show that philosophy graduates have among the highest rates of graduate school acceptance and competitive scores on standardized tests. The perception that philosophy is impractical is therefore mistaken.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Philosophy departments have experienced declining enrollment" },
      { letter: "B", text: "Students prefer vocational majors that lead directly to employment" },
      { letter: "C", text: "Philosophy graduates perform well on standardized tests" },
      { letter: "D", text: "The view that philosophy is an impractical major is incorrect" },
      { letter: "E", text: "Administrators should do more to promote philosophy departments" },
    ],
    correctAnswer: "D",
    explanation: "The conclusion indicator 'therefore' signals that the main point is that the perception of impracticality is mistaken. The declining enrollment, administrator explanations, and graduate success data all serve as background or support for this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The museum director claims that the new exhibit will attract younger visitors because it features interactive digital displays. But the last exhibit with digital technology failed to increase youth attendance. The director's prediction ignores relevant evidence and should not be trusted.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "questioning the director's qualifications to make predictions about attendance" },
      { letter: "B", text: "citing a past case to cast doubt on the director's prediction" },
      { letter: "C", text: "demonstrating that digital displays are not appealing to young people" },
      { letter: "D", text: "arguing that museum attendance is declining across all demographics" },
      { letter: "E", text: "suggesting an alternative explanation for the anticipated attendance increase" },
    ],
    correctAnswer: "B",
    explanation: "The critic uses the failure of a previous digital exhibit to attract youth as evidence that the current prediction is unreliable. This is an argument by precedent, using a past case to undermine a current prediction.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `All effective teachers are able to engage students in active learning. Professor Martinez's students are actively engaged during class. Therefore, Professor Martinez must be an effective teacher.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that student engagement is the only measure of teaching effectiveness" },
      { letter: "B", text: "fails to define what constitutes active learning" },
      { letter: "C", text: "confuses a necessary condition for being an effective teacher with a sufficient condition" },
      { letter: "D", text: "relies on a sample that may not be representative" },
      { letter: "E", text: "ignores the possibility that some effective teachers have disengaged students" },
    ],
    correctAnswer: "C",
    explanation: "The argument states that engagement is necessary for effective teaching (all effective teachers engage students), but then treats engagement as sufficient for effective teaching (engaged students means effective teacher). This is a classic confusion of necessary and sufficient conditions.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have discovered remarkably similar pottery designs at sites separated by over 500 miles in prehistoric North America. Some scholars suggest this indicates extensive trade networks, but lead researcher Dr. Chen believes the similarity results from a shared ancestral culture that spread as populations migrated, not from trade between distant communities.`,
    questionStem: "Which one of the following, if true, most strengthens Dr. Chen's hypothesis?",
    answerChoices: [
      { letter: "A", text: "The pottery at both sites was made from locally available clay" },
      { letter: "B", text: "Other artifacts at the sites, such as tools and jewelry, show no similarities" },
      { letter: "C", text: "Genetic analysis shows the populations at both sites share common ancestors" },
      { letter: "D", text: "Pottery design styles often spread through imitation and cultural exchange" },
      { letter: "E", text: "The sites date to approximately the same time period" },
    ],
    correctAnswer: "C",
    explanation: "Genetic evidence of shared ancestry directly supports the hypothesis that the populations descended from a common ancestral culture. This would explain the pottery similarity through shared heritage rather than trade.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-009",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Samira: Autonomous vehicles will dramatically reduce traffic fatalities because human error causes over 90% of accidents. Removing human drivers removes the primary cause of fatal crashes.

Marcus: That statistic is misleading. Most of those human errors are minor mistakes that other human drivers easily accommodate. Autonomous vehicles may not respond appropriately to the unexpected behaviors of human drivers during the transition period, potentially causing new types of accidents.`,
    questionStem: "Samira and Marcus disagree about whether",
    answerChoices: [
      { letter: "A", text: "human error is the primary cause of traffic fatalities" },
      { letter: "B", text: "autonomous vehicles will significantly reduce fatal accidents" },
      { letter: "C", text: "the transition to autonomous vehicles will eventually be complete" },
      { letter: "D", text: "autonomous vehicles can detect other vehicles on the road" },
      { letter: "E", text: "human drivers make minor errors frequently" },
    ],
    correctAnswer: "B",
    explanation: "Samira claims autonomous vehicles will 'dramatically reduce traffic fatalities,' while Marcus argues they 'may cause new types of accidents' during the transition period. Both express clear positions on whether fatalities will be reduced, and these positions conflict.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A corporation's board argues that executive compensation should be tied to stock price because it aligns executive interests with shareholder interests. When executives benefit from rising stock prices, they are motivated to make decisions that increase company value, benefiting all shareholders equally.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some executives have voluntarily reduced their own compensation packages" },
      { letter: "B", text: "Stock prices can be temporarily inflated through accounting practices that harm long-term value" },
      { letter: "C", text: "Many companies have adopted stock-based executive compensation" },
      { letter: "D", text: "Shareholder interests include concerns beyond stock price, such as environmental impact" },
      { letter: "E", text: "Executive compensation represents a small percentage of total company expenses" },
    ],
    correctAnswer: "B",
    explanation: "If executives can inflate stock prices through harmful short-term practices, then stock-based compensation could motivate decisions that harm long-term company value. This undermines the claim that such compensation aligns executive and shareholder interests.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-011",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The mayor's proposed budget includes significant funding for public art installations. Critics argue that during an economic downturn, the city cannot afford such expenditures. But these critics simply do not appreciate the value of art in public spaces. If they understood how art enriches community life, they would support the proposal.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that the economic downturn will be short-lived" },
      { letter: "B", text: "dismisses the critics' position by attacking their aesthetic sensibilities rather than their reasoning" },
      { letter: "C", text: "fails to consider alternative uses for the proposed funding" },
      { letter: "D", text: "implies that all community members would benefit equally from public art" },
      { letter: "E", text: "exaggerates the costs of the public art installations" },
    ],
    correctAnswer: "B",
    explanation: "The argument attacks the critics by claiming they don't appreciate art, rather than addressing their actual concern about affordability during an economic downturn. This is an ad hominem fallacy that dismisses the argument by attacking the arguers' tastes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-012",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The preservation society argues that the historic theater should be saved from demolition because it represents a unique example of Art Deco architecture in our region. The developer counters that the building can be replaced with a modern facility that better serves the community. But architectural heritage, once lost, cannot be recreated. The theater must be preserved.`,
    questionStem: "The preservation society's argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Art Deco architecture is the most important architectural style in the region" },
      { letter: "B", text: "The developer's proposed facility would have no architectural merit" },
      { letter: "C", text: "The irreplaceable nature of architectural heritage is a sufficient reason to preserve it" },
      { letter: "D", text: "Other Art Deco buildings in the region have already been demolished" },
      { letter: "E", text: "The community would use the historic theater more than a modern facility" },
    ],
    correctAnswer: "C",
    explanation: "The argument moves from 'heritage cannot be recreated' to 'must be preserved.' This requires assuming that being irreplaceable is sufficient justification for preservation. Without this assumption, the fact that something cannot be recreated wouldn't necessarily mean it must be saved.",
    difficulty: "hard",
  },
  {
    id: "lr-bank18-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Recent studies show that children who participate in team sports have better academic outcomes than those who do not. Educators therefore recommend increasing opportunities for team sports in schools as a way to improve student achievement.`,
    questionStem: "Which one of the following, if true, most strengthens the educators' recommendation?",
    answerChoices: [
      { letter: "A", text: "Schools with extensive sports programs have higher graduation rates" },
      { letter: "B", text: "Participation in team sports teaches collaboration skills that transfer to classroom learning" },
      { letter: "C", text: "Students who play team sports are often required to maintain minimum grades" },
      { letter: "D", text: "Many successful professionals participated in team sports during their youth" },
      { letter: "E", text: "Team sports provide physical exercise that improves overall health" },
    ],
    correctAnswer: "B",
    explanation: "This answer provides a causal mechanism explaining how sports participation could improve academic outcomes. If sports develop transferable skills, then increasing sports opportunities would genuinely lead to academic improvement, supporting the recommendation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-014",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some Renaissance artists worked primarily in fresco. All artists who worked primarily in fresco had extensive knowledge of architectural structures. Therefore, some Renaissance artists had extensive knowledge of architectural structures.`,
    questionStem: "Which one of the following arguments is most similar in its pattern of reasoning to the argument above?",
    answerChoices: [
      { letter: "A", text: "Some professional musicians play string instruments. All string instruments require regular tuning. Therefore, some professional musicians must regularly tune their instruments." },
      { letter: "B", text: "All doctors have medical degrees. Some researchers are doctors. Therefore, all researchers have medical degrees." },
      { letter: "C", text: "Some politicians are lawyers. Some lawyers are excellent public speakers. Therefore, some politicians are excellent public speakers." },
      { letter: "D", text: "No reptiles are mammals. All mammals are warm-blooded. Therefore, no reptiles are warm-blooded." },
      { letter: "E", text: "Every marathon runner trains regularly. Chen is a marathon runner. Therefore, Chen trains regularly." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments follow the pattern: Some A are B; All B have property C; Therefore, some A have property C. This is a valid syllogistic form. Answer A matches this structure with musicians, string instruments, and tuning.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A nutritionist argues that organic produce is not worth the higher price because laboratory tests show that organic and conventional produce have virtually identical nutritional content. Consumers who pay more for organic produce are therefore wasting their money if nutrition is their primary concern.`,
    questionStem: "Which one of the following, if true, most seriously weakens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Many consumers prefer the taste of organic produce" },
      { letter: "B", text: "Organic farming methods are better for the environment" },
      { letter: "C", text: "Organic produce often contains significantly lower levels of pesticide residues" },
      { letter: "D", text: "Some conventional produce is grown using organic methods but not certified" },
      { letter: "E", text: "The price difference between organic and conventional produce is decreasing" },
    ],
    correctAnswer: "C",
    explanation: "The nutritionist limits the comparison to 'nutritional content,' but if organic produce has fewer pesticides, consumers may have legitimate health-related reasons to prefer it beyond nutrition. This shows the argument's scope is too narrow to support its conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-016",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The senator claims that the proposed immigration reform will harm American workers. But the senator has accepted campaign contributions from groups that oppose immigration. Clearly, the senator's position on this issue is motivated by political self-interest rather than genuine concern for workers.`,
    questionStem: "The argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that the senator might have other reasons for opposing the reform" },
      { letter: "B", text: "attacks the senator's motives rather than addressing the substance of the claim" },
      { letter: "C", text: "assumes that all campaign contributions influence politicians' positions" },
      { letter: "D", text: "ignores evidence that the reform would benefit American workers" },
      { letter: "E", text: "draws a conclusion about immigration policy from evidence about campaign finance" },
    ],
    correctAnswer: "B",
    explanation: "The argument attempts to discredit the senator's claim by pointing to allegedly self-interested motives. But even if the senator is motivated by political calculations, the claim about harm to workers could still be true. This is an ad hominem fallacy.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-017",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Countries that adopt strict environmental regulations often see their most polluting industries relocate to countries with weaker regulations. This "pollution haven" effect means that strict regulations in one country may simply shift pollution elsewhere rather than reducing it globally. Therefore, unilateral environmental regulations are ineffective at addressing global environmental problems.`,
    questionStem: "The economist's argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "All polluting industries will relocate if regulations become stricter" },
      { letter: "B", text: "Countries with strict regulations have no other environmental benefits" },
      { letter: "C", text: "The pollution haven effect is not offset by other factors that reduce global pollution" },
      { letter: "D", text: "International coordination on environmental regulations is impossible" },
      { letter: "E", text: "Economic growth is incompatible with environmental protection" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that unilateral regulations are ineffective because they shift pollution. But if other effects of strict regulations (technological innovation, demonstration effects, market changes) offset this shift, regulations could still reduce global pollution. The argument assumes these offsetting factors don't exist or are insufficient.",
    difficulty: "hard",
  },
  {
    id: "lr-bank18-018",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The ancient Maya civilization collapsed around 900 CE. Some historians attribute this to prolonged drought, others to warfare, and still others to environmental degradation from deforestation. Each of these explanations has supporting evidence, but none fully accounts for the timing and geographic pattern of the collapse. The most likely explanation combines elements of all three factors, with each contributing to a cascading crisis.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "rejecting several proposed explanations in favor of an entirely new hypothesis" },
      { letter: "B", text: "demonstrating that one explanation is superior to competing alternatives" },
      { letter: "C", text: "synthesizing elements of multiple explanations into a more comprehensive account" },
      { letter: "D", text: "arguing that the collapse cannot be explained by any available evidence" },
      { letter: "E", text: "questioning the reliability of the historical record regarding the collapse" },
    ],
    correctAnswer: "C",
    explanation: "The argument acknowledges that multiple explanations have merit but each is incomplete. It then proposes that combining all three provides a more adequate explanation. This is a synthesis approach that integrates rather than rejects the individual factors.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-019",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologists find that people who regularly practice gratitude exercises report higher levels of happiness than those who do not. However, skeptics suggest that people who are already happier may simply be more inclined to engage in gratitude practices. Researchers counter that gratitude exercises genuinely increase happiness.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' position?",
    answerChoices: [
      { letter: "A", text: "Gratitude exercises take only a few minutes per day to complete" },
      { letter: "B", text: "In controlled experiments, participants randomly assigned to gratitude exercises showed happiness increases" },
      { letter: "C", text: "Many cultures have traditions that emphasize gratitude" },
      { letter: "D", text: "Happiness levels tend to remain stable over a person's lifetime" },
      { letter: "E", text: "People who practice gratitude also tend to exercise more regularly" },
    ],
    correctAnswer: "B",
    explanation: "Random assignment eliminates the selection bias that skeptics raised. If people assigned to gratitude exercises (regardless of initial happiness) show increased happiness, this demonstrates that gratitude causes the increase rather than happy people simply being more likely to practice gratitude.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-020",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Last year, our company's sales team adopted a new customer relationship management software. This year, sales increased by 15%. The new software must be responsible for the improved sales performance.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "fails to consider whether the sales team received adequate training on the new software" },
      { letter: "B", text: "overlooks the possibility that factors other than the software caused the sales increase" },
      { letter: "C", text: "does not specify the exact percentage increase that would indicate software effectiveness" },
      { letter: "D", text: "assumes that all members of the sales team used the software equally" },
      { letter: "E", text: "ignores the costs of implementing the new software" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that because the software adoption preceded the sales increase, the software caused the increase. But many other factors could explain improved sales: economic conditions, new products, competitor problems, or marketing campaigns. This is a post hoc ergo propter hoc fallacy.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Health officials recommend that adults sleep seven to nine hours per night for optimal health. A recent study found that adults who sleep less than six hours have higher rates of cardiovascular disease. This proves that insufficient sleep causes heart problems.`,
    questionStem: "Which one of the following, if true, most weakens the argument's conclusion?",
    answerChoices: [
      { letter: "A", text: "The study did not include adults who sleep more than nine hours per night" },
      { letter: "B", text: "Many adults find it difficult to sleep seven hours due to work schedules" },
      { letter: "C", text: "People with undiagnosed cardiovascular conditions often experience disrupted sleep" },
      { letter: "D", text: "The study was conducted over a period of only two years" },
      { letter: "E", text: "Some adults function well on less than six hours of sleep" },
    ],
    correctAnswer: "C",
    explanation: "If cardiovascular problems cause sleep disruption, the causal arrow may run in the opposite direction from what the argument claims. People might sleep less because they have heart problems, rather than developing heart problems because they sleep less. This is reverse causation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-022",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Wildlife biologist: The reintroduction of wolves to Yellowstone has led to a remarkable recovery of the ecosystem. Wolves control elk populations, which allows vegetation to recover along streams. This vegetation stabilizes riverbanks and provides habitat for numerous species. We should therefore reintroduce wolves to other national parks to achieve similar ecological benefits.`,
    questionStem: "The biologist's argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Wolves are the most effective predators for controlling elk populations" },
      { letter: "B", text: "The ecological conditions in other parks are sufficiently similar to those in Yellowstone" },
      { letter: "C", text: "Public support for wolf reintroduction exists in all national parks" },
      { letter: "D", text: "Yellowstone's ecosystem was degraded before wolf reintroduction" },
      { letter: "E", text: "No other predators can control elk populations effectively" },
    ],
    correctAnswer: "B",
    explanation: "The argument generalizes from Yellowstone's success to recommend wolf reintroduction elsewhere. This requires assuming that other parks share the relevant ecological characteristics that made reintroduction successful in Yellowstone. Without this assumption, the Yellowstone example might not be applicable elsewhere.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-023",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Lee: The university should require all students to take at least two courses in ethics. In an increasingly complex world, the ability to reason about moral questions is essential for responsible citizenship.

Professor Wang: I agree that ethics education is valuable, but a requirement would be counterproductive. Students forced to take ethics courses often become resentful and resistant, undermining the very values we hope to instill. Ethics education works best when students choose it freely.`,
    questionStem: "The professors disagree over whether",
    answerChoices: [
      { letter: "A", text: "the ability to reason about moral questions is important" },
      { letter: "B", text: "making ethics courses mandatory would effectively promote ethical reasoning" },
      { letter: "C", text: "some students would benefit from studying ethics" },
      { letter: "D", text: "universities have any role in developing students' ethical capacities" },
      { letter: "E", text: "students currently take enough ethics courses" },
    ],
    correctAnswer: "B",
    explanation: "Both professors value ethics education, but they disagree about whether requiring courses would be effective. Lee thinks requirements would help; Wang thinks they would be counterproductive. Their dispute is about the efficacy of mandates, not the value of ethics.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-024",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Editorial: The proposed factory will either create 500 jobs and boost the local economy or pollute the river and harm public health. Since the community desperately needs jobs, we must accept the factory despite the environmental risks.`,
    questionStem: "The reasoning in the editorial is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider whether 500 jobs is sufficient to significantly boost the economy" },
      { letter: "B", text: "assumes that creating jobs is more important than protecting public health" },
      { letter: "C", text: "presents a false choice by assuming the factory cannot both create jobs and protect the environment" },
      { letter: "D", text: "ignores the possibility that the factory might not create as many jobs as projected" },
      { letter: "E", text: "does not specify the types of jobs that would be created" },
    ],
    correctAnswer: "C",
    explanation: "The editorial presents only two options: jobs with pollution or no factory at all. But the factory might be built with pollution controls that provide jobs while protecting the environment. This false dichotomy ignores possible compromises.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-025",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historians have long debated why the Roman Empire fell. A new analysis suggests that lead poisoning from pipes and cookware may have contributed to declining Roman birth rates and cognitive function among the elite, weakening the empire's leadership over generations.`,
    questionStem: "Which one of the following, if true, most strengthens this analysis?",
    answerChoices: [
      { letter: "A", text: "Lead pipes were commonly used throughout the Roman Empire" },
      { letter: "B", text: "Modern studies confirm that lead exposure reduces fertility and cognitive function" },
      { letter: "C", text: "Analysis of Roman skeletons shows elevated lead levels, particularly among the wealthy" },
      { letter: "D", text: "The fall of Rome occurred gradually over several centuries" },
      { letter: "E", text: "Other ancient civilizations also used lead in various applications" },
    ],
    correctAnswer: "C",
    explanation: "Direct physical evidence that Romans, especially the elite, had high lead levels provides concrete support for the hypothesis. Combined with known effects of lead, this evidence connects the cause (lead exposure) to the population that allegedly suffered the effects (leadership class).",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-026",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All licensed electricians in this state must complete 8,000 hours of apprenticeship training. Some licensed electricians also hold additional certifications in specialized areas such as industrial or renewable energy systems. Workers who hold such specialized certifications earn, on average, 25% more than those with standard licenses alone.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All workers with specialized certifications are licensed electricians" },
      { letter: "B", text: "Some workers who completed 8,000 hours of apprenticeship training earn more than others who completed the same training" },
      { letter: "C", text: "Specialized certifications require less training than standard licenses" },
      { letter: "D", text: "Most licensed electricians eventually obtain specialized certifications" },
      { letter: "E", text: "The 8,000-hour apprenticeship requirement is excessive" },
    ],
    correctAnswer: "B",
    explanation: "Since some licensed electricians have specialized certifications and earn 25% more, and all licensed electricians completed 8,000 hours of training, it follows that some people who completed the required training earn more than other people who completed the same training.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-027",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city's traffic department claims that installing red-light cameras at major intersections has reduced accidents. Statistics show that the number of right-angle collisions at camera-equipped intersections has decreased by 30% since the cameras were installed.`,
    questionStem: "Which one of the following, if true, most seriously weakens the claim that red-light cameras have reduced accidents?",
    answerChoices: [
      { letter: "A", text: "Right-angle collisions are typically more severe than other types of accidents" },
      { letter: "B", text: "The cameras generate significant revenue from traffic fines" },
      { letter: "C", text: "Rear-end collisions at camera-equipped intersections have increased by 40%" },
      { letter: "D", text: "Some drivers are unaware that the intersections have cameras" },
      { letter: "E", text: "Traffic volume at the intersections has remained constant" },
    ],
    correctAnswer: "C",
    explanation: "If one type of accident (right-angle) decreased while another (rear-end) increased even more, the overall accident rate might have risen, not fallen. Drivers slamming on brakes to avoid red-light tickets could cause more rear-end collisions than the right-angle collisions prevented.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-028",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some argue that genetically modified crops are dangerous because they are 'unnatural.' But virtually all crops consumed today have been dramatically altered from their wild ancestors through centuries of selective breeding. If artificiality were genuinely dangerous, we would have abandoned agriculture long ago. The unnaturalness objection therefore proves too much.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "demonstrating that genetically modified crops are nutritionally equivalent to conventional crops" },
      { letter: "B", text: "showing that consistent application of the opponent's principle leads to an unacceptable conclusion" },
      { letter: "C", text: "arguing that selective breeding and genetic modification are identical processes" },
      { letter: "D", text: "appealing to the long history of agricultural practices" },
      { letter: "E", text: "questioning the scientific credentials of those who oppose genetic modification" },
    ],
    correctAnswer: "B",
    explanation: "The argument shows that if 'unnatural' were a valid reason to reject GMOs, we would also have to reject all domesticated crops, which would mean abandoning agriculture. This reductio ad absurdum demonstrates that the principle, applied consistently, leads to absurd results.",
    difficulty: "hard",
  },
  {
    id: "lr-bank18-029",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Local business owner: The minimum wage should not be raised because doing so would force me to either reduce staff or raise prices. If I reduce staff, workers lose their jobs. If I raise prices, customers go elsewhere and my business fails. Either way, workers are harmed. Therefore, raising the minimum wage would harm the very workers it is intended to help.`,
    questionStem: "The business owner's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that other businesses would face similar price pressures" },
      { letter: "B", text: "assumes that reduced working hours would necessarily harm workers" },
      { letter: "C", text: "generalizes from the effects on one business to conclusions about all workers" },
      { letter: "D", text: "ignores the possibility that higher wages might increase consumer spending" },
      { letter: "E", text: "does not acknowledge that some businesses can absorb higher labor costs" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that what harms workers at this particular business harms all workers affected by the minimum wage. But even if some workers lose jobs, other workers receive higher wages. The conclusion about 'workers' in general doesn't follow from evidence about workers at one business.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Film critic: The Academy Awards consistently overlook science fiction films, awarding best picture almost exclusively to dramas and biographical films. This reveals a bias against imaginative cinema. Science fiction films that explore profound themes about humanity's future deserve recognition alongside films about past events.`,
    questionStem: "The critic's argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Science fiction films are more imaginative than dramas and biographical films" },
      { letter: "B", text: "Profound thematic content is a relevant criterion for best picture recognition" },
      { letter: "C", text: "The Academy voters are unfamiliar with science fiction as a genre" },
      { letter: "D", text: "Films about the future are inherently more valuable than films about the past" },
      { letter: "E", text: "All science fiction films explore profound themes about humanity" },
    ],
    correctAnswer: "B",
    explanation: "The critic argues that science fiction films exploring profound themes 'deserve recognition.' This assumes that profound thematic content is relevant to what the Academy should recognize. If the Academy properly judged on other criteria entirely, the argument would fail.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-031",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Linguist: Children acquire their first language with remarkable speed and accuracy despite receiving imperfect input filled with errors, false starts, and incomplete sentences. This suggests that humans have an innate capacity for language acquisition that goes beyond simple imitation of what they hear.`,
    questionStem: "Which one of the following, if true, most strengthens the linguist's argument?",
    answerChoices: [
      { letter: "A", text: "Children from different cultures acquire language at similar rates" },
      { letter: "B", text: "Children regularly produce grammatical sentences they have never heard" },
      { letter: "C", text: "Adults find it more difficult to learn new languages than children do" },
      { letter: "D", text: "Children who are read to frequently develop larger vocabularies" },
      { letter: "E", text: "Some languages are more complex grammatically than others" },
    ],
    correctAnswer: "B",
    explanation: "If children produce grammatical sentences they've never heard, they cannot be simply imitating input. This provides direct evidence that language acquisition involves something beyond copying heard speech, supporting the claim of innate capacity.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-032",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No responsible journalist would publish unverified information. This article publishes unverified information. Therefore, the author of this article is not a responsible journalist.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All successful businesses provide good customer service. This business provides good customer service. Therefore, this business is successful." },
      { letter: "B", text: "No licensed contractor would ignore building codes. This contractor ignored building codes. Therefore, this contractor is not licensed." },
      { letter: "C", text: "Some teachers are impatient with slow learners. Johnson is impatient with slow learners. Therefore, Johnson might be a teacher." },
      { letter: "D", text: "Every trained chef knows proper knife techniques. Maria is a trained chef. Therefore, Maria knows proper knife techniques." },
      { letter: "E", text: "Most experienced drivers have never been in an accident. Kim has never been in an accident. Therefore, Kim is probably an experienced driver." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow modus tollens with a universal negative: No X would do Y; This person did Y; Therefore, this person is not X. Answer B matches this valid logical pattern exactly.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-033",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A technology company argues that remote work increases productivity because employees save time commuting and can work in comfortable environments. Their internal survey found that 85% of employees reported being equally or more productive while working from home during the past year.`,
    questionStem: "Which one of the following, if true, most weakens the company's conclusion about productivity?",
    answerChoices: [
      { letter: "A", text: "Some employees prefer working in an office environment" },
      { letter: "B", text: "The company experienced a 10% decrease in revenue during the remote work period" },
      { letter: "C", text: "Self-reported productivity often exceeds objectively measured output" },
      { letter: "D", text: "Other technology companies have also adopted remote work policies" },
      { letter: "E", text: "The company provided stipends for home office equipment" },
    ],
    correctAnswer: "C",
    explanation: "If self-reported productivity is unreliable (people overestimate their own productivity), then the survey evidence doesn't actually demonstrate increased productivity. The conclusion is based on subjective perceptions that may not reflect actual output.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-034",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor: My experience teaching has shown me that students who attend class regularly perform better on exams than those who don't. Clearly, attending class leads to better exam performance. Students who are struggling should therefore attend more classes to improve their grades.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "relies on the professor's personal experience rather than controlled studies" },
      { letter: "B", text: "fails to consider that a third factor might cause both regular attendance and better performance" },
      { letter: "C", text: "assumes that all students have equal ability to attend classes regularly" },
      { letter: "D", text: "does not define what constitutes regular attendance" },
      { letter: "E", text: "ignores the role of independent study in exam preparation" },
    ],
    correctAnswer: "B",
    explanation: "The correlation between attendance and performance could be explained by a common cause. Motivated, organized students might both attend regularly and study effectively for exams. If so, simply attending more might not help struggling students who lack these underlying traits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-035",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Daniela: Art museums should focus on displaying established masterworks that have stood the test of time. Visitors come to see the great achievements of human creativity, not experimental pieces whose value is uncertain.

George: But museums have always played a role in introducing new art to the public. Without institutions willing to display contemporary work, important artists might never gain recognition. The experimental works of today may become the masterworks of tomorrow.`,
    questionStem: "Daniela and George disagree about whether",
    answerChoices: [
      { letter: "A", text: "established masterworks are valuable" },
      { letter: "B", text: "museums should prioritize displaying contemporary experimental works" },
      { letter: "C", text: "some contemporary works will eventually be recognized as masterworks" },
      { letter: "D", text: "visitor preferences should influence museum decisions" },
      { letter: "E", text: "the purpose of art museums has changed over time" },
    ],
    correctAnswer: "B",
    explanation: "Daniela argues museums should focus on established works, not experimental pieces. George argues museums should display contemporary work to introduce new art. They explicitly disagree about whether contemporary/experimental work deserves museum priority.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-036",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `City planner: Our downtown area has become less vibrant as retail stores close and foot traffic declines. Converting unused office space to residential apartments would bring more residents downtown, supporting remaining businesses and attracting new ones. This would revitalize the area.`,
    questionStem: "The city planner's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "All closed retail stores should be converted to apartments" },
      { letter: "B", text: "New downtown residents would patronize local businesses rather than shopping elsewhere" },
      { letter: "C", text: "Residential conversion is less expensive than renovating for new retail" },
      { letter: "D", text: "The downtown area was more vibrant in the past" },
      { letter: "E", text: "Office space is less valuable than residential space" },
    ],
    correctAnswer: "B",
    explanation: "The planner argues that more residents would support local businesses. This requires assuming residents would actually shop downtown rather than driving to suburban malls or shopping online. Without this assumption, adding residents might not help businesses.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-037",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers found that bilingual children often switch between languages mid-sentence, a phenomenon called code-switching. Some view this as a sign of language confusion, but researchers argue it actually demonstrates sophisticated cognitive control. Code-switching requires monitoring both language systems simultaneously and selecting contextually appropriate elements from each.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' argument?",
    answerChoices: [
      { letter: "A", text: "Monolingual children never exhibit code-switching behavior" },
      { letter: "B", text: "Bilingual children who code-switch perform better on tests of cognitive flexibility" },
      { letter: "C", text: "Code-switching is common among bilingual adults as well as children" },
      { letter: "D", text: "Some bilingual children code-switch more frequently than others" },
      { letter: "E", text: "Children who learn two languages from birth code-switch less than those who learn a second language later" },
    ],
    correctAnswer: "B",
    explanation: "If code-switchers perform better on cognitive flexibility tests, this provides direct evidence that code-switching involves enhanced cognitive abilities rather than confusion. This supports the claim that code-switching reflects sophisticated cognitive control.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-038",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Physician: Some patients request antibiotics for viral infections, even though antibiotics are ineffective against viruses. These patients argue that antibiotics can't hurt and might help. But overprescription of antibiotics has contributed to the rise of antibiotic-resistant bacteria. Therefore, I never prescribe antibiotics for viral infections.`,
    questionStem: "The physician's argument contains which one of the following reasoning errors?",
    answerChoices: [
      { letter: "A", text: "It assumes that all patients who request antibiotics for viral infections are equally uninformed" },
      { letter: "B", text: "It fails to address the patients' argument that antibiotics might provide some benefit" },
      { letter: "C", text: "It confuses correlation with causation regarding antibiotic resistance" },
      { letter: "D", text: "It applies a general policy without considering that exceptions might be warranted" },
      { letter: "E", text: "It relies on an appeal to authority rather than medical evidence" },
    ],
    correctAnswer: "D",
    explanation: "The physician adopts a blanket policy of never prescribing antibiotics for viral infections. But some cases might involve bacterial co-infections or high-risk patients where antibiotics are warranted. The rigid 'never' policy ignores potentially legitimate exceptions.",
    difficulty: "hard",
  },
  {
    id: "lr-bank18-039",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The introduction of the printing press in 15th-century Europe enabled the rapid spread of ideas that fueled the Protestant Reformation. Without the press, Luther's criticisms of the Catholic Church could not have circulated widely enough to spark a major religious movement.`,
    questionStem: "Which one of the following, if true, most weakens the historian's argument?",
    answerChoices: [
      { letter: "A", text: "The printing press was invented in China centuries before its introduction in Europe" },
      { letter: "B", text: "Many of Luther's early supporters were illiterate and learned of his ideas through sermons" },
      { letter: "C", text: "Similar religious reform movements occurred in regions with limited printing capacity" },
      { letter: "D", text: "The Catholic Church also used the printing press to disseminate its responses to Luther" },
      { letter: "E", text: "Luther wrote in vernacular German rather than Latin" },
    ],
    correctAnswer: "C",
    explanation: "If religious reform movements succeeded in areas without printing, the printing press was not necessary for such movements to spread. This undermines the claim that the Reformation specifically required the press to circulate ideas widely enough.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-040",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Legal theorist: Laws must be publicly accessible and clearly written to function effectively. Citizens cannot comply with laws they cannot understand. Yet tax codes in most countries have become so complex that even professionals struggle to interpret them correctly. This complexity undermines the rule of law by making consistent compliance virtually impossible for ordinary citizens.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Laws must be publicly accessible and clearly written" },
      { letter: "B", text: "Tax codes in most countries have become extremely complex" },
      { letter: "C", text: "The complexity of tax codes threatens the effective functioning of the rule of law" },
      { letter: "D", text: "Citizens cannot comply with laws they cannot understand" },
      { letter: "E", text: "Tax professionals struggle to interpret tax codes correctly" },
    ],
    correctAnswer: "C",
    explanation: "The argument builds from the premise that laws need clarity, shows that tax codes lack this clarity, and concludes that this complexity 'undermines the rule of law.' The other statements are premises supporting this ultimate conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Many people believe that creative genius requires suffering. They point to artists like Van Gogh, who created masterpieces while mentally ill. But this confuses correlation with causation. For every tortured artist who produced great work, there may be many who suffered without producing anything notable, while many successful artists led comfortable lives. Suffering is neither necessary nor sufficient for creative achievement.`,
    questionStem: "The argument counters the popular belief primarily by",
    answerChoices: [
      { letter: "A", text: "citing scientific studies on the psychology of creativity" },
      { letter: "B", text: "questioning the definition of creative genius" },
      { letter: "C", text: "arguing that the available evidence does not support the causal conclusion" },
      { letter: "D", text: "demonstrating that Van Gogh's suffering was not severe" },
      { letter: "E", text: "proving that comfortable artists are more creative than suffering artists" },
    ],
    correctAnswer: "C",
    explanation: "The argument identifies the logical error in moving from examples of suffering artists to the conclusion that suffering causes creativity. It points out the missing counterevidence (suffering without art, art without suffering) that would be needed to support causation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-042",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Economists argue that increasing the money supply leads to inflation. Yet the central bank has significantly expanded the money supply over the past decade, and inflation has remained low. The traditional economic model must therefore be incorrect.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Inflation can only be caused by changes in the money supply" },
      { letter: "B", text: "Other factors have not counteracted the inflationary effects of the expanded money supply" },
      { letter: "C", text: "The central bank intended to cause inflation when it expanded the money supply" },
      { letter: "D", text: "Low inflation is always preferable to high inflation" },
      { letter: "E", text: "Economic models should be able to predict outcomes with certainty" },
    ],
    correctAnswer: "B",
    explanation: "If other factors (like low demand, technological productivity gains, or global competition) offset the inflationary effect of the money supply, the model could still be correct. The argument assumes no such counteracting factors exist.",
    difficulty: "hard",
  },
  {
    id: "lr-bank18-043",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Marine biologist: Ocean plastic pollution poses a significant threat to marine ecosystems. A proposed solution involves using drone ships to collect floating plastic debris. Critics argue this approach would be too slow to make a difference. But pilot programs have shown that a single drone ship can collect several tons of plastic per day, and the technology is rapidly improving.`,
    questionStem: "Which one of the following, if true, most strengthens the marine biologist's response to the critics?",
    answerChoices: [
      { letter: "A", text: "Preventing plastic from entering the ocean is more important than removing existing plastic" },
      { letter: "B", text: "A fleet of 200 drone ships operating continuously could remove most floating ocean plastic within a decade" },
      { letter: "C", text: "The drone ships require minimal human supervision to operate" },
      { letter: "D", text: "Some ocean currents concentrate plastic in specific areas" },
      { letter: "E", text: "The technology for the drone ships was developed by a nonprofit organization" },
    ],
    correctAnswer: "B",
    explanation: "The critics say the approach is too slow to make a difference. Evidence that a practical fleet could remove most plastic within a decade directly counters this objection by showing the approach can work at meaningful scale and speed.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-044",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Wellness advocate: Ancient civilizations like the Egyptians and Greeks used herbal remedies that are still employed today. If these remedies were ineffective, they would not have persisted for thousands of years. Their longevity proves they work.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "ignores the possibility that ancient civilizations had access to remedies we no longer use" },
      { letter: "B", text: "assumes that practices persist only if they are effective" },
      { letter: "C", text: "fails to consider that modern medicine has superseded ancient remedies" },
      { letter: "D", text: "overgeneralizes from the practices of two civilizations" },
      { letter: "E", text: "does not distinguish between different types of herbal remedies" },
    ],
    correctAnswer: "B",
    explanation: "Many ineffective practices persist due to tradition, placebo effects, or lack of better alternatives. Bloodletting persisted for centuries despite being harmful. The longevity of a practice does not prove its effectiveness.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-045",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the metropolitan planning commission are required to recuse themselves from votes on projects in which they have a financial interest. Thompson, a commission member, voted on the Riverside development project. Commission records show that no member recused themselves from this vote.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Thompson had no financial interest in the Riverside development project" },
      { letter: "B", text: "No commission member had a financial interest in the Riverside project" },
      { letter: "C", text: "The commission violated its recusal requirements" },
      { letter: "D", text: "Either Thompson had no financial interest in the project or Thompson violated the recusal requirement" },
      { letter: "E", text: "The Riverside development project was approved by the commission" },
    ],
    correctAnswer: "D",
    explanation: "Thompson voted and didn't recuse. Either Thompson had no financial interest (making recusal unnecessary) or Thompson had a financial interest but failed to recuse (a violation). One of these must be true. The argument cannot determine which.",
    difficulty: "hard",
  },
  {
    id: "lr-bank18-046",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Educational researcher: Class sizes in elementary schools should be reduced because smaller classes allow teachers to provide more individual attention to each student. Studies show that students in smaller classes demonstrate better academic outcomes.`,
    questionStem: "Which one of the following, if true, most weakens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Teachers in smaller classes report higher job satisfaction" },
      { letter: "B", text: "The cost of hiring additional teachers to reduce class size is substantial" },
      { letter: "C", text: "Schools that reduced class sizes did so in higher-income districts with already high-performing students" },
      { letter: "D", text: "Some teachers prefer larger classes because of increased energy" },
      { letter: "E", text: "Class size reduction would require constructing new classrooms" },
    ],
    correctAnswer: "C",
    explanation: "If smaller classes appeared only in high-income districts, the better outcomes might reflect socioeconomic advantages rather than class size. This selection bias undermines the claim that smaller classes cause better outcomes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the defendant had committed the crime, forensic evidence would have been found at the scene. No forensic evidence was found at the scene. Therefore, the defendant did not commit the crime.`,
    questionStem: "Which one of the following arguments is most similar in its logical structure to the argument above?",
    answerChoices: [
      { letter: "A", text: "If it had rained last night, the ground would be wet. The ground is wet. Therefore, it rained last night." },
      { letter: "B", text: "If the restaurant were open, the lights would be on. The lights are off. Therefore, the restaurant is closed." },
      { letter: "C", text: "All prime numbers greater than 2 are odd. Seven is an odd number greater than 2. Therefore, seven is prime." },
      { letter: "D", text: "If you study hard, you will pass the exam. You studied hard. Therefore, you will pass the exam." },
      { letter: "E", text: "Some athletes are wealthy. Jordan is wealthy. Therefore, Jordan is an athlete." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow modus tollens: If P then Q; Not Q; Therefore, not P. The original says if crime then evidence; no evidence; therefore no crime. Answer B says if open then lights on; lights off; therefore closed.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-048",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Politician: My opponent claims that my tax proposal will benefit only the wealthy. But my opponent is a millionaire who inherited a fortune and has never had to work for a living. How can someone so disconnected from ordinary people criticize any tax proposal?`,
    questionStem: "The politician's response is flawed because it",
    answerChoices: [
      { letter: "A", text: "misrepresents the opponent's original claim" },
      { letter: "B", text: "attacks the opponent's personal circumstances rather than addressing the claim about the tax proposal" },
      { letter: "C", text: "assumes that inherited wealth is always undeserved" },
      { letter: "D", text: "fails to provide any evidence about what the tax proposal would actually accomplish" },
      { letter: "E", text: "ignores the possibility that the opponent has consulted with economic experts" },
    ],
    correctAnswer: "B",
    explanation: "The politician responds to a claim about the tax proposal's effects by attacking the critic's wealth and background. The opponent's personal circumstances are irrelevant to whether the criticism of the tax proposal is accurate. This is an ad hominem fallacy.",
    difficulty: "easy",
  },
  {
    id: "lr-bank18-049",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Social media platforms have been criticized for spreading misinformation. In response, some platforms now label posts that contain potentially misleading claims. Research shows that labeled posts are shared less frequently than unlabeled posts. This labeling system is therefore effective at reducing the spread of misinformation.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Users understand what the labels mean" },
      { letter: "B", text: "The reduction in sharing is caused by the labels rather than by other factors" },
      { letter: "C", text: "All misinformation receives labels" },
      { letter: "D", text: "Users who share labeled posts believe the information is true" },
      { letter: "E", text: "The labeling process never makes errors" },
    ],
    correctAnswer: "B",
    explanation: "The argument attributes reduced sharing to the labeling. But if labeled posts are shared less for other reasons (perhaps they were already less shareable content), the labels wouldn't be responsible. The argument assumes labels cause the reduced sharing.",
    difficulty: "medium",
  },
  {
    id: "lr-bank18-050",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Some argue that artificial intelligence systems should be granted legal rights once they achieve sufficient cognitive sophistication. But rights exist to protect beings that can be harmed, and harm requires the capacity for subjective experience. Since AI systems process information without subjective experience, they cannot be harmed in any morally relevant sense, and therefore should not have rights.`,
    questionStem: "Which one of the following, if true, most strengthens the ethicist's argument?",
    answerChoices: [
      { letter: "A", text: "Current AI systems are not as cognitively sophisticated as humans" },
      { letter: "B", text: "Some legal systems have granted limited rights to corporations" },
      { letter: "C", text: "Subjective experience requires biological neural processes that cannot be replicated in silicon" },
      { letter: "D", text: "Many ethicists disagree about the foundations of rights" },
      { letter: "E", text: "AI systems can simulate responses that appear to indicate suffering" },
    ],
    correctAnswer: "C",
    explanation: "The ethicist argues AI cannot have subjective experience. If subjective experience requires biological processes that silicon cannot replicate, this supports the claim that AI lacks (and cannot develop) the relevant capacity for harm, strengthening the conclusion that AI should not have rights.",
    difficulty: "hard",
  },
];
