// Logical Reasoning Questions Bank - Set 53
import { Question } from "../lsat-types";

export const lrQuestionsSet53: Question[] = [
  {
    id: "lr-bank53-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during work hours are more productive than those who work continuously. Therefore, any company that wants to maximize productivity should require all employees to take mandatory breaks every hour.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that productivity may be influenced by factors other than break frequency" },
      { letter: "B", text: "assumes that what is true of employees who voluntarily take breaks will also be true of those required to take breaks" },
      { letter: "C", text: "overlooks the possibility that some employees already take breaks every hour" },
      { letter: "D", text: "does not specify the optimal length of breaks for maximizing productivity" },
      { letter: "E", text: "presumes without justification that productivity is the only goal companies should pursue" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the flaw of assuming that voluntary behavior and mandatory behavior will produce the same results. The study examined employees who chose to take breaks, but the conclusion is about requiring all employees to take breaks. Those who voluntarily take breaks may be different from those who would be forced to, and the forced breaks may not have the same effect.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers have observed that coral reefs in areas with high boat traffic show significantly more damage than reefs in protected areas with limited human access. Marine biologists conclude that boat traffic is a major cause of coral reef degradation.`,
    questionStem: "Which one of the following, if true, most strengthens the marine biologists' conclusion?",
    answerChoices: [
      { letter: "A", text: "Protected areas often have stricter regulations on pollution than areas with high boat traffic" },
      { letter: "B", text: "The propellers and anchors of boats have been directly observed causing physical damage to coral structures" },
      { letter: "C", text: "Coral reefs in both types of areas are affected by rising ocean temperatures" },
      { letter: "D", text: "Some species of coral are more resilient to damage than others" },
      { letter: "E", text: "The economic benefits of boat tourism often outweigh the costs of reef damage" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that boat traffic causes coral reef degradation based on a correlation. Choice B strengthens this by providing direct evidence of a causal mechanism—boats physically damaging coral with propellers and anchors. This eliminates alternative explanations for the correlation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that the new downtown parking garage will reduce traffic congestion because drivers currently spend an average of 20 minutes circling blocks looking for street parking. With ample garage parking available, this circling behavior will be eliminated, leading to less congested streets.`,
    questionStem: "Which one of the following, if true, most seriously weakens the city council's argument?",
    answerChoices: [
      { letter: "A", text: "The parking garage will be located at the edge of downtown, requiring drivers to walk farther to their destinations" },
      { letter: "B", text: "The availability of convenient parking is likely to attract many additional drivers who currently avoid downtown" },
      { letter: "C", text: "Some drivers prefer street parking because it is less expensive than garage parking" },
      { letter: "D", text: "The construction of the parking garage will cause temporary traffic disruptions" },
      { letter: "E", text: "Other cities have built similar parking garages with varying degrees of success" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that the total number of drivers will remain constant. Choice B undermines this by suggesting that convenient parking will attract new drivers, potentially increasing overall traffic even if circling is eliminated. This is a classic case of induced demand.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All members of the ethics committee must have completed at least one graduate-level course in moral philosophy. Dr. Hernandez has been appointed to the ethics committee. Therefore, Dr. Hernandez must have a strong understanding of ethical theories.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Graduate-level courses in moral philosophy are more rigorous than undergraduate courses" },
      { letter: "B", text: "Dr. Hernandez was appointed to the ethics committee based on her academic credentials" },
      { letter: "C", text: "Completing a graduate-level course in moral philosophy results in a strong understanding of ethical theories" },
      { letter: "D", text: "Members of the ethics committee are required to apply ethical theories in their work" },
      { letter: "E", text: "Dr. Hernandez has completed more than one graduate-level course in moral philosophy" },
    ],
    correctAnswer: "C",
    explanation: "The argument moves from 'completed a course' to 'has a strong understanding.' This requires assuming that course completion leads to strong understanding. Without this bridge, the conclusion doesn't follow from the premises.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Critics claim that social media has made people more isolated. However, studies show that social media users actually maintain more friendships than non-users. Additionally, people in remote areas now have access to communities they never could have joined before. Clearly, social media has expanded rather than contracted human connection.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Critics of social media are wrong about all of its effects" },
      { letter: "B", text: "Social media has increased human connection rather than decreased it" },
      { letter: "C", text: "Social media users maintain more friendships than non-users" },
      { letter: "D", text: "People in remote areas benefit most from social media" },
      { letter: "E", text: "Studies about social media are more reliable than critics' claims" },
    ],
    correctAnswer: "B",
    explanation: "The main conclusion is signaled by 'Clearly' and states that social media has expanded rather than contracted human connection. The other statements about friendship numbers and remote area access serve as supporting premises for this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that morality is purely subjective because different cultures have different moral codes. But consider: different cultures also have different beliefs about physics, yet we don't conclude that physics is subjective. The existence of disagreement about a topic does not establish that there are no objective truths about that topic.`,
    questionStem: "The philosopher's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "demonstrating that the conclusion of an argument contradicts one of its premises" },
      { letter: "B", text: "showing that an argument's reasoning, if valid, would lead to an unacceptable conclusion in an analogous case" },
      { letter: "C", text: "questioning the accuracy of the evidence offered for a conclusion" },
      { letter: "D", text: "establishing that the proponents of an argument have a personal interest in its conclusion" },
      { letter: "E", text: "providing an alternative explanation for the evidence cited by the opposing argument" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher uses an analogy to physics to show that the reasoning pattern (cultural disagreement implies subjectivity) would lead to absurd conclusions if applied consistently. This is a reductio ad absurdum via parallel case.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `My opponent claims that the proposed tax increase will harm small businesses. But she owns three large corporations and clearly stands to benefit from lower taxes. Therefore, her argument against the tax increase should be rejected.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to address the substance of the opponent's argument about small businesses" },
      { letter: "B", text: "assumes without justification that large corporations are not affected by tax policy" },
      { letter: "C", text: "overlooks the possibility that the opponent also owns small businesses" },
      { letter: "D", text: "presumes that wealthy individuals cannot have genuine concerns about economic policy" },
      { letter: "E", text: "does not consider that the opponent might support some forms of taxation" },
    ],
    correctAnswer: "A",
    explanation: "This is an ad hominem fallacy. The argument attacks the opponent's motives rather than addressing whether the tax increase would actually harm small businesses. The opponent's personal interests don't determine whether her argument is sound.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company claims that its new medication reduces migraine frequency by 50% compared to placebo. However, patients in the treatment group were also given dietary counseling, while the placebo group received no counseling. Critics argue this makes it impossible to attribute the results to the medication alone.`,
    questionStem: "Which one of the following, if true, most strengthens the pharmaceutical company's claim about the medication?",
    answerChoices: [
      { letter: "A", text: "The dietary counseling lasted only 15 minutes and covered general nutrition guidelines" },
      { letter: "B", text: "A separate study found that dietary counseling alone reduces migraine frequency by only 5%" },
      { letter: "C", text: "Patients in both groups had similar migraine histories before the study began" },
      { letter: "D", text: "The pharmaceutical company has a strong track record of developing effective medications" },
      { letter: "E", text: "Some patients in the treatment group did not follow the dietary recommendations" },
    ],
    correctAnswer: "B",
    explanation: "The critics suggest the dietary counseling might explain the results. Choice B shows that dietary counseling alone has minimal effect (5%), so the 50% reduction must be largely attributable to the medication. This directly addresses the confounding variable concern.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-009",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should not build the proposed sports stadium using public funds. Professional sports teams generate enormous profits for their owners, and it is unfair to ask taxpayers to subsidize private profit.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Professional sports teams never provide benefits to the communities in which they are located" },
      { letter: "B", text: "Taxpayers would not benefit from the stadium in ways that would justify public funding" },
      { letter: "C", text: "Sports stadiums built with public funds always lose money for the city" },
      { letter: "D", text: "Team owners could afford to build stadiums without public assistance" },
      { letter: "E", text: "The city has other priorities that should take precedence over stadium construction" },
    ],
    correctAnswer: "B",
    explanation: "The argument's logic depends on the idea that taxpayers shouldn't subsidize private profit. But if taxpayers received benefits that justified the expenditure (jobs, economic activity, entertainment), the subsidy might be fair. The argument assumes such benefits either don't exist or don't justify the cost.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Educational researchers conclude that smaller class sizes improve student learning outcomes. They point to data showing that students in classes of 15 or fewer consistently score higher on standardized tests than students in classes of 30 or more.`,
    questionStem: "Which one of the following, if true, most weakens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Standardized tests do not measure all aspects of student learning" },
      { letter: "B", text: "Schools with smaller class sizes tend to be in wealthier districts that also provide more resources per student" },
      { letter: "C", text: "Some teachers prefer teaching larger classes because of increased energy and interaction" },
      { letter: "D", text: "Class size has decreased nationally over the past two decades" },
      { letter: "E", text: "Students in smaller classes report higher satisfaction with their education" },
    ],
    correctAnswer: "B",
    explanation: "This points to a confounding variable: wealth and resources. If schools with small classes also have more resources, the improved outcomes might be due to resources rather than class size itself. This alternative explanation weakens the causal conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-011",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The government's new renewable energy policy will either create thousands of green jobs or it will fail to address climate change. Since the policy has already created over 10,000 jobs in the solar industry, it clearly is addressing climate change effectively.`,
    questionStem: "The reasoning in the argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "confuses a necessary condition for addressing climate change with a sufficient condition" },
      { letter: "B", text: "fails to consider that job creation and climate impact are not mutually exclusive outcomes" },
      { letter: "C", text: "treats two alternatives as mutually exclusive when they may not be" },
      { letter: "D", text: "assumes that past results guarantee future outcomes" },
      { letter: "E", text: "overlooks the possibility that some green jobs may not benefit the environment" },
    ],
    correctAnswer: "C",
    explanation: "The argument presents a false dichotomy, suggesting the policy will either create jobs OR fail to address climate change. But these aren't mutually exclusive—the policy could create jobs AND still fail to adequately address climate change. Job creation doesn't prove climate effectiveness.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Economist A: Minimum wage increases help low-income workers by ensuring they receive fair compensation for their labor. When workers earn more, they spend more, stimulating the economy.

Economist B: Minimum wage increases actually harm the workers they're intended to help. When labor costs rise, businesses hire fewer workers, leading to higher unemployment among low-wage workers.`,
    questionStem: "The main point at issue between Economist A and Economist B is whether",
    answerChoices: [
      { letter: "A", text: "low-income workers deserve fair compensation for their labor" },
      { letter: "B", text: "minimum wage increases have a net positive or negative effect on low-income workers" },
      { letter: "C", text: "businesses respond to labor cost increases by reducing their workforce" },
      { letter: "D", text: "increased spending by workers stimulates economic growth" },
      { letter: "E", text: "government should regulate wages in the labor market" },
    ],
    correctAnswer: "B",
    explanation: "Economist A claims minimum wage increases help low-income workers, while Economist B claims they harm these workers. The core disagreement is about the net effect on the intended beneficiaries—not about the mechanisms, but about the overall outcome.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No truly democratic government censors political speech. Country X censors political speech. Therefore, Country X does not have a truly democratic government.`,
    questionStem: "Which one of the following arguments is most similar in its pattern of reasoning to the argument above?",
    answerChoices: [
      { letter: "A", text: "All professional athletes train regularly. Maria trains regularly. Therefore, Maria is a professional athlete." },
      { letter: "B", text: "No honest person would lie under oath. Jackson lied under oath. Therefore, Jackson is not an honest person." },
      { letter: "C", text: "Some reptiles are cold-blooded. This animal is a reptile. Therefore, this animal might be cold-blooded." },
      { letter: "D", text: "Most successful businesses have strong leadership. This company lacks strong leadership. Therefore, it will probably fail." },
      { letter: "E", text: "All squares are rectangles. This shape is not a rectangle. Therefore, this shape is not a square." },
    ],
    correctAnswer: "B",
    explanation: "The original argument has the form: No A does B. X does B. Therefore, X is not A. Choice B follows this same pattern: No honest person lies under oath. Jackson lied under oath. Therefore, Jackson is not honest. Both are valid applications of modus tollens with universal negative premises.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art historians believe that a recently discovered painting was created by the Renaissance master Bellini. They base this on the painting's use of light, composition, and brushwork, all of which are characteristic of Bellini's known works.`,
    questionStem: "Which one of the following, if true, most strengthens the art historians' conclusion?",
    answerChoices: [
      { letter: "A", text: "Bellini trained several students who later became famous painters in their own right" },
      { letter: "B", text: "Chemical analysis of the paint pigments shows they were manufactured in the region where Bellini worked during the period the painting appears to have been created" },
      { letter: "C", text: "The painting depicts a religious scene, which was a common subject during the Renaissance" },
      { letter: "D", text: "Several art experts initially disagreed about the painting's attribution before reaching consensus" },
      { letter: "E", text: "Bellini created hundreds of paintings during his career, many of which are now in private collections" },
    ],
    correctAnswer: "B",
    explanation: "Choice B provides independent physical evidence supporting the attribution—the paint pigments match the right time and place. This corroborates the stylistic analysis with scientific data, making the conclusion significantly stronger.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A technology company argues that their facial recognition software should be adopted by law enforcement because it has a 98% accuracy rate in identifying individuals. Such high accuracy, they claim, would help police solve crimes more efficiently while minimizing errors.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument for adopting this technology?",
    answerChoices: [
      { letter: "A", text: "Other companies have developed facial recognition software with similar accuracy rates" },
      { letter: "B", text: "The software requires significant computing power to operate effectively" },
      { letter: "C", text: "When applied to a database of millions of faces, a 2% error rate would result in tens of thousands of misidentifications" },
      { letter: "D", text: "Some civil liberties groups oppose the use of facial recognition by law enforcement" },
      { letter: "E", text: "The software performs best when analyzing high-quality images taken in controlled lighting" },
    ],
    correctAnswer: "C",
    explanation: "The argument treats 98% accuracy as sufficient for minimizing errors. But choice C shows that at scale, 2% errors become enormous in absolute terms—tens of thousands of innocent people misidentified. This undermines the claim that errors would be minimized.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-016",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new exhibition on ancient Egypt has attracted record attendance. This proves that the public is more interested in ancient history than contemporary art, which the museum has featured in previous exhibitions.`,
    questionStem: "The argument's conclusion depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Ancient Egypt is more representative of ancient history than contemporary art is of modern culture" },
      { letter: "B", text: "The difference in attendance is not due to factors other than the subject matter of the exhibitions" },
      { letter: "C", text: "The museum has not increased its marketing efforts for the Egypt exhibition" },
      { letter: "D", text: "Previous exhibitions of contemporary art were of lower quality than the Egypt exhibition" },
      { letter: "E", text: "Museum attendance is the best measure of public interest in a topic" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that higher attendance is caused by greater interest in the subject matter. But other factors could explain the difference: marketing, timing, special events, ticket prices, etc. The argument requires assuming these other factors aren't responsible.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-017",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Everyone who has switched to a Mediterranean diet has reported improvements in their energy levels and overall wellbeing. This demonstrates that the Mediterranean diet is the healthiest dietary choice for all people.`,
    questionStem: "The nutritionist's reasoning is most vulnerable to which one of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It fails to define what constitutes a Mediterranean diet" },
      { letter: "B", text: "It generalizes from a self-selected group to the entire population" },
      { letter: "C", text: "It does not consider the environmental impact of the Mediterranean diet" },
      { letter: "D", text: "It assumes that energy levels are the most important measure of health" },
      { letter: "E", text: "It overlooks the possibility that some people cannot afford Mediterranean foods" },
    ],
    correctAnswer: "B",
    explanation: "Those who switch to a Mediterranean diet are self-selected—they chose to make the change. This group may differ from the general population in motivation, health consciousness, or other factors. What works for them may not work for everyone, making the generalization unwarranted.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-018",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Literary critic: Many claim that the novel is dead as an art form because people now prefer visual media. But the same claim was made about poetry when the novel first emerged, about theater when film was invented, and about radio when television appeared. Each of these art forms survives and thrives today. The novel will be no exception.`,
    questionStem: "The literary critic's argument employs which one of the following argumentative strategies?",
    answerChoices: [
      { letter: "A", text: "Citing statistical evidence to disprove a prediction" },
      { letter: "B", text: "Demonstrating that a conclusion follows necessarily from established premises" },
      { letter: "C", text: "Arguing that a pattern observed in similar past cases will likely continue" },
      { letter: "D", text: "Questioning the expertise of those who make the original claim" },
      { letter: "E", text: "Showing that the original claim contains an internal contradiction" },
    ],
    correctAnswer: "C",
    explanation: "The critic uses historical analogy: similar predictions about other art forms proved wrong, so the prediction about novels will likely also be wrong. This is reasoning from a pattern of past cases to a current case.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-019",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All partners at the law firm have either a JD from a top-ten law school or more than fifteen years of litigation experience. Martinez just made partner and graduated from a law school ranked outside the top fifty. Henderson, who has ten years of experience, is still an associate.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Martinez has more than fifteen years of litigation experience" },
      { letter: "B", text: "Henderson did not graduate from a top-ten law school" },
      { letter: "C", text: "All partners have at least ten years of litigation experience" },
      { letter: "D", text: "Martinez graduated from a better law school than Henderson" },
      { letter: "E", text: "Henderson will never become a partner at the firm" },
    ],
    correctAnswer: "A",
    explanation: "Partners must have either a top-ten JD OR 15+ years experience. Martinez is a partner without a top-ten JD (outside top fifty). Therefore, Martinez must have 15+ years experience. This is a straightforward disjunction: if not one, then the other.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-020",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have found that ancient settlements near rivers tended to have larger populations than those located inland. They conclude that access to rivers provided ancient peoples with critical resources that enabled population growth.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologists' conclusion?",
    answerChoices: [
      { letter: "A", text: "Rivers provided transportation routes that facilitated trade between settlements" },
      { letter: "B", text: "Some inland settlements had access to underground water sources" },
      { letter: "C", text: "Ancient river settlements show evidence of irrigation agriculture and fishing economies" },
      { letter: "D", text: "Climate patterns were similar in river and inland areas during ancient times" },
      { letter: "E", text: "Many ancient river settlements were eventually abandoned due to flooding" },
    ],
    correctAnswer: "C",
    explanation: "Choice C provides specific evidence of how rivers enabled population growth—through irrigation agriculture and fishing. This demonstrates the causal mechanism between river access and the resources that support larger populations.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-021",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Senator: My opponent claims that I have been ineffective during my time in office. But during my term, unemployment in our state decreased by 4%, and new business registrations increased by 12%. Clearly, I have been an effective senator.`,
    questionStem: "The senator's argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on statistics that may not be accurate" },
      { letter: "B", text: "assumes that economic improvements were caused by the senator's actions" },
      { letter: "C", text: "fails to address other measures of senatorial effectiveness" },
      { letter: "D", text: "does not compare these results to those of other senators" },
      { letter: "E", text: "uses percentage changes rather than absolute numbers" },
    ],
    correctAnswer: "B",
    explanation: "The senator commits the post hoc fallacy—assuming that because economic improvements occurred during the term, they were caused by the senator's actions. Economic conditions are influenced by many factors beyond any individual senator's control.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-022",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The company's new diversity initiative will improve innovation because research shows that diverse teams generate more creative solutions. Our workforce will become more diverse once we implement the new hiring practices outlined in the initiative.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The company's current workforce lacks diversity" },
      { letter: "B", text: "Creative solutions are the primary driver of innovation" },
      { letter: "C", text: "The new diverse hires will be integrated into teams rather than segregated" },
      { letter: "D", text: "Other companies have successfully improved innovation through diversity initiatives" },
      { letter: "E", text: "The company's employees will support the diversity initiative" },
    ],
    correctAnswer: "C",
    explanation: "The research is about diverse teams, not just diverse workforces. For diversity to improve innovation, diverse employees must actually work together in teams. If new hires are segregated, the team-level diversity that drives creativity won't exist.",
    difficulty: "hard",
  },
  {
    id: "lr-bank53-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Health officials recommend that adults sleep at least seven hours per night based on studies showing that people who sleep less than seven hours have higher rates of cardiovascular disease. Therefore, sleeping more will reduce your risk of cardiovascular disease.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some people function well on less than seven hours of sleep" },
      { letter: "B", text: "Cardiovascular disease may cause sleep disturbances that lead to reduced sleep time" },
      { letter: "C", text: "The studies controlled for age and gender but not for diet" },
      { letter: "D", text: "People who sleep more than nine hours also have elevated cardiovascular risk" },
      { letter: "E", text: "Cardiovascular disease rates have decreased over the past decade" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that less sleep causes cardiovascular disease. Choice B suggests reverse causation—that cardiovascular disease might cause poor sleep. If the disease causes the sleep reduction rather than vice versa, then sleeping more wouldn't reduce disease risk.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-024",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `It is often claimed that eyewitness testimony is reliable because people remember significant events clearly. However, research has consistently shown that stress and emotion actually impair memory accuracy. Furthermore, witnesses frequently incorporate information learned after an event into their memories without realizing it. For these reasons, courts should treat eyewitness testimony with considerable skepticism.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Stress and emotion impair memory accuracy" },
      { letter: "B", text: "People do not remember significant events as clearly as commonly believed" },
      { letter: "C", text: "Witnesses incorporate post-event information into their memories" },
      { letter: "D", text: "Courts should be skeptical of eyewitness testimony" },
      { letter: "E", text: "Research on memory contradicts common beliefs about eyewitness reliability" },
    ],
    correctAnswer: "D",
    explanation: "The phrase 'For these reasons' signals that what follows is the conclusion. The argument uses evidence about memory limitations to support the normative claim that courts should treat eyewitness testimony skeptically.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-025",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Those who argue that free will is an illusion point to neuroscience studies showing that brain activity precedes conscious awareness of decisions. But these studies only examined simple motor decisions, like when to move a finger. Complex moral choices, which are what we really care about when discussing free will, were not studied. Therefore, free will exists.`,
    questionStem: "The reasoning in the philosopher's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "attacks the motives of those who argue against free will rather than their evidence" },
      { letter: "B", text: "concludes that something exists merely because it has not been proven not to exist" },
      { letter: "C", text: "assumes that all decisions involve the same mental processes" },
      { letter: "D", text: "fails to consider neuroscience studies other than those mentioned" },
      { letter: "E", text: "conflates the concept of moral responsibility with the concept of free will" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher correctly notes limitations in the studies but then concludes free will exists merely because it hasn't been disproven for complex decisions. This is an appeal to ignorance—absence of evidence against a claim doesn't constitute evidence for it.",
    difficulty: "hard",
  },
  {
    id: "lr-bank53-026",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Urban planners propose that converting some downtown parking lots into green spaces would reduce the urban heat island effect, where city centers are significantly warmer than surrounding areas. The heat island effect is primarily caused by dark surfaces like asphalt absorbing and retaining solar heat.`,
    questionStem: "Which one of the following, if true, most strengthens the urban planners' proposal?",
    answerChoices: [
      { letter: "A", text: "Some cities have successfully created rooftop gardens on downtown buildings" },
      { letter: "B", text: "Studies show that vegetation cools surrounding air through evapotranspiration and provides shade" },
      { letter: "C", text: "The urban heat island effect contributes to increased energy consumption for air conditioning" },
      { letter: "D", text: "Downtown parking lots are often underutilized during evening hours" },
      { letter: "E", text: "Green spaces can increase property values in surrounding areas" },
    ],
    correctAnswer: "B",
    explanation: "The argument needs to show that green spaces would actually reduce heat. Choice B provides the mechanism: vegetation actively cools air through evapotranspiration and shading. This explains why replacing asphalt with plants would reduce temperatures.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-027",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A study found that employees who work from home are 15% more productive than those who work in the office. The company should therefore allow all employees to work from home to maximize productivity.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some employees do not have adequate workspace at home" },
      { letter: "B", text: "The study was conducted by a company that sells remote work software" },
      { letter: "C", text: "Employees in the study who worked from home had volunteered to do so" },
      { letter: "D", text: "Remote work eliminates commuting time, which employees can use for personal activities" },
      { letter: "E", text: "Some managers believe that in-person collaboration is important for team cohesion" },
    ],
    correctAnswer: "C",
    explanation: "This reveals selection bias. Employees who volunteered to work from home may be more self-motivated or have better home setups than average. Requiring all employees to work from home would include many who wouldn't perform well in that environment.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-028",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Scientist A: Gene editing technology like CRISPR should be used to eliminate genetic diseases from the human population. We have a moral obligation to prevent suffering when we have the means to do so.

Scientist B: Gene editing to eliminate diseases is too risky. The long-term effects of genetic modifications are unknown, and we could inadvertently create new problems while trying to solve old ones.`,
    questionStem: "Scientist A and Scientist B disagree about whether",
    answerChoices: [
      { letter: "A", text: "CRISPR is an effective gene editing technology" },
      { letter: "B", text: "genetic diseases cause significant human suffering" },
      { letter: "C", text: "the benefits of using gene editing to eliminate diseases outweigh the risks" },
      { letter: "D", text: "scientists have a moral obligation to prevent suffering" },
      { letter: "E", text: "long-term effects of genetic modifications are currently unknown" },
    ],
    correctAnswer: "C",
    explanation: "Scientist A focuses on the benefits (preventing suffering) and concludes we should use the technology. Scientist B focuses on the risks (unknown effects, new problems) and concludes we shouldn't. Their disagreement is fundamentally about whether benefits outweigh risks.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The proposed merger between the two largest telecommunications companies should be blocked because it would reduce competition in the industry. When competition decreases, companies have less incentive to innovate and improve services.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The telecommunications industry currently has sufficient competition" },
      { letter: "B", text: "The merged company would not face significant competition from smaller companies or new entrants" },
      { letter: "C", text: "Innovation and service improvement are the only benefits of competition" },
      { letter: "D", text: "Mergers between large companies always reduce industry competition" },
      { letter: "E", text: "The government has the authority to block proposed mergers" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes the merger would meaningfully reduce competition. But if smaller companies or new market entrants would provide sufficient competition, the merger might not reduce competitive pressure. The argument requires assuming this alternative competition wouldn't be adequate.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-030",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution claims my client committed the robbery at 9 PM based on an eyewitness. But credit card records show my client made a purchase in a town 50 miles away at 8:45 PM. Given normal driving speeds, it would be physically impossible to travel that distance in 15 minutes. Therefore, my client cannot be the robber.`,
    questionStem: "The defense attorney's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing an alternative suspect who had opportunity and motive" },
      { letter: "B", text: "demonstrating that accepting the prosecution's claim leads to a physical impossibility" },
      { letter: "C", text: "questioning the reliability of the eyewitness based on conditions at the time" },
      { letter: "D", text: "showing that the prosecution's evidence was obtained improperly" },
      { letter: "E", text: "establishing that the defendant had no motive to commit the crime" },
    ],
    correctAnswer: "B",
    explanation: "The attorney uses a reductio ad absurdum: if the defendant committed the robbery, they would have had to travel 50 miles in 15 minutes, which is physically impossible. This impossibility disproves the prosecution's claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Parents who read to their children every day have children who perform better in school. The Browns read to their daughter every day, so she will definitely perform well in school.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "ignores other factors that might influence academic performance" },
      { letter: "B", text: "treats a correlation as if it guaranteed an outcome in every individual case" },
      { letter: "C", text: "assumes that all parents are equally skilled at reading to children" },
      { letter: "D", text: "relies on a sample that may not be representative" },
      { letter: "E", text: "confuses cause and effect in the relationship between reading and performance" },
    ],
    correctAnswer: "B",
    explanation: "The premise describes a general pattern (children of parents who read tend to perform better), but the conclusion claims certainty about an individual case ('definitely perform well'). Statistical tendencies don't guarantee outcomes in specific instances.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historians argue that the decline of the Roman Empire was primarily caused by economic factors, including currency debasement and unsustainable military spending. They note that these problems accumulated gradually over centuries before the empire's collapse.`,
    questionStem: "Which one of the following, if true, most strengthens the historians' argument?",
    answerChoices: [
      { letter: "A", text: "The Roman Empire lasted longer than most other ancient empires" },
      { letter: "B", text: "Barbarian invasions occurred primarily after the economy had been weakened" },
      { letter: "C", text: "Some Roman emperors attempted currency reforms but were unsuccessful" },
      { letter: "D", text: "The Byzantine portion of the empire survived for another thousand years" },
      { letter: "E", text: "Military spending was necessary to defend the empire's extensive borders" },
    ],
    correctAnswer: "B",
    explanation: "If barbarian invasions came after economic weakening, this supports the argument that economic problems were the primary cause rather than external military pressure. The invasions succeeded because the economy had already compromised the empire's ability to respond.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-033",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Anyone who exercises regularly and eats well will be healthy. Sarah exercises regularly, but she does not eat well. Therefore, Sarah might not be healthy.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All successful companies have good products and effective marketing. TechCorp has good products but ineffective marketing. Therefore, TechCorp might not be successful." },
      { letter: "B", text: "People who study hard pass their exams. Tom studied hard. Therefore, Tom passed his exams." },
      { letter: "C", text: "No one who lacks ambition will succeed. Jones has ambition. Therefore, Jones will succeed." },
      { letter: "D", text: "Every mammal breathes air. Whales are mammals. Therefore, whales breathe air." },
      { letter: "E", text: "Most doctors recommend exercise. Dr. Smith is a doctor. Therefore, Dr. Smith probably recommends exercise." },
    ],
    correctAnswer: "A",
    explanation: "The original argument: A&B → C; A but not B; therefore maybe not C. Choice A follows the same pattern: good products & effective marketing → successful; good products but not effective marketing; therefore might not be successful.",
    difficulty: "hard",
  },
  {
    id: "lr-bank53-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The newspaper's editorial board should not have endorsed a candidate in the upcoming election. Newspapers have significant influence over public opinion, and using that influence to promote particular candidates undermines the democratic process.`,
    questionStem: "Which one of the following is an assumption required by the argument?",
    answerChoices: [
      { letter: "A", text: "The newspaper's endorsed candidate is not the best choice for voters" },
      { letter: "B", text: "Voters are incapable of forming their own opinions about candidates" },
      { letter: "C", text: "Using influence to promote candidates undermines democracy even when the influence is openly acknowledged" },
      { letter: "D", text: "Other media outlets do not endorse political candidates" },
      { letter: "E", text: "The newspaper's editorial board has a conflict of interest regarding the endorsed candidate" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that using influence to promote candidates undermines democracy. But newspaper endorsements are openly editorial—not presented as objective news. The argument must assume that even acknowledged influence undermines democracy.",
    difficulty: "hard",
  },
  {
    id: "lr-bank53-035",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Video games are harmful to children's development because children who play video games for more than two hours daily score lower on measures of social skills than children who play less or not at all.`,
    questionStem: "Which one of the following, if true, most seriously weakens the psychologist's argument?",
    answerChoices: [
      { letter: "A", text: "Many popular video games require players to cooperate with others online" },
      { letter: "B", text: "Children with lower social skills are more likely to prefer solitary activities like video games" },
      { letter: "C", text: "Some parents limit their children's video game time because of concerns about social development" },
      { letter: "D", text: "Children who play video games often develop strong problem-solving abilities" },
      { letter: "E", text: "The measures of social skills used in studies may not capture all aspects of social competence" },
    ],
    correctAnswer: "B",
    explanation: "This suggests reverse causation: rather than video games causing low social skills, children with already-low social skills may be drawn to video games. If the cause-effect relationship is reversed, then reducing video game time wouldn't improve social skills.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-036",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Political commentator: The senator claims to support environmental protection, yet she drives an SUV. This inconsistency shows that her professed environmental views are insincere and should not be trusted.`,
    questionStem: "The political commentator's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that anyone who owns an SUV cannot genuinely care about the environment" },
      { letter: "B", text: "attacks the senator's personal behavior rather than the merits of her policy positions" },
      { letter: "C", text: "presumes that all SUVs have equally high environmental impacts" },
      { letter: "D", text: "ignores the possibility that the senator's SUV use is necessary for her work" },
      { letter: "E", text: "fails to consider the senator's other environmentally friendly behaviors" },
    ],
    correctAnswer: "B",
    explanation: "This is a tu quoque (inconsistency) ad hominem. The commentator argues that because the senator's behavior is inconsistent with her stated views, her views should be dismissed. But a policy position's merit is independent of whether its advocate perfectly practices it.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Historical preservation laws restrict what property owners can do with designated historic buildings. While some argue these laws unfairly limit property rights, the laws serve an important public interest by maintaining community identity and architectural heritage. Since buildings, once demolished, cannot be replaced, preservation laws are a necessary means of protecting irreplaceable cultural resources.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Historic buildings contribute to community identity" },
      { letter: "B", text: "Property rights must sometimes be limited for the public good" },
      { letter: "C", text: "Preservation laws are necessary to protect irreplaceable cultural resources" },
      { letter: "D", text: "Demolished buildings cannot be replaced" },
      { letter: "E", text: "Some people believe preservation laws unfairly limit property rights" },
    ],
    correctAnswer: "C",
    explanation: "The conclusion is explicitly stated: 'preservation laws are a necessary means of protecting irreplaceable cultural resources.' The other statements serve as premises supporting this conclusion or context for the debate.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-038",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying language acquisition conclude that children must be exposed to language before age 7 to develop full native fluency. They base this on cases of children who were isolated from language during early childhood and later struggled to achieve fluency despite extensive instruction.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Children who learn a second language before age 7 typically achieve native-like pronunciation" },
      { letter: "B", text: "Brain imaging shows that language-processing areas develop most rapidly before age 7" },
      { letter: "C", text: "Some children raised in bilingual households achieve fluency in both languages" },
      { letter: "D", text: "Adults can learn to communicate effectively in new languages" },
      { letter: "E", text: "The isolated children in the studies often had other developmental challenges" },
    ],
    correctAnswer: "B",
    explanation: "Choice B provides neurological evidence for a critical period—the brain areas responsible for language develop most before age 7. This biological basis strengthens the claim that early exposure is necessary for full fluency.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-039",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Every employee who received a bonus last year exceeded their sales targets. All employees who exceeded their sales targets either received a bonus or a promotion. Davis exceeded his sales targets last year but was not promoted.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Davis was the only employee who received a bonus but not a promotion" },
      { letter: "B", text: "Some employees who received promotions did not exceed their sales targets" },
      { letter: "C", text: "Davis received a bonus last year" },
      { letter: "D", text: "All employees who received bonuses also received promotions" },
      { letter: "E", text: "Davis will receive a promotion next year" },
    ],
    correctAnswer: "C",
    explanation: "Davis exceeded sales targets. All who exceeded targets got either bonus or promotion. Davis was not promoted. Therefore, Davis must have received a bonus. This follows from the disjunction: if not one, then the other.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-040",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The new highway will either improve traffic flow or it won't affect traffic at all. Traffic studies show that the highway will definitely affect traffic patterns in the area. Therefore, the highway will improve traffic flow.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that traffic improvements might be temporary" },
      { letter: "B", text: "overlooks the possibility that the highway could make traffic flow worse" },
      { letter: "C", text: "assumes that all changes in traffic patterns are improvements" },
      { letter: "D", text: "relies on traffic studies without evaluating their methodology" },
      { letter: "E", text: "does not specify how traffic flow would be measured" },
    ],
    correctAnswer: "B",
    explanation: "The argument presents a false dichotomy: improve traffic OR no effect. But there's a third possibility—the highway could worsen traffic. The studies show it will affect traffic, but that doesn't mean the effect will be positive.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-041",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Installing solar panels on residential homes is environmentally beneficial. Manufacturing solar panels does produce some pollution, but over their 25-year lifespan, solar panels prevent far more pollution than their manufacture creates.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Solar panels are the most effective form of renewable energy" },
      { letter: "B", text: "The environmental impact of disposing of solar panels is not significant enough to offset their benefits" },
      { letter: "C", text: "All homeowners can afford to install solar panels" },
      { letter: "D", text: "Solar panels last exactly 25 years before requiring replacement" },
      { letter: "E", text: "Manufacturing processes for solar panels cannot be made cleaner" },
    ],
    correctAnswer: "B",
    explanation: "The argument considers manufacturing pollution but not disposal/end-of-life pollution. If disposal is highly polluting, the lifetime benefit calculation changes. The argument assumes disposal impact doesn't negate the benefits.",
    difficulty: "hard",
  },
  {
    id: "lr-bank53-042",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Business consultant: Companies should hire based primarily on skills and experience rather than academic degrees. Many successful entrepreneurs and executives never completed college, proving that formal education is not necessary for business success.`,
    questionStem: "Which one of the following, if true, most weakens the consultant's argument?",
    answerChoices: [
      { letter: "A", text: "Many companies require college degrees for entry-level positions" },
      { letter: "B", text: "The successful individuals without degrees often had exceptional talents or connections that compensated for their lack of formal education" },
      { letter: "C", text: "Some college programs include practical business experience through internships" },
      { letter: "D", text: "Academic degrees are easier to verify than claims about skills and experience" },
      { letter: "E", text: "The percentage of executives with college degrees has increased over time" },
    ],
    correctAnswer: "B",
    explanation: "The consultant generalizes from exceptional cases to all hiring decisions. Choice B points out that these successful individuals had compensating factors (talent, connections). Most candidates without degrees may lack these advantages, making the generalization inappropriate.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-043",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Art critic: Some dismiss abstract art as requiring no skill, claiming that anyone could splash paint on a canvas. But this is like saying anyone could write a symphony because anyone can make sounds. The fact that abstract art appears simple does not mean it is easy to create compelling abstract works.`,
    questionStem: "The art critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "citing empirical evidence that contradicts the opposing view" },
      { letter: "B", text: "showing that a principle, if applied consistently, leads to an unacceptable conclusion" },
      { letter: "C", text: "identifying an ambiguity in the opposing argument and exploiting it" },
      { letter: "D", text: "demonstrating that the opposing argument rests on a false premise" },
      { letter: "E", text: "using an analogy to reveal a flaw in the reasoning of those who dismiss abstract art" },
    ],
    correctAnswer: "E",
    explanation: "The critic uses an analogy to music: just as making sounds doesn't mean anyone can compose a symphony, splashing paint doesn't mean anyone can create compelling abstract art. The analogy exposes the flaw in reasoning from apparent simplicity to lack of skill.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar A: Mandatory minimum sentences are necessary to ensure consistency in criminal justice. Without them, similar crimes receive vastly different punishments depending on which judge presides over the case.

Legal scholar B: Mandatory minimums are unjust because they prevent judges from considering individual circumstances. A first-time offender and a repeat criminal may receive identical sentences despite their very different situations.`,
    questionStem: "The main point at issue between Legal scholar A and Legal scholar B is whether",
    answerChoices: [
      { letter: "A", text: "consistency in sentencing is currently lacking in the criminal justice system" },
      { letter: "B", text: "judges should have discretion to consider individual circumstances when sentencing" },
      { letter: "C", text: "first-time offenders deserve more lenient treatment than repeat offenders" },
      { letter: "D", text: "mandatory minimums are currently applied to all criminal offenses" },
      { letter: "E", text: "the criminal justice system treats all defendants fairly" },
    ],
    correctAnswer: "B",
    explanation: "Scholar A values consistency and sees judicial discretion as a problem. Scholar B values individualized justice and sees the lack of judicial discretion as the problem. Their fundamental disagreement is about whether judges should have discretion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-045",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Biologists have proposed that the extinction of large mammals in North America approximately 12,000 years ago was caused by human hunting rather than climate change. They note that this extinction coincided with the arrival of humans on the continent.`,
    questionStem: "Which one of the following, if true, most strengthens the biologists' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Climate change did occur in North America around 12,000 years ago" },
      { letter: "B", text: "Similar extinction events occurred in Australia and Madagascar shortly after humans arrived there" },
      { letter: "C", text: "Some large mammal species in North America survived the extinction event" },
      { letter: "D", text: "Early humans in North America also gathered plants for food" },
      { letter: "E", text: "Large mammals in Africa, where humans evolved, were less affected by extinctions" },
    ],
    correctAnswer: "B",
    explanation: "Choice B shows a repeated pattern: large mammal extinctions following human arrival across multiple continents. This pattern strengthens the causal link between human arrival and extinctions, as it would be unlikely for coincidental timing to occur repeatedly in different locations.",
    difficulty: "medium",
  },
  {
    id: "lr-bank53-046",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Health advocate: We should ban the sale of sugary drinks because they contribute to obesity. Other countries that have implemented sugar taxes have seen modest reductions in consumption. Since reduced consumption leads to lower obesity rates, a ban would be even more effective.`,
    questionStem: "The health advocate's reasoning is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that a complete ban would be proportionally more effective than a tax" },
      { letter: "B", text: "fails to consider other sources of sugar in people's diets" },
      { letter: "C", text: "ignores the economic impact on businesses that sell sugary drinks" },
      { letter: "D", text: "does not define what counts as a sugary drink" },
      { letter: "E", text: "presumes that obesity is caused solely by sugary drink consumption" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that because a tax causes modest reductions, a ban would cause larger reductions. But bans can lead to black markets, substitution with other unhealthy products, or consumer backlash. The relationship between policy strength and effectiveness may not be linear.",
    difficulty: "hard",
  },
  {
    id: "lr-bank53-047",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The company's customer satisfaction scores have declined for three consecutive quarters. Since customer satisfaction directly affects repeat purchases, the company should expect a decline in revenue in the coming year.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Customer satisfaction is the only factor that affects repeat purchases" },
      { letter: "B", text: "The decline in satisfaction scores reflects actual changes in customer sentiment" },
      { letter: "C", text: "The company cannot improve customer satisfaction in the coming year" },
      { letter: "D", text: "Revenue declines always follow satisfaction declines within one year" },
      { letter: "E", text: "New customers cannot compensate for the loss of repeat customers" },
    ],
    correctAnswer: "E",
    explanation: "The argument moves from reduced repeat purchases to revenue decline. But revenue could be maintained if new customer acquisition increases. The argument assumes that losing repeat customers will result in net revenue decline—i.e., new customers won't compensate.",
    difficulty: "hard",
  },
  {
    id: "lr-bank53-048",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Parents in the district argue that the new school start time of 7:00 AM is too early for teenagers. Research shows that adolescents' biological clocks make it difficult for them to fall asleep before 11:00 PM, and they need at least 8 hours of sleep for optimal functioning.`,
    questionStem: "Which one of the following, if true, most strengthens the parents' argument?",
    answerChoices: [
      { letter: "A", text: "Some teenagers are naturally early risers who function well in the morning" },
      { letter: "B", text: "Schools that have shifted to later start times report improved academic performance and reduced absenteeism" },
      { letter: "C", text: "Parents often need to leave for work before 7:00 AM" },
      { letter: "D", text: "Teenagers can adjust their sleep schedules if they avoid electronic devices before bed" },
      { letter: "E", text: "The school district changed the start time to accommodate bus schedules" },
    ],
    correctAnswer: "B",
    explanation: "Choice B provides direct evidence that later start times produce positive outcomes. This moves beyond the biological argument to show real-world results: better academic performance and attendance when schools start later.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-049",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy improves, then unemployment will decrease. If unemployment decreases, then consumer spending will increase. Therefore, if the economy improves, consumer spending will increase.`,
    questionStem: "Which one of the following arguments is most similar in its logical structure to the argument above?",
    answerChoices: [
      { letter: "A", text: "If it rains, the game will be cancelled. If the game is cancelled, tickets will be refunded. Therefore, if it rains, tickets will be refunded." },
      { letter: "B", text: "All roses are flowers. Some flowers are fragrant. Therefore, some roses are fragrant." },
      { letter: "C", text: "Either the train is late or the bus is late. The bus is not late. Therefore, the train is late." },
      { letter: "D", text: "If you study, you will pass. You studied. Therefore, you passed." },
      { letter: "E", text: "No reptiles are mammals. All snakes are reptiles. Therefore, no snakes are mammals." },
    ],
    correctAnswer: "A",
    explanation: "The original argument uses hypothetical syllogism: If A then B, if B then C, therefore if A then C. Choice A follows the same pattern: If rain then cancelled, if cancelled then refunded, therefore if rain then refunded.",
    difficulty: "easy",
  },
  {
    id: "lr-bank53-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `CEO: Our company's commitment to sustainability is proven by the fact that we use recycled paper in our offices. Critics who claim we are not environmentally responsible are simply wrong.`,
    questionStem: "The reasoning in the CEO's argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "treats a single action as sufficient evidence of comprehensive environmental responsibility" },
      { letter: "B", text: "assumes that using recycled paper has no environmental costs" },
      { letter: "C", text: "does not specify what percentage of the company's paper use involves recycled materials" },
      { letter: "D", text: "ignores the views of environmental experts on corporate sustainability" },
      { letter: "E", text: "fails to compare the company's practices to those of industry competitors" },
    ],
    correctAnswer: "A",
    explanation: "The CEO cites one minor environmental practice (recycled paper in offices) as proof of overall sustainability commitment. This is insufficient evidence—a company could use recycled paper while engaging in many environmentally harmful practices. The scope of the evidence doesn't match the scope of the conclusion.",
    difficulty: "easy",
  },
];
