// Logical Reasoning Questions Bank - Set 51
import { Question } from "../lsat-types";

export const lrQuestionsSet51: Question[] = [
  {
    id: "lr-bank51-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during the workday are more productive than those who work continuously. Therefore, companies should mandate that all employees take breaks every hour, as this will certainly increase overall productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that some employees may already take regular breaks" },
      { letter: "B", text: "assumes that what is true of voluntary behavior will also be true when that behavior is mandated" },
      { letter: "C", text: "relies on a study without providing details about its methodology" },
      { letter: "D", text: "overlooks the possibility that different types of work require different break schedules" },
      { letter: "E", text: "confuses correlation between breaks and productivity with causation" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that mandating breaks will have the same positive effect as voluntarily taking breaks. However, the study only showed a correlation with employees who chose to take breaks, not that forcing breaks on all employees would produce the same results.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martinez argues that classical music education should be required in all public schools because students who study classical music perform better academically. However, Professor Martinez herself studied classical music extensively, so her opinion on this matter cannot be trusted.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "presents an either/or choice when more options may exist" },
      { letter: "B", text: "attacks the person making the argument rather than addressing the argument itself" },
      { letter: "C", text: "assumes that correlation implies causation" },
      { letter: "D", text: "generalizes from an unrepresentative sample" },
      { letter: "E", text: "relies on ambiguous use of a key term" },
    ],
    correctAnswer: "B",
    explanation: "This is an ad hominem fallacy. The argument dismisses Professor Martinez's position solely because of her personal background in classical music, rather than addressing the merits of her claim about academic performance.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-003",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have discovered that ancient Roman buildings in coastal regions show significantly less structural damage than those built inland. Researchers hypothesize that the salt air from the ocean somehow helped preserve the concrete used in these buildings.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Coastal Roman buildings were typically constructed using the same techniques as inland buildings" },
      { letter: "B", text: "Laboratory tests show that Roman concrete exposed to salt compounds develops a crystalline structure that increases durability" },
      { letter: "C", text: "Many coastal Roman buildings were used for maritime commerce" },
      { letter: "D", text: "Inland Roman buildings were more frequently subject to earthquakes" },
      { letter: "E", text: "The Romans had extensive knowledge of construction techniques" },
    ],
    correctAnswer: "B",
    explanation: "This choice directly supports the hypothesis by providing a scientific mechanism explaining how salt air could preserve concrete. It shows that salt exposure creates beneficial structural changes in Roman concrete.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-004",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that installing more streetlights in the downtown area will reduce crime. They point to a study showing that neighborhoods with more streetlights have lower crime rates than neighborhoods with fewer streetlights.`,
    questionStem: "Which one of the following, if true, most weakens the city council's argument?",
    answerChoices: [
      { letter: "A", text: "Some crimes occur during daylight hours when streetlights are not in use" },
      { letter: "B", text: "Wealthier neighborhoods, which tend to have more streetlights, also have more private security and better-funded police patrols" },
      { letter: "C", text: "The cost of installing new streetlights is substantial" },
      { letter: "D", text: "Some residents have complained that bright streetlights disturb their sleep" },
      { letter: "E", text: "Other cities have also installed additional streetlights" },
    ],
    correctAnswer: "B",
    explanation: "This choice suggests that the correlation between streetlights and lower crime may be due to confounding factors. Wealthier neighborhoods may have lower crime due to increased security and police presence, not the streetlights themselves.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-005",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All of the candidates for the judicial appointment have extensive trial experience. Since trial experience is essential for making sound judicial decisions, the appointment committee will definitely select a qualified judge.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Trial experience is the only factor the committee will consider" },
      { letter: "B", text: "Trial experience is sufficient for making sound judicial decisions" },
      { letter: "C", text: "All candidates with trial experience are equally qualified" },
      { letter: "D", text: "The committee members themselves have trial experience" },
      { letter: "E", text: "Previous judicial appointments have been successful" },
    ],
    correctAnswer: "B",
    explanation: "The argument states that trial experience is essential (necessary) but then concludes the selected judge will be qualified, which requires assuming trial experience is also sufficient for qualification. The argument conflates necessary and sufficient conditions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-006",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical research has shown that moderate coffee consumption is associated with reduced risk of certain diseases. Coffee contains antioxidants that can protect cells from damage. However, excessive caffeine intake can cause anxiety and sleep disturbances. Therefore, while coffee can be part of a healthy diet, it should be consumed in moderation.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Coffee contains beneficial antioxidants" },
      { letter: "B", text: "Excessive caffeine causes health problems" },
      { letter: "C", text: "Medical research supports coffee consumption" },
      { letter: "D", text: "Coffee should be consumed in moderation as part of a healthy diet" },
      { letter: "E", text: "Moderate coffee consumption reduces disease risk" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is signaled by 'Therefore' and balances the benefits and risks mentioned in the premises. The other choices are supporting premises or partial conclusions that lead to the main point about moderation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-007",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The museum claims that its new exhibit represents diverse artistic perspectives. But every artist featured in the exhibit graduated from the same prestigious art school. A truly diverse exhibit would include artists from varied educational backgrounds. Therefore, the museum's claim about diversity is misleading.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing a counterexample to a general claim" },
      { letter: "B", text: "questioning the motives of those who made the claim" },
      { letter: "C", text: "showing that a claim is inconsistent with the evidence" },
      { letter: "D", text: "appealing to an authority on artistic matters" },
      { letter: "E", text: "demonstrating that the claim leads to a contradiction" },
    ],
    correctAnswer: "C",
    explanation: "The critic shows that the museum's claim of diversity is inconsistent with the fact that all featured artists share the same educational background. The argument demonstrates a gap between the claim and the actual evidence.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `No one has ever proven that extraterrestrial life does not exist. Therefore, extraterrestrial life must exist somewhere in the universe.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "treats the absence of evidence against a claim as proof of that claim" },
      { letter: "B", text: "relies on an ambiguous definition of extraterrestrial life" },
      { letter: "C", text: "assumes that what is possible must actually occur" },
      { letter: "D", text: "fails to consider alternative explanations" },
      { letter: "E", text: "draws a conclusion that is too narrow given the premises" },
    ],
    correctAnswer: "A",
    explanation: "This is an argument from ignorance (ad ignorantiam). The lack of proof that something does not exist is not valid evidence that it does exist. Absence of evidence is not evidence of absence, nor is it evidence of presence.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-009",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company claims that its new drug is more effective at treating migraines than existing medications. In clinical trials, 70% of patients who took the new drug reported significant pain relief within two hours, compared to 50% of patients who took a placebo.`,
    questionStem: "Which one of the following, if true, most strengthens the company's claim?",
    answerChoices: [
      { letter: "A", text: "The clinical trial included patients with varying severity of migraines" },
      { letter: "B", text: "When compared directly with the leading existing medication, the new drug showed a 25% higher rate of pain relief" },
      { letter: "C", text: "The new drug has fewer side effects than some existing medications" },
      { letter: "D", text: "Some patients in the trial had never taken migraine medication before" },
      { letter: "E", text: "The clinical trial was funded by the pharmaceutical company" },
    ],
    correctAnswer: "B",
    explanation: "The claim is that the new drug is more effective than existing medications. Choice B directly supports this by showing the new drug outperformed the leading existing medication in a head-to-head comparison.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Educational researchers argue that class size reduction is the most effective way to improve student performance. They cite studies showing that students in smaller classes score higher on standardized tests than students in larger classes.`,
    questionStem: "Which one of the following, if true, most weakens the researchers' argument?",
    answerChoices: [
      { letter: "A", text: "Reducing class sizes requires hiring additional teachers" },
      { letter: "B", text: "Teacher quality has a stronger correlation with student performance than class size does" },
      { letter: "C", text: "Some countries with large class sizes have high-performing students" },
      { letter: "D", text: "Smaller classes allow for more individual attention" },
      { letter: "E", text: "Class size reduction programs are expensive to implement" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims class size reduction is the 'most effective' way to improve performance. Choice B weakens this by suggesting that teacher quality is more strongly correlated with performance, challenging the claim about what is most effective.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-011",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The proposed legislation would ban the use of certain pesticides on farms within 50 miles of major water sources. Since the legislation aims to protect water quality, and the banned pesticides are known to contaminate groundwater, the legislation will successfully protect water quality in these areas.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "No other sources of water contamination exist in these areas" },
      { letter: "B", text: "Farmers will comply with the legislation" },
      { letter: "C", text: "The banned pesticides are the only pesticides that contaminate water" },
      { letter: "D", text: "All farms within 50 miles of water sources currently use the banned pesticides" },
      { letter: "E", text: "Water quality in these areas is currently poor" },
    ],
    correctAnswer: "B",
    explanation: "For the legislation to successfully protect water quality, farmers must actually comply with the ban. Without this assumption, the legislation could fail to achieve its goal even if the pesticides are harmful to water quality.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Hansen: Genetic modification of crops is essential for feeding the growing global population. Modified crops can produce higher yields and resist diseases that would otherwise devastate harvests.

Dr. Patel: The long-term ecological consequences of genetic modification are unknown. We should focus on sustainable farming practices rather than technological solutions that may create unforeseen problems.`,
    questionStem: "Dr. Hansen and Dr. Patel disagree about whether",
    answerChoices: [
      { letter: "A", text: "the global population is growing" },
      { letter: "B", text: "genetically modified crops can produce higher yields" },
      { letter: "C", text: "genetic modification is the appropriate approach to addressing food production challenges" },
      { letter: "D", text: "sustainable farming practices exist" },
      { letter: "E", text: "some crops are susceptible to disease" },
    ],
    correctAnswer: "C",
    explanation: "Dr. Hansen advocates for genetic modification as essential, while Dr. Patel suggests focusing on sustainable practices instead. Their disagreement centers on whether genetic modification is the right approach to food production challenges.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All members of the city council voted for the new zoning law. Janet is a member of the city council. Therefore, Janet voted for the new zoning law.`,
    questionStem: "Which one of the following arguments is most similar in its pattern of reasoning to the argument above?",
    answerChoices: [
      { letter: "A", text: "All roses are flowers. This plant is a flower. Therefore, this plant is a rose." },
      { letter: "B", text: "All licensed physicians have medical degrees. Dr. Smith has a medical degree. Therefore, Dr. Smith is a licensed physician." },
      { letter: "C", text: "All employees at the company received bonuses. Marcus is an employee at the company. Therefore, Marcus received a bonus." },
      { letter: "D", text: "Some students passed the exam. John is a student. Therefore, John passed the exam." },
      { letter: "E", text: "No reptiles are mammals. This animal is a mammal. Therefore, this animal is not a reptile." },
    ],
    correctAnswer: "C",
    explanation: "The original argument has the form: All A are B. X is A. Therefore, X is B. Choice C follows the same valid pattern: All employees received bonuses, Marcus is an employee, therefore Marcus received a bonus.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-014",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The mayor claims that the new public transit system has been a success because ridership has increased by 15% since its launch. However, during the same period, gas prices rose dramatically, forcing many people to seek alternatives to driving. The increase in ridership may simply reflect people's response to higher gas prices rather than any merit of the transit system itself.`,
    questionStem: "The reasoning above is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "attacks the mayor's character rather than addressing the argument" },
      { letter: "B", text: "assumes that the transit system has no merit" },
      { letter: "C", text: "fails to consider that both factors could contribute to increased ridership" },
      { letter: "D", text: "ignores the possibility that gas prices will decrease in the future" },
      { letter: "E", text: "relies on a biased source for its data about ridership" },
    ],
    correctAnswer: "C",
    explanation: "The argument commits an either/or fallacy by suggesting the increase is due to gas prices rather than the transit system's merit. Both factors could contribute to the increase; they are not mutually exclusive explanations.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Anthropologists studying an ancient civilization discovered that their calendar was based on lunar cycles. Artifacts found at the site include carved stones depicting various moon phases. The anthropologists conclude that this civilization used these carved stones for astronomical observations.`,
    questionStem: "Which one of the following, if true, most strengthens the anthropologists' conclusion?",
    answerChoices: [
      { letter: "A", text: "Other ancient civilizations also used lunar-based calendars" },
      { letter: "B", text: "The carved stones were found positioned in locations with clear views of the night sky" },
      { letter: "C", text: "The civilization had advanced mathematical knowledge" },
      { letter: "D", text: "Moon phase carvings were common decorative elements in ancient art" },
      { letter: "E", text: "The civilization's written records have not yet been fully translated" },
    ],
    correctAnswer: "B",
    explanation: "Finding the stones positioned with clear sky views supports the conclusion that they were used for astronomical observations rather than merely decorative or ceremonial purposes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-016",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A business consultant argues that companies should eliminate their dress codes because employees at companies without dress codes report higher job satisfaction. High job satisfaction leads to increased productivity, so eliminating dress codes will make companies more productive.`,
    questionStem: "Which one of the following, if true, most weakens the consultant's argument?",
    answerChoices: [
      { letter: "A", text: "Some employees prefer having clear guidelines about appropriate workplace attire" },
      { letter: "B", text: "Companies without dress codes tend to be in creative industries where other factors contribute more significantly to job satisfaction" },
      { letter: "C", text: "Implementing a dress code change requires time and resources" },
      { letter: "D", text: "Job satisfaction can be measured in various ways" },
      { letter: "E", text: "Some companies have very strict dress codes" },
    ],
    correctAnswer: "B",
    explanation: "This suggests that the correlation between no dress code and higher satisfaction may be due to industry type and other factors, not the dress code policy itself. Eliminating dress codes in other types of companies may not produce the same results.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-017",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The university should not cut funding for the philosophy department. Philosophy courses teach critical thinking skills, and students who develop strong critical thinking skills are more successful in their careers. Therefore, maintaining philosophy department funding benefits students' future career success.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "critical thinking skills cannot be developed through other courses" },
      { letter: "B", text: "all philosophy students become successful in their careers" },
      { letter: "C", text: "the philosophy department's courses effectively teach critical thinking skills" },
      { letter: "D", text: "career success is the primary goal of university education" },
      { letter: "E", text: "the university has sufficient funding for all departments" },
    ],
    correctAnswer: "C",
    explanation: "The argument claims philosophy courses teach critical thinking, which leads to career success. For this chain of reasoning to work, the philosophy department's courses must actually be effective at teaching these skills.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-018",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All licensed attorneys in this state must complete 15 hours of continuing legal education each year. Attorneys who fail to complete this requirement have their licenses suspended. Sarah's law license has not been suspended, and she has been practicing law in this state for ten years.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Sarah has completed at least 150 hours of continuing legal education" },
      { letter: "B", text: "Sarah has never failed to complete her continuing education requirement" },
      { letter: "C", text: "Sarah is one of the most experienced attorneys in the state" },
      { letter: "D", text: "All attorneys in the state complete more than the minimum required hours" },
      { letter: "E", text: "Continuing legal education improves the quality of legal services" },
    ],
    correctAnswer: "B",
    explanation: "Since failure to complete the requirement results in suspension, and Sarah's license has not been suspended, she must have completed the requirement every year. If she had ever failed, her license would have been suspended.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-019",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Senator Williams opposes the proposed environmental regulation, claiming it will harm businesses. But Senator Williams has received substantial campaign contributions from oil companies. Clearly, the proposed regulation must be good for the environment.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "concludes that a regulation is beneficial simply because someone with a conflict of interest opposes it" },
      { letter: "B", text: "assumes all campaign contributions influence political positions" },
      { letter: "C", text: "fails to define what constitutes a substantial contribution" },
      { letter: "D", text: "ignores the possibility that the regulation could both harm businesses and help the environment" },
      { letter: "E", text: "attacks Senator Williams personally without addressing her arguments" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits the fallacy of assuming that because someone with questionable motives opposes something, that thing must be good. Even if Senator Williams has a conflict of interest, the regulation's actual merits are not established by her opposition.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-020",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers believe that the decline in bee populations is primarily caused by the widespread use of neonicotinoid pesticides. They note that bee population declines have coincided with increased use of these pesticides over the past two decades.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Neonicotinoid pesticides are effective at controlling crop-damaging insects" },
      { letter: "B", text: "Bee populations in regions where neonicotinoid use has been banned have begun to recover" },
      { letter: "C", text: "Climate change has also affected bee habitats during the same time period" },
      { letter: "D", text: "Some beekeepers have reported stable bee populations" },
      { letter: "E", text: "Other types of pesticides have been used for longer periods without similar effects" },
    ],
    correctAnswer: "B",
    explanation: "If bee populations recover when neonicotinoids are removed, this strongly supports the causal connection between these pesticides and bee decline. It suggests that eliminating the suspected cause reverses the effect.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A fitness magazine claims that high-intensity interval training (HIIT) is superior to traditional endurance training for improving cardiovascular health. The magazine cites a study showing that participants who did HIIT three times a week for eight weeks showed greater improvements in cardiovascular markers than those who did traditional endurance training.`,
    questionStem: "Which one of the following, if true, most weakens the magazine's claim?",
    answerChoices: [
      { letter: "A", text: "HIIT workouts are typically shorter in duration than endurance training sessions" },
      { letter: "B", text: "The HIIT group in the study exercised for twice as many total minutes per week as the endurance group" },
      { letter: "C", text: "Some elite athletes incorporate both HIIT and endurance training" },
      { letter: "D", text: "HIIT can be more physically demanding than endurance training" },
      { letter: "E", text: "The study was published in a peer-reviewed journal" },
    ],
    correctAnswer: "B",
    explanation: "If the HIIT group exercised for twice as many minutes, the comparison is unfair. The superior results might be due to more exercise time rather than the type of training, undermining the claim that HIIT is inherently superior.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-022",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should invest in building more bike lanes because cities with extensive bike lane networks have lower rates of traffic congestion. Reducing traffic congestion would decrease commute times and improve air quality for all residents.`,
    questionStem: "Which one of the following is an assumption on which the argument depends?",
    answerChoices: [
      { letter: "A", text: "Building bike lanes is less expensive than other traffic reduction measures" },
      { letter: "B", text: "A significant number of residents would use bike lanes if they were available" },
      { letter: "C", text: "Other cities have successfully reduced congestion through bike lanes" },
      { letter: "D", text: "The city currently has no bike lanes" },
      { letter: "E", text: "Air quality is a concern for most city residents" },
    ],
    correctAnswer: "B",
    explanation: "For bike lanes to reduce congestion, people must actually use them. If residents would not bike even with lanes available, building them would not reduce car traffic or achieve the stated benefits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-023",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some ethicists argue that artificial intelligence should never be used to make life-or-death medical decisions because machines cannot truly understand human values. However, studies show that AI diagnostic systems are often more accurate than human physicians. Moreover, human doctors are subject to fatigue and bias. Given these considerations, AI should be allowed to play a significant role in medical diagnosis, though final decisions should remain with human physicians.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "AI diagnostic systems are more accurate than human physicians" },
      { letter: "B", text: "Human doctors are subject to fatigue and bias" },
      { letter: "C", text: "Machines cannot truly understand human values" },
      { letter: "D", text: "AI should play a significant role in diagnosis with humans making final decisions" },
      { letter: "E", text: "Some ethicists oppose AI in medical decisions" },
    ],
    correctAnswer: "D",
    explanation: "The conclusion follows 'Given these considerations' and represents a balanced position that acknowledges the benefits of AI while preserving human oversight. The other choices are premises supporting this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-024",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The government claims that lowering taxes will stimulate economic growth because businesses will have more money to invest. But this same government lowered taxes five years ago, and economic growth actually slowed during the following year. So there is no reason to believe that lowering taxes now will stimulate growth.`,
    questionStem: "The economist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "using a past instance to cast doubt on a predicted outcome" },
      { letter: "B", text: "demonstrating that the government's reasoning contains a logical contradiction" },
      { letter: "C", text: "showing that the government has a history of making false claims" },
      { letter: "D", text: "appealing to expert opinion on economic matters" },
      { letter: "E", text: "establishing that tax cuts always lead to economic decline" },
    ],
    correctAnswer: "A",
    explanation: "The economist cites a historical precedent where the predicted outcome did not occur to challenge the current prediction. The past failure of tax cuts to stimulate growth is used to question whether they will do so now.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-025",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every successful entrepreneur I know wakes up before 6 AM. Therefore, if you want to be a successful entrepreneur, you should start waking up before 6 AM.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on too small a sample of entrepreneurs" },
      { letter: "B", text: "assumes that a characteristic shared by successful entrepreneurs is a cause of their success" },
      { letter: "C", text: "fails to consider entrepreneurs who are not successful" },
      { letter: "D", text: "ignores the role of luck in entrepreneurial success" },
      { letter: "E", text: "assumes all entrepreneurs have the same daily schedules" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the correlation-causation fallacy. Just because successful entrepreneurs share this trait does not mean early rising causes success. It could be coincidental or the result of other factors that also lead to success.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-026",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A nonprofit organization argues that teaching financial literacy in high schools will reduce personal debt among young adults. Currently, many young adults struggle with credit card debt and student loans because they lack basic understanding of interest rates and budgeting.`,
    questionStem: "Which one of the following, if true, most strengthens the organization's argument?",
    answerChoices: [
      { letter: "A", text: "Many high schools already teach some form of economics" },
      { letter: "B", text: "States that have implemented mandatory financial literacy courses have seen measurably lower rates of young adult debt" },
      { letter: "C", text: "Financial literacy can be taught through various methods" },
      { letter: "D", text: "Some young adults learn about finance from their parents" },
      { letter: "E", text: "Credit card companies target young adults with promotional offers" },
    ],
    correctAnswer: "B",
    explanation: "This provides direct empirical evidence that financial literacy education achieves the predicted outcome of reducing debt. It shows that the proposed solution has worked in practice.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-027",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A real estate developer argues that building a new shopping mall will revitalize the downtown area. The developer points out that similar malls in other cities have attracted new businesses and residents to previously declining neighborhoods.`,
    questionStem: "Which one of the following, if true, most weakens the developer's argument?",
    answerChoices: [
      { letter: "A", text: "The proposed mall would include both retail stores and restaurants" },
      { letter: "B", text: "The downtown area already has several vacant commercial buildings" },
      { letter: "C", text: "The cities cited by the developer had larger populations and stronger economies than this city" },
      { letter: "D", text: "Building the mall would require significant public investment" },
      { letter: "E", text: "Some residents oppose the mall for aesthetic reasons" },
    ],
    correctAnswer: "C",
    explanation: "If the comparison cities were fundamentally different in key economic respects, the success of malls there may not predict success here. Different population and economic conditions undermine the analogy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new exhibition has received mixed reviews from critics. Nevertheless, the exhibition will likely be popular with the general public because the last three exhibitions that received mixed critical reviews attracted record numbers of visitors.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Critical opinion is inversely related to public interest" },
      { letter: "B", text: "The new exhibition is similar enough to the previous exhibitions for the pattern to continue" },
      { letter: "C", text: "The museum's marketing for this exhibition is as effective as for previous exhibitions" },
      { letter: "D", text: "Visitors do not read critical reviews before attending exhibitions" },
      { letter: "E", text: "Mixed reviews generate more publicity than positive reviews" },
    ],
    correctAnswer: "B",
    explanation: "The argument uses past exhibitions as precedent, assuming the new exhibition is comparable enough that the pattern of public response will repeat. Without this assumption, past results cannot predict future outcomes.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-029",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Attorney Chen: Mandatory minimum sentences ensure consistent punishment for crimes and prevent judges from giving overly lenient sentences based on personal bias.

Attorney Williams: Mandatory minimums remove judicial discretion needed to account for individual circumstances. A first-time offender who made a momentary lapse in judgment should not receive the same sentence as a repeat offender.`,
    questionStem: "The point at issue between Attorney Chen and Attorney Williams is whether",
    answerChoices: [
      { letter: "A", text: "judges sometimes exhibit personal bias in sentencing" },
      { letter: "B", text: "judicial discretion in sentencing is valuable" },
      { letter: "C", text: "first-time offenders exist in the criminal justice system" },
      { letter: "D", text: "sentences should be consistent across similar crimes" },
      { letter: "E", text: "mandatory minimums are constitutional" },
    ],
    correctAnswer: "B",
    explanation: "Chen views removing judicial discretion as a benefit (prevents bias), while Williams views it as a problem (prevents appropriate consideration of circumstances). They directly disagree about whether judicial discretion is valuable.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-030",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the committee approves the proposal, then the project will receive funding. The project did not receive funding. Therefore, the committee did not approve the proposal.`,
    questionStem: "The pattern of reasoning in which one of the following arguments most closely parallels that in the argument above?",
    answerChoices: [
      { letter: "A", text: "If it rains, the ground will be wet. The ground is wet. Therefore, it rained." },
      { letter: "B", text: "If the alarm sounds, there is a fire. There is no fire. Therefore, the alarm did not sound." },
      { letter: "C", text: "All cats are mammals. Fluffy is a cat. Therefore, Fluffy is a mammal." },
      { letter: "D", text: "If you study, you will pass. You passed. Therefore, you studied." },
      { letter: "E", text: "Some birds can fly. Penguins are birds. Therefore, penguins might be able to fly." },
    ],
    correctAnswer: "B",
    explanation: "The original uses modus tollens: If P then Q; not Q; therefore not P. Choice B follows the same pattern: If alarm then fire; no fire; therefore no alarm. This is valid deductive reasoning.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The governor argues that the state should invest more in renewable energy because our state has abundant sunshine and wind. However, neighboring states have already made similar investments and have seen only modest returns. Until the governor can explain why our state would achieve better results, we should be skeptical of this proposal.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to acknowledge that the governor may have evidence beyond what is stated" },
      { letter: "B", text: "assumes that neighboring states' conditions are identical to this state's conditions" },
      { letter: "C", text: "ignores the long-term benefits of renewable energy investment" },
      { letter: "D", text: "relies on an appeal to the authority of neighboring states" },
      { letter: "E", text: "presumes that modest returns are not worthwhile" },
    ],
    correctAnswer: "B",
    explanation: "The argument compares this state to neighboring states without considering that the state's abundant sunshine and wind might make its conditions more favorable for renewable energy than those of its neighbors.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art historians have attributed a recently discovered painting to the Renaissance master Vermeer based on its style and technique. However, some experts remain skeptical because no documentation exists linking Vermeer to this work.`,
    questionStem: "Which one of the following, if true, most strengthens the attribution to Vermeer?",
    answerChoices: [
      { letter: "A", text: "Many authentic Vermeer paintings were undocumented during his lifetime" },
      { letter: "B", text: "The painting depicts a subject matter common in the Renaissance period" },
      { letter: "C", text: "Chemical analysis shows the pigments used were available during Vermeer's era" },
      { letter: "D", text: "Some art historians specialize in detecting forgeries" },
      { letter: "E", text: "Vermeer was not well-known during his lifetime" },
    ],
    correctAnswer: "A",
    explanation: "If many authentic Vermeers lack documentation, then the absence of documentation for this painting does not count against its authenticity. This directly addresses the skeptics' concern about missing records.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-033",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A nutritionist claims that eating breakfast improves academic performance in children. She cites studies showing that children who eat breakfast regularly score higher on tests than children who skip breakfast.`,
    questionStem: "Which one of the following, if true, most weakens the nutritionist's claim?",
    answerChoices: [
      { letter: "A", text: "The studies were conducted in multiple countries" },
      { letter: "B", text: "Children who eat breakfast regularly tend to come from homes with greater parental involvement and educational resources" },
      { letter: "C", text: "Breakfast is considered the most important meal of the day by many nutrition experts" },
      { letter: "D", text: "Some children prefer to eat larger lunches instead of breakfast" },
      { letter: "E", text: "Test scores are influenced by many factors" },
    ],
    correctAnswer: "B",
    explanation: "This suggests a confounding variable: parental involvement and resources. The correlation between breakfast and test scores might be due to these factors rather than breakfast itself, weakening the causal claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The council should approve the new community garden project. Community gardens have been shown to increase property values, promote social interaction among neighbors, and provide fresh produce. Our neighborhood would greatly benefit from such amenities.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "the council has approved similar projects in the past" },
      { letter: "B", text: "community gardens are the only way to achieve these benefits" },
      { letter: "C", text: "residents of this neighborhood would participate in the community garden" },
      { letter: "D", text: "property values in the neighborhood are currently low" },
      { letter: "E", text: "the council values social interaction among neighbors" },
    ],
    correctAnswer: "C",
    explanation: "For the garden to provide the stated benefits to this neighborhood, residents must actually participate. Without participation, the garden would not promote social interaction or provide produce to residents.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Critics of space exploration argue that the money would be better spent addressing problems on Earth. While this concern has merit, space exploration has produced numerous technological innovations that benefit everyday life, from medical devices to communication systems. Furthermore, the inspiration provided by space exploration motivates young people to pursue careers in science and engineering. The benefits of space exploration thus extend far beyond the missions themselves, justifying continued investment.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Critics of space exploration believe money should address Earth's problems" },
      { letter: "B", text: "Space exploration produces technological innovations" },
      { letter: "C", text: "Continued investment in space exploration is justified" },
      { letter: "D", text: "Space exploration inspires young people" },
      { letter: "E", text: "The benefits of space exploration extend beyond missions" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is the final statement that continued investment is justified. All other points about technological benefits and inspiration are premises supporting this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-036",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Many people believe that violent video games cause aggressive behavior in children. However, the rate of youth violence has actually declined over the past two decades, precisely during the period when violent video games became increasingly popular and widespread. This suggests that violent video games do not have the harmful effect many attribute to them.`,
    questionStem: "The argument counters the popular belief by",
    answerChoices: [
      { letter: "A", text: "citing expert opinion on child psychology" },
      { letter: "B", text: "pointing to empirical data that contradicts the expected outcome" },
      { letter: "C", text: "showing that the belief is based on a logical fallacy" },
      { letter: "D", text: "demonstrating that violent video games have positive effects" },
      { letter: "E", text: "questioning the motives of those who hold the popular belief" },
    ],
    correctAnswer: "B",
    explanation: "The argument presents empirical data (declining youth violence) that contradicts what one would expect if the popular belief were true (that violent games cause aggression). If games caused violence, we would expect violence to increase as games spread.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-037",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The candidate for mayor promises to reduce crime by 50% if elected. But this candidate has never held public office before and has no experience in law enforcement. Since the candidate lacks relevant experience, voters should not believe that the crime reduction goal can be achieved.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that the candidate might hire experienced advisors" },
      { letter: "B", text: "assumes that only candidates with law enforcement experience can reduce crime" },
      { letter: "C", text: "does not provide evidence about current crime rates" },
      { letter: "D", text: "appeals to the voters' emotions rather than reason" },
      { letter: "E", text: "ignores other qualifications the candidate might possess" },
    ],
    correctAnswer: "A",
    explanation: "The argument overlooks that a mayor does not personally fight crime but rather oversees and appoints experienced officials. The candidate could achieve results by hiring qualified professionals, making personal experience less relevant.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-038",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying ancient Roman trade routes believe that a newly discovered shipwreck in the Mediterranean was a merchant vessel carrying goods from Egypt to Rome. The ship's cargo includes amphorae of a style commonly used for Egyptian grain.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' belief?",
    answerChoices: [
      { letter: "A", text: "Roman merchant ships often traveled between Egypt and Rome" },
      { letter: "B", text: "Analysis of wood samples from the ship shows it was constructed using timber native to Egypt" },
      { letter: "C", text: "The amphorae are well-preserved despite centuries underwater" },
      { letter: "D", text: "Other shipwrecks from the same period have been found in the Mediterranean" },
      { letter: "E", text: "Ancient writers described trade between Egypt and Rome" },
    ],
    correctAnswer: "B",
    explanation: "If the ship was built with Egyptian timber, this provides physical evidence supporting its Egyptian origin, strengthening the belief that it was traveling from Egypt to Rome.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-039",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A political analyst argues that negative campaign advertisements are effective because candidates who spend more on negative ads tend to win elections. The analyst recommends that candidates allocate more of their budget to negative advertising.`,
    questionStem: "Which one of the following, if true, most weakens the analyst's recommendation?",
    answerChoices: [
      { letter: "A", text: "Some voters claim they dislike negative advertisements" },
      { letter: "B", text: "Candidates who are already ahead in polls tend to have more funds available for all types of advertising" },
      { letter: "C", text: "Negative advertisements have been used in campaigns for over a century" },
      { letter: "D", text: "Television stations charge the same rates for positive and negative ads" },
      { letter: "E", text: "Some successful candidates refuse to run any negative advertisements" },
    ],
    correctAnswer: "B",
    explanation: "This suggests reverse causation: candidates may win and spend more on negative ads because they are already winning, not the other way around. Being ahead in polls leads to more funding, not negative ads leading to victory.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-040",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The library will either be renovated or relocated next year. If the library is renovated, it will be closed for at least three months. If the library is relocated, its entire collection will need to be packed and transported. The city council has announced that the library's collection will not be packed and transported next year.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "The library will remain open next year" },
      { letter: "B", text: "The library will be renovated and closed for at least three months" },
      { letter: "C", text: "The city council prefers renovation to relocation" },
      { letter: "D", text: "The library's collection is too large to transport" },
      { letter: "E", text: "The city council will change its decision about the library" },
    ],
    correctAnswer: "B",
    explanation: "Since the library will either be renovated or relocated, and relocation requires packing/transporting (which the council says won't happen), the library must be renovated. Renovation means closure for at least three months.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-041",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The defendant could not have committed the crime because he claims he was at home sleeping at the time of the robbery. His wife confirmed that he was home that night. Since his whereabouts are accounted for, he must be innocent.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "relies solely on testimony from sources who have an interest in the defendant being found innocent" },
      { letter: "B", text: "fails to establish that the defendant had no prior criminal record" },
      { letter: "C", text: "assumes that all robberies occur at night" },
      { letter: "D", text: "does not specify the exact time of the robbery" },
      { letter: "E", text: "ignores the possibility of accomplices" },
    ],
    correctAnswer: "A",
    explanation: "Both the defendant and his wife have obvious reasons to provide a false alibi. The argument uncritically accepts their testimony without considering their bias or seeking independent verification.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-042",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Reyes: Animals should have legal rights similar to humans because they can experience pain and suffering. The capacity to suffer, not species membership, should be the basis for moral consideration.

Dr. Foster: Legal rights require the capacity to understand and exercise those rights. Animals cannot participate in legal systems or fulfill civic duties, so they cannot meaningfully hold legal rights.`,
    questionStem: "Dr. Reyes and Dr. Foster disagree over",
    answerChoices: [
      { letter: "A", text: "whether animals can experience pain" },
      { letter: "B", text: "whether legal rights should be extended to animals" },
      { letter: "C", text: "whether humans have moral duties toward animals" },
      { letter: "D", text: "whether species membership is morally relevant" },
      { letter: "E", text: "whether animals participate in legal systems" },
    ],
    correctAnswer: "B",
    explanation: "Dr. Reyes argues animals should have legal rights, while Dr. Foster argues they cannot meaningfully hold them. This is their central disagreement, despite possibly agreeing on factual matters about animal capabilities.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-043",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some medications cause drowsiness. Anything that causes drowsiness should not be taken before operating heavy machinery. Therefore, some medications should not be taken before operating heavy machinery.`,
    questionStem: "Which one of the following arguments exhibits a pattern of reasoning most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All trees are plants. Some plants are flowering. Therefore, some trees are flowering." },
      { letter: "B", text: "Some foods contain allergens. Foods containing allergens must be labeled. Therefore, some foods must be labeled." },
      { letter: "C", text: "No reptiles are mammals. All dogs are mammals. Therefore, no dogs are reptiles." },
      { letter: "D", text: "Most students study regularly. Regular study leads to good grades. Therefore, most students get good grades." },
      { letter: "E", text: "All doctors are professionals. Some professionals are overpaid. Therefore, some doctors are overpaid." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow the pattern: Some A are B. All B are C. Therefore, some A are C. The original: Some meds cause drowsiness, drowsiness-causers shouldn't be used before machinery, so some meds shouldn't be used. Choice B follows the identical pattern.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-044",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The company's profits have increased every quarter for the past two years. Since the current management team took over three years ago, it is clear that the management team's strategies are responsible for this success.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that a trend will continue indefinitely" },
      { letter: "B", text: "fails to account for economic conditions that might have contributed to the profit increase" },
      { letter: "C", text: "does not specify the exact strategies implemented by management" },
      { letter: "D", text: "ignores the possibility that profits were declining before the current management took over" },
      { letter: "E", text: "relies on quarterly rather than annual profit data" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits post hoc ergo propter hoc fallacy. The profit increase coinciding with the management team's tenure does not prove causation; external factors like favorable economic conditions could be responsible.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-045",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Environmental scientists predict that the local river ecosystem will collapse within five years if current pollution levels continue. They base this prediction on declining fish populations and increasing algae blooms, both indicators of ecosystem stress.`,
    questionStem: "Which one of the following, if true, most strengthens the scientists' prediction?",
    answerChoices: [
      { letter: "A", text: "Local residents have noticed changes in the river's appearance" },
      { letter: "B", text: "Similar pollution levels in comparable river ecosystems elsewhere have led to collapse within the predicted timeframe" },
      { letter: "C", text: "The scientists have studied this river for many years" },
      { letter: "D", text: "Government agencies are aware of the pollution problem" },
      { letter: "E", text: "Some fish species are more resilient to pollution than others" },
    ],
    correctAnswer: "B",
    explanation: "Evidence that similar conditions led to collapse in comparable ecosystems supports the prediction through analogy. If the same causes produced the same effects elsewhere, the prediction is more credible.",
    difficulty: "easy",
  },
  {
    id: "lr-bank51-046",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A sociologist claims that social media use is the primary cause of increased loneliness among teenagers. She points to surveys showing that teenagers who spend more time on social media report feeling lonelier than those who use it less frequently.`,
    questionStem: "Which one of the following, if true, most weakens the sociologist's claim?",
    answerChoices: [
      { letter: "A", text: "Some teenagers use social media to stay connected with friends" },
      { letter: "B", text: "Lonely teenagers may turn to social media as a substitute for in-person interaction" },
      { letter: "C", text: "Social media platforms have billions of users worldwide" },
      { letter: "D", text: "Loneliness can have negative health consequences" },
      { letter: "E", text: "Previous generations also experienced teenage loneliness" },
    ],
    correctAnswer: "B",
    explanation: "This suggests reverse causation: loneliness may cause social media use rather than social media causing loneliness. Lonely teenagers might seek out social media as a coping mechanism, reversing the claimed causal direction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-047",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The town should not build the proposed sports complex because the construction costs would require raising property taxes. Any increase in property taxes will cause some residents to move away, and the town cannot afford to lose residents.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "the sports complex would not generate revenue to offset construction costs" },
      { letter: "B", text: "property taxes are the only way to fund the sports complex" },
      { letter: "C", text: "most residents oppose the sports complex" },
      { letter: "D", text: "the sports complex would not attract new residents to the town" },
      { letter: "E", text: "property taxes have never been raised before" },
    ],
    correctAnswer: "D",
    explanation: "The argument claims the town cannot afford to lose residents. But if the sports complex attracted new residents, this could offset or exceed any departures. The argument assumes the complex would not have this attracting effect.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-048",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Archaeological evidence shows that ancient peoples in this region traded extensively with distant civilizations. Trade goods from thousands of miles away have been found at local sites. Such long-distance trade requires sophisticated logistics, including reliable transportation and trusted intermediaries. Consequently, these ancient peoples must have developed complex social and economic institutions far earlier than historians previously believed.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Ancient peoples traded with distant civilizations" },
      { letter: "B", text: "Long-distance trade requires sophisticated logistics" },
      { letter: "C", text: "These ancient peoples developed complex institutions earlier than previously thought" },
      { letter: "D", text: "Trade goods from far away have been found at local sites" },
      { letter: "E", text: "Historians' previous beliefs about these people were wrong" },
    ],
    correctAnswer: "C",
    explanation: "The conclusion follows 'Consequently' and represents the ultimate inference drawn from the archaeological evidence and the requirements of long-distance trade. The other choices are premises supporting this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank51-049",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Opponent of the policy: The proposed carbon tax will burden low-income households disproportionately because they spend a higher percentage of their income on energy costs. Any policy that harms the most vulnerable members of society is unjust. Therefore, the carbon tax should not be implemented.

Proponent of the policy: The carbon tax proposal includes provisions to rebate all revenue to households on a per-capita basis, which would actually result in net financial gains for low-income households.`,
    questionStem: "The proponent responds to the opponent by",
    answerChoices: [
      { letter: "A", text: "questioning the opponent's expertise on economic matters" },
      { letter: "B", text: "arguing that environmental benefits outweigh financial harms" },
      { letter: "C", text: "providing information that undermines a premise of the opponent's argument" },
      { letter: "D", text: "accepting the opponent's conclusion but disputing its significance" },
      { letter: "E", text: "demonstrating that the opponent's reasoning contains a logical error" },
    ],
    correctAnswer: "C",
    explanation: "The opponent's argument depends on the premise that the tax will harm low-income households. The proponent challenges this premise by explaining that revenue rebates would actually benefit these households.",
    difficulty: "hard",
  },
  {
    id: "lr-bank51-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every member of the chess club voted to hold the tournament on Saturday. Therefore, the chess club voted to hold the tournament on Saturday. And since the chess club voted for it, every member must support the decision.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "confuses a decision made by individual members with a decision that each member continues to support" },
      { letter: "B", text: "fails to consider that some members may not attend the tournament" },
      { letter: "C", text: "assumes that all chess club members are equally enthusiastic about chess" },
      { letter: "D", text: "does not establish that the vote was conducted fairly" },
      { letter: "E", text: "ignores the possibility that some members abstained from voting" },
    ],
    correctAnswer: "A",
    explanation: "The argument illicitly moves from 'everyone voted for X at a particular time' to 'the club decided X' to 'everyone still supports X.' Members might have voted for Saturday as a compromise while preferring another day, or might have changed their minds since voting.",
    difficulty: "hard",
  },
];
