// Logical Reasoning Questions Bank - Set 42
import { Question } from "../lsat-types";

export const lrQuestionsSet42: Question[] = [
  {
    id: "lr-bank42-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A city council member argued that the new traffic law has been effective because traffic accidents have decreased by 15% since the law was enacted. However, during the same period, the city also implemented improved street lighting, expanded public transportation, and launched a major road repair initiative.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider whether the decrease in accidents is permanent" },
      { letter: "B", text: "overlooks other factors that could have contributed to the decrease in accidents" },
      { letter: "C", text: "assumes that all traffic laws are equally effective" },
      { letter: "D", text: "relies on statistics that have not been independently verified" },
      { letter: "E", text: "does not define what counts as a traffic accident" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the fallacy of ignoring alternative explanations. While the council member attributes the decrease in accidents solely to the new traffic law, several other changes occurred simultaneously (improved lighting, expanded public transit, road repairs) that could equally explain the reduction. The argument fails to rule out these competing causes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martinez claims that her teaching method is superior because her students consistently score higher on standardized tests than students taught by other methods. But Professor Martinez only teaches honors classes, while other professors teach a mix of honors and regular classes.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that teaching methods may vary in effectiveness across different subjects" },
      { letter: "B", text: "assumes without justification that standardized tests accurately measure learning" },
      { letter: "C", text: "ignores a significant difference between the groups being compared" },
      { letter: "D", text: "relies on the authority of Professor Martinez without independent verification" },
      { letter: "E", text: "confuses correlation with causation" },
    ],
    correctAnswer: "C",
    explanation: "The argument commits a comparison flaw by failing to account for a crucial difference between the groups. Professor Martinez teaches only honors students, who are likely to perform better regardless of teaching method. Comparing her results to professors who teach mixed classes is not a fair comparison, as the student populations differ significantly.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-003",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers found that employees who take regular breaks during the workday are more productive than those who work continuously. The researchers concluded that companies should mandate regular breaks for all employees to increase overall productivity.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' argument?",
    answerChoices: [
      { letter: "A", text: "The study was conducted across multiple industries and job types" },
      { letter: "B", text: "Employees who currently take breaks do so because they find the work monotonous" },
      { letter: "C", text: "Some employees prefer to work without interruption" },
      { letter: "D", text: "Productivity gains from breaks persist even when breaks are externally mandated rather than self-initiated" },
      { letter: "E", text: "The researchers have received funding from workplace wellness organizations" },
    ],
    correctAnswer: "D",
    explanation: "The argument assumes that mandating breaks will have the same positive effect as voluntary breaks. Choice D directly supports this assumption by showing that productivity gains persist even when breaks are externally required, addressing the potential objection that mandatory breaks might not yield the same benefits as self-chosen ones.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-004",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company argues that their new medication is safe for widespread use because clinical trials showed no serious side effects in over 5,000 participants during the two-year study period.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some participants experienced minor headaches during the trial" },
      { letter: "B", text: "The medication was tested only on adults between ages 25 and 55" },
      { letter: "C", text: "Similar medications have been on the market for decades" },
      { letter: "D", text: "The clinical trial was conducted at multiple research centers" },
      { letter: "E", text: "The pharmaceutical company has a good safety record with previous medications" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims the medication is safe for widespread use, but if the trial only included a narrow age range, the results may not apply to children, elderly individuals, or others outside this demographic. This significantly weakens the claim that the drug is safe for the general population.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-005",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Since the introduction of electronic voting machines, voter turnout has increased in every county that adopted them. Clearly, the convenience of electronic voting encourages more citizens to participate in elections.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Electronic voting machines are more accurate than paper ballots" },
      { letter: "B", text: "All counties that adopted electronic voting did so at the same time" },
      { letter: "C", text: "The increase in voter turnout is not primarily due to other factors that coincided with the adoption of electronic voting" },
      { letter: "D", text: "Voters prefer electronic voting to traditional paper ballots" },
      { letter: "E", text: "Electronic voting machines are less expensive to operate than traditional voting methods" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that electronic voting convenience caused higher turnout. This requires assuming that no other factors (such as competitive elections, increased civic engagement campaigns, or demographic changes) primarily drove the increase. Without this assumption, the convenience explanation is undermined.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-006",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical research has shown that moderate exercise reduces the risk of heart disease. However, many people find it difficult to maintain a regular exercise routine due to busy schedules. Given that even brief periods of physical activity provide health benefits, people who cannot commit to lengthy workouts should incorporate short bursts of activity throughout their day.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Moderate exercise reduces the risk of heart disease" },
      { letter: "B", text: "Many people find it difficult to maintain regular exercise routines" },
      { letter: "C", text: "Brief periods of physical activity provide health benefits" },
      { letter: "D", text: "People unable to commit to lengthy workouts should incorporate short bursts of activity throughout their day" },
      { letter: "E", text: "Busy schedules prevent people from exercising" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is the recommendation that people who cannot do lengthy workouts should incorporate short activity bursts. The other statements serve as premises supporting this conclusion: the health benefits of exercise, the difficulty of maintaining routines, and the effectiveness of brief activity all lead to the recommendation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-007",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The government claims that the new surveillance program is necessary for national security. But similar programs implemented in other democracies have led to widespread abuse of civil liberties without demonstrable security improvements. We should expect the same outcome here.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "attacking the motives of those who support the surveillance program" },
      { letter: "B", text: "drawing an analogy between the proposed program and programs in other countries" },
      { letter: "C", text: "providing statistical evidence that surveillance programs are ineffective" },
      { letter: "D", text: "arguing that the program violates established legal principles" },
      { letter: "E", text: "demonstrating that the program's supporters have made factual errors" },
    ],
    correctAnswer: "B",
    explanation: "The critic argues by analogy, comparing the proposed surveillance program to similar programs in other democracies. By pointing out that those programs led to abuse without security benefits, the critic suggests the same pattern will occur with this program. This is a classic analogical reasoning structure.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Everyone who attended the conference on environmental policy is concerned about climate change. Dr. Thompson is concerned about climate change. Therefore, Dr. Thompson must have attended the conference on environmental policy.`,
    questionStem: "The reasoning in the argument is flawed because the argument",
    answerChoices: [
      { letter: "A", text: "fails to consider that Dr. Thompson may have multiple reasons to be concerned about climate change" },
      { letter: "B", text: "assumes that only conference attendees are concerned about climate change" },
      { letter: "C", text: "does not specify when the conference took place" },
      { letter: "D", text: "relies on Dr. Thompson's self-reported concern rather than observable behavior" },
      { letter: "E", text: "confuses the expertise of conference attendees with their political views" },
    ],
    correctAnswer: "B",
    explanation: "This is a classic formal fallacy known as affirming the consequent. The argument states that all conference attendees are concerned about climate change, then incorrectly reverses this to conclude that anyone concerned about climate change must have attended. Many people can be concerned about climate change without attending this particular conference.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-009",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A study of ancient Roman texts reveals that Roman physicians prescribed willow bark tea for pain relief. Modern aspirin is derived from a compound found in willow bark. This suggests that Roman medical practices were more sophisticated than previously believed.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "Roman physicians also prescribed treatments that are now known to be ineffective" },
      { letter: "B", text: "The Romans traded extensively with other cultures that had different medical traditions" },
      { letter: "C", text: "Roman texts indicate that physicians understood that willow bark specifically reduced inflammation and fever" },
      { letter: "D", text: "Aspirin was first synthesized in the nineteenth century" },
      { letter: "E", text: "Many ancient cultures used plant-based remedies for various ailments" },
    ],
    correctAnswer: "C",
    explanation: "If Roman physicians understood the specific effects of willow bark on inflammation and fever, this demonstrates sophisticated medical knowledge beyond simple trial and error. This strengthens the claim that their practices were more sophisticated, showing they had theoretical understanding, not just empirical observation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The school board argues that the new curriculum has improved student performance because test scores have risen 20% since its implementation. Therefore, the curriculum should be adopted by other schools in the district.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "The new curriculum requires additional teacher training" },
      { letter: "B", text: "Students in schools with the old curriculum also showed a 20% increase in test scores during the same period" },
      { letter: "C", text: "Some teachers initially resisted the new curriculum" },
      { letter: "D", text: "The new curriculum costs more than the previous one" },
      { letter: "E", text: "Not all subjects showed equal improvement under the new curriculum" },
    ],
    correctAnswer: "B",
    explanation: "If schools using the old curriculum also saw a 20% increase, then the improvement cannot be attributed to the new curriculum. Some other factor must be responsible for the gains. This fundamentally undermines the causal claim that the new curriculum improved performance.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-011",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new interactive exhibits have attracted younger visitors. Since younger visitors are more likely to become lifelong museum supporters, the museum should continue investing in interactive technology.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Interactive exhibits are more expensive than traditional displays" },
      { letter: "B", text: "Younger visitors attracted by interactive exhibits will develop into the kind of supporters the museum needs" },
      { letter: "C", text: "Older visitors do not enjoy interactive exhibits" },
      { letter: "D", text: "The museum has sufficient funds to continue investing in technology" },
      { letter: "E", text: "All museums should prioritize attracting younger visitors" },
    ],
    correctAnswer: "B",
    explanation: "The argument connects attracting younger visitors through interactive exhibits to gaining lifelong supporters. This requires assuming that young visitors drawn specifically by interactive technology will become committed supporters, rather than just casual visitors who came for the novelty but won't return.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Attorney Chen: Mandatory minimum sentences ensure consistency in criminal justice. When judges have discretion, similar crimes can result in vastly different punishments depending on the judge assigned to the case.

Attorney Williams: But mandatory minimums prevent judges from considering the unique circumstances of each case. A first-time offender and a repeat offender may deserve different sentences even for the same crime.`,
    questionStem: "The main point at issue between Attorney Chen and Attorney Williams is whether",
    answerChoices: [
      { letter: "A", text: "judges currently have too much discretion in sentencing" },
      { letter: "B", text: "consistency in sentencing is more important than individualized consideration of circumstances" },
      { letter: "C", text: "mandatory minimum sentences result in longer prison terms overall" },
      { letter: "D", text: "first-time offenders should be treated differently from repeat offenders" },
      { letter: "E", text: "the criminal justice system is currently fair" },
    ],
    correctAnswer: "B",
    explanation: "Chen argues for consistency through mandatory minimums, while Williams argues for judicial discretion to consider individual circumstances. The fundamental disagreement is about the relative importance of these two values: uniform application of sentencing versus case-by-case consideration.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All successful entrepreneurs take calculated risks. Maria takes calculated risks. Therefore, Maria is a successful entrepreneur.`,
    questionStem: "The flawed pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All birds have feathers. Penguins are birds. Therefore, penguins have feathers." },
      { letter: "B", text: "All lawyers passed the bar exam. John passed the bar exam. Therefore, John is a lawyer." },
      { letter: "C", text: "No reptiles are warm-blooded. Snakes are reptiles. Therefore, snakes are not warm-blooded." },
      { letter: "D", text: "Some athletes are vegetarians. Tom is an athlete. Therefore, Tom might be a vegetarian." },
      { letter: "E", text: "All squares are rectangles. All rectangles have four sides. Therefore, all squares have four sides." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments commit the fallacy of affirming the consequent. The original argues: All successful entrepreneurs take risks; Maria takes risks; therefore Maria is a successful entrepreneur. Choice B has the identical structure: All lawyers passed the bar; John passed the bar; therefore John is a lawyer. Both incorrectly reverse a conditional relationship.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-014",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The governor claims that the state's economy has improved under her administration because unemployment has dropped. However, the governor has been actively campaigning for re-election and thus has a personal interest in portraying the economy favorably. Therefore, her claims about economic improvement should be dismissed.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that economic improvement is solely measured by unemployment rates" },
      { letter: "B", text: "fails to consider other indicators of economic health" },
      { letter: "C", text: "rejects a claim based on the source's potential bias rather than on the merits of the evidence" },
      { letter: "D", text: "does not acknowledge that unemployment data can be verified independently" },
      { letter: "E", text: "ignores the possibility that the economy might have improved for reasons unrelated to the governor's policies" },
    ],
    correctAnswer: "C",
    explanation: "This is an ad hominem fallacy. The argument dismisses the governor's claim about unemployment solely because she has a personal interest in the outcome, rather than examining whether the unemployment data is accurate. The source's bias does not automatically make the claim false; the evidence should be evaluated on its own merits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Scientists have observed that honeybee populations near certain organic farms are healthier than those near conventional farms. The scientists hypothesize that the absence of synthetic pesticides on organic farms is responsible for the improved bee health.`,
    questionStem: "Which one of the following, if true, most strengthens the scientists' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Organic farms often have more diverse plant populations than conventional farms" },
      { letter: "B", text: "Honeybee populations worldwide have been declining for decades" },
      { letter: "C", text: "When bees from organic farm areas are relocated to conventional farm areas, their health declines" },
      { letter: "D", text: "Some conventional farms use fewer pesticides than others" },
      { letter: "E", text: "Organic farming has become more popular in recent years" },
    ],
    correctAnswer: "C",
    explanation: "If bees become less healthy when moved from organic to conventional areas, this directly supports the hypothesis that something specific to conventional farms (the pesticides) is harming bee health. This experimental-style evidence shows the effect follows the exposure, strengthening the causal claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-016",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The marketing director argues that the company's new advertising campaign has been successful because sales increased by 30% in the quarter following the campaign's launch. She recommends continuing with the same advertising approach.`,
    questionStem: "Which one of the following, if true, most seriously weakens the marketing director's argument?",
    answerChoices: [
      { letter: "A", text: "The advertising campaign cost more than previous campaigns" },
      { letter: "B", text: "Competitor products experienced supply chain disruptions during the same quarter" },
      { letter: "C", text: "Some customers said they had not seen the new advertisements" },
      { letter: "D", text: "The company also launched new products in other categories during the same period" },
      { letter: "E", text: "The previous quarter's sales were lower than expected" },
    ],
    correctAnswer: "B",
    explanation: "If competitors faced supply chain problems, customers may have switched to this company's products out of necessity, not because of the advertising campaign. This alternative explanation for the sales increase undermines the claim that the advertising campaign caused the improvement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-017",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should build more public parks because studies show that access to green spaces improves mental health. Improving residents' mental health will reduce healthcare costs and increase productivity, benefiting the entire community.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Building public parks is the only way to provide access to green spaces" },
      { letter: "B", text: "Residents will actually use the new parks if they are built" },
      { letter: "C", text: "The cost of building parks will be less than the savings in healthcare costs" },
      { letter: "D", text: "All residents currently lack access to green spaces" },
      { letter: "E", text: "Mental health is the most important factor in overall well-being" },
    ],
    correctAnswer: "B",
    explanation: "The argument's chain of reasoning requires that residents use the parks. If parks are built but go unused, the mental health benefits won't materialize. This necessary assumption bridges the gap between building parks and improving mental health outcomes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-018",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Every member of the research team has published at least three peer-reviewed articles. All team members who have published more than five articles hold senior positions. Dr. Patel is a member of the research team but does not hold a senior position.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Dr. Patel has published exactly three peer-reviewed articles" },
      { letter: "B", text: "Dr. Patel has published no more than five peer-reviewed articles" },
      { letter: "C", text: "Dr. Patel will never hold a senior position" },
      { letter: "D", text: "All team members with senior positions have published exactly five articles" },
      { letter: "E", text: "Most research team members hold senior positions" },
    ],
    correctAnswer: "B",
    explanation: "Since all team members with more than five publications hold senior positions, and Dr. Patel does not hold a senior position, Dr. Patel must have five or fewer publications. Combined with the minimum of three for all team members, Dr. Patel has between three and five publications. Thus, no more than five must be true.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-019",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The proposed regulation would require all restaurants to display calorie counts on their menus. Opponents argue this would burden small restaurant owners. However, obesity rates have skyrocketed in recent decades, causing enormous health costs. Clearly, the regulation should be implemented.`,
    questionStem: "The argument is most vulnerable to the criticism that it",
    answerChoices: [
      { letter: "A", text: "fails to address the opponents' concern about the burden on small restaurants" },
      { letter: "B", text: "assumes that calorie displays will effectively reduce obesity" },
      { letter: "C", text: "does not consider whether consumers want calorie information" },
      { letter: "D", text: "overlooks the possibility that restaurants may raise prices to cover compliance costs" },
      { letter: "E", text: "both A and B" },
    ],
    correctAnswer: "E",
    explanation: "The argument has two main flaws: it ignores the opponents' concern about burden on small restaurants (A), and it assumes without evidence that displaying calories will actually reduce obesity (B). The argument jumps from 'obesity is a problem' to 'this regulation should be implemented' without addressing whether the regulation solves the problem or responding to the objection raised.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-020",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeological evidence indicates that ancient Mayan cities experienced periodic population declines that correlate with extended drought periods. Researchers conclude that water scarcity was a primary factor in the collapse of Mayan civilization.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "The Mayans developed sophisticated water storage systems" },
      { letter: "B", text: "Other ancient civilizations also experienced droughts without collapsing" },
      { letter: "C", text: "Skeletal remains from drought periods show signs of malnutrition and dehydration" },
      { letter: "D", text: "Mayan agricultural techniques were highly advanced" },
      { letter: "E", text: "Written records from the Mayan period are difficult to interpret" },
    ],
    correctAnswer: "C",
    explanation: "Direct physical evidence of malnutrition and dehydration in skeletal remains from drought periods provides concrete proof that water scarcity directly affected the population's health. This strengthens the causal link between drought and population decline, supporting the conclusion about water scarcity's role in collapse.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A fitness company claims that its new exercise program leads to significant weight loss. In their study, participants who followed the program for 12 weeks lost an average of 15 pounds. The company concludes that their program is highly effective for weight loss.`,
    questionStem: "Which one of the following, if true, most weakens the company's conclusion?",
    answerChoices: [
      { letter: "A", text: "Some participants lost more than 20 pounds during the study" },
      { letter: "B", text: "The study participants were required to follow a strict diet in addition to the exercise program" },
      { letter: "C", text: "The exercise program requires expensive equipment" },
      { letter: "D", text: "Not all participants completed the full 12-week program" },
      { letter: "E", text: "The company offers other fitness programs as well" },
    ],
    correctAnswer: "B",
    explanation: "If participants also followed a strict diet, the weight loss cannot be attributed solely to the exercise program. The diet could be primarily responsible for the results. This confounding variable weakens the conclusion that the exercise program itself is highly effective.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-022",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The literary critic argues that contemporary novels are inferior to classic literature because contemporary novels rarely grapple with profound philosophical themes. Great literature, the critic maintains, must engage with fundamental questions about human existence.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Classic literature is more popular than contemporary novels" },
      { letter: "B", text: "Readers prefer novels that address philosophical themes" },
      { letter: "C", text: "Engaging with profound philosophical themes is necessary for literary greatness" },
      { letter: "D", text: "Contemporary authors are less talented than classic authors" },
      { letter: "E", text: "All classic literature addresses philosophical themes" },
    ],
    correctAnswer: "C",
    explanation: "The critic's argument moves from 'contemporary novels lack philosophical themes' to 'contemporary novels are inferior.' This requires assuming that philosophical themes are necessary for greatness. Without this assumption, the absence of such themes wouldn't make contemporary novels inferior.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-023",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Automated customer service systems are increasingly common because they reduce labor costs. However, studies show that customers who interact with human representatives report higher satisfaction and are more likely to remain loyal. Companies focused on long-term growth should prioritize human customer service despite the higher costs.`,
    questionStem: "Which one of the following most accurately expresses the conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Automated customer service systems reduce labor costs" },
      { letter: "B", text: "Customers prefer human representatives to automated systems" },
      { letter: "C", text: "Customer loyalty is important for long-term growth" },
      { letter: "D", text: "Growth-focused companies should prioritize human customer service despite higher costs" },
      { letter: "E", text: "Automated systems are becoming more common" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is the recommendation that growth-focused companies should prioritize human customer service. The premises about cost reduction, customer satisfaction, and loyalty studies all support this final recommendation. The word 'should' signals the normative conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-024",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some argue that video games cause violent behavior. However, millions of people play video games regularly without engaging in violence. If video games truly caused violent behavior, we would expect to see much higher rates of violence among gamers. Since we don't, the causal claim is unfounded.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing an alternative explanation for violent behavior" },
      { letter: "B", text: "showing that a claimed cause does not produce its predicted effect" },
      { letter: "C", text: "attacking the credibility of those who make the causal claim" },
      { letter: "D", text: "demonstrating that correlation does not imply causation" },
      { letter: "E", text: "citing expert opinion to refute the causal claim" },
    ],
    correctAnswer: "B",
    explanation: "The argument uses a reductio ad absurdum approach: if video games caused violence, we would expect widespread violence among gamers, but we don't observe this. By showing the predicted consequence of the causal claim doesn't occur, the argument undermines the causal hypothesis.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-025",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The town council voted against building a new community center. Council member Davis voted against the project. Therefore, Davis must be opposed to community development in general.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes a single vote reflects a person's general stance on a broader issue" },
      { letter: "B", text: "ignores the reasons why Davis might have voted against this particular project" },
      { letter: "C", text: "fails to consider the opinions of other council members" },
      { letter: "D", text: "does not define what constitutes community development" },
      { letter: "E", text: "both A and B" },
    ],
    correctAnswer: "E",
    explanation: "The argument commits two related errors: it generalizes from one vote to a general position (A), and it ignores that Davis might have opposed this specific project for reasons unrelated to opposing community development generally (B). Davis might support community development but object to this project's cost, location, or design.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-026",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economists observe that countries with higher rates of entrepreneurship tend to have stronger economies. They conclude that encouraging entrepreneurship should be a primary goal of economic policy.`,
    questionStem: "Which one of the following, if true, most strengthens the economists' argument?",
    answerChoices: [
      { letter: "A", text: "Many entrepreneurs fail within the first five years" },
      { letter: "B", text: "Countries that implemented policies encouraging entrepreneurship subsequently experienced economic growth" },
      { letter: "C", text: "Strong economies can support more entrepreneurs" },
      { letter: "D", text: "Entrepreneurship is difficult to measure precisely" },
      { letter: "E", text: "Some countries with strong economies have low entrepreneurship rates" },
    ],
    correctAnswer: "B",
    explanation: "The argument suggests entrepreneurship causes economic strength. Choice B provides evidence of causation in the right direction: when countries encouraged entrepreneurship through policy, economic growth followed. This supports the conclusion that encouraging entrepreneurship leads to stronger economies.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-027",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A technology company argues that remote work increases productivity because their remote employees complete more tasks per day than office-based employees. The company plans to expand its remote work program based on this finding.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some remote employees work longer hours than their office-based counterparts" },
      { letter: "B", text: "The company carefully selects which employees can work remotely based on their track record of high performance" },
      { letter: "C", text: "Remote employees save time by not commuting" },
      { letter: "D", text: "Other technology companies have similar remote work policies" },
      { letter: "E", text: "The company provides remote employees with the same equipment as office workers" },
    ],
    correctAnswer: "B",
    explanation: "If the company selects high performers for remote work, the productivity difference could be due to employee selection, not the work arrangement itself. The remote workers were already more productive; the location didn't make them so. This selection bias undermines the causal claim about remote work increasing productivity.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of the robbery because he was at a concert across town at the time of the crime. Multiple witnesses saw him there, and he has photographs from the event.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The witnesses are truthful and their memories are accurate" },
      { letter: "B", text: "It is impossible to be in two places at once" },
      { letter: "C", text: "The photographs have not been altered" },
      { letter: "D", text: "The defendant did not hire someone else to commit the robbery" },
      { letter: "E", text: "The time of the robbery has been accurately determined" },
    ],
    correctAnswer: "E",
    explanation: "The alibi depends on the crime occurring at the same time the defendant was at the concert. If the robbery actually happened at a different time than believed, the concert alibi wouldn't prove innocence. The argument must assume the crime's timing has been correctly established.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-029",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Ellis: Universities should require all students to take courses in ethics because understanding ethical principles is essential for responsible citizenship. Every graduate should be equipped to make morally sound decisions.

Professor Franklin: Ethics courses are not the best way to develop moral reasoning. Students learn ethical behavior primarily through example and experience, not classroom instruction. Universities should focus on creating ethical campus environments instead.`,
    questionStem: "Professor Ellis and Professor Franklin disagree about whether",
    answerChoices: [
      { letter: "A", text: "ethical behavior is important for university graduates" },
      { letter: "B", text: "universities have a responsibility to develop students' moral reasoning" },
      { letter: "C", text: "required ethics courses are an effective means of developing moral reasoning" },
      { letter: "D", text: "example and experience play any role in moral development" },
      { letter: "E", text: "all students should learn about ethics in some form" },
    ],
    correctAnswer: "C",
    explanation: "Both professors agree that moral reasoning matters, but they disagree about the method: Ellis supports required ethics courses, while Franklin believes ethics courses are not the best approach and advocates for learning through experience and environment instead. Their dispute centers on the effectiveness of formal ethics instruction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-030",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The company should not hire external consultants because past consulting projects have consistently exceeded budget and failed to meet deadlines. There is no reason to believe this project would be different.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "We should not use this caterer because we have never used them before and don't know their quality." },
      { letter: "B", text: "We should not buy this car brand because previous models from this manufacturer have had reliability problems." },
      { letter: "C", text: "We should not attend the conference because it is expensive and few people from our department have expressed interest." },
      { letter: "D", text: "We should not invest in this stock because experts predict the market will decline." },
      { letter: "E", text: "We should not relocate the office because employees prefer the current location." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments conclude against an action based on past negative experiences with similar situations, assuming the pattern will continue. The original argues against consultants based on past consultant failures; choice B argues against a car brand based on past reliability problems with that manufacturer. Both use inductive reasoning from past patterns.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `No responsible journalist would publish unverified information. The Daily Tribune published the story about the mayor without verification. Therefore, the Daily Tribune employs irresponsible journalists.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "attacks the newspaper rather than addressing the accuracy of the story" },
      { letter: "B", text: "assumes that one instance reflects the character of all employees" },
      { letter: "C", text: "fails to consider that the story might have been verified after initial publication" },
      { letter: "D", text: "equates the actions of the organization with the responsibility of individual journalists" },
      { letter: "E", text: "presumes that the story was actually unverified without providing evidence" },
    ],
    correctAnswer: "D",
    explanation: "The argument moves from 'the newspaper published unverified information' to 'the newspaper employs irresponsible journalists.' This confuses organizational decisions with individual journalist responsibility. Editorial or management decisions to publish don't necessarily mean the journalists themselves are irresponsible.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Wildlife biologists argue that reintroducing wolves to the national park will restore ecological balance. They note that before wolves were eliminated, the elk population was stable and vegetation flourished. Since the wolves' absence, elk have overgrazed many areas.`,
    questionStem: "Which one of the following, if true, most strengthens the biologists' argument?",
    answerChoices: [
      { letter: "A", text: "Wolves primarily hunt sick and weak elk" },
      { letter: "B", text: "Other predators in the park have not controlled the elk population" },
      { letter: "C", text: "Similar wolf reintroduction programs in other regions successfully reduced overgrazing" },
      { letter: "D", text: "The park has sufficient wilderness to support a wolf population" },
      { letter: "E", text: "Local ranchers oppose wolf reintroduction" },
    ],
    correctAnswer: "C",
    explanation: "Evidence from similar successful programs directly supports the claim that wolf reintroduction can restore balance. This analogical evidence shows the approach has worked elsewhere, strengthening the prediction that it will work in this park as well.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-033",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The mayor argues that the city's new recycling program has been a success because the total volume of recyclable materials collected has doubled. She advocates for expanding the program to additional neighborhoods.`,
    questionStem: "Which one of the following, if true, most weakens the mayor's argument?",
    answerChoices: [
      { letter: "A", text: "The cost of the recycling program has exceeded initial projections" },
      { letter: "B", text: "Much of the collected material is contaminated and cannot actually be recycled" },
      { letter: "C", text: "Some residents have complained about the new recycling bins" },
      { letter: "D", text: "Other cities have more extensive recycling programs" },
      { letter: "E", text: "The recycling industry has experienced fluctuations in commodity prices" },
    ],
    correctAnswer: "B",
    explanation: "If the collected materials are contaminated and cannot actually be recycled, then the increased collection volume doesn't represent success. The program is collecting more but not actually recycling more, undermining the claim that the program has been successful.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The orchestra should not perform modern atonal compositions because audiences consistently express dissatisfaction with such pieces. The orchestra's mission is to serve its audience, and performing works that displease audiences contradicts this mission.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Atonal compositions have no artistic merit" },
      { letter: "B", text: "Audience satisfaction is the primary measure of fulfilling the orchestra's mission" },
      { letter: "C", text: "All audience members dislike atonal music" },
      { letter: "D", text: "Modern composers are less talented than classical composers" },
      { letter: "E", text: "The orchestra has never performed atonal compositions successfully" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that performing displeasing works contradicts the mission of serving audiences. This assumes that serving audiences means satisfying their preferences. But serving audiences could also mean challenging them, educating them, or exposing them to new art forms.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-035",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The CEO defended the company's decision to close the manufacturing plant by noting that continuing operations would have resulted in annual losses of $50 million. The closure affects 500 workers, but keeping the plant open would have eventually bankrupted the company, affecting all 5,000 employees.`,
    questionStem: "The CEO's argument employs which one of the following strategies?",
    answerChoices: [
      { letter: "A", text: "Comparing the negative consequences of two alternative courses of action" },
      { letter: "B", text: "Providing historical examples of similar business decisions" },
      { letter: "C", text: "Appealing to the authority of financial experts" },
      { letter: "D", text: "Challenging the accuracy of the critics' claims" },
      { letter: "E", text: "Arguing that the decision follows industry standard practices" },
    ],
    correctAnswer: "A",
    explanation: "The CEO compares two options and their negative consequences: closing the plant (500 jobs lost) versus keeping it open (eventual bankruptcy affecting 5,000 jobs). This lesser-of-two-evils approach argues that the chosen action, while harmful, prevents greater harm.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-036",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Researcher: Our study found that students who eat breakfast perform better academically. Therefore, schools that provide free breakfast programs will see improved student achievement.`,
    questionStem: "The researcher's reasoning is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that all students will participate in free breakfast programs" },
      { letter: "B", text: "does not consider the nutritional content of the breakfasts" },
      { letter: "C", text: "fails to account for factors that might explain both breakfast eating and academic performance" },
      { letter: "D", text: "ignores the cost of implementing breakfast programs" },
      { letter: "E", text: "does not define what constitutes better academic performance" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes eating breakfast causes better performance, but the correlation might be explained by a third factor. For example, students from stable, supportive homes might both eat breakfast more regularly and perform better academically. The breakfast itself might not be the causal factor.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-037",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholars argue that mandatory prison sentences for nonviolent drug offenses should be eliminated. They point out that such sentences have not reduced drug use rates while significantly increasing incarceration costs and separating families.`,
    questionStem: "Which one of the following, if true, most strengthens the legal scholars' argument?",
    answerChoices: [
      { letter: "A", text: "Prisons have become overcrowded due to drug offenders" },
      { letter: "B", text: "States that eliminated mandatory sentences for drug offenses saw decreased recidivism rates" },
      { letter: "C", text: "Treatment programs are less expensive than incarceration" },
      { letter: "D", text: "Public opinion has shifted toward supporting criminal justice reform" },
      { letter: "E", text: "Some drug offenders have gone on to lead productive lives after release" },
    ],
    correctAnswer: "B",
    explanation: "If eliminating mandatory sentences led to decreased recidivism (reoffending), this shows that the alternative approach is more effective. This directly strengthens the argument by providing evidence that alternatives to mandatory sentences produce better outcomes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-038",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The art critic claims that abstract expressionism represents the pinnacle of artistic achievement because it liberates art from the constraints of representational accuracy. Freedom from depicting reality, the critic argues, allows pure emotional expression.`,
    questionStem: "Which one of the following, if true, most weakens the critic's argument?",
    answerChoices: [
      { letter: "A", text: "Many abstract expressionist paintings sell for extremely high prices" },
      { letter: "B", text: "Some viewers find abstract expressionist works confusing" },
      { letter: "C", text: "Many representational works also achieve profound emotional expression" },
      { letter: "D", text: "Abstract expressionism developed in the mid-twentieth century" },
      { letter: "E", text: "Some abstract expressionist artists also created representational works" },
    ],
    correctAnswer: "C",
    explanation: "If representational works can also achieve profound emotional expression, then freedom from representation is not necessary for pure emotional expression. This undermines the critic's premise that liberation from representational constraints is what enables the emotional expression that makes abstract expressionism superior.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-039",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The restaurant review was unreliable because the reviewer visited only once. A single visit cannot capture the full range of a restaurant's quality, since any establishment can have an unusually good or bad night.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Restaurant quality varies from night to night" },
      { letter: "B", text: "The reviewer did not order enough dishes during the visit" },
      { letter: "C", text: "Multiple visits are necessary for a reliable review" },
      { letter: "D", text: "The restaurant in question has inconsistent quality" },
      { letter: "E", text: "Professional reviewers always visit restaurants multiple times" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes the review is unreliable because it was based on a single visit. The implicit assumption is that multiple visits are required for reliability. If a single visit could be sufficient under some circumstances, the argument's conclusion wouldn't follow.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-040",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Philosophers have long debated whether free will exists. Neuroscientific research suggests that brain activity precedes conscious decision-making, implying our choices may be determined before we're aware of them. However, this does not settle the debate because the concept of free will involves more than just the timing of brain processes. The question of moral responsibility, which is central to free will discussions, cannot be answered by neuroscience alone.`,
    questionStem: "The main conclusion of the argument is that",
    answerChoices: [
      { letter: "A", text: "neuroscience has not settled the philosophical debate about free will" },
      { letter: "B", text: "brain activity precedes conscious decision-making" },
      { letter: "C", text: "free will involves more than the timing of brain processes" },
      { letter: "D", text: "moral responsibility is central to discussions of free will" },
      { letter: "E", text: "philosophers have long debated whether free will exists" },
    ],
    correctAnswer: "A",
    explanation: "The main conclusion is that neuroscientific research has not settled the free will debate. The other statements serve as premises: the research findings, the observation that free will involves more than timing, and the point about moral responsibility all support the conclusion that neuroscience alone cannot resolve the philosophical question.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-041",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `City Planner: We must build more highways to reduce traffic congestion. Critics argue this will encourage more driving and ultimately worsen congestion. But we cannot simply do nothing while commuters suffer in gridlock every day.`,
    questionStem: "The city planner's response to the critics is flawed because it",
    answerChoices: [
      { letter: "A", text: "misrepresents the critics' position as advocating for no action" },
      { letter: "B", text: "assumes that highways are the only solution to congestion" },
      { letter: "C", text: "ignores the cost of highway construction" },
      { letter: "D", text: "fails to consider the environmental impact of more highways" },
      { letter: "E", text: "both A and B" },
    ],
    correctAnswer: "E",
    explanation: "The planner commits two errors: creating a false dichotomy between highways and doing nothing (ignoring alternatives like public transit, bike lanes, or congestion pricing) and misrepresenting critics who never said 'do nothing' but rather suggested that highways might worsen the problem.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-042",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historians argue that the printing press was the primary catalyst for the Protestant Reformation. Before the printing press, church doctrine could only be disseminated through hand-copied manuscripts controlled by the Catholic Church. The printing press allowed reformers to spread their ideas rapidly and widely.`,
    questionStem: "Which one of the following, if true, most strengthens the historians' argument?",
    answerChoices: [
      { letter: "A", text: "Martin Luther was an accomplished writer" },
      { letter: "B", text: "The Catholic Church initially supported the development of printing technology" },
      { letter: "C", text: "Earlier reform movements that lacked access to printing technology failed to gain widespread support" },
      { letter: "D", text: "Printed materials were more expensive than hand-copied manuscripts" },
      { letter: "E", text: "The printing press was invented in Germany, where Luther lived" },
    ],
    correctAnswer: "C",
    explanation: "Evidence that earlier reform movements failed without printing technology strengthens the claim that the printing press was essential. This provides a counterfactual comparison: similar reform ideas without the printing press did not succeed, suggesting the press was indeed the crucial factor enabling the Reformation's success.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-043",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The CEO argues that the company's generous employee benefits package is responsible for its high retention rate. The company loses only 5% of its workforce annually, compared to the industry average of 15%.`,
    questionStem: "Which one of the following, if true, most weakens the CEO's argument?",
    answerChoices: [
      { letter: "A", text: "The company is located in a region with few competing employers" },
      { letter: "B", text: "Some employees have expressed appreciation for the benefits package" },
      { letter: "C", text: "The company has increased its benefits in recent years" },
      { letter: "D", text: "Industry average retention rates have been declining" },
      { letter: "E", text: "The company's benefits package is more generous than most competitors" },
    ],
    correctAnswer: "A",
    explanation: "If there are few competing employers in the region, employees may stay simply because they have limited alternatives, not because of the benefits. This alternative explanation for high retention undermines the causal claim that the benefits package is responsible.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-044",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All of the candidates interviewed for the position have at least five years of experience. Some candidates with management experience were not interviewed. Every candidate who was interviewed has an advanced degree. No candidate without an advanced degree has management experience.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Some candidates with management experience have at least five years of experience" },
      { letter: "B", text: "All candidates with management experience were interviewed" },
      { letter: "C", text: "No candidate without five years of experience has an advanced degree" },
      { letter: "D", text: "Every candidate with management experience has an advanced degree" },
      { letter: "E", text: "Some candidates with advanced degrees have management experience" },
    ],
    correctAnswer: "D",
    explanation: "From the last statement, no candidate without an advanced degree has management experience. The contrapositive is: all candidates with management experience have an advanced degree. This is directly stated and must be true. The other options either contradict the premises or are not necessarily true.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-045",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company defends its high drug prices by noting that drug development requires billions of dollars in research. However, the company spends more on marketing and advertising than on research. Clearly, the high prices are not justified by research costs.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that marketing costs might also be legitimately passed on to consumers" },
      { letter: "B", text: "assumes that whatever a company spends the most on is its primary expense" },
      { letter: "C", text: "ignores the possibility that research costs could still justify the prices even if not the largest expense" },
      { letter: "D", text: "does not specify what proportion of the price goes to research" },
      { letter: "E", text: "both A and C" },
    ],
    correctAnswer: "E",
    explanation: "The argument has two flaws: it doesn't consider that marketing costs might also be legitimate business expenses (A), and it assumes that if research isn't the biggest expense, it can't justify prices (C). Research could still require billions even if marketing costs more, and marketing might also be a legitimate factor in pricing.",
    difficulty: "hard",
  },
  {
    id: "lr-bank42-046",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Economist A: Minimum wage increases benefit the economy because they put more money in the hands of consumers who will spend it, stimulating demand and creating jobs.

Economist B: Minimum wage increases harm the economy because they force businesses to cut hours, lay off workers, or raise prices, ultimately reducing employment and purchasing power.`,
    questionStem: "The economists disagree about whether",
    answerChoices: [
      { letter: "A", text: "minimum wage workers spend most of their income" },
      { letter: "B", text: "the net effect of minimum wage increases is economically beneficial" },
      { letter: "C", text: "businesses respond to minimum wage increases by raising prices" },
      { letter: "D", text: "consumer demand affects economic growth" },
      { letter: "E", text: "minimum wage increases put more money in workers' hands" },
    ],
    correctAnswer: "B",
    explanation: "Both economists acknowledge effects of minimum wage increases, but they reach opposite conclusions about the overall impact. Economist A sees net benefits through increased consumer spending; Economist B sees net harm through reduced employment and higher prices. Their fundamental disagreement is about the overall economic effect.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Any student who completes all assignments on time is eligible for extra credit. Therefore, since Marcus did not complete all assignments on time, he is not eligible for extra credit.`,
    questionStem: "The flawed pattern of reasoning exhibited by the argument above is most similar to that exhibited by which one of the following?",
    answerChoices: [
      { letter: "A", text: "Any member who pays dues is entitled to vote. Jones has not paid dues. Therefore, Jones is not entitled to vote." },
      { letter: "B", text: "All employees with perfect attendance receive a bonus. Kim has perfect attendance. Therefore, Kim receives a bonus." },
      { letter: "C", text: "Anyone who studies medicine for eight years can become a doctor. Lee studied medicine for eight years. Therefore, Lee can become a doctor." },
      { letter: "D", text: "Any restaurant that passes inspection can remain open. This restaurant passed inspection. Therefore, it can remain open." },
      { letter: "E", text: "Everyone who jogs regularly improves their cardiovascular health. Since Pat does not jog regularly, Pat has not improved their cardiovascular health." },
    ],
    correctAnswer: "E",
    explanation: "The original argument commits the fallacy of denying the antecedent: from 'if A then B' and 'not A,' it incorrectly concludes 'not B.' Choice E has the same structure: jogging leads to improved health; Pat doesn't jog; therefore Pat hasn't improved health. Both ignore that the consequent could occur through other means.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-048",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Skeptic: You claim that psychic readings provide genuine insights into people's lives. But psychics use vague statements that could apply to anyone, then refine their claims based on the subject's reactions. This technique, called cold reading, requires no special abilities whatsoever.`,
    questionStem: "The skeptic challenges the claim about psychic readings by",
    answerChoices: [
      { letter: "A", text: "denying that psychic readings ever provide accurate information" },
      { letter: "B", text: "offering an alternative explanation for the apparent accuracy of psychic readings" },
      { letter: "C", text: "questioning the motives of those who believe in psychic abilities" },
      { letter: "D", text: "citing scientific studies that disprove psychic phenomena" },
      { letter: "E", text: "arguing that the concept of psychic ability is logically incoherent" },
    ],
    correctAnswer: "B",
    explanation: "The skeptic provides an alternative explanation (cold reading) for why psychic readings seem accurate. Rather than directly denying the readings work, the skeptic explains the mechanism (vague statements refined by reactions) that produces the appearance of insight without requiring genuine psychic ability.",
    difficulty: "easy",
  },
  {
    id: "lr-bank42-049",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The government should not fund public broadcasting because citizens can access news and entertainment through private media outlets. Taxpayer money should only be used for services that private industry cannot adequately provide.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Private media outlets provide the same quality of content as public broadcasting" },
      { letter: "B", text: "Private media adequately provides the services offered by public broadcasting" },
      { letter: "C", text: "Public broadcasting is more expensive than private media" },
      { letter: "D", text: "Citizens prefer private media to public broadcasting" },
      { letter: "E", text: "Private media outlets do not receive any government funding" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims taxpayer money should only fund what private industry cannot adequately provide, then concludes public broadcasting shouldn't be funded. This requires assuming private media adequately provides what public broadcasting offers. If private media is inadequate in some way, the conclusion doesn't follow.",
    difficulty: "medium",
  },
  {
    id: "lr-bank42-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Scientists have identified genes associated with increased risk of heart disease. Some health advocates argue this proves we should screen everyone's DNA for these genes. However, most people with these genes never develop heart disease, while many who develop heart disease don't have the genes. Clearly, genetic screening for heart disease is pointless.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that screening might benefit those at elevated risk even if many will not develop the disease" },
      { letter: "B", text: "assumes genetic factors are the only cause of heart disease" },
      { letter: "C", text: "ignores the potential for genetic testing technology to improve" },
      { letter: "D", text: "dismisses the value of partial predictive ability in medical screening" },
      { letter: "E", text: "both A and D" },
    ],
    correctAnswer: "E",
    explanation: "The argument commits two related errors: it dismisses screening because it's not perfectly predictive (A and D). Screening can still be valuable if it identifies people at elevated risk who could benefit from preventive measures, even if not everyone with the genes develops disease. Perfect prediction is not required for screening to have value.",
    difficulty: "hard",
  },
];
