// Logical Reasoning Questions Bank - Set 37
import { Question } from "../lsat-types";

export const lrQuestionsSet37: Question[] = [
  {
    id: "lr-bank37-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during the workday are more productive than those who work continuously. Therefore, companies should require all employees to take mandatory breaks every hour to maximize productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that productivity may be influenced by factors other than break frequency" },
      { letter: "B", text: "assumes that what is true of employees who voluntarily take breaks will also be true of those required to take breaks" },
      { letter: "C", text: "ignores the possibility that some employees prefer not to take breaks" },
      { letter: "D", text: "does not specify what activities employees should engage in during breaks" },
      { letter: "E", text: "relies on a study without providing details about its methodology" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the flaw of assuming that voluntary behavior will produce the same results when mandated. The study examined employees who chose to take breaks, but this doesn't guarantee that forcing breaks on all employees would yield the same productivity gains.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Critics argue that the new tax policy will harm small businesses. However, the economists who designed the policy are highly educated professionals with decades of experience. Therefore, the critics' concerns are unfounded.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to address the substance of the critics' objections" },
      { letter: "B", text: "assumes that all economists agree about economic policy" },
      { letter: "C", text: "does not consider the economic impact on large businesses" },
      { letter: "D", text: "relies on an ambiguous definition of 'harm'" },
      { letter: "E", text: "presupposes that tax policies always benefit businesses" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits an ad hominem fallacy in reverse—rather than attacking critics, it defends the policy solely by appealing to the credentials of its designers. It never actually addresses whether the policy will harm small businesses.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every member of the city council voted for the new zoning ordinance. Since Mayor Thompson is a member of the city council, Mayor Thompson must have voted for the new zoning ordinance.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "confuses a necessary condition with a sufficient condition" },
      { letter: "B", text: "draws a conclusion about a group based on characteristics of individuals" },
      { letter: "C", text: "fails to consider whether the mayor abstained from voting" },
      { letter: "D", text: "assumes that all city council members have equal voting power" },
      { letter: "E", text: "does not establish that the mayor was present for the vote" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that 'every member voted for' means every member cast a vote in favor. However, members can abstain or be absent. The conclusion would only follow if we knew the mayor was present and did not abstain.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Those who argue that we have no free will point to neuroscience research showing that brain activity precedes conscious decision-making. But these scientists are themselves making choices about what to study and how to interpret their data. Their very arguments presuppose the free will they claim to disprove.`,
    questionStem: "The philosopher's argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that all choices require conscious deliberation" },
      { letter: "B", text: "conflates the appearance of choice with genuine free will" },
      { letter: "C", text: "ignores the distinction between libertarian and compatibilist accounts of free will" },
      { letter: "D", text: "misrepresents the scientists' position by assuming they deny making any choices" },
      { letter: "E", text: "relies on an appeal to authority rather than addressing the evidence" },
    ],
    correctAnswer: "D",
    explanation: "The philosopher mischaracterizes the scientists' position. Scientists who question free will don't deny that choices occur; rather, they argue that these choices are determined by prior causes. The argument attacks a straw man version of the scientists' view.",
    difficulty: "hard",
  },
  {
    id: "lr-bank37-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company's new drug has been tested on thousands of patients and shown to be effective. The company has invested billions of dollars in its development. Clearly, the drug should be approved for public use.`,
    questionStem: "The argument's reasoning is questionable because it",
    answerChoices: [
      { letter: "A", text: "fails to consider the drug's potential side effects and safety profile" },
      { letter: "B", text: "assumes that expensive drugs are more effective than cheaper alternatives" },
      { letter: "C", text: "does not specify the conditions under which the drug was tested" },
      { letter: "D", text: "relies on the company's own research rather than independent verification" },
      { letter: "E", text: "ignores the possibility that the drug may not be cost-effective" },
    ],
    correctAnswer: "A",
    explanation: "The argument focuses only on efficacy and investment but completely ignores safety considerations. Drug approval requires both effectiveness and an acceptable safety profile, which the argument fails to address.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Either we increase funding for public schools or the quality of education will decline. The legislature has just voted against increasing school funding. Therefore, the quality of education will inevitably decline.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "presents a false dichotomy by ignoring other ways to improve education" },
      { letter: "B", text: "assumes that increased funding always improves education quality" },
      { letter: "C", text: "does not consider the current state of education quality" },
      { letter: "D", text: "fails to define what constitutes a decline in education quality" },
      { letter: "E", text: "ignores the possibility that private schools might fill the gap" },
    ],
    correctAnswer: "A",
    explanation: "The argument presents only two options when others exist. Education quality might be maintained or improved through means other than increased funding, such as curriculum reform, teacher training, or efficiency improvements.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A survey of 500 customers at luxury car dealerships found that 85% were satisfied with their purchases. This proves that luxury cars provide superior customer satisfaction compared to economy vehicles.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "uses an unrepresentative sample to draw a comparative conclusion" },
      { letter: "B", text: "fails to define what constitutes customer satisfaction" },
      { letter: "C", text: "assumes that price correlates with quality" },
      { letter: "D", text: "does not account for buyer's remorse among luxury car owners" },
      { letter: "E", text: "ignores the environmental impact of luxury vehicles" },
    ],
    correctAnswer: "A",
    explanation: "The argument draws a comparative conclusion about luxury vs. economy cars but only surveys luxury car customers. Without comparable data from economy car customers, no valid comparison can be made about relative satisfaction levels.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of embezzlement because he has been a loyal employee for twenty years and has received numerous awards for his service. A person with such an exemplary record would never commit such a crime.`,
    questionStem: "The argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that past behavior necessarily predicts future behavior" },
      { letter: "B", text: "fails to consider the specific evidence in the current case" },
      { letter: "C", text: "relies on character evidence to refute factual allegations" },
      { letter: "D", text: "presumes the defendant's innocence without examining the evidence" },
      { letter: "E", text: "confuses legal guilt with moral culpability" },
    ],
    correctAnswer: "C",
    explanation: "The argument commits the fallacy of using character evidence to dismiss factual allegations. A person's good character and past record, while relevant to sentencing, do not prove they did not commit a specific act.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-009",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Biologist: Species that cannot adapt to changing environmental conditions will become extinct. The polar bear has survived for thousands of years in Arctic conditions. Therefore, polar bears will be able to adapt to the current rapid climate changes in the Arctic.`,
    questionStem: "The biologist's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that all environmental changes pose equal adaptive challenges" },
      { letter: "B", text: "confuses survival in stable conditions with ability to adapt to rapid change" },
      { letter: "C", text: "fails to consider that other Arctic species have also survived" },
      { letter: "D", text: "does not account for human intervention in polar bear conservation" },
      { letter: "E", text: "overlooks the role of genetic variation in adaptation" },
    ],
    correctAnswer: "B",
    explanation: "The biologist conflates long-term survival in relatively stable conditions with the ability to adapt to rapid environmental changes. Surviving in a consistent environment does not demonstrate capacity to quickly adapt when that environment changes dramatically.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-010",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: We should not use animals in medical research because animals cannot consent to being research subjects. Consent is a fundamental ethical requirement for research involving any sentient being.`,
    questionStem: "The ethicist's argument is most vulnerable to which of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It fails to consider that some animals may benefit from medical research" },
      { letter: "B", text: "It does not address the potential benefits of animal research for human health" },
      { letter: "C", text: "It would also prohibit medical research on infants and mentally incapacitated humans" },
      { letter: "D", text: "It assumes that all medical research causes significant harm to animals" },
      { letter: "E", text: "It overlooks regulations already in place to protect research animals" },
    ],
    correctAnswer: "C",
    explanation: "The argument's principle—that research requires the subject's consent—would logically extend to infants and severely mentally incapacitated humans who also cannot consent. This reveals an unintended consequence that the ethicist's principle would prohibit widely accepted practices.",
    difficulty: "hard",
  },
  {
    id: "lr-bank37-011",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying a remote village found that its residents live significantly longer than the national average. The village is located at high altitude, and researchers hypothesize that the reduced oxygen levels at this elevation trigger beneficial physiological adaptations that extend lifespan.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "The village residents consume a diet similar to that of people living at lower altitudes" },
      { letter: "B", text: "People who move to the village as adults also show increased longevity compared to their original communities" },
      { letter: "C", text: "The village has limited access to modern medical facilities" },
      { letter: "D", text: "Similar longevity patterns have been observed in other high-altitude communities worldwide" },
      { letter: "E", text: "The village residents engage in more physical activity than the national average" },
    ],
    correctAnswer: "A",
    explanation: "If village residents eat a diet similar to people at lower altitudes but still live longer, this rules out diet as an alternative explanation. This strengthens the hypothesis that altitude-related factors, rather than dietary differences, account for their longevity.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Mandatory minimum sentences for drug offenses should be abolished. Studies show that states with mandatory minimums have not experienced lower drug crime rates than states without such requirements. These laws simply fill prisons without reducing drug-related crime.`,
    questionStem: "Which one of the following, if true, would most strengthen the legal scholar's argument?",
    answerChoices: [
      { letter: "A", text: "States with mandatory minimums spend more on their prison systems than states without them" },
      { letter: "B", text: "Drug crime rates in states that recently abolished mandatory minimums have not increased" },
      { letter: "C", text: "Many judges believe mandatory minimums prevent them from considering individual circumstances" },
      { letter: "D", text: "Countries that have decriminalized drug possession have seen decreases in drug use" },
      { letter: "E", text: "The majority of people incarcerated under mandatory minimum laws are nonviolent offenders" },
    ],
    correctAnswer: "B",
    explanation: "If states that abolished mandatory minimums saw no increase in drug crime, this provides direct evidence that the laws were not effectively deterring crime. This strengthens the argument that mandatory minimums don't reduce drug crime.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: The ancient city of Mohenjo-daro shows evidence of sophisticated urban planning, including a grid street system and advanced drainage. This suggests that the Indus Valley Civilization had a centralized government capable of coordinating such large-scale public works.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologist's reasoning?",
    answerChoices: [
      { letter: "A", text: "Other cities of the Indus Valley Civilization show similar standardized urban planning features" },
      { letter: "B", text: "The construction techniques used in Mohenjo-daro were unique to that city" },
      { letter: "C", text: "Mohenjo-daro was one of the largest cities of the ancient world" },
      { letter: "D", text: "The city's layout remained consistent over several centuries" },
      { letter: "E", text: "Some ancient cities developed sophisticated infrastructure without centralized government" },
    ],
    correctAnswer: "A",
    explanation: "If multiple cities across the civilization show similar standardized features, this suggests coordination across a wide geographic area, which would require centralized planning and governance. This strengthens the inference of a centralized government.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Company executive: Implementing a four-day workweek will improve our company's productivity. Employees who work fewer hours are more focused and make fewer errors, ultimately producing better results than those who work traditional five-day weeks.`,
    questionStem: "Which one of the following, if true, most strengthens the executive's argument?",
    answerChoices: [
      { letter: "A", text: "Employees have expressed interest in a four-day workweek option" },
      { letter: "B", text: "Companies in similar industries that adopted four-day workweeks reported increased output per hour worked" },
      { letter: "C", text: "The company currently has higher error rates than its competitors" },
      { letter: "D", text: "Employee satisfaction surveys show that work-life balance is a top priority" },
      { letter: "E", text: "The technology sector has been experimenting with flexible work arrangements" },
    ],
    correctAnswer: "B",
    explanation: "Evidence that similar companies saw increased productivity with four-day workweeks directly supports the executive's claim. This provides relevant precedent suggesting the same results could be expected at this company.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: The recent rise in food allergies among children is likely caused by reduced exposure to diverse bacteria during early childhood. Modern sanitation and antibiotic use have created environments that are too clean, preventing children's immune systems from developing proper tolerance.`,
    questionStem: "Which one of the following, if true, most strengthens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Food allergy rates are lower in developing countries with less stringent sanitation practices" },
      { letter: "B", text: "Children who are breastfed have lower rates of food allergies" },
      { letter: "C", text: "The genes associated with food allergies have not changed significantly in recent generations" },
      { letter: "D", text: "Some children outgrow their food allergies by adolescence" },
      { letter: "E", text: "Food allergy testing has become more accurate in recent years" },
    ],
    correctAnswer: "A",
    explanation: "Lower allergy rates in countries with less sanitation directly supports the hypothesis that excessive cleanliness contributes to allergies. This evidence correlates reduced hygiene with reduced allergies, strengthening the causal claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The unsigned painting discovered in the estate is almost certainly an authentic work by Vermeer. The brushwork technique, use of light, and pigment composition are all consistent with Vermeer's authenticated works from the same period.`,
    questionStem: "Which one of the following, if true, would most strengthen the art historian's conclusion?",
    answerChoices: [
      { letter: "A", text: "Vermeer was known to have left some of his paintings unsigned" },
      { letter: "B", text: "The canvas material dates to the 17th century" },
      { letter: "C", text: "No known forger has successfully replicated Vermeer's distinctive brushwork" },
      { letter: "D", text: "The painting's subject matter is typical of Dutch Golden Age art" },
      { letter: "E", text: "The estate's owner was a known collector of Dutch paintings" },
    ],
    correctAnswer: "C",
    explanation: "If no forger has successfully replicated Vermeer's brushwork, and the painting displays that distinctive brushwork, this significantly strengthens the conclusion that it's authentic. It rules out the main alternative explanation—that it's a forgery.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Environmental scientist: The decline in bee populations is primarily caused by pesticide use in agricultural areas. Bees in regions with intensive farming operations are dying at much higher rates than those in areas with limited agricultural activity.`,
    questionStem: "Which one of the following, if true, most strengthens the scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Bee populations in organic farming regions have remained stable" },
      { letter: "B", text: "Some pesticides are designed to target insects other than bees" },
      { letter: "C", text: "Climate change has also been proposed as a cause of bee decline" },
      { letter: "D", text: "Beekeepers have reported higher losses in recent years" },
      { letter: "E", text: "Wild bee populations are declining faster than managed bee populations" },
    ],
    correctAnswer: "A",
    explanation: "If bees in organic farming areas (which don't use synthetic pesticides) have stable populations, this provides strong evidence that pesticides specifically—rather than farming in general—cause the decline.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-018",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Universal basic income would not reduce work incentives significantly. People have psychological needs for purpose and social connection that employment provides, and most would continue working even with a guaranteed income.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Most lottery winners continue working after winning substantial prizes" },
      { letter: "B", text: "Employment provides health insurance and retirement benefits beyond wages" },
      { letter: "C", text: "Universal basic income programs would cost less than current welfare programs" },
      { letter: "D", text: "Many wealthy individuals continue to work despite not needing the income" },
      { letter: "E", text: "Part-time employment has increased in countries with strong social safety nets" },
    ],
    correctAnswer: "A",
    explanation: "Lottery winners who continue working despite not needing income provide direct evidence that people work for reasons beyond financial necessity. This supports the claim that guaranteed income wouldn't eliminate work motivation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-019",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Hospital administrator: Installing hand sanitizer dispensers throughout the hospital has been effective in reducing hospital-acquired infections. Since we installed the dispensers six months ago, infection rates have dropped by 20 percent.`,
    questionStem: "Which one of the following, if true, most weakens the administrator's conclusion?",
    answerChoices: [
      { letter: "A", text: "Hand sanitizer is less effective against certain types of bacteria than traditional handwashing" },
      { letter: "B", text: "Six months ago, the hospital also implemented new cleaning protocols and reduced patient room occupancy" },
      { letter: "C", text: "Some hospital visitors do not use the hand sanitizer dispensers" },
      { letter: "D", text: "Infection rates at other hospitals have remained stable during the same period" },
      { letter: "E", text: "The hand sanitizer dispensers require regular maintenance and refilling" },
    ],
    correctAnswer: "B",
    explanation: "If other changes occurred simultaneously (new cleaning protocols, reduced occupancy), the reduction in infections might be due to these factors rather than the hand sanitizers. This introduces alternative explanations that weaken the causal claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Marketing director: Our new advertising campaign featuring celebrity endorsements has been a success. Since the campaign launched, our sales have increased by 15 percent compared to the same period last year.`,
    questionStem: "Which one of the following, if true, most seriously weakens the marketing director's reasoning?",
    answerChoices: [
      { letter: "A", text: "The company also lowered prices by 10 percent when the campaign launched" },
      { letter: "B", text: "Celebrity endorsements are expensive and reduce profit margins" },
      { letter: "C", text: "Competitor sales have also increased during the same period" },
      { letter: "D", text: "Some customers report being unaware of the advertising campaign" },
      { letter: "E", text: "The celebrity featured in the campaign was recently involved in a controversy" },
    ],
    correctAnswer: "A",
    explanation: "The price reduction provides an alternative explanation for the sales increase. Customers may be buying more because of lower prices, not because of the celebrity endorsements, undermining the claim that the advertising campaign caused the increase.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Political scientist: Democracies rarely go to war with other democracies. This demonstrates that the spread of democratic governance worldwide will lead to a more peaceful international order.`,
    questionStem: "Which one of the following, if true, most weakens the political scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Some democratic nations maintain large military forces" },
      { letter: "B", text: "The definition of what constitutes a democracy has varied historically" },
      { letter: "C", text: "Countries transitioning to democracy often experience internal instability and conflict with neighbors" },
      { letter: "D", text: "Economic interdependence between nations also reduces the likelihood of war" },
      { letter: "E", text: "Democracies have historically engaged in wars with non-democratic nations" },
    ],
    correctAnswer: "C",
    explanation: "If the process of becoming democratic actually increases conflict, then spreading democracy could cause more wars in the short term, even if established democracies are peaceful with each other. This undermines the prediction of a more peaceful international order.",
    difficulty: "hard",
  },
  {
    id: "lr-bank37-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Fitness trainer: High-intensity interval training is more effective for weight loss than traditional moderate-intensity exercise. A study showed that participants doing high-intensity workouts three times per week lost more weight than those doing moderate-intensity exercise five times per week.`,
    questionStem: "Which one of the following, if true, most weakens the trainer's argument?",
    answerChoices: [
      { letter: "A", text: "High-intensity training carries a greater risk of injury" },
      { letter: "B", text: "The participants in the high-intensity group were also given dietary counseling" },
      { letter: "C", text: "Some participants found high-intensity workouts too demanding to sustain" },
      { letter: "D", text: "Moderate-intensity exercise has cardiovascular benefits beyond weight loss" },
      { letter: "E", text: "The study lasted only eight weeks" },
    ],
    correctAnswer: "B",
    explanation: "If the high-intensity group received dietary counseling that the other group didn't, their greater weight loss could be due to dietary changes rather than the exercise type. This confounding variable undermines the causal claim about exercise intensity.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Business analyst: Our company should invest in solar panel manufacturing because the demand for renewable energy is growing rapidly. Countries around the world are committing to carbon reduction goals, which will drive increased demand for solar technology.`,
    questionStem: "Which one of the following, if true, most weakens the analyst's recommendation?",
    answerChoices: [
      { letter: "A", text: "Solar panel prices have been declining due to manufacturing efficiencies" },
      { letter: "B", text: "Wind energy is also experiencing rapid growth in demand" },
      { letter: "C", text: "The solar panel market is dominated by established manufacturers with significant cost advantages" },
      { letter: "D", text: "Government subsidies for solar energy vary by country" },
      { letter: "E", text: "Some regions receive insufficient sunlight for solar energy to be practical" },
    ],
    correctAnswer: "C",
    explanation: "Even if demand is growing, entering a market dominated by established competitors with cost advantages could make the investment unprofitable. Growing demand doesn't guarantee a new entrant can capture market share profitably.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-024",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Social media use causes increased feelings of loneliness among teenagers. Surveys consistently show that teenagers who spend more time on social media report feeling lonelier than those who spend less time online.`,
    questionStem: "Which one of the following, if true, most weakens the sociologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Teenagers often use social media to stay connected with friends who live far away" },
      { letter: "B", text: "Lonely teenagers may turn to social media as a substitute for in-person interaction" },
      { letter: "C", text: "Social media platforms are designed to maximize user engagement" },
      { letter: "D", text: "Teenagers spend an average of three hours per day on social media" },
      { letter: "E", text: "Some studies have found that social media can enhance feelings of connection" },
    ],
    correctAnswer: "B",
    explanation: "This answer suggests reverse causation: loneliness might cause increased social media use rather than vice versa. If lonely teenagers seek out social media, the correlation doesn't prove that social media causes loneliness.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-025",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Museum curator: Ancient Roman sculptures were originally painted in bright colors, not the white marble we see today. Traces of pigment have been found on numerous Roman statues, proving that Romans decorated their sculptures with vibrant polychrome finishes.`,
    questionStem: "Which one of the following, if true, most weakens the curator's conclusion?",
    answerChoices: [
      { letter: "A", text: "Greek sculptures, which influenced Roman art, were also originally painted" },
      { letter: "B", text: "The pigment traces found on some statues may have been added during later restoration attempts" },
      { letter: "C", text: "Some Roman sculptures were made of bronze rather than marble" },
      { letter: "D", text: "The techniques for analyzing ancient pigments have improved significantly" },
      { letter: "E", text: "Many Roman sculptures have been exposed to weathering that would remove traces of paint" },
    ],
    correctAnswer: "B",
    explanation: "If the pigments were added later during restoration rather than by the original Roman artists, then they don't prove that Romans painted their sculptures. This alternative explanation undermines the conclusion about original Roman practices.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Education researcher: Teaching cursive handwriting in schools is beneficial for students' cognitive development. Studies show that students who learn cursive perform better on reading comprehension tests than those who only learn print handwriting.`,
    questionStem: "Which one of the following, if true, most weakens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Cursive handwriting takes longer to master than print handwriting" },
      { letter: "B", text: "Schools that teach cursive typically have more educational resources overall" },
      { letter: "C", text: "Some students find cursive handwriting difficult to read" },
      { letter: "D", text: "Typing skills are becoming more important than handwriting in the modern workplace" },
      { letter: "E", text: "Reading comprehension can be improved through various teaching methods" },
    ],
    correctAnswer: "B",
    explanation: "If schools teaching cursive have more resources generally, the better reading comprehension could be due to those resources rather than cursive instruction specifically. This confounding factor undermines the causal connection claimed.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All effective leaders are good communicators. Since Janet is a good communicator, she will be an effective leader of the department.`,
    questionStem: "The argument's conclusion follows logically if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "Good communication is the only skill required for effective leadership" },
      { letter: "B", text: "Janet has experience leading teams in the past" },
      { letter: "C", text: "All good communicators are effective leaders" },
      { letter: "D", text: "Janet is better at communicating than other candidates for the position" },
      { letter: "E", text: "The department needs a leader with strong communication skills" },
    ],
    correctAnswer: "C",
    explanation: "The argument commits a logical error by affirming the consequent—it assumes that because good communication is necessary for effective leadership, it's also sufficient. For the conclusion to follow, we must assume that all good communicators are effective leaders.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city council should approve the proposed bike lane network. Studies in other cities have shown that bike lanes reduce traffic congestion by encouraging people to cycle instead of drive, and reduced congestion benefits all residents.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The city council has the authority to approve infrastructure projects" },
      { letter: "B", text: "Building bike lanes is the most cost-effective way to reduce traffic congestion" },
      { letter: "C", text: "Residents of this city would respond to bike lanes similarly to residents in the studied cities" },
      { letter: "D", text: "All residents of the city would use the bike lanes" },
      { letter: "E", text: "The proposed bike lane network would be similar in design to those in other cities" },
    ],
    correctAnswer: "C",
    explanation: "The argument uses evidence from other cities to predict results in this city. For this reasoning to work, it must assume that residents here would respond similarly—that the cities are comparable in relevant ways.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Philosophy professor: Students should study philosophy because it teaches critical thinking skills that are valuable in any career. Employers consistently rank critical thinking as one of the most desirable skills in job candidates.`,
    questionStem: "The professor's argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Philosophy is the only academic discipline that develops critical thinking" },
      { letter: "B", text: "Critical thinking skills learned in philosophy courses transfer to workplace contexts" },
      { letter: "C", text: "All philosophy courses emphasize critical thinking equally" },
      { letter: "D", text: "Students who study philosophy have higher employment rates than other graduates" },
      { letter: "E", text: "Employers prefer to hire students who have studied philosophy" },
    ],
    correctAnswer: "B",
    explanation: "The argument connects philosophy education to career value through critical thinking. This requires assuming that critical thinking skills developed in academic philosophy actually transfer to and are usable in workplace settings.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Vaccine researcher: The new vaccine candidate has shown strong immune responses in laboratory tests. We should therefore expect the vaccine to provide effective protection against the disease in clinical trials with human volunteers.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "laboratory tests are more rigorous than clinical trials" },
      { letter: "B", text: "strong immune responses in laboratory conditions correlate with protection in humans" },
      { letter: "C", text: "no other vaccine candidates are currently being tested" },
      { letter: "D", text: "the disease being targeted is currently widespread" },
      { letter: "E", text: "the vaccine will have no significant side effects" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from laboratory results to expectations about human protection. This requires assuming that lab results (likely from cell cultures or animal models) predict how the vaccine will perform in human bodies.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-031",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Restaurant critic: This restaurant uses only locally sourced organic ingredients. Therefore, the food served here is more nutritious than food at restaurants using conventional ingredients.`,
    questionStem: "Which one of the following is an assumption on which the argument depends?",
    answerChoices: [
      { letter: "A", text: "Organic ingredients are more expensive than conventional ingredients" },
      { letter: "B", text: "Local sourcing ensures that ingredients are fresh" },
      { letter: "C", text: "Organic ingredients have higher nutritional value than conventional ingredients" },
      { letter: "D", text: "The restaurant's cooking methods preserve the nutritional content of ingredients" },
      { letter: "E", text: "All restaurants should use locally sourced organic ingredients" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that organic equals more nutritious. This requires assuming that organic ingredients are actually more nutritious than conventional ones—a claim that the argument doesn't explicitly support.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution's key witness has given inconsistent statements about the time of the alleged crime. Any witness who contradicts their own testimony cannot be considered reliable. Therefore, my client should be acquitted.`,
    questionStem: "The argument's conclusion follows logically if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "The defendant has an alibi for the time in question" },
      { letter: "B", text: "Witnesses sometimes make honest mistakes about times" },
      { letter: "C", text: "The case against the defendant depends entirely on this witness's testimony" },
      { letter: "D", text: "The prosecution has no physical evidence linking the defendant to the crime" },
      { letter: "E", text: "Inconsistent witnesses are usually lying" },
    ],
    correctAnswer: "C",
    explanation: "The argument moves from 'the key witness is unreliable' to 'the defendant should be acquitted.' This only follows if the entire case rests on that witness—otherwise, other evidence could still support conviction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Technology analyst: Artificial intelligence will eventually replace human workers in most industries. AI systems can already perform many tasks faster and more accurately than humans, and their capabilities are improving rapidly.`,
    questionStem: "The analyst's argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Human workers will not find new types of jobs as AI advances" },
      { letter: "B", text: "AI systems will become capable of performing tasks that currently require human judgment and creativity" },
      { letter: "C", text: "Companies will choose to replace human workers with AI whenever possible" },
      { letter: "D", text: "The cost of AI systems will decrease over time" },
      { letter: "E", text: "Governments will not regulate the use of AI in the workplace" },
    ],
    correctAnswer: "B",
    explanation: "For AI to replace workers in 'most industries,' it must be able to do what those workers do. The argument assumes AI will expand beyond its current capabilities to handle tasks requiring human-like judgment and creativity.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The ancient kingdom flourished for three centuries before its sudden collapse. Archaeological evidence shows that in the final years, the kingdom experienced severe drought. The drought must have caused the kingdom's collapse.`,
    questionStem: "The argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "droughts of similar severity had not occurred during the kingdom's prosperous period" },
      { letter: "B", text: "the kingdom had no means of storing water during periods of drought" },
      { letter: "C", text: "other ancient kingdoms also collapsed during periods of drought" },
      { letter: "D", text: "the archaeological evidence of drought is accurate" },
      { letter: "E", text: "the kingdom was primarily dependent on agriculture" },
    ],
    correctAnswer: "A",
    explanation: "If equally severe droughts occurred during the kingdom's prosperous centuries, drought alone couldn't explain the collapse. The argument assumes this drought was different—that similar conditions hadn't been survived before.",
    difficulty: "hard",
  },
  {
    id: "lr-bank37-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical researchers have long believed that vitamin C supplementation prevents colds. However, recent meta-analyses of controlled studies show that vitamin C does not reduce the frequency of colds in the general population. Taking vitamin C supplements for cold prevention is therefore a waste of money for most people, though athletes and people under extreme physical stress may still benefit.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Medical researchers have been wrong about vitamin C and colds" },
      { letter: "B", text: "Vitamin C does not reduce cold frequency in the general population" },
      { letter: "C", text: "For most people, spending money on vitamin C supplements to prevent colds is not worthwhile" },
      { letter: "D", text: "Athletes should take vitamin C supplements" },
      { letter: "E", text: "Meta-analyses provide better evidence than individual studies" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is that vitamin C supplements for cold prevention are a 'waste of money for most people.' The research findings are offered as evidence for this practical recommendation, not as the conclusion itself.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some philosophers argue that consciousness cannot be explained by neuroscience because subjective experience is fundamentally different from brain activity. But we once thought life itself was beyond physical explanation—a vital force separate from chemistry and physics. We now understand life through biochemistry. Similarly, consciousness will eventually yield to scientific investigation, and the current explanatory gap will close.`,
    questionStem: "The main point of the argument is that",
    answerChoices: [
      { letter: "A", text: "consciousness is identical to brain activity" },
      { letter: "B", text: "the history of science shows that mysterious phenomena can eventually be explained" },
      { letter: "C", text: "some philosophers are wrong to think consciousness cannot be scientifically explained" },
      { letter: "D", text: "life was once thought to be beyond physical explanation" },
      { letter: "E", text: "neuroscience will replace philosophy in explaining consciousness" },
    ],
    correctAnswer: "C",
    explanation: "The argument uses the historical parallel of vitalism to counter philosophers who claim consciousness is beyond scientific explanation. The main point is that these philosophers are mistaken—consciousness will eventually be explained scientifically.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Genetically modified crops have been grown commercially for over two decades with no documented cases of harm to human health. Every major scientific organization has concluded they are as safe as conventional crops. Nevertheless, public suspicion of GMOs remains high. This gap between scientific consensus and public perception is a failure of science communication that researchers must work to address.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "GMO crops are safe for human consumption" },
      { letter: "B", text: "The public is misinformed about the safety of GMOs" },
      { letter: "C", text: "Scientists need to improve how they communicate about GMOs to the public" },
      { letter: "D", text: "Scientific organizations support the safety of GMO crops" },
      { letter: "E", text: "Public suspicion of GMOs is unjustified" },
    ],
    correctAnswer: "C",
    explanation: "The argument builds to the conclusion that the gap between scientific consensus and public perception represents a 'failure of science communication' that 'researchers must work to address.' The safety claims are premises supporting this conclusion about communication failure.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Urban planners often promote mixed-use development, which combines residential, commercial, and retail spaces in the same area. Such development reduces car dependence, creates vibrant neighborhoods, and can increase property values. Critics worry about noise and congestion, but these concerns can be mitigated through good design. Cities looking to revitalize their downtowns should seriously consider mixed-use development strategies.`,
    questionStem: "The argument is structured to lead to which one of the following conclusions?",
    answerChoices: [
      { letter: "A", text: "Mixed-use development has several important benefits" },
      { letter: "B", text: "Cities should incorporate mixed-use development in their downtown revitalization plans" },
      { letter: "C", text: "Concerns about noise and congestion from mixed-use development are unfounded" },
      { letter: "D", text: "Urban planners favor mixed-use development" },
      { letter: "E", text: "Mixed-use development increases property values" },
    ],
    correctAnswer: "B",
    explanation: "The argument presents benefits, addresses objections, and concludes with a recommendation that cities 'should seriously consider mixed-use development strategies.' This practical recommendation for city policy is the main conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: It has been claimed that playing violent video games causes aggressive behavior in children. But consider: millions of children play these games regularly, yet the vast majority do not exhibit aggressive behavior. If violent games truly caused aggression, we would expect to see widespread aggressive behavior among players, which we do not.`,
    questionStem: "The psychologist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "presenting statistical evidence that refutes a causal claim" },
      { letter: "B", text: "showing that a predicted consequence of a hypothesis does not occur" },
      { letter: "C", text: "demonstrating that correlation does not imply causation" },
      { letter: "D", text: "citing expert opinion to counter a popular belief" },
      { letter: "E", text: "arguing that the proposed cause is insufficient to produce the alleged effect" },
    ],
    correctAnswer: "B",
    explanation: "The psychologist uses modus tollens reasoning: if violent games caused aggression, then we'd see widespread aggression among players (predicted consequence). We don't see this. Therefore, the causal claim is questionable. The argument tests a hypothesis by examining whether its predicted consequences occur.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Those who argue that raising the minimum wage will increase unemployment are mistaken. They claim that higher wages will force businesses to lay off workers. But if that were true, we would expect countries with higher minimum wages to have higher unemployment rates. In fact, several countries with substantially higher minimum wages have lower unemployment than countries with minimal wage floors.`,
    questionStem: "The economist's argument uses which one of the following argumentative strategies?",
    answerChoices: [
      { letter: "A", text: "undermining a causal claim by presenting counterexamples" },
      { letter: "B", text: "attacking the motives of those who hold an opposing view" },
      { letter: "C", text: "showing that an argument proves too much by drawing absurd conclusions" },
      { letter: "D", text: "establishing a claim by providing a mechanism to explain how it works" },
      { letter: "E", text: "rejecting a conclusion because it is based on insufficient evidence" },
    ],
    correctAnswer: "A",
    explanation: "The economist presents counterexamples: countries with higher minimum wages but lower unemployment. These real-world cases contradict the predicted consequence of the opponents' causal claim, thereby undermining it.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Art critic: Some dismiss abstract art as meaningless because it doesn't represent recognizable objects. But by that reasoning, we would have to dismiss music as well—after all, instrumental music doesn't represent anything visual. Yet no one denies that music is a meaningful art form. Therefore, abstraction alone cannot render art meaningless.`,
    questionStem: "The art critic's argument is most accurately described as",
    answerChoices: [
      { letter: "A", text: "using an analogy to show that a principle leads to unacceptable consequences" },
      { letter: "B", text: "providing examples that demonstrate the falsity of a generalization" },
      { letter: "C", text: "arguing that what is true of a part must be true of the whole" },
      { letter: "D", text: "appealing to the authority of established artistic tradition" },
      { letter: "E", text: "showing that two apparently different cases are actually the same" },
    ],
    correctAnswer: "A",
    explanation: "The critic uses a reductio ad absurdum via analogy. The principle 'non-representational art is meaningless' would, if applied consistently, condemn instrumental music—an absurd result. This shows the principle must be rejected.",
    difficulty: "hard",
  },
  {
    id: "lr-bank37-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Legal theorist: The law should not punish people for thoughts alone, only for actions that harm others. We cannot even verify what someone is thinking, and thoughts do not directly harm anyone. Punishment for thoughts would require mind-reading, which is impossible, and would target mental states that may never lead to harmful action.`,
    questionStem: "The legal theorist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing practical and principled reasons for a position" },
      { letter: "B", text: "deriving a specific rule from a more general ethical principle" },
      { letter: "C", text: "rejecting a proposal because it conflicts with established legal precedent" },
      { letter: "D", text: "appealing to the intentions of those who designed the legal system" },
      { letter: "E", text: "arguing that punishing thoughts would violate individual rights" },
    ],
    correctAnswer: "A",
    explanation: "The theorist offers multiple types of reasons: practical ones (we can't verify thoughts; mind-reading is impossible) and principled ones (thoughts don't directly harm anyone; they may never lead to harmful action). The argument combines pragmatic and ethical justifications.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor A: Standardized testing is essential for ensuring educational accountability. Without uniform assessments, we have no way to compare student performance across schools or identify which schools need improvement.

Professor B: Standardized tests fail to measure the most important educational outcomes—creativity, critical thinking, and collaborative skills. Schools focused on test preparation often neglect these crucial competencies, ultimately shortchanging students.`,
    questionStem: "The professors disagree over whether",
    answerChoices: [
      { letter: "A", text: "student performance can be accurately measured" },
      { letter: "B", text: "standardized testing serves an important educational purpose" },
      { letter: "C", text: "some schools need improvement more than others" },
      { letter: "D", text: "creativity is more important than academic knowledge" },
      { letter: "E", text: "test preparation takes time away from other learning" },
    ],
    correctAnswer: "B",
    explanation: "Professor A argues standardized testing is 'essential' for accountability, while Professor B claims tests 'fail to measure the most important outcomes' and cause schools to neglect crucial skills. They directly disagree about whether standardized testing serves an important educational purpose.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Bioethicist A: Genetic enhancement of future children should be permitted. Parents already make countless decisions affecting their children's futures, from education to nutrition. Genetic enhancement is simply an extension of this parental prerogative to help children flourish.

Bioethicist B: Genetic enhancement is fundamentally different from other parental choices because it occurs before a child exists and cannot be undone. The enhanced individual never consented to these irreversible modifications. We should prohibit such interventions until we better understand their long-term consequences.`,
    questionStem: "The point at issue between the bioethicists is whether",
    answerChoices: [
      { letter: "A", text: "genetic enhancement could have beneficial effects on children" },
      { letter: "B", text: "parents have the right to make decisions affecting their children" },
      { letter: "C", text: "genetic enhancement is sufficiently similar to other parental choices to be permitted" },
      { letter: "D", text: "genetic enhancements can be reversed after a child is born" },
      { letter: "E", text: "we currently understand the long-term consequences of genetic enhancement" },
    ],
    correctAnswer: "C",
    explanation: "Bioethicist A claims genetic enhancement is 'simply an extension' of normal parental choices. Bioethicist B argues it is 'fundamentally different.' They directly disagree about whether genetic enhancement is similar enough to other parental decisions to warrant the same permissive treatment.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Commentator A: The government should not subsidize the arts. Art is a private good that benefits primarily those who consume it. Taxpayers should not be forced to fund cultural activities that they may not value or participate in.

Commentator B: Public funding for the arts is essential because the arts provide broad social benefits—they promote cultural heritage, foster social cohesion, and enhance community identity. These public goods justify public investment, just as we invest in parks and libraries.`,
    questionStem: "Commentator A and Commentator B disagree about whether",
    answerChoices: [
      { letter: "A", text: "the government subsidizes other cultural activities" },
      { letter: "B", text: "taxpayers should have a say in how their money is spent" },
      { letter: "C", text: "parks and libraries deserve public funding" },
      { letter: "D", text: "the arts provide significant benefits to society at large" },
      { letter: "E", text: "all citizens participate equally in artistic activities" },
    ],
    correctAnswer: "D",
    explanation: "Commentator A claims art 'benefits primarily those who consume it' (a private good), while Commentator B asserts arts 'provide broad social benefits' (a public good). Their core disagreement is whether the arts benefit society at large, which determines whether public funding is justified.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Every successful entrepreneur takes risks. Marcus is not a successful entrepreneur. Therefore, Marcus does not take risks.`,
    questionStem: "The flawed pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All great athletes practice regularly. Jennifer practices regularly. Therefore, Jennifer is a great athlete." },
      { letter: "B", text: "Every effective medication has undergone clinical trials. This supplement has not undergone clinical trials. Therefore, this supplement is not an effective medication." },
      { letter: "C", text: "All professional musicians can read music. Robert is not a professional musician. Therefore, Robert cannot read music." },
      { letter: "D", text: "Every mammal has a backbone. This creature has a backbone. Therefore, this creature is a mammal." },
      { letter: "E", text: "All squares are rectangles. This shape is not a square. Therefore, this shape is not a rectangle." },
    ],
    correctAnswer: "C",
    explanation: "Both arguments commit the same fallacy: denying the antecedent. The original says: All successful entrepreneurs take risks; Marcus isn't a successful entrepreneur; therefore, Marcus doesn't take risks. Option C follows the same pattern: All professional musicians read music; Robert isn't a professional musician; therefore, Robert can't read music.",
    difficulty: "medium",
  },
  {
    id: "lr-bank37-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The library was empty when I arrived. Empty libraries are quiet. So the library must have been quiet when I arrived.`,
    questionStem: "The reasoning in the argument above is most similar to the reasoning in which one of the following?",
    answerChoices: [
      { letter: "A", text: "The sky was overcast yesterday. Overcast skies often bring rain. So it probably rained yesterday." },
      { letter: "B", text: "The restaurant was crowded when we arrived. Crowded restaurants are noisy. So the restaurant must have been noisy when we arrived." },
      { letter: "C", text: "The meeting ended early. Meetings that end early usually accomplish their goals. So this meeting probably accomplished its goals." },
      { letter: "D", text: "The test was difficult. Difficult tests require preparation. So students should have prepared for this test." },
      { letter: "E", text: "The candidate was inexperienced. Inexperienced candidates rarely win elections. So this candidate probably did not win the election." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments follow the same valid pattern: (1) X was Y at a given time, (2) Things that are Y are Z, (3) Therefore, X was Z at that time. The original uses empty/quiet; option B uses crowded/noisy. Both draw conclusions about the same time period as the initial observation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy improves, consumer confidence will rise. If consumer confidence rises, retail sales will increase. Therefore, if the economy improves, retail sales will increase.`,
    questionStem: "The pattern of reasoning in the argument above is most parallel to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If it rains, the ground will be wet. The ground is wet. Therefore, it must have rained." },
      { letter: "B", text: "If the medication works, the patient will recover. If the patient recovers, she can return to work. Therefore, if the medication works, the patient can return to work." },
      { letter: "C", text: "All fish live in water. All trout are fish. Therefore, all trout live in water." },
      { letter: "D", text: "Either the company will expand or it will downsize. The company has not expanded. Therefore, it will downsize." },
      { letter: "E", text: "If taxes are raised, government revenue will increase. Government revenue has not increased. Therefore, taxes were not raised." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments use hypothetical syllogism (chain reasoning): If A then B; if B then C; therefore, if A then C. The original chains economic improvement → consumer confidence → retail sales. Option B chains medication working → patient recovery → return to work.",
    difficulty: "easy",
  },
  {
    id: "lr-bank37-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `A new study of metropolitan areas found that cities with extensive public transportation systems have lower per capita carbon emissions than cities where most residents rely on private vehicles. The study also found that even in cities with good public transit, residents in neighborhoods with poor transit access drive as much as residents in transit-poor cities overall.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Building more public transit will reduce a city's carbon emissions" },
      { letter: "B", text: "Private vehicles produce more carbon emissions per trip than public transit" },
      { letter: "C", text: "Cities with extensive public transportation have some neighborhoods with poor transit access" },
      { letter: "D", text: "Per capita carbon emissions depend entirely on transportation choices" },
      { letter: "E", text: "All residents in transit-rich neighborhoods use public transportation regularly" },
    ],
    correctAnswer: "C",
    explanation: "The passage states that 'even in cities with good public transit, residents in neighborhoods with poor transit access drive as much as...' This presupposes that such neighborhoods exist within transit-rich cities. Therefore, it must be true that these cities have some neighborhoods with poor transit access.",
    difficulty: "hard",
  },
  {
    id: "lr-bank37-050",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `In the past decade, the publishing industry has seen a significant shift toward digital books. However, recent data shows that print book sales have stabilized after initial declines, while e-book sales growth has plateaued. Many readers report preferring print for extended reading sessions, citing reduced eye strain and better comprehension. Publishers have responded by investing in high-quality print editions with premium features.`,
    questionStem: "Which one of the following can be properly inferred from the statements above?",
    answerChoices: [
      { letter: "A", text: "E-book sales will eventually decline below print book sales" },
      { letter: "B", text: "Print books will always remain more popular than e-books" },
      { letter: "C", text: "Some publishers believe there is a viable market for premium print books" },
      { letter: "D", text: "Digital reading causes more eye strain than reading print books" },
      { letter: "E", text: "Reader preferences are the only factor determining book format choices" },
    ],
    correctAnswer: "C",
    explanation: "The passage states that publishers 'have responded by investing in high-quality print editions with premium features.' Businesses invest in products they believe will sell. Therefore, it can be inferred that some publishers believe there is a viable market for premium print books.",
    difficulty: "medium",
  },
];
