// Logical Reasoning Questions Bank - Set 59
import { Question } from "../lsat-types";

export const lrQuestionsSet59: Question[] = [
  {
    id: "lr-bank59-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that people who drink three cups of coffee per day have lower rates of heart disease than those who drink no coffee. Therefore, drinking coffee must be beneficial for heart health and should be recommended to all patients concerned about cardiovascular disease.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on a sample size that is too small to draw meaningful conclusions" },
      { letter: "B", text: "fails to consider that the correlation between coffee consumption and heart health may not indicate causation" },
      { letter: "C", text: "assumes that what is true of one group must be true of all groups" },
      { letter: "D", text: "ignores the possibility that heart disease has multiple causes" },
      { letter: "E", text: "confuses a necessary condition with a sufficient condition" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the classic correlation-causation fallacy. Just because coffee drinkers have lower rates of heart disease does not mean coffee causes better heart health. There could be confounding variables—perhaps coffee drinkers also exercise more or have other healthy habits.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martin argues that we should increase funding for the humanities because such subjects develop critical thinking skills. But Professor Martin has a PhD in philosophy and would directly benefit from increased humanities funding. Therefore, we should reject her argument for increased humanities funding.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider alternative explanations for Professor Martin's position" },
      { letter: "B", text: "attacks the person making the argument rather than addressing the argument itself" },
      { letter: "C", text: "assumes that all professors in the humanities share the same views" },
      { letter: "D", text: "overlooks the possibility that humanities funding has already been increased" },
      { letter: "E", text: "confuses a correlation with a causal relationship" },
    ],
    correctAnswer: "B",
    explanation: "This is an ad hominem fallacy. The argument dismisses Professor Martin's position solely based on her personal stake in the outcome, rather than engaging with her actual argument about critical thinking skills. A person's potential bias does not automatically invalidate their argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every member of the city council voted for the new zoning ordinance. Sandra is not a member of the city council. Therefore, Sandra did not vote for the new zoning ordinance.`,
    questionStem: "The pattern of flawed reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All professional athletes train regularly. John trains regularly. Therefore, John is a professional athlete." },
      { letter: "B", text: "Every student in the honors program passed the exam. Maria is not in the honors program. Therefore, Maria did not pass the exam." },
      { letter: "C", text: "No lawyers attended the meeting. Thompson is a lawyer. Therefore, Thompson did not attend the meeting." },
      { letter: "D", text: "Some doctors support the new policy. Williams is a doctor. Therefore, Williams supports the new policy." },
      { letter: "E", text: "All mammals are warm-blooded. Snakes are not mammals. Therefore, snakes are not warm-blooded." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments commit the fallacy of denying the antecedent. The original argument assumes that because council members voted for the ordinance and Sandra is not a council member, she didn't vote for it—but others could have voted too. Similarly, choice B assumes that because honors students passed, non-honors students didn't—but they could have passed as well.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The mayor claims that the new public transit system will reduce traffic congestion by 30 percent. However, the mayor has consistently overestimated the benefits of previous infrastructure projects. In fact, the last three projects the mayor championed all failed to meet their projected targets. Clearly, the new transit system will not reduce traffic congestion by 30 percent.`,
    questionStem: "The argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "treats a probable outcome as though it were certain" },
      { letter: "B", text: "assumes that past patterns will necessarily continue in the future" },
      { letter: "C", text: "fails to specify what would count as a successful reduction in congestion" },
      { letter: "D", text: "ignores evidence that might support the mayor's claim" },
      { letter: "E", text: "confuses the mayor's credibility with the merits of the transit proposal" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that because the mayor's previous predictions were wrong, this prediction must also be wrong. This is the gambler's fallacy applied to predictions—past failures don't logically guarantee future failures. Each project should be evaluated on its own merits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Those who argue that animals have no moral rights because they cannot engage in moral reasoning are mistaken. After all, we grant moral rights to infants and severely cognitively impaired humans, even though they also cannot engage in moral reasoning. Therefore, the capacity for moral reasoning cannot be a prerequisite for having moral rights.`,
    questionStem: "The ethicist's argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes without justification that infants and cognitively impaired humans have moral rights" },
      { letter: "B", text: "fails to consider that there may be multiple sufficient conditions for having moral rights" },
      { letter: "C", text: "overlooks the possibility that some animals can engage in basic forms of moral reasoning" },
      { letter: "D", text: "does not adequately define what constitutes moral reasoning" },
      { letter: "E", text: "ignores potential morally relevant differences between animals and humans who cannot reason morally" },
    ],
    correctAnswer: "E",
    explanation: "The ethicist assumes that animals and humans who cannot engage in moral reasoning are relevantly similar. However, there may be other morally significant differences—such as species membership, potential for moral reasoning, or relational connections—that justify different treatment. The argument doesn't address these potential distinctions.",
    difficulty: "hard",
  },
  {
    id: "lr-bank59-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: The pharmaceutical company's study concluded that their new medication is safe because no serious side effects were reported during the three-month trial period. However, this conclusion is premature. Many medications have side effects that only become apparent after extended use, sometimes years after initial exposure.`,
    questionStem: "The scientist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "questioning the methodology used in the pharmaceutical company's study" },
      { letter: "B", text: "pointing out that the evidence presented is insufficient to support the conclusion drawn" },
      { letter: "C", text: "providing an alternative explanation for the study's findings" },
      { letter: "D", text: "attacking the credibility of the pharmaceutical company" },
      { letter: "E", text: "demonstrating that the medication does have serious side effects" },
    ],
    correctAnswer: "B",
    explanation: "The scientist argues that a three-month trial is insufficient to establish long-term safety because side effects can emerge over longer periods. This is a critique of the evidence's sufficiency rather than an attack on methodology, credibility, or an alternative explanation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Either we implement strict environmental regulations or businesses will continue to pollute unchecked. We cannot afford to let businesses pollute unchecked, as this would devastate our ecosystems. Therefore, we must implement strict environmental regulations.`,
    questionStem: "The argument's reasoning is questionable because the argument",
    answerChoices: [
      { letter: "A", text: "fails to consider that strict regulations might also have negative consequences" },
      { letter: "B", text: "presents only two options when other alternatives may exist" },
      { letter: "C", text: "assumes that all businesses would pollute if not regulated" },
      { letter: "D", text: "does not define what counts as strict environmental regulation" },
      { letter: "E", text: "ignores the economic benefits that might come from reduced regulation" },
    ],
    correctAnswer: "B",
    explanation: "This is a false dilemma fallacy. The argument presents only two options—strict regulations or unchecked pollution—when there could be middle-ground alternatives such as moderate regulations, voluntary industry standards, or market-based incentives.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: The defendant cannot be guilty of theft because theft requires the intent to permanently deprive the owner of their property. The defendant testified that she only intended to borrow the car temporarily and planned to return it the next day. Since she lacked the requisite intent, she cannot be guilty of theft.`,
    questionStem: "The legal scholar's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on a legal definition that may not apply in this jurisdiction" },
      { letter: "B", text: "assumes the defendant's testimony about her intentions is truthful" },
      { letter: "C", text: "fails to consider that the defendant may be guilty of other crimes" },
      { letter: "D", text: "confuses what the defendant intended with what she actually did" },
      { letter: "E", text: "overlooks the possibility that intent can be inferred from actions" },
    ],
    correctAnswer: "B",
    explanation: "The argument uncritically accepts the defendant's self-serving testimony about her intentions. People accused of crimes have strong motives to lie about their mental state, and intent is typically established through evidence beyond mere testimony. The scholar treats the defendant's claim as fact without questioning its reliability.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-009",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Everyone agrees that we need to reduce carbon emissions. Wind and solar power are renewable energy sources that produce no carbon emissions. Nuclear power plants also produce no carbon emissions during operation. Therefore, those who oppose nuclear power while supporting wind and solar are being inconsistent.`,
    questionStem: "The argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to acknowledge that there may be relevant differences between nuclear power and renewable energy sources" },
      { letter: "B", text: "assumes that carbon emissions are the only environmental concern" },
      { letter: "C", text: "overlooks the fact that nuclear power plants require uranium, which must be mined" },
      { letter: "D", text: "ignores economic factors that might distinguish nuclear from renewable energy" },
      { letter: "E", text: "presumes without justification that everyone has the same reasons for wanting to reduce carbon emissions" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that because both nuclear and renewable sources produce no operational carbon emissions, opposing one while supporting the other is inconsistent. However, there are many other relevant considerations—such as nuclear waste, safety risks, decommissioning costs, and weapons proliferation—that could justify different treatment.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-010",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ninety percent of successful entrepreneurs report working more than 60 hours per week during the early stages of their businesses. Therefore, aspiring entrepreneurs who want to succeed should plan to work at least 60 hours per week when starting their businesses.`,
    questionStem: "The argument's reasoning is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "relies on self-reported data that may be exaggerated" },
      { letter: "B", text: "assumes that correlation implies causation" },
      { letter: "C", text: "ignores the many entrepreneurs who worked long hours but still failed" },
      { letter: "D", text: "fails to define what constitutes a successful entrepreneur" },
      { letter: "E", text: "overlooks the health consequences of working long hours" },
    ],
    correctAnswer: "C",
    explanation: "This is a survivorship bias fallacy. The argument only looks at successful entrepreneurs without considering whether unsuccessful entrepreneurs also worked 60+ hours per week. If many failed entrepreneurs also worked long hours, then long hours alone don't predict success.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-011",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers have found that students who take handwritten notes perform better on conceptual understanding tests than students who take notes on laptops. The researchers hypothesize that this is because handwriting forces students to process and summarize information rather than transcribing it verbatim.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Students who type notes tend to record more words than students who write by hand" },
      { letter: "B", text: "When laptop users are instructed to avoid verbatim transcription, their conceptual understanding improves" },
      { letter: "C", text: "Handwritten notes are more difficult to share with classmates than typed notes" },
      { letter: "D", text: "Students generally prefer taking notes on laptops to writing by hand" },
      { letter: "E", text: "The students in the study were randomly assigned to handwriting or laptop conditions" },
    ],
    correctAnswer: "B",
    explanation: "If laptop users who are prevented from transcribing verbatim show improved conceptual understanding, this supports the hypothesis that processing and summarizing (rather than the physical act of handwriting itself) is what drives better comprehension. This directly tests the proposed mechanism.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `City officials are considering implementing congestion pricing in the downtown area, where drivers would pay a fee to enter during peak hours. Proponents argue that this will reduce traffic congestion because the fee will discourage unnecessary trips downtown during busy periods.`,
    questionStem: "Which one of the following, if true, most strengthens the proponents' argument?",
    answerChoices: [
      { letter: "A", text: "Other cities that have implemented congestion pricing have seen significant reductions in downtown traffic" },
      { letter: "B", text: "Public transportation options in the city are limited and unreliable" },
      { letter: "C", text: "Many downtown workers receive parking subsidies from their employers" },
      { letter: "D", text: "The proposed fee would be lower than the cost of parking in most downtown garages" },
      { letter: "E", text: "Air pollution levels in the downtown area have been rising in recent years" },
    ],
    correctAnswer: "A",
    explanation: "Evidence that congestion pricing has worked in other cities provides direct support for the claim that it will work here. This is an appeal to precedent that strengthens the causal claim about the policy's effectiveness.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: The absence of fortifications around ancient settlement X suggests that its inhabitants lived peacefully with neighboring communities. Settlements in conflict-prone regions typically constructed defensive walls and other protective structures, but no such structures have been found at site X despite extensive excavation.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologist's argument?",
    answerChoices: [
      { letter: "A", text: "The region where settlement X was located had abundant natural resources" },
      { letter: "B", text: "Other settlements from the same period and region that did experience conflict all had fortifications" },
      { letter: "C", text: "The excavation of settlement X has uncovered numerous artifacts indicating trade with distant communities" },
      { letter: "D", text: "Settlement X was located in a geographically isolated area" },
      { letter: "E", text: "The population of settlement X was relatively small compared to neighboring settlements" },
    ],
    correctAnswer: "B",
    explanation: "If other settlements in the same region and time period that experienced conflict all had fortifications, this establishes that fortifications were the standard response to conflict in that context. This strengthens the inference that the absence of fortifications at X indicates an absence of conflict.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company claims that its new allergy medication is more effective than the current leading brand. In the company's clinical trial, 78 percent of patients taking the new medication reported significant symptom relief, compared to 71 percent of patients taking the leading brand.`,
    questionStem: "Which one of the following, if true, most strengthens the pharmaceutical company's claim?",
    answerChoices: [
      { letter: "A", text: "The clinical trial involved over 2,000 participants randomly assigned to each medication group" },
      { letter: "B", text: "The new medication has fewer side effects than the leading brand" },
      { letter: "C", text: "Patients in the trial did not know which medication they were receiving" },
      { letter: "D", text: "The leading brand has been on the market for over fifteen years" },
      { letter: "E", text: "Both medications work by blocking the same histamine receptors" },
    ],
    correctAnswer: "A",
    explanation: "A large sample size with random assignment increases the statistical reliability of the results and reduces the likelihood that the observed difference is due to chance or confounding variables. This strengthens the claim that the new medication is genuinely more effective.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Business analyst: Remote work arrangements lead to higher employee productivity. Employees who work from home report spending less time in unproductive meetings and experiencing fewer interruptions from colleagues, allowing them to focus more effectively on their core tasks.`,
    questionStem: "Which one of the following, if true, most strengthens the business analyst's argument?",
    answerChoices: [
      { letter: "A", text: "Companies that allow remote work have lower office space costs" },
      { letter: "B", text: "Remote workers log more hours per week than office-based workers" },
      { letter: "C", text: "Objective measures of work output show that remote workers complete more tasks per hour than their office-based counterparts" },
      { letter: "D", text: "Remote workers report higher job satisfaction than office-based workers" },
      { letter: "E", text: "Many employees prefer the flexibility of working from home" },
    ],
    correctAnswer: "C",
    explanation: "The argument relies on self-reported benefits of remote work. Objective measures of actual output provide independent confirmation that these reported benefits translate into genuine productivity gains, strengthening the conclusion beyond mere employee perceptions.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Increasing economic inequality leads to higher rates of social unrest. As the gap between wealthy and poor citizens grows, those at the bottom of the economic ladder become increasingly frustrated with a system they perceive as unfair, making them more likely to engage in protests and civil disobedience.`,
    questionStem: "Which one of the following, if true, most strengthens the sociologist's argument?",
    answerChoices: [
      { letter: "A", text: "Countries with strong social safety nets experience less social unrest than countries without such programs" },
      { letter: "B", text: "Historical data shows that periods of increasing inequality have consistently preceded major social movements" },
      { letter: "C", text: "Wealthy individuals are more likely to support policies that maintain the status quo" },
      { letter: "D", text: "Education levels among lower-income populations have been declining in recent decades" },
      { letter: "E", text: "Media coverage of economic inequality has increased substantially in recent years" },
    ],
    correctAnswer: "B",
    explanation: "Historical evidence showing a consistent pattern of inequality preceding social unrest provides strong empirical support for the claimed causal relationship. This pattern across multiple instances strengthens the argument that inequality leads to unrest.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Environmental scientists argue that restoring wetlands is one of the most cost-effective ways to reduce flooding in downstream communities. Wetlands act as natural sponges, absorbing excess water during heavy rains and releasing it slowly, thereby reducing peak flood levels.`,
    questionStem: "Which one of the following, if true, most strengthens the environmental scientists' argument?",
    answerChoices: [
      { letter: "A", text: "Many wetlands were drained in the past century to create farmland" },
      { letter: "B", text: "Regions that have maintained their natural wetlands experience significantly less flood damage than comparable regions where wetlands have been destroyed" },
      { letter: "C", text: "Wetlands also provide habitat for numerous species of birds and fish" },
      { letter: "D", text: "Building concrete flood barriers is extremely expensive" },
      { letter: "E", text: "Climate change is expected to increase the frequency of heavy rainfall events" },
    ],
    correctAnswer: "B",
    explanation: "A direct comparison showing that areas with wetlands experience less flooding than similar areas without wetlands provides strong empirical support for the claimed flood-reduction benefits. This real-world evidence strengthens the causal claim about wetlands' effectiveness.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-018",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Free will is compatible with determinism. Even if all our actions are causally determined by prior events, we can still be considered free when we act according to our own desires and values, without external coercion. Freedom does not require that our choices be uncaused; it only requires that they flow from our own character.`,
    questionStem: "Which one of the following, if true, most strengthens the philosopher's argument?",
    answerChoices: [
      { letter: "A", text: "Most people intuitively believe that they make genuinely free choices" },
      { letter: "B", text: "Scientific research has not definitively established whether human actions are causally determined" },
      { letter: "C", text: "Our legal and moral practices of holding people responsible for their actions presuppose only that their actions flow from their character, not that those actions are uncaused" },
      { letter: "D", text: "Some philosophers have argued that randomness in decision-making would actually undermine free will" },
      { letter: "E", text: "Many religious traditions teach that humans have the capacity for free choice" },
    ],
    correctAnswer: "C",
    explanation: "If our actual practices of assigning responsibility require only that actions flow from character (not that they be uncaused), this supports the philosopher's conception of freedom. It shows that the proposed definition of free will aligns with how we already think about moral responsibility.",
    difficulty: "hard",
  },
  {
    id: "lr-bank59-019",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city's new bike-sharing program has been a success. Since the program launched six months ago, the number of cyclists on city streets has increased by 40 percent. This demonstrates that providing convenient access to bicycles encourages more people to choose cycling as a mode of transportation.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "The bike-sharing program has been more popular in some neighborhoods than in others" },
      { letter: "B", text: "Some regular cyclists have switched from using their own bikes to using the shared bikes" },
      { letter: "C", text: "The city also added twenty miles of protected bike lanes during the same six-month period" },
      { letter: "D", text: "The bike-sharing program operates only in the downtown area" },
      { letter: "E", text: "Other cities with bike-sharing programs have seen similar increases in cycling" },
    ],
    correctAnswer: "C",
    explanation: "If protected bike lanes were also added during the same period, the increase in cycling might be due to safer infrastructure rather than the bike-sharing program. This alternative explanation undermines the causal claim that the bike-sharing program specifically encouraged more cycling.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Art critic: The paintings of the Dutch Golden Age are superior to contemporary art because they required far greater technical skill. Artists like Rembrandt and Vermeer spent years mastering techniques such as chiaroscuro and perspective that most contemporary artists never learn. Technical mastery is the hallmark of great art.`,
    questionStem: "Which one of the following, if true, most seriously weakens the art critic's argument?",
    answerChoices: [
      { letter: "A", text: "Many contemporary artists have formal training in classical painting techniques" },
      { letter: "B", text: "The techniques used by Dutch Golden Age painters were well-established by the time Rembrandt began painting" },
      { letter: "C", text: "Great art throughout history has been defined primarily by its ability to evoke emotional responses and provoke thought, not by technical skill alone" },
      { letter: "D", text: "Some Dutch Golden Age paintings were produced by workshop assistants rather than master painters" },
      { letter: "E", text: "Contemporary art sells for higher prices than Dutch Golden Age paintings at auction" },
    ],
    correctAnswer: "C",
    explanation: "The art critic's argument depends on the premise that technical mastery is the hallmark of great art. If great art has historically been defined by emotional impact and intellectual provocation rather than technique, this undermines the critic's criterion for judging art and thus the conclusion about superiority.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `School administrator: Eliminating recess periods would improve academic achievement. Students would gain an additional 30 minutes of instructional time each day, which over the course of a school year amounts to nearly 100 extra hours of learning. More time spent on academics naturally leads to better academic outcomes.`,
    questionStem: "Which one of the following, if true, most weakens the administrator's argument?",
    answerChoices: [
      { letter: "A", text: "Some countries with high academic achievement have longer school days than ours" },
      { letter: "B", text: "Research shows that physical activity breaks improve students' concentration and information retention during subsequent academic instruction" },
      { letter: "C", text: "Recess provides important opportunities for social development" },
      { letter: "D", text: "Many parents oppose the elimination of recess" },
      { letter: "E", text: "Teachers report that students are often restless during afternoon classes" },
    ],
    correctAnswer: "B",
    explanation: "If physical activity breaks improve concentration and retention, then eliminating recess might actually decrease the effectiveness of instructional time. The additional 30 minutes of academics might be less productive than the current arrangement, undermining the assumption that more time equals better outcomes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: Voter turnout in local elections is declining because citizens feel disconnected from local government. Surveys show that most residents cannot name their city council representative or identify any recent local legislation. This lack of awareness creates apathy that keeps people from the polls.`,
    questionStem: "Which one of the following, if true, most weakens the political analyst's argument?",
    answerChoices: [
      { letter: "A", text: "Voter turnout in national elections has remained relatively stable over the same period" },
      { letter: "B", text: "Awareness of local government was equally low twenty years ago when local election turnout was significantly higher" },
      { letter: "C", text: "Many local elections are held on different days than state and national elections" },
      { letter: "D", text: "Cities with elected mayors tend to have higher turnout than cities with appointed city managers" },
      { letter: "E", text: "Local news coverage of government affairs has declined in recent years" },
    ],
    correctAnswer: "B",
    explanation: "If awareness was equally low when turnout was higher, then lack of awareness cannot be the cause of declining turnout. This breaks the claimed causal link by showing that the proposed cause existed without producing the effect in the past.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Organic produce is healthier than conventionally grown produce because organic farming prohibits the use of synthetic pesticides. Pesticide residues on conventional produce pose health risks to consumers, so eliminating these residues by choosing organic makes for a healthier diet.`,
    questionStem: "Which one of the following, if true, most weakens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Organic produce is significantly more expensive than conventional produce" },
      { letter: "B", text: "Some consumers buy organic produce for environmental rather than health reasons" },
      { letter: "C", text: "Organic farming uses natural pesticides that can leave residues as harmful as synthetic pesticide residues" },
      { letter: "D", text: "The nutritional content of organic and conventional produce is virtually identical" },
      { letter: "E", text: "Washing conventional produce removes a significant portion of pesticide residues" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes organic produce is healthier because it lacks synthetic pesticide residues. If organic farming uses natural pesticides that are equally harmful, then choosing organic doesn't actually eliminate the health risk from pesticide residues, undermining the conclusion that organic is healthier.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-024",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Raising the minimum wage will not significantly reduce poverty because only a small percentage of minimum wage workers are from poor households. Most minimum wage workers are teenagers from middle-class families or second earners in households with higher primary incomes. Therefore, minimum wage increases largely benefit those who are not in poverty.`,
    questionStem: "Which one of the following, if true, most weakens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Minimum wage increases often trigger corresponding wage increases for workers earning slightly above the minimum wage" },
      { letter: "B", text: "Some businesses respond to minimum wage increases by reducing workers' hours" },
      { letter: "C", text: "The proportion of poor households with at least one minimum wage worker is much higher than the proportion of minimum wage workers who are from poor households" },
      { letter: "D", text: "Minimum wage increases may lead to modest price increases for consumers" },
      { letter: "E", text: "Many workers earning above the minimum wage are still living in poverty" },
    ],
    correctAnswer: "C",
    explanation: "The economist's statistic focuses on what percentage of minimum wage workers are poor. But the relevant question for poverty reduction is what percentage of poor households would benefit. If most poor households have a minimum wage worker, the policy could still significantly reduce poverty even if most minimum wage workers aren't poor.",
    difficulty: "hard",
  },
  {
    id: "lr-bank59-025",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Medical researcher: Our study found that patients who received the experimental treatment had a 50 percent higher survival rate than patients who received the standard treatment. This proves that the experimental treatment is more effective at saving lives.`,
    questionStem: "Which one of the following, if true, most weakens the medical researcher's conclusion?",
    answerChoices: [
      { letter: "A", text: "The study was conducted at multiple hospitals across several countries" },
      { letter: "B", text: "The patients who received the experimental treatment were generally younger and healthier than those who received the standard treatment" },
      { letter: "C", text: "The experimental treatment is more expensive than the standard treatment" },
      { letter: "D", text: "Both treatments have been approved by regulatory agencies" },
      { letter: "E", text: "Some patients in the standard treatment group requested the experimental treatment" },
    ],
    correctAnswer: "B",
    explanation: "If patients receiving the experimental treatment were younger and healthier, the higher survival rate might be due to patient characteristics rather than treatment effectiveness. This selection bias provides an alternative explanation for the observed difference, weakening the causal conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Criminologist: The implementation of community policing strategies has been responsible for the decline in violent crime in major cities over the past decade. Since these programs were introduced, violent crime rates have fallen by nearly 35 percent, demonstrating that building trust between police and communities effectively reduces crime.`,
    questionStem: "Which one of the following, if true, most weakens the criminologist's argument?",
    answerChoices: [
      { letter: "A", text: "Some cities that implemented community policing saw larger crime reductions than others" },
      { letter: "B", text: "Violent crime rates have also declined by similar percentages in cities that did not implement community policing programs" },
      { letter: "C", text: "Community policing requires significant additional funding for police departments" },
      { letter: "D", text: "Public approval ratings of police departments have increased in cities with community policing" },
      { letter: "E", text: "Some violent crimes are not reported to police" },
    ],
    correctAnswer: "B",
    explanation: "If cities without community policing saw similar crime reductions, this suggests some other factor is responsible for the decline. Community policing cannot be credited with the reduction if the same result occurred in its absence.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Companies should not use personality tests in hiring decisions. Such tests measure traits like extraversion and agreeableness, but there is no evidence that these traits predict job performance across different types of positions. Hiring should be based only on factors that predict job success.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "personality tests are more expensive to administer than other assessment methods" },
      { letter: "B", text: "job candidates' personalities cannot change over time" },
      { letter: "C", text: "companies should not consider factors other than predicted job performance when hiring" },
      { letter: "D", text: "personality tests are not accurate measures of the traits they claim to measure" },
      { letter: "E", text: "there are other hiring methods that do predict job performance" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that personality tests shouldn't be used because they don't predict job performance. This assumes that only job performance predictors should be considered in hiring. If other factors (like cultural fit or team dynamics) were legitimately relevant, personality tests might still be useful even without predicting performance.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The ancient Mayans must have had contact with visitors from other continents. Their pyramids bear striking resemblances to Egyptian pyramids, and such similarities in architectural style could not have arisen independently in two separate cultures.`,
    questionStem: "Which one of the following is an assumption required by the argument?",
    answerChoices: [
      { letter: "A", text: "The Mayan pyramids were constructed after the Egyptian pyramids" },
      { letter: "B", text: "The Mayans did not have the mathematical knowledge to design pyramids independently" },
      { letter: "C", text: "Architectural forms cannot develop similarly in isolated cultures facing similar challenges" },
      { letter: "D", text: "The Egyptian and Mayan pyramids served similar religious purposes" },
      { letter: "E", text: "There is physical evidence of contact between ancient Mayans and Egyptians" },
    ],
    correctAnswer: "C",
    explanation: "The argument claims that similarities in pyramid design prove contact because such similarities 'could not have arisen independently.' This assumes independent development of similar forms is impossible. If isolated cultures could independently arrive at similar solutions to similar problems, the similarity wouldn't prove contact.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Citizens should be required to vote in elections. In countries with compulsory voting, election results more accurately reflect the will of the entire population rather than just those motivated enough to vote voluntarily. A government that truly represents its citizens must be chosen by all of them.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "People who do not currently vote would make informed choices if required to vote" },
      { letter: "B", text: "Compulsory voting would not face significant opposition from citizens" },
      { letter: "C", text: "A government chosen by all citizens is more legitimate than one chosen by only some citizens" },
      { letter: "D", text: "Compulsory voting has been successful in all countries that have implemented it" },
      { letter: "E", text: "Voluntary voting systems always produce unrepresentative governments" },
    ],
    correctAnswer: "C",
    explanation: "The argument moves from 'results reflect the will of the entire population' to 'a government that truly represents its citizens must be chosen by all.' This assumes that broader participation produces a more legitimate or truly representative government—that quantity of participation matters for legitimacy.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The defendant could not have committed the robbery because she was at a concert during the time the crime was committed. The concert venue is thirty miles from the location of the robbery, and according to timestamped credit card records, the defendant purchased refreshments at the concert at 9:15 PM, just ten minutes before the robbery occurred.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The defendant attended the entire concert from beginning to end" },
      { letter: "B", text: "Credit card records are more reliable than eyewitness testimony" },
      { letter: "C", text: "The defendant could not have traveled thirty miles in ten minutes" },
      { letter: "D", text: "The defendant's credit card was not used by someone else at the concert" },
      { letter: "E", text: "The robbery took place exactly at the time initially reported" },
    ],
    correctAnswer: "C",
    explanation: "The argument depends on the physical impossibility of the defendant traveling from the concert to the robbery location in ten minutes. If she could have made the thirty-mile trip in that time, the concert attendance wouldn't provide an alibi. The argument assumes this trip was impossible.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-031",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The new educational software will improve student learning outcomes. Studies show that students who use the software spend 20 percent more time engaged with educational content compared to students using traditional textbooks. Greater engagement with educational content leads to better learning.`,
    questionStem: "Which one of the following is an assumption on which the argument depends?",
    answerChoices: [
      { letter: "A", text: "Students enjoy using the software more than reading textbooks" },
      { letter: "B", text: "The software covers the same content as traditional textbooks" },
      { letter: "C", text: "The quality of engagement with the software is at least as educationally valuable as engagement with textbooks" },
      { letter: "D", text: "Teachers have been trained to use the new educational software effectively" },
      { letter: "E", text: "The software is available to all students regardless of their economic background" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that more time engaged equals better learning. But this only works if the quality of engagement is equivalent or better. If software engagement is less educationally valuable per unit of time than textbook engagement, 20 percent more time might not produce better outcomes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Philosophy professor: We should not teach ethical relativism to undergraduate students. Ethical relativism holds that moral judgments are merely expressions of cultural preferences with no objective truth value. Students who accept this view may conclude that all moral views are equally valid, which could lead them to be tolerant of clearly unethical practices.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "There are some practices that are objectively unethical regardless of cultural context" },
      { letter: "B", text: "Undergraduate students are more susceptible to philosophical influence than graduate students" },
      { letter: "C", text: "Ethical relativism is a false philosophical position" },
      { letter: "D", text: "Philosophy professors have a responsibility to guide students' moral development" },
      { letter: "E", text: "Teaching about a philosophical position is equivalent to endorsing it" },
    ],
    correctAnswer: "A",
    explanation: "The professor warns that students might become tolerant of 'clearly unethical practices.' This concern only makes sense if some practices actually are objectively unethical. If relativism were true, there would be no 'clearly unethical practices' to worry about students tolerating.",
    difficulty: "hard",
  },
  {
    id: "lr-bank59-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city council should approve the new shopping mall development. The mall will create over 500 jobs for local residents and generate significant tax revenue for the city. These economic benefits clearly outweigh any concerns about increased traffic or environmental impact.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "the jobs created by the mall will pay competitive wages" },
      { letter: "B", text: "economic benefits should be weighed against traffic and environmental concerns" },
      { letter: "C", text: "local residents will fill most of the jobs created by the mall" },
      { letter: "D", text: "traffic and environmental concerns are the only drawbacks of the mall development" },
      { letter: "E", text: "the projected job creation and tax revenue figures are accurate" },
    ],
    correctAnswer: "D",
    explanation: "The argument claims economic benefits 'clearly outweigh' traffic and environmental concerns. This weighing only works if those are the only relevant concerns. If there are other significant drawbacks not mentioned, the benefits might not outweigh total concerns.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Geneticist: The gene responsible for early-onset Alzheimer's disease has been identified. Anyone who inherits this gene will develop Alzheimer's disease before age 65. Therefore, genetic testing for this gene should be offered to anyone with a family history of early-onset Alzheimer's.`,
    questionStem: "The geneticist's recommendation assumes that",
    answerChoices: [
      { letter: "A", text: "early-onset Alzheimer's disease can be prevented if detected early" },
      { letter: "B", text: "knowing whether one carries the gene would be beneficial to people with a family history of the disease" },
      { letter: "C", text: "the genetic test for early-onset Alzheimer's disease is highly accurate" },
      { letter: "D", text: "people who test negative for the gene will not develop Alzheimer's disease" },
      { letter: "E", text: "most cases of Alzheimer's disease are caused by this genetic factor" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'we can test for this gene' to 'we should offer testing.' This assumes testing would be beneficial—that people would be better off knowing. Without some benefit from the knowledge, there's no reason to offer the test.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `It is often argued that zoos are harmful because they confine animals to artificial environments that cannot replicate their natural habitats. However, modern zoos play a crucial role in conservation efforts, housing breeding programs for endangered species that might otherwise go extinct. Furthermore, zoos educate millions of visitors annually about wildlife and environmental issues. These benefits to both animal species and human understanding make zoos valuable institutions that should be supported.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Zoos confine animals to artificial environments that differ from their natural habitats" },
      { letter: "B", text: "Modern zoos participate in conservation breeding programs for endangered species" },
      { letter: "C", text: "Zoos educate millions of people about wildlife and environmental issues" },
      { letter: "D", text: "Zoos are valuable institutions that deserve support" },
      { letter: "E", text: "The benefits of zoos outweigh the concerns about animal confinement" },
    ],
    correctAnswer: "D",
    explanation: "The final sentence states that zoos 'are valuable institutions that should be supported.' The conservation and education points are offered as supporting reasons for this conclusion. The passage acknowledges the criticism about artificial environments but argues that benefits make zoos worthwhile.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `People who regularly practice meditation show improved emotional regulation compared to non-meditators. Neuroimaging studies reveal that meditation increases gray matter in brain regions associated with self-awareness and compassion. Moreover, even brief meditation interventions can reduce stress and anxiety. Clearly, incorporating meditation into daily life can enhance mental well-being, which is why schools should consider adding meditation programs to their curricula.`,
    questionStem: "Which one of the following most accurately expresses the conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Schools should consider adding meditation programs to their curricula" },
      { letter: "B", text: "Meditation can enhance mental well-being" },
      { letter: "C", text: "Regular meditation practice improves emotional regulation" },
      { letter: "D", text: "Meditation increases gray matter in brain regions associated with self-awareness" },
      { letter: "E", text: "Brief meditation interventions can reduce stress and anxiety" },
    ],
    correctAnswer: "A",
    explanation: "While the passage draws the intermediate conclusion that meditation enhances mental well-being, the ultimate conclusion is the recommendation that schools add meditation programs. The mental well-being point supports this final recommendation, making the school curriculum change the main conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some argue that artificial intelligence will eventually replace human workers in most industries. But this prediction overlooks the fact that new technologies have historically created more jobs than they have eliminated. The industrial revolution, for example, led to massive economic growth and employment expansion. While AI will certainly transform the nature of work, there is no reason to believe it will result in widespread permanent unemployment.`,
    questionStem: "The main conclusion of the argument is that",
    answerChoices: [
      { letter: "A", text: "artificial intelligence will transform the nature of work" },
      { letter: "B", text: "new technologies have historically created more jobs than they eliminated" },
      { letter: "C", text: "the industrial revolution led to economic growth and job creation" },
      { letter: "D", text: "predictions that AI will cause widespread permanent unemployment are unfounded" },
      { letter: "E", text: "AI will replace human workers in most industries" },
    ],
    correctAnswer: "D",
    explanation: "The argument opposes the claim that AI will cause widespread permanent unemployment. The historical point about technology creating jobs serves as evidence for the conclusion that fears of AI-caused unemployment are not justified. The final sentence explicitly states this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The proposal to extend library hours until midnight would cost the city an additional $200,000 annually in staff salaries and utilities. Usage data shows that only 3 percent of library patrons visit after 8 PM. Given these low usage rates, the cost of extended hours cannot be justified. The library board should reject this proposal and instead allocate resources to expanding digital services, which surveys indicate are in high demand.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "The proposal to extend library hours would cost $200,000 annually" },
      { letter: "B", text: "Only 3 percent of library patrons visit after 8 PM" },
      { letter: "C", text: "The cost of extended library hours cannot be justified" },
      { letter: "D", text: "The library board should reject the proposal and expand digital services instead" },
      { letter: "E", text: "Digital services are in high demand according to surveys" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is the recommendation about what the library board should do: reject the extended hours proposal and allocate resources to digital services. The cost analysis and usage data support the intermediate conclusion that extended hours cannot be justified, which in turn supports the final recommendation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The museum director claims that the new modern art wing will attract younger visitors and increase attendance. But the director made the same prediction about the sculpture garden five years ago, and attendance has remained flat. Since the director's previous prediction proved wrong, we should not expect this new prediction to be accurate either.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "offering an alternative explanation for the flat attendance figures" },
      { letter: "B", text: "questioning the director's expertise in predicting visitor behavior" },
      { letter: "C", text: "using a past failure to cast doubt on a current prediction" },
      { letter: "D", text: "demonstrating that the modern art wing is unlikely to appeal to young visitors" },
      { letter: "E", text: "arguing that attendance figures are not a reliable measure of museum success" },
    ],
    correctAnswer: "C",
    explanation: "The critic explicitly argues that because the director's past prediction about the sculpture garden was wrong, the current prediction about the modern art wing should be doubted. This is a straightforward case of using past failure to question present reliability.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: My colleague argues that increased solar activity is responsible for recent global temperature increases. However, satellite measurements show that solar energy reaching Earth has actually decreased slightly over the past 40 years while global temperatures have risen significantly. Therefore, increased solar activity cannot be the primary cause of recent warming.`,
    questionStem: "The scientist's argument employs which one of the following methods of reasoning?",
    answerChoices: [
      { letter: "A", text: "Presenting evidence that directly contradicts a claim made by the colleague" },
      { letter: "B", text: "Showing that the colleague's argument relies on a false analogy" },
      { letter: "C", text: "Demonstrating that the colleague has a personal interest in the conclusion" },
      { letter: "D", text: "Arguing that the colleague's conclusion does not follow from the premises offered" },
      { letter: "E", text: "Proposing an alternative explanation for the phenomenon in question" },
    ],
    correctAnswer: "A",
    explanation: "The scientist presents satellite data showing solar energy has decreased while temperatures increased. This directly contradicts the colleague's claim that increased solar activity caused warming. If solar input decreased, it cannot be responsible for temperature increases.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Those who defend capital punishment on grounds of deterrence argue that fear of execution prevents potential murderers from committing homicides. But if deterrence were truly effective, we would expect states with the death penalty to have lower murder rates than states without it. In fact, the opposite is true: states with capital punishment consistently have higher murder rates. This suggests that capital punishment does not actually deter crime.`,
    questionStem: "The ethicist's argument uses which one of the following argumentative techniques?",
    answerChoices: [
      { letter: "A", text: "Attacking the motives of those who support capital punishment" },
      { letter: "B", text: "Showing that a predicted consequence of a position does not obtain" },
      { letter: "C", text: "Demonstrating that capital punishment violates ethical principles" },
      { letter: "D", text: "Arguing that opponents of capital punishment have the burden of proof" },
      { letter: "E", text: "Establishing that execution is a more severe punishment than imprisonment" },
    ],
    correctAnswer: "B",
    explanation: "The ethicist identifies what should follow if the deterrence claim were true (lower murder rates in death penalty states) and then shows that the opposite is actually the case. This is an indirect refutation by showing that expected consequences don't materialize.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that we have moral obligations only to beings who can reciprocate—that is, who can also have obligations to us. But consider a person in a permanent coma. Such a person cannot have obligations to anyone, yet surely we have moral obligations not to harm that person. Therefore, the capacity to reciprocate cannot be a requirement for being owed moral consideration.`,
    questionStem: "The philosopher's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "applying a general principle to reach a specific conclusion about coma patients" },
      { letter: "B", text: "using a counterexample to show that a proposed requirement is not necessary" },
      { letter: "C", text: "demonstrating that the opposing view leads to a logical contradiction" },
      { letter: "D", text: "appealing to widely shared moral intuitions to support a controversial claim" },
      { letter: "E", text: "distinguishing between different types of moral obligations" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher presents coma patients as a counterexample: they cannot reciprocate obligations, yet we owe them moral consideration. This single case is sufficient to refute the general claim that reciprocity is required for moral consideration.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Director: Our theater company should produce more experimental works. Audiences today are sophisticated and eager for challenging, innovative performances that push artistic boundaries.

Producer: I disagree. Our ticket sales data shows that traditional plays consistently outperform experimental works by a margin of three to one. If we want to remain financially viable, we need to give audiences what they actually choose to see.`,
    questionStem: "The main point at issue between the director and the producer is whether",
    answerChoices: [
      { letter: "A", text: "experimental theater productions are artistically valuable" },
      { letter: "B", text: "ticket sales data is a reliable indicator of audience preferences" },
      { letter: "C", text: "producing more experimental works would serve the company's interests" },
      { letter: "D", text: "contemporary audiences are sophisticated in their theatrical tastes" },
      { letter: "E", text: "traditional plays can also be innovative and challenging" },
    ],
    correctAnswer: "C",
    explanation: "The director argues the company should produce more experimental works because audiences want them. The producer argues against this because traditional works sell better. They disagree about what the company should do—the director says yes to more experimental works, the producer says no.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Economist A: A universal basic income would benefit society by ensuring that all citizens have their basic needs met, reducing poverty and providing security during economic transitions. People would be free to pursue education, creative endeavors, or entrepreneurship without fear of destitution.

Economist B: A universal basic income would harm society by reducing the incentive to work. If people receive money without working for it, many will choose not to work at all, leading to labor shortages and reduced economic productivity.`,
    questionStem: "Economist A and Economist B disagree about whether",
    answerChoices: [
      { letter: "A", text: "a universal basic income would ensure that all citizens have their basic needs met" },
      { letter: "B", text: "some people would choose not to work if given a basic income" },
      { letter: "C", text: "a universal basic income would have a net positive effect on society" },
      { letter: "D", text: "economic productivity is important for societal well-being" },
      { letter: "E", text: "people should be free to pursue education and creative endeavors" },
    ],
    correctAnswer: "C",
    explanation: "Economist A argues UBI would benefit society; Economist B argues it would harm society. Their core disagreement is about the net effect on society. They might agree on some individual effects (like reduced work incentive) but disagree about whether overall outcomes are positive or negative.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Victim impact statements should be prohibited in sentencing hearings. Such statements introduce emotionally charged testimony that can bias judges and juries toward harsher sentences, undermining the principle that punishment should be proportional to the crime itself, not to the eloquence of those affected.

Victims' advocate: Victim impact statements are essential to the justice system. They give those harmed by crime a voice in the process and help judges understand the true human cost of criminal behavior, leading to more just and complete sentencing decisions.`,
    questionStem: "The legal scholar and the victims' advocate disagree over whether",
    answerChoices: [
      { letter: "A", text: "victim impact statements are emotionally charged" },
      { letter: "B", text: "victim impact statements help judges understand the impact of crimes" },
      { letter: "C", text: "victim impact statements lead to more just sentencing decisions" },
      { letter: "D", text: "punishment should be proportional to the crime committed" },
      { letter: "E", text: "victims should have some role in the criminal justice process" },
    ],
    correctAnswer: "C",
    explanation: "The legal scholar argues victim impact statements undermine justice by biasing sentences. The victims' advocate argues they lead to 'more just' sentencing. They directly disagree about whether these statements improve or impair the justice of sentencing decisions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All effective teachers communicate clearly. Some effective teachers use humor in their lessons. Therefore, some people who communicate clearly use humor in their lessons.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All successful businesses have good management. Some successful businesses started as family enterprises. Therefore, some businesses with good management started as family enterprises." },
      { letter: "B", text: "All marathon runners train regularly. All marathon runners have good endurance. Therefore, all people who train regularly have good endurance." },
      { letter: "C", text: "Some politicians are lawyers. All lawyers have studied law. Therefore, some politicians have studied law." },
      { letter: "D", text: "No great artists are motivated solely by money. Some great artists are unknown during their lifetimes. Therefore, no one who is motivated solely by money is unknown during their lifetime." },
      { letter: "E", text: "All roses are flowers. Some roses are red. Therefore, some flowers are not red." },
    ],
    correctAnswer: "A",
    explanation: "The original argument has the form: All A are B. Some A are C. Therefore, some B are C. Choice A follows this same pattern: All successful businesses have good management (All A are B). Some successful businesses started as family enterprises (Some A are C). Therefore, some businesses with good management started as family enterprises (Some B are C).",
    difficulty: "medium",
  },
  {
    id: "lr-bank59-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The new restaurant cannot be successful. Successful restaurants in this neighborhood are either fine dining establishments or casual family restaurants. The new restaurant is neither a fine dining establishment nor a casual family restaurant—it is a trendy gastropub.`,
    questionStem: "Which one of the following arguments is most similar in its reasoning to the argument above?",
    answerChoices: [
      { letter: "A", text: "The novel cannot win the literary prize. Prize winners are always either innovative stylists or compelling storytellers. This novel is innovative in its style. Therefore, it might win the prize." },
      { letter: "B", text: "The candidate will not win the election. Winning candidates in this district are either long-time incumbents or well-funded challengers. This candidate is neither an incumbent nor well-funded—she is a grassroots activist." },
      { letter: "C", text: "The movie will be popular. Popular movies are either action blockbusters or romantic comedies. This movie is a romantic comedy. Therefore, it will be popular." },
      { letter: "D", text: "The student may pass the exam. Students who pass are either those who study extensively or those with natural aptitude. This student has natural aptitude." },
      { letter: "E", text: "The company should expand. Successful companies either expand or improve efficiency. This company has already maximized efficiency. Therefore, it should expand." },
    ],
    correctAnswer: "B",
    explanation: "The original argument: Successful X must be either A or B. This X is neither A nor B. Therefore, this X cannot be successful. Choice B follows the same pattern: Winners must be either incumbents or well-funded. This candidate is neither. Therefore, she will not win.",
    difficulty: "hard",
  },
  {
    id: "lr-bank59-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the archaeological site contains Roman artifacts, it was occupied during the Roman period. The site does contain Roman artifacts. So it was occupied during the Roman period. Moreover, if the site was occupied during the Roman period, it is likely to contain evidence of Roman building techniques. Therefore, the site is likely to contain evidence of Roman building techniques.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If the patient has the virus, the test will be positive. The test is positive. So the patient has the virus. Furthermore, if the patient has the virus, isolation is necessary. Therefore, isolation is necessary." },
      { letter: "B", text: "If the storm arrives tonight, the roads will be dangerous. The storm may arrive tonight. So the roads may be dangerous. Additionally, if the roads are dangerous, we should stay home. Therefore, we may need to stay home." },
      { letter: "C", text: "If the company profits increase, bonuses will be paid. Profits have increased. So bonuses will be paid. However, if taxes increase, bonuses may be reduced. Taxes have increased. Therefore, bonuses may be reduced." },
      { letter: "D", text: "If the plant receives adequate sunlight, it will grow. The plant is growing. So it must be receiving adequate sunlight. Furthermore, if the plant grows, it will flower. Therefore, the plant will flower." },
      { letter: "E", text: "If the manuscript is authentic, it is valuable. If the manuscript is valuable, the museum will purchase it. The manuscript is authentic. Therefore, the museum will purchase it." },
    ],
    correctAnswer: "A",
    explanation: "The original uses two applications of modus ponens chained together: If P then Q; P; therefore Q. And If Q then R; therefore R. Choice A follows this same structure: If virus then positive test; positive test; therefore virus. If virus then isolation; therefore isolation.",
    difficulty: "hard",
  },
  {
    id: "lr-bank59-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `A recent survey of employees at a technology company found that 85 percent of those who work remotely at least three days per week report high job satisfaction. Only 60 percent of those who work in the office full-time report high job satisfaction. However, employees who work remotely were also found to work an average of 5 more hours per week than office-based employees, and those who work remotely tend to have been with the company longer.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Working remotely causes higher job satisfaction among employees" },
      { letter: "B", text: "Employees who work longer hours tend to have higher job satisfaction" },
      { letter: "C", text: "Some employees who work remotely at least three days per week do not report high job satisfaction" },
      { letter: "D", text: "Longer-tenured employees are more likely to be satisfied with remote work" },
      { letter: "E", text: "Office-based employees would be more satisfied if allowed to work remotely" },
    ],
    correctAnswer: "C",
    explanation: "If 85 percent of remote workers report high satisfaction, then 15 percent do not. Since remote workers exist (the survey found them), some must be in that 15 percent. Therefore, some remote workers do not report high job satisfaction. This must be true given the percentages.",
    difficulty: "easy",
  },
  {
    id: "lr-bank59-050",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the finance committee are also members of the board of directors. No member of the ethics committee serves on the finance committee. Patricia is on the ethics committee, and Robert is on the finance committee. The board of directors has exactly twelve members, and the finance committee has exactly five members.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Patricia is not on the board of directors" },
      { letter: "B", text: "Robert is on the board of directors" },
      { letter: "C", text: "Patricia and Robert are not both on the board of directors" },
      { letter: "D", text: "At least seven board members are not on the finance committee" },
      { letter: "E", text: "No member of the ethics committee is on the board of directors" },
    ],
    correctAnswer: "B",
    explanation: "All finance committee members are board members. Robert is on the finance committee. Therefore, Robert must be on the board of directors. This follows directly by universal instantiation: if all F are B, and Robert is F, then Robert is B.",
    difficulty: "medium",
  },
];
