// Logical Reasoning Questions Bank - Set 40
import { Question } from "../lsat-types";

export const lrQuestionsSet40: Question[] = [
  {
    id: "lr-bank40-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during the workday are more productive than those who work continuously. Therefore, companies that mandate hourly breaks for all employees will see an increase in overall productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that what is true of some employees is true of all employees" },
      { letter: "B", text: "confuses a correlation between breaks and productivity with breaks causing productivity" },
      { letter: "C", text: "fails to consider that productivity might be measured differently across companies" },
      { letter: "D", text: "ignores the possibility that some types of work require continuous focus" },
      { letter: "E", text: "overlooks the costs associated with implementing mandatory break policies" },
    ],
    correctAnswer: "B",
    explanation: "The argument observes a correlation (employees who take breaks are more productive) and concludes that mandating breaks will cause increased productivity. This is a classic correlation-causation flaw. The productive employees might take breaks because they finish tasks quickly, or there may be a third factor explaining both.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have discovered that ancient settlements near rivers were abandoned around 3000 BCE. Climate records indicate a severe drought occurred in the region at that time. The archaeologists concluded that the drought caused the inhabitants to abandon their settlements.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologists' conclusion?",
    answerChoices: [
      { letter: "A", text: "The settlements had sophisticated irrigation systems that required consistent water flow" },
      { letter: "B", text: "Other settlements in regions unaffected by drought were also abandoned around 3000 BCE" },
      { letter: "C", text: "The drought lasted for approximately fifteen years" },
      { letter: "D", text: "Archaeological evidence shows the inhabitants migrated to areas with more reliable water sources" },
      { letter: "E", text: "The settlements had been continuously occupied for over five hundred years before being abandoned" },
    ],
    correctAnswer: "D",
    explanation: "If inhabitants migrated specifically to areas with more reliable water sources, this directly supports the claim that water scarcity (caused by drought) was the reason for abandonment. This evidence shows the inhabitants' response was directly related to the water problem.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that building a new sports stadium will revitalize the downtown area. They point to Riverside City, which built a stadium five years ago and has since seen significant economic growth in its downtown district.`,
    questionStem: "Which one of the following, if true, most seriously weakens the city council's argument?",
    answerChoices: [
      { letter: "A", text: "The proposed stadium would be larger than the one in Riverside City" },
      { letter: "B", text: "Riverside City also implemented major tax incentives for downtown businesses at the same time the stadium was built" },
      { letter: "C", text: "Some residents oppose the stadium because of concerns about traffic congestion" },
      { letter: "D", text: "The city council has not yet secured full funding for the stadium project" },
      { letter: "E", text: "Downtown areas in many cities have experienced decline over the past decade" },
    ],
    correctAnswer: "B",
    explanation: "If Riverside City implemented major tax incentives simultaneously with building the stadium, the economic growth could be attributable to those incentives rather than the stadium. This alternative explanation undermines the council's inference that the stadium caused the revitalization.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martinez argues that students should not be allowed to use artificial intelligence tools for writing assignments. She notes that students who rely on such tools fail to develop critical thinking skills that are essential for success in their careers.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Critical thinking skills cannot be developed through other means besides writing assignments" },
      { letter: "B", text: "Using AI tools for writing assignments prevents students from developing critical thinking skills" },
      { letter: "C", text: "All students who use AI tools do so to avoid doing their own work" },
      { letter: "D", text: "Professor Martinez has expertise in both education and artificial intelligence" },
      { letter: "E", text: "Career success depends entirely on critical thinking skills" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that AI tools should be prohibited because students need to develop critical thinking skills. This reasoning requires the assumption that using AI tools prevents the development of these skills. Without this link, the argument falls apart.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical research has consistently shown that regular exercise reduces the risk of heart disease. However, many people find it difficult to maintain an exercise routine due to busy schedules. Therefore, employers should provide on-site fitness facilities, as this would make it easier for employees to exercise regularly and thus reduce their risk of heart disease.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Regular exercise reduces the risk of heart disease" },
      { letter: "B", text: "Many people have difficulty maintaining exercise routines" },
      { letter: "C", text: "Employers should provide on-site fitness facilities" },
      { letter: "D", text: "Employees would exercise more if fitness facilities were convenient" },
      { letter: "E", text: "Busy schedules prevent people from exercising" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is the recommendation that employers should provide on-site fitness facilities. The other statements serve as premises supporting this conclusion: exercise reduces heart disease risk, busy schedules prevent exercise, and on-site facilities would make exercise easier.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critics argue that the proposed regulation would harm small businesses. But these same critics supported similar regulations five years ago when they believed such measures would benefit their own industries. Their current opposition, therefore, is motivated by self-interest rather than genuine concern for small businesses.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing evidence that the proposed regulation would actually benefit small businesses" },
      { letter: "B", text: "questioning the critics' motives based on their inconsistent positions" },
      { letter: "C", text: "demonstrating that the critics lack expertise in economic matters" },
      { letter: "D", text: "showing that similar regulations have been successful in the past" },
      { letter: "E", text: "arguing that self-interest is never a valid basis for policy positions" },
    ],
    correctAnswer: "B",
    explanation: "The argument attacks the critics by pointing out their inconsistency: they supported similar regulations before when it benefited them but oppose them now. This is used to suggest their current opposition stems from self-interest rather than principled concern for small businesses.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The governor claims that the new education policy is working because test scores have improved since its implementation. However, test scores were already trending upward before the policy was introduced. Clearly, the governor is wrong, and the policy has had no effect on education quality.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that test scores are the only measure of education quality" },
      { letter: "B", text: "fails to consider that the policy might have accelerated an existing trend" },
      { letter: "C", text: "attacks the governor personally rather than addressing the policy" },
      { letter: "D", text: "relies on evidence that cannot be verified" },
      { letter: "E", text: "confuses correlation with causation" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the flaw of assuming that because test scores were already improving, the policy had no effect. However, the policy might have accelerated the improvement or prevented a slowdown. The prior trend does not preclude the policy from having a positive effect.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying sleep patterns found that people who sleep less than six hours per night have a higher incidence of memory problems. They hypothesize that inadequate sleep impairs the brain's ability to consolidate memories during the night.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "People who sleep more than nine hours also show some memory impairment" },
      { letter: "B", text: "Brain imaging shows that memory consolidation processes are most active during certain sleep phases" },
      { letter: "C", text: "Some people function well on less than six hours of sleep" },
      { letter: "D", text: "Memory problems become more common as people age" },
      { letter: "E", text: "Caffeine consumption is higher among people who sleep less" },
    ],
    correctAnswer: "B",
    explanation: "If brain imaging confirms that memory consolidation is most active during sleep phases, this provides direct evidence for the mechanism proposed in the hypothesis. It supports the claim that sleep is necessary for memory consolidation and explains why insufficient sleep would impair memory.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-009",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company argues that its new medication should be approved because clinical trials showed it was effective in 70 percent of patients. The company emphasizes that no other medication on the market has achieved such a high success rate for this condition.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument for approval?",
    answerChoices: [
      { letter: "A", text: "The medication requires daily administration for the rest of the patient's life" },
      { letter: "B", text: "The clinical trials excluded patients with common co-occurring conditions" },
      { letter: "C", text: "The company has successfully brought other medications to market" },
      { letter: "D", text: "Some patients experienced minor side effects during the trials" },
      { letter: "E", text: "The condition being treated affects millions of people worldwide" },
    ],
    correctAnswer: "B",
    explanation: "If the trials excluded patients with common co-occurring conditions, the 70 percent success rate may not be representative of the broader patient population. When prescribed to real-world patients who often have these conditions, the medication might be far less effective.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-010",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should not build the proposed highway extension. Highways increase traffic flow, which leads to more air pollution. Since the city has committed to reducing its carbon footprint, building the highway would be counterproductive.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "No other infrastructure projects could reduce the city's carbon footprint" },
      { letter: "B", text: "The increased traffic flow would not be offset by more efficient vehicle movement" },
      { letter: "C", text: "The city's commitment to reducing its carbon footprint is genuine" },
      { letter: "D", text: "Highways are the primary source of urban air pollution" },
      { letter: "E", text: "Public transportation is a viable alternative to highway construction" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that increased traffic flow necessarily leads to more pollution. However, if the highway reduced congestion and allowed vehicles to move more efficiently (rather than idling in traffic), it might actually reduce emissions. The argument assumes this offsetting effect would not occur.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-011",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Patel: Genetic testing for disease predisposition should be made widely available. People have a right to know their genetic risks so they can make informed health decisions.

Dr. Chen: Making such testing widely available would do more harm than good. Many people would experience severe anxiety about conditions they may never develop, and few would take meaningful preventive action.`,
    questionStem: "The main point at issue between Dr. Patel and Dr. Chen is",
    answerChoices: [
      { letter: "A", text: "whether genetic testing can accurately predict disease predisposition" },
      { letter: "B", text: "whether the benefits of widespread genetic testing outweigh the potential harms" },
      { letter: "C", text: "whether people have a right to access their own genetic information" },
      { letter: "D", text: "whether anxiety is a common response to learning about genetic risks" },
      { letter: "E", text: "whether preventive health measures are generally effective" },
    ],
    correctAnswer: "B",
    explanation: "Dr. Patel argues that genetic testing should be widely available because of its benefits (informed decisions), while Dr. Chen argues it would do more harm than good (anxiety, little preventive action). They disagree about whether the overall impact of widespread testing would be positive or negative.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-012",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All successful entrepreneurs take calculated risks. Maria takes calculated risks. Therefore, Maria is a successful entrepreneur.`,
    questionStem: "Which one of the following arguments contains flawed reasoning most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All doctors have medical degrees. John has a medical degree. Therefore, John is a doctor." },
      { letter: "B", text: "All cats are mammals. Whiskers is a mammal. Therefore, Whiskers is a cat." },
      { letter: "C", text: "All rectangles have four sides. This shape has four sides. Therefore, this shape is a rectangle." },
      { letter: "D", text: "All musicians practice regularly. Sarah practices regularly. Therefore, Sarah is a musician." },
      { letter: "E", text: "All of the above contain similar reasoning." },
    ],
    correctAnswer: "D",
    explanation: "The original argument commits the fallacy of affirming the consequent: All A are B; X is B; therefore X is A. Answer D has the same structure: All musicians practice regularly (All A are B); Sarah practices regularly (X is B); therefore Sarah is a musician (X is A). Other answers have similar structures but D matches the categories most closely.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-013",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The committee should reject the proposed environmental regulation. Environmental groups support the regulation, and these groups have consistently advocated for policies that harm economic growth. Therefore, this regulation would also harm economic growth.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that economic growth is more important than environmental protection" },
      { letter: "B", text: "fails to provide evidence that past environmental policies actually harmed economic growth" },
      { letter: "C", text: "attacks the supporters of the regulation rather than evaluating the regulation itself" },
      { letter: "D", text: "ignores the possibility that the regulation might benefit certain economic sectors" },
      { letter: "E", text: "relies on an overly broad definition of economic harm" },
    ],
    correctAnswer: "C",
    explanation: "This is an ad hominem attack or guilt by association. The argument rejects the regulation based on who supports it rather than on the merits of the regulation itself. Even if environmental groups had previously supported harmful policies, that does not mean this particular regulation would be harmful.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A wildlife biologist argues that the decline in the local deer population is due to the recent introduction of wolves to the area. The deer population has dropped by 30 percent since wolves were reintroduced three years ago.`,
    questionStem: "Which one of the following, if true, most strengthens the biologist's argument?",
    answerChoices: [
      { letter: "A", text: "Wolves are known to prey primarily on deer in similar ecosystems" },
      { letter: "B", text: "The deer population had been stable for the decade prior to wolf reintroduction" },
      { letter: "C", text: "Some deer have migrated to adjacent areas without wolves" },
      { letter: "D", text: "The local deer population is still larger than in many other regions" },
      { letter: "E", text: "Hunters in the area have reduced their annual deer harvest" },
    ],
    correctAnswer: "B",
    explanation: "If the deer population was stable for a decade before wolf reintroduction and then declined 30 percent after, this suggests the wolves are indeed the cause of the decline. The stability rules out other factors that might have been causing a gradual decline.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Studies show that students who participate in extracurricular activities have higher grade point averages than those who do not. Schools should therefore require all students to participate in at least one extracurricular activity to improve academic performance.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some extracurricular activities are more time-intensive than others" },
      { letter: "B", text: "Students who choose to participate in extracurricular activities tend to be more motivated academically to begin with" },
      { letter: "C", text: "Many schools lack funding for a wide variety of extracurricular activities" },
      { letter: "D", text: "Grade point averages are not the only measure of academic success" },
      { letter: "E", text: "Some students prefer individual activities to group activities" },
    ],
    correctAnswer: "B",
    explanation: "If students who participate in extracurricular activities are already more academically motivated, the correlation between activities and grades might be due to this pre-existing motivation rather than the activities themselves. Forcing unmotivated students to participate would not create the same academic benefits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-016",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of embezzlement. Embezzlement requires intentional misappropriation of funds, and the defendant genuinely believed she had authorization to transfer the money to her personal account.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The defendant's belief about her authorization was sincere" },
      { letter: "B", text: "A genuine belief in authorization precludes the intent required for embezzlement" },
      { letter: "C", text: "The defendant did not actually have authorization for the transfer" },
      { letter: "D", text: "Embezzlement is the most serious charge that could apply to the defendant's actions" },
      { letter: "E", text: "The defendant's employer should have been clearer about authorization policies" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from the premise that the defendant believed she had authorization to the conclusion that she lacked the intent required for embezzlement. This requires the assumption that a genuine belief in authorization eliminates the intent element of the crime.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-017",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some argue that autonomous vehicles will never be safe enough for widespread use because they cannot replicate human judgment in complex situations. However, human judgment causes over 90 percent of traffic accidents. If autonomous vehicles can reduce accidents even modestly, they would represent a significant safety improvement.`,
    questionStem: "The argument counters the objection to autonomous vehicles by",
    answerChoices: [
      { letter: "A", text: "demonstrating that autonomous vehicles can replicate human judgment" },
      { letter: "B", text: "showing that the standard of comparison assumed by the objection is inappropriate" },
      { letter: "C", text: "questioning the credentials of those who oppose autonomous vehicles" },
      { letter: "D", text: "providing statistical evidence that autonomous vehicles have fewer accidents" },
      { letter: "E", text: "arguing that complex situations are rare in typical driving conditions" },
    ],
    correctAnswer: "B",
    explanation: "The objection implies that autonomous vehicles should match human judgment. The argument counters by pointing out that human judgment causes most accidents, so matching it is not the right standard. Even imperfect autonomous vehicles could be safer than human drivers.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-018",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The proposed tax on sugary beverages will not reduce obesity rates. When a similar tax was implemented in neighboring Millbrook County, obesity rates did not decline significantly within the first year. This proves that such taxes are ineffective at changing behavior.`,
    questionStem: "The argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "assumes that Millbrook County is representative of all communities" },
      { letter: "B", text: "relies on too short a time period to assess the policy's effectiveness" },
      { letter: "C", text: "fails to consider other benefits of reducing sugary beverage consumption" },
      { letter: "D", text: "ignores the possibility that obesity rates might have increased without the tax" },
      { letter: "E", text: "does not specify the amount of the tax implemented in Millbrook County" },
    ],
    correctAnswer: "B",
    explanation: "The argument bases its conclusion on only one year of data. Behavioral changes and their health effects, especially regarding obesity, often take much longer to manifest. A year is insufficient to determine whether a tax will ultimately be effective.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-019",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Courts should interpret constitutional provisions according to their original meaning at the time of adoption. Only this approach ensures that judges apply the law rather than impose their own policy preferences on society.`,
    questionStem: "Which one of the following, if true, most strengthens the legal scholar's argument?",
    answerChoices: [
      { letter: "A", text: "The framers of the constitution intended for it to be interpreted according to its original meaning" },
      { letter: "B", text: "Non-originalist interpretations have historically correlated with judges' personal political views" },
      { letter: "C", text: "Some constitutional provisions have clear and undisputed original meanings" },
      { letter: "D", text: "Most democratic nations use originalist constitutional interpretation" },
      { letter: "E", text: "Originalist interpretation sometimes produces outcomes that conflict with current popular opinion" },
    ],
    correctAnswer: "B",
    explanation: "The scholar's argument is that originalism prevents judges from imposing personal preferences. If non-originalist interpretations have historically aligned with judges' political views, this supports the claim that alternatives to originalism do allow personal preferences to influence decisions.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Company executives argue that the firm should relocate its headquarters to a state with lower corporate taxes. They calculate that the move would save the company $5 million annually in tax payments.`,
    questionStem: "Which one of the following, if true, most seriously weakens the executives' argument for relocation?",
    answerChoices: [
      { letter: "A", text: "The new state has less developed infrastructure than the current location" },
      { letter: "B", text: "Many employees have stated they would not relocate with the company" },
      { letter: "C", text: "Relocation costs, combined with anticipated employee turnover and recruitment expenses, would exceed $50 million" },
      { letter: "D", text: "Other companies in the industry have recently relocated to the same low-tax state" },
      { letter: "E", text: "The current state is considering reducing its corporate tax rates" },
    ],
    correctAnswer: "C",
    explanation: "If relocation would cost over $50 million while saving only $5 million annually, it would take more than 10 years just to break even. The immediate costs far outweigh the projected annual savings, making the financial argument for relocation weak.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-021",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The new public transit system will reduce traffic congestion. After all, surveys show that 40 percent of current drivers say they would use public transit if it were more convenient, and the new system will be significantly more convenient than the current one.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Traffic congestion is caused primarily by insufficient public transit options" },
      { letter: "B", text: "At least some of the drivers who say they would use more convenient transit will actually do so" },
      { letter: "C", text: "The new transit system will be completed on schedule" },
      { letter: "D", text: "Reducing traffic congestion is the primary goal of the new transit system" },
      { letter: "E", text: "The surveys accurately measured the percentage of drivers willing to switch to transit" },
    ],
    correctAnswer: "B",
    explanation: "The argument relies on survey responses about what drivers would do. It assumes that at least some of these stated intentions will translate into actual behavior change. If no one follows through on their stated intentions, the transit system would not reduce congestion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-022",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Historical evidence shows that economic sanctions rarely achieve their stated political goals. Sanctions often harm ordinary citizens while leaving political leaders largely unaffected. Moreover, sanctions can strengthen authoritarian regimes by allowing them to blame external forces for economic hardship. The international community should therefore seek alternative diplomatic tools.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Economic sanctions harm ordinary citizens more than political leaders" },
      { letter: "B", text: "Authoritarian regimes exploit sanctions to strengthen their control" },
      { letter: "C", text: "Economic sanctions rarely achieve their stated political goals" },
      { letter: "D", text: "The international community should seek alternative diplomatic tools" },
      { letter: "E", text: "Diplomatic solutions are more effective than economic sanctions" },
    ],
    correctAnswer: "D",
    explanation: "The conclusion is signaled by 'therefore' - the international community should seek alternative diplomatic tools. All the other statements are premises supporting this conclusion by showing why sanctions are ineffective or counterproductive.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-023",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Many argue that moral truths cannot exist because people across cultures disagree about ethical issues. But this reasoning is flawed. People also disagree about scientific facts, yet we do not conclude that scientific truths do not exist. Disagreement about a subject does not prove that there are no truths in that domain.`,
    questionStem: "The philosopher's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing examples of moral truths that are universally accepted" },
      { letter: "B", text: "demonstrating that ethical disagreements are less fundamental than they appear" },
      { letter: "C", text: "showing that a principle underlying an argument leads to an unacceptable conclusion when applied elsewhere" },
      { letter: "D", text: "arguing that moral and scientific claims are fundamentally similar" },
      { letter: "E", text: "questioning whether cultural disagreement about ethics actually exists" },
    ],
    correctAnswer: "C",
    explanation: "The philosopher uses an analogy to show the weakness of the reasoning. The principle 'disagreement proves no truth exists' would also imply that scientific truths do not exist, which is an unacceptable conclusion. This reductio ad absurdum approach exposes the flaw in the original reasoning.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-024",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Critics of the mayor's housing policy point to the fact that housing costs have increased during her tenure. But housing costs have increased in every major city over the same period due to national economic trends. Therefore, the mayor's housing policy has been successful.`,
    questionStem: "The argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that all major cities have implemented similar housing policies" },
      { letter: "B", text: "fails to consider that housing costs might have increased less under different policies" },
      { letter: "C", text: "ignores other measures of housing policy success besides cost" },
      { letter: "D", text: "relies on an appeal to the mayor's authority" },
      { letter: "E", text: "concludes that a policy is successful merely because it is not entirely responsible for a negative outcome" },
    ],
    correctAnswer: "E",
    explanation: "The argument only establishes that the mayor's policy is not entirely to blame for rising costs (since costs rose everywhere). It then incorrectly leaps to the conclusion that the policy was successful. Not being the cause of a problem is not the same as being successful.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-025",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The implementation of a universal basic income would not significantly reduce workforce participation. In trials conducted in several countries, recipients of basic income payments continued to work at nearly the same rates as non-recipients.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "The payments in the trials were sufficient to cover basic living expenses" },
      { letter: "B", text: "Participants in the trials were required to report their employment status regularly" },
      { letter: "C", text: "Most participants in the trials were already employed before receiving payments" },
      { letter: "D", text: "The trials lasted long enough for participants to adjust their long-term behavior" },
      { letter: "E", text: "Similar trials in other countries showed slightly lower workforce participation" },
    ],
    correctAnswer: "D",
    explanation: "A concern about short-term trials is that participants might not change behavior because they know the payments are temporary. If the trials lasted long enough for participants to adjust their long-term behavior, the finding that they continued working is more reliable evidence about permanent program effects.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The technology company claims its new smartphone battery lasts 25 percent longer than previous models. They base this claim on tests conducted under controlled laboratory conditions using standardized testing protocols.`,
    questionStem: "Which one of the following, if true, most seriously weakens the company's claim as it applies to actual consumer use?",
    answerChoices: [
      { letter: "A", text: "Independent laboratories verified the company's testing results" },
      { letter: "B", text: "The standardized protocols do not account for battery drain from commonly used applications" },
      { letter: "C", text: "The previous battery model was considered adequate by most consumers" },
      { letter: "D", text: "Competitors have made similar claims about their new batteries" },
      { letter: "E", text: "The new battery uses more expensive materials than the previous model" },
    ],
    correctAnswer: "B",
    explanation: "If the standardized protocols do not account for commonly used applications, the laboratory results may not reflect real-world performance. Consumers using typical applications might not experience the 25 percent improvement because their usage differs significantly from the controlled testing conditions.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum should not return the ancient artifacts to their countries of origin. These artifacts are irreplaceable cultural treasures that must be preserved in climate-controlled environments. The museum provides ideal conditions for preservation, while the countries of origin often lack such facilities.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The countries of origin have not requested the return of the artifacts" },
      { letter: "B", text: "The museum acquired the artifacts through legitimate means" },
      { letter: "C", text: "Preservation concerns can legitimately override ownership claims" },
      { letter: "D", text: "Climate-controlled environments are necessary for artifact preservation" },
      { letter: "E", text: "The museum allows public access to the artifacts" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that artifacts should not be returned because the museum can better preserve them. This assumes that preservation considerations are a legitimate basis for denying ownership claims. Without this assumption, the preservation capabilities would be irrelevant to the question of return.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-028",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Journalist: Social media platforms should be required to verify the identity of all users. Anonymous accounts are frequently used to spread misinformation and harassment.

Civil liberties advocate: Such verification requirements would undermine free speech. Many people, including political dissidents and abuse victims, rely on anonymity to express themselves safely.`,
    questionStem: "The journalist and the civil liberties advocate disagree about whether",
    answerChoices: [
      { letter: "A", text: "anonymous accounts are sometimes used for harmful purposes" },
      { letter: "B", text: "some people have legitimate reasons to remain anonymous online" },
      { letter: "C", text: "social media platforms currently verify user identities" },
      { letter: "D", text: "the benefits of mandatory identity verification outweigh its costs" },
      { letter: "E", text: "political dissidents need protection from government surveillance" },
    ],
    correctAnswer: "D",
    explanation: "The journalist believes the harm from anonymous accounts justifies verification requirements. The civil liberties advocate believes the speech concerns outweigh the benefits. They disagree about whether the overall balance favors verification. Both might agree that anonymity has both benefits and costs.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-029",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the company adopts the new safety protocols, it will avoid regulatory fines. The company did avoid regulatory fines this year. Therefore, the company must have adopted the new safety protocols.`,
    questionStem: "The pattern of flawed reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If it rains, the streets will be wet. The streets are wet. Therefore, it must have rained." },
      { letter: "B", text: "If the train is on time, we will arrive before noon. The train is on time. Therefore, we will arrive before noon." },
      { letter: "C", text: "All mammals are warm-blooded. Dogs are mammals. Therefore, dogs are warm-blooded." },
      { letter: "D", text: "If we do not study, we will fail the exam. We studied. Therefore, we will not fail the exam." },
      { letter: "E", text: "Either we take the highway or we take surface streets. We did not take the highway. Therefore, we took surface streets." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments commit the fallacy of affirming the consequent. The structure is: If P, then Q. Q occurred. Therefore, P. The original says: If new protocols, then no fines. No fines occurred. Therefore, new protocols. Answer A has the same structure: If rain, then wet streets. Wet streets. Therefore, rain.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-030",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical industry spends billions on advertising, which ultimately gets passed on to consumers through higher drug prices. This massive advertising expenditure proves that pharmaceutical companies prioritize profits over patient welfare.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that all advertising expenditures are wasteful" },
      { letter: "B", text: "fails to consider that advertising might inform patients about beneficial treatments" },
      { letter: "C", text: "presumes that any action that increases profits cannot also benefit patients" },
      { letter: "D", text: "overlooks the research and development costs incurred by pharmaceutical companies" },
      { letter: "E", text: "relies on an emotional appeal rather than factual evidence" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that because advertising increases profits (through higher prices), it must be prioritizing profits over patient welfare. This creates a false dichotomy. Advertising could both generate profits and benefit patients by informing them about helpful treatments.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-031",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the city council who voted for the budget increase are up for reelection this year. Some members of the city council did not vote for the budget increase. Every council member who is up for reelection has received campaign contributions from local businesses.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All members of the city council have received campaign contributions from local businesses" },
      { letter: "B", text: "Some members who received campaign contributions from local businesses did not vote for the budget increase" },
      { letter: "C", text: "No member who voted against the budget increase is up for reelection" },
      { letter: "D", text: "Some members of the city council who voted for the budget increase received campaign contributions from local businesses" },
      { letter: "E", text: "All members who voted for the budget increase are receiving campaign contributions from local businesses" },
    ],
    correctAnswer: "E",
    explanation: "We know: (1) All who voted for the increase are up for reelection, and (2) All who are up for reelection received contributions. Therefore, all who voted for the increase are receiving contributions from local businesses. This is a valid chain of reasoning.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Children who learn to play musical instruments show enhanced mathematical abilities compared to children who do not receive musical training. This suggests that musical training directly improves the brain's capacity for mathematical reasoning.`,
    questionStem: "Which one of the following, if true, most strengthens the psychologist's reasoning?",
    answerChoices: [
      { letter: "A", text: "Children who excel in mathematics often choose to learn musical instruments" },
      { letter: "B", text: "Musical training and mathematical reasoning engage overlapping regions of the brain" },
      { letter: "C", text: "Parents who encourage musical training also tend to emphasize academic achievement" },
      { letter: "D", text: "Some mathematical concepts can be expressed in musical notation" },
      { letter: "E", text: "Professional musicians score higher on mathematics tests than the general population" },
    ],
    correctAnswer: "B",
    explanation: "If musical training and mathematical reasoning use overlapping brain regions, this provides a plausible mechanism for how musical training could directly improve mathematical abilities. This neurological connection supports the claim of a causal relationship.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-033",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The senator argues that the proposed carbon tax would devastate the national economy. She points to economic models suggesting the tax would reduce GDP growth by 2 percent over five years.`,
    questionStem: "Which one of the following, if true, most seriously weakens the senator's argument?",
    answerChoices: [
      { letter: "A", text: "The carbon tax has been endorsed by several prominent economists" },
      { letter: "B", text: "Some industries would benefit from the transition to cleaner energy sources" },
      { letter: "C", text: "The economic models used do not account for the costs of climate change damage that the tax would help prevent" },
      { letter: "D", text: "Other countries have implemented carbon taxes with varying results" },
      { letter: "E", text: "The proposed tax rate is lower than what environmentalists originally requested" },
    ],
    correctAnswer: "C",
    explanation: "If the models ignore the economic costs of climate change that the tax would help prevent, they present an incomplete picture. The 2 percent GDP reduction might be offset or exceeded by the economic benefits of avoiding climate damage, making the 'devastation' claim misleading.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Restaurant reviewer: The new Italian restaurant is clearly overrated. I visited on a Saturday night and found the pasta overcooked and the service slow. Any restaurant that cannot deliver quality on its busiest night does not deserve its stellar reputation.`,
    questionStem: "The argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "Saturday night is the restaurant's busiest night" },
      { letter: "B", text: "the reviewer is qualified to judge Italian cuisine" },
      { letter: "C", text: "pasta quality is the most important criterion for evaluating an Italian restaurant" },
      { letter: "D", text: "one visit is sufficient to assess a restaurant's overall quality" },
      { letter: "E", text: "the restaurant has received positive reviews from other critics" },
    ],
    correctAnswer: "D",
    explanation: "The reviewer concludes the restaurant is overrated based on a single visit. This reasoning requires the assumption that one visit provides enough evidence to fairly assess the restaurant's overall quality. Otherwise, the negative experience could be an anomaly.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-035",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: People should eat more whole grains because studies show that populations consuming high-whole-grain diets have lower rates of heart disease. When researchers analyzed the diets of long-lived populations around the world, whole grains were consistently present.`,
    questionStem: "The nutritionist's reasoning is most vulnerable to which one of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It fails to specify what counts as a whole grain" },
      { letter: "B", text: "It overlooks other dietary factors that might explain the health outcomes" },
      { letter: "C", text: "It assumes that what is true of populations is true of individuals" },
      { letter: "D", text: "It does not consider the cost and availability of whole grains" },
      { letter: "E", text: "It relies on research that has not been peer-reviewed" },
    ],
    correctAnswer: "B",
    explanation: "The argument attributes the health benefits to whole grains, but populations with high whole grain consumption might also have other healthy dietary habits (more vegetables, less processed food) or lifestyle factors that explain their lower heart disease rates.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-036",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The painting attributed to Vermeer is actually a forgery. While the pigments are consistent with the 17th century, the canvas weave pattern matches machine-made canvas from the 20th century, which was not available during Vermeer's lifetime.`,
    questionStem: "Which one of the following, if true, most strengthens the art historian's conclusion?",
    answerChoices: [
      { letter: "A", text: "Vermeer is known to have experimented with unusual artistic techniques" },
      { letter: "B", text: "The canvas has never been restored or repaired since its creation" },
      { letter: "C", text: "Sophisticated forgers can replicate 17th-century pigments but rarely attend to canvas details" },
      { letter: "D", text: "Other paintings from Vermeer's studio use hand-woven canvas" },
      { letter: "E", text: "The painting's provenance cannot be traced before 1920" },
    ],
    correctAnswer: "B",
    explanation: "If the canvas has never been repaired, the machine-made weave pattern must be original to the painting. This eliminates the possibility that a genuine Vermeer was later placed on a newer canvas during restoration, strongly supporting the forgery conclusion.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-037",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `City planner: Converting downtown parking lots to green spaces would reduce the urban heat island effect. Studies in other cities have shown that replacing paved surfaces with vegetation can lower local temperatures by several degrees during summer months.`,
    questionStem: "Which one of the following, if true, most weakens the planner's reasoning as applied to this particular city?",
    answerChoices: [
      { letter: "A", text: "The city already has several large parks in residential neighborhoods" },
      { letter: "B", text: "The city's downtown area is surrounded by ocean water that already moderates summer temperatures" },
      { letter: "C", text: "Maintaining green spaces requires significant municipal resources" },
      { letter: "D", text: "Some residents oppose losing parking spaces in the downtown area" },
      { letter: "E", text: "The studies were conducted in cities with different climates" },
    ],
    correctAnswer: "B",
    explanation: "If the ocean already moderates downtown temperatures, the urban heat island effect may not be a significant problem in this city. The benefits seen in other cities might not apply here because the baseline conditions are different, weakening the case for converting parking lots.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-038",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: The incumbent will likely win reelection. Historically, incumbents with approval ratings above 50 percent have won reelection 90 percent of the time. The current incumbent's approval rating is 54 percent.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The incumbent's approval rating will not drop significantly before the election" },
      { letter: "B", text: "Historical patterns always predict future outcomes" },
      { letter: "C", text: "Approval ratings are the only factor that determines election outcomes" },
      { letter: "D", text: "The current political environment is similar to historical election cycles" },
      { letter: "E", text: "The incumbent will run a competent campaign" },
    ],
    correctAnswer: "A",
    explanation: "The argument uses the current approval rating to predict election outcomes, but elections occur in the future. This reasoning assumes the approval rating will remain above 50 percent. If it drops significantly, the historical pattern would no longer apply.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-039",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `While some argue that zoos are unethical because they confine wild animals, modern zoos contribute significantly to conservation efforts. Many endangered species have been saved from extinction through captive breeding programs. Additionally, zoos educate millions of visitors annually about wildlife conservation. The benefits to species preservation and public education justify the existence of well-managed zoos.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Some people believe zoos are unethical" },
      { letter: "B", text: "Modern zoos contribute significantly to conservation efforts" },
      { letter: "C", text: "Endangered species have been saved through captive breeding" },
      { letter: "D", text: "The benefits to species preservation and public education justify well-managed zoos" },
      { letter: "E", text: "Zoos educate millions of visitors about conservation" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is the final sentence, which states that the benefits justify the existence of well-managed zoos. The conservation efforts, captive breeding success, and education are premises that support this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Opponents of the minimum wage increase claim it will cause significant job losses. However, economists examined data from states that raised their minimum wages and found employment levels remained stable or even increased. The prediction of mass job losses is therefore unfounded.`,
    questionStem: "The argument relies primarily on which one of the following strategies?",
    answerChoices: [
      { letter: "A", text: "Questioning the qualifications of the opponents" },
      { letter: "B", text: "Using empirical evidence to challenge a prediction" },
      { letter: "C", text: "Demonstrating logical inconsistencies in the opponents' reasoning" },
      { letter: "D", text: "Appealing to the authority of economic experts" },
      { letter: "E", text: "Showing that the opponents have ulterior motives" },
    ],
    correctAnswer: "B",
    explanation: "The argument counters the prediction of job losses by presenting empirical data from states that actually raised minimum wages. This real-world evidence showing stable or increased employment directly challenges the theoretical prediction.",
    difficulty: "easy",
  },
  {
    id: "lr-bank40-041",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The university should eliminate its philosophy department. A survey of recent graduates found that philosophy majors have the lowest starting salaries of any major. Education should prepare students for financial success, and philosophy clearly fails in this regard.`,
    questionStem: "The argument is most vulnerable to criticism on which one of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It uses starting salary as the only measure of a major's value" },
      { letter: "B", text: "It assumes all philosophy majors intend to pursue careers in philosophy" },
      { letter: "C", text: "It fails to consider the historical importance of philosophy in education" },
      { letter: "D", text: "It does not specify how much lower philosophy majors' salaries are" },
      { letter: "E", text: "It ignores the possibility that philosophy develops valuable critical thinking skills" },
    ],
    correctAnswer: "A",
    explanation: "The argument equates educational value solely with financial success as measured by starting salaries. This ignores other legitimate educational goals such as developing critical thinking, ethical reasoning, or pursuing knowledge for its own sake.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-042",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Environmental scientist: The recent decline in bee populations is primarily caused by the use of neonicotinoid pesticides. Bee populations have declined most sharply in agricultural regions where these pesticides are heavily used.`,
    questionStem: "Which one of the following, if true, most strengthens the scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Neonicotinoid pesticides are more effective at controlling crop pests than older pesticides" },
      { letter: "B", text: "Laboratory studies show that even low doses of neonicotinoids impair bees' navigation and foraging abilities" },
      { letter: "C", text: "Bee populations have declined worldwide, not just in agricultural regions" },
      { letter: "D", text: "Some farmers have voluntarily stopped using neonicotinoid pesticides" },
      { letter: "E", text: "Other factors, such as habitat loss, also contribute to bee population decline" },
    ],
    correctAnswer: "B",
    explanation: "Laboratory evidence showing that neonicotinoids harm bee functioning provides a direct mechanistic link between the pesticides and bee decline. This strengthens the causal claim by showing how the pesticides could be causing the observed population decline.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-043",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Marketing director: Our new advertising campaign has been highly successful. Since the campaign launched three months ago, our sales have increased by 15 percent compared to the same period last year.`,
    questionStem: "Which one of the following, if true, most seriously weakens the marketing director's claim?",
    answerChoices: [
      { letter: "A", text: "The advertising campaign cost more than any previous campaign" },
      { letter: "B", text: "Sales for competitors in the industry increased by an average of 20 percent over the same period" },
      { letter: "C", text: "The company also improved its product quality during this period" },
      { letter: "D", text: "The advertising campaign targeted a younger demographic than previous campaigns" },
      { letter: "E", text: "Consumer spending in general has increased over the past year" },
    ],
    correctAnswer: "B",
    explanation: "If competitors saw even greater sales increases (20 percent vs. 15 percent) during the same period, the company's campaign may actually be underperforming relative to the market. The sales increase might be due to general market growth rather than campaign effectiveness.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-044",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Jury instructions that are written in plain language improve juror comprehension and lead to fairer verdicts. Courts should therefore adopt plain-language jury instructions to improve the quality of justice.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Jurors are currently unable to understand legal terminology" },
      { letter: "B", text: "Better juror comprehension results in fairer verdicts" },
      { letter: "C", text: "Lawyers would support the adoption of plain-language instructions" },
      { letter: "D", text: "Current jury instructions are written in unnecessarily complex language" },
      { letter: "E", text: "Plain-language instructions can convey all necessary legal concepts" },
    ],
    correctAnswer: "E",
    explanation: "The argument recommends plain-language instructions to improve comprehension and fairness. This assumes that plain language can adequately convey the legal concepts jurors need to understand. If some concepts cannot be translated into plain language, the recommendation might compromise legal accuracy.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Scientist A: Climate models predict that global temperatures will rise by 2 to 4 degrees Celsius by 2100. These models have been validated against historical data and represent our best understanding of climate dynamics.

Scientist B: Climate models have consistently underestimated the rate of ice sheet melting and sea level rise. We cannot rely on these models to predict future climate conditions accurately.`,
    questionStem: "Scientist A and Scientist B disagree about whether",
    answerChoices: [
      { letter: "A", text: "global temperatures will rise by some amount by 2100" },
      { letter: "B", text: "climate models have been tested against historical data" },
      { letter: "C", text: "current climate models provide reliable predictions" },
      { letter: "D", text: "ice sheet melting is occurring faster than expected" },
      { letter: "E", text: "climate science should continue to refine its models" },
    ],
    correctAnswer: "C",
    explanation: "Scientist A claims the models represent our best understanding and are validated, implying they are reliable. Scientist B argues the models have underestimated key factors and cannot be relied upon. Their core disagreement is about whether current models provide reliable predictions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No one who regularly exercises is significantly overweight. Some people who eat healthy diets are significantly overweight. Therefore, some people who eat healthy diets do not regularly exercise.`,
    questionStem: "The pattern of reasoning in the argument above is most closely paralleled by which one of the following?",
    answerChoices: [
      { letter: "A", text: "No one who studies hard fails the exam. Some people who attend every class fail the exam. Therefore, some people who attend every class do not study hard." },
      { letter: "B", text: "All people who study hard pass the exam. Some people who pass the exam did not study hard. Therefore, studying hard is not the only way to pass." },
      { letter: "C", text: "No one who is rich is unhappy. Some people who are famous are rich. Therefore, some famous people are not unhappy." },
      { letter: "D", text: "All cats are mammals. Some mammals are not cats. Therefore, there exist non-cat mammals." },
      { letter: "E", text: "No birds are mammals. All eagles are birds. Therefore, no eagles are mammals." },
    ],
    correctAnswer: "A",
    explanation: "The original argument has the structure: No A is C. Some B is C. Therefore, some B is not A. Answer A matches this exactly: No studying hard (A) leads to failing (C). Some attending class (B) leads to failing (C). Therefore, some attending class (B) don't study hard (not A).",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-047",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The proposal to build affordable housing in the suburban district must be rejected. A survey of district residents found that 70 percent oppose the project. In a democracy, the will of the majority should prevail.`,
    questionStem: "The argument is most vulnerable to criticism on which of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It assumes that survey respondents accurately represent all district residents" },
      { letter: "B", text: "It fails to consider that majority preferences do not always reflect good policy" },
      { letter: "C", text: "It ignores the interests of those who would benefit from affordable housing" },
      { letter: "D", text: "It provides no evidence about why residents oppose the project" },
      { letter: "E", text: "It conflates local opinion with democratic principles" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that majority preference should determine policy, but democratic governance also involves protecting minority rights and making good policy decisions. Majority opposition does not necessarily mean the policy is wrong, especially when it affects a vulnerable group needing housing.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-048",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: The rise of social media has led to increased political polarization. People on social media tend to follow accounts that share their existing views and avoid exposure to opposing perspectives, creating echo chambers that reinforce and intensify their positions.`,
    questionStem: "Which one of the following, if true, most strengthens the sociologist's argument?",
    answerChoices: [
      { letter: "A", text: "Political polarization has been increasing since before social media became widespread" },
      { letter: "B", text: "Studies show that people who use social media less frequently hold more moderate political views" },
      { letter: "C", text: "Social media platforms use algorithms that prioritize content similar to what users have previously engaged with" },
      { letter: "D", text: "Television news programs also tend to present politically slanted perspectives" },
      { letter: "E", text: "Some social media users intentionally seek out diverse viewpoints" },
    ],
    correctAnswer: "C",
    explanation: "If platforms algorithmically promote content similar to what users have engaged with, this mechanism actively creates and reinforces the echo chambers described. This supports the claim that social media structurally contributes to polarization.",
    difficulty: "medium",
  },
  {
    id: "lr-bank40-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `A book can only become a bestseller if it receives positive reviews from major publications. A book that receives positive reviews from major publications will attract attention from book clubs. Any book that attracts attention from book clubs will see increased sales.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "If a book sees increased sales, it received positive reviews from major publications" },
      { letter: "B", text: "If a book becomes a bestseller, it will see increased sales" },
      { letter: "C", text: "If a book does not attract attention from book clubs, it cannot become a bestseller" },
      { letter: "D", text: "All books that receive positive reviews from major publications become bestsellers" },
      { letter: "E", text: "A book cannot see increased sales without becoming a bestseller" },
    ],
    correctAnswer: "B",
    explanation: "If a book becomes a bestseller, it must have received positive reviews (necessary condition). Positive reviews lead to book club attention, which leads to increased sales. Therefore, every bestseller must have seen increased sales through this chain of causation.",
    difficulty: "hard",
  },
  {
    id: "lr-bank40-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Attorney: The witness's testimony should be given little weight. She claims she saw the defendant at the scene at 8 PM, but records show she made a phone call from her home at 7:55 PM. It is highly unlikely she could have traveled from her home to the scene in just five minutes.`,
    questionStem: "The reasoning in the attorney's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes the witness has no motive to lie about what she saw" },
      { letter: "B", text: "fails to consider that the witness might have made an error about the exact time" },
      { letter: "C", text: "does not establish that the witness was actually at home when the call was made" },
      { letter: "D", text: "ignores the possibility that the defendant was also at the scene earlier" },
      { letter: "E", text: "attacks the witness's credibility rather than the substance of her testimony" },
    ],
    correctAnswer: "C",
    explanation: "The attorney assumes the witness was at home when she made the 7:55 PM call. However, phone calls can be made from cell phones while traveling. The witness could have been en route to or near the scene when making the call, making her 8 PM observation entirely plausible.",
    difficulty: "hard",
  },
];
