// Logical Reasoning Questions Bank - Set 65
import { Question } from "../lsat-types";

export const lrQuestionsSet65: Question[] = [
  {
    id: "lr-bank65-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that people who drink three or more cups of coffee per day have lower rates of depression than those who drink no coffee. Therefore, drinking coffee prevents depression.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that the study may have been funded by coffee companies" },
      { letter: "B", text: "assumes that a correlation between two phenomena establishes that one causes the other" },
      { letter: "C", text: "relies on a sample that is too small to be representative" },
      { letter: "D", text: "ignores the possibility that coffee has other health effects" },
      { letter: "E", text: "fails to define what counts as a cup of coffee" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the classic correlation-causation fallacy. Just because coffee drinking and lower depression rates occur together does not mean coffee drinking causes the lower rates. It could be that people who are not depressed are more likely to drink coffee, or that some third factor causes both.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Critics claim that the new environmental regulations will harm small businesses. But these critics are all representatives of large corporations that stand to benefit if small competitors are not protected by the same regulations. Therefore, the regulations will not harm small businesses.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that large corporations may also be harmed by the regulations" },
      { letter: "B", text: "assumes that what is true of large corporations is also true of small businesses" },
      { letter: "C", text: "rejects a claim based solely on the source of that claim rather than addressing its merits" },
      { letter: "D", text: "presumes that environmental regulations are always beneficial" },
      { letter: "E", text: "ignores the possibility that the critics have studied the issue carefully" },
    ],
    correctAnswer: "C",
    explanation: "This is an ad hominem fallacy. The argument attacks the source of the criticism (representatives of large corporations) rather than addressing whether the criticism itself is valid. Even if the critics have ulterior motives, their claim about harm to small businesses could still be true.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-003",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have discovered that ancient Mesopotamian cities had sophisticated drainage systems. These drainage systems required complex engineering knowledge to design and build. Since there is no evidence that this knowledge was imported from other civilizations, the Mesopotamians must have developed this engineering knowledge independently.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "The drainage systems in Mesopotamian cities were more advanced than those in neighboring regions" },
      { letter: "B", text: "Archaeological evidence shows a gradual evolution of drainage technology in Mesopotamia over several centuries" },
      { letter: "C", text: "Mesopotamian texts describe the training of engineers in local schools" },
      { letter: "D", text: "Similar drainage systems were later adopted by other ancient civilizations" },
      { letter: "E", text: "The materials used in the drainage systems were locally sourced" },
    ],
    correctAnswer: "B",
    explanation: "Evidence of gradual evolution of the technology within Mesopotamia strongly supports the conclusion that the knowledge was developed independently. If the knowledge had been imported, we would expect to see it appear suddenly rather than evolve gradually.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-004",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that building a new sports stadium will revitalize the downtown area. They point to the example of Riverside City, where a new stadium was followed by a 20 percent increase in downtown business revenue within three years.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "The proposed stadium would be located on the outskirts of downtown rather than in its center" },
      { letter: "B", text: "Riverside City also implemented major tax incentives for downtown businesses at the same time the stadium was built" },
      { letter: "C", text: "The new stadium would create several hundred construction jobs" },
      { letter: "D", text: "Other cities have built stadiums with varying degrees of success" },
      { letter: "E", text: "The proposed stadium would cost more than the one built in Riverside City" },
    ],
    correctAnswer: "B",
    explanation: "If Riverside City implemented tax incentives at the same time as building the stadium, then the increase in business revenue might be attributable to the tax incentives rather than the stadium. This alternative explanation weakens the argument that building a stadium alone will revitalize downtown.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-005",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All effective managers are good communicators. Since Janet is not a good communicator, she will not be an effective manager at the new company.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Janet has been an ineffective manager in the past" },
      { letter: "B", text: "Good communication skills cannot be learned" },
      { letter: "C", text: "Janet's communication skills will not improve before or after she joins the new company" },
      { letter: "D", text: "Effective management requires nothing more than good communication" },
      { letter: "E", text: "The new company values good communication skills" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that Janet will not be an effective manager, but this requires assuming that her current lack of communication skills will persist. If she could improve her communication skills, the conclusion would not necessarily follow from the premises.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-006",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Public libraries are essential community resources. They provide free access to information for all citizens regardless of economic status. In an era of increasing income inequality, such equal access is more important than ever. Furthermore, libraries serve as community gathering spaces and offer programs that support literacy and lifelong learning. For these reasons, funding for public libraries should be increased, not decreased.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Public libraries provide free access to information for all citizens" },
      { letter: "B", text: "Income inequality is increasing in society" },
      { letter: "C", text: "Libraries serve as community gathering spaces" },
      { letter: "D", text: "Funding for public libraries should be increased rather than decreased" },
      { letter: "E", text: "Public libraries are essential community resources" },
    ],
    correctAnswer: "D",
    explanation: "The phrase 'For these reasons' signals that the main conclusion follows. Everything before this phrase provides reasons supporting the conclusion that library funding should be increased. While choice E appears at the beginning, it serves as an intermediate conclusion supporting the main point about funding.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-007",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that we cannot have free will because all our actions are determined by prior causes. But consider: if determinism makes free will impossible, then we cannot be held morally responsible for our actions. Yet we clearly do hold people morally responsible. Therefore, either determinism is false, or it is compatible with free will.`,
    questionStem: "The philosopher's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "showing that a position leads to a conclusion that conflicts with a widely accepted practice" },
      { letter: "B", text: "providing a counterexample to a general claim" },
      { letter: "C", text: "demonstrating that two seemingly opposed positions are actually consistent" },
      { letter: "D", text: "arguing that a concept is too vague to be meaningful" },
      { letter: "E", text: "appealing to expert authority to settle a dispute" },
    ],
    correctAnswer: "A",
    explanation: "The philosopher argues that if determinism makes free will impossible, then moral responsibility would be impossible. But we do practice holding people morally responsible, which conflicts with the conclusion. This forces us to reject either the premise or accept that determinism is compatible with free will.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Either the government should increase funding for renewable energy research or it should provide tax incentives for companies that use renewable energy. The government has decided to increase funding for renewable energy research. Therefore, the government should not provide tax incentives for companies that use renewable energy.`,
    questionStem: "The reasoning in the argument is flawed because the argument",
    answerChoices: [
      { letter: "A", text: "fails to consider whether the government can afford both options" },
      { letter: "B", text: "assumes that what is true of renewable energy is true of all energy sources" },
      { letter: "C", text: "treats two options that could both be implemented as if they were mutually exclusive" },
      { letter: "D", text: "relies on evidence that is not directly relevant to the conclusion" },
      { letter: "E", text: "draws a conclusion about what should happen from premises about what will happen" },
    ],
    correctAnswer: "C",
    explanation: "The argument presents a false dichotomy. The initial 'either/or' statement does not actually establish that only one option can be pursued. Both increasing research funding and providing tax incentives could be implemented simultaneously. Choosing one does not preclude the other.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-009",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company claims that its new medication reduces cholesterol levels more effectively than existing medications. In clinical trials, patients taking the new medication showed an average 25 percent reduction in cholesterol levels after six months, compared to an average 18 percent reduction for patients taking the leading existing medication.`,
    questionStem: "Which one of the following, if true, most strengthens the company's claim?",
    answerChoices: [
      { letter: "A", text: "The clinical trials were conducted at multiple hospitals across the country" },
      { letter: "B", text: "Patients in both groups had similar cholesterol levels at the start of the trials and followed similar diets during the trials" },
      { letter: "C", text: "The new medication has fewer side effects than existing medications" },
      { letter: "D", text: "The company has successfully developed other medications in the past" },
      { letter: "E", text: "Cholesterol reduction is an important factor in preventing heart disease" },
    ],
    correctAnswer: "B",
    explanation: "For the comparison to be valid, the two groups must be comparable at the start and during the trial. If patients started with similar cholesterol levels and followed similar diets, then the difference in reduction can more confidently be attributed to the medication rather than other factors.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Educational researcher: Students who participate in extracurricular activities have higher grade point averages than students who do not. This shows that participating in extracurricular activities improves academic performance.`,
    questionStem: "Which one of the following, if true, most weakens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Some extracurricular activities are more time-consuming than others" },
      { letter: "B", text: "Many schools require students to maintain a minimum grade point average to participate in extracurricular activities" },
      { letter: "C", text: "Extracurricular activities teach valuable skills like teamwork and time management" },
      { letter: "D", text: "Students who participate in extracurricular activities spend less time on homework" },
      { letter: "E", text: "The grade point average difference between the two groups is statistically significant" },
    ],
    correctAnswer: "B",
    explanation: "If schools require a minimum GPA to participate in extracurricular activities, then the causation could run in the opposite direction: students who already have good grades are the ones who can participate, rather than participation causing good grades. This reverse causation explanation weakens the researcher's causal claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-011",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should convert the abandoned factory into a community center. Community centers provide valuable recreational and educational opportunities for residents. Moreover, the abandoned factory is an eyesore that decreases property values in the neighborhood.`,
    questionStem: "The argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "converting the factory is the only way to improve neighborhood property values" },
      { letter: "B", text: "community centers always increase property values" },
      { letter: "C", text: "the factory cannot be profitably converted into a commercial enterprise" },
      { letter: "D", text: "there is no other suitable location for building a community center" },
      { letter: "E", text: "converting the factory into a community center is feasible" },
    ],
    correctAnswer: "E",
    explanation: "The argument assumes that the proposed conversion is actually possible. If it were not feasible to convert the factory into a community center (due to structural issues, costs, zoning, etc.), then the recommendation would be pointless regardless of the benefits community centers provide.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Hernandez: The use of artificial intelligence in medical diagnosis should be expanded. AI systems can analyze vast amounts of data and detect patterns that human physicians might miss, leading to more accurate diagnoses.

Dr. Patel: I disagree. While AI can process data quickly, medical diagnosis requires understanding the whole patient, including emotional and social factors that AI cannot assess. Expanding AI use could lead to worse patient outcomes.`,
    questionStem: "The main point at issue between Dr. Hernandez and Dr. Patel is",
    answerChoices: [
      { letter: "A", text: "whether AI systems can process large amounts of medical data" },
      { letter: "B", text: "whether expanding AI use in medical diagnosis would improve patient outcomes" },
      { letter: "C", text: "whether human physicians sometimes miss important diagnostic patterns" },
      { letter: "D", text: "whether emotional factors are relevant to medical treatment" },
      { letter: "E", text: "whether AI technology will continue to advance in the future" },
    ],
    correctAnswer: "B",
    explanation: "Dr. Hernandez argues that expanding AI use would lead to more accurate diagnoses (implying better outcomes), while Dr. Patel argues it could lead to worse patient outcomes. This is the central disagreement. Both might agree on the other points.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-013",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The senator argues that we should not pass this trade agreement because it was negotiated by the previous administration, which had different priorities. But the senator supported a nearly identical trade agreement last year when it was proposed by her own party. Clearly, her opposition now is purely political.`,
    questionStem: "The reasoning above is questionable because it",
    answerChoices: [
      { letter: "A", text: "attacks the senator's motives rather than addressing the merits of her argument against the trade agreement" },
      { letter: "B", text: "assumes that trade agreements negotiated by different administrations are necessarily different" },
      { letter: "C", text: "fails to consider that the senator may have changed her views on trade policy" },
      { letter: "D", text: "presumes that political motivations are always illegitimate" },
      { letter: "E", text: "ignores the possibility that the current trade agreement has flaws the previous one did not" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits an ad hominem fallacy by attacking the senator's alleged political motives rather than evaluating whether her substantive arguments against the trade agreement are valid. Even if her opposition is politically motivated, that does not mean her arguments are wrong.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The recent increase in consumer spending will likely lead to higher inflation. When consumers spend more, demand for goods and services increases. If supply cannot keep pace with this increased demand, prices will rise.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's reasoning?",
    answerChoices: [
      { letter: "A", text: "Consumer spending has increased by 5 percent over the past quarter" },
      { letter: "B", text: "Many manufacturers are currently operating at maximum production capacity" },
      { letter: "C", text: "Inflation has been relatively low for the past several years" },
      { letter: "D", text: "Interest rates are expected to remain stable in the near future" },
      { letter: "E", text: "Consumer confidence surveys show optimism about the economy" },
    ],
    correctAnswer: "B",
    explanation: "The economist's argument depends on supply not keeping pace with increased demand. If manufacturers are already at maximum capacity, they cannot easily increase supply to meet higher demand, making price increases (inflation) more likely.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Company executives argue that allowing employees to work from home reduces productivity. They point to studies showing that employees who work from home log fewer hours than those who work in the office.`,
    questionStem: "Which one of the following, if true, most seriously weakens the executives' argument?",
    answerChoices: [
      { letter: "A", text: "Many employees prefer working from home to working in an office" },
      { letter: "B", text: "Some companies have reported increased productivity among remote workers" },
      { letter: "C", text: "Research shows that output per hour is significantly higher for employees working from home than for those in the office" },
      { letter: "D", text: "Working from home eliminates commute time for employees" },
      { letter: "E", text: "Office workers often spend time in meetings that could be handled through email" },
    ],
    correctAnswer: "C",
    explanation: "The executives equate hours logged with productivity. If employees working from home produce more per hour, they could be more productive overall despite logging fewer hours. This directly challenges the assumption that fewer hours means lower productivity.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-016",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Parents should monitor their children's social media use. Unmonitored access to social media exposes children to cyberbullying, inappropriate content, and online predators. Parents who do not monitor their children's social media use are failing to protect them from these dangers.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "all children use social media" },
      { letter: "B", text: "cyberbullying is more harmful than traditional bullying" },
      { letter: "C", text: "parental monitoring can effectively reduce or prevent exposure to these dangers" },
      { letter: "D", text: "children cannot protect themselves from online dangers" },
      { letter: "E", text: "social media companies should do more to protect young users" },
    ],
    correctAnswer: "C",
    explanation: "The argument recommends parental monitoring as protection against online dangers. This only makes sense if monitoring actually helps reduce or prevent exposure to these dangers. If monitoring were ineffective, the recommendation would be pointless.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-017",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ninety percent of the doctors who were surveyed recommended our brand of pain reliever. Therefore, our pain reliever is more effective than competing brands.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that effectiveness is the only reason doctors would recommend a medication" },
      { letter: "B", text: "relies on a survey without specifying how many doctors were surveyed" },
      { letter: "C", text: "fails to consider that some doctors might recommend multiple brands" },
      { letter: "D", text: "presumes that all doctors have equal expertise in pain management" },
      { letter: "E", text: "does not specify what condition the pain reliever is meant to treat" },
    ],
    correctAnswer: "A",
    explanation: "Doctors might recommend a pain reliever for reasons other than effectiveness, such as cost, availability, fewer side effects, or even financial incentives from the manufacturer. The argument fails to establish that recommendations reflect superior effectiveness.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-018",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All professional musicians practice for several hours each day. Maya practices for several hours each day. Therefore, Maya is a professional musician.`,
    questionStem: "The flawed reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All birds have feathers. Penguins are birds. Therefore, penguins have feathers." },
      { letter: "B", text: "All squares are rectangles. This shape is a rectangle. Therefore, this shape is a square." },
      { letter: "C", text: "No reptiles are warm-blooded. Snakes are reptiles. Therefore, snakes are not warm-blooded." },
      { letter: "D", text: "All cats are mammals. All dogs are mammals. Therefore, all cats are dogs." },
      { letter: "E", text: "Some teachers are patient. John is patient. Therefore, John might be a teacher." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments commit the fallacy of affirming the consequent. The original argues: All A are B; X is B; therefore X is A. Choice B follows the same pattern: All squares are rectangles; this is a rectangle; therefore this is a square. Both invalidly assume that satisfying a necessary condition proves membership in the category.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-019",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `In the Greenville School District, any teacher who has completed at least ten years of service is eligible for a sabbatical. Ms. Rodriguez has taught in the district for eight years. Mr. Thompson, who was hired two years before Ms. Rodriguez, recently received a sabbatical.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Ms. Rodriguez will be eligible for a sabbatical in two years" },
      { letter: "B", text: "Mr. Thompson has taught in the district for at least ten years" },
      { letter: "C", text: "Ms. Rodriguez has applied for a sabbatical" },
      { letter: "D", text: "Only teachers with ten or more years of service receive sabbaticals" },
      { letter: "E", text: "Mr. Thompson is a better teacher than Ms. Rodriguez" },
    ],
    correctAnswer: "B",
    explanation: "Mr. Thompson was hired two years before Ms. Rodriguez, who has taught for eight years. Therefore, Mr. Thompson has taught for ten years. Since he received a sabbatical and eligibility requires at least ten years of service, he must have met that requirement.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-020",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution claims my client committed the robbery at 9 PM on March 5th. However, credit card records show my client made a purchase at a store 50 miles away at 8:45 PM that same day. It is impossible to travel 50 miles in 15 minutes. Therefore, my client could not have committed the robbery.`,
    questionStem: "The defense attorney's argument employs which one of the following methods of reasoning?",
    answerChoices: [
      { letter: "A", text: "Attacking the credibility of the prosecution's witnesses" },
      { letter: "B", text: "Demonstrating that the prosecution's claim is physically impossible given the evidence" },
      { letter: "C", text: "Showing that similar crimes have been committed by other individuals" },
      { letter: "D", text: "Arguing that the prosecution has failed to establish motive" },
      { letter: "E", text: "Questioning whether the robbery actually occurred" },
    ],
    correctAnswer: "B",
    explanation: "The defense attorney presents evidence (the credit card purchase) that makes the prosecution's timeline physically impossible. If the client was 50 miles away 15 minutes before the crime, and traveling that distance in 15 minutes is impossible, then the client could not have been at the crime scene.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-021",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Mayor: Our city's new recycling program has been a great success. In the first year, we collected twice as much recyclable material as we did the previous year under the old program. This proves that residents are now more committed to environmental protection.`,
    questionStem: "The reasoning in the mayor's argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "fails to specify the exact amounts of recyclable material collected" },
      { letter: "B", text: "overlooks possible explanations for the increase other than greater resident commitment" },
      { letter: "C", text: "assumes that recycling is the only measure of environmental commitment" },
      { letter: "D", text: "does not compare the city's recycling rates to those of other cities" },
      { letter: "E", text: "presumes that the new program will continue to be successful" },
    ],
    correctAnswer: "B",
    explanation: "The mayor attributes the increase in recycling to greater resident commitment, but there could be other explanations: the new program might accept more types of materials, have more convenient collection times, provide more bins, or have mandatory requirements. The argument fails to rule out these alternative explanations.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-022",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Biologist: The recent decline in the monarch butterfly population is primarily due to the loss of milkweed plants, which are the sole food source for monarch caterpillars. Agricultural practices, particularly the use of herbicides on crops, have dramatically reduced milkweed populations in the butterflies' breeding areas.`,
    questionStem: "Which one of the following, if true, provides the most support for the biologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Monarch butterflies migrate thousands of miles each year" },
      { letter: "B", text: "Regions where milkweed remains abundant have stable or growing monarch populations" },
      { letter: "C", text: "Other butterfly species have also experienced population declines" },
      { letter: "D", text: "Climate change may also affect monarch butterfly migration patterns" },
      { letter: "E", text: "Milkweed is considered a nuisance plant by many farmers" },
    ],
    correctAnswer: "B",
    explanation: "If areas with abundant milkweed have stable or growing monarch populations, this supports the claim that milkweed loss is responsible for the decline elsewhere. It shows a direct correlation between milkweed availability and butterfly population health.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: Voter turnout in local elections is always lower than in national elections because people care more about national issues than local ones. This explains why only 30 percent of eligible voters participated in our recent city council election.`,
    questionStem: "Which one of the following, if true, most weakens the analyst's explanation?",
    answerChoices: [
      { letter: "A", text: "Many people feel that their vote does not matter in national elections" },
      { letter: "B", text: "Local election dates are often scheduled on different days than national elections, when fewer people can take time off to vote" },
      { letter: "C", text: "Some local elections have higher turnout than some national elections" },
      { letter: "D", text: "National elections receive more media coverage than local elections" },
      { letter: "E", text: "The city council makes decisions that directly affect residents' daily lives" },
    ],
    correctAnswer: "B",
    explanation: "This provides an alternative explanation for lower local election turnout that has nothing to do with how much people care about local issues. If local elections are held at inconvenient times, practical barriers rather than lack of interest could explain the lower turnout.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-024",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The ancient Greeks developed democracy, philosophy, and significant advances in mathematics and science. Modern Western civilization owes much of its intellectual foundation to ancient Greek thought. Therefore, studying ancient Greek culture should be a required part of every student's education.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Students cannot understand modern civilization without studying its historical origins" },
      { letter: "B", text: "Ancient Greek culture was superior to all other ancient cultures" },
      { letter: "C", text: "Understanding the foundations of Western civilization is valuable enough to warrant required study" },
      { letter: "D", text: "All students are interested in ancient history" },
      { letter: "E", text: "Modern educators are qualified to teach about ancient Greek culture" },
    ],
    correctAnswer: "C",
    explanation: "The argument moves from the claim that Western civilization owes much to Greek thought to the conclusion that studying Greek culture should be required. This requires assuming that understanding these foundations is valuable enough to make such study mandatory for everyone.",
    difficulty: "hard",
  },
  {
    id: "lr-bank65-025",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical ethicist: Physicians have an obligation to be honest with their patients. Some argue that there are cases where deceiving a patient might lead to better health outcomes. However, deception undermines the trust that is essential to the doctor-patient relationship. Without this trust, patients may withhold information or fail to follow medical advice, ultimately leading to worse outcomes. Thus, even when deception might seem beneficial in the short term, honesty remains the physician's ethical duty.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the medical ethicist's argument?",
    answerChoices: [
      { letter: "A", text: "Trust is essential to the doctor-patient relationship" },
      { letter: "B", text: "Deception sometimes leads to better health outcomes" },
      { letter: "C", text: "Patients may withhold information if they do not trust their doctors" },
      { letter: "D", text: "Physicians should be honest with their patients even when deception might seem beneficial" },
      { letter: "E", text: "Short-term benefits should never outweigh long-term consequences" },
    ],
    correctAnswer: "D",
    explanation: "The main conclusion is that honesty remains the physician's ethical duty even when deception might seem beneficial in the short term. The other statements are either premises supporting this conclusion or claims that the ethicist is responding to.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-026",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The average life expectancy in the United States has increased from 70 years in 1960 to 79 years today. This increase is due to improvements in medical technology and access to healthcare. Therefore, if we continue to improve medical technology and healthcare access, life expectancy will continue to increase at the same rate indefinitely.`,
    questionStem: "The argument's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that past trends will continue unchanged into the future without considering potential limiting factors" },
      { letter: "B", text: "fails to account for improvements in nutrition and sanitation" },
      { letter: "C", text: "ignores differences in life expectancy between various demographic groups" },
      { letter: "D", text: "relies on statistics that may not be accurate" },
      { letter: "E", text: "confuses average life expectancy with maximum human lifespan" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that because life expectancy increased due to certain factors, it will continue to increase indefinitely at the same rate. This ignores potential limiting factors such as biological limits on human lifespan, diminishing returns from medical advances, or new health threats.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-027",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: People who eat breakfast tend to have lower body mass indexes than people who skip breakfast. I recommend that anyone trying to lose weight should eat a nutritious breakfast every morning.`,
    questionStem: "Which one of the following, if true, most strengthens the nutritionist's reasoning?",
    answerChoices: [
      { letter: "A", text: "Many breakfast foods are high in protein, which promotes feelings of fullness" },
      { letter: "B", text: "Studies show that people who start eating breakfast after previously skipping it tend to lose weight" },
      { letter: "C", text: "Breakfast is often called the most important meal of the day" },
      { letter: "D", text: "People who eat breakfast tend to exercise more than those who skip it" },
      { letter: "E", text: "The breakfast foods people choose vary widely in nutritional content" },
    ],
    correctAnswer: "B",
    explanation: "The nutritionist's recommendation implies that eating breakfast causes weight loss, not just that it's correlated with lower weight. Choice B provides evidence of causation by showing that when people who previously skipped breakfast start eating it, they tend to lose weight.",
    difficulty: "hard",
  },
  {
    id: "lr-bank65-028",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council's decision to install more streetlights has been vindicated. In the year since the new lights were installed, nighttime crime in the affected areas has decreased by 15 percent.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "The cost of installing the streetlights exceeded initial estimates" },
      { letter: "B", text: "Nighttime crime decreased by 20 percent citywide during the same period, including in areas where no new lights were installed" },
      { letter: "C", text: "Some residents complained that the new lights were too bright" },
      { letter: "D", text: "Daytime crime rates in the affected areas remained unchanged" },
      { letter: "E", text: "The new streetlights use energy-efficient LED technology" },
    ],
    correctAnswer: "B",
    explanation: "If nighttime crime decreased even more in areas without new streetlights, then the streetlights cannot be credited with the decrease in the areas where they were installed. Some other factor is likely responsible for the citywide decline in crime.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `In a democracy, laws should reflect the will of the majority of citizens. The majority of citizens in our country oppose the death penalty. Therefore, the death penalty should be abolished in our country.`,
    questionStem: "The argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "the death penalty is immoral" },
      { letter: "B", text: "other countries have abolished the death penalty" },
      { letter: "C", text: "the majority opinion on the death penalty will not change" },
      { letter: "D", text: "majority opposition to a practice is sufficient grounds for abolishing it through law" },
      { letter: "E", text: "opinion polls accurately measure public sentiment" },
    ],
    correctAnswer: "D",
    explanation: "The argument moves from majority opposition to the conclusion that the practice should be abolished. This requires assuming that majority will should actually determine whether laws permit or prohibit something, which is the practical application of the democratic principle stated.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-030",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Chen: Universities should prioritize teaching students practical skills that will help them in their careers. The purpose of higher education is to prepare students for the workforce.

Professor Williams: I disagree. The purpose of higher education is to develop critical thinking and expose students to diverse ideas. Career preparation is important but secondary to intellectual growth.`,
    questionStem: "Professor Chen and Professor Williams disagree about",
    answerChoices: [
      { letter: "A", text: "whether critical thinking is a valuable skill" },
      { letter: "B", text: "whether career preparation should be the primary purpose of higher education" },
      { letter: "C", text: "whether students should be exposed to diverse ideas" },
      { letter: "D", text: "whether universities currently prioritize practical skills" },
      { letter: "E", text: "whether intellectual growth is possible without formal education" },
    ],
    correctAnswer: "B",
    explanation: "Professor Chen believes the primary purpose of higher education is career preparation, while Professor Williams believes the primary purpose is intellectual development, with career preparation being secondary. This is the central point of disagreement.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Company policy requires all employees to undergo annual ethics training. Yet despite this requirement, three employees were caught engaging in unethical conduct this year. This proves that ethics training is completely ineffective at preventing unethical behavior.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that ethics training should prevent all unethical behavior to be considered effective" },
      { letter: "B", text: "fails to specify what type of unethical conduct the employees engaged in" },
      { letter: "C", text: "does not consider whether the three employees had completed their ethics training" },
      { letter: "D", text: "ignores the possibility that the company has more than three employees" },
      { letter: "E", text: "presumes that all unethical behavior is equally serious" },
    ],
    correctAnswer: "A",
    explanation: "The argument sets an impossibly high standard for effectiveness: preventing all unethical behavior. Ethics training could still be effective if it reduces unethical behavior overall, even if it doesn't eliminate it entirely. Three incidents prove nothing about overall effectiveness.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-032",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Many people assume that economic growth always improves quality of life. However, in Scandinavian countries, quality of life has remained high even during periods of modest economic growth, while in some rapidly growing economies, quality of life has actually declined due to pollution, stress, and inequality. Clearly, the relationship between economic growth and quality of life is more complex than commonly assumed.`,
    questionStem: "The sociologist develops the argument by",
    answerChoices: [
      { letter: "A", text: "providing a precise definition of quality of life" },
      { letter: "B", text: "citing examples that complicate a commonly held assumption" },
      { letter: "C", text: "proposing an alternative measure of social progress" },
      { letter: "D", text: "analyzing statistical data from multiple countries" },
      { letter: "E", text: "dismissing economic growth as irrelevant to quality of life" },
    ],
    correctAnswer: "B",
    explanation: "The sociologist identifies a common assumption (economic growth always improves quality of life) and then presents examples that show the relationship is more complex. Scandinavian countries show high quality of life without rapid growth, while some growing economies show declining quality of life.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-033",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `The unusual rock formations found in the valley were likely created by glacial activity during the last ice age. The rocks are arranged in patterns consistent with glacial deposits, and the valley is located in a region known to have been covered by glaciers during that period.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "Similar rock formations have been found in regions that were never covered by glaciers" },
      { letter: "B", text: "Geological analysis of the rocks reveals scratch marks consistent with glacial transport" },
      { letter: "C", text: "The valley is now located in a temperate climate zone" },
      { letter: "D", text: "Some scientists dispute the extent of glaciation during the last ice age" },
      { letter: "E", text: "Rock formations can be created by various geological processes" },
    ],
    correctAnswer: "B",
    explanation: "Scratch marks from glacial transport provide direct physical evidence of glacial activity. This independent confirmation strengthens the argument that the formations were created by glaciers, beyond just their arrangement and location.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-034",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A new study found that employees who work in open-plan offices report lower job satisfaction than those who work in private offices. The researchers concluded that open-plan offices harm employee morale and should be replaced with private offices to improve workplace satisfaction.`,
    questionStem: "Which one of the following, if true, most undermines the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Open-plan offices are less expensive to build than private offices" },
      { letter: "B", text: "Some employees in open-plan offices report high job satisfaction" },
      { letter: "C", text: "Employees with lower job satisfaction are more likely to be assigned to open-plan offices in the first place" },
      { letter: "D", text: "Job satisfaction depends on many factors beyond office design" },
      { letter: "E", text: "The study included employees from various industries" },
    ],
    correctAnswer: "C",
    explanation: "If employees with lower satisfaction are more likely to be assigned to open-plan offices (perhaps because they are junior or in less valued roles), then the office type might not cause lower satisfaction. The causation could be reversed or driven by a third factor.",
    difficulty: "hard",
  },
  {
    id: "lr-bank65-035",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Video games are often criticized for promoting violence, but this criticism is unfounded. A study of 1,000 teenagers found no significant correlation between playing violent video games and engaging in aggressive behavior in real life.`,
    questionStem: "The argument's conclusion depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Teenagers who play violent video games have access to other forms of entertainment" },
      { letter: "B", text: "The study's methodology was appropriate for detecting a relationship between video games and aggression" },
      { letter: "C", text: "All violent video games depict the same level of violence" },
      { letter: "D", text: "Parents should not monitor their children's video game use" },
      { letter: "E", text: "The teenagers in the study were representative of all age groups" },
    ],
    correctAnswer: "B",
    explanation: "The argument relies on the study's findings to dismiss the criticism. This requires assuming the study was well-designed enough to detect a correlation if one existed. If the methodology was flawed, the lack of correlation found would not prove anything.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-036",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Many ancient cultures developed sophisticated calendars. The Maya, for example, created a calendar system that accurately predicted astronomical events. The ancient Egyptians aligned their pyramids with remarkable precision to astronomical features. These accomplishments prove that ancient peoples possessed knowledge that rivals or exceeds modern scientific understanding.`,
    questionStem: "The argument's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "generalizes from the accomplishments of two cultures to claims about all ancient cultures" },
      { letter: "B", text: "confuses impressive achievements in specific areas with comprehensive scientific knowledge" },
      { letter: "C", text: "fails to acknowledge that modern scientists have studied these ancient accomplishments" },
      { letter: "D", text: "does not provide specific dates for when these accomplishments occurred" },
      { letter: "E", text: "assumes that calendars and pyramids are the only measures of scientific understanding" },
    ],
    correctAnswer: "B",
    explanation: "The argument cites impressive achievements in astronomy and architecture but concludes that ancient knowledge rivals modern science overall. This overgeneralizes from specific accomplishments to comprehensive scientific understanding, ignoring the vast areas of knowledge where modern science far exceeds ancient understanding.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-037",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy improves, consumer confidence will rise. Consumer confidence has risen. Therefore, the economy has improved.`,
    questionStem: "Which one of the following exhibits a pattern of flawed reasoning most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "If it rains, the ground will be wet. It rained. Therefore, the ground is wet." },
      { letter: "B", text: "If she passed the exam, she will celebrate. She is celebrating. Therefore, she passed the exam." },
      { letter: "C", text: "If the train is delayed, I will be late. The train is not delayed. Therefore, I will not be late." },
      { letter: "D", text: "If he is a doctor, he has a medical degree. He is a doctor. Therefore, he has a medical degree." },
      { letter: "E", text: "If the store is closed, we cannot buy groceries. We bought groceries. Therefore, the store was open." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments affirm the consequent. The original: If A then B; B; therefore A. Choice B follows the same pattern: If she passed then she will celebrate; she is celebrating; therefore she passed. This ignores other reasons why consumer confidence might rise or why someone might celebrate.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-038",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Anthropologist: The ancient settlement discovered in the valley was likely a trading hub rather than a permanent residential community. The structures found there are too large and uniformly designed to have been family dwellings, and the site is located at the intersection of several ancient travel routes.`,
    questionStem: "Which one of the following, if true, most strengthens the anthropologist's hypothesis?",
    answerChoices: [
      { letter: "A", text: "The settlement dates to a period when long-distance trade was common in the region" },
      { letter: "B", text: "Excavations at the site have uncovered goods from many distant regions" },
      { letter: "C", text: "Other settlements in the area show evidence of permanent habitation" },
      { letter: "D", text: "The structures at the site were built using local materials" },
      { letter: "E", text: "The climate in the valley would have been suitable for year-round habitation" },
    ],
    correctAnswer: "B",
    explanation: "Finding goods from many distant regions strongly supports the hypothesis that the settlement was a trading hub. A trading center would be expected to have such diverse goods, while a permanent residential community would have predominantly local items.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-039",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Restaurant critic: The new downtown restaurant is overrated. While the food is undeniably excellent, the prices are too high for what is offered. No meal, however good, is worth $200 per person.`,
    questionStem: "Which one of the following, if true, most seriously weakens the critic's argument?",
    answerChoices: [
      { letter: "A", text: "Other downtown restaurants charge similar prices" },
      { letter: "B", text: "The restaurant has received positive reviews from other critics" },
      { letter: "C", text: "The $200 price includes a multi-course tasting menu with wine pairings and premium ingredients flown in daily" },
      { letter: "D", text: "The restaurant's chef has won numerous culinary awards" },
      { letter: "E", text: "Some diners prefer more casual dining experiences" },
    ],
    correctAnswer: "C",
    explanation: "The critic claims the price is too high 'for what is offered.' If the $200 includes multiple courses, wine pairings, and premium imported ingredients, then the price may be justified by what is actually offered. This undermines the claim that the price is unreasonable.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-040",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The proposal to build a new highway through the forest preserve should be rejected. While the highway would reduce traffic congestion, it would destroy habitat for several endangered species. Once this habitat is destroyed, it cannot be restored. Traffic congestion, by contrast, can be addressed through other means such as improved public transportation and flexible work schedules. We should not cause permanent environmental damage when temporary problems have alternative solutions.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "The highway would destroy habitat for endangered species" },
      { letter: "B", text: "Traffic congestion can be addressed through alternative means" },
      { letter: "C", text: "The proposal to build a highway through the forest preserve should be rejected" },
      { letter: "D", text: "Habitat destruction is irreversible" },
      { letter: "E", text: "Temporary problems should not be solved by creating permanent damage" },
    ],
    correctAnswer: "C",
    explanation: "The argument opens with its main conclusion and then provides supporting reasons. The final sentence articulates a general principle that supports the specific conclusion. All other statements serve as premises or intermediate conclusions supporting the main recommendation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-041",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Those who advocate for strict enforcement of immigration laws often claim they are motivated by concern for public safety and the rule of law. However, many of these same advocates show little concern for enforcing other laws that do not involve immigration. Their inconsistency reveals that their true motivation is not respect for the law but rather hostility toward immigrants.`,
    questionStem: "The philosopher's argument is vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "assumes that people who advocate for a policy are necessarily hostile to those affected by it" },
      { letter: "B", text: "presumes that people cannot have multiple legitimate reasons for a policy position" },
      { letter: "C", text: "fails to consider that prioritizing some laws over others does not necessarily indicate bad faith" },
      { letter: "D", text: "ignores the distinction between civil and criminal laws" },
      { letter: "E", text: "relies on evidence that may not be representative of all immigration law advocates" },
    ],
    correctAnswer: "C",
    explanation: "The philosopher concludes that inconsistency in enforcement priorities reveals hostility. However, people can legitimately prioritize some laws over others based on factors like perceived severity of consequences, without this indicating bad faith or hidden prejudice.",
    difficulty: "hard",
  },
  {
    id: "lr-bank65-042",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The new surgical technique is clearly superior to the traditional method. In a study comparing the two techniques, patients who underwent the new procedure had shorter hospital stays and fewer post-operative complications than patients who received the traditional surgery.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The surgeons performing the new technique were at least as skilled as those performing the traditional surgery" },
      { letter: "B", text: "The new technique is less expensive than the traditional method" },
      { letter: "C", text: "All surgeons prefer the new technique to the traditional method" },
      { letter: "D", text: "The study was published in a peer-reviewed medical journal" },
      { letter: "E", text: "Post-operative complications are always serious" },
    ],
    correctAnswer: "A",
    explanation: "For the comparison to be valid, the study must have controlled for surgeon skill level. If better surgeons happened to perform the new technique, the improved outcomes could be due to surgeon skill rather than the technique itself. The argument assumes comparable skill levels.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-043",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the city council must complete ethics training before assuming office. Some members of the city council are also members of the school board. No member of the school board is under 25 years of age.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All members of the school board have completed ethics training" },
      { letter: "B", text: "No member of the city council is under 25 years of age" },
      { letter: "C", text: "Some people who have completed ethics training are not under 25 years of age" },
      { letter: "D", text: "Anyone who has completed ethics training is eligible to serve on the school board" },
      { letter: "E", text: "All members of the city council are also members of the school board" },
    ],
    correctAnswer: "C",
    explanation: "Some city council members are also school board members. All city council members have completed ethics training. No school board members are under 25. Therefore, some people who completed ethics training (those who are on both boards) are not under 25.",
    difficulty: "hard",
  },
  {
    id: "lr-bank65-044",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `People often argue that genetically modified crops are unnatural and therefore potentially harmful. But this reasoning is flawed. Consider that almost all the foods we eat today have been substantially modified through centuries of selective breeding. Carrots, for example, were originally purple or white before humans bred them to be orange. If genetic modification is unnatural, then so is virtually everything in our diet.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "showing that an argument's logic leads to an absurd conclusion" },
      { letter: "B", text: "providing scientific evidence that genetic modification is safe" },
      { letter: "C", text: "demonstrating that the term 'unnatural' is meaningless" },
      { letter: "D", text: "arguing that tradition justifies current practices" },
      { letter: "E", text: "appealing to the authority of agricultural scientists" },
    ],
    correctAnswer: "A",
    explanation: "The argument uses a reductio ad absurdum. It shows that if we accept the premise that GM crops are unnatural, we must also accept that virtually all our food is unnatural, which would make the 'unnatural' objection trivial or absurd.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-045",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Mandatory minimum sentencing laws have failed to deter crime. States that have implemented these laws have not seen greater reductions in crime rates compared to states without such laws.`,
    questionStem: "Which one of the following, if true, most strengthens the legal scholar's argument?",
    answerChoices: [
      { letter: "A", text: "Mandatory minimum sentencing laws have increased prison populations in states that adopted them" },
      { letter: "B", text: "Potential criminals are generally aware of the sentencing laws in their state" },
      { letter: "C", text: "Crime rates have decreased nationwide over the past two decades" },
      { letter: "D", text: "Some states have recently begun to repeal their mandatory minimum laws" },
      { letter: "E", text: "Judges have criticized mandatory minimum laws as overly harsh" },
    ],
    correctAnswer: "B",
    explanation: "For sentencing laws to deter crime, potential criminals must know about them. If potential criminals are aware of these laws but crime hasn't decreased more in states with them, this strengthens the conclusion that the laws have failed as a deterrent.",
    difficulty: "hard",
  },
  {
    id: "lr-bank65-046",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Psychology professor: Memory is far less reliable than people assume. In a study, participants watched a video of a car accident and were later asked about the speed of the vehicles. When researchers used the word "smashed" instead of "contacted," participants estimated significantly higher speeds. This demonstrates that memories can be altered by subsequent information.`,
    questionStem: "Which one of the following, if true, most weakens the professor's conclusion?",
    answerChoices: [
      { letter: "A", text: "Participants in the study were college students who may not be representative of the general population" },
      { letter: "B", text: "The word choice may have influenced how participants expressed their estimates rather than altering their actual memories" },
      { letter: "C", text: "People are often overconfident in the accuracy of their memories" },
      { letter: "D", text: "The study has been replicated with similar results in multiple countries" },
      { letter: "E", text: "Other studies have shown that memories can be unreliable in different ways" },
    ],
    correctAnswer: "B",
    explanation: "The professor concludes that memories were altered. But if the word choice only affected how participants reported their estimates without changing their actual memories, then the study shows response bias rather than memory alteration. This alternative explanation weakens the conclusion.",
    difficulty: "hard",
  },
  {
    id: "lr-bank65-047",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The school board's decision to eliminate art and music programs was wrong. Studies consistently show that students who participate in arts education perform better academically. By eliminating these programs, the school board is ensuring that students will perform worse in their academic subjects.`,
    questionStem: "The reasoning in the argument is most vulnerable to the criticism that it",
    answerChoices: [
      { letter: "A", text: "assumes that all students are equally interested in arts education" },
      { letter: "B", text: "infers that arts education causes better academic performance from a correlation between them" },
      { letter: "C", text: "fails to consider the cost of maintaining arts programs" },
      { letter: "D", text: "presumes that academic performance is the only measure of educational success" },
      { letter: "E", text: "ignores the possibility that some schools have successfully operated without arts programs" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from the observation that arts students perform better academically to the conclusion that eliminating arts will cause worse performance. This assumes causation from correlation. Perhaps students who are already academically inclined choose to participate in arts programs.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No responsible pet owner allows their dog to roam freely in the neighborhood. Sarah allows her dog to roam freely in the neighborhood. Therefore, Sarah is not a responsible pet owner.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All good students study regularly. Michael studies regularly. Therefore, Michael is a good student." },
      { letter: "B", text: "No experienced driver runs red lights. Thompson runs red lights. Therefore, Thompson is not an experienced driver." },
      { letter: "C", text: "Some doctors work long hours. Martinez works long hours. Therefore, Martinez might be a doctor." },
      { letter: "D", text: "All professional athletes train daily. Lopez does not train daily. Therefore, Lopez is not a professional athlete." },
      { letter: "E", text: "No honest person lies under oath. Wilson is an honest person. Therefore, Wilson does not lie under oath." },
    ],
    correctAnswer: "B",
    explanation: "The original argument uses valid reasoning: No A is B; X is B; therefore X is not A. Choice B follows the exact same pattern: No experienced driver runs red lights; Thompson runs red lights; therefore Thompson is not an experienced driver. This is the valid form modus tollens with a universal negative.",
    difficulty: "easy",
  },
  {
    id: "lr-bank65-049",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Editor: Our newspaper should not publish letters that contain personal attacks on individuals. Such attacks contribute nothing to public discourse and can harm people's reputations unfairly.

Reporter: I disagree. Refusing to publish such letters amounts to censorship. A free press must allow all viewpoints to be expressed, even uncomfortable ones. It is for readers to judge the merits of letters, not editors.`,
    questionStem: "The editor and reporter disagree over whether",
    answerChoices: [
      { letter: "A", text: "personal attacks can harm people's reputations" },
      { letter: "B", text: "readers are capable of evaluating letters critically" },
      { letter: "C", text: "newspapers have an obligation to publish all submitted letters" },
      { letter: "D", text: "newspapers have the right to decide which letters to publish" },
      { letter: "E", text: "declining to publish certain types of letters constitutes inappropriate censorship" },
    ],
    correctAnswer: "E",
    explanation: "The editor believes not publishing personal attacks is an appropriate editorial decision, while the reporter characterizes this same action as censorship that violates press freedom. They disagree about whether this editorial discretion constitutes inappropriate censorship.",
    difficulty: "medium",
  },
  {
    id: "lr-bank65-050",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Countries with high levels of education spending tend to have stronger economies than countries that spend less on education. Therefore, if developing nations increase their education spending, their economies will grow stronger.`,
    questionStem: "The argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "education is the most important factor in economic growth" },
      { letter: "B", text: "developed nations cannot further improve their economies through education spending" },
      { letter: "C", text: "the relationship between education spending and economic strength is at least partly causal, not merely correlational" },
      { letter: "D", text: "developing nations currently spend less on education than developed nations" },
      { letter: "E", text: "economic growth always leads to increased education spending" },
    ],
    correctAnswer: "C",
    explanation: "The argument moves from an observation about correlation to a prediction about causation. It assumes that education spending actually contributes to economic strength, rather than the relationship being coincidental or running in the opposite direction (stronger economies can afford more education spending).",
    difficulty: "hard",
  },
];
