// Logical Reasoning Questions Bank - Set 4
import { Question } from "../lsat-types";

export const lrQuestionsSet4: Question[] = [
  {
    id: "lr-bank4-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `CEO: Our company's employee wellness program must be effective. Since we implemented it last year, our healthcare costs have decreased by 10 percent.`,
    questionStem: "The CEO's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes the wellness program is the only factor that could affect healthcare costs" },
      { letter: "B", text: "ignores the costs of running the wellness program itself" },
      { letter: "C", text: "fails to consider employees' opinions about the program" },
      { letter: "D", text: "overlooks the possibility that the program might produce long-term cost increases" },
      { letter: "E", text: "does not define what 'effective' means in this context" },
    ],
    correctAnswer: "A",
    explanation: "Post hoc reasoning and failure to consider alternative explanations. Healthcare costs could have decreased due to changes in workforce demographics, insurance plan changes, fewer claims, or economic factors unrelated to the wellness program.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Oceanographer: The Great Pacific Garbage Patch is growing. Satellite imagery shows that the area covered by floating debris has expanded significantly over the past decade.`,
    questionStem: "Which one of the following, if true, most strengthens the oceanographer's conclusion?",
    answerChoices: [
      { letter: "A", text: "Plastic production worldwide has increased substantially over the past decade" },
      { letter: "B", text: "Ocean cleanup efforts have removed thousands of tons of debris" },
      { letter: "C", text: "Ground-level surveys confirm that debris density has increased in addition to area" },
      { letter: "D", text: "Similar garbage patches exist in other oceans" },
      { letter: "E", text: "Many countries have banned single-use plastics" },
    ],
    correctAnswer: "C",
    explanation: "Area expansion alone might not indicate growth if the debris is just spreading out. Confirmation that density has also increased provides additional evidence that the total amount of garbage is actually growing, not just redistributing.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Music producer: Auto-tune technology has ruined modern popular music. Since its widespread adoption in the 2000s, listeners have become accustomed to unnaturally perfect vocals, and artists no longer develop genuine singing ability.`,
    questionStem: "Which one of the following, if true, most weakens the producer's argument?",
    answerChoices: [
      { letter: "A", text: "Many successful contemporary artists have demonstrated strong vocal abilities in live performances without auto-tune" },
      { letter: "B", text: "Auto-tune is expensive and therefore not available to all artists" },
      { letter: "C", text: "Earlier technologies like reverb and echo also altered vocal recordings" },
      { letter: "D", text: "Some genres of music rarely use auto-tune" },
      { letter: "E", text: "Music sales have declined since the introduction of auto-tune" },
    ],
    correctAnswer: "A",
    explanation: "The producer claims artists no longer develop genuine singing ability. Counter-evidence showing that many successful contemporary artists have strong natural vocals demonstrated in live settings directly contradicts this claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Cyclist: I should switch to an electric bicycle for my commute. Electric bicycles allow riders to arrive at work without being sweaty, and arriving sweaty is the main reason I currently drive instead of cycling.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Electric bicycles are more environmentally friendly than cars" },
      { letter: "B", text: "The cyclist's workplace does not have shower facilities" },
      { letter: "C", text: "There are no other significant obstacles to cycling to work" },
      { letter: "D", text: "Electric bicycles are faster than regular bicycles" },
      { letter: "E", text: "The cyclist is physically capable of riding a bicycle" },
    ],
    correctAnswer: "C",
    explanation: "The cyclist reasons that solving the sweating problem would allow them to cycle instead of drive. This assumes sweating is the ONLY significant obstacle. If there are other major barriers (distance, safety, weather), the e-bike wouldn't fully solve the problem.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-005",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The library fine for overdue books is 25 cents per day. Maximum fines are capped at the replacement cost of the book. The replacement cost of this book is $15. The book is currently 90 days overdue.`,
    questionStem: "Based on the information above, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "The fine for this book is $22.50" },
      { letter: "B", text: "The fine for this book is $15" },
      { letter: "C", text: "The fine for this book is less than $22.50" },
      { letter: "D", text: "The fine for this book is at least $15" },
      { letter: "E", text: "The book will be reported as lost" },
    ],
    correctAnswer: "B",
    explanation: "90 days × $0.25 = $22.50, but fines are capped at replacement cost. Since $22.50 > $15 (replacement cost), the fine would hit the cap. The fine must be exactly $15 (the cap applies).",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-006",
    type: "sufficient-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All best-selling authors write every day. Jenkins writes every day. Therefore, Jenkins is a best-selling author.`,
    questionStem: "The flawed reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All mammals are warm-blooded. Snakes are not warm-blooded. Therefore, snakes are not mammals." },
      { letter: "B", text: "All doctors have medical degrees. All people with medical degrees studied biology. Therefore, all doctors studied biology." },
      { letter: "C", text: "All chefs can cook. Maria can cook. Therefore, Maria is a chef." },
      { letter: "D", text: "Some teachers are patient. Some patient people are not teachers. Therefore, patience is not required for teaching." },
      { letter: "E", text: "No fish can breathe air. Whales breathe air. Therefore, whales are not fish." },
    ],
    correctAnswer: "C",
    explanation: "Both commit affirming the consequent: All A are B; X is B; therefore X is A. Original: All best-selling authors write daily; Jenkins writes daily; Jenkins is best-selling. C: All chefs cook; Maria cooks; Maria is a chef. Both invalid.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-007",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `A restaurant chain known for its premium pricing unexpectedly increased sales by raising prices an additional 15 percent during a period when most consumers were cutting back on dining expenses.`,
    questionStem: "Which one of the following, if true, most helps to explain the increase in sales?",
    answerChoices: [
      { letter: "A", text: "The restaurant chain also reduced portion sizes when it raised prices" },
      { letter: "B", text: "Higher prices signaled premium quality, attracting affluent customers less affected by economic conditions" },
      { letter: "C", text: "Other restaurant chains lowered their prices during the same period" },
      { letter: "D", text: "The restaurant chain had recently received negative publicity" },
      { letter: "E", text: "Consumer confidence indices showed declining optimism about the economy" },
    ],
    correctAnswer: "B",
    explanation: "Veblen goods: for certain luxury products, higher prices increase demand because price signals quality and exclusivity. The price increase attracted affluent consumers seeking premium experiences, offsetting reduced demand from price-sensitive customers.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-008",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: The candidate's claim to be fiscally conservative is undermined by their voting record. They voted for every major spending bill in the last session while opposing all proposed tax cuts. This pattern is inconsistent with fiscal conservatism as traditionally defined.`,
    questionStem: "The analyst's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "attacking the candidate's personal character" },
      { letter: "B", text: "demonstrating that the candidate's actions contradict their stated position" },
      { letter: "C", text: "comparing the candidate unfavorably to other politicians" },
      { letter: "D", text: "challenging the definition of fiscal conservatism" },
      { letter: "E", text: "questioning the accuracy of voting records" },
    ],
    correctAnswer: "B",
    explanation: "The analyst contrasts the candidate's self-description (fiscally conservative) with evidence of their actions (voting for spending, against tax cuts). This shows inconsistency between claims and conduct without attacking character or redefining terms.",
    difficulty: "easy",
  },
  {
    id: "lr-bank4-009",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the contract is valid, both parties must have signed it. Both parties signed the contract. Therefore, the contract is valid.`,
    questionStem: "The flawed reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If the alarm is set, the light will be green. The light is green. Therefore, the alarm is set." },
      { letter: "B", text: "If the payment is late, a fee will be charged. The payment is not late. Therefore, no fee will be charged." },
      { letter: "C", text: "All musicians can read music. Sarah cannot read music. Therefore, Sarah is not a musician." },
      { letter: "D", text: "If it is Sunday, the store is closed. It is Sunday. Therefore, the store is closed." },
      { letter: "E", text: "Some students passed the exam. Maria is a student. Therefore, Maria passed the exam." },
    ],
    correctAnswer: "A",
    explanation: "Both commit affirming the consequent: If P then Q; Q; therefore P. Original: If valid, then both signed; both signed; therefore valid. A: If alarm set, then green light; light green; therefore alarm set. Both invalid—the consequent can be true for other reasons.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-010",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: A company should not market products to children that it would not market to adults with complete information about the product's effects.`,
    questionStem: "Which one of the following practices is most clearly inconsistent with the principle?",
    answerChoices: [
      { letter: "A", text: "Marketing educational toys to children that are also marketed to adult collectors" },
      { letter: "B", text: "Marketing sugary cereals to children using cartoon characters while marketing the same product to adults with health claims" },
      { letter: "C", text: "Marketing bicycles to children that have the same safety features as adult bicycles" },
      { letter: "D", text: "Marketing video games with age-appropriate content to both children and adults" },
      { letter: "E", text: "Marketing sports equipment designed specifically for children's smaller bodies" },
    ],
    correctAnswer: "B",
    explanation: "The principle prohibits marketing to children products that fully informed adults would reject. Using cartoon characters to market sugary cereals to children while using different (health-focused) appeals to adults suggests the children are being marketed to without the full information that might deter adults.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-011",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Blogger: This diet must work for weight loss. Hundreds of people have posted testimonials on the program's website saying they lost significant weight using this method.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "generalizes from a sample that may not be representative" },
      { letter: "B", text: "relies on evidence from a source that has incentive to be biased" },
      { letter: "C", text: "assumes that weight loss is always healthy" },
      { letter: "D", text: "does not consider the cost of the diet program" },
      { letter: "E", text: "fails to define what 'significant weight' means" },
    ],
    correctAnswer: "B",
    explanation: "The testimonials appear on the program's own website, which has obvious incentive to feature only positive results and exclude failures. This is survivorship bias from a biased source—people who didn't lose weight wouldn't post on the program's promotional site.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: This ancient temple was built for astronomical observations. The main entrance is aligned with the rising sun on the winter solstice.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "Many ancient peoples celebrated the winter solstice" },
      { letter: "B", text: "The temple's other openings are aligned with the rising of significant stars and the positions of planets" },
      { letter: "C", text: "Building materials from the temple have been carbon-dated to 3000 BCE" },
      { letter: "D", text: "The temple is located on a hilltop with clear views in all directions" },
      { letter: "E", text: "Similar temples have been found in neighboring regions" },
    ],
    correctAnswer: "B",
    explanation: "One alignment might be coincidental. Multiple precise alignments with different celestial bodies (stars, planets) indicate intentional astronomical design rather than chance orientation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-013",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Economic inequality causes crime. Countries with greater income inequality consistently have higher crime rates than more egalitarian countries.`,
    questionStem: "Which one of the following, if true, most weakens the sociologist's argument?",
    answerChoices: [
      { letter: "A", text: "Crime rates are difficult to compare accurately across countries with different legal definitions" },
      { letter: "B", text: "Historical data shows that crime rates sometimes increase in countries becoming more egalitarian" },
      { letter: "C", text: "Certain factors, such as weak institutions, both increase inequality and independently cause higher crime" },
      { letter: "D", text: "Some wealthy countries have higher crime rates than some poor countries" },
      { letter: "E", text: "Policies aimed at reducing inequality are often expensive to implement" },
    ],
    correctAnswer: "C",
    explanation: "This suggests a third variable (weak institutions) that causes both inequality and crime independently. The correlation between inequality and crime might not reflect causation if both are effects of a common cause.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-014",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Veterinarian: You should feed your cat a wet food diet rather than dry food. Cats evolved in desert environments and naturally obtain most of their water from prey. Dry food does not provide adequate hydration.`,
    questionStem: "The veterinarian's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Cats that eat dry food cannot drink enough water to compensate" },
      { letter: "B", text: "Wet food is nutritionally complete for cats" },
      { letter: "C", text: "All dry cat foods have the same moisture content" },
      { letter: "D", text: "Cats prefer wet food to dry food" },
      { letter: "E", text: "Desert environments have no water sources" },
    ],
    correctAnswer: "A",
    explanation: "The argument claims dry food doesn't provide adequate hydration. But cats can drink water independently. The argument assumes cats cannot (or do not) compensate by drinking more water when eating dry food.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-015",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Every employee in the research division has a graduate degree. No employee in the sales division has a graduate degree. Martinez has a graduate degree and works at the company.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Martinez works in the research division" },
      { letter: "B", text: "Martinez does not work in the sales division" },
      { letter: "C", text: "Martinez has more education than sales employees" },
      { letter: "D", text: "All employees with graduate degrees work in research" },
      { letter: "E", text: "Martinez was hired for their graduate degree" },
    ],
    correctAnswer: "B",
    explanation: "No sales employees have graduate degrees. Martinez has a graduate degree. Therefore, Martinez cannot be in sales. We cannot conclude Martinez is in research—there might be other divisions that don't require graduate degrees.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-016",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Fitness influencer: High-intensity interval training (HIIT) is the best form of exercise. I switched to HIIT six months ago and have never felt better.`,
    questionStem: "The argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "generalizes from a single personal experience to a universal claim" },
      { letter: "B", text: "fails to consider the costs of HIIT programs" },
      { letter: "C", text: "assumes that feeling better is the goal of exercise" },
      { letter: "D", text: "ignores the possibility that HIIT might be unsuitable for some people" },
      { letter: "E", text: "does not specify what 'best' means in this context" },
    ],
    correctAnswer: "A",
    explanation: "The influencer makes a universal claim (best form of exercise) based solely on their personal experience. A sample of one cannot support a general conclusion about what is best for everyone, regardless of different fitness levels, goals, and health conditions.",
    difficulty: "easy",
  },
  {
    id: "lr-bank4-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The new minimum wage increase will not cause significant job losses. Small businesses in states that recently raised minimum wages did not experience higher rates of business closures or layoffs.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Large corporations can more easily absorb increased labor costs than small businesses" },
      { letter: "B", text: "The recent state minimum wage increases were comparable in size to the new increase being discussed" },
      { letter: "C", text: "Some businesses raised prices to offset higher labor costs" },
      { letter: "D", text: "Employee turnover decreased in states that raised minimum wages" },
      { letter: "E", text: "Consumer spending increased in states with higher minimum wages" },
    ],
    correctAnswer: "B",
    explanation: "For the comparison to be relevant, the state increases must be similar in magnitude to the proposed increase. If recent state increases were much smaller, they wouldn't predict the effects of a larger increase.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-018",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Screen time is harmful to children's development. Children who spend more than three hours daily on screens score lower on cognitive tests than children with less screen time.`,
    questionStem: "Which one of the following, if true, most weakens the psychologist's reasoning?",
    answerChoices: [
      { letter: "A", text: "Some types of screen time, such as educational programs, may have cognitive benefits" },
      { letter: "B", text: "Parents of children with developmental delays often use screens as a calming tool" },
      { letter: "C", text: "Screen time has increased substantially for children of all cognitive levels" },
      { letter: "D", text: "Many countries have issued guidelines limiting children's screen time" },
      { letter: "E", text: "Physical activity levels have not changed significantly among children" },
    ],
    correctAnswer: "B",
    explanation: "This suggests reverse causation. If children with existing developmental challenges use screens more (perhaps because screens are calming), then the correlation might reflect pre-existing conditions rather than screens causing cognitive problems.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-019",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Restaurant reviewer: Diners should avoid this restaurant. Its chef has no formal culinary training, and formally trained chefs consistently produce better food.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Culinary training is the only way to learn to cook well" },
      { letter: "B", text: "Self-taught chefs are incapable of producing excellent food" },
      { letter: "C", text: "The food at this restaurant is not an exception to the general pattern" },
      { letter: "D", text: "Formal training is available to anyone who wants to become a chef" },
      { letter: "E", text: "The reviewer has eaten at the restaurant" },
    ],
    correctAnswer: "C",
    explanation: "The reviewer argues from a general pattern (trained chefs are better) to a specific conclusion (this restaurant's food is worse). This assumes this restaurant doesn't buck the trend. Some self-taught chefs produce excellent food.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-020",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `Despite having fewer doctors per capita than neighboring countries, this country has higher life expectancy and lower infant mortality rates.`,
    questionStem: "Which one of the following, if true, most helps to resolve the apparent paradox?",
    answerChoices: [
      { letter: "A", text: "The country has more hospitals than neighboring countries" },
      { letter: "B", text: "The country invests heavily in preventive care and public health measures" },
      { letter: "C", text: "Medical school is more competitive in this country" },
      { letter: "D", text: "The country has stricter medical licensing requirements" },
      { letter: "E", text: "Healthcare costs are higher in this country" },
    ],
    correctAnswer: "B",
    explanation: "Preventive care and public health (clean water, vaccination, nutrition programs) can improve health outcomes more efficiently than additional doctors treating illness. Fewer doctors but better public health infrastructure produces better outcomes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-021",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: You argue that genetic engineering is unnatural and therefore wrong. But the same logic would condemn vaccines, surgery, and even cooking food. Since those practices are clearly beneficial and not wrong, something being unnatural is not sufficient to make it wrong.`,
    questionStem: "The ethicist's response employs which method of reasoning?",
    answerChoices: [
      { letter: "A", text: "Providing empirical evidence against the opponent's conclusion" },
      { letter: "B", text: "Showing that the opponent's principle has unacceptable implications when applied consistently" },
      { letter: "C", text: "Attacking the opponent's qualifications to make ethical judgments" },
      { letter: "D", text: "Demonstrating that genetic engineering has specific benefits" },
      { letter: "E", text: "Redefining the term 'unnatural' to support a different conclusion" },
    ],
    correctAnswer: "B",
    explanation: "The ethicist applies the opponent's principle ('unnatural = wrong') to other cases (vaccines, surgery) and shows it leads to absurd conclusions. This reductio ad absurdum undermines the principle without directly addressing genetic engineering.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-022",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some poets are pessimists. No optimists are cynics. Therefore, some poets are not cynics.`,
    questionStem: "The reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some athletes are vegetarians. All vegetarians avoid meat. Therefore, some athletes avoid meat." },
      { letter: "B", text: "Some lawyers are wealthy. No wealthy people are financially insecure. Therefore, some lawyers are not financially insecure." },
      { letter: "C", text: "All birds have feathers. Some animals have feathers. Therefore, some animals are birds." },
      { letter: "D", text: "No reptiles are mammals. Some pets are mammals. Therefore, no pets are reptiles." },
      { letter: "E", text: "Some students are athletes. Some athletes are not scholars. Therefore, some students are not scholars." },
    ],
    correctAnswer: "B",
    explanation: "Pattern: Some A are B. No C are D. Therefore, some A are not D. Wait, let me reconsider. The original says: Some poets are pessimists. No optimists are cynics. Therefore some poets are not cynics. Actually B follows: Some lawyers wealthy; no wealthy financially insecure; some lawyers not financially insecure. Similar valid pattern.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-023",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: One should not benefit from one's own wrongdoing.`,
    questionStem: "Which one of the following judgments most closely conforms to the principle?",
    answerChoices: [
      { letter: "A", text: "A person who accidentally damages a competitor's product should not gain market share as a result" },
      { letter: "B", text: "An employee who fraudulently claims credit for a colleague's work should not receive the resulting promotion" },
      { letter: "C", text: "A company that unknowingly violates environmental regulations should not be forced to pay fines" },
      { letter: "D", text: "An athlete who loses due to a referee's error should still receive a medal" },
      { letter: "E", text: "A charity that receives stolen funds should be allowed to keep them if they were already spent on charitable work" },
    ],
    correctAnswer: "B",
    explanation: "The principle says wrongdoers shouldn't benefit from their wrongs. B fits: the employee committed wrong (fraud) and is seeking benefit (promotion) from that wrong. A involves accident (not wrongdoing), C involves unknowing violation, D and E address others' wrongs.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-024",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Consultant: Your company's marketing strategy must be flawed. After all, your main competitor's sales have grown faster than yours over the past year, and they must be doing something better.`,
    questionStem: "The consultant's reasoning is most vulnerable to criticism on which of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It fails to consider that both companies' sales might be growing" },
      { letter: "B", text: "It assumes that marketing strategy is the only factor affecting sales growth" },
      { letter: "C", text: "It does not specify what changes the company should make" },
      { letter: "D", text: "It relies on incomplete data about the competitor's performance" },
      { letter: "E", text: "It presumes that the consultant is qualified to assess marketing strategies" },
    ],
    correctAnswer: "B",
    explanation: "The consultant assumes marketing explains the sales difference. But sales depend on many factors: product quality, pricing, distribution, market conditions, and luck. The competitor might excel in other areas while having similar marketing.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-025",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researcher: Playing chess improves children's mathematical abilities. Students who participated in a chess program showed significant improvement in math scores.`,
    questionStem: "Which one of the following, if true, most strengthens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Chess has been popular in schools for many decades" },
      { letter: "B", text: "Students not in the chess program showed no similar improvement in math scores during the same period" },
      { letter: "C", text: "Chess requires strategic thinking similar to that used in advanced mathematics" },
      { letter: "D", text: "Students in the chess program also improved in reading comprehension" },
      { letter: "E", text: "The chess program was taught by professional chess players" },
    ],
    correctAnswer: "B",
    explanation: "A control group showing no improvement rules out alternative explanations like curriculum changes, maturation, or test familiarity. If chess students improved but others didn't, chess is more likely the cause.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-026",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The art gallery displays only paintings created after 1900. All cubist paintings in the gallery are by Picasso. Some paintings by Picasso in the gallery are not cubist.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All paintings by Picasso were created after 1900" },
      { letter: "B", text: "The gallery displays some paintings created before 1900" },
      { letter: "C", text: "All cubist paintings were created after 1900" },
      { letter: "D", text: "Some paintings in the gallery by Picasso were created after 1900" },
      { letter: "E", text: "All paintings in the gallery are cubist" },
    ],
    correctAnswer: "D",
    explanation: "The gallery has Picasso paintings (given). All gallery paintings are post-1900 (given). Therefore, the Picasso paintings in the gallery are post-1900. So some Picasso paintings in the gallery were created after 1900.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-027",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Fashion critic: Fast fashion is destroying clothing quality. Since fast fashion became dominant, the average garment is worn only seven times before being discarded, compared to over thirty times a generation ago.`,
    questionStem: "Which one of the following, if true, most weakens the critic's argument?",
    answerChoices: [
      { letter: "A", text: "Fast fashion garments are less expensive than traditional clothing" },
      { letter: "B", text: "Consumer attitudes toward clothing ownership have changed, with many now preferring variety over longevity regardless of quality" },
      { letter: "C", text: "Some fast fashion brands have introduced recycling programs" },
      { letter: "D", text: "Clothing production has increased substantially since fast fashion emerged" },
      { letter: "E", text: "Some luxury brands have also reduced their quality standards" },
    ],
    correctAnswer: "B",
    explanation: "The critic assumes low wear counts indicate poor quality. But if consumer preferences have changed (people want variety, not durability), clothes might be worn less because of changing attitudes, not declining quality. The correlation doesn't prove quality is the cause.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Advisor: Students should take a gap year before college. Students who take gap years have higher graduation rates than those who go directly to college.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Gap years are financially accessible to all students" },
      { letter: "B", text: "The higher graduation rates are at least partly due to the gap year experience itself" },
      { letter: "C", text: "All students would benefit equally from a gap year" },
      { letter: "D", text: "Students who take gap years are more intelligent than those who don't" },
      { letter: "E", text: "Gap years always involve productive activities" },
    ],
    correctAnswer: "B",
    explanation: "The advisor recommends gap years based on correlation with graduation rates. This assumes the gap year contributes to graduation success. If gap-year students were already more motivated or mature (and would have succeeded anyway), recommending gap years wouldn't help.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-029",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `Despite spending less time studying than their classmates, students in the music program consistently achieve higher grades in all subjects, including those unrelated to music.`,
    questionStem: "Which one of the following, if true, most helps to explain the apparent paradox?",
    answerChoices: [
      { letter: "A", text: "The music program has rigorous admission standards that select for academically capable students" },
      { letter: "B", text: "Music students receive additional tutoring from the school" },
      { letter: "C", text: "Most music program students come from wealthy families" },
      { letter: "D", text: "The music program requires significant time commitments for practice" },
      { letter: "E", text: "Many music students plan to pursue careers in music" },
    ],
    correctAnswer: "A",
    explanation: "Selection bias. If admission to the music program requires strong academics, music students were already high achievers before joining. Their success reflects who was selected, not what music does. Less study time doesn't matter if they're naturally strong students.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-030",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The claim that the Great Wall of China is visible from space is a myth. While the wall is extremely long, it is also quite narrow—only about 15 feet wide. This is far too thin to be distinguished from the surrounding terrain at orbital distances, as confirmed by astronauts who have looked for it.`,
    questionStem: "The historian's argument primarily relies on",
    answerChoices: [
      { letter: "A", text: "appeal to authority" },
      { letter: "B", text: "analogy to similar structures" },
      { letter: "C", text: "physical reasoning supported by eyewitness testimony" },
      { letter: "D", text: "statistical analysis of visual acuity" },
      { letter: "E", text: "historical documentation of the wall's construction" },
    ],
    correctAnswer: "C",
    explanation: "The historian explains why it's physically impossible (too narrow for the distance) and then confirms this reasoning with astronaut testimony. The argument combines physical/geometric reasoning with eyewitness verification.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Local resident: The new shopping mall will not increase traffic congestion. A similar mall opened in Riverside, and traffic there remained manageable.`,
    questionStem: "The resident's argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "relies on a potentially unrepresentative comparison case" },
      { letter: "B", text: "ignores the economic benefits of the mall" },
      { letter: "C", text: "assumes that all malls generate identical traffic" },
      { letter: "D", text: "does not consider the opinions of mall developers" },
      { letter: "E", text: "fails to define 'manageable' traffic" },
    ],
    correctAnswer: "A",
    explanation: "One case in a different location may not be representative. Riverside might have different road infrastructure, population density, public transit options, or mall size. What worked there might not apply here.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Criminologist: Reducing prison sentences for nonviolent offenders will not increase crime rates. Several states that reduced sentences saw no increase in recidivism.`,
    questionStem: "Which one of the following, if true, most strengthens the criminologist's argument?",
    answerChoices: [
      { letter: "A", text: "The states that reduced sentences invested savings in rehabilitation programs" },
      { letter: "B", text: "Violent crime is more common than nonviolent crime" },
      { letter: "C", text: "Public opinion supports shorter sentences for nonviolent offenders" },
      { letter: "D", text: "Long sentences are expensive for state budgets" },
      { letter: "E", text: "Some nonviolent offenders were wrongly convicted" },
    ],
    correctAnswer: "A",
    explanation: "This explains why recidivism didn't increase—rehabilitation programs helped. It strengthens the argument that reducing sentences can work if accompanied by appropriate support, rather than suggesting the correlation was coincidental.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-033",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Analyst: Working from home increases productivity. Companies that allowed remote work during the pandemic reported that employee output increased.`,
    questionStem: "Which one of the following, if true, most weakens the analyst's conclusion?",
    answerChoices: [
      { letter: "A", text: "Not all jobs can be performed remotely" },
      { letter: "B", text: "Companies may have only reported positive results while suppressing negative data" },
      { letter: "C", text: "Working from home saves employees commute time" },
      { letter: "D", text: "Some employees prefer working in an office" },
      { letter: "E", text: "Technology enables efficient remote collaboration" },
    ],
    correctAnswer: "B",
    explanation: "Reporting bias. If companies selectively report positive results, the data is skewed. Companies with decreased productivity might not publicize this, making remote work look more effective than it actually is.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-034",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All judges must be lawyers. Some lawyers are not judges. All judges appointed this year have at least ten years of legal experience.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All lawyers have at least ten years of legal experience" },
      { letter: "B", text: "All people with ten years of legal experience are judges" },
      { letter: "C", text: "Judges appointed this year are lawyers with at least ten years of experience" },
      { letter: "D", text: "Some lawyers have at least ten years of legal experience" },
      { letter: "E", text: "No one can become a judge without being a lawyer first" },
    ],
    correctAnswer: "C",
    explanation: "All judges must be lawyers. Judges appointed this year have 10+ years experience. Therefore, judges appointed this year are lawyers with 10+ years experience. This combines the two conditions that apply to new judges.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-035",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: An action is morally permissible if it produces more good than harm for all those affected by it.`,
    questionStem: "Which one of the following actions is most clearly permissible according to the principle?",
    answerChoices: [
      { letter: "A", text: "Breaking a promise to one person in order to prevent serious harm to many others" },
      { letter: "B", text: "Lying to protect one's reputation from a false accusation" },
      { letter: "C", text: "Taking credit for a colleague's work to receive a deserved promotion" },
      { letter: "D", text: "Stealing food from a wealthy person to feed oneself" },
      { letter: "E", text: "Speeding to get to a meeting on time" },
    ],
    correctAnswer: "A",
    explanation: "The principle weighs total good vs. harm for all affected. A shows a clear case: minor harm (one broken promise) prevents serious harm to many. This produces more good than harm overall. The other options don't clearly show net positive outcomes for all affected.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-036",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Pet owner: Cats make better pets than dogs. My cat requires much less attention than my neighbor's dog, and cats are generally more independent.`,
    questionStem: "The pet owner's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "compares a specific cat to a specific dog rather than cats and dogs generally" },
      { letter: "B", text: "assumes that requiring less attention makes a better pet" },
      { letter: "C", text: "does not consider the costs of pet ownership" },
      { letter: "D", text: "ignores that some people prefer dogs" },
      { letter: "E", text: "fails to define what makes a pet 'good'" },
    ],
    correctAnswer: "B",
    explanation: "The pet owner equates 'requires less attention' with 'better.' But 'better' is subjective—some people want pets that are affectionate and interactive. The argument assumes everyone values independence, which isn't true.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-037",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `The government provides free preventive health screenings, yet fewer people get screened now than when they had to pay for screenings.`,
    questionStem: "Which one of the following, if true, most helps to explain the decline in screening rates?",
    answerChoices: [
      { letter: "A", text: "People perceive free services as lower quality than paid services" },
      { letter: "B", text: "The screenings are now only available at government clinics with limited hours" },
      { letter: "C", text: "Health outcomes have improved overall in recent years" },
      { letter: "D", text: "The population has grown since screenings became free" },
      { letter: "E", text: "Doctors still recommend regular health screenings" },
    ],
    correctAnswer: "B",
    explanation: "Accessibility matters more than cost for some people. If free screenings are only at inconvenient locations or times, people might find it harder to get screened than when they could pay for convenient appointments at their own doctor.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-038",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: Contrary to popular belief, lightning can and does strike the same place twice. The Empire State Building is struck by lightning about 20 to 25 times per year, definitively disproving the old saying.`,
    questionStem: "The scientist's argument primarily proceeds by",
    answerChoices: [
      { letter: "A", text: "explaining the scientific mechanism behind lightning strikes" },
      { letter: "B", text: "citing a specific counterexample to disprove a general claim" },
      { letter: "C", text: "appealing to scientific authority to settle a debate" },
      { letter: "D", text: "comparing different types of lightning events" },
      { letter: "E", text: "questioning the reliability of popular sayings generally" },
    ],
    correctAnswer: "B",
    explanation: "The scientist disproves the saying 'lightning never strikes the same place twice' by providing a clear counterexample: the Empire State Building, which is struck many times annually. One definitive counterexample disproves a universal negative claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank4-039",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Nothing that is artificial is organic. Some foods are organic. Therefore, some foods are not artificial.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to which one of the following?",
    answerChoices: [
      { letter: "A", text: "Nothing valuable is free. Some experiences are free. Therefore, some experiences are not valuable." },
      { letter: "B", text: "All cars require fuel. Some vehicles do not require fuel. Therefore, some vehicles are not cars." },
      { letter: "C", text: "No reptiles are mammals. All cats are mammals. Therefore, no cats are reptiles." },
      { letter: "D", text: "Some dogs are not friendly. All pets should be friendly. Therefore, some dogs should not be pets." },
      { letter: "E", text: "Nothing illegal is ethical. Some business practices are unethical. Therefore, some business practices are illegal." },
    ],
    correctAnswer: "A",
    explanation: "Pattern: No A is B. Some C are B. Therefore, some C are not A. Original: Nothing artificial is organic; some foods are organic; some foods are not artificial. A: Nothing valuable is free; some experiences are free; some experiences are not valuable. Same pattern.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-040",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Coach: Natural talent is overrated in sports. The most successful athletes are those who practice the most, not those with the most natural ability.`,
    questionStem: "The coach's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Practice can compensate for a lack of natural talent" },
      { letter: "B", text: "All athletes have access to equal practice facilities" },
      { letter: "C", text: "Natural talent has no value in athletic success" },
      { letter: "D", text: "The most talented athletes do not also practice the most" },
      { letter: "E", text: "Success in sports can be objectively measured" },
    ],
    correctAnswer: "D",
    explanation: "The coach argues that practice, not talent, explains success. But if talented athletes also practice more (maybe talent provides motivation and early success that encourages practice), the correlation with practice might actually reflect underlying talent. The argument assumes the two don't go together.",
    difficulty: "hard",
  },
  {
    id: "lr-bank4-041",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The Roman Empire's fall was primarily due to military overextension. The empire reached its greatest territorial extent in 117 CE and began declining shortly after.`,
    questionStem: "Which one of the following, if true, most strengthens the historian's argument?",
    answerChoices: [
      { letter: "A", text: "The Roman military was considered the most powerful in the ancient world" },
      { letter: "B", text: "Defending the extended borders required more soldiers than Rome could sustainably recruit or afford" },
      { letter: "C", text: "Other ancient empires also expanded before declining" },
      { letter: "D", text: "Roman emperors increasingly relied on foreign mercenaries" },
      { letter: "E", text: "The Roman Empire lasted for several centuries after 117 CE" },
    ],
    correctAnswer: "B",
    explanation: "This explains the mechanism connecting overextension to decline: unsustainable demands on military resources. It shows how territorial size directly caused problems that could lead to decline, strengthening the causal claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-042",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Educator: Homework is essential for learning. Students who complete homework regularly perform better on tests than those who don't.`,
    questionStem: "Which one of the following, if true, most weakens the educator's argument?",
    answerChoices: [
      { letter: "A", text: "Some students learn effectively without homework" },
      { letter: "B", text: "Students who complete homework may be more motivated and attentive in class generally" },
      { letter: "C", text: "Homework takes time away from other activities" },
      { letter: "D", text: "Some types of homework are more effective than others" },
      { letter: "E", text: "Teachers assign different amounts of homework" },
    ],
    correctAnswer: "B",
    explanation: "This suggests the correlation is explained by a third variable (motivation/attentiveness) that causes both homework completion and test performance. The homework itself might not be essential—motivated students would perform well anyway.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-043",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `No one without a security badge can enter the laboratory. Everyone with a security badge has undergone a background check. Chen has not undergone a background check.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Chen does not have a security badge" },
      { letter: "B", text: "Chen has never entered the laboratory" },
      { letter: "C", text: "Chen cannot enter the laboratory" },
      { letter: "D", text: "Everyone who has undergone a background check has a security badge" },
      { letter: "E", text: "Chen will fail to undergo a background check" },
    ],
    correctAnswer: "A",
    explanation: "Everyone with a badge has had a background check. Chen hasn't had a background check. Therefore, Chen doesn't have a badge. (We can infer C too, but A is more directly proven from the given statements.)",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-044",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Movie critic: This director's films must be of high quality because they have won numerous awards at prestigious film festivals.`,
    questionStem: "The critic's reasoning is most vulnerable to which of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It assumes that festival judges are infallible arbiters of quality" },
      { letter: "B", text: "It fails to name the specific awards won" },
      { letter: "C", text: "It ignores the director's earlier, less successful films" },
      { letter: "D", text: "It assumes that all film festivals have the same standards" },
      { letter: "E", text: "It does not consider box office performance" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes awards = quality. But awards reflect judges' opinions, which may differ from objective quality (if such a thing exists) or popular opinion. Festival preferences might be biased toward certain styles or themes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-045",
    type: "resolve-paradox",
    sectionType: "logical-reasoning",
    stimulus: `A country known for its excellent public schools has seen private school enrollment increase by 30% over the past decade, even though private schools cost significantly more than the free public option.`,
    questionStem: "Which one of the following, if true, most helps to explain the increase in private school enrollment?",
    answerChoices: [
      { letter: "A", text: "Population growth has increased overall school enrollment" },
      { letter: "B", text: "Rising income inequality means wealthy families can better afford private school tuition" },
      { letter: "C", text: "Private schools have increased their marketing efforts" },
      { letter: "D", text: "Public schools have maintained consistent quality standards" },
      { letter: "E", text: "Some private schools have reduced their tuition costs" },
    ],
    correctAnswer: "B",
    explanation: "If more families now have the wealth to afford private schools (due to rising inequality concentrating wealth), demand for private schools increases even if public schools remain excellent. Those who can afford the premium are exercising the option.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-046",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution claims my client had motive to commit the crime. But millions of people might have had similar motives, yet only one person committed this crime. Motive alone proves nothing.`,
    questionStem: "The defense attorney's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing an alibi for the defendant" },
      { letter: "B", text: "showing that the prosecution's evidence does not uniquely implicate the defendant" },
      { letter: "C", text: "attacking the character of prosecution witnesses" },
      { letter: "D", text: "presenting alternative suspects for the crime" },
      { letter: "E", text: "challenging the accuracy of the prosecution's timeline" },
    ],
    correctAnswer: "B",
    explanation: "The attorney argues that motive is not sufficiently probative because many people could have it. Since the evidence doesn't uniquely point to the defendant, it shouldn't be considered strong evidence of guilt.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All efficient machines are well-maintained. This machine is not efficient. Therefore, this machine is not well-maintained.`,
    questionStem: "The flawed reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All fish can swim. This animal can swim. Therefore, this animal is a fish." },
      { letter: "B", text: "All lions are carnivores. This animal is not a lion. Therefore, this animal is not a carnivore." },
      { letter: "C", text: "All squares are rectangles. This shape is a rectangle. Therefore, this shape is a square." },
      { letter: "D", text: "No birds are mammals. This animal is a bird. Therefore, this animal is not a mammal." },
      { letter: "E", text: "Some dogs are friendly. This animal is friendly. Therefore, this animal might be a dog." },
    ],
    correctAnswer: "B",
    explanation: "Both commit denying the antecedent: All A are B; X is not A; therefore X is not B. Original: All efficient machines are maintained; this isn't efficient; therefore not maintained. B: All lions are carnivores; not a lion; therefore not a carnivore. Both invalid.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-048",
    type: "principle-apply",
    sectionType: "logical-reasoning",
    stimulus: `Principle: Public officials should not use their positions for personal financial gain.`,
    questionStem: "Which one of the following most clearly violates the principle?",
    answerChoices: [
      { letter: "A", text: "A mayor donates their entire salary to charity" },
      { letter: "B", text: "A council member votes against a proposal that would benefit their own business" },
      { letter: "C", text: "A regulator accepts employment at a company they recently regulated, receiving a large salary" },
      { letter: "D", text: "A legislator invests their personal savings in diversified index funds" },
      { letter: "E", text: "An official uses vacation time to attend a family wedding" },
    ],
    correctAnswer: "C",
    explanation: "The principle prohibits using official positions for personal financial gain. C shows a regulator potentially trading favorable regulatory treatment for future employment—using their position's influence for later financial benefit.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-049",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: This site was a major trading center. Artifacts from at least six different cultures have been found here.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "The site is located on an ancient river route" },
      { letter: "B", text: "Objects from these cultures are found together in layers suggesting simultaneous presence" },
      { letter: "C", text: "The site covers a large geographic area" },
      { letter: "D", text: "Similar multi-cultural sites exist elsewhere" },
      { letter: "E", text: "The artifacts are well-preserved" },
    ],
    correctAnswer: "B",
    explanation: "Artifacts from different cultures could indicate sequential occupation rather than trade. If they appear together in the same layers (simultaneously), it suggests cultures were present at the same time—more consistent with a trading hub where different groups met.",
    difficulty: "medium",
  },
  {
    id: "lr-bank4-050",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Publisher: E-books will eventually replace printed books entirely. E-book sales have grown consistently every year for the past decade.`,
    questionStem: "Which one of the following, if true, most weakens the publisher's prediction?",
    answerChoices: [
      { letter: "A", text: "E-book sales growth has slowed significantly in recent years and appears to be plateauing" },
      { letter: "B", text: "Some people prefer the feel of physical books" },
      { letter: "C", text: "E-book readers require charging" },
      { letter: "D", text: "Libraries continue to lend physical books" },
      { letter: "E", text: "E-books are sometimes less expensive than printed books" },
    ],
    correctAnswer: "A",
    explanation: "The prediction of complete replacement assumes continued growth. If growth is slowing and plateauing, e-books might stabilize at a market share rather than eventually capturing the entire market. Past growth doesn't guarantee future dominance.",
    difficulty: "medium",
  },
];
