// Logical Reasoning Questions Bank - Set 45
import { Question } from "../lsat-types";

export const lrQuestionsSet45: Question[] = [
  {
    id: "lr-bank45-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during the workday are more productive than those who work continuously. Therefore, companies should require all employees to take mandatory breaks every hour, as this will maximize overall productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that some employees may already take regular breaks voluntarily" },
      { letter: "B", text: "assumes that what increases productivity when chosen voluntarily will have the same effect when mandated" },
      { letter: "C", text: "relies on a study without specifying its methodology" },
      { letter: "D", text: "overlooks the possibility that continuous work has other benefits besides productivity" },
      { letter: "E", text: "confuses correlation between breaks and productivity with causation" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that mandatory breaks will have the same positive effect as voluntary breaks. However, the study only showed that employees who choose to take breaks are more productive. When breaks are forced, employees may resent the interruption or find them disruptive, potentially eliminating the productivity benefit.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists discovered pottery fragments in a cave that were initially dated to 3000 BCE. However, a closer examination revealed that the clay composition matches clay deposits found only in a region 500 miles away. The archaeologists concluded that ancient peoples must have engaged in long-distance trade much earlier than previously believed.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologists' conclusion?",
    answerChoices: [
      { letter: "A", text: "The cave contains other artifacts that are clearly of local origin" },
      { letter: "B", text: "Similar pottery styles have been found at sites between the cave and the distant clay source" },
      { letter: "C", text: "The distant clay source was not accessible by water routes" },
      { letter: "D", text: "No clay deposits with the same composition exist anywhere closer to the cave" },
      { letter: "E", text: "The pottery fragments show signs of heavy use before being discarded" },
    ],
    correctAnswer: "D",
    explanation: "If no clay with the same composition exists closer to the cave, then the pottery must have come from the distant source 500 miles away. This eliminates the possibility that the clay came from a closer, unknown source and strongly supports the conclusion about long-distance trade.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that building a new sports stadium downtown will revitalize the urban core. They point to another city that built a stadium five years ago and has since seen a 30% increase in downtown business activity. Clearly, the stadium was responsible for this economic growth.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "The stadium in the other city was built with public funds" },
      { letter: "B", text: "The other city also implemented major tax incentives for downtown businesses at the same time the stadium was built" },
      { letter: "C", text: "Some residents of the other city opposed the stadium construction" },
      { letter: "D", text: "The new stadium would be larger than the one in the other city" },
      { letter: "E", text: "Downtown business activity in the other city had been declining before the stadium was built" },
    ],
    correctAnswer: "B",
    explanation: "If the other city implemented major tax incentives at the same time as the stadium was built, then the increase in business activity could be due to those incentives rather than the stadium. This alternative explanation weakens the claim that the stadium was responsible for the economic growth.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All truly great works of literature challenge readers to question their fundamental assumptions about life. This novel, while popular, simply reinforces comfortable beliefs that readers already hold. Therefore, despite its commercial success, this novel cannot be considered a great work of literature.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Commercial success is incompatible with literary greatness" },
      { letter: "B", text: "A work that reinforces existing beliefs cannot also challenge fundamental assumptions" },
      { letter: "C", text: "Popular novels are generally not considered great literature" },
      { letter: "D", text: "Readers prefer novels that reinforce their existing beliefs" },
      { letter: "E", text: "The author of this novel did not intend to challenge readers" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes the novel is not great because it reinforces existing beliefs rather than challenging assumptions. This assumes that reinforcing beliefs and challenging assumptions are mutually exclusive. If a novel could do both simultaneously, the argument would fail.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical researchers have found that patients who have strong social support networks recover from major surgery faster than those who are socially isolated. This suggests that hospitals should encourage family visitation. However, increased visitation can disrupt hospital routines and introduce infection risks. Therefore, hospitals must carefully balance the psychological benefits of visitation against these practical concerns.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Strong social support networks help patients recover from surgery faster" },
      { letter: "B", text: "Hospitals should encourage family visitation" },
      { letter: "C", text: "Increased visitation can disrupt hospital routines and introduce infection risks" },
      { letter: "D", text: "Hospitals must carefully balance the psychological benefits of visitation against practical concerns" },
      { letter: "E", text: "Medical researchers have made important discoveries about recovery" },
    ],
    correctAnswer: "D",
    explanation: "The word 'Therefore' signals the main conclusion. The argument presents evidence that social support aids recovery (suggesting more visitation) and counterevidence about practical problems with visitation, then concludes that hospitals must balance these competing considerations.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martinez argues that we should increase funding for space exploration because it advances scientific knowledge. But Professor Martinez has received several grants from NASA for her research. Therefore, her arguments about space exploration funding should be dismissed.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to establish that Professor Martinez's research is actually funded by NASA" },
      { letter: "B", text: "attacks the source of an argument rather than addressing the argument itself" },
      { letter: "C", text: "assumes that all scientists who receive grants are biased" },
      { letter: "D", text: "overlooks the possibility that space exploration has benefits beyond scientific knowledge" },
      { letter: "E", text: "fails to consider whether Professor Martinez's grants represent a conflict of interest" },
    ],
    correctAnswer: "B",
    explanation: "This is an ad hominem fallacy. The argument dismisses Professor Martinez's position based on her personal situation (receiving NASA grants) rather than addressing whether her argument about space exploration advancing scientific knowledge is actually sound. Even if she has a potential bias, her argument could still be valid.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-007",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The film industry claims that movie piracy costs billions in lost revenue. However, many people who download pirated movies would never have paid to see those movies in the first place. These people represent zero lost revenue, not the full ticket price the industry claims. While some revenue is certainly lost to piracy, the industry's estimates are greatly exaggerated.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing an alternative explanation for a phenomenon" },
      { letter: "B", text: "challenging an assumption underlying an opponent's position" },
      { letter: "C", text: "demonstrating that an opponent's conclusion is self-contradictory" },
      { letter: "D", text: "using statistical evidence to refute a claim" },
      { letter: "E", text: "questioning the motives of those making a claim" },
    ],
    correctAnswer: "B",
    explanation: "The film industry's revenue loss estimate assumes that every pirated download represents a lost sale. The critic challenges this assumption by pointing out that many pirates would never have paid anyway. By undermining this assumption, the critic argues the industry's estimates are exaggerated.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Studies show that children who learn to play a musical instrument perform better in mathematics. Some educators have therefore proposed that all schools require instrumental music education. These educators believe that music training directly enhances mathematical reasoning abilities.`,
    questionStem: "Which one of the following, if true, most strengthens the educators' reasoning?",
    answerChoices: [
      { letter: "A", text: "Children who excel at mathematics often choose to study music" },
      { letter: "B", text: "Music and mathematics both require the ability to recognize patterns" },
      { letter: "C", text: "Schools that offer music programs tend to have more funding overall" },
      { letter: "D", text: "Children who began music training showed subsequent improvement in math scores, while a control group did not" },
      { letter: "E", text: "Many professional mathematicians report enjoying music as a hobby" },
    ],
    correctAnswer: "D",
    explanation: "The educators claim music training directly enhances mathematical ability. Choice D provides evidence of a causal relationship: children who received music training improved in math while those who didn't showed no improvement. This controlled comparison supports the claim that music training causes math improvement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-009",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The government should not subsidize electric vehicle purchases. Such subsidies primarily benefit wealthy individuals who can already afford these vehicles, while the working class continues to rely on older, less efficient gasoline-powered cars. Government subsidies should reduce inequality, not increase it.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Electric vehicles are more expensive than gasoline-powered vehicles" },
      { letter: "B", text: "The working class would not benefit from the environmental improvements resulting from more electric vehicles" },
      { letter: "C", text: "Government subsidies for electric vehicles do not reduce inequality" },
      { letter: "D", text: "The primary purpose of any government subsidy should be to reduce inequality" },
      { letter: "E", text: "Wealthy individuals do not need financial assistance to purchase electric vehicles" },
    ],
    correctAnswer: "C",
    explanation: "The argument's structure is: subsidies should reduce inequality; these subsidies don't reduce inequality (they increase it); therefore, the government shouldn't provide them. The argument must assume that EV subsidies do not reduce inequality. Without this assumption, the argument fails.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company argues that its new pain medication is superior to existing options because in clinical trials, 80% of patients reported significant pain relief. The company's marketing materials emphasize this high success rate as evidence of the drug's exceptional effectiveness.`,
    questionStem: "Which one of the following, if true, most weakens the company's argument?",
    answerChoices: [
      { letter: "A", text: "The new medication is more expensive than existing pain relievers" },
      { letter: "B", text: "Existing pain medications typically show a 75% or higher success rate in similar trials" },
      { letter: "C", text: "Some patients in the trial experienced mild side effects" },
      { letter: "D", text: "The trial lasted only six weeks" },
      { letter: "E", text: "Pain relief is subjective and difficult to measure precisely" },
    ],
    correctAnswer: "B",
    explanation: "The company claims the new drug is superior based on an 80% success rate. However, if existing medications already achieve 75% or higher success rates, then the new drug's 80% rate is not exceptionally better. This undermines the claim that the new medication is superior to existing options.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-011",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every successful entrepreneur I have met has been willing to take significant financial risks. Jennifer is clearly willing to take significant financial risks, as she just invested her entire savings in a startup. Therefore, Jennifer will be a successful entrepreneur.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on a sample that may not be representative" },
      { letter: "B", text: "treats a characteristic common to successful entrepreneurs as sufficient for success" },
      { letter: "C", text: "fails to define what constitutes significant financial risk" },
      { letter: "D", text: "assumes that Jennifer's investment decision was rational" },
      { letter: "E", text: "overlooks the role of luck in entrepreneurial success" },
    ],
    correctAnswer: "B",
    explanation: "The argument establishes that risk-taking is a necessary condition for entrepreneurial success (all successful entrepreneurs take risks). But it then concludes that because Jennifer takes risks, she will succeed. This confuses a necessary condition with a sufficient condition. Risk-taking may be required for success but doesn't guarantee it.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Thomas: Autonomous vehicles will dramatically reduce traffic accidents because human error causes over 90% of crashes. Removing the human element will make roads much safer.

    Patricia: I disagree. Autonomous vehicles rely on complex software that can malfunction or be hacked. Additionally, these vehicles struggle with unusual situations that human drivers handle intuitively. Autonomous vehicles may actually create new types of dangers.`,
    questionStem: "Thomas and Patricia disagree about whether",
    answerChoices: [
      { letter: "A", text: "human error is responsible for the majority of traffic accidents" },
      { letter: "B", text: "autonomous vehicle software can be hacked" },
      { letter: "C", text: "autonomous vehicles will make roads safer overall" },
      { letter: "D", text: "human drivers can handle unusual situations better than autonomous vehicles" },
      { letter: "E", text: "new technologies always introduce new risks" },
    ],
    correctAnswer: "C",
    explanation: "Thomas explicitly claims autonomous vehicles will make roads safer by reducing human error. Patricia explicitly disagrees, arguing they may create new dangers. Both directly address whether autonomous vehicles will improve overall road safety, making this the point at issue.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No responsible journalist publishes unverified information. This article contains several unverified claims. Therefore, the author of this article is not a responsible journalist.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All professional athletes train daily. Marcus trains daily. Therefore, Marcus is a professional athlete." },
      { letter: "B", text: "No honest person cheats on exams. David cheated on his exam. Therefore, David is not an honest person." },
      { letter: "C", text: "Every good teacher is patient. Some patient people are not good teachers. Therefore, patience is not sufficient for being a good teacher." },
      { letter: "D", text: "Most successful businesses have detailed plans. This business has a detailed plan. Therefore, this business will probably be successful." },
      { letter: "E", text: "All mammals are warm-blooded. Snakes are not warm-blooded. Therefore, snakes are not mammals." },
    ],
    correctAnswer: "B",
    explanation: "The original argument follows this pattern: No X does Y; This entity did Y; Therefore, this entity is not X. Choice B follows the identical pattern: No honest person cheats; David cheated; Therefore, David is not honest. This is a valid logical form (denying a necessary condition).",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-014",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The discovery of water ice on Mars greatly increases the probability of establishing a permanent human colony there. Water can be converted to oxygen for breathing and hydrogen for fuel. With these resources available on Mars, the colony would not need constant supply missions from Earth.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Water ice on Mars exists in quantities sufficient for human use" },
      { letter: "B", text: "Establishing a Mars colony is a worthwhile goal" },
      { letter: "C", text: "No other sources of oxygen or hydrogen exist on Mars" },
      { letter: "D", text: "Technology to convert Martian ice to oxygen and hydrogen already exists" },
      { letter: "E", text: "Supply missions from Earth are prohibitively expensive" },
    ],
    correctAnswer: "A",
    explanation: "The argument claims the ice discovery increases colonization probability because the ice can provide resources. This assumes there is enough ice to actually serve this purpose. If the ice exists only in trace amounts, it wouldn't reduce the need for Earth supplies.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers found that patients who listened to classical music before surgery experienced less anxiety than those who did not. The researchers concluded that hospitals should play classical music in pre-operative waiting areas to reduce patient anxiety.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' recommendation?",
    answerChoices: [
      { letter: "A", text: "The patients in the study were all undergoing the same type of surgery" },
      { letter: "B", text: "Patients who chose to listen to their preferred genre of music showed even greater anxiety reduction" },
      { letter: "C", text: "Reduced pre-operative anxiety has been linked to better surgical outcomes" },
      { letter: "D", text: "Some patients in the study had never listened to classical music before" },
      { letter: "E", text: "The calming effect of classical music is well-documented in psychological literature" },
    ],
    correctAnswer: "C",
    explanation: "The researchers recommend playing classical music to reduce anxiety. If reduced anxiety leads to better surgical outcomes, this provides an additional, medically important reason to follow the recommendation, significantly strengthening the argument for implementing this practice.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-016",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Critics of the proposed minimum wage increase claim it will cause unemployment. However, three major economists support the increase. These economists have impressive credentials and have published extensively. Therefore, the critics are wrong, and the minimum wage increase will not cause unemployment.`,
    questionStem: "The argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on the authority of experts rather than addressing the substance of the critics' concerns" },
      { letter: "B", text: "fails to specify the credentials of the economists" },
      { letter: "C", text: "ignores the possibility that many economists oppose the increase" },
      { letter: "D", text: "assumes that all economists agree on economic matters" },
      { letter: "E", text: "does not consider the interests of workers who would benefit from the increase" },
    ],
    correctAnswer: "A",
    explanation: "The argument dismisses the critics' position solely because some economists with good credentials support the increase. This is an appeal to authority. The argument never actually addresses whether the critics' claim about unemployment is correct or incorrect based on economic reasoning or evidence.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-017",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A city's traffic department concluded that installing roundabouts instead of traffic signals reduces accidents. They based this on data showing that intersections converted to roundabouts had 40% fewer accidents than before the conversion.`,
    questionStem: "Which one of the following, if true, most weakens the traffic department's conclusion?",
    answerChoices: [
      { letter: "A", text: "Roundabouts are more expensive to construct than traffic signals" },
      { letter: "B", text: "The intersections selected for conversion had unusually high accident rates before the change" },
      { letter: "C", text: "Some drivers find roundabouts confusing at first" },
      { letter: "D", text: "Traffic signal technology has improved in recent years" },
      { letter: "E", text: "Other cities have also reported success with roundabouts" },
    ],
    correctAnswer: "B",
    explanation: "If the converted intersections had unusually high accident rates before conversion, the reduction could be due to regression to the mean rather than the roundabouts themselves. Extreme cases naturally tend to become more typical over time. This alternative explanation weakens the conclusion that roundabouts are responsible for the reduction.",
    difficulty: "hard",
  },
  {
    id: "lr-bank45-018",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `People often claim that television has a negative effect on children's reading habits. But consider that when television first became widespread in the 1950s, literacy rates and library usage actually increased. If television harmed reading habits, we would have seen the opposite trend. Therefore, television does not harm children's reading habits.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "presenting statistical evidence that contradicts a causal claim" },
      { letter: "B", text: "arguing that if a claim were true, certain consequences would follow, then showing those consequences did not occur" },
      { letter: "C", text: "demonstrating that correlation does not imply causation" },
      { letter: "D", text: "attacking the credibility of those who make the opposing claim" },
      { letter: "E", text: "showing that an opposing view is based on outdated information" },
    ],
    correctAnswer: "B",
    explanation: "The argument uses a modus tollens structure. It reasons that if television harmed reading (hypothesis), literacy would have declined (predicted consequence). Since literacy actually increased (consequence did not occur), television does not harm reading (hypothesis is false). This is reasoning by contraposition.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-019",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All partners in the law firm are required to have at least ten years of legal experience. Some attorneys at the firm specialize in corporate law. The firm recently promoted two attorneys who specialize in corporate law to partner status.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All attorneys who specialize in corporate law have at least ten years of experience" },
      { letter: "B", text: "At least two attorneys at the firm have at least ten years of legal experience" },
      { letter: "C", text: "No one with fewer than ten years of experience can become a partner at the firm" },
      { letter: "D", text: "The two newly promoted partners have more experience than other corporate law specialists" },
      { letter: "E", text: "Corporate law specialists are more likely to be promoted than other attorneys" },
    ],
    correctAnswer: "B",
    explanation: "Partners must have at least ten years of experience, and two attorneys were promoted to partner. Therefore, these two new partners must each have at least ten years of experience. This means at least two attorneys at the firm have at least ten years of experience.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-020",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Local food production should be prioritized over imported food. Locally grown produce reaches consumers within days of harvest, whereas imported produce may spend weeks in transit. The longer produce takes to reach consumers, the more nutrients it loses.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "nutrient content is the most important factor in food purchasing decisions" },
      { letter: "B", text: "imported produce has no advantages over local produce" },
      { letter: "C", text: "higher nutrient content is a reason to prefer one food source over another" },
      { letter: "D", text: "all imported produce travels the same distance" },
      { letter: "E", text: "consumers are aware of the nutrient differences between local and imported produce" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes local food should be prioritized and gives the reason that imported food loses more nutrients. This only supports the conclusion if having higher nutrients is actually a reason to prefer local food. Without this assumption, the nutrient difference would be irrelevant to the conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-021",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Most people who regularly exercise report high levels of life satisfaction. Therefore, if the government wants to increase citizens' life satisfaction, it should require all citizens to exercise at least three times per week.`,
    questionStem: "The argument's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "proposes a solution that would be impossible to implement" },
      { letter: "B", text: "assumes that the government has an obligation to increase citizens' life satisfaction" },
      { letter: "C", text: "overlooks the possibility that life satisfaction causes people to exercise rather than the reverse" },
      { letter: "D", text: "fails to consider that some forms of exercise are more beneficial than others" },
      { letter: "E", text: "generalizes from a specific group to the entire population without justification" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes exercise causes life satisfaction. However, the causal relationship could be reversed: satisfied people might have more energy and motivation to exercise. If satisfaction causes exercise rather than the reverse, mandating exercise would not increase satisfaction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-022",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `The ancient Mayans developed a complex calendar system that accurately predicted astronomical events. Some historians argue that this demonstrates the Mayans had contact with more technologically advanced civilizations. However, other historians maintain that the Mayans independently developed their astronomical knowledge through centuries of careful observation.`,
    questionStem: "Which one of the following, if true, most supports the view that the Mayans developed their knowledge independently?",
    answerChoices: [
      { letter: "A", text: "The Mayan calendar differs significantly from calendars used by other ancient civilizations" },
      { letter: "B", text: "Archaeological evidence shows the Mayans had sophisticated writing systems" },
      { letter: "C", text: "Other ancient civilizations also developed accurate calendars" },
      { letter: "D", text: "The Mayans made errors in their calendar that more advanced civilizations would not have made" },
      { letter: "E", text: "The Mayan civilization existed for several thousand years" },
    ],
    correctAnswer: "A",
    explanation: "If the Mayan calendar is significantly different from other calendars, this suggests it was developed independently. If they had received knowledge from another civilization, their calendar would likely resemble that civilization's calendar system. The unique design supports independent development.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A school district implemented a new reading program and saw test scores increase by 15% over two years. The superintendent concluded that the new program is highly effective and should be expanded to all schools in the district.`,
    questionStem: "Which one of the following, if true, most weakens the superintendent's conclusion?",
    answerChoices: [
      { letter: "A", text: "The teachers implementing the program received additional training" },
      { letter: "B", text: "Neighboring districts that did not implement the program saw similar increases in test scores" },
      { letter: "C", text: "Some parents initially opposed the new program" },
      { letter: "D", text: "The new program is more expensive than the previous one" },
      { letter: "E", text: "Test scores in mathematics remained unchanged during this period" },
    ],
    correctAnswer: "B",
    explanation: "If neighboring districts saw similar improvements without the new program, then something other than the program is likely causing the improvement (perhaps a state initiative, demographic changes, or test modifications). This alternative explanation undermines the claim that the reading program caused the improvement.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-024",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Some philosophers argue that moral truth is objective and universal. But different cultures have radically different moral codes. What is considered moral in one society may be considered deeply immoral in another. This proves that there are no objective moral truths.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that philosophers are not qualified to determine moral truths" },
      { letter: "B", text: "confuses the existence of disagreement about moral truth with the non-existence of moral truth" },
      { letter: "C", text: "fails to provide specific examples of cultural moral differences" },
      { letter: "D", text: "ignores that some moral beliefs are shared across all cultures" },
      { letter: "E", text: "does not define what constitutes a moral code" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that because cultures disagree about morality, there is no objective moral truth. This is fallacious reasoning. People can disagree about objective facts without those facts ceasing to be true. Disagreement about the earth's shape doesn't prove it has no shape. Similarly, moral disagreement doesn't disprove objective moral truth.",
    difficulty: "hard",
  },
  {
    id: "lr-bank45-025",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Many believe that ancient Roman architecture surpasses modern construction in durability. Indeed, some Roman structures have stood for two millennia while many modern buildings deteriorate within decades. However, we must consider survivorship bias: we see only the Roman buildings that survived, not the many that collapsed. The sturdiest modern buildings, too, may last for centuries.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Roman architecture is not as superior to modern construction as many believe" },
      { letter: "B", text: "Survivorship bias affects our perception of Roman architecture" },
      { letter: "C", text: "Many Roman buildings have collapsed over time" },
      { letter: "D", text: "The sturdiest modern buildings may last for centuries" },
      { letter: "E", text: "Ancient Roman structures have stood for two millennia" },
    ],
    correctAnswer: "A",
    explanation: "The argument aims to counter the belief that Roman architecture is superior. It uses survivorship bias as a reason: we only see Rome's best buildings, not its failures. The statement about modern buildings lasting could also be true. The main point is that the common belief about Roman superiority is flawed.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-026",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Employees who work from home are more productive than those who work in offices. A study tracked workers' output and found that remote workers completed 20% more tasks per day. Companies should therefore allow all employees to work from home to maximize productivity.`,
    questionStem: "Which one of the following is an assumption on which the argument depends?",
    answerChoices: [
      { letter: "A", text: "The number of tasks completed is an accurate measure of productivity" },
      { letter: "B", text: "All employees would prefer to work from home" },
      { letter: "C", text: "The employees in the study were chosen randomly" },
      { letter: "D", text: "Office work is becoming obsolete in modern businesses" },
      { letter: "E", text: "Companies are primarily concerned with maximizing productivity" },
    ],
    correctAnswer: "A",
    explanation: "The argument uses task completion as evidence of productivity to support allowing remote work. This assumes that completing more tasks actually means being more productive. If tasks vary greatly in importance or difficulty, completing more tasks might not reflect higher true productivity.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-027",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Every museum in this city charges an entrance fee. The art gallery on Main Street does not charge an entrance fee. Therefore, the art gallery on Main Street is not a museum.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All licensed drivers have passed a driving test. Sarah has passed a driving test. Therefore, Sarah is a licensed driver." },
      { letter: "B", text: "Most novels have more than 200 pages. This book has exactly 200 pages. Therefore, this book is probably not a novel." },
      { letter: "C", text: "Every certified accountant has a college degree. Robert does not have a college degree. Therefore, Robert is not a certified accountant." },
      { letter: "D", text: "Some restaurants serve breakfast. This establishment serves breakfast. Therefore, this establishment might be a restaurant." },
      { letter: "E", text: "No hospital allows smoking. This building allows smoking. Therefore, this building might not be a hospital." },
    ],
    correctAnswer: "C",
    explanation: "The original argument: All X have property Y; This thing lacks property Y; Therefore, this thing is not X. Choice C follows the same pattern: All certified accountants have degrees; Robert lacks a degree; Therefore, Robert is not a certified accountant. Both use modus tollens with a universal statement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-028",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A wildlife biologist claims that the recent decline in salmon populations is caused by increased predation from sea lions, whose numbers have grown substantially. The biologist recommends reducing the sea lion population to help salmon recover.`,
    questionStem: "Which one of the following, if true, most strengthens the biologist's reasoning?",
    answerChoices: [
      { letter: "A", text: "Sea lion populations have been protected by law for several decades" },
      { letter: "B", text: "Salmon populations began declining at the same time sea lion populations began increasing" },
      { letter: "C", text: "In areas where sea lions are absent, salmon populations have remained stable" },
      { letter: "D", text: "Sea lions consume large quantities of fish each day" },
      { letter: "E", text: "Other predators of salmon, such as bears, have also increased in number" },
    ],
    correctAnswer: "C",
    explanation: "If salmon populations are stable where there are no sea lions, this supports the claim that sea lions are causing the decline. This provides a natural control group showing that without the proposed cause (sea lions), the effect (salmon decline) does not occur.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-029",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Studies show that employees who receive praise from managers are more engaged and productive than those who do not. A business consultant concludes that companies should train managers to praise employees more frequently, as this will boost productivity across the organization.`,
    questionStem: "Which one of the following, if true, most weakens the consultant's conclusion?",
    answerChoices: [
      { letter: "A", text: "Some employees value financial bonuses more than verbal praise" },
      { letter: "B", text: "Managers naturally tend to praise employees who are already highly productive" },
      { letter: "C", text: "Training managers to give praise effectively requires significant time and resources" },
      { letter: "D", text: "Employee engagement has been declining across many industries" },
      { letter: "E", text: "Praise from peers can be as effective as praise from managers" },
    ],
    correctAnswer: "B",
    explanation: "If managers naturally praise productive employees, the correlation between praise and productivity could be reversed: productivity leads to praise, not praise to productivity. Training managers to praise more wouldn't then increase productivity, since productive employees are already being praised.",
    difficulty: "hard",
  },
  {
    id: "lr-bank45-030",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The town council has proposed building a new community center. Councilwoman Torres opposes this proposal. But Councilwoman Torres owns property near the proposed site and opposes any development that might increase traffic in that area. So we should dismiss her objections to the community center.`,
    questionStem: "The reasoning in the argument is most vulnerable to which of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It provides no evidence that increased traffic is actually harmful" },
      { letter: "B", text: "It ignores the possibility that the community center would benefit residents" },
      { letter: "C", text: "It rejects a position based on the motives of a person who holds it rather than on its merits" },
      { letter: "D", text: "It assumes that all development necessarily increases traffic" },
      { letter: "E", text: "It fails to consider that Torres might have valid reasons for opposing the center" },
    ],
    correctAnswer: "C",
    explanation: "This is a circumstantial ad hominem fallacy. The argument dismisses Torres's objections because of her potential self-interest, without addressing whether her objections might still be valid. Even if she has selfish motives, the community center proposal could still be flawed.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-031",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Some argue that raising taxes on corporations will cause them to relocate to lower-tax countries. But consider that corporate taxes in our country were significantly higher in the 1960s than they are today, yet corporations remained and thrived. Historical evidence does not support the prediction that corporations will flee higher taxes.`,
    questionStem: "The economist's argument employs which one of the following argumentative strategies?",
    answerChoices: [
      { letter: "A", text: "Appealing to the authority of historical precedent" },
      { letter: "B", text: "Using a historical counterexample to challenge a predictive claim" },
      { letter: "C", text: "Arguing that what applied in the past must apply in the future" },
      { letter: "D", text: "Demonstrating that the opposing argument is logically inconsistent" },
      { letter: "E", text: "Questioning the qualifications of those who predict corporate relocation" },
    ],
    correctAnswer: "B",
    explanation: "The economist counters the prediction that corporations will relocate if taxes increase by pointing to the 1960s when taxes were higher yet corporations stayed. This historical example serves as a counterexample to challenge the predictive claim, not as an appeal to authority.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The university should eliminate its philosophy department. Philosophy courses teach students to think critically and analyze arguments, but these skills can be acquired in other departments. Furthermore, philosophy majors have lower starting salaries than graduates from other programs. Eliminating the department would allow resources to be directed to more practical programs.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Starting salary is an appropriate measure of a program's value" },
      { letter: "B", text: "Philosophy courses are not popular with students" },
      { letter: "C", text: "Critical thinking is the only benefit of studying philosophy" },
      { letter: "D", text: "Other departments can teach critical thinking as effectively as philosophy" },
      { letter: "E", text: "Universities should prioritize practical programs over theoretical ones" },
    ],
    correctAnswer: "D",
    explanation: "The argument dismisses the value of philosophy courses by claiming critical thinking can be acquired elsewhere. This only works if those other departments teach critical thinking as effectively as philosophy does. If philosophy teaches it better, there would still be reason to keep the department.",
    difficulty: "hard",
  },
  {
    id: "lr-bank45-033",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Marcus: Zoos are essential for conservation. Many endangered species would have gone extinct without captive breeding programs. The educational value of zoos also inspires the next generation of conservationists.

    Lydia: But zoos often prioritize popular animals over truly endangered ones. Most zoo animals cannot be released into the wild, and the resources spent on zoos could fund habitat preservation, which helps far more species.`,
    questionStem: "Marcus and Lydia disagree over",
    answerChoices: [
      { letter: "A", text: "whether any zoo animals are ever released into the wild" },
      { letter: "B", text: "whether zoos have educational value" },
      { letter: "C", text: "whether zoos are an effective use of conservation resources" },
      { letter: "D", text: "whether captive breeding programs have saved any species" },
      { letter: "E", text: "whether habitat preservation should receive more funding" },
    ],
    correctAnswer: "C",
    explanation: "Marcus argues zoos are essential for conservation, implying they are a good use of resources. Lydia counters that zoo resources could better be spent on habitat preservation. Their core disagreement is about whether zoos effectively use conservation resources compared to alternatives.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-034",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers found that people who drink coffee daily have a lower risk of developing type 2 diabetes than those who never drink coffee. They hypothesize that compounds in coffee improve insulin sensitivity, thereby reducing diabetes risk.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Tea drinkers show no reduced risk of type 2 diabetes" },
      { letter: "B", text: "Decaffeinated coffee drinkers show the same reduced risk as regular coffee drinkers" },
      { letter: "C", text: "Coffee drinkers tend to have healthier diets overall" },
      { letter: "D", text: "Type 2 diabetes rates have declined as coffee consumption has increased" },
      { letter: "E", text: "Some coffee compounds have been shown to affect insulin function in laboratory studies" },
    ],
    correctAnswer: "E",
    explanation: "The hypothesis is that coffee compounds improve insulin sensitivity. If laboratory studies show coffee compounds actually affect insulin function, this provides direct evidence for the proposed mechanism. This strengthens the causal claim that coffee compounds are responsible for the reduced diabetes risk.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-035",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The proposed law would require all new buildings to meet strict energy efficiency standards. Opponents claim these standards would significantly increase construction costs. However, a recent survey found that most citizens support energy-efficient building requirements. Therefore, the concerns about increased costs are unfounded.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on a survey without disclosing its methodology" },
      { letter: "B", text: "assumes that popular support for a policy proves claims about its costs are false" },
      { letter: "C", text: "fails to consider that energy efficiency has long-term cost benefits" },
      { letter: "D", text: "does not specify what counts as strict energy efficiency standards" },
      { letter: "E", text: "ignores that some citizens may support energy efficiency despite the costs" },
    ],
    correctAnswer: "B",
    explanation: "Public support for a policy has no bearing on whether claims about its costs are accurate. The argument commits a non sequitur: the fact that people want something doesn't mean concerns about its costs are wrong. The costs could be high even if the policy is popular.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-036",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A nutritionist argues that organic foods are healthier than conventionally grown foods. She points to a study showing that organic produce contains higher levels of certain antioxidants than conventional produce.`,
    questionStem: "Which one of the following, if true, most weakens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Organic foods are typically more expensive than conventional foods" },
      { letter: "B", text: "The antioxidant differences are too small to have any measurable health impact" },
      { letter: "C", text: "Some consumers prefer the taste of conventional produce" },
      { letter: "D", text: "Organic farming practices are better for the environment" },
      { letter: "E", text: "The study was funded by an organic food producers' association" },
    ],
    correctAnswer: "B",
    explanation: "The nutritionist claims organic foods are healthier based on higher antioxidant levels. If those differences are too small to have any measurable health impact, then the higher antioxidant levels don't actually make organic foods healthier. This directly undermines the argument's reasoning.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-037",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Art critics often dismiss popular art as lacking aesthetic value. But the very fact that popular art resonates with millions of people demonstrates that it has significant aesthetic appeal. Therefore, art critics are wrong to dismiss popular art.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Art critics have no special expertise in evaluating aesthetic value" },
      { letter: "B", text: "All art that has aesthetic appeal also has aesthetic value" },
      { letter: "C", text: "Popular art is created with the intention of having aesthetic value" },
      { letter: "D", text: "The number of people who appreciate art is relevant to its aesthetic merit" },
      { letter: "E", text: "Art critics and the general public use the same standards to evaluate art" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'popular art has aesthetic appeal' to 'critics are wrong to say it lacks aesthetic value.' This requires assuming that aesthetic appeal implies aesthetic value. Without this assumption, art could appeal to many people without having the kind of aesthetic value critics are evaluating.",
    difficulty: "hard",
  },
  {
    id: "lr-bank45-038",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The defendant could not have committed the robbery because she claims she was at a movie theater at the time. When asked which movie she saw, she provided a detailed plot summary. Only someone who actually saw the movie could provide such detailed information.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes the defendant had no motive to commit the crime" },
      { letter: "B", text: "fails to consider that the defendant might have learned the plot without attending the movie" },
      { letter: "C", text: "relies on the defendant's self-interested testimony" },
      { letter: "D", text: "does not establish when the movie was playing at the theater" },
      { letter: "E", text: "assumes all theaters show movies at the same times" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes knowing the plot proves theater attendance. However, the defendant could have learned the plot in many ways: reading reviews, talking to friends, watching trailers, or even seeing the movie on a different day. Detailed plot knowledge doesn't prove she was at the theater at the time of the robbery.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-039",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some psychologists claim that violent video games increase aggressive behavior in children. However, the research on this topic is mixed, with some studies finding no effect. Furthermore, millions of children play violent video games without becoming violent. It is irresponsible to blame video games for complex social problems that have multiple causes.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Violent video games do not cause aggressive behavior" },
      { letter: "B", text: "Research on violent video games and aggression is inconclusive" },
      { letter: "C", text: "It is irresponsible to blame video games for complex social problems" },
      { letter: "D", text: "Millions of children play violent video games without becoming violent" },
      { letter: "E", text: "Complex social problems have multiple causes" },
    ],
    correctAnswer: "C",
    explanation: "The argument presents evidence (mixed research, many non-violent gamers) to support the evaluative claim that 'it is irresponsible to blame video games for complex social problems.' This normative judgment about the blame being irresponsible is the main point the argument is making.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-040",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historians have long debated why the Roman Empire fell. A new theory proposes that climate change was a significant factor. Tree ring data shows that Europe experienced severe droughts during the period of Rome's decline, which would have reduced agricultural productivity and weakened the empire's economic base.`,
    questionStem: "Which one of the following, if true, most strengthens the new theory?",
    answerChoices: [
      { letter: "A", text: "The Roman Empire faced numerous military threats during its decline" },
      { letter: "B", text: "Other ancient empires also declined during periods of climate stress" },
      { letter: "C", text: "Roman historical records describe food shortages and famines during this period" },
      { letter: "D", text: "Modern civilizations are also vulnerable to climate change effects" },
      { letter: "E", text: "Tree ring data is a reliable indicator of historical climate conditions" },
    ],
    correctAnswer: "C",
    explanation: "The theory connects climate change to agricultural problems to economic weakness to Rome's fall. If Roman records describe food shortages and famines during this period, this confirms that the proposed mechanism (drought reducing food production) actually occurred, strengthening the causal chain.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Parent: My teenager argues that she should be allowed to stay out until midnight because all her friends do. But I've spoken with other parents, and many of them actually require their children to be home by 10 PM. My teenager is simply mistaken about what her friends are permitted to do.`,
    questionStem: "The parent responds to the teenager's argument by",
    answerChoices: [
      { letter: "A", text: "proposing a compromise between the competing positions" },
      { letter: "B", text: "questioning the factual premise on which the teenager's argument relies" },
      { letter: "C", text: "arguing that the teenager's request is inherently unreasonable" },
      { letter: "D", text: "suggesting that the teenager is intentionally being deceptive" },
      { letter: "E", text: "pointing out that popularity is not a valid basis for making decisions" },
    ],
    correctAnswer: "B",
    explanation: "The teenager's argument rests on the claim that all friends stay out until midnight. The parent challenges this factual premise by providing evidence (conversations with other parents) that many friends actually have earlier curfews. By undermining this premise, the parent weakens the entire argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-042",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A study found that people who own dogs have lower rates of heart disease than non-dog owners. Cardiologists theorize that dog ownership reduces heart disease risk because walking a dog provides regular cardiovascular exercise.`,
    questionStem: "Which one of the following, if true, most weakens the cardiologists' explanation?",
    answerChoices: [
      { letter: "A", text: "Dog owners who hire dog walkers show the same reduced risk as those who walk their dogs themselves" },
      { letter: "B", text: "Some dog owners rarely walk their dogs" },
      { letter: "C", text: "Regular exercise is known to reduce heart disease risk" },
      { letter: "D", text: "Cat owners do not show reduced rates of heart disease" },
      { letter: "E", text: "The study did not control for diet and other lifestyle factors" },
    ],
    correctAnswer: "A",
    explanation: "If dog owners who hire walkers (and thus don't get the exercise) have the same reduced risk as those who walk dogs themselves, then walking is not the explanation for the health benefit. This suggests something else about dog ownership, not the exercise, is responsible.",
    difficulty: "hard",
  },
  {
    id: "lr-bank45-043",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Politicians should be prohibited from accepting campaign contributions from corporations. When corporations fund campaigns, politicians feel obligated to support legislation favorable to those corporations. This creates an inherent conflict between politicians' duty to voters and their obligations to donors.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Politicians are always influenced by their donors" },
      { letter: "B", text: "Legislation favorable to corporations is always harmful to voters" },
      { letter: "C", text: "A politician's duty to voters should take precedence over obligations to donors" },
      { letter: "D", text: "Corporations always seek legislation that benefits only themselves" },
      { letter: "E", text: "All campaign contributions create conflicts of interest" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes corporate contributions should be prohibited because they create a conflict between duty to voters and obligations to donors. This conclusion only follows if the duty to voters should take precedence. Otherwise, the conflict would not be problematic enough to justify a prohibition.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-044",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Of the 100 patients who tried the new experimental treatment, 60 showed improvement. Of the 100 patients who received the standard treatment, 55 showed improvement. Therefore, the experimental treatment is more effective than the standard treatment.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to define what constitutes improvement" },
      { letter: "B", text: "does not consider whether the difference in outcomes is statistically significant" },
      { letter: "C", text: "assumes both groups of patients had similar conditions" },
      { letter: "D", text: "ignores the possibility that some patients received both treatments" },
      { letter: "E", text: "relies on a sample size that is too small to draw conclusions" },
    ],
    correctAnswer: "B",
    explanation: "A difference of 60% vs 55% might not be statistically significant with 100 patients in each group. Without statistical analysis, the 5% difference could easily be due to chance variation rather than a real difference in treatment effectiveness. The argument treats this difference as meaningful without justification.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-045",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some effective medicines have unpleasant side effects. This medication has unpleasant side effects. Therefore, this medication might be effective.`,
    questionStem: "The flawed pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some talented musicians practice daily. Elena practices daily. Therefore, Elena might be talented." },
      { letter: "B", text: "All swans in this pond are white. This bird is white. Therefore, this bird is a swan in this pond." },
      { letter: "C", text: "No reptiles are warm-blooded. This animal is warm-blooded. Therefore, this animal is not a reptile." },
      { letter: "D", text: "Most doctors recommend exercise. Dr. Smith recommends exercise. Therefore, Dr. Smith is like most doctors." },
      { letter: "E", text: "All prime numbers greater than 2 are odd. 7 is odd. Therefore, 7 is prime." },
    ],
    correctAnswer: "A",
    explanation: "The original argument: Some A are B; This is B; Therefore, this might be A. This incorrectly infers that having property B makes something likely to be A, when B is shared by many things that are not A. Choice A follows the same pattern: Some talented musicians practice; Elena practices; Elena might be talented. Both commit the fallacy of affirming the consequent with a 'some' premise.",
    difficulty: "hard",
  },
  {
    id: "lr-bank45-046",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: Genetically modified crops are safe for human consumption. Decades of research have found no credible evidence of health risks, and regulatory agencies worldwide have approved them.

    Activist: But absence of evidence is not evidence of absence. GMO crops have only been widely consumed for a few decades, not long enough to detect potential long-term health effects. We should apply the precautionary principle.`,
    questionStem: "The scientist and activist disagree about",
    answerChoices: [
      { letter: "A", text: "whether regulatory agencies have approved genetically modified crops" },
      { letter: "B", text: "whether decades of research have been conducted on GMO safety" },
      { letter: "C", text: "whether the current evidence is sufficient to conclude GMO crops are safe" },
      { letter: "D", text: "whether the precautionary principle should ever be applied to new technologies" },
      { letter: "E", text: "whether absence of evidence can ever be meaningful" },
    ],
    correctAnswer: "C",
    explanation: "The scientist argues current evidence shows GMOs are safe. The activist argues current evidence is insufficient because long-term effects cannot yet be known. They both acknowledge research has been done; they disagree about whether that research is sufficient to conclude safety.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-047",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `In a certain company, all managers have completed the leadership training program. Some employees who have completed the leadership training program have not been promoted. Only promoted employees are eligible for the executive bonus.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Some managers are not eligible for the executive bonus" },
      { letter: "B", text: "Some employees who completed leadership training are not eligible for the executive bonus" },
      { letter: "C", text: "All employees who are eligible for the executive bonus are managers" },
      { letter: "D", text: "Some managers have not been promoted" },
      { letter: "E", text: "All promoted employees have completed the leadership training program" },
    ],
    correctAnswer: "B",
    explanation: "Some employees who completed leadership training have not been promoted. Only promoted employees are eligible for the executive bonus. Therefore, those unpromoted employees (who completed training) are not eligible for the bonus. Thus, some training completers are not bonus-eligible.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-048",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Insurance companies charge higher premiums to young drivers because they have more accidents per mile driven than older drivers. An analyst argues that this practice is unfair because the higher accident rate is caused by inexperience, not youth. A 30-year-old new driver would pose the same risk as an 18-year-old new driver.`,
    questionStem: "Which one of the following, if true, most strengthens the analyst's argument?",
    answerChoices: [
      { letter: "A", text: "Insurance premiums vary significantly between different insurance companies" },
      { letter: "B", text: "Studies show that drivers who began driving at age 30 have accident rates similar to those who began at 18" },
      { letter: "C", text: "Young drivers are more likely to engage in risky driving behaviors" },
      { letter: "D", text: "Most 30-year-olds have been driving for over a decade" },
      { letter: "E", text: "Some young drivers have very low accident rates" },
    ],
    correctAnswer: "B",
    explanation: "The analyst claims inexperience, not age, causes higher accident rates. If new drivers at age 30 have accident rates similar to new drivers at 18, this supports the claim that inexperience is the causal factor, not youth itself. This directly confirms the analyst's hypothesis.",
    difficulty: "medium",
  },
  {
    id: "lr-bank45-049",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Archaeological evidence shows that ancient Egyptians used a complex system of ramps to build the pyramids. Some engineers argue that this ramp theory is incorrect because the ramps would have required almost as much stone as the pyramids themselves, which seems implausibly labor-intensive.`,
    questionStem: "Which one of the following, if true, most weakens the engineers' objection?",
    answerChoices: [
      { letter: "A", text: "Ancient Egyptians were capable of remarkable engineering feats" },
      { letter: "B", text: "The ramps were likely made of mud brick and rubble, not quarried stone" },
      { letter: "C", text: "Building the pyramids required decades of labor from thousands of workers" },
      { letter: "D", text: "Some pyramids show no archaeological evidence of ramps" },
      { letter: "E", text: "Alternative theories about pyramid construction also have significant problems" },
    ],
    correctAnswer: "B",
    explanation: "The engineers object that ramps would require nearly as much stone as the pyramids. If the ramps were made of mud brick and rubble instead of quarried stone, they would be much less labor-intensive to construct, eliminating the engineers' objection about impractical labor requirements.",
    difficulty: "easy",
  },
  {
    id: "lr-bank45-050",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Studies show that people who read fiction develop greater empathy than those who do not. Fiction readers must imagine the perspectives of diverse characters, which exercises their ability to understand others' mental states. Schools should therefore incorporate more fiction reading into their curricula, since developing empathy is essential for creating responsible citizens.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Fiction reading develops greater empathy" },
      { letter: "B", text: "Imagining characters' perspectives exercises empathy skills" },
      { letter: "C", text: "Schools should incorporate more fiction reading into their curricula" },
      { letter: "D", text: "Developing empathy is essential for creating responsible citizens" },
      { letter: "E", text: "People who read fiction understand others' mental states better" },
    ],
    correctAnswer: "C",
    explanation: "The argument provides supporting evidence (fiction develops empathy, empathy is essential for citizenship) to reach the conclusion signaled by 'therefore': schools should incorporate more fiction reading. The other statements are premises supporting this recommendation.",
    difficulty: "easy",
  },
];
