// Logical Reasoning Questions Bank - Set 60
import { Question } from "../lsat-types";

export const lrQuestionsSet60: Question[] = [
  {
    id: "lr-bank60-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during the workday are more productive than those who work continuously. Therefore, employers should require all employees to take breaks at specified times throughout the day, as this will maximize workplace productivity.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that what is true for some employees is true for all employees" },
      { letter: "B", text: "fails to consider that mandatory breaks might not have the same effect as voluntary breaks" },
      { letter: "C", text: "ignores the possibility that the study's sample size was too small" },
      { letter: "D", text: "confuses correlation with causation in interpreting the study results" },
      { letter: "E", text: "presumes that productivity is the only factor employers should consider" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that requiring breaks will have the same positive effect as taking breaks voluntarily. The study found that employees who take regular breaks are more productive, but this does not mean that forcing employees to take breaks at specified times will produce the same result. The voluntary nature of the breaks in the study may be crucial to their effectiveness.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Critics of the new environmental regulations argue that they will harm the economy. However, the CEO of GreenTech Industries, a company that manufactures solar panels, has stated that the regulations will actually boost economic growth. Since the CEO is a successful business leader, we should trust this assessment over the critics' claims.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on the testimony of someone who has a vested interest in the outcome" },
      { letter: "B", text: "assumes that economic growth is more important than environmental protection" },
      { letter: "C", text: "fails to define what constitutes harm to the economy" },
      { letter: "D", text: "generalizes from a single company's experience to the entire economy" },
      { letter: "E", text: "ignores the possibility that both the CEO and the critics could be partially correct" },
    ],
    correctAnswer: "A",
    explanation: "The CEO of a solar panel company has a direct financial interest in environmental regulations that would likely increase demand for solar panels. This conflict of interest undermines the reliability of the CEO's assessment, yet the argument treats it as authoritative simply because the CEO is a successful business leader.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-003",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying ancient cave paintings in southern France have determined that the paintings were created approximately 30,000 years ago. The researchers conclude that these early humans must have had sophisticated cognitive abilities and symbolic thinking, since creating such artwork requires the ability to represent abstract concepts visually.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "The cave paintings depict animals that no longer exist in the region" },
      { letter: "B", text: "Similar paintings have been found in caves throughout Europe" },
      { letter: "C", text: "The paintings include geometric symbols that appear to represent counting or record-keeping" },
      { letter: "D", text: "The pigments used in the paintings were made from minerals found miles away from the caves" },
      { letter: "E", text: "Modern humans find the cave paintings aesthetically pleasing" },
    ],
    correctAnswer: "C",
    explanation: "The presence of geometric symbols representing counting or record-keeping would provide additional evidence of sophisticated cognitive abilities and symbolic thinking beyond just artistic representation. This directly supports the conclusion that these early humans had advanced mental capabilities.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-004",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council has proposed building a new sports stadium downtown, arguing that it will revitalize the area by attracting visitors who will spend money at local businesses. The council points to the success of a similar stadium project in another city, where downtown businesses reported increased revenue after the stadium opened.`,
    questionStem: "Which one of the following, if true, most weakens the city council's argument?",
    answerChoices: [
      { letter: "A", text: "The proposed stadium would be smaller than the one in the other city" },
      { letter: "B", text: "Many residents oppose using public funds for the stadium project" },
      { letter: "C", text: "The other city's downtown area had few existing businesses before the stadium was built" },
      { letter: "D", text: "Sports stadiums typically host events only on weekends and evenings" },
      { letter: "E", text: "The increased revenue in the other city was offset by increased traffic congestion" },
    ],
    correctAnswer: "C",
    explanation: "If the other city's downtown had few existing businesses before the stadium was built, then any increase would be notable. However, this situation differs significantly from a downtown area that already has established businesses. The comparison becomes less relevant, weakening the argument that the same success would occur in the proposed location.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-005",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All successful entrepreneurs share certain personality traits, including high tolerance for risk and strong self-motivation. Since Jennifer exhibits both of these traits, she will likely be a successful entrepreneur if she starts her own business.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Jennifer has the financial resources necessary to start a business" },
      { letter: "B", text: "Having the traits shared by successful entrepreneurs is sufficient for entrepreneurial success" },
      { letter: "C", text: "Risk tolerance and self-motivation are the only traits needed for business success" },
      { letter: "D", text: "Jennifer has experience in the business world" },
      { letter: "E", text: "Most people who start businesses fail within the first year" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'all successful entrepreneurs have these traits' to 'Jennifer has these traits, so she will be successful.' This assumes that having these traits is sufficient for success, not merely necessary. The argument conflates necessary conditions with sufficient conditions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-006",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical research has shown that regular exercise reduces the risk of heart disease. However, many people claim they do not have time to exercise. This excuse is unconvincing because most people spend several hours each day watching television or browsing social media. Clearly, it is a matter of priorities rather than available time, and those who value their health should reallocate some of their leisure time to physical activity.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Regular exercise reduces the risk of heart disease" },
      { letter: "B", text: "Most people spend several hours each day on leisure activities" },
      { letter: "C", text: "The claim that people lack time for exercise is not persuasive" },
      { letter: "D", text: "People who value their health should exercise more and watch less television" },
      { letter: "E", text: "Exercise is more important than entertainment for maintaining good health" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is that the excuse of not having time to exercise is unconvincing. The argument supports this by pointing out that people have time for leisure activities, suggesting it is about priorities rather than time. The final sentence about reallocating time is a recommendation that follows from the main conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-007",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Politician: My opponent argues that we should reduce military spending and redirect those funds to education. But my opponent never served in the military and has no understanding of the threats our country faces. Furthermore, my opponent's own children attend private schools, so the public education system is clearly not a personal priority. We should therefore reject my opponent's proposal.`,
    questionStem: "The politician's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "presenting evidence that directly contradicts the opponent's claims" },
      { letter: "B", text: "attacking the opponent's character and circumstances rather than addressing the proposal's merits" },
      { letter: "C", text: "demonstrating that the opponent's proposal would have negative consequences" },
      { letter: "D", text: "showing that the opponent's reasoning contains a logical inconsistency" },
      { letter: "E", text: "arguing that the opponent lacks the expertise to make policy recommendations" },
    ],
    correctAnswer: "B",
    explanation: "The politician engages in ad hominem attacks by focusing on the opponent's lack of military service and personal choice of schools rather than addressing whether the proposal to redirect military funds to education has merit. This is a classic example of attacking the person rather than the argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `In a survey of 500 people who regularly drink coffee, 80% reported that they feel more alert after their morning coffee. This proves that coffee consumption increases alertness and that people who want to be more alert should drink coffee.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on self-reported data rather than objective measurements" },
      { letter: "B", text: "fails to consider that the alertness might be due to relieving caffeine withdrawal symptoms" },
      { letter: "C", text: "assumes that a sample of 500 people is representative of the general population" },
      { letter: "D", text: "does not account for the placebo effect in coffee consumption" },
      { letter: "E", text: "ignores the potential negative health effects of coffee consumption" },
    ],
    correctAnswer: "B",
    explanation: "Regular coffee drinkers may experience caffeine withdrawal symptoms, including drowsiness. Their increased alertness after drinking coffee might simply be the relief of withdrawal rather than a genuine increase in alertness above normal levels. This alternative explanation undermines the conclusion that coffee increases alertness.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-009",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Paleontologists have discovered fossils of a new species of dinosaur in an area that is now desert. Based on the plant fossils found alongside the dinosaur remains, scientists conclude that this species lived in a lush, tropical environment and that the region's climate has changed dramatically over millions of years.`,
    questionStem: "Which one of the following, if true, most strengthens the scientists' conclusion?",
    answerChoices: [
      { letter: "A", text: "The dinosaur's teeth are similar to those of modern herbivores that live in tropical regions" },
      { letter: "B", text: "Other dinosaur species known to have lived in tropical environments have been found on different continents" },
      { letter: "C", text: "The rock layer containing the fossils shows evidence of ancient rivers and lakes" },
      { letter: "D", text: "The new dinosaur species is estimated to have been quite large" },
      { letter: "E", text: "Fossils from this period are rarely well-preserved in desert conditions" },
    ],
    correctAnswer: "C",
    explanation: "Evidence of ancient rivers and lakes in the rock layer directly supports the conclusion that the region was once lush and tropical rather than arid. This geological evidence corroborates the botanical evidence from plant fossils and strengthens the case for dramatic climate change.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A study found that students who participated in after-school music programs had higher grades than students who did not participate in such programs. The school board therefore concluded that expanding music programs would improve overall student academic performance.`,
    questionStem: "Which one of the following, if true, most weakens the school board's conclusion?",
    answerChoices: [
      { letter: "A", text: "Music programs require significant funding that could be used for other educational initiatives" },
      { letter: "B", text: "Students who choose to participate in after-school programs tend to be more academically motivated to begin with" },
      { letter: "C", text: "Some students in the music program had lower grades than the average non-participant" },
      { letter: "D", text: "The study was conducted at schools in wealthy neighborhoods" },
      { letter: "E", text: "Music education has been shown to improve cognitive development in young children" },
    ],
    correctAnswer: "B",
    explanation: "If students who choose music programs are already more academically motivated, then their higher grades might be due to this pre-existing motivation rather than the music program itself. This selection bias means expanding music programs might not improve grades for students who would not have voluntarily participated.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-011",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The government should not regulate the prices that pharmaceutical companies charge for their medications. After all, pharmaceutical research and development is extremely expensive, and companies need to charge high prices in order to recoup their investments and fund future research. Without the potential for high profits, companies would have no incentive to develop new life-saving drugs.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "pharmaceutical companies currently spend all of their profits on research and development" },
      { letter: "B", text: "price regulation would necessarily reduce pharmaceutical company profits below the level needed to fund research" },
      { letter: "C", text: "new drugs are always more effective than existing medications" },
      { letter: "D", text: "the government has no legitimate interest in ensuring affordable medication" },
      { letter: "E", text: "pharmaceutical research cannot be funded through alternative means such as government grants" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that price regulation would reduce profits to such an extent that research could not be funded. However, price regulation could still allow for substantial profits; it would simply limit excessive pricing. The argument assumes the worst-case scenario without justification.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-012",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Adams: Artificial intelligence will never truly replicate human consciousness because consciousness requires subjective experience, which cannot be programmed into a machine. No matter how sophisticated AI becomes, it will only simulate understanding without genuine comprehension.

Professor Baker: Your view is too narrow. Consciousness emerges from complex information processing, and there is no reason to believe that only biological brains can achieve this. As AI systems become more complex, they may develop genuine conscious experiences indistinguishable from our own.`,
    questionStem: "Professor Adams and Professor Baker disagree about whether",
    answerChoices: [
      { letter: "A", text: "current AI systems are capable of subjective experience" },
      { letter: "B", text: "consciousness can emerge from non-biological information processing systems" },
      { letter: "C", text: "AI development will continue to advance in the future" },
      { letter: "D", text: "subjective experience is a necessary component of consciousness" },
      { letter: "E", text: "human consciousness can be fully understood by science" },
    ],
    correctAnswer: "B",
    explanation: "Professor Adams argues that consciousness cannot be programmed into machines, implying that non-biological systems cannot be conscious. Professor Baker directly counters this by arguing that consciousness emerges from complex information processing and could occur in non-biological systems. This is the central point of disagreement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No experienced lawyers make procedural errors in court. Thompson made a procedural error in the case last week. Therefore, Thompson is not an experienced lawyer.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All professional athletes train daily. Martinez trains daily. Therefore, Martinez is a professional athlete." },
      { letter: "B", text: "All qualified applicants have graduate degrees. Johnson does not have a graduate degree. Therefore, Johnson is not a qualified applicant." },
      { letter: "C", text: "No reliable cars break down frequently. This car breaks down frequently. Therefore, this car is not reliable." },
      { letter: "D", text: "Some talented musicians cannot read music. Rivera cannot read music. Therefore, Rivera might be a talented musician." },
      { letter: "E", text: "Most successful businesses have good marketing. This business has good marketing. Therefore, this business will probably be successful." },
    ],
    correctAnswer: "C",
    explanation: "The original argument has the form: No A are B. X is B. Therefore, X is not A. Answer choice C follows the same pattern: No reliable cars break down frequently (No A are B). This car breaks down frequently (X is B). Therefore, this car is not reliable (X is not A).",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-014",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The company's new wellness program must be effective because employee health insurance claims have decreased by 15% since the program was implemented. The program includes fitness classes, nutrition counseling, and stress management workshops, and clearly these initiatives are responsible for the improved employee health.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "assumes that decreased insurance claims necessarily indicate improved health" },
      { letter: "B", text: "fails to consider other factors that might explain the decrease in health claims" },
      { letter: "C", text: "does not provide specific data about employee participation in the wellness program" },
      { letter: "D", text: "overlooks the possibility that some employees may have left the company" },
      { letter: "E", text: "ignores potential long-term effects of the wellness program" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the post hoc fallacy by assuming that because claims decreased after the program was implemented, the program caused the decrease. Other factors could explain the change, such as seasonal variations, changes in insurance policies, or workforce demographic shifts.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists studying an ancient civilization have found that settlements near rivers grew much larger than those in arid regions. They hypothesize that access to water allowed for agricultural surplus, which supported larger populations and more complex social structures.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologists' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Modern cities are also frequently located near bodies of water" },
      { letter: "B", text: "Grain storage facilities in river settlements were significantly larger than those in arid settlements" },
      { letter: "C", text: "The arid settlements showed evidence of trade with the river settlements" },
      { letter: "D", text: "River settlements were established earlier than arid settlements" },
      { letter: "E", text: "Some arid settlements developed sophisticated water collection systems" },
    ],
    correctAnswer: "B",
    explanation: "Larger grain storage facilities in river settlements directly support the hypothesis that these locations allowed for agricultural surplus. The ability to store more grain indicates greater agricultural production, which would support larger populations as the archaeologists propose.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-016",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Proponents of organic farming argue that organic produce is healthier than conventionally grown produce because it is not treated with synthetic pesticides. They conclude that consumers should pay the premium for organic foods to protect their health.`,
    questionStem: "Which one of the following, if true, most weakens the proponents' argument?",
    answerChoices: [
      { letter: "A", text: "Organic farming methods produce lower crop yields than conventional methods" },
      { letter: "B", text: "The pesticide residues on conventionally grown produce are typically well below levels considered harmful to health" },
      { letter: "C", text: "Organic produce is often more expensive than conventionally grown produce" },
      { letter: "D", text: "Some organic farms use natural pesticides that can also have negative health effects" },
      { letter: "E", text: "Many consumers prefer the taste of organic produce" },
    ],
    correctAnswer: "B",
    explanation: "If pesticide residues on conventional produce are below harmful levels, then avoiding these residues provides little or no health benefit. This undermines the primary reason given for paying more for organic produce, weakening the argument that consumers should pay the premium for health reasons.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-017",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Cities that have implemented congestion pricing, which charges drivers a fee to enter busy urban areas during peak hours, have seen reductions in traffic congestion. Therefore, our city should implement congestion pricing to reduce the severe traffic problems we currently face.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Congestion pricing is the only effective method for reducing urban traffic" },
      { letter: "B", text: "The revenue from congestion pricing will be used to improve public transportation" },
      { letter: "C", text: "The conditions in this city are sufficiently similar to those in cities where congestion pricing succeeded" },
      { letter: "D", text: "Drivers in this city will be willing to pay the congestion fee" },
      { letter: "E", text: "The traffic problems in this city are more severe than in other cities" },
    ],
    correctAnswer: "C",
    explanation: "The argument relies on the success of congestion pricing in other cities to support its implementation in this city. This reasoning assumes that the relevant conditions are similar enough that the same policy would produce similar results. Without this assumption, the evidence from other cities would not apply.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-018",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the research team have published at least three peer-reviewed papers. Dr. Chen has been on the research team for five years. Anyone who has published at least three peer-reviewed papers is eligible for the senior scientist position. The senior scientist position requires both eligibility and approval from the department chair.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Dr. Chen has been approved by the department chair for the senior scientist position" },
      { letter: "B", text: "Dr. Chen is eligible for the senior scientist position" },
      { letter: "C", text: "Dr. Chen has published exactly three peer-reviewed papers" },
      { letter: "D", text: "Anyone on the research team can become a senior scientist" },
      { letter: "E", text: "The department chair must be a member of the research team" },
    ],
    correctAnswer: "B",
    explanation: "From the statements: Dr. Chen is on the research team, so Dr. Chen has published at least three peer-reviewed papers. Anyone with at least three peer-reviewed papers is eligible for the senior scientist position. Therefore, Dr. Chen is eligible for the senior scientist position. We cannot conclude Dr. Chen has been approved or will get the position.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-019",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The author claims that social media has improved democratic participation by giving everyone a platform to express their views. However, research shows that social media algorithms create echo chambers where users are primarily exposed to opinions they already hold. Rather than broadening democratic discourse, social media may actually be narrowing it by reinforcing existing beliefs and reducing exposure to diverse perspectives.`,
    questionStem: "The critic responds to the author's claim by",
    answerChoices: [
      { letter: "A", text: "questioning the author's credentials to speak on the topic" },
      { letter: "B", text: "presenting evidence that the author's conclusion may be the opposite of the truth" },
      { letter: "C", text: "arguing that the author has misunderstood what democratic participation means" },
      { letter: "D", text: "demonstrating that social media has other negative effects besides those mentioned" },
      { letter: "E", text: "showing that the author's argument relies on a faulty analogy" },
    ],
    correctAnswer: "B",
    explanation: "The critic presents evidence about echo chambers and algorithm-driven content that suggests social media may be narrowing rather than broadening democratic discourse. This directly challenges the author's conclusion by suggesting the actual effect is the opposite of what the author claims.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-020",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of stealing the jewelry because she has an alibi for the time of the theft. Her mother testified that the defendant was at home watching television with her during the entire evening in question. Since the mother has no criminal record, there is no reason to doubt her testimony.`,
    questionStem: "The argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that a person with no criminal record cannot lie" },
      { letter: "B", text: "fails to consider that the mother might be mistaken about the date" },
      { letter: "C", text: "overlooks the possibility that the defendant could have left briefly without the mother noticing" },
      { letter: "D", text: "ignores the relationship between the witness and the defendant that might affect the testimony's reliability" },
      { letter: "E", text: "presumes the defendant is innocent before evaluating all the evidence" },
    ],
    correctAnswer: "D",
    explanation: "The mother has a strong personal interest in protecting her daughter, which creates a potential bias that affects the reliability of her testimony. The argument treats the testimony as reliable simply because the mother has no criminal record, ignoring this obvious conflict of interest.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-021",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The recent increase in remote work has led to a decline in commercial real estate values in major cities. As more companies allow employees to work from home permanently, demand for office space will continue to decrease. This trend will fundamentally reshape urban economies that have traditionally relied on downtown business districts.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's prediction?",
    answerChoices: [
      { letter: "A", text: "Some companies are requiring employees to return to the office at least part-time" },
      { letter: "B", text: "Major technology companies have announced plans to significantly reduce their office space in the coming years" },
      { letter: "C", text: "Residential real estate prices in suburban areas have increased recently" },
      { letter: "D", text: "Some downtown areas are converting former office buildings into residential units" },
      { letter: "E", text: "Public transportation ridership has declined in major cities" },
    ],
    correctAnswer: "B",
    explanation: "Announcements by major technology companies to reduce office space provide concrete evidence that the trend toward remote work will continue and that demand for office space will decrease. This directly supports the economist's prediction about the reshaping of urban economies.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A new study has found that children who play video games for more than two hours a day have lower academic achievement than children who play less or not at all. Researchers conclude that parents should strictly limit their children's video game time to improve academic performance.`,
    questionStem: "Which one of the following, if true, most weakens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Some video games are designed to be educational" },
      { letter: "B", text: "Children with learning difficulties may be more likely to spend time playing video games as an escape from academic frustration" },
      { letter: "C", text: "The study did not include children under the age of eight" },
      { letter: "D", text: "Parents who limit video game time may be more involved in their children's education overall" },
      { letter: "E", text: "Video game playing can improve hand-eye coordination" },
    ],
    correctAnswer: "B",
    explanation: "If children with learning difficulties use video games as an escape from academic frustration, then the lower academic achievement may be the cause of increased video game playing rather than its result. This reverses the causal relationship and suggests limiting video games would not address the underlying problem.",
    difficulty: "hard",
  },
  {
    id: "lr-bank60-023",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city council should not approve the new shopping mall development. Large retail developments draw customers away from small local businesses, and we have an obligation to protect the unique character of our downtown shopping district, which depends on these small businesses.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "The shopping mall would be located near the downtown shopping district" },
      { letter: "B", text: "Small businesses cannot compete with large retail stores on price" },
      { letter: "C", text: "The unique character of the downtown is worth protecting even at some economic cost" },
      { letter: "D", text: "The shopping mall would not create any new jobs in the city" },
      { letter: "E", text: "All members of the city council agree about the importance of small businesses" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that the mall should not be approved in order to protect downtown's unique character. This implicitly assumes that preserving this character is valuable enough to justify rejecting the development, even though the mall might bring economic benefits to the city.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-024",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Although genetic testing can reveal predispositions to certain diseases, it cannot predict with certainty whether a person will develop those diseases. Environmental factors, lifestyle choices, and random genetic mutations all play significant roles in disease development. Furthermore, the psychological burden of knowing one's genetic risks may cause unnecessary anxiety. For these reasons, genetic testing should only be recommended when the results can inform specific preventive measures or treatment decisions.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Genetic testing cannot predict disease development with certainty" },
      { letter: "B", text: "Environmental factors are as important as genetics in disease development" },
      { letter: "C", text: "Knowing one's genetic risks can cause psychological harm" },
      { letter: "D", text: "Genetic testing should be recommended only in specific circumstances" },
      { letter: "E", text: "Lifestyle choices significantly influence whether genetic predispositions become actual diseases" },
    ],
    correctAnswer: "D",
    explanation: "The final sentence presents the main conclusion: genetic testing should only be recommended when results can guide prevention or treatment. The preceding sentences about uncertainty, environmental factors, and psychological burden are supporting reasons for this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-025",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Martinez: Animal testing is necessary for medical research because there is no other way to study how potential treatments affect living organisms. Computer models cannot replicate the complexity of biological systems, and human trials cannot be conducted until preliminary safety data is established.

Dr. Williams: The necessity argument for animal testing is overstated. Advances in organ-on-chip technology and sophisticated computer simulations are increasingly providing alternatives that can predict human responses more accurately than animal models, which often fail to translate to human outcomes anyway.`,
    questionStem: "The main point at issue between Dr. Martinez and Dr. Williams is whether",
    answerChoices: [
      { letter: "A", text: "animal testing has historically contributed to medical advances" },
      { letter: "B", text: "human trials should be conducted before any preliminary safety testing" },
      { letter: "C", text: "viable alternatives to animal testing currently exist or are becoming available" },
      { letter: "D", text: "computer models can perfectly replicate biological systems" },
      { letter: "E", text: "medical research is important for human health" },
    ],
    correctAnswer: "C",
    explanation: "Dr. Martinez argues that there is no other way to study treatment effects on living organisms, while Dr. Williams argues that alternative technologies are increasingly providing viable options. The core disagreement is whether alternatives to animal testing exist or are becoming available.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-026",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The new tax proposal is unfair because it would primarily benefit wealthy individuals. Any policy that primarily benefits the wealthy rather than the middle class should be rejected. Therefore, lawmakers should vote against this proposal without further consideration.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that any benefit to wealthy individuals is inherently unfair" },
      { letter: "B", text: "fails to consider whether the proposal might benefit middle-class individuals as well" },
      { letter: "C", text: "does not define what constitutes the middle class" },
      { letter: "D", text: "ignores the possibility that the proposal has merits beyond its distributional effects" },
      { letter: "E", text: "assumes that all lawmakers share the same values regarding fairness" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'primarily benefits the wealthy' to 'should be rejected,' following the principle that policies primarily benefiting the wealthy over the middle class should be rejected. However, it fails to consider whether middle-class individuals might also benefit significantly, even if the wealthy benefit more.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-027",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: The decline of local newspapers has contributed to decreased civic engagement in communities. Local newspapers traditionally covered city council meetings, school board decisions, and local elections, keeping citizens informed about matters that directly affected their lives. Without this coverage, citizens are less aware of local issues and less likely to participate in local governance.`,
    questionStem: "Which one of the following, if true, most strengthens the sociologist's argument?",
    answerChoices: [
      { letter: "A", text: "National news organizations have increased their coverage of major metropolitan areas" },
      { letter: "B", text: "Voter turnout in local elections has declined more sharply in communities that lost their local newspapers" },
      { letter: "C", text: "Social media platforms now allow citizens to discuss local issues with each other" },
      { letter: "D", text: "Many local newspapers have transitioned to online-only formats" },
      { letter: "E", text: "Citizens report that they find national news more interesting than local news" },
    ],
    correctAnswer: "B",
    explanation: "A correlation between newspaper loss and declining local election turnout directly supports the claim that local newspaper decline contributes to decreased civic engagement. This empirical evidence strengthens the causal relationship the sociologist proposes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-028",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new interactive exhibit has been a success. Since it opened three months ago, overall museum attendance has increased by 25%. The interactive format clearly appeals to visitors more than traditional static displays, and the museum should convert more of its galleries to this format.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Interactive exhibits are more expensive to maintain than traditional displays" },
      { letter: "B", text: "The museum launched a major advertising campaign at the same time the new exhibit opened" },
      { letter: "C", text: "Some museum visitors have complained that interactive exhibits are too noisy" },
      { letter: "D", text: "Other museums in the area have also seen increased attendance recently" },
      { letter: "E", text: "The interactive exhibit focuses on a topic that was already popular with the public" },
    ],
    correctAnswer: "B",
    explanation: "If the museum launched a major advertising campaign at the same time as the exhibit, the attendance increase might be due to the advertising rather than the interactive format. This alternative explanation weakens the conclusion that the interactive format is responsible for the success.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-029",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If a restaurant receives consistently positive reviews, it will attract more customers. The Riverside Cafe has not attracted more customers lately. Therefore, the Riverside Cafe has not received consistently positive reviews.`,
    questionStem: "The reasoning in the argument above is most similar to the reasoning in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If an employee exceeds expectations, they will receive a bonus. Martinez exceeded expectations. Therefore, Martinez will receive a bonus." },
      { letter: "B", text: "If a book becomes a bestseller, it will be made into a movie. This book was made into a movie. Therefore, this book became a bestseller." },
      { letter: "C", text: "If a student studies effectively, the student will pass the exam. This student did not pass the exam. Therefore, this student did not study effectively." },
      { letter: "D", text: "If the temperature drops below freezing, the pipes may burst. The temperature dropped below freezing. Therefore, the pipes will burst." },
      { letter: "E", text: "If a candidate wins the primary, the candidate may win the general election. This candidate did not win the primary. Therefore, this candidate will not win the general election." },
    ],
    correctAnswer: "C",
    explanation: "The original argument has the form: If P, then Q. Not Q. Therefore, not P. This is the valid form known as modus tollens. Choice C follows the same pattern: If study effectively, then pass. Did not pass. Therefore, did not study effectively.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Philosophy professor: The existence of moral disagreement across cultures does not prove that morality is relative. People also disagree about scientific facts, but we do not conclude from this that there are no objective truths about the physical world. Therefore, we should not conclude that there are no objective moral truths simply because different cultures have different moral beliefs.`,
    questionStem: "The professor's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Moral disagreements are exactly analogous to scientific disagreements" },
      { letter: "B", text: "There are objective truths about the physical world" },
      { letter: "C", text: "Cultural differences in moral beliefs are not as significant as they appear" },
      { letter: "D", text: "Scientists never disagree about fundamental physical laws" },
      { letter: "E", text: "Moral truths are as easily verifiable as scientific truths" },
    ],
    correctAnswer: "B",
    explanation: "The professor's argument relies on an analogy with scientific disagreement. The argument assumes that we correctly conclude there are objective truths about the physical world despite scientific disagreement. If there were no objective physical truths, the analogy would not support the conclusion about moral truths.",
    difficulty: "hard",
  },
  {
    id: "lr-bank60-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Citizens should support the proposed highway expansion project. The project will reduce commute times, which will make workers more productive. More productive workers benefit the economy. Since everyone benefits from a strong economy, everyone should support this project.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that reduced commute times will necessarily lead to increased productivity" },
      { letter: "B", text: "fails to consider that the project may have costs that outweigh its benefits for some citizens" },
      { letter: "C", text: "does not address potential environmental impacts of highway expansion" },
      { letter: "D", text: "presumes that all citizens commute to work by car" },
      { letter: "E", text: "ignores the possibility that the project may take years to complete" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims everyone should support the project because everyone benefits from a strong economy. However, it ignores that the project may impose specific costs on some citizens (such as property loss, increased local traffic, or noise) that outweigh their share of the general economic benefit.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionists recommend eating breakfast to maintain a healthy weight. A study following 1,000 adults over ten years found that those who regularly skipped breakfast were more likely to be overweight than those who ate breakfast daily. The researchers concluded that eating breakfast helps regulate metabolism and prevents overeating later in the day.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "Breakfast eaters in the study consumed approximately the same total daily calories as breakfast skippers" },
      { letter: "B", text: "Most nutritionists believe that breakfast is the most important meal of the day" },
      { letter: "C", text: "Participants who ate breakfast tended to choose healthier foods throughout the day" },
      { letter: "D", text: "The study controlled for differences in exercise habits between the two groups" },
      { letter: "E", text: "Breakfast skippers in the study were more likely to snack late at night" },
    ],
    correctAnswer: "A",
    explanation: "If breakfast eaters consumed the same total daily calories as breakfast skippers but were less likely to be overweight, this supports the conclusion that eating breakfast affects metabolism in a way that prevents weight gain, rather than simply reducing overall calorie consumption.",
    difficulty: "hard",
  },
  {
    id: "lr-bank60-033",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Art critic: Abstract expressionism represented a decline in artistic skill. Unlike the Renaissance masters who could render realistic human figures with extraordinary precision, abstract expressionists produced works that any child could create. The value placed on these works by the art market is therefore entirely based on pretension rather than genuine artistic merit.`,
    questionStem: "Which one of the following, if true, most weakens the art critic's argument?",
    answerChoices: [
      { letter: "A", text: "Many abstract expressionists were trained in classical techniques before developing their abstract styles" },
      { letter: "B", text: "Some Renaissance paintings have sold for more money than abstract expressionist works" },
      { letter: "C", text: "The artistic techniques required for abstract expressionism are fundamentally different from, not lesser than, those of realism" },
      { letter: "D", text: "Public opinion about abstract expressionism has varied over time" },
      { letter: "E", text: "Some art collectors prefer abstract art to realistic art" },
    ],
    correctAnswer: "C",
    explanation: "The critic assumes that artistic skill equals the ability to render realistic images. If abstract expressionism requires different but equally demanding techniques, then the comparison to child's work is invalid, and the conclusion about lack of genuine merit is undermined.",
    difficulty: "hard",
  },
  {
    id: "lr-bank60-034",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The defendant's lawyer argued that the eyewitness testimony should be discounted because studies have shown that eyewitness identifications are often inaccurate, especially when the witness and subject are of different races. In this case, the witness identified the defendant across racial lines and under poor lighting conditions. The lawyer concluded that the identification cannot be considered reliable.`,
    questionStem: "The lawyer's argument uses which one of the following argumentative strategies?",
    answerChoices: [
      { letter: "A", text: "Citing general research findings and applying them to the specific circumstances of the case" },
      { letter: "B", text: "Attacking the credibility and character of the witness" },
      { letter: "C", text: "Demonstrating that the witness had a motive to lie" },
      { letter: "D", text: "Proving that the defendant was somewhere else at the time of the crime" },
      { letter: "E", text: "Arguing that the police investigation was improperly conducted" },
    ],
    correctAnswer: "A",
    explanation: "The lawyer cites general research about the unreliability of eyewitness testimony, particularly cross-racial identifications, and then applies these general findings to the specific circumstances of this case (cross-racial identification, poor lighting) to argue the testimony is unreliable.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-035",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every time I have eaten at that restaurant, I have enjoyed my meal. My friend also enjoys eating there. Therefore, everyone who eats at that restaurant enjoys their meals.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on the experiences of too few individuals to support a universal conclusion" },
      { letter: "B", text: "assumes that the friend and the speaker have similar tastes" },
      { letter: "C", text: "fails to consider that the restaurant's quality may have changed over time" },
      { letter: "D", text: "ignores the possibility that some menu items are better than others" },
      { letter: "E", text: "presumes that enjoyment can be objectively measured" },
    ],
    correctAnswer: "A",
    explanation: "The argument generalizes from the experiences of just two individuals (the speaker and a friend) to a universal claim about everyone who eats at the restaurant. This is a hasty generalization based on an insufficient sample size.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-036",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The university should not eliminate its philosophy department. Philosophy teaches critical thinking skills that are essential in all areas of life and work. Graduates with philosophy degrees often succeed in diverse fields such as law, business, and technology, demonstrating that the skills developed through philosophical study are broadly applicable.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Philosophy is the only discipline that teaches critical thinking skills" },
      { letter: "B", text: "Philosophy graduates earn higher salaries than graduates in other fields" },
      { letter: "C", text: "Critical thinking skills cannot be effectively taught outside of a philosophy department" },
      { letter: "D", text: "The success of philosophy graduates in other fields is at least partly attributable to their philosophical training" },
      { letter: "E", text: "All university departments should be evaluated based on the career success of their graduates" },
    ],
    correctAnswer: "D",
    explanation: "The argument cites philosophy graduates' success in diverse fields as evidence that philosophical study provides valuable skills. This reasoning assumes that the graduates' success is at least partly due to their philosophical training rather than other factors.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-037",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All of the company's vice presidents have at least fifteen years of experience in the industry. Some of the vice presidents have MBA degrees. Everyone with an MBA degree who has at least fifteen years of industry experience is eligible for the CEO position.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All of the company's vice presidents are eligible for the CEO position" },
      { letter: "B", text: "Some of the company's vice presidents are eligible for the CEO position" },
      { letter: "C", text: "Anyone eligible for the CEO position must be a vice president" },
      { letter: "D", text: "All people with MBA degrees are eligible for the CEO position" },
      { letter: "E", text: "Only people with MBA degrees can become CEO" },
    ],
    correctAnswer: "B",
    explanation: "All vice presidents have at least fifteen years of experience, and some vice presidents have MBA degrees. Those with both an MBA and fifteen years of experience are eligible for CEO. Therefore, the vice presidents with MBAs (who all have the required experience) are eligible for the CEO position.",
    difficulty: "hard",
  },
  {
    id: "lr-bank60-038",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Editor Johnson: Our newspaper should maintain strict objectivity in its news coverage. Reporters should present facts without interpretation or opinion, allowing readers to draw their own conclusions. This is the essence of responsible journalism.

Editor Park: Pure objectivity in journalism is a myth. Every choice about what stories to cover, which sources to quote, and how to frame an issue involves subjective judgment. Rather than pretending to be objective, journalists should be transparent about their perspectives while still being fair and accurate.`,
    questionStem: "Editor Johnson and Editor Park disagree over whether",
    answerChoices: [
      { letter: "A", text: "journalists have an obligation to be accurate in their reporting" },
      { letter: "B", text: "readers are capable of drawing their own conclusions from factual reporting" },
      { letter: "C", text: "objectivity in news reporting is achievable and should be the goal" },
      { letter: "D", text: "newspapers should cover a wide variety of stories" },
      { letter: "E", text: "fairness is an important value in journalism" },
    ],
    correctAnswer: "C",
    explanation: "Editor Johnson advocates for strict objectivity as the essence of responsible journalism. Editor Park argues that pure objectivity is a myth and that transparency about perspectives is preferable to pretending to be objective. They fundamentally disagree about whether objectivity is achievable and should be the journalistic goal.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-039",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `People should exercise more regularly because regular exercise improves cardiovascular health. Improved cardiovascular health leads to a longer life. Everyone wants to live a long life. Therefore, people who do not exercise regularly do not really want to live long lives.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that cardiovascular health is the only factor affecting longevity" },
      { letter: "B", text: "confuses what people want with what people actually do" },
      { letter: "C", text: "ignores the possibility that some forms of exercise may not improve cardiovascular health" },
      { letter: "D", text: "presumes that living longer is always desirable" },
      { letter: "E", text: "fails to consider that some people may be unable to exercise" },
    ],
    correctAnswer: "B",
    explanation: "The argument fallaciously concludes that people who do not exercise do not want to live long lives. However, wanting something does not always translate into doing what is necessary to achieve it. People may want to live long but fail to exercise due to lack of discipline, time, knowledge, or other factors.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-040",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Criminal justice reformers argue that rehabilitation programs reduce recidivism more effectively than harsh punishment. They point to countries with rehabilitation-focused prison systems that have significantly lower rates of reoffending than countries with punitive systems. Critics counter that cultural differences, not prison policies, explain the different recidivism rates.`,
    questionStem: "Which one of the following, if true, most strengthens the reformers' position against the critics' objection?",
    answerChoices: [
      { letter: "A", text: "Rehabilitation programs are less expensive to implement than punitive measures" },
      { letter: "B", text: "Prisoners who participate in rehabilitation programs report higher life satisfaction" },
      { letter: "C", text: "Within the same country, prisons using rehabilitation approaches have lower recidivism rates than those using punitive approaches" },
      { letter: "D", text: "Recidivism rates have remained stable in most countries over the past decade" },
      { letter: "E", text: "Some countries with punitive systems have implemented rehabilitation programs in recent years" },
    ],
    correctAnswer: "C",
    explanation: "If recidivism differences appear within the same country between rehabilitation and punitive prisons, cultural differences cannot explain the variation. This directly counters the critics' objection that cultural rather than policy differences account for the international disparities.",
    difficulty: "hard",
  },
  {
    id: "lr-bank60-041",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Many ancient myths contain stories of catastrophic floods. The widespread presence of flood narratives across unrelated cultures suggests that these stories are based on actual historical events. There must have been a massive global flood at some point in human prehistory that gave rise to these common myths.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some ancient cultures do not have flood myths in their traditions" },
      { letter: "B", text: "Flooding is a common local occurrence in many parts of the world, and different cultures would naturally develop flood stories independently" },
      { letter: "C", text: "Geological evidence does not support the occurrence of a global flood" },
      { letter: "D", text: "Many ancient myths also contain stories about the sun, moon, and stars" },
      { letter: "E", text: "Some scholars believe that flood myths have symbolic rather than literal meanings" },
    ],
    correctAnswer: "B",
    explanation: "If flooding is a common local phenomenon worldwide, then multiple cultures would independently develop flood myths based on their own local experiences. This alternative explanation for the widespread presence of flood myths eliminates the need to posit a single global flood as the origin.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-042",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some government officials are not honest. All honest people can be trusted. Therefore, some government officials cannot be trusted.`,
    questionStem: "The flawed pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some teachers are not patient. All patient people are good with children. Therefore, some teachers are not good with children." },
      { letter: "B", text: "All doctors are intelligent. Some intelligent people are arrogant. Therefore, some doctors are arrogant." },
      { letter: "C", text: "No criminals are law-abiding. Some law-abiding citizens are not wealthy. Therefore, no criminals are wealthy." },
      { letter: "D", text: "All musicians are creative. Some creative people are not successful. Therefore, some musicians are not successful." },
      { letter: "E", text: "Some athletes are not dedicated. All dedicated people succeed. Therefore, all athletes succeed." },
    ],
    correctAnswer: "A",
    explanation: "The original argument reasons: Some A are not B. All B are C. Therefore, some A are not C. This is flawed because being not-B does not mean lacking property C (which is guaranteed only for B). Choice A follows the same pattern: Some teachers are not patient. All patient people are good with children. Therefore, some teachers are not good with children.",
    difficulty: "hard",
  },
  {
    id: "lr-bank60-043",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Investment advisor: My client argues that she should sell her technology stocks because the sector is overvalued. But just last year, she said the same thing before technology stocks rose another 20%. And three years ago, she predicted a crash that never came. Given her track record, there is no reason to think her current pessimism is any more justified.`,
    questionStem: "The investment advisor responds to the client's argument by",
    answerChoices: [
      { letter: "A", text: "demonstrating that the client's conclusion is based on faulty data" },
      { letter: "B", text: "pointing out that the client has been wrong about similar predictions in the past" },
      { letter: "C", text: "showing that the client does not understand how stock valuations work" },
      { letter: "D", text: "arguing that technology stocks are actually undervalued" },
      { letter: "E", text: "presenting evidence that contradicts the client's assessment of current market conditions" },
    ],
    correctAnswer: "B",
    explanation: "The advisor challenges the client's current prediction by citing the client's past failed predictions about technology stocks. By showing that the client has been wrong about similar assessments before, the advisor suggests the current prediction is equally unreliable.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-044",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The local theater company should perform more contemporary plays rather than focusing primarily on classical works. Audiences today find it easier to relate to stories that reflect current social issues and use modern language. When people can relate to what they see on stage, they are more likely to attend performances.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "classical plays cannot be performed in ways that relate to contemporary audiences" },
      { letter: "B", text: "the primary goal of the theater company is to maximize attendance" },
      { letter: "C", text: "contemporary plays are of higher artistic quality than classical works" },
      { letter: "D", text: "audiences are not interested in learning about historical periods" },
      { letter: "E", text: "all contemporary plays address current social issues" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that the theater should perform more contemporary plays because they will increase attendance. This conclusion only follows if the theater's primary concern is attracting audiences rather than other goals like preserving classical traditions or artistic excellence.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-045",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Senator Reynolds has advocated for stronger environmental regulations on factories. However, Senator Reynolds owns stock in several companies that manufacture pollution control equipment. Clearly, the senator's environmental advocacy is motivated by personal financial gain rather than genuine concern for the environment.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "attacks the senator's motives rather than addressing the merits of stronger regulations" },
      { letter: "B", text: "assumes that owning stock in pollution control companies is unethical" },
      { letter: "C", text: "fails to establish that the senator's stock holdings are significant enough to influence policy positions" },
      { letter: "D", text: "ignores the possibility that the senator divested from polluting industries" },
      { letter: "E", text: "presumes that politicians cannot have both personal and public interests in the same policy" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits the genetic fallacy by focusing on the senator's alleged motives rather than evaluating whether stronger environmental regulations are actually good policy. Even if the senator has financial interests, this does not determine whether the policy position is correct or beneficial.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-046",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Biologists have observed that certain species of birds in urban areas have developed higher-pitched songs than their counterparts in rural areas. The researchers hypothesize that this adaptation allows urban birds to communicate more effectively despite the low-frequency noise pollution common in cities, such as traffic sounds.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Urban birds have also developed louder songs than rural birds" },
      { letter: "B", text: "Traffic noise in cities is concentrated at lower frequencies that would interfere less with higher-pitched songs" },
      { letter: "C", text: "Some urban bird species have not changed their song frequencies" },
      { letter: "D", text: "Rural birds can communicate effectively at lower frequencies" },
      { letter: "E", text: "Birds in quiet suburban areas have intermediate song frequencies" },
    ],
    correctAnswer: "B",
    explanation: "If traffic noise is concentrated at lower frequencies, then higher-pitched songs would avoid this interference, supporting the hypothesis that the pitch shift is an adaptation for communication in noisy urban environments. This explains why higher pitch specifically would be advantageous.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-047",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Company executives argue that their generous executive compensation packages are necessary to attract and retain top talent. They point out that executives who feel undercompensated will leave for competitors who pay more, harming the company's performance. Therefore, shareholders should approve the proposed increase in executive pay.`,
    questionStem: "Which one of the following, if true, most weakens the executives' argument?",
    answerChoices: [
      { letter: "A", text: "Some executives are motivated by factors other than compensation, such as company culture and job satisfaction" },
      { letter: "B", text: "The proposed compensation increase would reduce funds available for employee wages and research" },
      { letter: "C", text: "Research shows no correlation between executive pay levels and company performance" },
      { letter: "D", text: "Many companies have successfully recruited executives while offering below-market compensation" },
      { letter: "E", text: "Executive compensation has increased faster than average worker wages over the past two decades" },
    ],
    correctAnswer: "C",
    explanation: "If there is no correlation between executive pay and company performance, then the argument that higher pay is necessary to attract talent who will improve performance is undermined. The lack of connection between pay and outcomes weakens the justification for increased compensation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank60-048",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The invention of the printing press is often cited as the most important technological development in human history. However, the development of writing itself was far more revolutionary. Writing enabled the preservation and transmission of knowledge across generations, the creation of complex legal and economic systems, and the emergence of organized religion. The printing press merely made the products of writing more widely available; it did not create the fundamental transformation that writing itself accomplished.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "The printing press is often considered the most important technological development" },
      { letter: "B", text: "Writing enabled the preservation and transmission of knowledge" },
      { letter: "C", text: "The development of writing was more revolutionary than the invention of the printing press" },
      { letter: "D", text: "The printing press made the products of writing more widely available" },
      { letter: "E", text: "Organized religion emerged as a result of writing" },
    ],
    correctAnswer: "C",
    explanation: "The argument contrasts the common view about the printing press with the claim that writing was more revolutionary. The supporting evidence about writing's effects and the characterization of the printing press as merely expanding access both support the main conclusion that writing was the more revolutionary development.",
    difficulty: "easy",
  },
  {
    id: "lr-bank60-049",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Wildlife biologist: The declining wolf population in this region cannot be explained by natural predation alone, since wolves have no natural predators in this area. Nor can it be explained by disease, as veterinary examinations of deceased wolves show no evidence of illness. The most likely explanation is illegal hunting, which authorities have struggled to prevent.`,
    questionStem: "The wildlife biologist's argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "illegal hunting is widespread in regions where wolves live" },
      { letter: "B", text: "the veterinary examinations were conducted on a representative sample of deceased wolves" },
      { letter: "C", text: "there are no other significant factors besides predation, disease, and hunting that could cause population decline" },
      { letter: "D", text: "wolf populations in other regions are not experiencing similar declines" },
      { letter: "E", text: "authorities have the resources to prevent illegal hunting if they try harder" },
    ],
    correctAnswer: "C",
    explanation: "The biologist eliminates predation and disease, then concludes that illegal hunting is the most likely cause. This reasoning assumes there are no other significant factors that could explain the decline, such as habitat loss, food scarcity, or reduced reproduction rates.",
    difficulty: "hard",
  },
  {
    id: "lr-bank60-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The Roman Empire fell because of internal moral decay rather than external military pressure. During its final centuries, Roman citizens became increasingly focused on personal pleasure and abandoned the civic virtues that had built the empire. This moral decline weakened the society from within and made it vulnerable to outside forces. The lesson for our own society is clear: we must resist moral decay if we wish to avoid a similar fate.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes without justification that modern society is comparable to the Roman Empire" },
      { letter: "B", text: "relies on a simplistic single-cause explanation for a complex historical event" },
      { letter: "C", text: "defines moral decay in a way that cannot be objectively measured" },
      { letter: "D", text: "ignores evidence that contradicts the claim about Roman moral decline" },
      { letter: "E", text: "presumes that what happened in the past will necessarily happen in the future" },
    ],
    correctAnswer: "B",
    explanation: "The fall of the Roman Empire was an extraordinarily complex event with multiple contributing factors including economic problems, military overextension, political instability, and external invasions. Attributing it primarily to moral decay oversimplifies history and may lead to flawed conclusions about modern societies.",
    difficulty: "hard",
  },
];
