// Logical Reasoning Questions Bank - Set 31
import { Question } from "../lsat-types";

export const lrQuestionsSet31: Question[] = [
  {
    id: "lr-bank31-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that students who use laptops in class have lower grades than students who take notes by hand. Therefore, laptops must interfere with learning, and schools should ban them from classrooms to improve academic performance.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on a sample that is too small to support the conclusion" },
      { letter: "B", text: "assumes that correlation between two factors establishes that one causes the other" },
      { letter: "C", text: "fails to consider that students might have different learning styles" },
      { letter: "D", text: "ignores the possibility that laptops have educational benefits beyond note-taking" },
      { letter: "E", text: "presumes that all schools have the resources to enforce such a ban" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the classic correlation-causation fallacy. Just because laptop users have lower grades doesn't mean laptops cause lower grades. There could be other explanations—perhaps struggling students prefer laptops, or perhaps students who use laptops are taking more difficult courses.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeological evidence shows that ancient civilizations in the Indus Valley had sophisticated drainage systems and urban planning. Historians have concluded that these civilizations must have had a centralized government capable of organizing large-scale public works projects.`,
    questionStem: "Which one of the following, if true, most strengthens the historians' conclusion?",
    answerChoices: [
      { letter: "A", text: "Similar drainage systems have been found in other ancient civilizations known to have centralized governments" },
      { letter: "B", text: "The drainage systems required standardized brick sizes across multiple cities spanning hundreds of miles" },
      { letter: "C", text: "Some ancient civilizations with centralized governments did not build sophisticated drainage systems" },
      { letter: "D", text: "The Indus Valley civilizations engaged in extensive trade with neighboring regions" },
      { letter: "E", text: "Modern drainage systems are typically built by municipal governments" },
    ],
    correctAnswer: "B",
    explanation: "The standardization of brick sizes across vast distances strongly suggests centralized coordination and authority. This type of uniformity would be very difficult to achieve without some form of central planning and government oversight, thereby strengthening the conclusion about centralized government.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that building a new sports stadium will revitalize the downtown area. They point to increased property values and new business development near stadiums in other cities as evidence that such projects stimulate economic growth in surrounding neighborhoods.`,
    questionStem: "Which one of the following, if true, most seriously weakens the city council's argument?",
    answerChoices: [
      { letter: "A", text: "Some residents near the proposed stadium site have expressed concerns about increased traffic" },
      { letter: "B", text: "The proposed stadium would require significant public funding that could otherwise be used for infrastructure improvements" },
      { letter: "C", text: "Studies show that increased property values near new stadiums typically result from displacement of existing businesses and residents rather than genuine economic growth" },
      { letter: "D", text: "The city already has several sports facilities that are underutilized" },
      { letter: "E", text: "Professional sports teams sometimes relocate to new cities offering better stadium deals" },
    ],
    correctAnswer: "C",
    explanation: "This answer directly challenges the assumption that increased property values represent genuine economic revitalization. If the increases result from displacement rather than growth, the stadium isn't creating new economic activity but merely redistributing it while potentially harming existing communities.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martinez argues that philosophy courses should be required for all college students. She reasons that studying philosophy teaches critical thinking skills, and critical thinking skills are essential for success in any career. Therefore, requiring philosophy courses would better prepare students for their professional lives.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Philosophy is the only discipline that teaches critical thinking skills" },
      { letter: "B", text: "All students will apply critical thinking skills in their careers" },
      { letter: "C", text: "Philosophy courses are more effective at teaching critical thinking than students' other coursework" },
      { letter: "D", text: "Students cannot develop critical thinking skills without formal instruction" },
      { letter: "E", text: "Career success is the primary goal of college education" },
    ],
    correctAnswer: "C",
    explanation: "For the argument to work, philosophy courses must provide something that students wouldn't otherwise get from their existing coursework. If other courses already teach critical thinking equally well, there would be no added benefit from requiring philosophy specifically.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical researchers have discovered that patients who participate in clinical trials often show improvement even when given placebos. This phenomenon, known as the placebo effect, demonstrates that psychological factors can produce real physiological changes. Consequently, healthcare providers should recognize that a patient's beliefs and expectations about treatment can significantly influence health outcomes.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Patients in clinical trials often improve when given placebos" },
      { letter: "B", text: "Psychological factors can cause genuine physical changes in the body" },
      { letter: "C", text: "Healthcare providers should acknowledge that patient beliefs can affect treatment outcomes" },
      { letter: "D", text: "The placebo effect is a well-documented medical phenomenon" },
      { letter: "E", text: "Clinical trials must account for psychological factors in their design" },
    ],
    correctAnswer: "C",
    explanation: "The word 'Consequently' signals the main conclusion. The argument uses the evidence about placebos and psychological factors to support the practical recommendation that healthcare providers should recognize the role of patient beliefs in health outcomes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critics argue that social media platforms should not moderate content because doing so infringes on free speech. However, private companies have always had the right to set rules for their platforms, just as newspapers have always had the right to decide what letters to publish. If we accept that newspapers can exercise editorial judgment without violating free speech, we must accept the same for social media companies.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "demonstrating that an opposing view leads to a logical contradiction" },
      { letter: "B", text: "drawing an analogy between social media platforms and a more established institution" },
      { letter: "C", text: "providing statistical evidence to refute the critics' position" },
      { letter: "D", text: "questioning the motives of those who oppose content moderation" },
      { letter: "E", text: "showing that free speech has never been an absolute right" },
    ],
    correctAnswer: "B",
    explanation: "The argument draws a direct analogy between social media platforms and newspapers. It argues that since newspapers can exercise editorial judgment without violating free speech, the same logic should apply to social media companies making content moderation decisions.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The environmental group argues that we should ban all pesticides because some pesticides have been shown to harm beneficial insects like bees. But this position is extreme. After all, would they also ban all medicines because some medicines have harmful side effects? Clearly, we should not ban all pesticides.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that pesticides and medicines serve different purposes" },
      { letter: "B", text: "misrepresents the environmental group's position as more extreme than it actually is" },
      { letter: "C", text: "assumes that what is true of medicines must also be true of pesticides" },
      { letter: "D", text: "ignores the possibility that some pesticides are more harmful than others" },
      { letter: "E", text: "relies on an inappropriate analogy between pesticides and medicines" },
    ],
    correctAnswer: "B",
    explanation: "This is a straw man fallacy. The argument misrepresents the environmental group's position. Just because the group wants to ban 'all pesticides' due to harm to bees doesn't mean their actual position is that extreme—the argument may be exaggerating their stance to make it easier to attack.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholars have proposed that mandatory minimum sentences for drug offenses should be eliminated. They argue that judges need discretion to consider individual circumstances, as identical crimes may warrant different punishments depending on the offender's background, role in the offense, and potential for rehabilitation.`,
    questionStem: "Which one of the following, if true, most strengthens the legal scholars' argument?",
    answerChoices: [
      { letter: "A", text: "Mandatory minimum sentences were originally enacted to ensure consistent punishment across jurisdictions" },
      { letter: "B", text: "Countries that allow judicial discretion in sentencing have lower recidivism rates than those with mandatory minimums" },
      { letter: "C", text: "Some judges have expressed frustration with being unable to consider mitigating factors in sentencing" },
      { letter: "D", text: "Drug offenses account for a significant portion of the prison population" },
      { letter: "E", text: "Public opinion polls show mixed support for mandatory minimum sentences" },
    ],
    correctAnswer: "B",
    explanation: "Lower recidivism rates in countries with judicial discretion provide empirical support for the claim that considering individual circumstances leads to better outcomes. This directly strengthens the argument that judges should have discretion to tailor sentences to individual offenders.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-009",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should not invest in expanding public transportation because most residents drive personal vehicles to work. Resources spent on buses and trains would primarily benefit only a small minority of the population, making such investment an inefficient use of taxpayer money.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Personal vehicles are more convenient than public transportation for most commuters" },
      { letter: "B", text: "The number of people who would use expanded public transportation would not significantly increase" },
      { letter: "C", text: "Public transportation is more expensive to maintain than road infrastructure for personal vehicles" },
      { letter: "D", text: "Taxpayer money should only be spent on services that benefit the majority of residents" },
      { letter: "E", text: "Most residents prefer driving to using public transportation" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that current ridership patterns would continue even with expanded service. However, if expanded service attracted significantly more riders (perhaps because current service is inadequate), the investment could benefit many more people than the current 'small minority.'",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-010",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company claims that its new weight-loss drug is effective because participants in their clinical trial lost an average of 15 pounds over six months. The company argues that this proves the drug should be approved for widespread use.`,
    questionStem: "Which one of the following, if true, most seriously weakens the pharmaceutical company's argument?",
    answerChoices: [
      { letter: "A", text: "Some participants in the trial experienced mild side effects such as headaches" },
      { letter: "B", text: "The trial did not include a control group receiving a placebo" },
      { letter: "C", text: "Weight-loss drugs have historically been controversial in the medical community" },
      { letter: "D", text: "The trial lasted only six months, which may be too short to assess long-term effects" },
      { letter: "E", text: "Other weight-loss drugs currently on the market have similar effectiveness rates" },
    ],
    correctAnswer: "B",
    explanation: "Without a placebo control group, there's no way to know if the weight loss was caused by the drug or by other factors (such as participants' changed behavior from being in a trial, dietary changes, or natural weight fluctuation). This is a fundamental methodological flaw that undermines the claim of effectiveness.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-011",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Elena: Artificial intelligence will eventually surpass human intelligence in all domains. Once AI systems can improve themselves, they will rapidly become more capable than humans at every cognitive task, including creativity and emotional intelligence.

James: While AI has made impressive advances in specific tasks, human intelligence is fundamentally different from machine processing. Consciousness, genuine understanding, and emotional experience cannot be replicated by algorithms, no matter how sophisticated.`,
    questionStem: "Elena and James disagree about whether",
    answerChoices: [
      { letter: "A", text: "AI has made significant progress in recent years" },
      { letter: "B", text: "emotional intelligence is an important human capability" },
      { letter: "C", text: "AI can eventually replicate all aspects of human cognition" },
      { letter: "D", text: "current AI systems are useful for certain tasks" },
      { letter: "E", text: "consciousness is an important aspect of human intelligence" },
    ],
    correctAnswer: "C",
    explanation: "Elena believes AI will surpass humans 'in all domains' including creativity and emotional intelligence. James directly disagrees, arguing that consciousness, understanding, and emotional experience 'cannot be replicated' by AI. Their core disagreement is about whether AI can eventually match all human cognitive abilities.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-012",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Everyone who has won the Nobel Prize in Physics has been exceptionally intelligent. Dr. Harrison is exceptionally intelligent. Therefore, Dr. Harrison will win the Nobel Prize in Physics.`,
    questionStem: "The flawed reasoning in the argument above is most similar to the flawed reasoning in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All professional athletes are physically fit. Marcus is a professional athlete. Therefore, Marcus is physically fit." },
      { letter: "B", text: "All successful entrepreneurs work hard. Jennifer works hard. Therefore, Jennifer is a successful entrepreneur." },
      { letter: "C", text: "Some doctors are surgeons. Dr. Smith is a doctor. Therefore, Dr. Smith might be a surgeon." },
      { letter: "D", text: "No reptiles are mammals. Snakes are reptiles. Therefore, snakes are not mammals." },
      { letter: "E", text: "Most teachers are patient. Patricia is patient. Therefore, Patricia is probably a teacher." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments commit the fallacy of affirming the consequent. The original argues: All Nobel winners are intelligent → Harrison is intelligent → Harrison will win. Answer B has the same structure: All successful entrepreneurs work hard → Jennifer works hard → Jennifer is a successful entrepreneur. Both incorrectly reverse a conditional relationship.",
    difficulty: "hard",
  },
  {
    id: "lr-bank31-013",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If a country reduces its carbon emissions significantly, it will help slow climate change. Country X has not reduced its carbon emissions significantly. Therefore, Country X is not helping to slow climate change.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If a student studies consistently, the student will pass the exam. This student did not study consistently. Therefore, this student will not pass the exam." },
      { letter: "B", text: "If a medicine is effective, it will reduce symptoms. This medicine reduces symptoms. Therefore, this medicine is effective." },
      { letter: "C", text: "If an employee meets all targets, the employee will receive a bonus. This employee did not receive a bonus. Therefore, this employee did not meet all targets." },
      { letter: "D", text: "If a building is well-maintained, it will last for decades. This building has lasted for decades. Therefore, this building is well-maintained." },
      { letter: "E", text: "If a law is clearly written, it will be easy to enforce. This law is not clearly written. Therefore, this law will be difficult to enforce." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments have the form: If P, then Q. Not P. Therefore, not Q. This is the formal fallacy of denying the antecedent. Answer A follows the exact same flawed pattern: If study consistently, then pass. Didn't study consistently. Therefore, won't pass.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying ancient human migration patterns have found similar tool-making techniques among prehistoric peoples in Eastern Asia and the Americas. They conclude that the first Americans must have migrated from Asia, bringing their tool-making knowledge with them.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "The tools found in the Americas are dated to a period after the tools found in Eastern Asia" },
      { letter: "B", text: "Modern genetic studies show connections between some Asian and American populations" },
      { letter: "C", text: "Similar environmental conditions existed in both Eastern Asia and the Americas during prehistoric times" },
      { letter: "D", text: "The tool-making techniques are too complex to have been independently developed in separate locations" },
      { letter: "E", text: "Archaeological sites in the Americas are more numerous than those in Eastern Asia" },
    ],
    correctAnswer: "A",
    explanation: "If the American tools are dated later than the Asian tools, this establishes a temporal sequence consistent with migration from Asia to the Americas. This chronological evidence strengthens the claim that the techniques were brought from Asia rather than developed independently or traveling in the opposite direction.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-015",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The board of directors should not approve the merger because it would result in significant job losses. Thousands of employees would be laid off, devastating local communities that depend on these jobs for economic stability.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The merger would not create any new jobs in other areas" },
      { letter: "B", text: "Job losses are a more important consideration than potential benefits of the merger" },
      { letter: "C", text: "The laid-off employees would be unable to find other employment" },
      { letter: "D", text: "Local communities cannot adapt to economic changes" },
      { letter: "E", text: "The board of directors has the authority to reject the merger" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that job losses should be the decisive factor against the merger. However, a merger might have benefits (efficiency gains, long-term competitiveness, new opportunities) that could outweigh the job losses. The argument assumes job losses trump these potential benefits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-016",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The mayor argues that the new downtown development project will reduce traffic congestion because it will include residential units close to business districts. When people live near where they work, she reasons, they will drive less, thereby reducing the number of cars on the road during rush hour.`,
    questionStem: "Which one of the following, if true, most seriously weakens the mayor's argument?",
    answerChoices: [
      { letter: "A", text: "Some residents of the new development may choose to work remotely rather than commute" },
      { letter: "B", text: "The new development will also include retail spaces that will attract shoppers from across the city" },
      { letter: "C", text: "Public transportation options in the downtown area are limited" },
      { letter: "D", text: "The residential units in the development will be priced higher than average for the area" },
      { letter: "E", text: "Traffic congestion has been steadily worsening in the downtown area over the past decade" },
    ],
    correctAnswer: "B",
    explanation: "If the development includes retail that attracts shoppers from across the city, it could increase rather than decrease traffic, as people drive downtown to shop. This directly undermines the mayor's conclusion that the development will reduce congestion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-017",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Senator Williams has proposed legislation to increase funding for renewable energy research. However, Senator Williams owns stock in several solar energy companies. Clearly, her proposal is motivated by personal financial gain rather than genuine concern for the environment, and therefore we should reject her legislation.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that legislation cannot benefit both the public and its sponsor" },
      { letter: "B", text: "attacks the character of the person making the proposal rather than addressing the merits of the proposal itself" },
      { letter: "C", text: "fails to consider that other senators might also benefit from the legislation" },
      { letter: "D", text: "ignores the possibility that the Senator acquired the stock after formulating the proposal" },
      { letter: "E", text: "presumes that all investments in renewable energy are motivated by profit" },
    ],
    correctAnswer: "B",
    explanation: "This is an ad hominem fallacy. The argument attacks Senator Williams's motives rather than evaluating the merits of the renewable energy legislation itself. Even if the Senator would benefit financially, the legislation might still be good policy. The source's motives don't determine whether the proposal is sound.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-018",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some critics claim that violent video games cause aggressive behavior in players. However, countries like Japan and South Korea have some of the highest rates of video game consumption in the world, yet they have significantly lower rates of violent crime than countries where video games are less popular. This suggests that the relationship between video games and violence is not as straightforward as critics claim.`,
    questionStem: "The argument employs which one of the following methods of reasoning?",
    answerChoices: [
      { letter: "A", text: "Providing a counterexample that challenges a proposed causal relationship" },
      { letter: "B", text: "Demonstrating that the critics' position contains an internal contradiction" },
      { letter: "C", text: "Offering an alternative explanation for the phenomenon in question" },
      { letter: "D", text: "Questioning the expertise of those who make the original claim" },
      { letter: "E", text: "Showing that the critics' conclusion is based on insufficient data" },
    ],
    correctAnswer: "A",
    explanation: "The argument presents Japan and South Korea as counterexamples to the claimed causal relationship between violent video games and aggressive behavior. If video games caused violence, countries with high video game consumption should have high violence rates, but these countries show the opposite pattern.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-019",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All licensed physicians must complete continuing medical education requirements to maintain their licenses. Dr. Chen has maintained her medical license for the past twenty years without interruption. The state medical board records show that continuing education requirements have been in place throughout this entire period.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Dr. Chen has never failed to meet a continuing education deadline" },
      { letter: "B", text: "Dr. Chen has completed continuing medical education requirements over the past twenty years" },
      { letter: "C", text: "Dr. Chen is considered an expert in her field" },
      { letter: "D", text: "The continuing education requirements have become more stringent over time" },
      { letter: "E", text: "Dr. Chen has practiced medicine continuously for twenty years" },
    ],
    correctAnswer: "B",
    explanation: "Since all licensed physicians must complete continuing education to maintain their licenses, and Dr. Chen has maintained her license throughout the period when these requirements were in effect, it must be true that she has completed the required continuing education. This is a straightforward logical inference.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-020",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Sociologists argue that the decline of traditional community organizations like civic clubs and religious institutions has led to increased social isolation and declining mental health in modern society. They point to the rise in depression and anxiety rates over the past several decades as evidence of this connection.`,
    questionStem: "Which one of the following, if true, most strengthens the sociologists' argument?",
    answerChoices: [
      { letter: "A", text: "Mental health treatment options have improved significantly in recent decades" },
      { letter: "B", text: "Individuals who actively participate in community organizations report lower rates of depression and anxiety than those who do not" },
      { letter: "C", text: "The decline in community organization membership began before the rise in mental health issues was documented" },
      { letter: "D", text: "Social media usage has increased at the same time that community organization participation has declined" },
      { letter: "E", text: "Some community organizations have adapted to modern life by offering online participation options" },
    ],
    correctAnswer: "C",
    explanation: "Establishing that the decline in community organizations preceded the rise in mental health issues strengthens the causal claim by establishing the correct temporal sequence. Causes must precede their effects, so showing that the proposed cause came first supports the argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-021",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The defendant cannot be guilty of the crime because she claims she was at home at the time of the robbery. When questioned by police, she stated clearly that she never left her house that evening. Since she has no reason to lie, we must conclude that she is innocent.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider physical evidence from the crime scene" },
      { letter: "B", text: "relies solely on the defendant's own uncorroborated testimony" },
      { letter: "C", text: "assumes that the police conducted a proper investigation" },
      { letter: "D", text: "ignores the possibility that the defendant had an accomplice" },
      { letter: "E", text: "presumes that all defendants tell the truth when questioned" },
    ],
    correctAnswer: "B",
    explanation: "The argument's main flaw is that it accepts the defendant's claim as proof of innocence without any corroborating evidence. The assertion that she has 'no reason to lie' is itself unsubstantiated, and self-serving statements by accused individuals require independent verification.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-022",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Companies that offer flexible work arrangements see higher employee satisfaction and lower turnover rates. Therefore, all companies should implement flexible work policies to improve their workforce retention.`,
    questionStem: "Which one of the following is an assumption on which the argument depends?",
    answerChoices: [
      { letter: "A", text: "Employee satisfaction is the primary factor in workforce retention" },
      { letter: "B", text: "Flexible work arrangements are the only way to improve employee satisfaction" },
      { letter: "C", text: "The benefits of flexible work arrangements outweigh any potential drawbacks for all companies" },
      { letter: "D", text: "Employees at all companies desire flexible work arrangements" },
      { letter: "E", text: "Companies that currently lack flexible policies have lower employee satisfaction" },
    ],
    correctAnswer: "C",
    explanation: "The argument recommends all companies implement flexible work policies. This assumes that doing so would be beneficial overall for every company. However, some companies might face unique challenges (security requirements, customer-facing roles, manufacturing constraints) where flexible work could create problems that outweigh the retention benefits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Economists argue that raising the minimum wage will not lead to significant job losses because when workers have more money, they spend more, stimulating the economy and creating new jobs that offset any positions eliminated due to higher labor costs.`,
    questionStem: "Which one of the following, if true, most seriously weakens the economists' argument?",
    answerChoices: [
      { letter: "A", text: "Some businesses have chosen to automate positions rather than pay higher wages" },
      { letter: "B", text: "Minimum wage increases are often phased in gradually over several years" },
      { letter: "C", text: "Workers who receive higher wages tend to save a significant portion of the increase rather than spend it" },
      { letter: "D", text: "Large corporations can absorb wage increases more easily than small businesses" },
      { letter: "E", text: "The minimum wage has not kept pace with inflation over the past several decades" },
    ],
    correctAnswer: "C",
    explanation: "The economists' argument depends on workers spending their additional income to stimulate the economy. If workers save rather than spend a significant portion of wage increases, the economic stimulus effect would be diminished, weakening the argument that increased spending would create offsetting jobs.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-024",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Studies have shown that children who learn to play musical instruments perform better in mathematics. Music training develops pattern recognition and spatial-temporal reasoning, skills that are directly applicable to mathematical thinking. Schools that have cut music programs in favor of more math instruction may therefore be undermining the very goal they seek to achieve.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Children who play musical instruments have better mathematical abilities" },
      { letter: "B", text: "Music training develops cognitive skills useful for mathematics" },
      { letter: "C", text: "Cutting music programs to increase math instruction may be counterproductive" },
      { letter: "D", text: "Schools should prioritize music education over mathematics" },
      { letter: "E", text: "Pattern recognition is essential for mathematical thinking" },
    ],
    correctAnswer: "C",
    explanation: "The phrase 'may therefore be undermining' signals the main conclusion. The argument builds from evidence about music's cognitive benefits to conclude that eliminating music programs to boost math instruction may actually work against the goal of improving math performance.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-025",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Either we continue to rely on fossil fuels and face catastrophic climate change, or we immediately transition to 100% renewable energy. Since completely eliminating fossil fuels overnight is impossible given current technology and infrastructure, we have no choice but to accept the consequences of continued fossil fuel use.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "overstates the severity of climate change impacts" },
      { letter: "B", text: "presents a false dichotomy by ignoring intermediate options" },
      { letter: "C", text: "fails to consider the economic costs of transitioning to renewable energy" },
      { letter: "D", text: "assumes that current technology cannot be improved" },
      { letter: "E", text: "ignores the environmental impacts of renewable energy production" },
    ],
    correctAnswer: "B",
    explanation: "The argument presents only two extreme options: complete reliance on fossil fuels or immediate 100% transition to renewables. This is a false dichotomy because there are many intermediate possibilities, such as gradual transitions, hybrid approaches, carbon capture technology, or partial renewable adoption.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-026",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have found that ancient Mayan cities were abandoned suddenly around 900 CE. They hypothesize that prolonged drought caused agricultural failure, leading to social collapse. Analysis of lake sediments shows significantly reduced rainfall during this period.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologists' hypothesis?",
    answerChoices: [
      { letter: "A", text: "The Mayan writing system has been mostly deciphered by modern scholars" },
      { letter: "B", text: "Mayan agricultural practices were heavily dependent on consistent seasonal rainfall" },
      { letter: "C", text: "Some Mayan cities in coastal areas continued to be inhabited after 900 CE" },
      { letter: "D", text: "The Mayan civilization had survived previous periods of environmental stress" },
      { letter: "E", text: "Warfare between Mayan city-states increased during the 8th century CE" },
    ],
    correctAnswer: "B",
    explanation: "If Mayan agriculture was heavily dependent on consistent rainfall, then drought would have had a devastating impact on food production, making agricultural failure and social collapse much more likely. This strengthens the causal connection between drought and the abandonment of cities.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The university should eliminate its foreign language requirement for graduation. Students who want to learn languages will do so voluntarily, and those who are forced to study languages they don't want to learn rarely achieve meaningful proficiency anyway.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Most students do not want to study foreign languages" },
      { letter: "B", text: "The primary purpose of the language requirement is to produce proficient speakers" },
      { letter: "C", text: "Students are the best judges of which subjects will benefit them" },
      { letter: "D", text: "Universities should not have any graduation requirements" },
      { letter: "E", text: "Voluntary language study produces better outcomes than required study" },
    ],
    correctAnswer: "B",
    explanation: "The argument against the requirement is based on students not achieving 'meaningful proficiency.' This assumes that proficiency is the main goal of the requirement. However, language requirements might serve other purposes (exposure to other cultures, cognitive benefits, global awareness) that don't require full proficiency.",
    difficulty: "hard",
  },
  {
    id: "lr-bank31-028",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `People often claim that money cannot buy happiness. However, studies consistently show that people in wealthier countries report higher levels of life satisfaction than those in poorer countries. Within countries, those with higher incomes generally report greater well-being than those with lower incomes. The evidence clearly contradicts the popular saying.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "showing that a widely held belief is contradicted by empirical evidence" },
      { letter: "B", text: "demonstrating that a conclusion follows logically from its premises" },
      { letter: "C", text: "identifying an ambiguity in a key term used in the discussion" },
      { letter: "D", text: "appealing to expert authority to support its conclusion" },
      { letter: "E", text: "using an analogy to illustrate a complex relationship" },
    ],
    correctAnswer: "A",
    explanation: "The argument takes a common belief ('money cannot buy happiness') and challenges it by presenting empirical research findings about wealth and life satisfaction. It uses evidence from studies to contradict the popular saying.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-029",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Adams: Universities should prioritize practical job training because the primary purpose of higher education is to prepare students for successful careers. Students and their families invest significant resources in education and deserve a tangible return on that investment.

Professor Baker: While career preparation is important, universities should primarily focus on developing critical thinking and broad knowledge. The purpose of higher education is to create informed citizens and lifelong learners, not merely to train workers for specific jobs.`,
    questionStem: "The main point of disagreement between Professor Adams and Professor Baker concerns",
    answerChoices: [
      { letter: "A", text: "whether career preparation has any role in higher education" },
      { letter: "B", text: "whether students invest significant resources in their education" },
      { letter: "C", text: "what the primary purpose of higher education should be" },
      { letter: "D", text: "whether critical thinking is a valuable skill" },
      { letter: "E", text: "whether universities are currently meeting student needs" },
    ],
    correctAnswer: "C",
    explanation: "Both professors are debating what universities should primarily focus on. Adams says career preparation is the primary purpose, while Baker says developing critical thinking and informed citizenship is primary. Their disagreement is fundamentally about the central purpose of higher education.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-030",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The CEO announced that the company's employee wellness program has been a great success. She noted that since implementing the program two years ago, average employee sick days have decreased by 25 percent. This reduction, she argued, demonstrates that the wellness initiatives have made employees healthier.`,
    questionStem: "Which one of the following, if true, most seriously weakens the CEO's argument?",
    answerChoices: [
      { letter: "A", text: "The company offers generous paid time off in addition to sick days" },
      { letter: "B", text: "Similar wellness programs at other companies have produced mixed results" },
      { letter: "C", text: "Two years ago, the company also changed its sick leave policy to be less generous" },
      { letter: "D", text: "Some employees have complained that wellness program activities take time away from work" },
      { letter: "E", text: "The wellness program includes both physical fitness and mental health components" },
    ],
    correctAnswer: "C",
    explanation: "If the company changed its sick leave policy to be less generous at the same time as implementing the wellness program, the reduction in sick days might be due to employees being less willing to use sick leave rather than actually being healthier. This alternative explanation weakens the claim that the wellness program caused the improvement.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ninety percent of convicted criminals report having consumed alcohol at some point in their lives. This statistic clearly shows that alcohol consumption is a major contributing factor to criminal behavior. To reduce crime rates, we should therefore implement stricter alcohol regulations.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that correlation does not imply causation" },
      { letter: "B", text: "relies on a statistic that likely applies to the general population as well, not just criminals" },
      { letter: "C", text: "does not specify what types of crimes were committed" },
      { letter: "D", text: "ignores the possibility that some criminals abstain from alcohol" },
      { letter: "E", text: "assumes that all alcohol consumption leads to criminal behavior" },
    ],
    correctAnswer: "B",
    explanation: "The argument's key flaw is that almost everyone in the general population has consumed alcohol at some point. If 90% of non-criminals have also consumed alcohol, then the statistic about criminals is meaningless for establishing a connection between alcohol and crime. The comparison group is missing.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Conservation biologists argue that creating wildlife corridors between fragmented habitats is essential for maintaining genetic diversity in endangered species. Without these corridors, isolated populations cannot interbreed, leading to inbreeding depression and eventual extinction.`,
    questionStem: "Which one of the following, if true, most strengthens the biologists' argument?",
    answerChoices: [
      { letter: "A", text: "Some endangered species have very specific habitat requirements that cannot be met by corridors" },
      { letter: "B", text: "Wildlife corridors can also benefit plant species by allowing seed dispersal" },
      { letter: "C", text: "Studies of isolated populations show significantly lower genetic diversity and higher rates of birth defects" },
      { letter: "D", text: "Creating wildlife corridors requires cooperation between multiple landowners" },
      { letter: "E", text: "Some species have successfully recovered without the use of wildlife corridors" },
    ],
    correctAnswer: "C",
    explanation: "Evidence showing that isolated populations actually do suffer from lower genetic diversity and higher birth defects directly supports the biologists' claim about the negative effects of habitat fragmentation. This empirical support strengthens the argument for wildlife corridors.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city council voted to ban single-use plastic bags at grocery stores. Council members argued that this will significantly reduce plastic pollution in local waterways. They pointed to successful bag bans in other cities as evidence that the policy will work.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Grocery store plastic bags are a significant source of plastic pollution in local waterways" },
      { letter: "B", text: "Other cities that banned plastic bags are similar to this city in relevant ways" },
      { letter: "C", text: "Consumers will not simply switch to other single-use bags" },
      { letter: "D", text: "Plastic pollution is the most serious environmental problem facing the city" },
      { letter: "E", text: "The council has the authority to regulate plastic bag usage" },
    ],
    correctAnswer: "A",
    explanation: "For the bag ban to significantly reduce plastic pollution, grocery bags must be a significant source of that pollution. If plastic bags constitute only a tiny fraction of plastic pollution, banning them would not produce significant results, regardless of success in other cities.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-034",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All great artists have faced rejection at some point in their careers. Therefore, if someone has never faced rejection, that person is not a great artist.`,
    questionStem: "The pattern of reasoning in the argument is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All championship teams have talented players. This team has talented players. Therefore, this team will win the championship." },
      { letter: "B", text: "All mammals are warm-blooded. This animal is not warm-blooded. Therefore, this animal is not a mammal." },
      { letter: "C", text: "Some successful businesses take risks. This business takes risks. Therefore, this business might be successful." },
      { letter: "D", text: "All doctors have medical degrees. Dr. Johnson has a medical degree. Therefore, Dr. Johnson is a doctor." },
      { letter: "E", text: "Most athletes train regularly. This person trains regularly. Therefore, this person is probably an athlete." },
    ],
    correctAnswer: "B",
    explanation: "The original argument uses modus tollens: All great artists faced rejection (All A are B). No rejection (Not B). Therefore, not a great artist (Not A). Answer B has the same valid logical structure: All mammals are warm-blooded (All A are B). Not warm-blooded (Not B). Therefore, not a mammal (Not A).",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-035",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The proposed tax on sugary beverages will not reduce obesity rates. Look at what happened when the city implemented a plastic bag fee—people simply paid the fee and continued using plastic bags. Similarly, consumers will just pay the sugar tax and keep buying the same drinks they always have.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that all consumer behaviors respond identically to price increases" },
      { letter: "B", text: "ignores the possibility that the sugar tax might be higher than the plastic bag fee" },
      { letter: "C", text: "fails to consider that the purposes of the two policies are different" },
      { letter: "D", text: "relies on an analogy between two situations that may not be sufficiently similar" },
      { letter: "E", text: "presumes that reducing obesity is the only goal of the sugar tax" },
    ],
    correctAnswer: "D",
    explanation: "The argument assumes that consumer behavior toward sugary drinks will mirror behavior toward plastic bags. However, these situations may differ significantly—sugary drinks are consumables with health impacts, substitutes are readily available, consumption patterns differ from bag usage, and the tax amounts may differ. The analogy may not hold.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-036",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A technology company claims that its facial recognition software is unbiased because it was trained on a diverse dataset containing faces of people from many different demographic groups. The company argues that this diversity in training data ensures the software will perform equally well for all users.`,
    questionStem: "Which one of the following, if true, most seriously weakens the company's argument?",
    answerChoices: [
      { letter: "A", text: "The software has been adopted by several law enforcement agencies" },
      { letter: "B", text: "Other facial recognition systems have been shown to have demographic biases" },
      { letter: "C", text: "The training dataset, while diverse, contained significantly fewer examples of some demographic groups than others" },
      { letter: "D", text: "Facial recognition technology has improved rapidly in recent years" },
      { letter: "E", text: "Some users have raised privacy concerns about facial recognition technology" },
    ],
    correctAnswer: "C",
    explanation: "If the 'diverse' dataset was actually imbalanced—with far fewer examples of some groups—the software might still perform poorly for underrepresented groups despite the claimed diversity. This directly challenges the assumption that diversity in training data ensures equal performance.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-037",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Pediatricians recommend that children spend at least one hour per day in outdoor play. They argue that outdoor play promotes physical health, reduces obesity risk, and improves mental well-being. Unfortunately, surveys indicate that the average child today spends less than 30 minutes daily in outdoor activities.`,
    questionStem: "Which one of the following, if true, provides the most support for the pediatricians' recommendation?",
    answerChoices: [
      { letter: "A", text: "Children who spend more time outdoors have lower rates of myopia than those who spend most of their time indoors" },
      { letter: "B", text: "Many parents are concerned about safety issues related to unsupervised outdoor play" },
      { letter: "C", text: "Schools have reduced recess time in favor of additional academic instruction" },
      { letter: "D", text: "Indoor exercise can provide many of the same physical benefits as outdoor play" },
      { letter: "E", text: "Screen time has increased significantly for children over the past two decades" },
    ],
    correctAnswer: "A",
    explanation: "Evidence that outdoor time has additional health benefits (reducing myopia) strengthens the pediatricians' recommendation for outdoor play specifically. This shows that outdoor play provides benefits beyond just physical exercise, which could be obtained indoors.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-038",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some argue that standardized testing should be eliminated because it causes student stress. But if we eliminated every practice that causes stress, we would have to eliminate homework, grades, and even deadlines—all of which are essential components of education. Therefore, the fact that standardized testing causes stress is not sufficient reason to eliminate it.`,
    questionStem: "The argument uses which one of the following techniques to reach its conclusion?",
    answerChoices: [
      { letter: "A", text: "Demonstrating that accepting the critics' principle would lead to unacceptable consequences" },
      { letter: "B", text: "Providing evidence that standardized testing does not actually cause stress" },
      { letter: "C", text: "Showing that student stress has other, more significant causes" },
      { letter: "D", text: "Questioning the expertise of those who criticize standardized testing" },
      { letter: "E", text: "Offering alternative methods for reducing student stress" },
    ],
    correctAnswer: "A",
    explanation: "The argument employs a reductio ad absurdum approach. It takes the critics' principle (eliminate practices that cause stress) and shows that applying it consistently would lead to eliminating homework, grades, and deadlines—consequences that would be unacceptable. This undermines the principle without disputing that testing causes stress.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-039",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The new building code requires all residential construction to include solar panels. This requirement will increase housing costs, which will reduce housing affordability. The city council should therefore reject the new building code to protect affordable housing options for residents.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Solar panels do not provide any financial benefits that offset their initial cost" },
      { letter: "B", text: "Affordable housing is the city council's highest priority" },
      { letter: "C", text: "The building code would apply to all new residential construction without exception" },
      { letter: "D", text: "Housing costs have not increased due to other building code requirements" },
      { letter: "E", text: "Other cities with similar solar requirements have seen reduced housing affordability" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that solar panels only add costs without offsetting benefits. However, solar panels reduce electricity costs over time and may increase property values. If these savings and benefits offset the initial cost, the net impact on affordability might be neutral or positive.",
    difficulty: "hard",
  },
  {
    id: "lr-bank31-040",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `My grandmother smoked cigarettes for sixty years and lived to be ninety-five. Therefore, the health risks of smoking must be greatly exaggerated by medical researchers.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "relies on anecdotal evidence from a single case to challenge well-established statistical findings" },
      { letter: "B", text: "assumes that all smokers have the same health outcomes" },
      { letter: "C", text: "fails to consider that the grandmother might have been even healthier without smoking" },
      { letter: "D", text: "ignores the possibility that medical research methods have improved over time" },
      { letter: "E", text: "presumes that longevity is the only measure of health" },
    ],
    correctAnswer: "A",
    explanation: "The argument uses a single anecdote to challenge statistical evidence about health risks. Statistical claims about smoking risks are based on population-level data showing increased probability of harm, not claims that every single smoker will die young. Individual exceptions do not disprove statistical trends.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-041",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The government should not subsidize the arts because true art thrives without official support. Throughout history, the greatest artists have created their masterpieces despite financial hardship, not because of government grants.

Arts Administrator: Government arts funding is essential because it allows artists to focus on their work without financial stress. When artists don't have to worry about paying rent, they can take creative risks and produce more innovative work.`,
    questionStem: "The critic and the arts administrator most clearly disagree about whether",
    answerChoices: [
      { letter: "A", text: "great art has been produced throughout history" },
      { letter: "B", text: "financial support from the government enables artists to create better work" },
      { letter: "C", text: "artists experience financial difficulties" },
      { letter: "D", text: "government has a role in supporting other sectors of society" },
      { letter: "E", text: "some artists have produced masterpieces despite financial hardship" },
    ],
    correctAnswer: "B",
    explanation: "The critic argues that great art is created despite financial hardship (implying government funding isn't necessary or helpful), while the administrator argues that funding enables better, more innovative work. They directly disagree about whether government financial support helps artists create better art.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-042",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The school district is implementing a new reading curriculum that emphasizes phonics instruction. Officials argue this will improve reading outcomes because research shows that systematic phonics instruction is the most effective method for teaching children to read.`,
    questionStem: "Which one of the following, if true, most seriously weakens the officials' argument?",
    answerChoices: [
      { letter: "A", text: "Some children learn to read before receiving any formal instruction" },
      { letter: "B", text: "The research supporting phonics instruction was conducted in schools with significantly smaller class sizes than those in this district" },
      { letter: "C", text: "Phonics instruction has been used in education for over a century" },
      { letter: "D", text: "The new curriculum was developed by a well-respected educational publishing company" },
      { letter: "E", text: "Teachers in the district have expressed enthusiasm for the new curriculum" },
    ],
    correctAnswer: "B",
    explanation: "If the research supporting phonics was conducted in schools with much smaller classes, the findings may not apply to this district with larger classes. The effectiveness of phonics instruction might depend on individual attention that smaller classes can provide but larger classes cannot.",
    difficulty: "hard",
  },
  {
    id: "lr-bank31-043",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Astronomers have detected an unusual pattern of dimming in the light from a distant star. They hypothesize that this pattern is caused by an orbiting planet with multiple moons. The irregular dimming would occur as the planet and its various moons pass between the star and Earth at different times.`,
    questionStem: "Which one of the following, if true, most strengthens the astronomers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Many stars are known to have orbiting planets" },
      { letter: "B", text: "The dimming pattern repeats at regular intervals consistent with an orbital period" },
      { letter: "C", text: "Other explanations for unusual stellar dimming have been proposed by astronomers" },
      { letter: "D", text: "The star is similar in size and age to our sun" },
      { letter: "E", text: "No planets have been directly imaged around this star" },
    ],
    correctAnswer: "B",
    explanation: "If the dimming repeats at regular intervals suggesting an orbital period, this strongly supports the hypothesis of an orbiting planet. Orbiting objects would produce predictable, periodic dimming patterns, which is exactly what we would expect if the hypothesis is correct.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-044",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the debate team are either seniors or juniors. No freshman is a member of the debate team. Some members of the debate team are also on the speech team. All students on the speech team must maintain a minimum GPA of 3.5.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All seniors on the debate team are also on the speech team" },
      { letter: "B", text: "Some students who must maintain a minimum GPA of 3.5 are seniors or juniors" },
      { letter: "C", text: "No member of the speech team is a freshman" },
      { letter: "D", text: "All juniors are members of the debate team" },
      { letter: "E", text: "Some students on the speech team are not on the debate team" },
    ],
    correctAnswer: "B",
    explanation: "Some debate team members are on the speech team, and all speech team members must maintain a 3.5 GPA. All debate team members are seniors or juniors. Therefore, those debate team members who are also on speech team are seniors or juniors who must maintain a 3.5 GPA. So some students with the GPA requirement must be seniors or juniors.",
    difficulty: "hard",
  },
  {
    id: "lr-bank31-045",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The proposed legislation to increase penalties for white-collar crime has been endorsed by the Association of Corporate Executives. Since this organization represents the very people who commit white-collar crimes, their endorsement proves that the legislation must be ineffective at deterring such crimes. If it were truly effective, they would oppose it.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that all corporate executives engage in white-collar crime" },
      { letter: "B", text: "fails to consider that the organization might support the legislation for reasons other than its ineffectiveness" },
      { letter: "C", text: "ignores the possibility that the legislation could be modified before passage" },
      { letter: "D", text: "relies on an appeal to authority rather than addressing the merits of the legislation" },
      { letter: "E", text: "presumes that harsher penalties always lead to greater deterrence" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes the only reason the executives would endorse the legislation is if it's ineffective. However, they might support it for other reasons: improving their industry's reputation, believing most members are honest and wouldn't be affected, or genuinely wanting to deter crime among bad actors in their industry.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some scientists believe that consciousness can be fully explained by brain activity. But explaining how something works is not the same as explaining why it exists. Even a complete understanding of the neural correlates of consciousness would not tell us why consciousness exists at all. Therefore, science alone cannot fully explain consciousness.`,
    questionStem: "The pattern of reasoning in this argument is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some people believe that money is the key to happiness. But having money is not the same as knowing how to use it wisely. Even great wealth cannot guarantee happiness. Therefore, money alone cannot ensure happiness." },
      { letter: "B", text: "Some economists believe that market forces can solve all social problems. But solving a problem is not the same as preventing it from recurring. Even perfect markets cannot prevent all future problems. Therefore, markets alone cannot address all social issues." },
      { letter: "C", text: "Some historians believe that great leaders shape history. But shaping events is not the same as causing them. Even powerful leaders operate within historical constraints. Therefore, leadership alone cannot explain historical change." },
      { letter: "D", text: "Some engineers believe that any problem can be solved with better technology. But solving a technical problem is not the same as addressing its underlying causes. Even the best technology cannot fix problems rooted in human behavior. Therefore, technology alone cannot solve all problems." },
      { letter: "E", text: "Some biologists believe that genes determine all traits. But explaining inheritance is not the same as explaining development. Even complete genetic knowledge cannot explain how organisms develop. Therefore, genetics alone cannot explain living organisms." },
    ],
    correctAnswer: "D",
    explanation: "Both arguments have the structure: X can explain aspect A, but explaining A is not the same as explaining aspect B. Even complete knowledge of A would not address B. Therefore, X alone cannot fully explain the phenomenon. Answer D follows this same pattern regarding technology and problem-solving.",
    difficulty: "hard",
  },
  {
    id: "lr-bank31-047",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `A new study found that employees who work from home report higher job satisfaction than those who work in traditional offices. The study's authors conclude that companies should allow remote work to improve employee well-being and productivity.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Higher job satisfaction leads to increased productivity" },
      { letter: "B", text: "Employees who prefer remote work are more likely to participate in surveys about work satisfaction" },
      { letter: "C", text: "Remote work would lead to higher job satisfaction for employees who currently work in offices" },
      { letter: "D", text: "All employees have the resources necessary for remote work" },
      { letter: "E", text: "Traditional office environments are inherently stressful" },
    ],
    correctAnswer: "C",
    explanation: "The study shows that current remote workers have higher satisfaction, but the conclusion recommends allowing remote work for office workers. This assumes that office workers would experience the same satisfaction boost if allowed to work remotely. However, current remote workers may have self-selected for roles that suit remote work.",
    difficulty: "hard",
  },
  {
    id: "lr-bank31-048",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The museum curator argues that the recently discovered painting is an authentic work by Rembrandt. She points out that the painting uses techniques and materials consistent with those used by Rembrandt, and that the subject matter is typical of his work from that period.`,
    questionStem: "Which one of the following, if true, most seriously weakens the curator's argument?",
    answerChoices: [
      { letter: "A", text: "Some of Rembrandt's known works have been controversial among art historians" },
      { letter: "B", text: "Rembrandt had several students who learned to paint using his exact techniques and materials" },
      { letter: "C", text: "The painting was found in a private collection that included works by various artists" },
      { letter: "D", text: "Modern technology has improved the ability to authenticate paintings" },
      { letter: "E", text: "Rembrandt is known to have produced hundreds of paintings during his career" },
    ],
    correctAnswer: "B",
    explanation: "If Rembrandt's students painted using his exact techniques and materials, then the features the curator cites as evidence of authenticity could equally well indicate a painting by one of his students. This alternative explanation significantly weakens the claim that the painting must be by Rembrandt himself.",
    difficulty: "medium",
  },
  {
    id: "lr-bank31-049",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Exercise is known to release endorphins that improve mood. Regular physical activity has also been shown to reduce symptoms of anxiety and depression. Given these benefits, physicians should consider prescribing exercise as a first-line treatment for mild mental health conditions before resorting to medication, which often carries significant side effects.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Exercise releases endorphins that improve mood" },
      { letter: "B", text: "Regular physical activity reduces anxiety and depression symptoms" },
      { letter: "C", text: "Medications for mental health conditions have significant side effects" },
      { letter: "D", text: "Physicians should prescribe exercise before medication for mild mental health conditions" },
      { letter: "E", text: "Exercise has numerous physical and mental health benefits" },
    ],
    correctAnswer: "D",
    explanation: "The argument provides premises about exercise's mood benefits and medication's side effects to support the recommendation that physicians should prescribe exercise as a first-line treatment before medication. This recommendation is the main conclusion being argued for.",
    difficulty: "easy",
  },
  {
    id: "lr-bank31-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Several prominent economists have publicly supported the new trade agreement. Therefore, the agreement must be economically beneficial. Critics who raise concerns about job losses and wage stagnation are simply failing to understand the complex economic principles involved.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to specify how many economists support the agreement" },
      { letter: "B", text: "dismisses opposing views by questioning the critics' expertise rather than addressing their specific concerns" },
      { letter: "C", text: "assumes that what prominent people believe must be correct" },
      { letter: "D", text: "ignores the possibility that economists can disagree among themselves" },
      { letter: "E", text: "presumes that economic benefit is the only relevant consideration" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits an ad hominem fallacy by dismissing critics' concerns about job losses and wage stagnation as merely failing to understand economics, rather than actually addressing these specific concerns. Even if economists support the agreement, the critics' points about jobs and wages deserve substantive responses.",
    difficulty: "medium",
  },
];
