// Logical Reasoning Questions Bank - Set 57
import { Question } from "../lsat-types";

export const lrQuestionsSet57: Question[] = [
  {
    id: "lr-bank57-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during the workday are more productive than those who work continuously. Therefore, companies should mandate that all employees take breaks every hour, as this will certainly increase overall productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that productivity might be measured in different ways" },
      { letter: "B", text: "assumes that what is true of voluntary behavior will be equally effective when mandated" },
      { letter: "C", text: "overlooks the possibility that some employees already take regular breaks" },
      { letter: "D", text: "relies on a study without specifying its methodology" },
      { letter: "E", text: "confuses correlation between two factors with a causal relationship" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that mandating breaks will have the same positive effect as employees voluntarily choosing to take breaks. However, the study only showed that employees who choose to take breaks are more productive; it did not establish that forcing breaks on employees would yield the same results.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archeologists discovered that an ancient civilization abandoned their coastal city approximately 3,000 years ago. Geological evidence shows that a massive tsunami struck the region around the same time. The archeologists concluded that the tsunami was the primary cause of the city's abandonment.`,
    questionStem: "Which one of the following, if true, most strengthens the archeologists' conclusion?",
    answerChoices: [
      { letter: "A", text: "Other coastal cities in the region were also abandoned around the same time" },
      { letter: "B", text: "The city had survived several smaller tsunamis in the centuries before its abandonment" },
      { letter: "C", text: "Excavations revealed that the city's food storage facilities and temples were destroyed by water damage consistent with a tsunami" },
      { letter: "D", text: "The civilization had the technological capability to rebuild structures damaged by natural disasters" },
      { letter: "E", text: "Written records from neighboring civilizations mention the city's prosperous trade before its abandonment" },
    ],
    correctAnswer: "C",
    explanation: "Evidence that the city's essential infrastructure was destroyed specifically by water damage consistent with a tsunami directly supports the conclusion that the tsunami caused the abandonment. This provides a clear causal mechanism linking the tsunami to the abandonment.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that building a new sports stadium downtown will revitalize the area economically. They point to Greenfield City, which built a stadium five years ago and has since seen significant economic growth in its downtown area. Thus, the council concludes that a new stadium here will produce similar economic benefits.`,
    questionStem: "Which one of the following, if true, most seriously weakens the city council's argument?",
    answerChoices: [
      { letter: "A", text: "The proposed stadium would cost more to build than the one in Greenfield City" },
      { letter: "B", text: "Greenfield City's economic growth began before the stadium was built, driven by a new technology sector" },
      { letter: "C", text: "Some residents oppose the stadium because of increased traffic concerns" },
      { letter: "D", text: "The city council has successfully completed other major construction projects" },
      { letter: "E", text: "Greenfield City's stadium hosts more events annually than the proposed stadium would" },
    ],
    correctAnswer: "B",
    explanation: "If Greenfield City's economic growth was already occurring before the stadium was built and was driven by an unrelated factor (the technology sector), then the stadium may not have caused the growth. This undermines the analogy the council is drawing and weakens the argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All successful entrepreneurs possess exceptional risk tolerance. Maria has started three businesses, each of which has been profitable for over a decade. Therefore, Maria must have exceptional risk tolerance.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Anyone who starts multiple businesses is an entrepreneur" },
      { letter: "B", text: "Profitability is a sufficient indicator of business success" },
      { letter: "C", text: "Exceptional risk tolerance is the only trait shared by all successful entrepreneurs" },
      { letter: "D", text: "Maria's businesses were riskier than typical business ventures" },
      { letter: "E", text: "Risk tolerance can be developed through experience" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that Maria is a successful entrepreneur because her businesses have been profitable. This requires assuming that profitability is sufficient to establish that someone is a successful entrepreneur, which then allows the application of the premise about successful entrepreneurs having exceptional risk tolerance.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Medical researchers have found that patients who maintain strong social connections recover faster from surgery than isolated patients. Hospitals have begun implementing visitor-friendly policies and group recovery programs. While these changes require additional resources, the reduction in average hospital stay length more than compensates for the increased costs. Clearly, hospitals benefit financially from promoting social connection among patients.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Patients with strong social connections recover faster from surgery" },
      { letter: "B", text: "Hospitals have implemented visitor-friendly policies and group recovery programs" },
      { letter: "C", text: "The reduction in hospital stay length compensates for increased program costs" },
      { letter: "D", text: "Hospitals derive financial benefits from encouraging social connection among patients" },
      { letter: "E", text: "Additional resources are required to implement social connection programs" },
    ],
    correctAnswer: "D",
    explanation: "The phrase 'Clearly' signals the main conclusion. The argument builds from evidence about faster recovery times and cost savings to conclude that hospitals benefit financially from promoting social connections. The other statements are premises supporting this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that because computers can perform calculations faster than humans, computers are more intelligent than humans. But this reasoning is flawed. After all, calculators can perform calculations faster than computers, yet no one would claim that calculators are more intelligent than computers. Speed of calculation alone does not determine intelligence.`,
    questionStem: "The philosopher's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "demonstrating that the opposing argument leads to an absurd conclusion" },
      { letter: "B", text: "providing a counterexample that applies the same logic to reveal its weakness" },
      { letter: "C", text: "questioning the definition of intelligence used by the opposing argument" },
      { letter: "D", text: "showing that the premises of the opposing argument are factually incorrect" },
      { letter: "E", text: "arguing that computers and calculators are fundamentally similar" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher uses the example of calculators being faster than computers to show that if speed determined intelligence, we would have to conclude calculators are more intelligent than computers. Since this conclusion is clearly rejected, the reasoning that speed determines intelligence must be flawed. This is a parallel counterexample.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Editorial: The governor claims that the new education bill will improve student outcomes because it increases funding for schools. However, the governor accepted significant campaign contributions from the teachers' union, which would benefit from increased education spending. Therefore, the governor's claim that the bill will improve student outcomes should not be believed.`,
    questionStem: "The reasoning in the editorial is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "presumes that all campaign contributions influence political decisions" },
      { letter: "B", text: "rejects a claim based on the source of the claim rather than its merits" },
      { letter: "C", text: "assumes that teachers' unions only support policies that benefit their members" },
      { letter: "D", text: "fails to consider whether increased funding could benefit both teachers and students" },
      { letter: "E", text: "overlooks evidence that increased funding has improved outcomes in other states" },
    ],
    correctAnswer: "B",
    explanation: "The editorial commits an ad hominem fallacy by attacking the governor's motives (accepting union contributions) rather than addressing whether the claim about improved student outcomes is actually true. The source's potential bias does not prove the claim is false.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying a rare bird species found that birds living near urban areas had significantly brighter plumage than those in remote forests. The researchers hypothesized that the urban birds developed brighter plumage as a response to the increased visual noise in urban environments, which made it harder for potential mates to notice them.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Urban birds also tend to sing more loudly than their forest counterparts" },
      { letter: "B", text: "The diet available to urban birds contains more carotenoids, which contribute to plumage brightness" },
      { letter: "C", text: "Female birds of this species have been shown to prefer brighter males in both environments" },
      { letter: "D", text: "The urban birds descended from forest populations that relocated within the last fifty years" },
      { letter: "E", text: "Brighter plumage is associated with better overall health in this species" },
    ],
    correctAnswer: "D",
    explanation: "If urban birds descended from forest populations that only recently relocated, then the difference in plumage must have developed quickly in response to the new urban environment rather than being an inherent trait. This supports the hypothesis that the change was an adaptive response to urban conditions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-009",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Mandatory minimum sentencing laws should be abolished. These laws remove judicial discretion and often result in punishments that are disproportionate to the crimes committed. Studies show that states without mandatory minimums have lower recidivism rates, proving that more flexible sentencing is more effective at reducing crime.`,
    questionStem: "Which one of the following, if true, most weakens the legal scholar's argument?",
    answerChoices: [
      { letter: "A", text: "Mandatory minimum sentences were originally enacted to ensure consistency in sentencing across different judges" },
      { letter: "B", text: "States without mandatory minimums also have significantly different approaches to rehabilitation and parole" },
      { letter: "C", text: "Some judges have criticized mandatory minimums as limiting their ability to consider individual circumstances" },
      { letter: "D", text: "The length of mandatory minimum sentences varies considerably from state to state" },
      { letter: "E", text: "Recidivism rates are calculated differently across different jurisdictions" },
    ],
    correctAnswer: "B",
    explanation: "If states without mandatory minimums also differ in other ways (rehabilitation programs, parole practices), then the lower recidivism rates might be caused by these other factors rather than the absence of mandatory minimums. This alternative explanation weakens the claim that flexible sentencing is more effective.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-010",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Philosophy professor: My students who regularly attend office hours consistently perform better on exams than those who do not. Clearly, attending office hours improves exam performance. I strongly encourage all students to take advantage of office hours.`,
    questionStem: "The professor's reasoning depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "all students have equal access to office hours" },
      { letter: "B", text: "exam performance is the best measure of learning" },
      { letter: "C", text: "students who attend office hours are not already more likely to perform well for other reasons" },
      { letter: "D", text: "the professor provides the same quality of assistance to all students who attend" },
      { letter: "E", text: "office hours attendance correlates with class attendance" },
    ],
    correctAnswer: "C",
    explanation: "The professor assumes a causal relationship between office hours and performance. However, this could be a selection effect: students who attend office hours might be more motivated or studious, which independently causes better performance. The argument assumes this alternative explanation is not the case.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-011",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Marcus: Artificial intelligence will eventually replace most human jobs, leading to widespread unemployment and social instability. We must begin preparing now by implementing universal basic income and retraining programs.

    Sophia: While AI will certainly change the job market, history shows that technological advances create new jobs even as they eliminate old ones. The automobile industry eliminated horse-related jobs but created millions more. We should focus on education that develops adaptable skills rather than assuming mass unemployment.`,
    questionStem: "Marcus and Sophia disagree about whether",
    answerChoices: [
      { letter: "A", text: "artificial intelligence will change the job market" },
      { letter: "B", text: "education and training programs are important responses to technological change" },
      { letter: "C", text: "AI will ultimately cause a net loss of jobs for human workers" },
      { letter: "D", text: "the automobile industry created jobs while eliminating others" },
      { letter: "E", text: "technological changes have historically affected employment" },
    ],
    correctAnswer: "C",
    explanation: "Marcus believes AI will lead to widespread unemployment (net job loss), while Sophia believes new jobs will be created to offset eliminated ones (no net loss). Both agree that AI will change the job market and that some response involving education is needed; they disagree on whether the net effect will be negative.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-012",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All licensed physicians have completed medical school. Some licensed physicians work in private practice. Therefore, some people who have completed medical school work in private practice.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "All roses are flowers. Some flowers are red. Therefore, some roses are red." },
      { letter: "B", text: "All senators are politicians. Some senators are lawyers. Therefore, some lawyers are politicians." },
      { letter: "C", text: "All dogs are mammals. All mammals are animals. Therefore, all dogs are animals." },
      { letter: "D", text: "Some teachers are patient. All patient people are kind. Therefore, some teachers are kind." },
      { letter: "E", text: "No reptiles are mammals. Some pets are mammals. Therefore, some pets are not reptiles." },
    ],
    correctAnswer: "B",
    explanation: "The original argument has the structure: All A are B. Some A are C. Therefore, some B are C. Choice B mirrors this exactly: All senators (A) are politicians (B). Some senators (A) are lawyers (C). Therefore, some lawyers (C) are politicians (B).",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-013",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `A company's employee handbook states that all employees must complete cybersecurity training within their first month of employment. It also states that employees who have not completed cybersecurity training are not permitted to access the company's internal database. Jennifer has been employed at the company for three months and regularly accesses the internal database for her work.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Jennifer completed cybersecurity training within her first month of employment" },
      { letter: "B", text: "The company strictly enforces its employee handbook policies" },
      { letter: "C", text: "Jennifer has completed cybersecurity training" },
      { letter: "D", text: "All employees who access the internal database have completed cybersecurity training within their first month" },
      { letter: "E", text: "Jennifer's job requires access to the internal database" },
    ],
    correctAnswer: "C",
    explanation: "Since employees who haven't completed cybersecurity training cannot access the database, and Jennifer accesses the database, she must have completed the training. However, we cannot be certain she completed it within her first month (she might have violated that requirement but eventually completed it), only that she has completed it.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-014",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: People who drink three or more cups of coffee daily have a 15% lower risk of developing type 2 diabetes compared to non-coffee drinkers. This clearly demonstrates that coffee consumption protects against diabetes. I recommend that my patients who don't currently drink coffee start doing so to reduce their diabetes risk.`,
    questionStem: "The reasoning in the nutritionist's argument is flawed because the argument",
    answerChoices: [
      { letter: "A", text: "fails to specify the type of coffee that provides protective benefits" },
      { letter: "B", text: "ignores the possibility that adding sugar to coffee could increase diabetes risk" },
      { letter: "C", text: "overlooks the possibility that coffee drinkers and non-drinkers differ in other relevant ways" },
      { letter: "D", text: "does not consider that some people may be allergic to coffee" },
      { letter: "E", text: "assumes that what is beneficial in large quantities is also beneficial in small quantities" },
    ],
    correctAnswer: "C",
    explanation: "The argument commits a correlation-causation fallacy. People who drink coffee may differ from non-drinkers in other ways (exercise habits, diet, socioeconomic status) that actually account for the lower diabetes risk. The study shows correlation, not that coffee itself causes the protective effect.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Business analyst: Our company should invest in renewable energy infrastructure. While the initial costs are high, energy prices have been rising steadily, and renewable sources will eventually cost less than fossil fuels. Companies that invest early will have a significant competitive advantage when fossil fuel prices become prohibitive.`,
    questionStem: "Which one of the following, if true, most strengthens the business analyst's argument?",
    answerChoices: [
      { letter: "A", text: "Several competing companies have already begun investing in renewable energy" },
      { letter: "B", text: "Government regulations are increasingly favoring renewable energy sources over fossil fuels" },
      { letter: "C", text: "The technology for renewable energy is still improving rapidly" },
      { letter: "D", text: "Current fossil fuel reserves are expected to last for at least another century" },
      { letter: "E", text: "The company has successfully implemented new technologies in the past" },
    ],
    correctAnswer: "B",
    explanation: "If government regulations increasingly favor renewables, this adds another reason why early investment would provide competitive advantage and supports the prediction that fossil fuels will become more costly (through regulation, not just supply). This strengthens the case for investing now.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-016",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Criminologist: Installing security cameras in public areas reduces crime. A study of twelve neighborhoods that installed cameras showed an average 30% reduction in reported crimes within two years. Therefore, cities should prioritize camera installation in high-crime areas to reduce criminal activity.`,
    questionStem: "Which one of the following, if true, most weakens the criminologist's argument?",
    answerChoices: [
      { letter: "A", text: "Some types of crime, such as online fraud, cannot be prevented by security cameras" },
      { letter: "B", text: "The neighborhoods in the study also implemented increased police patrols and better street lighting during the same period" },
      { letter: "C", text: "Security cameras require ongoing maintenance and monitoring costs" },
      { letter: "D", text: "Some residents object to security cameras on privacy grounds" },
      { letter: "E", text: "The study did not include neighborhoods that chose not to install cameras" },
    ],
    correctAnswer: "B",
    explanation: "If the neighborhoods also implemented other crime-prevention measures simultaneously, the reduction in crime cannot be attributed specifically to the cameras. The other measures might be responsible for some or all of the crime reduction, undermining the argument for prioritizing camera installation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-017",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Book critic: This novel cannot be considered great literature because it was written primarily for commercial success. The author has admitted in interviews that he wrote it with the mass market in mind, specifically targeting readers who enjoy fast-paced thrillers. Great literature requires artistic integrity that is incompatible with such commercial motivations.`,
    questionStem: "The critic's argument relies on the assumption that",
    answerChoices: [
      { letter: "A", text: "fast-paced thrillers cannot be examples of great literature" },
      { letter: "B", text: "authors should not consider their potential audience when writing" },
      { letter: "C", text: "commercial success and artistic integrity cannot coexist in the same work" },
      { letter: "D", text: "the author was being honest in the interviews about his motivations" },
      { letter: "E", text: "great literature must be difficult to read" },
    ],
    correctAnswer: "C",
    explanation: "The critic argues that writing for commercial success means lacking artistic integrity. This assumes these two things are mutually exclusive. However, it's possible for an author to write with both commercial and artistic goals, producing a work with mass appeal that also has artistic integrity.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-018",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some economists argue that raising the minimum wage will lead to job losses because employers will hire fewer workers. However, studies of past minimum wage increases have shown minimal impact on employment levels. Furthermore, higher wages increase consumer spending, which stimulates economic growth and can actually create jobs. The concern that minimum wage increases cause significant unemployment is therefore not supported by evidence.`,
    questionStem: "Which one of the following most accurately states the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Some economists believe minimum wage increases cause job losses" },
      { letter: "B", text: "Past minimum wage increases have had minimal impact on employment" },
      { letter: "C", text: "Higher wages lead to increased consumer spending" },
      { letter: "D", text: "The fear that raising minimum wage causes significant unemployment is unfounded" },
      { letter: "E", text: "Economic growth can create jobs" },
    ],
    correctAnswer: "D",
    explanation: "The word 'therefore' signals the conclusion. The argument presents evidence (studies showing minimal impact, economic growth effects) to conclude that concerns about unemployment from minimum wage increases are not supported by evidence. This is the main point being argued.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-019",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Attorney: The prosecution argues that my client must be guilty because he was seen near the crime scene. But the crime occurred in a busy shopping district where hundreds of people pass through daily. My client works in a store just two blocks away and walks through that area every day. If proximity to the crime scene indicated guilt, we would have hundreds of suspects. The prosecution's reasoning proves nothing.`,
    questionStem: "The attorney responds to the prosecution's argument by",
    answerChoices: [
      { letter: "A", text: "providing an alibi that places the client elsewhere during the crime" },
      { letter: "B", text: "demonstrating that the evidence applies too broadly to identify the client specifically" },
      { letter: "C", text: "questioning the reliability of witnesses who placed the client near the scene" },
      { letter: "D", text: "arguing that the prosecution has the burden of proof" },
      { letter: "E", text: "presenting evidence that someone else committed the crime" },
    ],
    correctAnswer: "B",
    explanation: "The attorney argues that being near the crime scene is too common an occurrence to be meaningful evidence. Many people are near that location regularly, so this evidence doesn't specifically implicate the client. The attorney shows that the evidence applies to too many people to prove anything about any one person.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-020",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Health official: We should ban the sale of sugary drinks in schools. Childhood obesity rates have increased dramatically over the past twenty years, and during this same period, the consumption of sugary drinks by children has also increased significantly. Clearly, sugary drinks are a major cause of childhood obesity.`,
    questionStem: "The health official's reasoning is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "fails to define what constitutes a 'sugary drink'" },
      { letter: "B", text: "assumes that a correlation between two trends establishes a causal relationship" },
      { letter: "C", text: "ignores the role of exercise in preventing obesity" },
      { letter: "D", text: "does not consider whether banning sugary drinks would be enforceable" },
      { letter: "E", text: "overlooks other nutritional factors that contribute to childhood health" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the classic correlation-causation fallacy. The fact that both obesity and sugary drink consumption have increased during the same period does not prove that one caused the other. Many other factors (screen time, decreased physical activity, portion sizes) have also changed during this period.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-021",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Ecologist: The decline in the local wolf population has caused an increase in deer populations, which in turn has led to overgrazing and significant damage to forest vegetation. Reintroducing wolves to the area would restore ecological balance by naturally controlling deer numbers and allowing vegetation to recover.`,
    questionStem: "Which one of the following, if true, most strengthens the ecologist's argument?",
    answerChoices: [
      { letter: "A", text: "Wolves have been successfully reintroduced in other regions with similar ecological conditions" },
      { letter: "B", text: "The local deer population is larger than the ecosystem can sustainably support" },
      { letter: "C", text: "In areas where wolves were reintroduced, deer changed their grazing patterns to avoid wolf territories, allowing vegetation recovery even before deer numbers decreased" },
      { letter: "D", text: "Some local farmers have expressed concern about wolves threatening their livestock" },
      { letter: "E", text: "Other predators in the area have been unable to control the deer population" },
    ],
    correctAnswer: "C",
    explanation: "This evidence shows that wolf reintroduction has multiple beneficial effects beyond just reducing deer numbers. Wolves also change deer behavior, which helps vegetation recover. This provides additional support for the claim that reintroduction would restore ecological balance.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Political commentator: The senator's approval ratings have dropped 15 points since she publicly supported the new tax legislation. This proves that voters strongly oppose the tax changes she is advocating.`,
    questionStem: "Which one of the following, if true, most weakens the commentator's conclusion?",
    answerChoices: [
      { letter: "A", text: "Other senators who supported the same legislation have not seen similar drops in approval ratings" },
      { letter: "B", text: "The senator made several controversial statements about immigration during the same period" },
      { letter: "C", text: "The tax legislation has received mixed reviews from economists" },
      { letter: "D", text: "Approval ratings often fluctuate based on factors unrelated to specific policy positions" },
      { letter: "E", text: "The senator's approval ratings were unusually high before the drop" },
    ],
    correctAnswer: "B",
    explanation: "If the senator made other controversial statements during the same period, the drop in approval ratings might be due to those statements rather than her tax position. This alternative explanation weakens the conclusion that the drop specifically reflects opposition to the tax changes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-023",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Corporate trainer: Employees who participate in our leadership development program become better managers. We should therefore require all employees who are promoted to management positions to complete the program, as this will ensure we have effective managers throughout the organization.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "The leadership development program is cost-effective" },
      { letter: "B", text: "Employees who are promoted to management want to become better managers" },
      { letter: "C", text: "The improvements gained from the program will translate into effective management performance" },
      { letter: "D", text: "No one can become an effective manager without completing the program" },
      { letter: "E", text: "Current managers who did not complete the program are ineffective" },
    ],
    correctAnswer: "C",
    explanation: "The argument moves from 'become better managers' to 'have effective managers.' This requires assuming that the improvements from the program actually result in effective management. Being 'better' could still mean 'not good enough,' so the argument assumes the improvement reaches the level of effectiveness.",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-024",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Chen: Clinical trials for new medications should prioritize speed to get life-saving treatments to patients as quickly as possible. The current approval process takes too long and costs lives that could be saved if treatments were available sooner.

    Dr. Patel: The current approval process exists to protect patients from harmful side effects that only become apparent through extensive testing. Rushing trials would put patients at risk of serious harm from inadequately tested medications.`,
    questionStem: "The main point at issue between Dr. Chen and Dr. Patel is",
    answerChoices: [
      { letter: "A", text: "whether clinical trials can identify all potential side effects" },
      { letter: "B", text: "whether some medications currently in development could save lives" },
      { letter: "C", text: "whether patient safety or treatment access should be prioritized in drug approval" },
      { letter: "D", text: "whether the current approval process is the fastest possible" },
      { letter: "E", text: "whether pharmaceutical companies should bear the cost of clinical trials" },
    ],
    correctAnswer: "C",
    explanation: "Dr. Chen prioritizes getting treatments to patients faster (access), while Dr. Patel prioritizes protecting patients from inadequately tested drugs (safety). They disagree about which value should take precedence in the drug approval process.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-025",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Hiring manager: Our company's most successful salespeople all played team sports in college. Therefore, when hiring new salespeople, we should give preference to candidates who participated in college athletics, as they are more likely to succeed in our sales department.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that success in sales can be accurately predicted" },
      { letter: "B", text: "ignores the possibility that current successful employees share other common traits" },
      { letter: "C", text: "fails to consider that the company may have historically preferred to hire athletes" },
      { letter: "D", text: "overlooks the possibility that college athletics interferes with academic performance" },
      { letter: "E", text: "presumes that team sports develop skills applicable to sales" },
    ],
    correctAnswer: "C",
    explanation: "If the company has historically preferred hiring athletes, then the fact that successful salespeople played team sports might simply reflect hiring bias rather than a genuine correlation between athletics and sales success. The observation would be circular: we hired athletes, so our successful employees are athletes.",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-026",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the city council approves the budget, the new community center will be built. The city council approved the budget. Therefore, the new community center will be built.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If it rains tomorrow, the outdoor concert will be canceled. It rained today. Therefore, the concert was canceled." },
      { letter: "B", text: "If a student passes the final exam, the student will graduate. Maria passed the final exam. Therefore, Maria will graduate." },
      { letter: "C", text: "If the train is late, passengers will miss their connections. Passengers missed their connections. Therefore, the train was late." },
      { letter: "D", text: "If the medication is effective, symptoms will improve within a week. Symptoms improved within a week. Therefore, the medication was effective." },
      { letter: "E", text: "If taxes are lowered, consumer spending will increase. Consumer spending has not increased. Therefore, taxes were not lowered." },
    ],
    correctAnswer: "B",
    explanation: "The original argument uses modus ponens: If P then Q; P; Therefore Q. Choice B has the identical structure: If passing (P) then graduating (Q); Maria passed (P); Therefore Maria will graduate (Q). The other choices involve different time frames, affirming the consequent, or denying the consequent.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-027",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the board of directors are shareholders. No shareholders are allowed to vote on executive compensation packages due to conflict of interest rules. The board of directors is responsible for approving executive compensation packages. Recently, the board failed to approve the CEO's proposed compensation package.`,
    questionStem: "If all of the statements above are true, which one of the following can be properly inferred?",
    answerChoices: [
      { letter: "A", text: "The CEO's compensation package was unreasonable" },
      { letter: "B", text: "Board members must rely on non-shareholders to make decisions about executive compensation" },
      { letter: "C", text: "No member of the board of directors voted on the CEO's compensation package" },
      { letter: "D", text: "The conflict of interest rules should be changed" },
      { letter: "E", text: "Some shareholders opposed the CEO's compensation package" },
    ],
    correctAnswer: "C",
    explanation: "All board members are shareholders, and shareholders cannot vote on executive compensation. Therefore, no board member could vote on the compensation package. The passage says the board is responsible for approving packages, but this seems to create a contradiction; nevertheless, we can infer that no board member voted.",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-028",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The newly discovered painting is almost certainly by Vermeer. The brushwork technique matches Vermeer's known works exactly, and the canvas material and pigments are consistent with those available in 17th-century Delft, where Vermeer worked.`,
    questionStem: "Which one of the following, if true, most strengthens the art historian's conclusion?",
    answerChoices: [
      { letter: "A", text: "Vermeer's technique was highly distinctive and unlike any other painter of his era" },
      { letter: "B", text: "Several previously undiscovered Vermeer paintings have been authenticated in the past decade" },
      { letter: "C", text: "The painting depicts a domestic scene, which was Vermeer's preferred subject matter" },
      { letter: "D", text: "Modern forgeries typically fail to replicate historical canvas materials accurately" },
      { letter: "E", text: "Vermeer produced relatively few paintings during his lifetime" },
    ],
    correctAnswer: "A",
    explanation: "If Vermeer's technique was unique and unlike any other painter's, then finding a painting with exactly matching brushwork strongly indicates it is by Vermeer, since no one else could have produced it. This eliminates the possibility that another artist with similar technique painted it.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-029",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Environmental agency: The decrease in butterfly populations in the region must be due to pesticide use by local farms. Agricultural pesticide use in the region has increased by 40% over the past decade, while butterfly populations have declined by 60% during the same period.`,
    questionStem: "Which one of the following, if true, most weakens the environmental agency's argument?",
    answerChoices: [
      { letter: "A", text: "Some butterfly species are more resistant to pesticides than others" },
      { letter: "B", text: "Butterfly populations in regions with minimal agricultural activity have declined at similar rates" },
      { letter: "C", text: "The pesticides used in the region are specifically designed to target crop pests, not butterflies" },
      { letter: "D", text: "Farmers in the region have started using organic farming methods on some fields" },
      { letter: "E", text: "Butterfly populations fluctuate naturally from year to year" },
    ],
    correctAnswer: "B",
    explanation: "If butterfly populations have declined similarly in areas without significant agricultural activity or pesticide use, then pesticides are unlikely to be the cause of the decline. Some other factor affecting butterflies broadly must be responsible, such as climate change or habitat loss.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Music producer: This band will never achieve mainstream success. Their music is too experimental, incorporating unconventional time signatures and atonal harmonies that general audiences find difficult to appreciate. Mainstream success requires music that appeals to broad audiences.`,
    questionStem: "The music producer's argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "experimental music cannot be commercially successful" },
      { letter: "B", text: "the band wants to achieve mainstream success" },
      { letter: "C", text: "the band will not change its musical style to be more accessible" },
      { letter: "D", text: "general audiences prefer simple time signatures and tonal harmonies" },
      { letter: "E", text: "mainstream success is the only meaningful measure of a band's achievement" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes the band will never achieve mainstream success based on their current experimental style. This assumes the band will continue making experimental music. If they might change to a more accessible style, the conclusion would not necessarily follow.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-031",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Biologist: Critics claim that evolution cannot produce complex structures like the eye because partial eyes would provide no survival advantage. But this ignores the many intermediate forms that exist in nature. Light-sensitive patches in some organisms enable them to detect shadows of predators. Cup-shaped eyes in other organisms allow directional light sensing. Each stage provides measurable survival benefits, demonstrating how complex eyes could evolve incrementally.`,
    questionStem: "The biologist's response to the critics proceeds by",
    answerChoices: [
      { letter: "A", text: "rejecting the critics' definition of 'complex structure'" },
      { letter: "B", text: "challenging the scientific credentials of the critics" },
      { letter: "C", text: "providing examples that undermine a key assumption of the critics' argument" },
      { letter: "D", text: "showing that the critics' conclusion contradicts established scientific principles" },
      { letter: "E", text: "arguing that the critics' reasoning leads to an absurd conclusion" },
    ],
    correctAnswer: "C",
    explanation: "The critics assume partial eyes provide no survival advantage. The biologist counters by providing examples of organisms with intermediate eye structures that do provide survival benefits. These examples directly contradict the critics' key assumption, thereby undermining their argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-032",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: The incumbent party will certainly win the upcoming election. In the past five elections, the party with the larger campaign fund has won. Current reports show the incumbent party has raised significantly more money than the opposition, so their victory is assured.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on a sample that may be too small to establish a reliable pattern" },
      { letter: "B", text: "assumes that past electoral patterns will continue indefinitely" },
      { letter: "C", text: "ignores the possibility that campaign funds can be used ineffectively" },
      { letter: "D", text: "fails to consider that voters may change their preferences before the election" },
      { letter: "E", text: "does not account for differences between local and national elections" },
    ],
    correctAnswer: "A",
    explanation: "Five elections is a very small sample size from which to draw a reliable general principle. Many factors influence elections, and a pattern holding over just five cases could easily be coincidental. The argument inappropriately treats this limited pattern as a certain predictor.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-033",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Anthropologist: The ancient settlement was likely a major trading hub. Excavations have revealed pottery styles from three distinct cultures, none of which originated locally. The settlement is also positioned at the intersection of two natural travel routes through the mountains.`,
    questionStem: "Which one of the following, if true, most strengthens the anthropologist's hypothesis?",
    answerChoices: [
      { letter: "A", text: "The settlement was occupied for over three hundred years" },
      { letter: "B", text: "Similar settlements in the region have yielded fewer artifacts from foreign cultures" },
      { letter: "C", text: "Weights and balance scales consistent with commercial trading were found at the site" },
      { letter: "D", text: "The pottery from different cultures shows stylistic influences on each other" },
      { letter: "E", text: "No written records from the settlement have been discovered" },
    ],
    correctAnswer: "C",
    explanation: "The discovery of weights and balance scales provides direct evidence of commercial trading activity, which is exactly what would be expected at a trading hub. This adds to the circumstantial evidence of foreign goods and strategic location.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-034",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Company executive: Our new employee wellness program has been a success. Since implementing the program six months ago, employee productivity has increased by 12%. This demonstrates that investing in employee health and well-being directly improves business outcomes.`,
    questionStem: "Which one of the following, if true, most seriously weakens the executive's argument?",
    answerChoices: [
      { letter: "A", text: "Some employees have not participated in the wellness program" },
      { letter: "B", text: "The company also upgraded its computer systems and software six months ago" },
      { letter: "C", text: "Employee satisfaction surveys show modest improvements since the program began" },
      { letter: "D", text: "The wellness program has reduced employee healthcare costs" },
      { letter: "E", text: "Similar programs at other companies have also improved productivity" },
    ],
    correctAnswer: "B",
    explanation: "If the company upgraded its technology at the same time, the productivity increase might be due to better tools rather than the wellness program. This alternative explanation undermines the claim that the wellness program caused the productivity improvement.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-035",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Literary critic: The novel lacks artistic merit because the author relied heavily on formulaic plot devices common in commercial fiction. True artistic achievement requires originality and innovation in storytelling technique.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Commercial fiction cannot have artistic merit" },
      { letter: "B", text: "Plot is the most important element of a novel" },
      { letter: "C", text: "Originality in plot structure is necessary for a novel to have artistic merit" },
      { letter: "D", text: "The author was consciously imitating commercial fiction" },
      { letter: "E", text: "Critics are the best judges of artistic merit" },
    ],
    correctAnswer: "C",
    explanation: "The critic argues that using formulaic plots means the novel lacks merit, and that artistic achievement requires originality. This assumes that originality specifically in plot (the basis of the criticism) is necessary for artistic merit, not just originality in some other aspect of the work.",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Urban planner: Mixed-use developments that combine residential, commercial, and recreational spaces reduce urban sprawl and commuting distances. They also create more vibrant communities where people can live, work, and socialize without relying on automobiles. Given the environmental and social benefits, zoning laws should be reformed to encourage mixed-use development rather than the strict separation of residential and commercial areas that currently prevails.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the urban planner's argument?",
    answerChoices: [
      { letter: "A", text: "Mixed-use developments reduce urban sprawl" },
      { letter: "B", text: "Current zoning laws separate residential and commercial areas" },
      { letter: "C", text: "Zoning regulations should be changed to promote mixed-use development" },
      { letter: "D", text: "Mixed-use developments reduce automobile dependence" },
      { letter: "E", text: "Mixed-use developments create vibrant communities" },
    ],
    correctAnswer: "C",
    explanation: "The urban planner presents various benefits of mixed-use developments as premises to support the conclusion that zoning laws should be reformed. The phrase 'should be reformed' signals a prescriptive conclusion that is being argued for based on the evidence presented.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-037",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Social media influencer: My followers trust my product recommendations because I only promote items I genuinely use and believe in. Last month I recommended a new skincare line, and sales increased by 200%. This proves that authentic endorsements are more effective than traditional advertising.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that followers' purchasing decisions were based solely on trust" },
      { letter: "B", text: "provides only a single example to support a general conclusion" },
      { letter: "C", text: "fails to establish that the endorsement was actually authentic" },
      { letter: "D", text: "does not compare the sales increase to what traditional advertising might achieve" },
      { letter: "E", text: "ignores the possibility that the product was already popular" },
    ],
    correctAnswer: "D",
    explanation: "The argument concludes that authentic endorsements are 'more effective' than traditional advertising but provides no comparison. A 200% sales increase sounds impressive but might be less than what a traditional advertising campaign could achieve. Without comparison data, the conclusion about relative effectiveness is unsupported.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-038",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No professional athletes are eligible for the amateur competition. Some Olympic hopefuls are professional athletes. Therefore, some Olympic hopefuls are not eligible for the amateur competition.`,
    questionStem: "The pattern of reasoning in the argument is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "No reptiles are mammals. Some pets are reptiles. Therefore, some pets are not mammals." },
      { letter: "B", text: "All birds have feathers. No mammals have feathers. Therefore, no birds are mammals." },
      { letter: "C", text: "Some doctors are researchers. All researchers have advanced degrees. Therefore, some doctors have advanced degrees." },
      { letter: "D", text: "No children are voters. All voters are citizens. Therefore, no children are citizens." },
      { letter: "E", text: "All lawyers passed the bar exam. Some legislators are lawyers. Therefore, all legislators passed the bar exam." },
    ],
    correctAnswer: "A",
    explanation: "The original argument has the structure: No A are B. Some C are A. Therefore, some C are not B. Choice A exactly mirrors this: No reptiles (A) are mammals (B). Some pets (C) are reptiles (A). Therefore, some pets (C) are not mammals (B).",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-039",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Universal basic income would not significantly reduce the incentive to work. Most people derive meaning and social connection from their jobs, not just income. Studies of lottery winners show that most continue working even when they no longer need the money.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Universal basic income programs are expensive to implement" },
      { letter: "B", text: "In pilot programs of universal basic income, employment rates remained stable" },
      { letter: "C", text: "Many lottery winners choose to reduce their working hours" },
      { letter: "D", text: "Work provides structure that many people find psychologically valuable" },
      { letter: "E", text: "Countries with generous unemployment benefits have higher unemployment rates" },
    ],
    correctAnswer: "B",
    explanation: "Direct evidence from actual universal basic income pilot programs showing stable employment rates provides strong empirical support for the claim that UBI would not significantly reduce work incentives. This is more direct evidence than the analogy to lottery winners.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-040",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Child psychologist: Screen time should be strictly limited for young children because it reduces face-to-face social interaction, which is crucial for developing emotional intelligence. Children learn to read facial expressions and emotional cues primarily through direct human interaction.`,
    questionStem: "Which one of the following, if true, most weakens the psychologist's argument?",
    answerChoices: [
      { letter: "A", text: "Many children enjoy educational programs on screens" },
      { letter: "B", text: "Screen time often displaces outdoor physical activity" },
      { letter: "C", text: "Modern video calling technology allows children to engage in face-to-face interaction during screen time" },
      { letter: "D", text: "Some children who have limited screen time still struggle with emotional intelligence" },
      { letter: "E", text: "Parents often use screen time to occupy children while completing household tasks" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes screen time necessarily reduces face-to-face interaction. If video calling allows face-to-face interaction through screens, then screen time doesn't necessarily reduce social interaction, undermining the basis for strict limits.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-041",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Restaurant reviewer: This new restaurant serves excellent food. The chef previously worked at one of the city's most acclaimed restaurants, and several of the dishes I sampled were outstanding. However, the service was slow and inattentive. Overall, I would not recommend this restaurant for a special occasion.`,
    questionStem: "The reviewer's argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Excellent food is not sufficient reason to recommend a restaurant for special occasions" },
      { letter: "B", text: "The chef's previous experience is relevant to the quality of the current restaurant" },
      { letter: "C", text: "Other reviewers would have the same experience with the service" },
      { letter: "D", text: "The slow service was not due to the restaurant being unusually busy" },
      { letter: "E", text: "Special occasions require expensive restaurants" },
    ],
    correctAnswer: "A",
    explanation: "The reviewer acknowledges excellent food but still does not recommend the restaurant for special occasions due to poor service. This requires assuming that food quality alone is not enough for a special occasion recommendation, meaning service also matters significantly.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Journalist: The mayor claims that the new traffic policies have reduced commute times. But the mayor has a strong political interest in these policies appearing successful because they were a centerpiece of her campaign. We should therefore be skeptical of this claim until it is verified by independent sources.`,
    questionStem: "The journalist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing evidence that directly contradicts the mayor's claim" },
      { letter: "B", text: "demonstrating that the mayor's data was collected improperly" },
      { letter: "C", text: "arguing that the source's potential bias warrants caution about accepting the claim" },
      { letter: "D", text: "showing that traffic policies typically do not affect commute times" },
      { letter: "E", text: "questioning whether reduced commute times are actually desirable" },
    ],
    correctAnswer: "C",
    explanation: "The journalist doesn't claim the mayor is wrong, but argues that the mayor's political interest creates a reason to be skeptical until independent verification is obtained. This is an argument about the reliability of the source due to potential bias, not a direct refutation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-043",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `University administrator: Our new tutoring program has successfully improved student performance. Before the program, 60% of students in introductory courses passed. After implementing the program, 75% of students who used the tutoring services passed. This 15-point increase demonstrates the program's effectiveness.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "fails to consider whether the tutoring program was cost-effective" },
      { letter: "B", text: "compares two groups that may differ in important ways beyond tutoring use" },
      { letter: "C", text: "does not specify what subjects the tutoring program covers" },
      { letter: "D", text: "assumes that all students have equal access to the tutoring program" },
      { letter: "E", text: "ignores the possibility that course difficulty has changed over time" },
    ],
    correctAnswer: "B",
    explanation: "The argument compares all students before the program to only those who used the tutoring services after. Students who voluntarily seek tutoring may be more motivated or hardworking than average students, so the comparison is between potentially different populations, making the conclusion about the program's effectiveness unreliable.",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-044",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Medical researcher: A new drug shows promise in treating Alzheimer's disease. In laboratory tests, the drug reduced the buildup of amyloid plaques, which are associated with cognitive decline in Alzheimer's patients. Reducing these plaques should slow the progression of the disease.`,
    questionStem: "Which one of the following, if true, most strengthens the researcher's reasoning?",
    answerChoices: [
      { letter: "A", text: "The drug has no significant side effects in initial trials" },
      { letter: "B", text: "Previous drugs that reduced amyloid plaques failed to slow cognitive decline" },
      { letter: "C", text: "Studies have confirmed that amyloid plaque accumulation directly causes cognitive decline in Alzheimer's patients" },
      { letter: "D", text: "The drug is relatively inexpensive to manufacture" },
      { letter: "E", text: "Patients in the laboratory tests showed high tolerance for the drug" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that reducing plaques will slow cognitive decline because plaques are 'associated with' decline. If studies confirm that plaques directly cause the decline (not just correlation), then reducing plaques should indeed slow the disease, strengthening the argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-045",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Education reformer: The traditional model of lecturing in classrooms is obsolete. Students today have access to high-quality educational videos online that can be paused, rewound, and watched repeatedly. Classroom time would be better spent on interactive problem-solving activities that cannot be replicated online.`,
    questionStem: "Which one of the following, if true, most weakens the reformer's argument?",
    answerChoices: [
      { letter: "A", text: "Not all students have reliable internet access at home" },
      { letter: "B", text: "Some teachers are more engaging lecturers than others" },
      { letter: "C", text: "Students who watch educational videos often do not complete them" },
      { letter: "D", text: "Research shows that students learn best when lectures are interactive and responsive to student questions" },
      { letter: "E", text: "Creating high-quality educational videos requires significant resources" },
    ],
    correctAnswer: "D",
    explanation: "If research shows that the best lectures are interactive and responsive to student questions, then classroom lectures have advantages that online videos cannot replicate. This undermines the claim that videos can replace lectures and that lecture time should be converted to other activities.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-046",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Adams: The humanities are essential to a complete education. They develop critical thinking, ethical reasoning, and communication skills that prepare students for responsible citizenship and meaningful lives, regardless of their career paths.

    Professor Barnes: While the humanities have value, universities must prioritize STEM fields in a technology-driven economy. Students and their families make significant financial investments in higher education and deserve career-focused training that leads to well-paying jobs.`,
    questionStem: "Professor Adams and Professor Barnes disagree most about",
    answerChoices: [
      { letter: "A", text: "whether the humanities develop valuable skills" },
      { letter: "B", text: "whether higher education requires significant financial investment" },
      { letter: "C", text: "what should be the primary focus of university education" },
      { letter: "D", text: "whether STEM fields offer well-paying career opportunities" },
      { letter: "E", text: "whether critical thinking is important" },
    ],
    correctAnswer: "C",
    explanation: "Adams believes universities should prioritize humanities for their broad benefits to students and society, while Barnes believes universities should prioritize STEM for career and economic outcomes. Their disagreement centers on what the primary educational focus should be.",
    difficulty: "easy",
  },
  {
    id: "lr-bank57-047",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Environmentalist: We must protect the old-growth forest from development. Once these ancient trees are cut down, they cannot be replaced; it takes hundreds of years for a forest to reach old-growth status. However, losing a few trees to natural causes each year is acceptable because that is part of the forest's natural cycle.`,
    questionStem: "The environmentalist's reasoning is most vulnerable to criticism on which one of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It fails to specify how many trees constitute 'a few'" },
      { letter: "B", text: "It assumes that development would remove all old-growth trees" },
      { letter: "C", text: "It does not explain why natural loss is acceptable but human-caused loss is not, given both are irreversible" },
      { letter: "D", text: "It overlooks economic benefits that development might provide" },
      { letter: "E", text: "It relies on an emotional appeal rather than scientific evidence" },
    ],
    correctAnswer: "C",
    explanation: "The argument claims old-growth trees cannot be replaced (irreversibility) as the reason to prevent development. But the same irreversibility applies to trees lost naturally. If irreversibility is the key concern, the distinction between natural and human-caused loss requires additional justification that the argument does not provide.",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-048",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Financial advisor: Investors who diversify their portfolios across multiple asset classes experience less volatility than those who concentrate their investments. Since most people prefer stable, predictable returns over dramatic fluctuations, investors should diversify their portfolios.`,
    questionStem: "The financial advisor's argument assumes that",
    answerChoices: [
      { letter: "A", text: "diversified portfolios always outperform concentrated portfolios" },
      { letter: "B", text: "reduced volatility is more important to most investors than maximizing returns" },
      { letter: "C", text: "all investors have access to multiple asset classes" },
      { letter: "D", text: "professional financial advice is necessary for proper diversification" },
      { letter: "E", text: "volatile investments are more likely to lose money" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from 'people prefer stability' to recommending diversification for lower volatility. This assumes that achieving the preferred stability is more important to these investors than other goals like maximizing returns. Some investors might prefer higher returns despite volatility.",
    difficulty: "hard",
  },
  {
    id: "lr-bank57-049",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The decline of the Roman Empire was primarily caused by internal political instability rather than external military threats. While barbarian invasions certainly occurred, they were successful mainly because the empire had already weakened itself through civil wars, corruption, and failures of political succession.`,
    questionStem: "Which one of the following, if true, most strengthens the historian's argument?",
    answerChoices: [
      { letter: "A", text: "The Roman military remained one of the most powerful in the world until the empire's final years" },
      { letter: "B", text: "Barbarian groups had attempted to invade Roman territory for centuries before they succeeded" },
      { letter: "C", text: "Economic factors also contributed to the empire's decline" },
      { letter: "D", text: "Some historians believe that climate change affected agricultural productivity in the empire" },
      { letter: "E", text: "The eastern portion of the empire survived for another thousand years after addressing internal political issues" },
    ],
    correctAnswer: "B",
    explanation: "If barbarians had tried and failed to invade for centuries, then their eventual success cannot be explained by the barbarians themselves becoming stronger. Something must have changed within the empire that allowed previously unsuccessful invasions to succeed, supporting the internal weakness hypothesis.",
    difficulty: "medium",
  },
  {
    id: "lr-bank57-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Marketing director: Our advertising campaign must be working. Last quarter, we spent significantly more on advertising than ever before, and our sales increased by 20%. Some competitors who did not increase their advertising spending actually saw sales decline during the same period.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that the competitors' products are comparable to the company's products" },
      { letter: "B", text: "fails to consider whether a different marketing strategy might have been more effective" },
      { letter: "C", text: "ignores other factors that might have caused the increase in sales" },
      { letter: "D", text: "does not specify the exact amount spent on advertising" },
      { letter: "E", text: "presumes that increased spending always leads to proportionate results" },
    ],
    correctAnswer: "C",
    explanation: "The argument attributes the sales increase to advertising without ruling out other possible causes such as seasonal trends, economic conditions, product improvements, or pricing changes. The correlation between increased advertising and increased sales does not establish that advertising caused the sales increase.",
    difficulty: "easy",
  },
];
