// Logical Reasoning Questions Bank - Set 20
// High-quality LSAT-style questions covering all question types

import { Question } from "../lsat-types";

export const lrQuestionsSet20: Question[] = [
  // FLAW QUESTIONS (10 questions: lr-bank20-001 to lr-bank20-010)
  {
    id: "lr-bank20-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor: Students who participate in study groups consistently earn higher grades than students who study alone. Therefore, joining a study group is the most effective way to improve academic performance.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that students who join study groups may already be more motivated academically" },
      { letter: "B", text: "assumes that all students have equal access to study groups" },
      { letter: "C", text: "ignores the possibility that some subjects are better suited to individual study" },
      { letter: "D", text: "relies on anecdotal evidence rather than systematic research" },
      { letter: "E", text: "does not specify what constitutes a study group" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits the correlation-causation fallacy. It observes that study group participants have higher grades but concludes that study groups cause the improvement. However, students who join study groups may already be more motivated, organized, or academically capable, which would explain both their participation and their higher grades. The correlation might reflect selection bias rather than causal effect. B, C, D, and E identify potential concerns but not the core logical flaw in the reasoning.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Columnist: The proposed highway expansion will cost taxpayers $500 million. That money could instead fund 50 new schools. How can anyone support a highway over educating our children? The choice is clear: we must reject the highway proposal.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "appeals to emotions rather than providing substantive reasons" },
      { letter: "B", text: "presents a false dichotomy between highway funding and school funding" },
      { letter: "C", text: "fails to provide evidence that new schools are actually needed" },
      { letter: "D", text: "assumes that all taxpayers oppose the highway expansion" },
      { letter: "E", text: "does not consider the economic benefits of improved transportation" },
    ],
    correctAnswer: "B",
    explanation: "The columnist commits the false dichotomy fallacy by presenting only two options—highway or schools—when in reality, the money could be allocated many different ways, or additional funding sources might exist. There is no reason to assume these are the only two possible uses of the funds. While A touches on the emotional appeal, the core logical flaw is the false either/or framing. E identifies a missing consideration but not the structural flaw.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Eyewitness testimony should not be admitted as evidence in criminal trials. Studies show that eyewitness identifications are incorrect approximately 30% of the time. Any evidence with such a high error rate is simply too unreliable to be used in determining guilt.`,
    questionStem: "A flaw in the argument is that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that other forms of evidence may also have significant error rates" },
      { letter: "B", text: "assumes that jurors cannot properly assess eyewitness credibility" },
      { letter: "C", text: "does not address the role of cross-examination in testing eyewitness testimony" },
      { letter: "D", text: "ignores cases where eyewitness testimony was proven accurate" },
      { letter: "E", text: "treats eyewitness testimony as the sole form of evidence in criminal cases" },
    ],
    correctAnswer: "A",
    explanation: "The argument sets an absolute standard for evidence reliability without considering whether other admitted forms of evidence meet this same standard. If DNA evidence, forensic analysis, or documentary evidence also had significant error rates, the argument's principle would require excluding those as well. The flaw is the failure to apply the same standard across comparable cases. B, C, and D identify relevant considerations but not the central logical flaw. E mischaracterizes the argument's scope.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Restaurant critic: La Maison's new chef has won multiple culinary awards and trained at renowned establishments in Paris. The food at La Maison must therefore be exceptional.`,
    questionStem: "The reasoning in the argument is flawed because the argument",
    answerChoices: [
      { letter: "A", text: "relies on an appeal to authority rather than an evaluation of the food itself" },
      { letter: "B", text: "assumes that French culinary training is superior to other forms of training" },
      { letter: "C", text: "ignores the possibility that the chef's past success may not continue at a new restaurant" },
      { letter: "D", text: "does not consider the opinions of other food critics" },
      { letter: "E", text: "fails to define what constitutes exceptional food" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that past performance guarantees future results. A chef who excelled in previous settings may face new challenges at La Maison—different ingredients, kitchen staff, equipment, or management—that could affect food quality. Past credentials and training do not guarantee exceptional current performance. While A mentions authority, the more precise flaw is the assumption that past success transfers automatically to a new context.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Countries with higher rates of religious observance have lower crime rates than countries with lower religious observance. This proves that religion promotes moral behavior and reduces criminal activity.`,
    questionStem: "Which one of the following most accurately describes a flaw in the sociologist's reasoning?",
    answerChoices: [
      { letter: "A", text: "It draws a causal conclusion from merely correlational evidence" },
      { letter: "B", text: "It fails to specify which religions were included in the study" },
      { letter: "C", text: "It assumes that crime rates are an accurate measure of moral behavior" },
      { letter: "D", text: "It generalizes from a sample that may not be representative" },
      { letter: "E", text: "It ignores the possibility that different countries define crimes differently" },
    ],
    correctAnswer: "A",
    explanation: "The sociologist observes a correlation between religious observance and lower crime rates but concludes that religion causes the reduction in crime. This is a classic correlation-causation error. The relationship could be explained by other factors—perhaps both high religious observance and low crime are effects of tight-knit social structures, economic conditions, or cultural values. The argument presents no evidence that religious observance itself reduces crime.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Politician: My opponent claims that my tax plan will harm small businesses. But my opponent received campaign donations from large corporations. Obviously, her criticism is motivated by her allegiance to big business interests, not genuine concern for small businesses.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "attacks the source of a claim rather than addressing the substance of the claim" },
      { letter: "B", text: "assumes that all large corporations oppose policies that help small businesses" },
      { letter: "C", text: "fails to provide evidence that the tax plan will actually help small businesses" },
      { letter: "D", text: "presumes that campaign donations necessarily influence a politician's positions" },
      { letter: "E", text: "ignores the possibility that large and small businesses may have aligned interests" },
    ],
    correctAnswer: "A",
    explanation: "The politician commits an ad hominem fallacy by attacking the opponent's motivations and funding sources rather than addressing whether the tax plan would actually harm small businesses. Even if the opponent has received corporate donations, that does not make her criticism false. The argument attempts to dismiss the claim without engaging with its substance. D is relevant but secondary to the core ad hominem flaw.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: It is wrong to cause unnecessary suffering to animals. Eating meat is not necessary for human survival, as many healthy vegetarian societies demonstrate. Therefore, eating meat is morally wrong because it requires causing animals to suffer.`,
    questionStem: "The argument's reasoning is flawed in that it",
    answerChoices: [
      { letter: "A", text: "equates the absence of necessity with the presence of wrongdoing" },
      { letter: "B", text: "fails to consider that some forms of meat production may not cause suffering" },
      { letter: "C", text: "assumes that what is true of societies is true of all individuals within them" },
      { letter: "D", text: "does not adequately define what constitutes suffering" },
      { letter: "E", text: "ignores the nutritional benefits of eating meat" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that eating meat is wrong because it causes suffering, but this assumes all meat production causes suffering. Some methods of raising and slaughtering animals may minimize suffering significantly, or some animals (like certain shellfish) may lack the capacity to suffer. The argument fails to account for these possibilities, making its conclusion overly broad. A mischaracterizes the argument's structure.",
    difficulty: "hard",
  },
  {
    id: "lr-bank20-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The Roman Empire fell because of moral decay among its citizens. Contemporary observers noted increasing corruption, declining civic virtue, and abandonment of traditional values in the empire's final centuries. These accounts prove that moral decline was the primary cause of Rome's collapse.`,
    questionStem: "The argument is most vulnerable to which one of the following criticisms?",
    answerChoices: [
      { letter: "A", text: "It treats observations that are consistent with a hypothesis as proof of that hypothesis" },
      { letter: "B", text: "It fails to define what constitutes moral decay" },
      { letter: "C", text: "It assumes that ancient observers were unbiased in their accounts" },
      { letter: "D", text: "It ignores military and economic factors that may have contributed to Rome's fall" },
      { letter: "E", text: "It applies modern moral standards to an ancient civilization" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits a confirmation bias error. The evidence cited—observations of moral decline—is consistent with the hypothesis that moral decay caused Rome's fall, but it is also consistent with many other hypotheses. The observations do not prove causation; they merely show that moral decline was present. Other factors (military, economic, political) could have caused both the moral decline and the empire's collapse. D identifies a missing consideration, but A captures the logical structure of the flaw.",
    difficulty: "hard",
  },
  {
    id: "lr-bank20-009",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: Our experiment found no evidence that the new medication reduces blood pressure. Therefore, patients should not take this medication, as it clearly provides no health benefits for cardiovascular conditions.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "treats the absence of evidence as evidence of absence" },
      { letter: "B", text: "assumes that blood pressure reduction is the only cardiovascular benefit" },
      { letter: "C", text: "fails to consider the side effects of the medication" },
      { letter: "D", text: "generalizes from a single experiment to all possible uses of the medication" },
      { letter: "E", text: "does not specify the methodology of the experiment" },
    ],
    correctAnswer: "A",
    explanation: "The scientist conflates 'no evidence of benefit' with 'evidence of no benefit.' Finding no evidence in one experiment that a medication reduces blood pressure does not prove it provides no cardiovascular benefits—the experiment may have been underpowered, used the wrong dosage, measured at the wrong time, or focused on the wrong outcome. The absence of evidence in this case does not constitute proof of absence. B is also a flaw but is secondary to the primary logical error.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-010",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Consumer advocate: Every product recalled for safety defects in the past year was manufactured overseas. This shows that overseas manufacturing leads to dangerous products. To protect consumers, we should require all products sold domestically to be manufactured domestically.`,
    questionStem: "Which one of the following most accurately describes a flaw in the argument?",
    answerChoices: [
      { letter: "A", text: "It fails to consider the total number of products manufactured overseas versus domestically" },
      { letter: "B", text: "It assumes that domestic manufacturing would be economically viable" },
      { letter: "C", text: "It ignores the role of regulatory oversight in product safety" },
      { letter: "D", text: "It does not distinguish between different countries of overseas manufacture" },
      { letter: "E", text: "It conflates correlation with causation without considering base rates" },
    ],
    correctAnswer: "A",
    explanation: "The argument notes that all recalled products were manufactured overseas but fails to consider that the vast majority of products sold may be manufactured overseas. If 95% of products are made overseas, we would expect 95% of recalled products to be overseas-manufactured even if overseas production is no more dangerous than domestic production. The argument ignores base rates, which is essential for evaluating the significance of the correlation. E is close but A is more specific about the flaw.",
    difficulty: "hard",
  },

  // STRENGTHEN QUESTIONS (8 questions: lr-bank20-011 to lr-bank20-018)
  {
    id: "lr-bank20-011",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying sleep patterns found that individuals who reported using smartphones within one hour of bedtime took longer to fall asleep and experienced less restful sleep than those who avoided screens before bed. The researchers concluded that smartphone use before bedtime disrupts sleep quality.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' conclusion?",
    answerChoices: [
      { letter: "A", text: "When participants who typically used smartphones before bed abstained from doing so, their sleep quality improved significantly" },
      { letter: "B", text: "People who use smartphones before bed tend to have more stressful jobs" },
      { letter: "C", text: "Blue light from screens has been shown to suppress melatonin production" },
      { letter: "D", text: "Most participants in the study were between 18 and 35 years old" },
      { letter: "E", text: "Some participants reported using their smartphones for relaxation purposes" },
    ],
    correctAnswer: "A",
    explanation: "The researchers' conclusion is that smartphone use causes disrupted sleep. Answer A provides experimental evidence supporting causation: when the independent variable (smartphone use) is changed, the dependent variable (sleep quality) changes accordingly. This controls for confounding variables that might explain both behaviors. C provides a mechanism but doesn't directly test the causal claim. B suggests an alternative explanation. D and E are largely irrelevant.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Political scientist: Voter turnout in local elections is consistently lower than in national elections. This suggests that citizens view local elections as less important. To increase civic engagement at the local level, municipalities should better educate citizens about the direct impact local governments have on their daily lives.`,
    questionStem: "Which one of the following, if true, most strengthens the political scientist's recommendation?",
    answerChoices: [
      { letter: "A", text: "Citizens who receive information about local government services are more likely to vote in local elections" },
      { letter: "B", text: "National elections receive more media coverage than local elections" },
      { letter: "C", text: "Some municipalities have experimented with online voting for local elections" },
      { letter: "D", text: "Voter turnout in presidential primaries varies significantly by state" },
      { letter: "E", text: "Many citizens cannot name their local elected officials" },
    ],
    correctAnswer: "A",
    explanation: "The political scientist recommends education about local government impact to increase turnout. A directly supports this by showing that when citizens receive such information, their voting behavior changes accordingly. This provides evidence that the proposed intervention would work. B explains low turnout but doesn't support the specific recommendation. E confirms ignorance but doesn't show education changes behavior.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Marine biologist: The decline of coral reef ecosystems is primarily caused by rising ocean temperatures rather than pollution or overfishing. Temperature stress causes coral bleaching, which leads to coral death and ecosystem collapse. Conservation efforts should focus primarily on addressing climate change.`,
    questionStem: "Which one of the following, if true, most strengthens the marine biologist's argument?",
    answerChoices: [
      { letter: "A", text: "Coral reefs in marine protected areas with strict pollution controls have experienced the same rates of bleaching as unprotected reefs" },
      { letter: "B", text: "Some coral species appear to be adapting to warmer water temperatures" },
      { letter: "C", text: "Overfishing has reduced populations of herbivorous fish that help keep algae from overgrowing coral" },
      { letter: "D", text: "Pollution from agricultural runoff has increased significantly in coastal waters" },
      { letter: "E", text: "Coral bleaching events have occurred in the past during periods of natural temperature variation" },
    ],
    correctAnswer: "A",
    explanation: "The biologist claims temperature, not pollution or overfishing, is the primary cause. A provides evidence that controlling pollution does not prevent bleaching—reefs in protected areas bleach at the same rate. This suggests pollution is not the primary driver, supporting the focus on temperature. B might suggest the problem is less severe. C and D support alternative causes. E provides historical context but doesn't distinguish between causes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The implementation of a universal basic income would reduce poverty more effectively than current welfare programs. Unlike existing programs, which create disincentives to work by reducing benefits when recipients earn income, a universal basic income would be provided regardless of employment status, allowing recipients to keep all additional earnings.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Countries that have implemented universal basic income pilots have seen increases in entrepreneurship among recipients" },
      { letter: "B", text: "The administrative costs of current welfare programs are higher than the projected costs of universal basic income administration" },
      { letter: "C", text: "Studies show that recipients of unconditional cash transfers are more likely to seek employment than recipients of conditional benefits" },
      { letter: "D", text: "Some current welfare recipients work fewer hours to avoid losing their benefits" },
      { letter: "E", text: "Universal basic income programs would be funded through changes to the tax code" },
    ],
    correctAnswer: "C",
    explanation: "The economist's key claim is that universal basic income removes disincentives to work that exist in current programs. C provides direct evidence supporting this: unconditional cash transfers (like UBI) lead to more employment seeking than conditional benefits. This confirms the mechanism the economist relies upon. D supports the claim that current programs have disincentives but doesn't show UBI is better. A and B support UBI but not the specific poverty-reduction argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: The ancient city of Cahokia, near present-day St. Louis, was abandoned around 1350 CE. Many scholars have attributed this to environmental degradation caused by deforestation. However, I believe a prolonged drought was the primary cause of the city's decline, as agricultural failure would have made the large population unsustainable.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologist's hypothesis?",
    answerChoices: [
      { letter: "A", text: "Tree ring data from the region shows significantly reduced rainfall from 1300 to 1350 CE" },
      { letter: "B", text: "Cahokia had the largest population of any pre-Columbian settlement north of Mexico" },
      { letter: "C", text: "Archaeological evidence shows extensive deforestation in the area surrounding Cahokia" },
      { letter: "D", text: "Other settlements in the region were also abandoned during this period" },
      { letter: "E", text: "Cahokia's residents relied heavily on maize agriculture" },
    ],
    correctAnswer: "A",
    explanation: "The archaeologist claims prolonged drought caused Cahokia's decline. A provides independent evidence that a drought actually occurred during the relevant period—tree ring data showing reduced rainfall from 1300-1350 CE. This directly supports the drought hypothesis. D suggests a regional pattern that could be consistent with drought but is less direct. E establishes agricultural dependence but not that drought occurred. C supports the competing deforestation theory.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Company executive: Our employee wellness program, which includes gym memberships and stress management workshops, has been highly effective. Since implementing the program, employee productivity has increased by 15% and healthcare costs have decreased by 10%.`,
    questionStem: "Which one of the following, if true, most strengthens the executive's claim about the wellness program's effectiveness?",
    answerChoices: [
      { letter: "A", text: "Employees who participate in the wellness program report higher job satisfaction" },
      { letter: "B", text: "Comparable companies without wellness programs experienced declining productivity during the same period" },
      { letter: "C", text: "The company also implemented new technology systems during the same period" },
      { letter: "D", text: "Healthcare costs have decreased industry-wide due to lower insurance premiums" },
      { letter: "E", text: "The wellness program is popular among employees" },
    ],
    correctAnswer: "B",
    explanation: "The executive claims the wellness program caused improved productivity and reduced healthcare costs. B strengthens this by providing a comparison group—similar companies without the program saw declining productivity. This suggests the improvements aren't due to external factors affecting all companies but rather to the specific wellness intervention. C and D actually weaken the claim by suggesting alternative causes. A and E support the program's appeal but not its causal effectiveness.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Individuals who practice mindfulness meditation for at least 20 minutes daily show reduced symptoms of anxiety and depression compared to non-meditators. This suggests that mindfulness meditation should be incorporated into standard treatment protocols for these conditions.`,
    questionStem: "Which one of the following, if true, most strengthens the psychologist's recommendation?",
    answerChoices: [
      { letter: "A", text: "Mindfulness meditation has been practiced in various forms for thousands of years" },
      { letter: "B", text: "Patients who added daily mindfulness meditation to their existing treatment showed greater improvement than those receiving only standard treatment" },
      { letter: "C", text: "Some patients prefer meditation to taking medication" },
      { letter: "D", text: "Mindfulness meditation has no known side effects" },
      { letter: "E", text: "Many therapists are already trained in mindfulness techniques" },
    ],
    correctAnswer: "B",
    explanation: "The psychologist recommends adding mindfulness to treatment protocols. B provides evidence that when meditation is added to standard treatment, outcomes improve beyond standard treatment alone. This directly supports incorporating meditation as a beneficial addition. D addresses safety but not efficacy. A appeals to tradition. C and E address practicality but not whether the recommendation would improve patient outcomes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-018",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Urban planner: Converting vacant lots in urban neighborhoods into community gardens would reduce crime in those areas. Community gardens create spaces where residents interact and build social connections, which increases informal surveillance and community cohesion.`,
    questionStem: "Which one of the following, if true, most strengthens the urban planner's argument?",
    answerChoices: [
      { letter: "A", text: "Neighborhoods with higher rates of resident interaction consistently have lower crime rates" },
      { letter: "B", text: "Many urban neighborhoods have numerous vacant lots" },
      { letter: "C", text: "Community gardens provide fresh produce for neighborhood residents" },
      { letter: "D", text: "Some cities have allocated funding for community garden initiatives" },
      { letter: "E", text: "Maintaining community gardens requires significant volunteer effort" },
    ],
    correctAnswer: "A",
    explanation: "The urban planner's argument relies on a causal chain: gardens increase resident interaction, which reduces crime. A provides evidence for the second link—that neighborhoods with more interaction have less crime. This supports the mechanism the planner relies upon. B establishes opportunity but not effectiveness. C and D are tangential benefits. E might suggest implementation challenges.",
    difficulty: "medium",
  },

  // WEAKEN QUESTIONS (8 questions: lr-bank20-019 to lr-bank20-026)
  {
    id: "lr-bank20-019",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Education researcher: Schools that have implemented later start times have seen improvements in student academic performance and attendance. Therefore, all schools should adopt later start times to improve student outcomes.`,
    questionStem: "Which one of the following, if true, most weakens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Some teachers prefer earlier start times for personal scheduling reasons" },
      { letter: "B", text: "Schools that adopted later start times also implemented other reforms such as smaller class sizes and additional tutoring" },
      { letter: "C", text: "Transportation logistics become more complicated with later school start times" },
      { letter: "D", text: "Student athletes would have less time for after-school sports practices" },
      { letter: "E", text: "Some students may stay up later if they know school starts later" },
    ],
    correctAnswer: "B",
    explanation: "The researcher attributes improved outcomes to later start times. B undermines this by noting that schools implementing later starts also made other changes. The improvements might be due to smaller classes and tutoring, not the start times themselves. This is a classic confounding variable problem that weakens the causal claim. A, C, and D raise practical objections but don't challenge whether later starts caused the improvements. E suggests a possible behavioral response but doesn't undermine the observed correlation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Organic produce is healthier than conventionally grown produce because organic farming prohibits synthetic pesticides. Reducing exposure to these chemicals improves long-term health outcomes.`,
    questionStem: "Which one of the following, if true, most seriously undermines the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Organic produce typically costs more than conventional produce" },
      { letter: "B", text: "Organic farming uses natural pesticides that can be equally or more toxic than synthetic alternatives" },
      { letter: "C", text: "Some consumers prefer the taste of organic produce" },
      { letter: "D", text: "Organic certification standards vary between countries" },
      { letter: "E", text: "Not all conventional produce contains detectable pesticide residues" },
    ],
    correctAnswer: "B",
    explanation: "The nutritionist's argument rests on the claim that avoiding synthetic pesticides improves health. B directly undermines this by noting that organic farming uses natural pesticides that may be equally or more toxic. If organic pesticides are also harmful, then the claimed health benefit disappears. E somewhat weakens the argument but doesn't challenge the organic-specific claim. A, C, and D are irrelevant to the health argument.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Technology analyst: The decline in personal computer sales over the past decade proves that tablets and smartphones have become the preferred devices for most computing tasks. Manufacturers should shift their focus entirely to mobile device development.`,
    questionStem: "Which one of the following, if true, most weakens the analyst's recommendation?",
    answerChoices: [
      { letter: "A", text: "Some professional tasks such as video editing and software development still require personal computers" },
      { letter: "B", text: "Personal computer prices have decreased significantly over the past decade" },
      { letter: "C", text: "Many consumers own both personal computers and mobile devices" },
      { letter: "D", text: "The decline in PC sales coincided with longer product replacement cycles rather than decreased demand for computing power" },
      { letter: "E", text: "Some manufacturers have already reduced their personal computer product lines" },
    ],
    correctAnswer: "D",
    explanation: "The analyst interprets declining PC sales as evidence that mobile devices have replaced PCs for most tasks. D provides an alternative explanation: people are keeping their PCs longer rather than replacing them with mobile devices. This means PCs remain important, just purchased less frequently. The recommendation to abandon PCs would be premature. A provides a reason to continue PC development but doesn't challenge the interpretation of sales data. C is consistent with the analyst's position.",
    difficulty: "hard",
  },
  {
    id: "lr-bank20-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Environmental advocate: Electric vehicles produce zero emissions and are therefore better for the environment than gasoline-powered cars. To reduce air pollution, governments should provide substantial subsidies for electric vehicle purchases.`,
    questionStem: "Which one of the following, if true, most weakens the environmental advocate's argument?",
    answerChoices: [
      { letter: "A", text: "Electric vehicle batteries eventually need to be replaced, generating electronic waste" },
      { letter: "B", text: "In regions where electricity is generated primarily from coal, the total emissions from electric vehicle use exceed those from efficient gasoline vehicles" },
      { letter: "C", text: "Electric vehicles have a higher purchase price than comparable gasoline vehicles" },
      { letter: "D", text: "Some consumers prefer the driving experience of gasoline-powered vehicles" },
      { letter: "E", text: "The range of electric vehicles is limited compared to gasoline vehicles" },
    ],
    correctAnswer: "B",
    explanation: "The advocate claims electric vehicles are better for the environment because they produce zero emissions. B undermines this by noting that when electricity comes from coal, total emissions from EVs can exceed those of gasoline cars. The 'zero emissions' claim refers only to tailpipe emissions, ignoring the power generation emissions. The environmental benefit depends on the electricity source. A raises a concern but doesn't challenge the air pollution argument. C, D, and E are practical concerns unrelated to environmental impact.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Criminologist: Increased police presence in high-crime neighborhoods has led to a 20% reduction in reported crimes in those areas. This demonstrates that visible policing deters criminal activity and should be expanded throughout the city.`,
    questionStem: "Which one of the following, if true, most seriously calls into question the criminologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Some residents feel uncomfortable with heavy police presence in their neighborhoods" },
      { letter: "B", text: "Crime rates in adjacent neighborhoods increased by 15% during the same period" },
      { letter: "C", text: "The cost of increased police presence is substantial" },
      { letter: "D", text: "Some types of crime are more easily deterred than others" },
      { letter: "E", text: "Police departments in other cities have tried similar approaches with varying results" },
    ],
    correctAnswer: "B",
    explanation: "The criminologist claims policing deters crime. B suggests the crime didn't decrease but merely displaced to adjacent areas. If total crime remained constant while shifting locations, then policing didn't actually reduce criminal activity—it just moved it. This fundamentally challenges the claim that visible policing deters crime. A is a social concern but doesn't challenge the effectiveness claim. C is a resource concern. D and E don't directly undermine the specific conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-024",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Business consultant: Companies that implement open-plan offices report higher levels of employee collaboration and innovation. Organizations seeking to foster creativity should therefore eliminate private offices and cubicles in favor of open layouts.`,
    questionStem: "Which one of the following, if true, most weakens the consultant's recommendation?",
    answerChoices: [
      { letter: "A", text: "Some employees prefer having private workspaces" },
      { letter: "B", text: "Companies that implement open-plan offices are also more likely to have innovative cultures that predispose them toward collaboration" },
      { letter: "C", text: "Open-plan offices can be noisy environments" },
      { letter: "D", text: "Private offices are more expensive to construct than open-plan spaces" },
      { letter: "E", text: "Some highly innovative companies have retained traditional office layouts" },
    ],
    correctAnswer: "B",
    explanation: "The consultant infers that open-plan offices cause collaboration and innovation. B suggests reverse causation or selection bias: innovative, collaborative companies might be more likely to adopt open plans. The office layout might be a result of company culture rather than a cause of it. This weakens the claim that adopting open plans will make other companies more innovative. A and C are drawbacks but don't challenge the causal claim. E provides a counterexample but is weaker than B's systematic challenge.",
    difficulty: "hard",
  },
  {
    id: "lr-bank20-025",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Health official: Our public awareness campaign about the dangers of smoking has been successful. Surveys show that 95% of adults in our region are aware that smoking causes serious health problems. The campaign has achieved its goal.`,
    questionStem: "Which one of the following, if true, most weakens the health official's conclusion?",
    answerChoices: [
      { letter: "A", text: "Smoking rates in the region have not decreased since the campaign began" },
      { letter: "B", text: "Some residents learned about smoking dangers from sources other than the campaign" },
      { letter: "C", text: "The campaign cost more than initially budgeted" },
      { letter: "D", text: "Awareness of smoking dangers was already at 93% before the campaign began" },
      { letter: "E", text: "Some smokers continue to smoke despite knowing the health risks" },
    ],
    correctAnswer: "D",
    explanation: "The official claims the campaign successfully raised awareness. D reveals that awareness was already at 93% before the campaign, meaning the campaign only increased awareness by 2 percentage points. This minimal change suggests the campaign added little value despite the 95% awareness rate. The high awareness existed prior to the campaign. A is a strong objection but focuses on behavior change, not the stated goal of awareness. B notes alternative sources but doesn't challenge success. E is expected behavior.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Literary critic: The novels of Author X, written in the early 20th century, are timeless masterpieces. They continue to be widely read today, demonstrating that great literature transcends its historical context and speaks to universal human experiences.`,
    questionStem: "Which one of the following, if true, most weakens the critic's reasoning?",
    answerChoices: [
      { letter: "A", text: "Author X's novels are required reading in many high school and university literature courses" },
      { letter: "B", text: "Some contemporary readers find Author X's prose style difficult to follow" },
      { letter: "C", text: "Author X won several major literary awards during their lifetime" },
      { letter: "D", text: "The themes in Author X's novels were considered controversial when first published" },
      { letter: "E", text: "Literary critics continue to publish scholarly analyses of Author X's work" },
    ],
    correctAnswer: "A",
    explanation: "The critic argues that continued readership proves the novels speak to universal experiences. A provides an alternative explanation: the novels remain widely read because they are assigned in courses, not because readers freely choose them. Institutional requirements rather than timeless appeal might explain current readership. This undermines the claim that ongoing popularity demonstrates universal themes. B, C, D, and E don't explain why the books are still read.",
    difficulty: "medium",
  },

  // ASSUMPTION QUESTIONS (8 questions: lr-bank20-027 to lr-bank20-034)
  {
    id: "lr-bank20-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Manager: Our customer service representatives should be evaluated primarily on customer satisfaction scores rather than call handling time. Representatives who take longer on calls but resolve issues completely will generate more satisfied customers and more long-term business.`,
    questionStem: "The manager's argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Customer satisfaction can be accurately measured through surveys" },
      { letter: "B", text: "Complete issue resolution is more valuable to the company than handling more calls" },
      { letter: "C", text: "All customer service representatives are equally skilled at resolving issues" },
      { letter: "D", text: "Customers always prefer longer calls to shorter ones" },
      { letter: "E", text: "Call handling time has no effect on customer satisfaction" },
    ],
    correctAnswer: "B",
    explanation: "The manager argues for prioritizing satisfaction over call volume. This assumes that the business value from satisfied customers outweighs any loss from handling fewer total calls. If handling more calls (even with lower satisfaction) generated more value, the argument would fail. Use negation test: if complete resolution were less valuable than call volume, the recommendation wouldn't follow. A is practical but not logically required. D is too extreme. E contradicts the argument's logic.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Zoologist: The endangered snow leopard population has increased in the Himalayan region since stricter anti-poaching laws were enacted five years ago. This proves that legal protections are effective at preserving endangered species.`,
    questionStem: "Which one of the following is an assumption on which the zoologist's argument depends?",
    answerChoices: [
      { letter: "A", text: "Snow leopards are the only endangered species in the Himalayan region" },
      { letter: "B", text: "The increase in snow leopard population was not primarily due to factors other than the anti-poaching laws" },
      { letter: "C", text: "Anti-poaching laws have been enacted in all countries where snow leopards live" },
      { letter: "D", text: "Poaching was the only threat to snow leopard survival before the new laws" },
      { letter: "E", text: "The snow leopard population will continue to increase in the future" },
    ],
    correctAnswer: "B",
    explanation: "The zoologist concludes that legal protections caused the population increase. This assumes the increase wasn't due to other factors—such as habitat improvement, prey population changes, or reduced demand for leopard products independent of legal enforcement. If other factors primarily caused the increase, the laws wouldn't be proven effective. Negation: if other factors were primarily responsible, the conclusion wouldn't follow. D is too strong (only threat). A and C are irrelevant.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The paintings attributed to the Dutch Master were actually created by his workshop assistants. The brushwork is inconsistent with the Master's known technique, and chemical analysis shows the pigments were prepared differently than in his authenticated works.`,
    questionStem: "The art historian's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Workshop assistants could not have been trained to replicate the Master's technique" },
      { letter: "B", text: "The Master did not experiment with different techniques or pigment preparations during different periods" },
      { letter: "C", text: "Chemical analysis of pigments is always accurate" },
      { letter: "D", text: "Other art historians agree with this attribution" },
      { letter: "E", text: "The paintings in question are less valuable than the Master's authenticated works" },
    ],
    correctAnswer: "B",
    explanation: "The art historian argues the paintings aren't by the Master because technique and pigments differ from authenticated works. This assumes the Master's methods remained consistent. If he experimented with different techniques or pigments at different periods, the differences wouldn't prove workshop attribution. Negation: if the Master did experiment with different techniques, the evidence wouldn't support the conclusion. A actually strengthens the argument. C is about methodology, not a logical requirement.",
    difficulty: "hard",
  },
  {
    id: "lr-bank20-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Countries that invest heavily in education have stronger economic growth over time. Therefore, developing nations seeking to improve their economies should prioritize education spending.`,
    questionStem: "The economist's reasoning relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Education is more important than natural resources for economic development" },
      { letter: "B", text: "The relationship between education investment and economic growth observed in other countries will hold for developing nations" },
      { letter: "C", text: "All types of education spending produce equal economic returns" },
      { letter: "D", text: "Developing nations currently invest less in education than developed nations" },
      { letter: "E", text: "Economic growth is the most important goal for developing nations" },
    ],
    correctAnswer: "B",
    explanation: "The economist applies a general pattern (education investment leads to growth) to recommend action for developing nations. This assumes the pattern applies to those nations. If developing nations faced different circumstances making education investment less effective for them, the recommendation wouldn't follow. The argument bridges from general evidence to a specific recommendation. A is too strong. D doesn't address whether investment would be effective. C overstates the claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-031",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Physician: Patients with chronic pain should consider acupuncture as an alternative to opioid medications. Studies show that acupuncture provides significant pain relief for many patients, and it carries none of the addiction risks associated with opioids.`,
    questionStem: "Which one of the following is an assumption required by the physician's argument?",
    answerChoices: [
      { letter: "A", text: "Acupuncture has no side effects whatsoever" },
      { letter: "B", text: "All patients with chronic pain will respond positively to acupuncture" },
      { letter: "C", text: "For at least some chronic pain patients, acupuncture provides adequate pain relief compared to opioids" },
      { letter: "D", text: "Opioid medications should never be prescribed for chronic pain" },
      { letter: "E", text: "Acupuncture is less expensive than opioid medications" },
    ],
    correctAnswer: "C",
    explanation: "The physician recommends acupuncture as an alternative to opioids. For this to be sensible, acupuncture must provide adequate pain relief to be a viable alternative. If acupuncture's pain relief were always insufficient compared to opioids, it wouldn't be a real alternative despite being safer. Negation: if acupuncture never provided adequate relief, it couldn't be recommended as an alternative. A and B are too strong. D mischaracterizes the argument's scope. E is irrelevant.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Linguist: The Piraha people of the Amazon have a language with no words for specific numbers beyond "one" and "two." This suggests that the human capacity for mathematical thinking is shaped by language rather than being entirely innate.`,
    questionStem: "The linguist's argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The Piraha people have difficulty with mathematical concepts that their language cannot express" },
      { letter: "B", text: "All languages have words for at least some numbers" },
      { letter: "C", text: "The Piraha language has remained unchanged for centuries" },
      { letter: "D", text: "Other Amazon peoples have more extensive numerical vocabulary" },
      { letter: "E", text: "Mathematical thinking is useful for survival in the Amazon" },
    ],
    correctAnswer: "A",
    explanation: "The linguist argues from the absence of number words to a conclusion about mathematical thinking. This assumes the language limitation actually affects the Piraha's mathematical cognition. If the Piraha could think mathematically despite lacking number words, the language-shapes-cognition conclusion wouldn't follow. Negation: if Piraha people had no difficulty with mathematical concepts despite limited vocabulary, the argument would fail. B, C, D, and E don't connect language to cognition.",
    difficulty: "hard",
  },
  {
    id: "lr-bank20-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Film critic: The director's latest film is a disappointment. While visually stunning, it lacks the emotional depth that characterized her earlier work. The shift to big-budget productions has compromised her artistic vision.`,
    questionStem: "The critic's argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "visual quality and emotional depth cannot coexist in the same film" },
      { letter: "B", text: "the requirements of big-budget productions are at least partly responsible for the lack of emotional depth" },
      { letter: "C", text: "the director's earlier films were not visually impressive" },
      { letter: "D", text: "all big-budget productions lack artistic merit" },
      { letter: "E", text: "the director prefers making smaller films" },
    ],
    correctAnswer: "B",
    explanation: "The critic claims big-budget production compromised artistic vision, causing the lack of emotional depth. This assumes a causal connection between the budget and the artistic shortcoming. If the budget had nothing to do with the emotional depth issue (perhaps the director simply made different artistic choices), the blame on big budgets would be unfounded. Negation: if big-budget requirements weren't responsible, the conclusion wouldn't follow. A and D are too extreme. C contradicts the stimulus.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Marketing executive: Our advertising campaign featuring celebrity endorsements has significantly increased brand awareness among young consumers. We should expand this approach to reach older demographics as well.`,
    questionStem: "The executive's reasoning assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Older consumers are aware of the celebrities used in the campaign" },
      { letter: "B", text: "Celebrity endorsements can be effective with demographics other than young consumers" },
      { letter: "C", text: "Brand awareness is the company's primary marketing objective" },
      { letter: "D", text: "The same celebrities will be used in campaigns targeting older demographics" },
      { letter: "E", text: "Older consumers currently have low awareness of the brand" },
    ],
    correctAnswer: "B",
    explanation: "The executive argues from success with young consumers to a recommendation for older demographics. This assumes celebrity endorsements can work with other age groups. If celebrity endorsements only work with young people, the expansion recommendation wouldn't make sense. Negation: if celebrity endorsements couldn't be effective with older demographics, the recommendation would be unfounded. A and D are about specific implementation details. C and E are not required for the argument.",
    difficulty: "easy",
  },

  // MAIN-CONCLUSION QUESTIONS (4 questions: lr-bank20-035 to lr-bank20-038)
  {
    id: "lr-bank20-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `While genetic factors influence athletic potential, they do not determine athletic success. Many individuals with favorable genetics never become elite athletes due to lack of training, opportunity, or motivation. Conversely, athletes with less genetic advantage have achieved remarkable success through dedicated practice and optimal coaching. The role of environmental factors in athletic achievement is therefore at least as significant as genetic inheritance.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Genetic factors influence but do not determine athletic success" },
      { letter: "B", text: "Environmental factors are at least as significant as genetics in athletic achievement" },
      { letter: "C", text: "Many genetically gifted individuals fail to become elite athletes" },
      { letter: "D", text: "Dedicated practice can compensate for genetic disadvantages" },
      { letter: "E", text: "Athletic success requires both favorable genetics and proper training" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes with 'therefore,' indicating the main conclusion: environmental factors are at least as significant as genetic inheritance. The earlier statements—that genetics don't determine success, that gifted individuals may fail, and that practice can lead to success—are all premises supporting this conclusion about the relative importance of environment versus genetics. A is a premise. C and D are supporting examples. E is not stated.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The decline of local newspapers has been blamed on the internet and changing reader habits. However, many local newspapers that have maintained investigative journalism and community coverage have retained stable readership. Meanwhile, papers that cut editorial staff and reduced original content have lost subscribers at accelerating rates. The quality of journalism, not merely the medium, determines whether local newspapers survive.`,
    questionStem: "Which one of the following most accurately expresses the conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "The internet has caused the decline of local newspapers" },
      { letter: "B", text: "Newspapers that maintain quality journalism retain readership" },
      { letter: "C", text: "Journalism quality is the key factor in local newspaper survival" },
      { letter: "D", text: "Local newspapers that cut staff lose subscribers" },
      { letter: "E", text: "Reader habits have changed significantly in recent years" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that 'the quality of journalism, not merely the medium, determines whether local newspapers survive.' The observations about papers maintaining quality versus those cutting content are premises supporting this conclusion about what drives survival. A is presented as a competing view being challenged. B and D are premises. E is mentioned but not the focus.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Critics argue that social media has made society more polarized. But historical records show that political divisions were equally intense in earlier eras—the partisan newspapers of the 19th century were far more inflammatory than today's social media posts. What appears as new polarization may simply be increased visibility of disagreements that have always existed. We should be cautious about attributing social changes to new technologies without considering historical context.`,
    questionStem: "The main conclusion of the argument is that",
    answerChoices: [
      { letter: "A", text: "social media has not made society more polarized" },
      { letter: "B", text: "19th century newspapers were more inflammatory than social media" },
      { letter: "C", text: "historical context should inform our assessment of technology's social impact" },
      { letter: "D", text: "political divisions have always existed in society" },
      { letter: "E", text: "increased visibility of disagreements explains apparent polarization" },
    ],
    correctAnswer: "C",
    explanation: "The final sentence states the main conclusion: we should be cautious about attributing social changes to new technologies without considering historical context. The historical examples are premises supporting this methodological conclusion about how to evaluate technology's effects. A overstates the claim. B and D are premises. E is an alternative explanation offered as evidence.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some philosophers argue that moral truths are objective facts independent of human beliefs. Others contend that morality is entirely relative to cultural norms. Both positions face serious objections. If morality were purely objective, we would expect greater consensus across cultures than we observe. If morality were purely relative, we could not criticize practices like slavery as genuinely wrong. The truth likely involves both objective and subjective elements that interact in complex ways.`,
    questionStem: "Which one of the following most accurately expresses the main point of the argument?",
    answerChoices: [
      { letter: "A", text: "Objective moral facts exist independently of human beliefs" },
      { letter: "B", text: "Morality is entirely relative to cultural norms" },
      { letter: "C", text: "Both purely objective and purely relative views of morality face problems" },
      { letter: "D", text: "Morality likely combines objective and subjective elements" },
      { letter: "E", text: "Slavery is genuinely wrong regardless of cultural context" },
    ],
    correctAnswer: "D",
    explanation: "The argument evaluates two extreme positions, finds problems with each, and concludes that 'the truth likely involves both objective and subjective elements.' This synthesis is the main conclusion. A and B are the positions being evaluated. C is an intermediate conclusion supporting the main point. E is used as an example to criticize pure relativism.",
    difficulty: "medium",
  },

  // METHOD-OF-REASONING QUESTIONS (4 questions: lr-bank20-039 to lr-bank20-042)
  {
    id: "lr-bank20-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Public health advocate: Some argue that seat belt laws infringe on personal freedom—adults should be able to choose their own risk levels. But seat belt laws are justified for the same reason that drunk driving laws are justified: individual choices that significantly increase the risk of serious injury impose costs on society as a whole through emergency services, healthcare, and lost productivity. Personal freedom does not extend to imposing substantial costs on others.`,
    questionStem: "The public health advocate's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "rejecting the analogy between seat belt laws and other personal freedom issues" },
      { letter: "B", text: "arguing that seat belt laws have reduced traffic fatalities" },
      { letter: "C", text: "demonstrating that most people support seat belt laws" },
      { letter: "D", text: "drawing a parallel to an accepted regulation to justify a similar one" },
      { letter: "E", text: "showing that the freedom to not wear seat belts is not constitutionally protected" },
    ],
    correctAnswer: "D",
    explanation: "The advocate compares seat belt laws to drunk driving laws, which are presumably accepted, to argue that seat belt laws are similarly justified. Both involve individual choices that impose societal costs. By showing the parallel, the advocate attempts to transfer the acceptability of drunk driving laws to seat belt laws. This is argument by analogy. The argument does not actually cite statistics, public opinion, constitutional law, or reject analogies.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Museum curator: Some critics claim that displaying human remains in museums is always disrespectful to the deceased. However, this position leads to absurd conclusions. By this logic, medical schools should not use cadavers for education, and forensic scientists should not examine skeletal remains to identify crime victims or learn about past societies. Since these practices are clearly valuable and not inherently disrespectful, the blanket prohibition on displaying human remains must be rejected.`,
    questionStem: "The curator's argument employs which one of the following reasoning techniques?",
    answerChoices: [
      { letter: "A", text: "providing statistical evidence that contradicts the critics' claims" },
      { letter: "B", text: "arguing that the critics are motivated by personal bias" },
      { letter: "C", text: "showing that the critics' principle would prohibit widely accepted practices" },
      { letter: "D", text: "demonstrating that most scholars reject the critics' position" },
      { letter: "E", text: "distinguishing between different types of human remains" },
    ],
    correctAnswer: "C",
    explanation: "The curator uses reductio ad absurdum: taking the critics' principle (displaying human remains is disrespectful) and showing it leads to unacceptable conclusions (prohibiting medical education and forensic science). By demonstrating that consistent application of the principle would forbid accepted practices, the curator argues the principle must be rejected. This is a classic method of showing a principle is too broad.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The senator claims that tariffs on imported goods will protect domestic jobs. But tariffs raise prices for consumers and businesses that use imported materials. These higher costs reduce consumer spending and business investment, ultimately destroying more jobs than the tariffs protect. The historical record confirms this: countries that have imposed high tariffs have experienced slower economic growth and net job losses.`,
    questionStem: "The economist's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "attacking the senator's credentials rather than addressing the argument" },
      { letter: "B", text: "presenting a causal mechanism and supporting it with historical evidence" },
      { letter: "C", text: "arguing from the popularity of free trade policies" },
      { letter: "D", text: "demonstrating that the senator's claim is internally contradictory" },
      { letter: "E", text: "showing that the senator has changed positions on trade policy" },
    ],
    correctAnswer: "B",
    explanation: "The economist first explains the causal mechanism by which tariffs harm the economy (higher prices reduce spending and investment, destroying jobs). Then the economist cites historical evidence confirming this mechanism (countries with high tariffs experienced slower growth and job losses). This combines theoretical reasoning with empirical support. The argument addresses the substance of the claim, not the senator personally.",
    difficulty: "easy",
  },
  {
    id: "lr-bank20-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Botanist: It has been proposed that plants evolved flowers primarily to attract pollinators. However, the earliest flowering plants appear in the fossil record at a time when flying insects were already abundant and diverse. If flowers evolved specifically to attract pollinators, we would expect to see flowers and flying insects diversifying together. The fact that insects diversified first suggests that early flowers may have served other primary functions, with pollinator attraction being a later adaptation.`,
    questionStem: "Which one of the following most accurately describes the method of reasoning used by the botanist?",
    answerChoices: [
      { letter: "A", text: "providing an alternative hypothesis without supporting evidence" },
      { letter: "B", text: "arguing that a hypothesis makes a prediction inconsistent with observed facts" },
      { letter: "C", text: "demonstrating that the proposed hypothesis is internally contradictory" },
      { letter: "D", text: "showing that authorities in the field disagree with the proposal" },
      { letter: "E", text: "proving that flowers could not have attracted early pollinators" },
    ],
    correctAnswer: "B",
    explanation: "The botanist identifies what the hypothesis would predict (flowers and insects diversifying together) and shows this prediction doesn't match the fossil evidence (insects diversified first). This is a form of disconfirmation: if the hypothesis were true, we would expect X, but we observe not-X, so the hypothesis is doubtful. The botanist challenges the hypothesis by testing its implications against evidence.",
    difficulty: "medium",
  },

  // POINT-AT-ISSUE QUESTIONS (3 questions: lr-bank20-043 to lr-bank20-045)
  {
    id: "lr-bank20-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Reyes: Artificial intelligence will never truly understand human language. Language comprehension requires lived experience—embodiment, emotion, social interaction—that no AI system can possess. Current AI models merely simulate understanding through pattern matching.

Dr. Chen: While AI lacks human experience, that doesn't preclude genuine understanding. Understanding is a matter of functional competence: the ability to use language correctly, draw appropriate inferences, and respond sensibly. By this measure, advanced AI systems already demonstrate real language understanding.`,
    questionStem: "The point at issue between Dr. Reyes and Dr. Chen is whether",
    answerChoices: [
      { letter: "A", text: "current AI systems can match human language abilities" },
      { letter: "B", text: "lived experience is necessary for genuine language understanding" },
      { letter: "C", text: "AI technology will continue to improve in the future" },
      { letter: "D", text: "pattern matching is a component of human language processing" },
      { letter: "E", text: "functional competence is sufficient for language understanding" },
    ],
    correctAnswer: "B",
    explanation: "Dr. Reyes claims lived experience is necessary for understanding—without it, AI cannot truly understand. Dr. Chen disagrees, arguing that functional competence suffices regardless of experiential differences. Their core disagreement is whether lived experience is required for genuine understanding. E is close but B captures the disagreement more precisely, as Reyes makes experience necessary while Chen makes it unnecessary. A is not directly debated.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Mills: Universities should not divest from fossil fuel companies. Divestment is merely symbolic and has no effect on company behavior. These companies will simply find other investors. Furthermore, fossil fuel investments fund scholarships and research.

Professor Yang: The symbolic nature of divestment is precisely the point. Divestment declares that fossil fuel companies are morally unacceptable partners. This shifts public discourse and pressures companies to change. The fact that other investors might buy the shares doesn't diminish the moral statement being made.`,
    questionStem: "Professor Mills and Professor Yang disagree about whether",
    answerChoices: [
      { letter: "A", text: "fossil fuel investments provide any financial benefits to universities" },
      { letter: "B", text: "divestment campaigns are primarily symbolic in nature" },
      { letter: "C", text: "symbolic actions can have meaningful real-world effects" },
      { letter: "D", text: "fossil fuel companies are morally acceptable business partners" },
      { letter: "E", text: "universities have a responsibility to take moral positions" },
    ],
    correctAnswer: "C",
    explanation: "Mills argues divestment is 'merely symbolic' with 'no effect'—implying symbolic actions lack meaningful impact. Yang argues the symbolic nature is 'precisely the point' and 'shifts public discourse and pressures companies'—claiming symbolic actions can have real effects. They agree divestment is symbolic but disagree about whether symbolic actions matter. B is something they agree on. D and E aren't directly addressed by both.",
    difficulty: "hard",
  },
  {
    id: "lr-bank20-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Scientist A: The discovery of microbial life on Mars would be the most important scientific finding in history. It would prove that life emerges readily given the right conditions, suggesting the universe is full of living organisms.

Scientist B: Finding microbial life on Mars would be significant, but we couldn't conclude that life emerges readily. Mars and Earth share material through meteorite impacts; Martian microbes might have originated from Earth, or vice versa. Life could still be extraordinarily rare even if found on two neighboring planets.`,
    questionStem: "The main point of disagreement between the scientists concerns",
    answerChoices: [
      { letter: "A", text: "whether finding life on Mars would be an important discovery" },
      { letter: "B", text: "whether material is exchanged between Earth and Mars through meteorites" },
      { letter: "C", text: "what conclusions about the prevalence of life in the universe could be drawn from discovering Martian microbes" },
      { letter: "D", text: "whether life on Earth might have originated from Mars" },
      { letter: "E", text: "whether microbial life could survive in the Martian environment" },
    ],
    correctAnswer: "C",
    explanation: "Scientist A claims Martian life would prove life emerges readily, implying the universe is full of life. Scientist B disagrees about this inference, arguing Martian life might share origins with Earth life, so finding life on both planets wouldn't prove life is common. They agree the discovery would be significant (A) but disagree about what it would prove about life's prevalence. B is mentioned only by Scientist B as supporting evidence.",
    difficulty: "medium",
  },

  // PARALLEL-REASONING QUESTIONS (3 questions: lr-bank20-046 to lr-bank20-048)
  {
    id: "lr-bank20-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some historians argue that great leaders shape historical events. But leaders only succeed when conditions are favorable—when economic, social, and political circumstances allow their vision to take hold. Without the right conditions, even brilliant leadership fails. Therefore, historical conditions are more fundamental than individual leadership in determining the course of events.`,
    questionStem: "Which one of the following arguments is most similar in its pattern of reasoning to the argument above?",
    answerChoices: [
      { letter: "A", text: "Some claim that talent is the key to athletic success. But talented athletes fail without proper coaching and training. Therefore, coaching matters more than raw talent in athletic achievement." },
      { letter: "B", text: "Many believe that hard work guarantees success. But many hardworking people fail due to circumstances beyond their control. Therefore, luck plays a role in success." },
      { letter: "C", text: "Educators often emphasize the importance of good teachers. But student success depends on many factors including family support and peer influence. Therefore, teachers alone cannot determine student outcomes." },
      { letter: "D", text: "Biologists study how genes influence traits. But environmental factors also affect how genes are expressed. Therefore, nature and nurture both contribute to development." },
      { letter: "E", text: "Some seeds grow better in certain soils. Therefore, soil quality is the only factor that determines plant growth." },
    ],
    correctAnswer: "A",
    explanation: "The original argument: X (leadership) is said to be key, but X only succeeds when Y (conditions) is favorable, therefore Y is more fundamental than X. Answer A follows this pattern: X (talent) is said to be key, but X only succeeds with Y (coaching/training), therefore Y matters more than X. Both arguments demote a commonly cited factor by showing its dependence on another factor. C is similar but concludes both matter rather than ranking one higher. D explicitly endorses both factors equally.",
    difficulty: "hard",
  },
  {
    id: "lr-bank20-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `No one who has read the complete works of Shakespeare is unfamiliar with his major plays. Anyone who teaches English literature has read the complete works of Shakespeare. Therefore, no one who teaches English literature is unfamiliar with Shakespeare's major plays.`,
    questionStem: "The pattern of reasoning in the argument is most closely paralleled by which one of the following?",
    answerChoices: [
      { letter: "A", text: "No vegetarians eat beef. Some athletes are vegetarians. Therefore, some athletes do not eat beef." },
      { letter: "B", text: "All trained doctors can recognize common symptoms. Everyone at this clinic is a trained doctor. Therefore, everyone at this clinic can recognize common symptoms." },
      { letter: "C", text: "No one who exercises regularly is in poor physical condition. All marathon runners exercise regularly. Therefore, no marathon runners are in poor physical condition." },
      { letter: "D", text: "Some musicians play multiple instruments. All orchestra members are musicians. Therefore, some orchestra members play multiple instruments." },
      { letter: "E", text: "No beginners can solve advanced problems. Some students are not beginners. Therefore, some students can solve advanced problems." },
    ],
    correctAnswer: "C",
    explanation: "Original structure: No A (read complete works) is B (unfamiliar with plays). All C (English lit teachers) are A. Therefore, no C is B. Answer C follows this: No A (exercises regularly) is B (poor condition). All C (marathon runners) are A. Therefore, no C is B. Both use a universal negative and a universal affirmative to derive a universal negative conclusion. B has similar structure but uses positive rather than negative statements for the first premise.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy enters a recession, unemployment will rise. If unemployment rises, consumer spending will decline. The economy has entered a recession. Therefore, consumer spending will decline.`,
    questionStem: "The pattern of reasoning in the argument is most similar to which one of the following?",
    answerChoices: [
      { letter: "A", text: "If there is a drought, crop yields will fall. If crop yields fall, food prices will increase. Food prices have increased. Therefore, there must have been a drought." },
      { letter: "B", text: "If the temperature drops, water will freeze. If water freezes, pipes may burst. The temperature has dropped. Therefore, pipes may burst." },
      { letter: "C", text: "If a student studies, they may pass. If they pass, they can graduate. The student did not graduate. Therefore, the student did not study." },
      { letter: "D", text: "If interest rates rise, borrowing will decrease. If the central bank is concerned about inflation, interest rates will rise. The central bank is not concerned about inflation. Therefore, borrowing will not decrease." },
      { letter: "E", text: "If taxes increase, the deficit will shrink. Taxes have increased. Therefore, the economy will improve." },
    ],
    correctAnswer: "B",
    explanation: "The original uses a chain of conditionals (if A then B, if B then C) and affirms the first antecedent (A is true) to conclude C. This is valid hypothetical syllogism with modus ponens. B follows the same pattern: if A (temperature drops) then B (water freezes), if B then C (pipes may burst), A is true, therefore C. A and C affirm the consequent or deny incorrectly. D denies the antecedent. E doesn't complete the chain properly.",
    difficulty: "easy",
  },

  // INFERENCE QUESTIONS (2 questions: lr-bank20-049 to lr-bank20-050)
  {
    id: "lr-bank20-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Recent archaeological evidence indicates that ancient Polynesians reached South America at least 300 years before Europeans arrived. Sweet potatoes, which originated in South America, were being cultivated throughout Polynesia by 1000 CE. The word for sweet potato in many Polynesian languages closely resembles the Quechua word used in South America. DNA analysis of ancient sweet potato samples from Polynesia shows genetic signatures matching South American varieties.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Polynesian voyages to South America were more common than European voyages" },
      { letter: "B", text: "Sweet potatoes could not have reached Polynesia without human transport" },
      { letter: "C", text: "The Polynesian and Quechua languages share a common ancestor" },
      { letter: "D", text: "There was some form of contact between Polynesian and South American cultures before European arrival" },
      { letter: "E", text: "Polynesians established permanent settlements in South America" },
    ],
    correctAnswer: "D",
    explanation: "The passage describes sweet potatoes (from South America) cultivated in Polynesia by 1000 CE, similar words for the crop in both regions, and matching genetic signatures. These facts together strongly support that contact occurred—either Polynesians traveled to South America or South Americans traveled to Polynesia—before Europeans arrived (post-1492). D must be true given this evidence. A, C, and E go beyond what's stated. B is probable but not strictly necessary from these facts.",
    difficulty: "medium",
  },
  {
    id: "lr-bank20-050",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All partners in the law firm must have passed the bar examination. Some partners in the firm specialize in corporate law, while others specialize in litigation. No one can specialize in both corporate law and litigation simultaneously. Martinez is a partner who does not specialize in corporate law.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Martinez specializes in litigation" },
      { letter: "B", text: "Martinez has passed the bar examination" },
      { letter: "C", text: "All litigators in the firm are partners" },
      { letter: "D", text: "Some corporate law specialists have not passed the bar examination" },
      { letter: "E", text: "Martinez does not work for the law firm" },
    ],
    correctAnswer: "B",
    explanation: "The passage states all partners have passed the bar, and Martinez is a partner. Therefore, Martinez must have passed the bar. This follows necessarily. A seems tempting—Martinez doesn't specialize in corporate law, and there are only two specializations mentioned—but the passage says 'some partners' specialize in each area, not that all partners specialize in one or the other. Martinez might have no specialization. C reverses the relationship. D contradicts the first statement. E contradicts Martinez being a partner.",
    difficulty: "hard",
  },
];
