// Logical Reasoning Questions Bank - Set 28
// High-quality LSAT-style questions covering all question types

import { Question } from "../lsat-types";

export const lrQuestionsSet28: Question[] = [
  // FLAW QUESTIONS (10 questions)
  {
    id: "lr-bank28-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: The proposed legislation would require all employers to provide twelve weeks of paid family leave. Opponents argue this would harm small businesses. However, the legislation is supported by major corporations like TechGiant Inc. and GlobalBank. Since these are highly successful businesses, the legislation clearly cannot be harmful to business interests.`,
    questionStem: "The reasoning in the legal scholar's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that legislation supported by some businesses must benefit all businesses" },
      { letter: "B", text: "fails to consider whether the corporations cited have ulterior motives for supporting the legislation" },
      { letter: "C", text: "ignores the possibility that small businesses operate under different constraints than large corporations" },
      { letter: "D", text: "presumes that successful businesses always make decisions that benefit the economy as a whole" },
      { letter: "E", text: "conflates the interests of employers with the interests of employees" },
    ],
    correctAnswer: "C",
    explanation: "The argument commits the fallacy of false analogy by treating large corporations and small businesses as equivalent. Major corporations like TechGiant Inc. can absorb the costs of paid leave programs, while small businesses with tighter margins may struggle. The opposition specifically came from small businesses, which the scholar dismisses based on support from large corporations.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: My clients who eliminated processed sugar from their diets all reported feeling more energetic within two weeks. This proves that processed sugar causes fatigue. Anyone who wants to feel more energetic should therefore eliminate processed sugar from their diet.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies solely on self-reported data rather than objective measurements" },
      { letter: "B", text: "fails to consider that other dietary changes may have accompanied the elimination of processed sugar" },
      { letter: "C", text: "assumes without justification that what worked for the nutritionist's clients will work for everyone" },
      { letter: "D", text: "ignores the possibility that some people may experience adverse effects from eliminating processed sugar" },
      { letter: "E", text: "does not specify how much processed sugar the clients were consuming before the change" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits a causal fallacy by assuming that eliminating processed sugar was the cause of increased energy. People who eliminate processed sugar often make other dietary changes simultaneously (eating more whole foods, more vegetables, etc.) or other lifestyle changes. Without controlling for these factors, we cannot attribute the energy increase solely to sugar elimination.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `City Council Member: Our city's public transportation system operates at a significant financial deficit each year. Private transportation companies, by contrast, operate profitably. This demonstrates that privately operated transportation is inherently more efficient than publicly operated transportation, and we should therefore privatize our public transit system.`,
    questionStem: "The argument is flawed in that it",
    answerChoices: [
      { letter: "A", text: "ignores the possibility that private companies achieve profitability by serving only the most lucrative routes" },
      { letter: "B", text: "assumes that financial profitability is the only measure of efficiency" },
      { letter: "C", text: "fails to consider that public transit may receive inadequate funding from the city" },
      { letter: "D", text: "overlooks the social benefits that public transportation provides beyond transportation itself" },
      { letter: "E", text: "does not establish that the city's public transportation system has always operated at a deficit" },
    ],
    correctAnswer: "A",
    explanation: "Private transportation companies can choose their routes and passengers, selecting only profitable ones. Public transit must serve all areas, including unprofitable routes to low-income neighborhoods, elderly populations, and off-peak hours. Comparing profitability without accounting for these different obligations is misleading about relative efficiency.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor: Students in my philosophy courses who participate actively in class discussions consistently earn higher grades than those who remain silent. Therefore, to improve their grades, quiet students should speak up more in class.`,
    questionStem: "The reasoning in the professor's argument is questionable because it",
    answerChoices: [
      { letter: "A", text: "assumes that all students are equally capable of participating in class discussions" },
      { letter: "B", text: "treats a correlation between participation and grades as evidence that participation causes higher grades" },
      { letter: "C", text: "fails to consider that some students may have valid reasons for not speaking in class" },
      { letter: "D", text: "presumes that grades are an accurate measure of learning in philosophy courses" },
      { letter: "E", text: "overlooks the possibility that forced participation might lower the quality of class discussions" },
    ],
    correctAnswer: "B",
    explanation: "The professor commits a correlation-causation fallacy. Students who participate actively might already understand the material better (hence both participation and high grades) or be more confident (affecting both behaviors). Simply speaking more would not address the underlying factors that cause both the participation and the grades.",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Political analyst: The senator claims to be fiscally conservative, yet she voted for a bill that increased government spending by $50 billion. Her claim to fiscal conservatism is therefore completely unfounded.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "attacks the senator's character rather than addressing the merits of the spending bill" },
      { letter: "B", text: "assumes that fiscal conservatives must oppose all increases in government spending" },
      { letter: "C", text: "fails to consider the senator's overall voting record on fiscal matters" },
      { letter: "D", text: "does not explain what fiscal conservatism requires in terms of specific policies" },
      { letter: "E", text: "ignores the possibility that the bill included provisions to offset the spending increase" },
    ],
    correctAnswer: "B",
    explanation: "The argument employs a rigid definition fallacy. Fiscal conservatism does not necessarily require opposing all spending increases. A fiscal conservative might support spending that reduces costs elsewhere, funds essential services efficiently, or prevents larger future expenditures. One vote supporting increased spending does not invalidate a claim to fiscal conservatism.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Environmental activist: The chemical company claims that its new pesticide is safe for the environment. But the company profits from selling this pesticide, so it has a financial incentive to claim the pesticide is safe. Therefore, the pesticide is likely not safe for the environment.`,
    questionStem: "The argument's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "concludes that a claim is false simply because the person making it has an incentive to make it" },
      { letter: "B", text: "fails to consider evidence that might support the company's safety claims" },
      { letter: "C", text: "assumes that companies never tell the truth about their products" },
      { letter: "D", text: "overlooks the possibility that regulatory agencies have tested the pesticide" },
      { letter: "E", text: "does not specify what environmental harms the pesticide might cause" },
    ],
    correctAnswer: "A",
    explanation: "This is a circumstantial ad hominem fallacy. While the company's financial interest is relevant to consider, having a motive to make a claim does not prove the claim is false. Many true claims are made by people with incentives to make them. The argument should evaluate the evidence for safety rather than just dismissing the claim based on the source's interests.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The ancient Mayans were skilled astronomers who accurately predicted eclipses. Some researchers have claimed that the Mayans also predicted specific world events that would occur in the twenty-first century. Since the Mayans were demonstrably accurate in their astronomical predictions, we should take seriously their alleged predictions about world events.`,
    questionStem: "The historian's argument is most vulnerable to the criticism that it",
    answerChoices: [
      { letter: "A", text: "fails to provide evidence that the Mayans actually made predictions about the twenty-first century" },
      { letter: "B", text: "assumes that skill in one area of prediction indicates skill in a completely different area" },
      { letter: "C", text: "does not explain the methods by which the Mayans made their astronomical predictions" },
      { letter: "D", text: "overlooks the possibility that the Mayans' astronomical predictions were sometimes inaccurate" },
      { letter: "E", text: "conflates the Mayans' beliefs about astronomy with their beliefs about world events" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits a fallacy of false expertise or unwarranted generalization. Accuracy in predicting eclipses (which follow mathematical patterns) does not indicate ability to predict unpredictable human events like wars or social changes. Expertise in one domain does not automatically transfer to unrelated domains.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Medical researcher: A new study shows that patients who took the experimental drug experienced a 30 percent reduction in symptoms compared to the placebo group. Critics point out that the study was funded by the pharmaceutical company that developed the drug. However, the methodology was peer-reviewed and followed established protocols. Therefore, the criticism based on funding source is invalid.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "dismisses a legitimate concern about potential bias without fully addressing it" },
      { letter: "B", text: "assumes that peer review guarantees the accuracy of research findings" },
      { letter: "C", text: "fails to consider that the pharmaceutical company may have influenced which studies were published" },
      { letter: "D", text: "overlooks the possibility that the study's sample size was too small" },
      { letter: "E", text: "presumes that proper methodology eliminates all possibility of biased results" },
    ],
    correctAnswer: "E",
    explanation: "While proper methodology reduces bias, it does not eliminate all concerns about funding-source bias. Bias can occur in study design decisions, interpretation of results, or publication decisions that are not fully captured by methodology review. The argument too quickly dismisses the funding concern by pointing only to methodology.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-009",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Music critic: Modern pop music lacks the artistic depth of classical compositions from previous centuries. Classical composers like Mozart and Beethoven created works of enduring brilliance. Today's pop songs, by contrast, are quickly forgotten. This shows that musical artistry has declined over time.`,
    questionStem: "The argument's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "compares the best examples from one era with typical examples from another" },
      { letter: "B", text: "assumes that popularity is a reliable indicator of artistic quality" },
      { letter: "C", text: "fails to consider that different genres have different artistic standards" },
      { letter: "D", text: "overlooks the possibility that some contemporary classical music is of high quality" },
      { letter: "E", text: "does not define what constitutes artistic depth in music" },
    ],
    correctAnswer: "A",
    explanation: "This is a survivorship bias fallacy. The critic compares the greatest classical composers whose works survived for centuries with the average pop music of today. Most music from previous centuries has been forgotten, just like most of today's music will be. A fair comparison would compare either the best of both eras or the average of both eras.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-010",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Some argue that genetic enhancement of human embryos is morally wrong because it is unnatural. But wearing eyeglasses is also unnatural, and no one considers that morally wrong. Therefore, the unnaturalness of genetic enhancement is not a valid moral objection to it.`,
    questionStem: "The argument is most vulnerable to criticism on which of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It assumes that two practices are morally equivalent simply because they share one characteristic" },
      { letter: "B", text: "It fails to consider that genetic enhancement may have consequences that wearing glasses does not" },
      { letter: "C", text: "It presumes that opponents of genetic enhancement base their objection solely on unnaturalness" },
      { letter: "D", text: "It does not explain why wearing eyeglasses should be considered unnatural" },
      { letter: "E", text: "It ignores the distinction between enhancing existing traits and correcting deficiencies" },
    ],
    correctAnswer: "B",
    explanation: "The argument makes a weak analogy. While both practices may be 'unnatural,' genetic enhancement of embryos involves fundamentally different considerations: heritability of changes, consent of future persons, potential for creating inequality, and unknown long-term effects. The argument dismisses unnaturalness as a concern without addressing whether other aspects of genetic enhancement raise valid moral issues.",
    difficulty: "hard",
  },

  // STRENGTHEN QUESTIONS (8 questions)
  {
    id: "lr-bank28-011",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologist: The cave paintings found in Southern France are approximately 35,000 years old, making them among the oldest known examples of human art. The sophistication of these paintings suggests that humans did not suddenly develop artistic abilities at this time. Rather, artistic expression likely developed gradually over thousands of years before these paintings were created.`,
    questionStem: "Which one of the following, if true, most strengthens the archaeologist's argument?",
    answerChoices: [
      { letter: "A", text: "Cave paintings from other regions of Europe have been dated to approximately the same period" },
      { letter: "B", text: "Fragments of decorated tools and jewelry dating back 100,000 years have been found in Africa" },
      { letter: "C", text: "Modern artists require years of training to achieve comparable levels of sophistication" },
      { letter: "D", text: "The pigments used in the cave paintings were derived from locally available minerals" },
      { letter: "E", text: "The caves where the paintings were found were difficult to access" },
    ],
    correctAnswer: "B",
    explanation: "Finding decorated artifacts that predate the cave paintings by 65,000 years directly supports the claim that artistic expression developed gradually before the French cave paintings. This provides concrete evidence of earlier artistic activity, showing that humans had been creating art long before these cave paintings.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: The recent increase in remote work has led to a decline in commercial real estate values in major cities. This decline will likely continue because many companies have discovered that remote work arrangements do not reduce productivity and significantly reduce overhead costs.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Several major technology companies have announced permanent remote work options for their employees" },
      { letter: "B", text: "Commercial real estate values in suburban areas have increased during the same period" },
      { letter: "C", text: "Surveys show that most employees prefer working from home at least part of the time" },
      { letter: "D", text: "The construction of new commercial office buildings has slowed significantly" },
      { letter: "E", text: "Some companies are converting unused office space into residential apartments" },
    ],
    correctAnswer: "A",
    explanation: "The economist argues that the decline will continue because remote work has proven effective. Major technology companies committing to permanent remote work demonstrates that influential businesses are acting on this conclusion, directly supporting the prediction that reduced demand for commercial space will persist.",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Marine biologist: The decline in shark populations is causing an increase in ray populations in coastal waters. Rays feed on scallops and other shellfish, so this imbalance is threatening commercially important shellfish fisheries. Protecting sharks is therefore essential for maintaining healthy shellfish populations.`,
    questionStem: "Which one of the following, if true, provides the most support for the marine biologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Shark populations have declined by over 70 percent in the past fifty years" },
      { letter: "B", text: "Areas where shark populations have remained stable show no unusual increase in ray populations" },
      { letter: "C", text: "Rays are not the only predators of shellfish in coastal waters" },
      { letter: "D", text: "Commercial fishing operations have also contributed to the decline in shellfish populations" },
      { letter: "E", text: "Some species of sharks also consume shellfish" },
    ],
    correctAnswer: "B",
    explanation: "This provides a control comparison that strengthens the causal chain. If areas with stable shark populations have normal ray populations, this supports the claim that shark decline causes ray increase. This evidence connects the first step of the argument (shark decline leads to ray increase) to the overall conclusion about protecting sharks.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Exposure to natural environments reduces stress and improves mental well-being. Therefore, hospitals should incorporate more natural elements such as plants, natural lighting, and views of outdoor spaces to help patients recover more quickly.`,
    questionStem: "Which one of the following, if true, most strengthens the psychologist's argument?",
    answerChoices: [
      { letter: "A", text: "Many patients report feeling more comfortable in rooms with natural lighting" },
      { letter: "B", text: "Reducing stress has been shown to speed physical healing and recovery" },
      { letter: "C", text: "Some hospitals have already begun incorporating natural elements into their designs" },
      { letter: "D", text: "Hospital staff also experience reduced stress when working in naturalistic environments" },
      { letter: "E", text: "Natural lighting is more cost-effective than artificial lighting in the long run" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes a connection between reduced stress/improved mental well-being and faster patient recovery. Answer B explicitly provides this connection by establishing that stress reduction speeds physical healing. This bridges the gap between the premise (nature reduces stress) and the conclusion (nature helps recovery).",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The unsigned painting recently discovered in an Italian villa is almost certainly the work of Caravaggio. The dramatic use of chiaroscuro, the realistic depiction of human figures, and the characteristic diagonal composition all match Caravaggio's known style perfectly.`,
    questionStem: "Which one of the following, if true, most strengthens the art historian's conclusion?",
    answerChoices: [
      { letter: "A", text: "Chemical analysis of the pigments shows they are consistent with materials available in early 17th century Italy" },
      { letter: "B", text: "Historical records indicate that Caravaggio visited the villa where the painting was discovered" },
      { letter: "C", text: "No other painter of that era is known to have combined all three of these stylistic elements" },
      { letter: "D", text: "The canvas and stretcher bars are of a type commonly used by Italian painters of the period" },
      { letter: "E", text: "Caravaggio is known to have painted several works that were never signed" },
    ],
    correctAnswer: "C",
    explanation: "The historian bases the attribution on stylistic elements. If no other painter combined all three elements, then the stylistic evidence more definitively points to Caravaggio. This eliminates alternative explanations for the style match, strengthening the attribution.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Education researcher: Students who learn to play musical instruments in elementary school perform better in mathematics in later grades. Music education should therefore be mandatory in all elementary schools as a way to improve mathematical achievement.`,
    questionStem: "Which one of the following, if true, most strengthens the researcher's argument?",
    answerChoices: [
      { letter: "A", text: "Students who excel in mathematics often choose to learn musical instruments" },
      { letter: "B", text: "Learning music develops spatial-temporal reasoning skills that are foundational to mathematical thinking" },
      { letter: "C", text: "Many successful mathematicians are also accomplished musicians" },
      { letter: "D", text: "Schools with music programs tend to have higher overall academic achievement" },
      { letter: "E", text: "Students enjoy mathematics classes more when they also study music" },
    ],
    correctAnswer: "B",
    explanation: "Answer B provides a causal mechanism explaining HOW music education improves math performance. By establishing that music develops spatial-temporal reasoning, which underlies mathematical thinking, it supports the claim that music education causes math improvement rather than just being correlated with it.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Criminologist: Cities that have implemented community policing programs have experienced reductions in violent crime rates. Community policing, which emphasizes building relationships between police officers and community members, should therefore be adopted more widely as a crime prevention strategy.`,
    questionStem: "Which one of the following, if true, most strengthens the criminologist's argument?",
    answerChoices: [
      { letter: "A", text: "Community policing requires fewer officers per capita than traditional policing methods" },
      { letter: "B", text: "Violent crime rates have been declining nationally regardless of policing strategies" },
      { letter: "C", text: "Cities that did not implement community policing during the same period saw no comparable reduction in violent crime" },
      { letter: "D", text: "Community policing programs improve public perception of law enforcement" },
      { letter: "E", text: "Officers in community policing programs report higher job satisfaction" },
    ],
    correctAnswer: "C",
    explanation: "This provides a control group comparison. If cities without community policing did not see similar crime reductions, this strengthens the causal link between community policing and reduced crime. It helps rule out the possibility that crime was declining for unrelated reasons.",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-018",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Botanist: The recent decline in bee populations is threatening agricultural productivity because bees pollinate approximately one-third of food crops. We should ban the use of neonicotinoid pesticides, which have been linked to bee die-offs, to protect both bee populations and food security.`,
    questionStem: "Which one of the following, if true, most strengthens the botanist's argument?",
    answerChoices: [
      { letter: "A", text: "Some crops can be pollinated by wind or other insects besides bees" },
      { letter: "B", text: "Regions that have banned neonicotinoid pesticides have seen stabilization of bee populations" },
      { letter: "C", text: "Farmers have become increasingly dependent on commercial bee colonies for pollination" },
      { letter: "D", text: "Neonicotinoid pesticides are highly effective at controlling crop pests" },
      { letter: "E", text: "Bee populations have declined in both agricultural and non-agricultural areas" },
    ],
    correctAnswer: "B",
    explanation: "This provides direct evidence that banning neonicotinoids achieves the desired outcome. If bee populations have stabilized where these pesticides are banned, this supports the causal claim that the pesticides cause bee decline and that banning them is an effective solution.",
    difficulty: "medium",
  },

  // WEAKEN QUESTIONS (8 questions)
  {
    id: "lr-bank28-019",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Business consultant: Companies should eliminate annual performance reviews because employees report that these reviews are stressful and demoralizing. Replacing annual reviews with more frequent, informal feedback will improve employee morale and ultimately lead to better performance.`,
    questionStem: "Which one of the following, if true, most weakens the consultant's argument?",
    answerChoices: [
      { letter: "A", text: "Some managers lack the training to provide effective informal feedback" },
      { letter: "B", text: "Annual reviews provide a structured opportunity for discussing career advancement" },
      { letter: "C", text: "Studies show that employees perform best when they receive both formal and informal feedback" },
      { letter: "D", text: "The stress employees report is often related to the outcomes of reviews rather than the review process itself" },
      { letter: "E", text: "Many employees prefer to receive criticism in private rather than in informal settings" },
    ],
    correctAnswer: "D",
    explanation: "If the stress comes from outcomes (raises, promotions, terminations) rather than the review process, then eliminating formal reviews will not eliminate the stress. The stressful decisions would still need to be made and communicated, just through different means. This undermines the consultant's assumption that changing the format will improve morale.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Urban planner: Converting downtown streets to pedestrian-only zones will benefit local businesses. Studies show that pedestrians spend more money per visit than drivers in retail areas. Therefore, removing car traffic from downtown will increase retail sales.`,
    questionStem: "Which one of the following, if true, most seriously weakens the urban planner's argument?",
    answerChoices: [
      { letter: "A", text: "Pedestrian zones require ongoing maintenance and management costs" },
      { letter: "B", text: "Some retailers in pedestrian zones have reported increased shoplifting" },
      { letter: "C", text: "Removing car access significantly reduces the total number of visitors to retail areas" },
      { letter: "D", text: "Drivers who cannot park downtown may choose to shop at suburban malls instead" },
      { letter: "E", text: "Not all downtown businesses are retail establishments" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that pedestrians will continue visiting in similar or greater numbers. If removing car access significantly reduces total visitors, then even if each pedestrian spends more, total sales could decline. The higher spending per pedestrian would be offset by fewer total customers.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: Social media use causes depression in teenagers. Teenagers who spend more than three hours per day on social media are twice as likely to report symptoms of depression compared to those who use it less frequently.`,
    questionStem: "Which one of the following, if true, most undermines the psychologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Teenagers who report depression symptoms are more likely to turn to social media for distraction and connection" },
      { letter: "B", text: "Some teenagers use social media primarily for educational purposes" },
      { letter: "C", text: "Adult social media users do not show the same correlation with depression" },
      { letter: "D", text: "Teenagers who use social media heavily often also experience sleep deprivation" },
      { letter: "E", text: "Some popular social media platforms have implemented features designed to limit user time" },
    ],
    correctAnswer: "A",
    explanation: "This suggests reverse causation. If depressed teenagers seek out social media as a coping mechanism, then depression causes social media use rather than the other way around. The correlation would exist without social media causing depression, undermining the psychologist's causal conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Environmental scientist: Electric vehicles will significantly reduce carbon emissions from transportation. As more drivers switch to electric vehicles, we can expect substantial improvements in air quality and reductions in greenhouse gas emissions.`,
    questionStem: "Which one of the following, if true, most weakens the environmental scientist's argument?",
    answerChoices: [
      { letter: "A", text: "Electric vehicle batteries require replacement every eight to ten years" },
      { letter: "B", text: "The majority of electricity used to charge electric vehicles is generated by burning fossil fuels" },
      { letter: "C", text: "Electric vehicles are currently more expensive than comparable gasoline-powered vehicles" },
      { letter: "D", text: "Some electric vehicle owners continue to own gasoline-powered vehicles for long trips" },
      { letter: "E", text: "The production of electric vehicles generates more carbon emissions than the production of traditional vehicles" },
    ],
    correctAnswer: "B",
    explanation: "If electric vehicles are charged using electricity from fossil fuels, then the carbon emissions are merely shifted from the tailpipe to the power plant rather than eliminated. This undermines the claim that electric vehicles will significantly reduce overall carbon emissions.",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The Roman Empire fell primarily because of moral decay among its citizens. Contemporary accounts describe widespread corruption, hedonism, and a decline in civic virtue. These internal weaknesses made the empire vulnerable to external threats that it had previously been able to repel.`,
    questionStem: "Which one of the following, if true, most weakens the historian's argument?",
    answerChoices: [
      { letter: "A", text: "The Western and Eastern Roman Empires experienced different fates despite similar cultural conditions" },
      { letter: "B", text: "Roman writers from every era complained about moral decay in their society" },
      { letter: "C", text: "The Germanic tribes that invaded Rome had different cultural values" },
      { letter: "D", text: "Economic factors such as inflation and taxation also contributed to the empire's decline" },
      { letter: "E", text: "Some Roman emperors attempted to restore traditional moral values" },
    ],
    correctAnswer: "B",
    explanation: "If Romans throughout history complained about moral decay, then such complaints cannot explain the empire's fall at a particular time. Moral decay was always described as present, yet the empire persisted for centuries. This suggests that the contemporary accounts of decay do not indicate a unique causal factor for the fall.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-024",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Pharmaceutical researcher: Our new medication for chronic pain is superior to existing treatments because patients in clinical trials reported greater pain relief with fewer side effects. Doctors should therefore prescribe this medication instead of current alternatives.`,
    questionStem: "Which one of the following, if true, most seriously undermines the researcher's recommendation?",
    answerChoices: [
      { letter: "A", text: "The clinical trials lasted only twelve weeks, while chronic pain often requires years of treatment" },
      { letter: "B", text: "Some patients in the trials experienced allergic reactions to the medication" },
      { letter: "C", text: "The new medication costs significantly more than existing treatments" },
      { letter: "D", text: "The company conducting the research also manufactures the medication" },
      { letter: "E", text: "Some existing treatments have been on the market for decades with well-documented safety profiles" },
    ],
    correctAnswer: "A",
    explanation: "Chronic pain requires long-term treatment, but the trials only lasted twelve weeks. Short-term effectiveness does not guarantee long-term effectiveness, and short-term safety data does not reveal side effects that develop over years of use. This undermines the conclusion that the medication is superior for chronic pain treatment.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-025",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Organic foods are healthier than conventionally grown foods. Therefore, consumers who want to improve their health should purchase organic products whenever possible.`,
    questionStem: "Which one of the following, if true, most weakens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Organic farming methods are more labor-intensive than conventional methods" },
      { letter: "B", text: "Many consumers cannot afford to purchase organic products regularly" },
      { letter: "C", text: "Scientific studies have found no significant nutritional differences between organic and conventional foods" },
      { letter: "D", text: "Some organic farms use pesticides that are approved for organic production" },
      { letter: "E", text: "The organic food market has grown substantially in recent years" },
    ],
    correctAnswer: "C",
    explanation: "The nutritionist's recommendation is based on the premise that organic foods are healthier. If scientific studies show no significant nutritional differences, this directly challenges the foundation of the argument. Without the health benefit, there is no health-based reason to prefer organic products.",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `School administrator: Implementing a later start time for high school classes will improve student academic performance. Research shows that teenagers have biological sleep patterns that make early morning alertness difficult. Students who are more alert in class will learn more effectively.`,
    questionStem: "Which one of the following, if true, most weakens the administrator's argument?",
    answerChoices: [
      { letter: "A", text: "Teachers prefer earlier start times because they can leave work earlier in the afternoon" },
      { letter: "B", text: "Later start times would interfere with after-school athletic programs and jobs" },
      { letter: "C", text: "Students with later start times tend to go to sleep later, resulting in no increase in total sleep" },
      { letter: "D", text: "Some high-achieving students have adapted well to early start times" },
      { letter: "E", text: "Bus schedules would need to be revised to accommodate later start times" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that later start times will lead to more alert students. But if students simply go to sleep later, maintaining the same amount of sleep (or even less), they will not be more alert. This breaks the causal chain between later start times and improved performance.",
    difficulty: "medium",
  },

  // ASSUMPTION QUESTIONS (8 questions)
  {
    id: "lr-bank28-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Political scientist: Democracies do not go to war with each other. Therefore, the best way to ensure lasting world peace is to promote the spread of democratic governance throughout the world.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "All non-democratic governments are prone to initiating wars" },
      { letter: "B", text: "Democratic governance can be successfully established in any country" },
      { letter: "C", text: "Wars between democracies and non-democracies would be less destructive than other wars" },
      { letter: "D", text: "Countries that become democracies will remain democracies" },
      { letter: "E", text: "There are no other equally effective means of preventing wars" },
    ],
    correctAnswer: "D",
    explanation: "If countries that become democracies can revert to non-democratic systems, then spreading democracy would not ensure lasting peace. The peace would be temporary, lasting only as long as countries remain democratic. The argument assumes democratic transitions are durable.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Architect: Buildings constructed using sustainable materials are becoming increasingly popular. Since clients who choose sustainable buildings are typically willing to pay premium prices, architects should specialize in sustainable design to maximize their earnings.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Sustainable building materials are not more expensive to work with than conventional materials" },
      { letter: "B", text: "The additional revenue from premium prices exceeds any additional costs of sustainable design" },
      { letter: "C", text: "All architects have the training necessary for sustainable design" },
      { letter: "D", text: "Sustainable buildings are superior in quality to conventional buildings" },
      { letter: "E", text: "The trend toward sustainable buildings will continue indefinitely" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that sustainable design will maximize earnings based on premium prices. But if sustainable design involves higher costs (specialized training, more expensive materials, longer design time) that exceed the premium prices, it would not maximize earnings. The argument assumes the premium exceeds additional costs.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Geneticist: Genetic testing can identify individuals who carry genes associated with increased risk of certain diseases. People who learn they carry such genes can take preventive measures to reduce their risk. Therefore, widespread genetic testing would lead to improved public health outcomes.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Genetic testing is accurate in identifying disease-associated genes" },
      { letter: "B", text: "People who learn of their genetic risks will actually take preventive measures" },
      { letter: "C", text: "Preventive measures are available for all diseases with genetic risk factors" },
      { letter: "D", text: "Genetic testing does not create undue anxiety for those who receive positive results" },
      { letter: "E", text: "The cost of genetic testing is not prohibitively expensive" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that knowledge leads to action. If people who learn of their genetic risks do not take preventive measures (due to fatalism, cost barriers, or lifestyle preferences), then the testing would not improve health outcomes. The connection between knowledge and behavior is essential to the argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Theater critic: Director Chen's production of Hamlet is not truly innovative. While the staging incorporates modern technology like holographic projections, the interpretation of the text follows conventional approaches. A truly innovative production must offer a new interpretation of the play's meaning, not just novel technical elements.`,
    questionStem: "The critic's argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "holographic projections have been used in theatrical productions before" },
      { letter: "B", text: "conventional interpretations of Hamlet are inferior to innovative ones" },
      { letter: "C", text: "Director Chen intended the production to be innovative" },
      { letter: "D", text: "a new interpretation of meaning cannot arise solely from novel staging techniques" },
      { letter: "E", text: "most audiences prefer innovative productions to conventional ones" },
    ],
    correctAnswer: "D",
    explanation: "The critic distinguishes between novel technology and interpretive innovation. But if novel staging (like holographic projections) could itself generate a new interpretation of meaning, then the production could be innovative despite a conventional textual approach. The argument assumes staging novelty alone cannot constitute interpretive innovation.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-031",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Countries that invest heavily in education tend to have stronger economies. Policymakers should therefore increase education spending to stimulate economic growth.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "education spending is the most effective way to stimulate economic growth" },
      { letter: "B", text: "the correlation between education spending and economic strength indicates that education causes economic growth" },
      { letter: "C", text: "countries with strong economies can afford to spend more on education" },
      { letter: "D", text: "all forms of education spending contribute equally to economic growth" },
      { letter: "E", text: "economic growth is the most important policy objective" },
    ],
    correctAnswer: "B",
    explanation: "The economist observes a correlation but recommends causation-based action. If strong economies cause education spending (rather than vice versa), or if a third factor causes both, then increasing education spending would not stimulate growth. The argument assumes education causes economic strength.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Veterinarian: Pet owners should not feed their dogs a vegetarian diet. Dogs evolved as carnivores and require nutrients found primarily in meat, such as certain amino acids that dogs cannot synthesize on their own.`,
    questionStem: "The veterinarian's argument requires which of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Dogs cannot obtain essential amino acids from any vegetarian sources" },
      { letter: "B", text: "The amino acids dogs need cannot be adequately provided through vegetarian diets or supplements" },
      { letter: "C", text: "All meat-based dog foods contain adequate amounts of essential amino acids" },
      { letter: "D", text: "Dogs prefer the taste of meat-based foods to vegetarian foods" },
      { letter: "E", text: "Vegetarian diets are harmful to all animals that evolved as carnivores" },
    ],
    correctAnswer: "B",
    explanation: "The veterinarian claims dogs should not eat vegetarian diets because they need certain nutrients 'found primarily in meat.' But if these nutrients could be provided through vegetarian sources or supplements, a vegetarian diet could still meet dogs' needs. The argument assumes vegetarian diets cannot adequately provide these nutrients.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Art museum director: Our museum should focus its acquisition budget on contemporary art rather than historical works. Contemporary art is more accessible to younger visitors, and attracting younger visitors is essential for the museum's long-term sustainability.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "younger visitors are not interested in historical art" },
      { letter: "B", text: "contemporary art is less expensive to acquire than historical works" },
      { letter: "C", text: "younger visitors who are attracted to the museum will continue visiting as they age" },
      { letter: "D", text: "acquiring contemporary art is the most effective way to attract younger visitors" },
      { letter: "E", text: "the museum does not currently own any contemporary art" },
    ],
    correctAnswer: "C",
    explanation: "The director's concern is long-term sustainability. If younger visitors attracted now do not become long-term supporters, then attracting them would not ensure sustainability. The argument assumes that attracting younger visitors now will lead to ongoing patronage.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Software engineer: Open-source software is more secure than proprietary software because anyone can examine the code and identify vulnerabilities. Proprietary software conceals its code, allowing security flaws to go undetected.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Proprietary software companies do not conduct internal security reviews" },
      { letter: "B", text: "People who examine open-source code actually do identify and report vulnerabilities" },
      { letter: "C", text: "Open-source software is always free of charge" },
      { letter: "D", text: "Malicious actors cannot also examine open-source code to find vulnerabilities to exploit" },
      { letter: "E", text: "All programmers are capable of identifying security vulnerabilities" },
    ],
    correctAnswer: "B",
    explanation: "The argument claims open-source is more secure because anyone CAN examine the code. But possibility is not actuality. If people who can examine the code do not actually do so or do not report what they find, the theoretical advantage disappears. The argument assumes the examination actually happens.",
    difficulty: "medium",
  },

  // MAIN-CONCLUSION QUESTIONS (4 questions)
  {
    id: "lr-bank28-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Many employers now require job applicants to have college degrees for positions that previously did not require them. This credential inflation does not benefit employers because it restricts their pool of qualified candidates. It certainly does not benefit workers, as it forces them to incur significant educational debt. The only beneficiaries are the colleges themselves. Credential inflation is therefore a socially harmful trend that policymakers should work to reverse.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Credential inflation restricts the pool of qualified job candidates" },
      { letter: "B", text: "Workers are harmed by credential inflation because they must incur educational debt" },
      { letter: "C", text: "Colleges are the only beneficiaries of credential inflation" },
      { letter: "D", text: "Policymakers should take action to reverse credential inflation" },
      { letter: "E", text: "Credential inflation is harmful to society and should be reversed" },
    ],
    correctAnswer: "E",
    explanation: "The argument builds to the conclusion that credential inflation is 'a socially harmful trend that policymakers should work to reverse.' This combines the evaluative claim (socially harmful) with the prescriptive claim (should be reversed). The other claims about employers, workers, and colleges serve as evidence for this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some philosophers argue that free will is an illusion because our choices are determined by prior causes. However, even if our choices are causally determined, we still experience deliberation and the sense of choosing. This experience of agency is itself significant and deserving of philosophical attention. The determinism debate should not obscure the importance of understanding how we experience and exercise practical reasoning.`,
    questionStem: "The main point of the argument is that",
    answerChoices: [
      { letter: "A", text: "free will may be an illusion" },
      { letter: "B", text: "the experience of agency is philosophically significant regardless of whether choices are determined" },
      { letter: "C", text: "practical reasoning involves deliberation and the sense of choosing" },
      { letter: "D", text: "philosophers should focus on understanding practical reasoning rather than debating determinism" },
      { letter: "E", text: "the determinism debate has obscured other important philosophical questions" },
    ],
    correctAnswer: "B",
    explanation: "The argument acknowledges the determinism position but argues that the experience of agency is significant in its own right. This is the central claim that the author is defending. The final sentence reinforces that understanding this experience should not be overshadowed by the determinism debate.",
    difficulty: "hard",
  },
  {
    id: "lr-bank28-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Consumer spending accounts for nearly 70 percent of economic activity. When consumers reduce their spending due to economic uncertainty, businesses suffer reduced revenues and may lay off workers. Those workers then reduce their spending, creating a downward spiral. To prevent such spirals, governments should maintain consumer confidence during economic downturns through clear communication and targeted support programs.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Consumer spending constitutes the majority of economic activity" },
      { letter: "B", text: "Reduced consumer spending can create economic downward spirals" },
      { letter: "C", text: "Governments should act to maintain consumer confidence during economic downturns" },
      { letter: "D", text: "Worker layoffs lead to further reductions in consumer spending" },
      { letter: "E", text: "Economic uncertainty causes consumers to reduce their spending" },
    ],
    correctAnswer: "C",
    explanation: "The argument describes the mechanics of economic downturns to support a policy recommendation: governments should maintain consumer confidence through communication and support programs. The description of spending patterns and downward spirals serves as evidence for this prescriptive conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Ancient Athenian democracy excluded women, slaves, and non-citizens from political participation, leaving only a small fraction of the population with voting rights. Modern democracies, despite their flaws, extend political rights far more broadly. Those who idealize ancient Athens as a model of democracy therefore misunderstand both ancient and modern political systems.`,
    questionStem: "Which one of the following best expresses the main point of the argument?",
    answerChoices: [
      { letter: "A", text: "Ancient Athenian democracy excluded most of the population from political participation" },
      { letter: "B", text: "Modern democracies are superior to ancient Athenian democracy" },
      { letter: "C", text: "Idealizing ancient Athens as a democratic model reflects a misunderstanding of both ancient and modern systems" },
      { letter: "D", text: "Women, slaves, and non-citizens could not vote in ancient Athens" },
      { letter: "E", text: "Modern democracies have their own flaws despite broader participation" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is that those who idealize ancient Athens as a model of democracy 'misunderstand both ancient and modern political systems.' The facts about Athenian exclusions and modern broader participation serve as evidence for this evaluative conclusion about people who hold an idealized view.",
    difficulty: "medium",
  },

  // METHOD-OF-REASONING QUESTIONS (4 questions)
  {
    id: "lr-bank28-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Magazine editor: Our readers claim they want more substantive articles on complex topics. But when we track which articles are actually read, the short, entertaining pieces consistently attract the most readers. We should therefore continue prioritizing short, entertaining content over longer, substantive articles.`,
    questionStem: "The editor's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "questioning the sincerity of readers' stated preferences" },
      { letter: "B", text: "using behavioral data to challenge the reliability of stated preferences" },
      { letter: "C", text: "demonstrating that reader preferences have changed over time" },
      { letter: "D", text: "arguing that editors should not be influenced by reader preferences" },
      { letter: "E", text: "showing that substantive articles cannot be entertaining" },
    ],
    correctAnswer: "B",
    explanation: "The editor notes a discrepancy between what readers say they want (stated preference) and what they actually read (revealed preference). The argument uses actual behavior data to argue that stated preferences should not determine content strategy. This is using behavioral evidence to challenge stated claims.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Meteorologist: My colleague predicts that this winter will be unusually severe based on the thickness of tree bark observed this fall. However, there is no known mechanism by which trees could predict winter weather, and numerous studies have failed to find any correlation between bark thickness and winter severity. The prediction is therefore unfounded.`,
    questionStem: "The meteorologist's reasoning technique is to",
    answerChoices: [
      { letter: "A", text: "cite lack of both explanatory mechanism and empirical correlation to discredit a claim" },
      { letter: "B", text: "use personal experience to contradict a colleague's prediction" },
      { letter: "C", text: "appeal to expert authority in a related field" },
      { letter: "D", text: "demonstrate that the colleague lacks proper credentials" },
      { letter: "E", text: "show that similar predictions have been wrong in the past" },
    ],
    correctAnswer: "A",
    explanation: "The meteorologist attacks the prediction on two grounds: there is no causal mechanism that would explain how trees could predict weather, and empirical studies have not found the claimed correlation. This dual approach of questioning both explanation and evidence is the core reasoning strategy.",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that personal identity persists through psychological continuity alone. But consider someone who gradually loses all memories and personality traits while remaining physically the same person. At what point would they cease to be the same person? This question has no clear answer, suggesting that psychological continuity alone cannot fully explain personal identity.`,
    questionStem: "The philosopher's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "providing a counterexample that disproves a universal claim" },
      { letter: "B", text: "using a thought experiment to expose a problem with a theory" },
      { letter: "C", text: "appealing to common intuitions about personal identity" },
      { letter: "D", text: "demonstrating that a concept leads to logical contradictions" },
      { letter: "E", text: "showing that competing theories of identity are equally valid" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher constructs a hypothetical scenario (someone gradually losing memories and personality) to challenge the psychological continuity view. By showing that the theory cannot answer a key question about this case, the argument exposes a limitation in the theory. This is classic thought experiment methodology.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution claims my client was at the crime scene because his fingerprints were found there. But my client worked at that location for three years before his termination last month. His fingerprints being present proves nothing about his presence on the night of the crime. The prosecution has failed to establish their case.`,
    questionStem: "The defense attorney's argument employs which one of the following techniques?",
    answerChoices: [
      { letter: "A", text: "attacking the credibility of the prosecution's witnesses" },
      { letter: "B", text: "providing an alternative explanation that undermines the prosecution's inference" },
      { letter: "C", text: "demonstrating that the prosecution's evidence was illegally obtained" },
      { letter: "D", text: "showing that the prosecution has contradicted itself" },
      { letter: "E", text: "arguing that the evidence proves the client's innocence" },
    ],
    correctAnswer: "B",
    explanation: "The attorney accepts the evidence (fingerprints at the scene) but offers an alternative explanation for how they got there (years of employment at the location). This alternative interpretation shows that the evidence does not support the prosecution's conclusion, without disputing the evidence itself.",
    difficulty: "easy",
  },

  // POINT-AT-ISSUE QUESTIONS (3 questions)
  {
    id: "lr-bank28-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Jameson: Professional athletes are overpaid. No one deserves to earn millions of dollars for playing a game, while teachers and nurses who provide essential services earn modest salaries.\n\nMartinez: Athletes earn what the market determines they are worth. Their salaries reflect the enormous revenues generated by professional sports, and any individual athlete's earnings are a small fraction of the value they create.`,
    questionStem: "Jameson and Martinez most clearly disagree about whether",
    answerChoices: [
      { letter: "A", text: "teachers and nurses provide essential services to society" },
      { letter: "B", text: "professional sports generate substantial revenues" },
      { letter: "C", text: "market-determined salaries accurately reflect what individuals deserve to earn" },
      { letter: "D", text: "professional athletes work hard for their earnings" },
      { letter: "E", text: "salary levels should be set by government intervention" },
    ],
    correctAnswer: "C",
    explanation: "Jameson claims athletes don't 'deserve' their salaries based on the nature of their work. Martinez argues that market-determined salaries reflect worth. The core disagreement is whether market value equals deserved compensation. Jameson says no (some work deserves more regardless of market); Martinez says yes (market reflects value).",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Park: Medical decisions should be left to patients and their doctors without interference from insurance companies. When insurance companies deny coverage for treatments that physicians recommend, they are practicing medicine without a license.\n\nDr. Okonkwo: Insurance companies have a legitimate role in healthcare decisions. They employ medical professionals to review treatment requests and ensure that expensive procedures are medically necessary. This prevents wasteful spending that ultimately harms all patients through higher premiums.`,
    questionStem: "The main point at issue between Dr. Park and Dr. Okonkwo is whether",
    answerChoices: [
      { letter: "A", text: "insurance companies employ medical professionals to review treatment requests" },
      { letter: "B", text: "insurance companies are legally permitted to deny coverage for treatments" },
      { letter: "C", text: "expensive medical procedures are sometimes unnecessary" },
      { letter: "D", text: "insurance companies should have a role in determining what treatments patients receive" },
      { letter: "E", text: "physician recommendations are always in patients' best interests" },
    ],
    correctAnswer: "D",
    explanation: "Dr. Park argues insurance companies should not interfere in medical decisions (calling it 'practicing medicine without a license'). Dr. Okonkwo argues they have a 'legitimate role.' The central disagreement is whether insurance companies should have any role in treatment decisions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Hayes: Public funding for the arts is essential. Without government support, many orchestras, theaters, and museums would close, depriving communities of cultural resources. The government has a responsibility to ensure public access to the arts.\n\nNguyen: If people truly value the arts, they will support cultural institutions through private donations and ticket purchases. Government funding of the arts forces taxpayers to subsidize activities they may not value. Cultural institutions that cannot survive on private support do not deserve to continue operating.`,
    questionStem: "Hayes and Nguyen disagree about whether",
    answerChoices: [
      { letter: "A", text: "many cultural institutions rely on government funding to survive" },
      { letter: "B", text: "the government has an obligation to fund arts institutions that cannot survive independently" },
      { letter: "C", text: "private donations and ticket sales provide some funding for cultural institutions" },
      { letter: "D", text: "the arts provide value to communities" },
      { letter: "E", text: "some taxpayers do not personally value the arts" },
    ],
    correctAnswer: "B",
    explanation: "Hayes argues the government has 'a responsibility' to support arts institutions. Nguyen argues institutions 'that cannot survive on private support do not deserve to continue operating' and that government funding should not exist. The disagreement is about governmental obligation to fund the arts.",
    difficulty: "hard",
  },

  // PARALLEL-REASONING QUESTIONS (3 questions)
  {
    id: "lr-bank28-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All licensed physicians have completed medical school. Some licensed physicians work in research rather than clinical practice. Therefore, some people who have completed medical school work in research rather than clinical practice.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All registered nurses have passed a licensing exam. Some registered nurses work night shifts. Therefore, some people who work night shifts have passed a licensing exam." },
      { letter: "B", text: "All published authors have written books. Some published authors also write articles. Therefore, some people who write articles have written books." },
      { letter: "C", text: "All marathon runners train regularly. Some marathon runners are over fifty years old. Therefore, some people who train regularly are over fifty years old." },
      { letter: "D", text: "All certified accountants passed a professional exam. Some certified accountants work for government agencies. Therefore, some government employees have passed a professional exam." },
      { letter: "E", text: "All licensed attorneys graduated from law school. All licensed attorneys passed the bar exam. Therefore, all people who graduated from law school passed the bar exam." },
    ],
    correctAnswer: "C",
    explanation: "The original pattern: All A are B. Some A are C. Therefore, some B are C. Original: All physicians completed medical school. Some physicians work in research. Therefore, some who completed medical school work in research. Answer C matches: All marathon runners train. Some runners are over fifty. Therefore, some who train are over fifty.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the economy improves, consumer confidence will increase. Consumer confidence has not increased. Therefore, the economy has not improved.`,
    questionStem: "Which one of the following arguments exhibits reasoning most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "If it rains, the ground will be wet. It rained. Therefore, the ground is wet." },
      { letter: "B", text: "If the team wins tonight, they will make the playoffs. The team did not win tonight. Therefore, they will not make the playoffs." },
      { letter: "C", text: "If inflation rises, interest rates will increase. Interest rates have not increased. Therefore, inflation has not risen." },
      { letter: "D", text: "If the project is completed on time, the client will be satisfied. The client is satisfied. Therefore, the project was completed on time." },
      { letter: "E", text: "If employees receive training, productivity will improve. Productivity has improved. Therefore, employees must have received training." },
    ],
    correctAnswer: "C",
    explanation: "The original uses modus tollens: If P then Q. Not Q. Therefore, not P. Original: If economy improves, confidence increases. Confidence has not increased. Therefore, economy has not improved. Answer C matches: If inflation rises, rates increase. Rates have not increased. Therefore, inflation has not risen.",
    difficulty: "easy",
  },
  {
    id: "lr-bank28-048",
    type: "parallel-flaw",
    sectionType: "logical-reasoning",
    stimulus: `My neighbor says the new restaurant has terrible food, but my neighbor has never eaten there. Therefore, the restaurant must actually have excellent food.`,
    questionStem: "The flawed reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "The critic panned the movie, but critics often dislike popular films. Therefore, the movie is probably popular." },
      { letter: "B", text: "The reviewer said the book is boring, but the reviewer only read the first chapter. Therefore, the book must be exciting." },
      { letter: "C", text: "The professor says the theory is flawed, but the professor specializes in a different field. Therefore, the theory must be correct." },
      { letter: "D", text: "My friend says the hotel is expensive, but my friend stayed there last year. Therefore, prices may have changed." },
      { letter: "E", text: "The expert claims the investment is risky, but the expert works for a competing firm. Therefore, we should ignore the expert's opinion." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments commit the same flaw: rejecting a claim and concluding the opposite must be true. The original rejects the neighbor's claim (no experience) and concludes the opposite (excellent food). B rejects the reviewer's claim (only read one chapter) and concludes the opposite (must be exciting). Both incorrectly assume that discrediting a negative claim proves the positive.",
    difficulty: "hard",
  },

  // INFERENCE QUESTIONS (2 questions)
  {
    id: "lr-bank28-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the historical society must have resided in the county for at least ten years. Some members of the historical society also serve on the planning commission. The planning commission only accepts members who own property within city limits.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "All planning commission members have resided in the county for at least ten years" },
      { letter: "B", text: "Some property owners within city limits have resided in the county for at least ten years" },
      { letter: "C", text: "All historical society members own property within city limits" },
      { letter: "D", text: "The planning commission has members who are not in the historical society" },
      { letter: "E", text: "Some people who have resided in the county for at least ten years serve on the planning commission" },
    ],
    correctAnswer: "B",
    explanation: "Some people are members of both the historical society and planning commission. Historical society members must have 10+ years residency. Planning commission members must own property in city limits. Therefore, those who are in both groups have 10+ years residency AND own property in city limits. So some property owners have 10+ years residency.",
    difficulty: "medium",
  },
  {
    id: "lr-bank28-050",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The library will reduce its operating hours next year unless it receives additional funding. The city council has already allocated all available funds for the next fiscal year. No funds will be reallocated to the library unless the council declares a budget emergency, which requires evidence that essential services are threatened.`,
    questionStem: "If all the statements above are true, which one of the following can be properly inferred?",
    answerChoices: [
      { letter: "A", text: "The library will definitely reduce its operating hours next year" },
      { letter: "B", text: "The city council does not consider the library an essential service" },
      { letter: "C", text: "If the library's reduced hours would threaten essential services, the library may receive additional funding" },
      { letter: "D", text: "The council will not declare a budget emergency" },
      { letter: "E", text: "Essential services in the city are currently not threatened" },
    ],
    correctAnswer: "C",
    explanation: "The conditional chain is: budget emergency (if essential services threatened) allows fund reallocation, which could give the library additional funding, which would prevent reduced hours. Therefore, if reduced library hours would threaten essential services, this could trigger the emergency declaration and fund reallocation. Answer C correctly captures this conditional possibility.",
    difficulty: "hard",
  },
];
