// Logical Reasoning Questions Bank - Set 32
import { Question } from "../lsat-types";

export const lrQuestionsSet32: Question[] = [
  {
    id: "lr-bank32-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during work hours are more productive than those who work continuously. Therefore, employers should mandate that all employees take breaks every hour, as this will certainly increase overall company productivity.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that what works for some employees will work for all employees" },
      { letter: "B", text: "confuses a correlation between breaks and productivity with breaks causing productivity" },
      { letter: "C", text: "fails to consider that mandatory breaks might be less effective than voluntary ones" },
      { letter: "D", text: "overlooks the possibility that some types of work require sustained concentration" },
      { letter: "E", text: "ignores the costs associated with implementing a mandatory break policy" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits a classic correlation-causation fallacy. While the study found that employees who take breaks are more productive, this does not establish that the breaks caused the increased productivity. Other factors could explain both the break-taking behavior and the productivity, such as better time management skills or lower stress levels.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers have proposed that the extinction of large predators in certain ecosystems has led to an overpopulation of herbivores, which in turn has caused significant damage to vegetation. To test this hypothesis, ecologists plan to reintroduce wolves into a national park where deer populations have been growing unchecked for decades.`,
    questionStem: "Which one of the following, if true, most strengthens the reasoning behind the ecologists' plan?",
    answerChoices: [
      { letter: "A", text: "Wolves are the natural predators of deer in this region" },
      { letter: "B", text: "In similar ecosystems where wolves were reintroduced, deer populations stabilized and vegetation recovered" },
      { letter: "C", text: "The national park has sufficient space to support a wolf population" },
      { letter: "D", text: "Deer populations in the park have tripled over the past twenty years" },
      { letter: "E", text: "Some local residents support the reintroduction of wolves to the area" },
    ],
    correctAnswer: "B",
    explanation: "The ecologists' plan is based on the hypothesis that reintroducing predators will control herbivore populations and allow vegetation to recover. Evidence that this approach has worked in similar ecosystems directly supports the reasoning behind their plan, making B the strongest answer.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that building a new sports stadium downtown will revitalize the area economically. They point to increased foot traffic on game days and the potential for new restaurants and shops to open near the stadium. Based on these projections, the council recommends allocating $500 million in public funds to the project.`,
    questionStem: "Which one of the following, if true, most seriously weakens the city council's argument?",
    answerChoices: [
      { letter: "A", text: "The proposed stadium would have fewer seats than the current stadium" },
      { letter: "B", text: "Studies of other cities show that stadium construction typically displaces existing businesses and provides only temporary economic benefits" },
      { letter: "C", text: "The city has successfully completed other large construction projects in the past" },
      { letter: "D", text: "Some residents have expressed concerns about increased traffic congestion" },
      { letter: "E", text: "The stadium would host events other than sports games" },
    ],
    correctAnswer: "B",
    explanation: "The council's argument rests on the assumption that the stadium will provide economic benefits. Evidence from other cities showing that stadiums typically displace businesses and provide only temporary benefits directly undermines this assumption and significantly weakens the argument for public investment.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Medical ethicists argue that patients have a right to make informed decisions about their treatment. Since experimental treatments carry unknown risks that cannot be fully explained to patients, doctors should not offer experimental treatments to their patients.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Patients generally prefer traditional treatments over experimental ones" },
      { letter: "B", text: "Doctors are unable to explain the concept of unknown risks to patients" },
      { letter: "C", text: "Informed decision-making requires complete knowledge of all potential risks" },
      { letter: "D", text: "Experimental treatments are always more dangerous than established treatments" },
      { letter: "E", text: "Medical ethicists have the authority to determine what treatments doctors may offer" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes that experimental treatments should not be offered because their unknown risks cannot be fully explained. This conclusion only follows if informed decision-making requires complete knowledge of all risks. Without this assumption, patients could still make informed decisions based on the knowledge that risks are uncertain.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `The rise of social media has fundamentally changed how people consume news. Traditional newspapers are struggling financially as advertising revenue shifts to online platforms. Many journalists have lost their jobs, and local news coverage has declined significantly. Without intervention, we risk losing the investigative journalism that holds powerful institutions accountable. Therefore, governments should consider subsidizing local news organizations to preserve this essential democratic function.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Social media has changed how people consume news" },
      { letter: "B", text: "Traditional newspapers are struggling financially" },
      { letter: "C", text: "Investigative journalism holds powerful institutions accountable" },
      { letter: "D", text: "Governments should consider subsidizing local news organizations" },
      { letter: "E", text: "Many journalists have lost their jobs due to declining advertising revenue" },
    ],
    correctAnswer: "D",
    explanation: "The word 'Therefore' signals the main conclusion. All the other statements are premises supporting the conclusion that governments should consider subsidizing local news organizations. The argument builds from the problem (declining newspapers) through the consequences (lost journalism jobs, reduced coverage) to the proposed solution.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The museum director claims that the new modern art wing will attract younger visitors. But this is unlikely to succeed. The museum's previous attempts to attract younger audiences through contemporary exhibitions failed. Moreover, surveys show that young people prefer interactive digital experiences over traditional museum visits. The director's optimism is simply not supported by evidence.`,
    questionStem: "The critic's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "questioning the director's qualifications to make predictions about visitor demographics" },
      { letter: "B", text: "providing alternative explanations for why the museum has struggled to attract young visitors" },
      { letter: "C", text: "citing past failures and current preferences to cast doubt on a prediction" },
      { letter: "D", text: "demonstrating that the director's claim contains an internal contradiction" },
      { letter: "E", text: "arguing that modern art is not appealing to younger audiences" },
    ],
    correctAnswer: "C",
    explanation: "The critic uses two types of evidence to challenge the director's prediction: (1) historical evidence of past failures and (2) current survey data about young people's preferences. This combination of past performance and present trends is used to argue that the prediction is unlikely to come true.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Anyone who has studied philosophy extensively understands the importance of critical thinking. Professor Martinez has taught philosophy for thirty years. Therefore, Professor Martinez must be an excellent critical thinker who applies rigorous logical analysis to all aspects of life.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that teaching a subject is equivalent to studying it extensively" },
      { letter: "B", text: "confuses understanding the importance of something with practicing it consistently" },
      { letter: "C", text: "fails to consider that critical thinking skills may decline over time" },
      { letter: "D", text: "overlooks the possibility that philosophy can be taught without emphasizing critical thinking" },
      { letter: "E", text: "draws a conclusion about all aspects of life from evidence about academic expertise" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from understanding the importance of critical thinking to being an excellent critical thinker who applies it consistently. This is a flaw because understanding that something is important does not mean one actually practices it. Someone can know critical thinking matters without applying it rigorously in their own life.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologists studying decision-making have found that people tend to make better choices when they have fewer options. A study showed that shoppers who were offered six varieties of jam were more likely to make a purchase than those offered twenty-four varieties. Retailers who want to increase sales should therefore reduce the number of product options they offer.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "The jam study was conducted in a high-end grocery store" },
      { letter: "B", text: "Similar results have been found across multiple product categories and retail environments" },
      { letter: "C", text: "Shoppers reported feeling less stressed when faced with fewer options" },
      { letter: "D", text: "Some shoppers specifically seek out stores with wide product selections" },
      { letter: "E", text: "The jam varieties in the smaller selection were also available in the larger selection" },
    ],
    correctAnswer: "B",
    explanation: "The argument generalizes from one study about jam to a broad recommendation for all retailers. Evidence that similar results have been found across multiple product categories and retail environments supports this generalization, showing that the jam study was not an isolated case.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-009",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company argues that its new medication is safe because clinical trials showed no serious side effects in participants. The trials included 500 participants who took the medication for six months, and none experienced significant adverse reactions. This demonstrates that the medication can be safely prescribed to the general public.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some participants reported mild headaches during the first week of treatment" },
      { letter: "B", text: "The medication is intended for long-term use over several years, and some side effects may only emerge after extended exposure" },
      { letter: "C", text: "The clinical trial was conducted at multiple hospitals across the country" },
      { letter: "D", text: "Similar medications produced by other companies have been found to be safe" },
      { letter: "E", text: "The clinical trial participants were volunteers who signed consent forms" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that the medication is safe based on a six-month trial. If the medication is intended for long-term use over years, and some side effects only emerge after extended exposure, then the six-month trial may not have been long enough to detect all potential adverse effects. This significantly weakens the safety claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-010",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Environmental activists argue that governments should ban single-use plastics to reduce ocean pollution. However, this approach is misguided. Many single-use plastic items, such as medical supplies and food packaging, serve essential purposes that cannot be easily replaced. A complete ban would therefore cause more harm than good.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "Ocean pollution is not a serious environmental problem" },
      { letter: "B", text: "Environmental activists are not aware of the essential uses of plastics" },
      { letter: "C", text: "A ban on single-use plastics would necessarily include essential items like medical supplies" },
      { letter: "D", text: "There are no alternative materials that could replace plastics for essential purposes" },
      { letter: "E", text: "The harm from ocean pollution is less significant than the harm from banning plastics" },
    ],
    correctAnswer: "C",
    explanation: "The argument claims a ban would be harmful because essential items like medical supplies could not be replaced. This only works if the ban would include these essential items. If a ban could exempt essential uses, the argument against a ban fails. The assumption that a ban must include all single-use plastics is necessary for the conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-011",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Marcus: Autonomous vehicles will revolutionize transportation safety. Computer systems can process information faster than humans and are not subject to fatigue or distraction. Once the technology matures, self-driving cars will virtually eliminate accidents caused by human error.

Diana: I disagree. Autonomous vehicles introduce new types of risks that could offset their benefits. Software can malfunction, sensors can be fooled by unusual conditions, and hackers could potentially take control of vehicles. The safety benefits of autonomous vehicles are far from guaranteed.`,
    questionStem: "Marcus and Diana disagree about whether",
    answerChoices: [
      { letter: "A", text: "computer systems can process information faster than humans" },
      { letter: "B", text: "autonomous vehicles will significantly improve transportation safety" },
      { letter: "C", text: "human error is a major cause of traffic accidents" },
      { letter: "D", text: "the technology for autonomous vehicles needs further development" },
      { letter: "E", text: "hackers pose a threat to computer-controlled systems" },
    ],
    correctAnswer: "B",
    explanation: "Marcus claims autonomous vehicles will 'revolutionize transportation safety' and 'virtually eliminate accidents.' Diana counters that 'safety benefits are far from guaranteed' due to new risks. Their core disagreement is whether autonomous vehicles will significantly improve safety, not about specific technical details that one acknowledges and the other disputes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-012",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All successful entrepreneurs are willing to take calculated risks. Some successful entrepreneurs have failed multiple times before achieving success. Therefore, some people who are willing to take calculated risks have failed multiple times before achieving success.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All professional athletes train regularly. Some professional athletes compete internationally. Therefore, some people who train regularly compete internationally." },
      { letter: "B", text: "All cats are mammals. All mammals are warm-blooded. Therefore, all cats are warm-blooded." },
      { letter: "C", text: "Some teachers are patient. All patient people are good listeners. Therefore, some teachers are good listeners." },
      { letter: "D", text: "No reptiles are warm-blooded. Some pets are reptiles. Therefore, some pets are not warm-blooded." },
      { letter: "E", text: "All lawyers passed the bar exam. Some lawyers work in government. Therefore, all people who work in government passed the bar exam." },
    ],
    correctAnswer: "A",
    explanation: "The original argument follows this pattern: All A are B. Some A are C. Therefore, some B are C. This is a valid syllogism. Answer A follows the same pattern: All professional athletes (A) train regularly (B). Some professional athletes (A) compete internationally (C). Therefore, some who train regularly (B) compete internationally (C).",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-013",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The city's traffic congestion has worsened significantly since the new shopping mall opened last year. Clearly, the mall is responsible for the increased traffic. To solve the congestion problem, the city should require the mall to reduce its operating hours.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that reducing the mall's hours would be an effective solution without considering alternatives" },
      { letter: "B", text: "concludes that one event caused another merely because the first preceded the second" },
      { letter: "C", text: "fails to consider the economic benefits the mall provides to the city" },
      { letter: "D", text: "ignores the possibility that shoppers would simply visit during the reduced hours" },
      { letter: "E", text: "overlooks the interests of mall employees who might lose work hours" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the post hoc ergo propter hoc fallacy, assuming that because traffic worsened after the mall opened, the mall caused the traffic increase. The temporal sequence alone does not establish causation; other factors such as population growth, road construction, or changes in commuting patterns could be responsible.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists have discovered that ancient civilizations in different parts of the world independently developed similar pyramid-building techniques. Some researchers have proposed that these similarities suggest contact between these civilizations. However, a more plausible explanation is that pyramid shapes naturally emerge from the engineering constraints of building large stone structures without modern technology.`,
    questionStem: "Which one of the following, if true, most strengthens the alternative explanation offered in the argument?",
    answerChoices: [
      { letter: "A", text: "Some ancient civilizations built structures other than pyramids" },
      { letter: "B", text: "Ancient pyramids in different regions were built using locally available materials" },
      { letter: "C", text: "Children across cultures tend to build similar pyramid-shaped structures when playing with blocks" },
      { letter: "D", text: "Some historians believe ancient civilizations had more contact than previously thought" },
      { letter: "E", text: "Modern engineers use computers to design buildings of various shapes" },
    ],
    correctAnswer: "C",
    explanation: "The alternative explanation suggests that pyramid shapes naturally emerge from engineering constraints when building large structures. If children across cultures independently create similar pyramid shapes when building with blocks, this supports the idea that pyramids are a natural structural solution that emerges from physical constraints rather than from cultural contact.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A business consultant argues that companies should eliminate remote work policies and require all employees to work in the office. The consultant points to a study showing that teams that work in the same physical location communicate more frequently than remote teams. Since communication is essential to productivity, returning to office work will increase company productivity.`,
    questionStem: "Which one of the following, if true, most seriously weakens the consultant's argument?",
    answerChoices: [
      { letter: "A", text: "Some employees prefer working from home for personal reasons" },
      { letter: "B", text: "The study compared in-office teams to fully remote teams, not to hybrid work arrangements" },
      { letter: "C", text: "Increased communication frequency often involves non-work-related conversations that reduce productive work time" },
      { letter: "D", text: "Many successful technology companies have adopted remote work policies" },
      { letter: "E", text: "Office space is expensive to maintain in major metropolitan areas" },
    ],
    correctAnswer: "C",
    explanation: "The consultant assumes that more frequent communication leads to greater productivity. If increased communication often involves non-work-related conversations that reduce productive work time, then the link between communication frequency and productivity is broken. More communication might actually decrease productivity, undermining the argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-016",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Current copyright laws were designed for an era of physical media and do not adequately address digital content. When someone copies a physical book, the original is unaffected, but the copy deprives the author of a potential sale. Digital copying is different because it costs nothing and creates perfect duplicates. Therefore, copyright laws should be reformed to reflect the unique nature of digital content.`,
    questionStem: "The legal scholar's argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Digital copying has become more common than physical copying" },
      { letter: "B", text: "The differences between physical and digital copying are relevant to how copyright law should treat them" },
      { letter: "C", text: "Authors of digital content deserve more protection than authors of physical content" },
      { letter: "D", text: "Current copyright laws do not apply to digital content at all" },
      { letter: "E", text: "All digital content should be freely available to the public" },
    ],
    correctAnswer: "B",
    explanation: "The scholar argues that because digital and physical copying are different, copyright laws should be reformed for digital content. This conclusion only follows if those differences are relevant to how the law should treat them. If the differences were legally irrelevant, there would be no reason to reform the laws.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-017",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some philosophers argue that free will is an illusion because all human actions are determined by prior causes. However, this deterministic view fails to account for the subjective experience of making choices. When we deliberate between options, we genuinely feel that we could choose otherwise. This feeling of freedom may not prove that we have libertarian free will, but it demonstrates that the concept of free will captures something real about human experience that pure determinism ignores.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Determinism claims that all human actions are caused by prior events" },
      { letter: "B", text: "People feel as though they could choose differently when making decisions" },
      { letter: "C", text: "The concept of free will reflects a genuine aspect of human experience that determinism overlooks" },
      { letter: "D", text: "The subjective experience of choice proves that libertarian free will exists" },
      { letter: "E", text: "Philosophers disagree about whether free will is compatible with determinism" },
    ],
    correctAnswer: "C",
    explanation: "The argument builds toward the final claim that the concept of free will captures 'something real about human experience that pure determinism ignores.' The other statements are premises or context. The argument explicitly denies that the conclusion proves libertarian free will exists (eliminating D), focusing instead on what the experience of choice demonstrates about the limitations of determinism.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-018",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Historian: Many people believe that the Roman Empire fell because of moral decay and decadence. However, this explanation is too simplistic. The empire faced numerous challenges including military overextension, economic troubles, political instability, and pressure from migrating peoples. Any single-factor explanation for such a complex historical event is bound to be inadequate. The fall of Rome resulted from the interaction of multiple causes over centuries.`,
    questionStem: "The historian's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "presenting new archaeological evidence that contradicts the conventional view" },
      { letter: "B", text: "arguing that a commonly held explanation is too narrow and proposing a more comprehensive account" },
      { letter: "C", text: "demonstrating that the Roman Empire did not actually decline as significantly as believed" },
      { letter: "D", text: "questioning the credentials of those who support the moral decay theory" },
      { letter: "E", text: "showing that moral decay was a consequence rather than a cause of the empire's fall" },
    ],
    correctAnswer: "B",
    explanation: "The historian explicitly calls the moral decay explanation 'too simplistic' and then lists multiple other factors. The argument's method is to reject a single-factor explanation as inadequate and replace it with a multi-causal account that includes military, economic, political, and demographic factors.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-019",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The candidate claims to support environmental protection, but she drives a large SUV and her house has a swimming pool. Clearly, she does not genuinely care about the environment and her environmental policy proposals should not be taken seriously.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "attacks the candidate's personal behavior rather than addressing the merits of her policy proposals" },
      { letter: "B", text: "assumes that all environmentalists must live without modern conveniences" },
      { letter: "C", text: "fails to consider that the candidate might offset her carbon footprint in other ways" },
      { letter: "D", text: "overlooks the possibility that the candidate's SUV might be a fuel-efficient hybrid" },
      { letter: "E", text: "ignores the environmental impact of other candidates' lifestyles" },
    ],
    correctAnswer: "A",
    explanation: "This is an ad hominem attack. The argument dismisses the candidate's policy proposals based on her personal behavior rather than evaluating the proposals themselves. Even if the candidate is hypocritical, her policies could still be sound. The merits of environmental policies are independent of whether the person proposing them lives an environmentally perfect life.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-020",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Scientists have observed that certain species of birds have been migrating earlier each spring over the past several decades. Researchers hypothesize that this change is driven by global warming, as warmer temperatures trigger the biological signals that prompt migration.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "The birds in question migrate to regions where temperatures have remained stable" },
      { letter: "B", text: "Some bird species have not changed their migration timing at all" },
      { letter: "C", text: "The regions where these birds spend winter have experienced the greatest temperature increases" },
      { letter: "D", text: "Migration timing is influenced by multiple factors including food availability" },
      { letter: "E", text: "Scientists have been tracking bird migration more accurately in recent years" },
    ],
    correctAnswer: "C",
    explanation: "The hypothesis is that warmer temperatures trigger earlier migration. If the regions where these birds spend winter have experienced the greatest temperature increases, this provides a direct mechanism for the hypothesis. The birds would be exposed to the warming temperatures that supposedly trigger their earlier departure.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Critics of artificial intelligence warn that AI will lead to massive unemployment as machines replace human workers. However, throughout history, technological advances have ultimately created more jobs than they eliminated. The industrial revolution, for example, displaced many agricultural workers but created far more factory and service jobs. AI will similarly create new types of employment that we cannot currently imagine.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some AI researchers believe that artificial general intelligence is still decades away" },
      { letter: "B", text: "Unlike previous technological shifts, AI has the potential to automate cognitive tasks that new jobs would also require" },
      { letter: "C", text: "Many workers displaced during the industrial revolution experienced significant hardship" },
      { letter: "D", text: "Governments can implement policies to help workers transition to new types of jobs" },
      { letter: "E", text: "The industrial revolution took place over a longer time period than AI adoption is expected to take" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes AI will follow the pattern of previous technological advances. However, if AI can automate the cognitive tasks that new jobs would require, then it could break this historical pattern. Previous technologies automated physical labor, creating jobs that required human cognition. If AI automates cognition itself, the new jobs might also be automatable.",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-022",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `University administrators argue that increasing tuition is necessary to maintain educational quality. They note that faculty salaries must remain competitive to attract top professors, facilities need constant upgrades, and student support services require ongoing investment. Without tuition increases, the university would be forced to cut programs and reduce the quality of education it provides.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Other universities are also raising their tuition rates" },
      { letter: "B", text: "Students value educational quality more than affordable tuition" },
      { letter: "C", text: "The university has no other viable means of increasing revenue or reducing costs while maintaining quality" },
      { letter: "D", text: "Faculty salaries are the largest portion of the university's budget" },
      { letter: "E", text: "All programs at the university are essential and cannot be eliminated" },
    ],
    correctAnswer: "C",
    explanation: "The administrators conclude that tuition increases are necessary to maintain quality. This conclusion requires assuming there are no other options. If the university could increase revenue through other means (endowments, partnerships, grants) or reduce costs without affecting quality (administrative efficiency), then tuition increases would not be necessary.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-023",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the city council must disclose their financial interests before voting on any matter that could affect those interests. Councilwoman Roberts did not disclose any financial interests before voting on the zoning proposal. The zoning proposal would affect the value of commercial properties in the downtown district.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Councilwoman Roberts does not own any commercial properties in the downtown district" },
      { letter: "B", text: "Councilwoman Roberts violated the council's disclosure rules" },
      { letter: "C", text: "Either Roberts has no financial interests affected by the zoning proposal, or she failed to follow the disclosure requirement" },
      { letter: "D", text: "The zoning proposal will be invalidated due to the failure to disclose" },
      { letter: "E", text: "Other council members properly disclosed their financial interests" },
    ],
    correctAnswer: "C",
    explanation: "The rule requires disclosure only if a member has interests that could be affected. Roberts did not disclose. Either she has no interests affected by the proposal (so disclosure was not required), or she has interests but failed to disclose (violating the rule). One of these must be true given the stated facts.",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-024",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Chen: Medical schools should require courses in nutrition because diet plays a crucial role in preventing chronic diseases. Physicians who understand nutrition can provide better preventive care and help patients make healthier choices.

Dr. Patel: I disagree with adding required nutrition courses. Medical school curricula are already packed with essential material, and adding requirements would either extend training time or crowd out other important subjects. Physicians can learn about nutrition through continuing education after graduation.`,
    questionStem: "The point at issue between Dr. Chen and Dr. Patel is whether",
    answerChoices: [
      { letter: "A", text: "nutrition is important for preventing chronic diseases" },
      { letter: "B", text: "medical school curricula should include required nutrition courses" },
      { letter: "C", text: "continuing education is an effective way for physicians to learn new material" },
      { letter: "D", text: "medical training currently takes too long to complete" },
      { letter: "E", text: "physicians need to understand nutrition to provide good care" },
    ],
    correctAnswer: "B",
    explanation: "Dr. Chen explicitly argues for requiring nutrition courses in medical schools, while Dr. Patel disagrees with adding required nutrition courses. Their disagreement is specifically about whether such courses should be required in medical school, not about the importance of nutrition itself or whether physicians should eventually learn about it.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-025",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the new highway is built, traffic congestion in the city center will decrease. But the city council has rejected the highway proposal due to budget constraints. Therefore, traffic congestion in the city center will not decrease.`,
    questionStem: "The flawed pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If it rains tomorrow, the outdoor concert will be cancelled. It will not rain tomorrow. Therefore, the outdoor concert will not be cancelled." },
      { letter: "B", text: "All birds can fly. Penguins are birds. Therefore, penguins can fly." },
      { letter: "C", text: "If the defendant is guilty, there will be evidence at the crime scene. There is evidence at the crime scene. Therefore, the defendant is guilty." },
      { letter: "D", text: "Either we take the highway or we take the local roads. We are not taking the highway. Therefore, we are taking the local roads." },
      { letter: "E", text: "If plants receive enough sunlight, they will grow. These plants are growing. Therefore, they are receiving enough sunlight." },
    ],
    correctAnswer: "A",
    explanation: "The original argument commits the fallacy of denying the antecedent: If A then B; not A; therefore not B. The highway would reduce congestion, but other things could also reduce congestion, so rejecting the highway does not guarantee congestion will remain. Answer A follows the same pattern: If rain, then cancellation; no rain; therefore no cancellation. But other factors could also cause cancellation.",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-026",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Editorial: Vegetarian diets are healthier than diets that include meat. Studies show that vegetarians have lower rates of heart disease and obesity. Therefore, everyone should adopt a vegetarian diet for health reasons.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that vegetarian diets require careful planning to ensure adequate nutrition" },
      { letter: "B", text: "ignores the possibility that people who choose vegetarian diets may differ in other health-related behaviors from those who do not" },
      { letter: "C", text: "assumes without justification that lower rates of heart disease lead to longer lifespans" },
      { letter: "D", text: "overlooks the cultural and traditional importance of meat in many societies" },
      { letter: "E", text: "relies on studies that may have been conducted by biased researchers" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that the health benefits are caused by the vegetarian diet itself. However, people who choose vegetarian diets might also exercise more, smoke less, or engage in other healthy behaviors. The observed health differences could be due to these other factors rather than the diet. This is a selection bias or confounding variable problem.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-027",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Marine biologists have noticed that coral reefs near certain coastal cities are dying at faster rates than reefs in more isolated areas. The biologists hypothesize that runoff containing fertilizers from urban lawns and gardens is flowing into the ocean and causing algae blooms that smother the coral.`,
    questionStem: "Which one of the following, if true, most strengthens the biologists' hypothesis?",
    answerChoices: [
      { letter: "A", text: "Coral reefs have been declining globally due to rising ocean temperatures" },
      { letter: "B", text: "The algae species growing on the affected reefs are known to thrive in nutrient-rich conditions" },
      { letter: "C", text: "Some coastal cities have implemented bans on certain types of fertilizers" },
      { letter: "D", text: "Isolated reefs face other threats such as invasive species" },
      { letter: "E", text: "Not all urban areas are located near coral reef ecosystems" },
    ],
    correctAnswer: "B",
    explanation: "The hypothesis links fertilizer runoff to algae blooms that harm coral. If the specific algae growing on affected reefs are known to thrive in nutrient-rich conditions (like those created by fertilizers), this supports the connection between fertilizer runoff and the algae growth that is harming the coral.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-028",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A school district claims that its new mathematics curriculum has improved student performance. They point out that average test scores have risen by 15% since the curriculum was implemented three years ago. This demonstrates that the new teaching methods are more effective than the previous approach.`,
    questionStem: "Which one of the following, if true, most seriously weakens the school district's claim?",
    answerChoices: [
      { letter: "A", text: "Some teachers were initially resistant to adopting the new curriculum" },
      { letter: "B", text: "The district simultaneously reduced class sizes and increased tutoring resources when implementing the new curriculum" },
      { letter: "C", text: "Neighboring school districts that kept their old curricula saw smaller improvements" },
      { letter: "D", text: "The new curriculum includes more problem-solving exercises than the old one" },
      { letter: "E", text: "Student enrollment has remained stable over the three-year period" },
    ],
    correctAnswer: "B",
    explanation: "The district attributes improved test scores to the new curriculum. However, if class sizes were reduced and tutoring increased at the same time, these factors could explain the improvement instead. The district cannot conclude the curriculum is responsible when multiple changes occurred simultaneously.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Political commentator: The proposed campaign finance reform will not reduce corruption in politics. Wealthy individuals and corporations will always find ways to influence politicians, whether through direct contributions, independent expenditures, or other means. As long as money confers advantages in the political system, reforms will merely redirect rather than eliminate its influence.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "All wealthy individuals seek to influence political outcomes" },
      { letter: "B", text: "Campaign finance reform has never been effective in any country" },
      { letter: "C", text: "Politicians are universally susceptible to being influenced by money" },
      { letter: "D", text: "Reducing the influence of money in some areas would not count as reducing corruption" },
      { letter: "E", text: "Redirecting the influence of money is as harmful as direct corruption" },
    ],
    correctAnswer: "D",
    explanation: "The commentator argues that reform will merely redirect money's influence rather than eliminate it, and concludes this means corruption will not be reduced. This requires assuming that redirecting influence does not count as reducing corruption. If blocking some avenues of influence (even if money finds other routes) constitutes reducing corruption, the argument fails.",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-030",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some people argue that because science has been wrong in the past, we should not trust current scientific conclusions. This argument proves too much. By the same reasoning, we should not trust any human endeavor that has ever been wrong, which would include medicine, law, and even common sense reasoning itself. Since we cannot function without relying on these, the argument against trusting science is self-defeating.`,
    questionStem: "The philosopher's reasoning does which one of the following?",
    answerChoices: [
      { letter: "A", text: "Provides examples of scientific theories that were later proven correct" },
      { letter: "B", text: "Shows that the argument against science would, if valid, undermine accepted practices as well" },
      { letter: "C", text: "Questions whether science has actually been wrong as often as critics claim" },
      { letter: "D", text: "Argues that scientific methods have improved and are now more reliable" },
      { letter: "E", text: "Demonstrates that common sense is a more reliable source of knowledge than science" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher uses a reductio ad absurdum approach. By showing that the argument's logic would also undermine medicine, law, and common sense, the philosopher demonstrates that the argument proves too much. If we cannot accept conclusions that would undermine practices we must rely on, we should reject the argument against science.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-031",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The company's new wellness program must be effective because employee satisfaction surveys show that 85% of participants report feeling healthier since joining the program. This high satisfaction rate demonstrates that the program is achieving its goal of improving employee health.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on self-reported feelings of health rather than objective health measures" },
      { letter: "B", text: "fails to compare the results to a control group of non-participants" },
      { letter: "C", text: "does not consider the cost-effectiveness of the wellness program" },
      { letter: "D", text: "assumes that satisfaction with a program equates to the program being well-designed" },
      { letter: "E", text: "ignores the possibility that some employees were already healthy before joining" },
    ],
    correctAnswer: "A",
    explanation: "The argument equates feeling healthier with being healthier. Subjective reports of improved health are not the same as actual health improvements. Participants might feel better due to placebo effects or because they enjoy the program, without experiencing measurable health benefits. The goal was improving health, not improving perceptions of health.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-032",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Sociologists studying urban crime have found that neighborhoods with more community organizations and local businesses tend to have lower crime rates. They theorize that this is because these institutions create more "eyes on the street" and foster a sense of community ownership that discourages criminal activity.`,
    questionStem: "Which one of the following, if true, most strengthens the sociologists' theory?",
    answerChoices: [
      { letter: "A", text: "Neighborhoods with higher incomes tend to have more community organizations" },
      { letter: "B", text: "Crime rates decrease in neighborhoods after new community organizations are established" },
      { letter: "C", text: "Some neighborhoods with many community organizations still experience high crime" },
      { letter: "D", text: "Police presence is also higher in neighborhoods with more local businesses" },
      { letter: "E", text: "Community organizations often advocate for more street lighting and security cameras" },
    ],
    correctAnswer: "B",
    explanation: "The theory proposes that community organizations and businesses cause lower crime rates. If crime rates decrease after new community organizations are established, this shows a temporal pattern consistent with causation: the organizations come first, then crime drops. This is stronger evidence than mere correlation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-033",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Health official: Our public awareness campaign about the dangers of smoking has been highly successful. In the five years since the campaign began, the percentage of adults who smoke has declined from 22% to 18%. This 4-percentage-point decrease shows that our messaging is changing behavior and saving lives.`,
    questionStem: "Which one of the following, if true, most seriously weakens the health official's conclusion?",
    answerChoices: [
      { letter: "A", text: "The campaign cost more than initially budgeted" },
      { letter: "B", text: "In the five years before the campaign, smoking rates declined from 26% to 22%" },
      { letter: "C", text: "Some adults who quit smoking did so for reasons unrelated to health concerns" },
      { letter: "D", text: "The campaign focused primarily on preventing young people from starting to smoke" },
      { letter: "E", text: "Smoking rates vary significantly across different regions of the country" },
    ],
    correctAnswer: "B",
    explanation: "The official attributes the 4-point decline to the campaign. But if smoking rates were already declining by 4 points in the five years before the campaign, then the decline during the campaign period simply continued an existing trend. The campaign may not have accelerated the decline at all, weakening the claim of its success.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Art critic: Abstract expressionist paintings cannot be objectively evaluated because they lack representational content. When a painting depicts recognizable objects or scenes, we can assess how accurately and skillfully the artist has rendered them. But abstract works offer no such external standard of comparison, leaving critics with nothing but subjective impressions.`,
    questionStem: "The art critic's argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "Representational accuracy is the only basis for objective evaluation of art" },
      { letter: "B", text: "Abstract expressionism is an inferior form of artistic expression" },
      { letter: "C", text: "Subjective impressions have no value in art criticism" },
      { letter: "D", text: "All representational paintings can be objectively evaluated" },
      { letter: "E", text: "Artists intend their abstract works to be evaluated subjectively" },
    ],
    correctAnswer: "A",
    explanation: "The critic argues that without representational content, there is no basis for objective evaluation. This reasoning only works if representational accuracy is the only possible objective standard. If other objective criteria exist (composition, technique, color theory, emotional impact measurable through viewer responses), then abstract works could still be objectively evaluated.",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Recent studies suggest that multitasking reduces productivity and increases errors. Workers who frequently switch between tasks take longer to complete each task and make more mistakes than those who focus on one task at a time. Yet many employers still encourage multitasking as a desirable skill. Given this evidence, employers should reconsider their expectations and instead create work environments that allow for sustained focus on single tasks.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Multitasking reduces productivity and increases errors" },
      { letter: "B", text: "Many employers encourage multitasking as a desirable skill" },
      { letter: "C", text: "Workers who focus on single tasks perform better than those who multitask" },
      { letter: "D", text: "Employers should reconsider their expectations and create environments allowing sustained focus" },
      { letter: "E", text: "Current workplace expectations are misaligned with research on productivity" },
    ],
    correctAnswer: "D",
    explanation: "The phrase 'Given this evidence' signals that what follows is the conclusion drawn from the preceding premises. The main conclusion is the recommendation that employers should reconsider their expectations and create work environments that allow for sustained focus. The research findings serve as premises supporting this recommendation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-036",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: You claim that eating organic food is healthier than eating conventionally grown food. But I notice that you also eat at fast food restaurants regularly, consume sugary drinks daily, and rarely exercise. If you truly believed organic food was important for health, you would be more consistent about other health behaviors. Your advocacy for organic food rings hollow given your overall lifestyle.`,
    questionStem: "The nutritionist's response to the claim about organic food",
    answerChoices: [
      { letter: "A", text: "provides scientific evidence that organic food is not healthier than conventional food" },
      { letter: "B", text: "challenges the person's credibility rather than addressing the claim directly" },
      { letter: "C", text: "shows that organic food cannot compensate for other unhealthy behaviors" },
      { letter: "D", text: "demonstrates that the claim about organic food is logically inconsistent" },
      { letter: "E", text: "argues that multiple health behaviors must be adopted simultaneously" },
    ],
    correctAnswer: "B",
    explanation: "The nutritionist attacks the person making the claim rather than the claim itself. This is an ad hominem argument. Instead of providing evidence about whether organic food is healthier, the nutritionist focuses on the speaker's inconsistent behavior. The speaker's lifestyle does not determine whether their claim about organic food is true.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-037",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Investment advisor: Last year, 80% of my stock recommendations generated positive returns for my clients. My competitor, by contrast, had only 60% of his recommendations perform positively. This proves that my investment strategy is superior and that clients should trust my judgment over his.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider the magnitude of returns, not just whether they were positive" },
      { letter: "B", text: "assumes that past performance guarantees future results" },
      { letter: "C", text: "does not account for different levels of risk in the recommended investments" },
      { letter: "D", text: "overlooks the possibility that market conditions favored certain types of investments" },
      { letter: "E", text: "ignores the number of recommendations each advisor made" },
    ],
    correctAnswer: "A",
    explanation: "The argument only considers whether returns were positive or negative, not how large they were. If the competitor's successful 60% gained 50% each while the advisor's successful 80% gained only 2% each, the competitor's strategy could still be better overall. The argument fails to consider the magnitude of gains and losses.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-038",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Educational researchers propose that teaching students to play chess improves their general cognitive abilities, including skills in mathematics and logical reasoning. They base this proposal on observations that students who regularly play chess perform better on standardized tests than students who do not play chess.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' proposal?",
    answerChoices: [
      { letter: "A", text: "Chess requires players to think several moves ahead and consider multiple possibilities" },
      { letter: "B", text: "Students randomly assigned to chess instruction showed greater improvement on reasoning tests than a control group" },
      { letter: "C", text: "Many successful mathematicians and scientists enjoy playing chess as a hobby" },
      { letter: "D", text: "Chess has been played for centuries across many different cultures" },
      { letter: "E", text: "Students who play chess also tend to participate in other academic extracurricular activities" },
    ],
    correctAnswer: "B",
    explanation: "The researchers claim chess improves cognitive abilities, but correlation between chess playing and test performance could be due to other factors. A randomized experiment with a control group eliminates selection bias by randomly assigning students to receive chess instruction. If those students show greater improvement, it provides causal evidence that chess itself produces the benefit.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-039",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `City planner: Building more highways will reduce traffic congestion. When highways are expanded, each individual road has more capacity, so traffic flows more smoothly. Therefore, the city should invest in highway expansion as the solution to our traffic problems.`,
    questionStem: "Which one of the following, if true, most seriously weakens the city planner's argument?",
    answerChoices: [
      { letter: "A", text: "Highway construction causes temporary traffic disruptions during the building period" },
      { letter: "B", text: "Some residents oppose highway expansion due to noise and air quality concerns" },
      { letter: "C", text: "Increased highway capacity induces more people to drive, often restoring congestion to previous levels" },
      { letter: "D", text: "Public transportation systems are underfunded in most cities" },
      { letter: "E", text: "Other cities have built highways that successfully reduced their traffic congestion" },
    ],
    correctAnswer: "C",
    explanation: "This describes the phenomenon of induced demand. If building more highways causes more people to drive (because driving becomes more attractive when there is more capacity), congestion may return to previous levels. The increased capacity is filled by new drivers, undermining the goal of reducing congestion through expansion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-040",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Theater critic: This season's production of Hamlet is the best I have ever seen. The lead actor brought unprecedented depth to the character, the staging was innovative yet true to the text, and the supporting cast performed flawlessly. Audiences seeking the definitive Hamlet experience should not miss this production.`,
    questionStem: "The critic's recommendation depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "The critic's judgment of theatrical quality is representative of what audiences will appreciate" },
      { letter: "B", text: "Hamlet is the most important play in the theatrical canon" },
      { letter: "C", text: "Innovation in staging always improves a production's quality" },
      { letter: "D", text: "The lead actor has more theatrical experience than other actors who have played Hamlet" },
      { letter: "E", text: "Supporting cast performances are as important as the lead actor's performance" },
    ],
    correctAnswer: "A",
    explanation: "The critic recommends the production to audiences based on the critic's own assessment that it is the best. This recommendation only makes sense if the critic's judgment is representative of what audiences will appreciate. If the critic's tastes diverge significantly from general audiences, the recommendation would not be well-founded.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-041",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `No one who has been convicted of a felony can serve on a jury in this jurisdiction. All registered voters are eligible for jury duty unless they have been convicted of a felony. Maria is a registered voter who has never been convicted of a felony. Thomas has been convicted of a felony and is not a registered voter.`,
    questionStem: "If the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Maria will be selected to serve on a jury" },
      { letter: "B", text: "Thomas cannot become a registered voter" },
      { letter: "C", text: "Maria is eligible for jury duty" },
      { letter: "D", text: "All people eligible for jury duty are registered voters" },
      { letter: "E", text: "Thomas would be eligible for jury duty if he became a registered voter" },
    ],
    correctAnswer: "C",
    explanation: "Maria is a registered voter who has never been convicted of a felony. According to the second statement, all registered voters are eligible for jury duty unless they have been convicted of a felony. Since Maria has never been convicted of a felony, she is eligible for jury duty. Note that being eligible does not mean she will be selected (eliminating A).",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-042",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Adams: Universities should prioritize teaching over research. Students pay tuition for an education, and their learning should be the primary focus. Research often distracts faculty from their teaching responsibilities.

Professor Blake: Research and teaching are complementary, not competing priorities. Faculty who conduct cutting-edge research bring current knowledge into the classroom and model intellectual inquiry for students. Universities that separate teaching and research shortchange both activities.`,
    questionStem: "Professor Adams and Professor Blake disagree about whether",
    answerChoices: [
      { letter: "A", text: "students pay tuition primarily for educational services" },
      { letter: "B", text: "research enriches or detracts from the teaching mission of universities" },
      { letter: "C", text: "faculty members are capable of balancing multiple responsibilities" },
      { letter: "D", text: "cutting-edge research produces knowledge useful for classroom instruction" },
      { letter: "E", text: "universities have obligations to their students" },
    ],
    correctAnswer: "B",
    explanation: "Adams argues research distracts from teaching, suggesting it detracts from the teaching mission. Blake argues research and teaching are complementary and enrich each other. Their core disagreement is about the relationship between research and teaching: whether research helps or hinders the educational mission of universities.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-043",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Any policy that increases government spending without raising taxes will increase the deficit. The proposed infrastructure bill increases government spending substantially. The bill does not include any provisions for raising taxes. Therefore, the infrastructure bill will increase the deficit.`,
    questionStem: "The pattern of reasoning in the argument above is most closely paralleled by which one of the following?",
    answerChoices: [
      { letter: "A", text: "All mammals are warm-blooded. Dolphins are warm-blooded. Therefore, dolphins are mammals." },
      { letter: "B", text: "Any medicine that relieves symptoms without addressing causes will only provide temporary relief. This pain medication relieves symptoms but does not address the underlying cause of the pain. Therefore, this medication will only provide temporary relief." },
      { letter: "C", text: "Some employees who work overtime receive bonus pay. John works overtime regularly. Therefore, John probably receives bonus pay." },
      { letter: "D", text: "If it rains tomorrow, the outdoor event will be cancelled. The weather forecast predicts sunshine. Therefore, the outdoor event will proceed as planned." },
      { letter: "E", text: "All successful businesses have effective marketing. This business has effective marketing. Therefore, this business will be successful." },
    ],
    correctAnswer: "B",
    explanation: "The original argument has this structure: Any X that has property A without property B will have outcome C. This particular X has A but not B. Therefore, this X will have C. Answer B follows the same pattern: Any medicine that does A without B will have C. This medicine does A without B. Therefore, it will have C.",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-044",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Survey data shows that 90% of prison inmates report having watched violent television programs as children. This demonstrates that exposure to violent media causes criminal behavior. To reduce crime, we should restrict children's access to violent content.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "assumes that television is the only medium through which children are exposed to violence" },
      { letter: "B", text: "fails to consider what percentage of children who watched violent programs did not become criminals" },
      { letter: "C", text: "overlooks the possibility that prison inmates might misremember their childhood viewing habits" },
      { letter: "D", text: "ignores other factors that might contribute to both television watching and criminal behavior" },
      { letter: "E", text: "does not specify what types of violent programs the inmates watched" },
    ],
    correctAnswer: "B",
    explanation: "The argument notes that 90% of inmates watched violent TV as children but ignores the base rate. If 90% of all children watched violent TV, then the inmates' rate would match the general population, providing no evidence of a causal link. Without knowing how many children who watched violent TV did not become criminals, we cannot assess whether violent TV increases crime risk.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-045",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company claims that its new allergy medication is superior to existing treatments because clinical trials showed fewer side effects. In the trials, only 5% of patients taking the new medication reported drowsiness, compared to 15% of patients taking the leading competitor's medication.`,
    questionStem: "Which one of the following, if true, most strengthens the company's claim that its medication is superior?",
    answerChoices: [
      { letter: "A", text: "The new medication costs significantly less than the competitor's product" },
      { letter: "B", text: "Both medications showed similar effectiveness in treating allergy symptoms" },
      { letter: "C", text: "The clinical trials were conducted over a six-month period" },
      { letter: "D", text: "Some patients prefer medications that cause mild drowsiness because it helps them sleep" },
      { letter: "E", text: "The competitor's medication has been on the market for over a decade" },
    ],
    correctAnswer: "B",
    explanation: "The company claims superiority based on fewer side effects. But if the competitor's medication is more effective at treating allergies, fewer side effects might not make the new medication superior overall. If both medications are similarly effective, then fewer side effects would indeed make the new medication the better choice, supporting the superiority claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-046",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Historical analysis suggests that democracies rarely go to war against each other. This "democratic peace" phenomenon implies that spreading democracy worldwide would reduce international conflict. Therefore, foreign policy should prioritize promoting democratic governance in authoritarian countries.`,
    questionStem: "Which one of the following, if true, most seriously weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Some authoritarian countries have peaceful relations with democratic neighbors" },
      { letter: "B", text: "Countries transitioning to democracy often experience internal instability and increased propensity for international conflict" },
      { letter: "C", text: "The definition of democracy has changed over time" },
      { letter: "D", text: "Some scholars dispute the statistical methodology used to establish the democratic peace" },
      { letter: "E", text: "Economic interdependence also correlates with reduced conflict between nations" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that promoting democracy will lead to peace. If countries transitioning to democracy actually experience increased conflict, then the process of spreading democracy could increase rather than decrease international conflict, at least in the short term. The end state of established democracies being peaceful does not mean the transition is peaceful.",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-047",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Coffee shop owner: I should raise my prices because the cost of coffee beans has increased by 20% over the past year. If I do not adjust my prices to reflect these higher costs, my profit margin will shrink and my business may become unsustainable.`,
    questionStem: "The coffee shop owner's argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Customers will continue to purchase coffee even at higher prices" },
      { letter: "B", text: "No other coffee shops in the area have raised their prices" },
      { letter: "C", text: "The cost of coffee beans is the only significant expense for the business" },
      { letter: "D", text: "The owner cannot reduce other costs sufficiently to maintain profit margins" },
      { letter: "E", text: "Coffee bean prices will continue to increase in the future" },
    ],
    correctAnswer: "D",
    explanation: "The owner argues for raising prices because costs have risen. This conclusion requires assuming that raising prices is necessary, which in turn requires assuming that cost reductions elsewhere are not sufficient alternatives. If the owner could cut other costs to maintain margins, price increases would not be the only option.",
    difficulty: "medium",
  },
  {
    id: "lr-bank32-048",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Mayor: Our city's unemployment rate dropped from 8% to 6% during my term in office. This improvement clearly demonstrates that my economic policies have been effective at creating jobs and strengthening our local economy.`,
    questionStem: "The mayor's reasoning is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to compare the city's unemployment rate to that of neighboring cities" },
      { letter: "B", text: "does not consider that unemployment might have dropped even more under different policies" },
      { letter: "C", text: "ignores factors other than mayoral policy that could explain the reduced unemployment" },
      { letter: "D", text: "assumes that a 2% decrease in unemployment is a significant improvement" },
      { letter: "E", text: "overlooks the possibility that the unemployment rate was calculated differently at different times" },
    ],
    correctAnswer: "C",
    explanation: "The mayor assumes that because unemployment dropped during the mayor's term, the mayor's policies caused the improvement. However, unemployment could have dropped due to national economic trends, state policies, private sector decisions, or other factors outside the mayor's control. The timing alone does not establish causation.",
    difficulty: "easy",
  },
  {
    id: "lr-bank32-049",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Linguist: Some researchers claim that language shapes thought, meaning speakers of different languages perceive and conceptualize reality differently. Evidence for this claim comes from studies showing that speakers of languages with different color vocabulary categorize colors differently. For example, Russian speakers, whose language has separate words for light blue and dark blue, distinguish these shades faster than English speakers.`,
    questionStem: "Which one of the following, if true, most strengthens the linguist's evidence for the claim that language shapes thought?",
    answerChoices: [
      { letter: "A", text: "Young children in all cultures begin to learn color words at approximately the same age" },
      { letter: "B", text: "When Russian speakers learn English and use it primarily, their speed in distinguishing blue shades decreases" },
      { letter: "C", text: "Some languages have fewer color words than English but the same number as other languages" },
      { letter: "D", text: "Artists who study color theory distinguish colors faster than non-artists regardless of language" },
      { letter: "E", text: "The Russian language has been spoken for over a thousand years" },
    ],
    correctAnswer: "B",
    explanation: "The claim is that language shapes thought. If Russian speakers who learn English and use it primarily become slower at distinguishing blue shades, this suggests their language use is directly affecting their perception. This strengthens the causal claim because it shows that changing language can change cognition.",
    difficulty: "hard",
  },
  {
    id: "lr-bank32-050",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Educational policy analyst: Standardized tests are an effective way to ensure educational accountability. Schools whose students perform well on standardized tests are providing quality education, while schools whose students perform poorly need improvement. Therefore, we should use standardized test scores as the primary measure for evaluating schools.`,
    questionStem: "Which one of the following, if true, most seriously weakens the analyst's argument?",
    answerChoices: [
      { letter: "A", text: "Some teachers believe that standardized tests create stress for students" },
      { letter: "B", text: "High test scores often reflect students' socioeconomic backgrounds rather than the quality of instruction they receive" },
      { letter: "C", text: "Standardized tests have been used in education for many decades" },
      { letter: "D", text: "Some countries with high-performing educational systems use standardized testing" },
      { letter: "E", text: "Teachers may need training to effectively prepare students for standardized tests" },
    ],
    correctAnswer: "B",
    explanation: "The analyst assumes that test scores reflect the quality of education provided by schools. If high test scores primarily reflect students' socioeconomic backgrounds rather than instruction quality, then test scores would not be a valid measure of school quality. A wealthy school district might score well regardless of instruction quality, while a poor district might score poorly despite excellent teaching.",
    difficulty: "easy",
  },
];
