// Logical Reasoning Questions Bank - Set 67
import { Question } from "../lsat-types";

export const lrQuestionsSet67: Question[] = [
  {
    id: "lr-bank67-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during the workday are more productive than those who work continuously. Therefore, the company should mandate that all employees take a fifteen-minute break every two hours to maximize overall productivity.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that what is true for some employees is true for all employees" },
      { letter: "B", text: "fails to consider that mandatory breaks might not have the same effect as voluntary breaks" },
      { letter: "C", text: "overlooks the possibility that some tasks require uninterrupted focus" },
      { letter: "D", text: "confuses correlation with causation in interpreting the study results" },
      { letter: "E", text: "ignores the costs associated with implementing the break policy" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that mandating breaks will produce the same productivity benefits as voluntary breaks. However, the study only showed that employees who choose to take breaks are more productive; it did not establish that forced breaks would yield the same results. The voluntary nature of the breaks may be essential to their effectiveness.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-002",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Archaeologists discovered that ancient pottery fragments found at two distant sites share identical chemical compositions and decorative patterns. The researchers concluded that there must have been trade routes connecting these two regions during the period when the pottery was made.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "The clay used to make the pottery is found only in one of the two regions" },
      { letter: "B", text: "Similar pottery has been found at other archaeological sites in the area" },
      { letter: "C", text: "The decorative patterns were common throughout the ancient world" },
      { letter: "D", text: "Trade routes are known to have existed in neighboring regions during this period" },
      { letter: "E", text: "The pottery fragments date to approximately the same time period" },
    ],
    correctAnswer: "A",
    explanation: "If the clay is found only in one region, then the pottery at the other site must have been transported there, strongly supporting the existence of trade routes. This eliminates the alternative explanation that both regions independently produced similar pottery using local materials.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-003",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The city council argues that building a new sports stadium will revitalize the downtown area. They point to the success of Riverside City, where a new stadium led to a 30% increase in downtown business activity within five years.`,
    questionStem: "Which one of the following, if true, most weakens the argument?",
    answerChoices: [
      { letter: "A", text: "Riverside City's stadium cost more than the proposed stadium would cost" },
      { letter: "B", text: "The proposed stadium would be built on the outskirts of downtown rather than in the center" },
      { letter: "C", text: "Riverside City also implemented major tax incentives for downtown businesses at the same time the stadium opened" },
      { letter: "D", text: "Some residents oppose the stadium due to concerns about traffic congestion" },
      { letter: "E", text: "The proposed stadium would seat fewer spectators than Riverside City's stadium" },
    ],
    correctAnswer: "C",
    explanation: "This answer weakens the argument by providing an alternative explanation for Riverside City's success. If major tax incentives were implemented simultaneously, the increase in business activity might be attributable to those incentives rather than to the stadium, undermining the council's reasoning.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-004",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `All successful entrepreneurs possess exceptional risk tolerance. Maria has demonstrated exceptional risk tolerance throughout her career. Therefore, Maria will be a successful entrepreneur.`,
    questionStem: "The conclusion follows logically if which one of the following is assumed?",
    answerChoices: [
      { letter: "A", text: "Exceptional risk tolerance is the only quality needed for entrepreneurial success" },
      { letter: "B", text: "Maria has other qualities commonly associated with successful entrepreneurs" },
      { letter: "C", text: "Most people with exceptional risk tolerance become entrepreneurs" },
      { letter: "D", text: "Successful entrepreneurs are more likely to take risks than unsuccessful ones" },
      { letter: "E", text: "Maria has already started her own business" },
    ],
    correctAnswer: "A",
    explanation: "The argument commits the fallacy of affirming the consequent: it assumes that because all successful entrepreneurs have risk tolerance, having risk tolerance is sufficient for success. The conclusion only follows if we assume risk tolerance is the only requirement, making exceptional risk tolerance both necessary and sufficient for success.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-005",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Critics claim that social media has made people more narcissistic. However, studies show that rates of narcissistic personality traits have remained stable over the past few decades. Furthermore, social media simply provides a new platform for behaviors that existed long before the internet. The real change is not in human psychology but in the visibility of self-promotional behavior.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Critics are wrong to claim that social media has increased narcissism" },
      { letter: "B", text: "Social media provides a platform for pre-existing behaviors" },
      { letter: "C", text: "Narcissistic personality traits have remained stable over time" },
      { letter: "D", text: "Self-promotional behavior is more visible now than in the past" },
      { letter: "E", text: "Studies on narcissism are more reliable than critics' claims" },
    ],
    correctAnswer: "A",
    explanation: "The main conclusion is that critics are wrong about social media causing increased narcissism. The other statements serve as supporting evidence: stable rates of narcissistic traits, social media as a platform for existing behaviors, and increased visibility rather than psychological change all support the rejection of the critics' claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-006",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that artificial intelligence cannot truly understand language because it merely processes symbols without comprehending their meaning. But consider this: when you learned your native language as a child, you also began by associating sounds with objects and actions without deeper understanding. If we accept that humans eventually develop genuine understanding through this process, we cannot categorically deny that AI might develop understanding through a similar pattern-based learning process.`,
    questionStem: "The philosopher's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "drawing an analogy between two learning processes to challenge a categorical claim" },
      { letter: "B", text: "demonstrating that AI has already achieved genuine language understanding" },
      { letter: "C", text: "questioning the definition of understanding used by critics of AI" },
      { letter: "D", text: "providing empirical evidence that contradicts the critics' position" },
      { letter: "E", text: "arguing that symbol processing is sufficient for understanding" },
    ],
    correctAnswer: "A",
    explanation: "The philosopher draws an analogy between how children learn language (starting with pattern-based associations) and how AI learns language. By showing that we accept humans can develop understanding from this starting point, the philosopher challenges the categorical claim that AI cannot develop understanding through a similar process.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company's new medication was tested on 500 volunteers, and 80% reported significant symptom improvement. This proves that the medication is highly effective and should be approved for widespread use.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on a sample size that may be too small to draw reliable conclusions" },
      { letter: "B", text: "fails to consider whether a placebo group showed similar improvement rates" },
      { letter: "C", text: "assumes that volunteers are representative of the general population" },
      { letter: "D", text: "does not address potential side effects of the medication" },
      { letter: "E", text: "ignores the possibility that symptoms might have improved without treatment" },
    ],
    correctAnswer: "B",
    explanation: "Without a control group receiving a placebo, we cannot determine whether the improvement was caused by the medication or by the placebo effect, natural symptom fluctuation, or other factors. The 80% improvement rate is meaningless without comparison to what would have happened without the active medication.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-008",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Legal scholar: Mandatory minimum sentencing laws were intended to reduce judicial discretion and ensure consistent punishment. However, these laws have actually increased prosecutorial discretion, as prosecutors now have more leverage to negotiate plea bargains. This has led to a less fair system overall, as outcomes depend more on prosecutorial decisions than on judicial evaluation of individual circumstances.`,
    questionStem: "Which one of the following, if true, most strengthens the legal scholar's argument?",
    answerChoices: [
      { letter: "A", text: "Judges generally have more legal training than prosecutors" },
      { letter: "B", text: "Prosecutorial decisions are less subject to review and appeal than judicial decisions" },
      { letter: "C", text: "Mandatory minimum sentences apply to a wide variety of offenses" },
      { letter: "D", text: "Some prosecutors decline to pursue charges that carry mandatory minimums" },
      { letter: "E", text: "Plea bargain rates have increased since mandatory minimums were implemented" },
    ],
    correctAnswer: "B",
    explanation: "This strengthens the argument that the system is less fair by showing that prosecutorial discretion is less accountable than judicial discretion. If prosecutorial decisions face less review, the shift of power from judges to prosecutors means less oversight of the decisions that determine outcomes, supporting the claim of reduced fairness.",
    difficulty: "hard",
  },
  {
    id: "lr-bank67-009",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: People who eat breakfast regularly tend to have lower body mass indexes than those who skip breakfast. Therefore, eating breakfast is an effective strategy for weight management.`,
    questionStem: "Which one of the following, if true, most weakens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Some people who eat breakfast consume more total daily calories than those who skip it" },
      { letter: "B", text: "Breakfast eating habits are often established in childhood" },
      { letter: "C", text: "People who are already lean may be more likely to have regular eating schedules including breakfast" },
      { letter: "D", text: "The type of food eaten at breakfast affects its nutritional value" },
      { letter: "E", text: "Skipping breakfast can lead to overeating later in the day" },
    ],
    correctAnswer: "C",
    explanation: "This suggests reverse causation: rather than breakfast eating causing lower BMI, being lean might cause regular breakfast habits. If naturally lean people are more likely to eat breakfast, the correlation does not support the causal claim that eating breakfast helps with weight management.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-010",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city's new recycling program requires residents to sort their recyclables into separate bins. Since the previous single-bin system resulted in high contamination rates that made recycling economically unviable, the new program will make recycling economically sustainable.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Residents will comply with the requirement to sort their recyclables" },
      { letter: "B", text: "The new program will be less expensive to operate than the old one" },
      { letter: "C", text: "High contamination rates were the only factor making recycling unviable" },
      { letter: "D", text: "All recyclable materials can be sorted into the designated categories" },
      { letter: "E", text: "Other cities have successfully implemented similar sorting programs" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that residents will actually sort their recyclables as required. If residents do not comply with the sorting requirement, contamination rates could remain high, and the new program would not achieve its goal of making recycling economically sustainable.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-011",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Chen: Universities should prioritize teaching practical job skills because students increasingly attend college primarily to improve their employment prospects. The traditional focus on liberal arts education no longer serves students' needs.

Professor Williams: The purpose of higher education has never been merely vocational training. Universities that abandon the liberal arts in favor of narrow skill-based curricula fail to develop the critical thinking and adaptability that serve students throughout their careers.`,
    questionStem: "Professor Chen and Professor Williams disagree about whether",
    answerChoices: [
      { letter: "A", text: "students attend college primarily to improve employment prospects" },
      { letter: "B", text: "critical thinking is important for long-term career success" },
      { letter: "C", text: "liberal arts education serves students' needs" },
      { letter: "D", text: "universities have traditionally focused on liberal arts" },
      { letter: "E", text: "practical job skills can be taught effectively at universities" },
    ],
    correctAnswer: "C",
    explanation: "Chen argues that liberal arts education no longer serves students' needs, while Williams argues that liberal arts develop critical thinking and adaptability that serve students throughout their careers. They directly disagree about whether liberal arts education is valuable for students.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-012",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All licensed physicians have completed medical school. Some licensed physicians are excellent diagnosticians. Therefore, some people who have completed medical school are excellent diagnosticians.`,
    questionStem: "The pattern of reasoning in the argument above is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "All marathon runners train regularly. Some marathon runners are vegetarians. Therefore, some people who train regularly are vegetarians." },
      { letter: "B", text: "All cats are mammals. All mammals are warm-blooded. Therefore, all cats are warm-blooded." },
      { letter: "C", text: "Some teachers are patient. All patient people are good listeners. Therefore, some teachers are good listeners." },
      { letter: "D", text: "No reptiles are mammals. Some pets are reptiles. Therefore, some pets are not mammals." },
      { letter: "E", text: "All lawyers passed the bar exam. Some people who passed the bar exam are not practicing law. Therefore, some lawyers are not practicing law." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments follow the same valid logical structure: All A are B. Some A are C. Therefore, some B are C. The original argument and answer choice A both use this pattern, where the middle term (licensed physicians/marathon runners) connects the other two categories.",
    difficulty: "hard",
  },
  {
    id: "lr-bank67-013",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Senator: My opponent claims that my proposed tax cut will primarily benefit the wealthy. But my opponent has received substantial campaign contributions from labor unions, which have a vested interest in opposing tax cuts. Therefore, my opponent's criticism should be disregarded.`,
    questionStem: "The reasoning in the senator's argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that union members do not pay taxes" },
      { letter: "B", text: "attacks the source of a claim rather than addressing the claim itself" },
      { letter: "C", text: "fails to provide evidence that the tax cut would not benefit the wealthy" },
      { letter: "D", text: "ignores the possibility that the opponent has other reasons for the criticism" },
      { letter: "E", text: "presumes that all labor unions share the same political views" },
    ],
    correctAnswer: "B",
    explanation: "The senator commits an ad hominem fallacy by attacking the opponent's funding sources rather than addressing the substance of the criticism. The opponent's connections to labor unions do not determine whether the claim about the tax cut benefiting the wealthy is true or false.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Biologist: The recent decline in the local bee population is likely caused by the increased use of a particular pesticide in the region. Bees exposed to this pesticide in laboratory conditions showed impaired navigation abilities and reduced foraging efficiency.`,
    questionStem: "Which one of the following, if true, most strengthens the biologist's argument?",
    answerChoices: [
      { letter: "A", text: "The pesticide has been banned in several other countries due to environmental concerns" },
      { letter: "B", text: "The timing of the bee population decline corresponds with the introduction of the pesticide in local farming" },
      { letter: "C", text: "Laboratory conditions often differ significantly from natural environments" },
      { letter: "D", text: "Other insect populations in the region have also declined" },
      { letter: "E", text: "The pesticide is less toxic than some alternatives" },
    ],
    correctAnswer: "B",
    explanation: "The temporal correlation between the pesticide's introduction and the population decline strengthens the causal claim. If the decline began when the pesticide was introduced, this supports the argument that the pesticide is responsible, especially given the laboratory evidence of its harmful effects on bees.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-015",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Art historian: The painting attributed to Vermeer must be authentic because it contains the same pigments that Vermeer used in his confirmed works, and spectral analysis shows the same brushstroke patterns characteristic of his technique.`,
    questionStem: "Which one of the following, if true, most weakens the art historian's argument?",
    answerChoices: [
      { letter: "A", text: "Vermeer's paintings are among the most valuable in the world" },
      { letter: "B", text: "Sophisticated forgers have been known to study and replicate masters' techniques and materials" },
      { letter: "C", text: "The painting was discovered in a private collection with no documented provenance" },
      { letter: "D", text: "Some of Vermeer's confirmed works were painted by his students under his supervision" },
      { letter: "E", text: "Spectral analysis is a relatively new technology in art authentication" },
    ],
    correctAnswer: "B",
    explanation: "If skilled forgers can replicate both the materials and techniques of old masters, then the presence of authentic pigments and characteristic brushstrokes does not prove authenticity. This weakens the argument by showing that the evidence cited could be present in a forgery.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-016",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The government should not regulate the content of video games. Parents, not the government, should be responsible for monitoring what their children play. After all, parents are in the best position to know what is appropriate for their own children.`,
    questionStem: "The argument relies on the assumption that",
    answerChoices: [
      { letter: "A", text: "all parents actively monitor their children's video game usage" },
      { letter: "B", text: "the government's ability to know what is appropriate for children is a relevant consideration for whether it should regulate content" },
      { letter: "C", text: "video games do not have harmful effects on children" },
      { letter: "D", text: "the video game industry would self-regulate without government intervention" },
      { letter: "E", text: "government regulation would be ineffective at limiting children's access to inappropriate content" },
    ],
    correctAnswer: "B",
    explanation: "The argument concludes that the government should not regulate based on the premise that parents are better positioned to know what is appropriate. This reasoning assumes that being better positioned to judge appropriateness is relevant to the question of who should regulate content.",
    difficulty: "hard",
  },
  {
    id: "lr-bank67-017",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Studies show that employees who feel valued by their employers are more likely to remain with the company. Company X has one of the lowest employee turnover rates in its industry. Company Y, which is in the same industry, recently implemented a comprehensive employee recognition program.`,
    questionStem: "If the statements above are true, which one of the following can be properly inferred?",
    answerChoices: [
      { letter: "A", text: "Company X has an employee recognition program" },
      { letter: "B", text: "Company Y's turnover rate will decrease" },
      { letter: "C", text: "Employees at Company X feel valued" },
      { letter: "D", text: "Feeling valued is one factor that may influence employee retention" },
      { letter: "E", text: "Company Y previously had a high turnover rate" },
    ],
    correctAnswer: "D",
    explanation: "The first statement establishes that feeling valued affects retention. This directly supports the inference that feeling valued is a factor that may influence whether employees stay. The other options make assumptions not supported by the given information.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-018",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Environmental activist: We must ban all plastic packaging immediately. Every year, millions of tons of plastic waste end up in our oceans, harming marine life. Continuing to use plastic packaging shows a callous disregard for the environment.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "uses emotionally charged language to dismiss those who disagree" },
      { letter: "B", text: "fails to consider whether alternatives to plastic might have their own environmental costs" },
      { letter: "C", text: "assumes that all plastic packaging ends up in the ocean" },
      { letter: "D", text: "provides no evidence that plastic harms marine life" },
      { letter: "E", text: "ignores the practical challenges of implementing an immediate ban" },
    ],
    correctAnswer: "B",
    explanation: "The argument fails to consider that alternatives to plastic packaging (such as paper, glass, or metal) might have their own environmental costs, such as deforestation, higher transportation emissions due to weight, or other impacts. A complete analysis would need to compare the total environmental impact of alternatives.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-019",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critics argue that space exploration is a waste of resources that should be spent on earthly problems. However, the technologies developed for space exploration have led to numerous innovations we use daily, from memory foam to water purification systems. The economic value of these spin-off technologies exceeds the cost of the space programs that produced them.`,
    questionStem: "The argument proceeds by",
    answerChoices: [
      { letter: "A", text: "showing that the benefits of space exploration outweigh its costs" },
      { letter: "B", text: "questioning the motives of those who criticize space exploration" },
      { letter: "C", text: "arguing that space exploration directly solves earthly problems" },
      { letter: "D", text: "demonstrating that critics are unaware of space technology's benefits" },
      { letter: "E", text: "claiming that all technological progress depends on space exploration" },
    ],
    correctAnswer: "A",
    explanation: "The argument directly counters the 'waste of resources' criticism by demonstrating that space exploration produces economic benefits through spin-off technologies that exceed its costs. This is a cost-benefit argument showing that the investment pays off.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-020",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economist: Countries that invest heavily in early childhood education tend to have higher economic productivity in the long term. Therefore, increasing funding for preschool programs would be an effective economic policy.`,
    questionStem: "Which one of the following, if true, most strengthens the economist's argument?",
    answerChoices: [
      { letter: "A", text: "Early childhood education improves children's cognitive development and future earning potential" },
      { letter: "B", text: "Countries with high economic productivity tend to have more resources to invest in education" },
      { letter: "C", text: "Some countries with low investment in early education have high economic productivity" },
      { letter: "D", text: "Preschool programs are popular among voters" },
      { letter: "E", text: "Teacher salaries in early childhood education are relatively low" },
    ],
    correctAnswer: "A",
    explanation: "This provides a mechanism explaining how early education leads to economic productivity: improved cognitive development increases earning potential, which contributes to productivity. This strengthens the causal claim underlying the economist's recommendation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Manager: Our new open office design has improved collaboration among team members. Since we removed the cubicle walls six months ago, the number of collaborative projects has increased by 40%.`,
    questionStem: "Which one of the following, if true, most weakens the manager's argument?",
    answerChoices: [
      { letter: "A", text: "Some employees have complained about noise levels in the open office" },
      { letter: "B", text: "The company also introduced a new project management system that encourages team-based work six months ago" },
      { letter: "C", text: "Open office designs are popular in the technology industry" },
      { letter: "D", text: "The number of individual projects has remained constant" },
      { letter: "E", text: "Some collaborative projects have been less successful than anticipated" },
    ],
    correctAnswer: "B",
    explanation: "This provides an alternative explanation for the increase in collaborative projects. If a new project management system encouraging teamwork was introduced at the same time as the office redesign, the increase might be due to the system rather than the open office layout.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-022",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The museum's new interactive exhibit on climate change will be more effective at changing visitors' attitudes than the previous static displays. Research shows that people remember information better when they actively engage with it rather than passively observe it.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "all visitors will choose to interact with the new exhibit" },
      { letter: "B", text: "better information retention leads to attitude change" },
      { letter: "C", text: "the previous displays provided accurate information about climate change" },
      { letter: "D", text: "interactive exhibits are more expensive to create than static displays" },
      { letter: "E", text: "visitors come to the museum specifically to learn about climate change" },
    ],
    correctAnswer: "B",
    explanation: "The argument connects better memory retention to attitude change, but these are different outcomes. The assumption is that remembering information better leads to changing attitudes. Without this link, better retention would not necessarily translate to greater effectiveness at changing attitudes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-023",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Councilwoman: The proposed highway extension will not increase traffic in our neighborhood. The traffic study commissioned by the highway department concluded that traffic would increase by less than 5%, which is negligible.`,
    questionStem: "The reasoning in the argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on a study that may be biased in favor of the highway extension" },
      { letter: "B", text: "treats a small increase as equivalent to no increase" },
      { letter: "C", text: "fails to consider the views of neighborhood residents" },
      { letter: "D", text: "assumes that the traffic study's methodology was sound" },
      { letter: "E", text: "ignores other potential negative effects of the highway extension" },
    ],
    correctAnswer: "B",
    explanation: "The argument equates a 'less than 5%' increase with 'no increase.' This is a false equivalence; even a small increase is still an increase. The councilwoman dismisses a real projected increase by characterizing it as negligible without justifying why 5% should be considered equivalent to zero.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-024",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Technological unemployment—the displacement of workers by machines—has been a concern since the Industrial Revolution. Yet historically, technology has created more jobs than it has destroyed, as new industries emerge to replace old ones. However, the current wave of artificial intelligence differs fundamentally from previous technologies because it can perform cognitive tasks that were once exclusively human. Therefore, we cannot assume that history will repeat itself.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Artificial intelligence performs cognitive tasks that were once exclusively human" },
      { letter: "B", text: "Technology has historically created more jobs than it destroyed" },
      { letter: "C", text: "Past patterns of technological job creation may not apply to artificial intelligence" },
      { letter: "D", text: "Technological unemployment has been a concern since the Industrial Revolution" },
      { letter: "E", text: "New industries emerge to replace those displaced by technology" },
    ],
    correctAnswer: "C",
    explanation: "The conclusion is stated at the end: 'we cannot assume that history will repeat itself.' The argument acknowledges the historical pattern but argues that AI's unique characteristics (performing cognitive tasks) mean we cannot assume the same job-creation pattern will continue.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-025",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Patel: Clinical trials for new medications should always include a placebo control group. Without this comparison, we cannot determine whether observed improvements are due to the medication or other factors.

Dr. Okonkwo: When effective treatments already exist, it would be unethical to give patients in a control group placebos instead of proven treatments. Clinical trials should compare new medications to existing standard treatments.`,
    questionStem: "The main point of disagreement between Dr. Patel and Dr. Okonkwo concerns",
    answerChoices: [
      { letter: "A", text: "whether clinical trials can accurately measure medication effectiveness" },
      { letter: "B", text: "whether placebo controls are always the appropriate comparison group in clinical trials" },
      { letter: "C", text: "whether new medications should undergo clinical testing before approval" },
      { letter: "D", text: "whether existing treatments for diseases are effective" },
      { letter: "E", text: "whether patient welfare should be considered in clinical trial design" },
    ],
    correctAnswer: "B",
    explanation: "Dr. Patel argues placebo controls should always be used, while Dr. Okonkwo argues they should not be used when effective treatments exist. Their disagreement is specifically about whether placebo controls are always appropriate, not about clinical trials in general or patient welfare as an abstract principle.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-026",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Psychologist: People who practice gratitude exercises daily report higher levels of happiness. This suggests that cultivating gratitude can improve mental well-being.`,
    questionStem: "Which one of the following, if true, most strengthens the argument?",
    answerChoices: [
      { letter: "A", text: "People who are already happy may be more likely to practice gratitude exercises" },
      { letter: "B", text: "The same people reported lower happiness levels before they began the gratitude exercises" },
      { letter: "C", text: "Gratitude exercises are recommended by many self-help books" },
      { letter: "D", text: "Happiness levels vary significantly among individuals" },
      { letter: "E", text: "Some people who practice gratitude exercises do not report increased happiness" },
    ],
    correctAnswer: "B",
    explanation: "This addresses the potential reverse causation problem. If the same individuals were less happy before starting the exercises, it suggests that the exercises caused the improvement rather than happy people simply being more inclined to practice gratitude.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-027",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Company executive: Our decision to move customer service operations overseas has been a success. Customer satisfaction ratings have remained stable at 85% since the transition, proving that offshore customer service can be just as effective as domestic operations.`,
    questionStem: "Which one of the following, if true, most weakens the executive's conclusion?",
    answerChoices: [
      { letter: "A", text: "The company's competitors have also moved customer service operations overseas" },
      { letter: "B", text: "Customer satisfaction ratings were 92% before the transition to offshore operations" },
      { letter: "C", text: "The offshore customer service center employs more staff than the previous domestic center" },
      { letter: "D", text: "Some customers prefer speaking with domestic customer service representatives" },
      { letter: "E", text: "The cost savings from offshore operations have exceeded projections" },
    ],
    correctAnswer: "B",
    explanation: "If satisfaction ratings were 92% before the transition and are now 85%, there has actually been a 7-percentage-point decline. The executive's claim that ratings have 'remained stable' is misleading, and the evidence actually suggests offshore service is less effective than domestic operations.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-028",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Editorial: The city should not implement the proposed congestion pricing plan. A recent poll shows that 65% of city residents oppose the plan. Democratic principles require that government policies reflect the will of the people.`,
    questionStem: "The reasoning in the editorial is flawed in that it",
    answerChoices: [
      { letter: "A", text: "assumes that poll respondents are representative of all city residents" },
      { letter: "B", text: "fails to consider that public opinion may change over time" },
      { letter: "C", text: "presupposes that democratic governance requires implementing whatever is most popular" },
      { letter: "D", text: "does not address the potential benefits of congestion pricing" },
      { letter: "E", text: "relies on an ambiguous definition of 'democratic principles'" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that democracy means simply implementing whatever the majority currently supports. However, democratic governance often involves elected representatives making decisions they believe are in the public interest, even if unpopular. The argument conflates popular opinion with democratic legitimacy.",
    difficulty: "hard",
  },
  {
    id: "lr-bank67-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The ancient city must have been a major trading center. Archaeologists have uncovered coins from distant lands throughout the excavation site, indicating that merchants from many regions conducted business there.`,
    questionStem: "The argument requires the assumption that",
    answerChoices: [
      { letter: "A", text: "only major trading centers attracted merchants from many regions" },
      { letter: "B", text: "the coins were not brought to the site after the city was abandoned" },
      { letter: "C", text: "all major trading centers have left archaeological evidence of foreign coins" },
      { letter: "D", text: "the city's residents traveled to distant lands" },
      { letter: "E", text: "ancient merchants always carried coins from their home regions" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes the coins were deposited during the city's active period. If the coins were brought to the site later (perhaps by collectors or through geological processes), they would not indicate that the city was a trading center when it was inhabited.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-030",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Some politicians are lawyers. No lawyers are unaware of legal procedures. Therefore, some politicians are not unaware of legal procedures.`,
    questionStem: "The pattern of reasoning in the argument above is most closely paralleled by which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some artists are musicians. All musicians have musical training. Therefore, some artists have musical training." },
      { letter: "B", text: "All doctors are scientists. Some scientists are researchers. Therefore, some doctors are researchers." },
      { letter: "C", text: "No athletes are unhealthy. Some celebrities are athletes. Therefore, some celebrities are not unhealthy." },
      { letter: "D", text: "Some teachers are parents. Some parents are strict. Therefore, some teachers are strict." },
      { letter: "E", text: "All engineers have technical skills. No one without technical skills can design bridges. Therefore, all bridge designers are engineers." },
    ],
    correctAnswer: "C",
    explanation: "Both arguments follow the same pattern: Some A are B. No B are C. Therefore, some A are not C. The original argument: Some politicians(A) are lawyers(B). No lawyers(B) are unaware(C). Therefore, some politicians(A) are not unaware(C). Answer C matches: Some celebrities(A) are athletes(B). No athletes(B) are unhealthy(C). Therefore, some celebrities(A) are not unhealthy(C).",
    difficulty: "hard",
  },
  {
    id: "lr-bank67-031",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Defense attorney: The prosecution claims my client stole the painting at 9 PM. But security footage shows my client was at a restaurant across town at 9 PM. A person cannot be in two places at once. Therefore, my client did not steal the painting.`,
    questionStem: "The defense attorney's argument uses which one of the following argumentative techniques?",
    answerChoices: [
      { letter: "A", text: "Attacking the credibility of the prosecution's witnesses" },
      { letter: "B", text: "Demonstrating that the prosecution's conclusion leads to an impossibility" },
      { letter: "C", text: "Providing an alibi that makes the alleged crime physically impossible" },
      { letter: "D", text: "Questioning the accuracy of the time stated by the prosecution" },
      { letter: "E", text: "Suggesting an alternative suspect for the crime" },
    ],
    correctAnswer: "C",
    explanation: "The defense attorney provides an alibi (the restaurant footage) that makes it physically impossible for the client to have committed the crime as alleged. By establishing that the client was elsewhere at the time of the theft, the argument demonstrates the impossibility of the prosecution's claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-032",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Parent: My child should not be required to take physical education classes. She is already on the school gymnastics team, which provides her with plenty of physical activity. Requiring her to take PE would just take time away from her academic studies.`,
    questionStem: "The reasoning in the argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "assumes that gymnastics provides the same benefits as physical education classes" },
      { letter: "B", text: "ignores the possibility that PE classes serve purposes beyond physical activity" },
      { letter: "C", text: "overlooks the fact that academic studies are important" },
      { letter: "D", text: "fails to consider that the child might enjoy PE classes" },
      { letter: "E", text: "presumes that all students on sports teams should be exempt from PE" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes PE is only about physical activity. PE classes often include health education, exposure to various sports, teamwork with diverse peers, and other educational components not provided by gymnastics team membership. The argument overlooks these additional purposes.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-033",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historian: The decline of the Roman Empire was primarily caused by economic factors rather than military defeats. Even as the empire faced military pressures, it was the debasement of currency and resulting inflation that undermined the empire's ability to pay its soldiers and maintain its infrastructure.`,
    questionStem: "Which one of the following, if true, most strengthens the historian's argument?",
    answerChoices: [
      { letter: "A", text: "The Roman Empire's borders were at their greatest extent during a period of economic prosperity" },
      { letter: "B", text: "Many Roman soldiers deserted when their pay lost purchasing power due to inflation" },
      { letter: "C", text: "The Roman Empire lasted longer than most other ancient empires" },
      { letter: "D", text: "Some historians attribute the decline to moral decay rather than economic factors" },
      { letter: "E", text: "The Byzantine Empire continued for centuries after the Western Roman Empire fell" },
    ],
    correctAnswer: "B",
    explanation: "This directly supports the causal mechanism proposed by the historian: economic problems (inflation) led to military weakness (soldiers deserting). This connects the economic factors to the military problems, showing how economic decline caused the empire's failure to maintain its defenses.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-034",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Sociologist: Access to higher education has become more equitable in recent decades. The percentage of college students from lower-income families has increased significantly since 1990.`,
    questionStem: "Which one of the following, if true, most weakens the sociologist's conclusion?",
    answerChoices: [
      { letter: "A", text: "Tuition costs at private universities have increased faster than inflation" },
      { letter: "B", text: "The percentage of lower-income families in the general population has increased even more than their representation in college" },
      { letter: "C", text: "Many lower-income students attend community colleges rather than four-year universities" },
      { letter: "D", text: "Scholarship programs for lower-income students have expanded" },
      { letter: "E", text: "College graduation rates for lower-income students remain lower than for higher-income students" },
    ],
    correctAnswer: "B",
    explanation: "If the general population has become proportionally more lower-income, then a higher percentage of lower-income college students might actually represent decreased equity. For example, if lower-income families went from 20% of the population to 40%, but college enrollment only went from 10% to 15%, relative access has actually declined.",
    difficulty: "hard",
  },
  {
    id: "lr-bank67-035",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The candidate's proposal to eliminate the income tax and replace it with a national sales tax would be disastrous. Sales taxes are regressive, taking a larger percentage of income from lower-income households. Under this proposal, the tax burden would shift dramatically from the wealthy to the poor.`,
    questionStem: "The argument depends on assuming which one of the following?",
    answerChoices: [
      { letter: "A", text: "The current income tax system is progressive" },
      { letter: "B", text: "Lower-income households spend a larger percentage of their income on taxable purchases" },
      { letter: "C", text: "The candidate's proposal would not include exemptions for essential goods" },
      { letter: "D", text: "A national sales tax would be more difficult to administer than an income tax" },
      { letter: "E", text: "Wealthy households would find ways to avoid the sales tax" },
    ],
    correctAnswer: "A",
    explanation: "For the tax burden to 'shift' from wealthy to poor, the current system must be taxing the wealthy more heavily (progressive). If the current system were already regressive or flat, a sales tax might not represent a shift. The argument assumes the current income tax is progressive, making the change to a regressive tax significant.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-036",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Food critic: This restaurant cannot be serving authentic Italian cuisine. I visited last week and ordered their signature pasta dish, which was served with a cream-based sauce. In northern Italy, where I studied, cream sauces are common, but this restaurant claims to specialize in southern Italian cuisine, which traditionally uses olive oil and tomato-based sauces.`,
    questionStem: "The food critic's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "relies on the critic's personal experience rather than objective standards" },
      { letter: "B", text: "assumes that authentic cuisine cannot incorporate influences from other regions" },
      { letter: "C", text: "generalizes from a single dish to the restaurant's entire menu" },
      { letter: "D", text: "fails to consider that culinary traditions evolve over time" },
      { letter: "E", text: "presumes that the critic is an expert on Italian cuisine" },
    ],
    correctAnswer: "C",
    explanation: "The critic bases the conclusion that the restaurant cannot serve authentic cuisine on a single dish. Even if one dish is not traditionally southern Italian, the restaurant could serve many authentic southern Italian dishes. One exception does not invalidate the restaurant's overall authenticity claim.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `People often argue that competitive sports build character in young people by teaching them to handle both victory and defeat gracefully. However, research shows that young athletes who receive poor coaching often develop negative traits such as aggression and poor sportsmanship. The character-building benefits of sports are not automatic but depend heavily on the quality of adult supervision.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Competitive sports do not always build character in young people" },
      { letter: "B", text: "Poor coaching can lead to negative traits in young athletes" },
      { letter: "C", text: "The character-building benefits of sports require quality adult supervision" },
      { letter: "D", text: "Young people should only participate in sports with good coaches" },
      { letter: "E", text: "Research has examined the effects of coaching quality on young athletes" },
    ],
    correctAnswer: "C",
    explanation: "The main conclusion is stated in the final sentence: the character-building benefits of sports are not automatic but depend on adult supervision quality. The argument uses research about poor coaching effects as evidence to support this conclusion about the conditional nature of sports' benefits.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-038",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Political scientist: Democracies rarely go to war with other democracies. This suggests that promoting democratic governance around the world would reduce international conflict.`,
    questionStem: "Which one of the following, if true, most strengthens the political scientist's argument?",
    answerChoices: [
      { letter: "A", text: "The number of democracies in the world has increased significantly since 1945" },
      { letter: "B", text: "Democratic nations have other characteristics, such as higher wealth, that independently reduce the likelihood of conflict" },
      { letter: "C", text: "The democratic peace phenomenon holds even when controlling for factors like trade relationships and geographic distance" },
      { letter: "D", text: "Some non-democracies have peaceful relations with their neighbors" },
      { letter: "E", text: "New democracies are sometimes unstable in their early years" },
    ],
    correctAnswer: "C",
    explanation: "This strengthens the argument by ruling out confounding factors. If democracies avoid war with each other even when controlling for trade, geography, and other factors, then democracy itself appears to be the cause of peace. This supports the claim that promoting democracy would reduce conflict.",
    difficulty: "hard",
  },
  {
    id: "lr-bank67-039",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Nutritionist: Organic foods are no healthier than conventionally grown foods. Numerous studies have found no significant differences in vitamin and mineral content between organic and conventional produce.`,
    questionStem: "Which one of the following, if true, most weakens the nutritionist's argument?",
    answerChoices: [
      { letter: "A", text: "Organic foods are typically more expensive than conventional foods" },
      { letter: "B", text: "Some consumers prefer organic foods for environmental reasons" },
      { letter: "C", text: "Health benefits may result from the absence of pesticide residues rather than differences in nutrient content" },
      { letter: "D", text: "Not all organic farms follow the same growing practices" },
      { letter: "E", text: "The studies compared only fruits and vegetables, not grains or dairy" },
    ],
    correctAnswer: "C",
    explanation: "The nutritionist's argument focuses narrowly on vitamin and mineral content. However, health benefits could come from other factors, such as the absence of pesticide residues. If organic foods are healthier because they contain fewer harmful substances rather than more nutrients, the argument's focus on nutrients misses the point.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-040",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Ethicist: Animal testing for cosmetics is morally wrong because it causes suffering to animals for frivolous purposes. Medical research is different because it aims to save human lives. Therefore, we should ban cosmetic animal testing while allowing it for medical purposes.`,
    questionStem: "The argument is most vulnerable to criticism on which one of the following grounds?",
    answerChoices: [
      { letter: "A", text: "It assumes that all cosmetic testing causes significant animal suffering" },
      { letter: "B", text: "It fails to consider that some medical research may not lead to life-saving treatments" },
      { letter: "C", text: "It does not address whether alternative testing methods exist" },
      { letter: "D", text: "It presumes that human lives are more valuable than animal welfare" },
      { letter: "E", text: "It ignores the economic impact of banning cosmetic animal testing" },
    ],
    correctAnswer: "B",
    explanation: "The argument distinguishes cosmetic testing (frivolous) from medical research (life-saving). However, some medical research may not aim to save lives or may be unlikely to produce useful results. The argument does not address this gray area, potentially allowing 'medical' testing that is as frivolous as cosmetic testing.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-041",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The mayor's plan to reduce traffic congestion by adding more lanes to the highway will fail. Studies consistently show that adding lanes leads to induced demand, where the additional capacity attracts more drivers, eventually returning congestion to previous levels.`,
    questionStem: "The argument relies on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The mayor is unaware of the induced demand phenomenon" },
      { letter: "B", text: "The city's situation is comparable to those in the studies cited" },
      { letter: "C", text: "No other measures will be implemented alongside the lane expansion" },
      { letter: "D", text: "Reducing traffic congestion should be the city's top priority" },
      { letter: "E", text: "The studies were conducted by unbiased researchers" },
    ],
    correctAnswer: "B",
    explanation: "The argument applies general study findings to the specific city. This assumes the city's situation is comparable to those studied. If the city differs significantly (perhaps it has limited growth potential or unique geography), induced demand might not occur to the same degree.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-042",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `All members of the finance committee have access to confidential budget documents. Some employees with access to confidential budget documents are required to undergo background checks. No interns are required to undergo background checks.`,
    questionStem: "If the statements above are true, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "No interns are members of the finance committee" },
      { letter: "B", text: "All members of the finance committee undergo background checks" },
      { letter: "C", text: "Some interns do not have access to confidential budget documents" },
      { letter: "D", text: "Some members of the finance committee are not required to undergo background checks" },
      { letter: "E", text: "All employees with access to confidential documents are on the finance committee" },
    ],
    correctAnswer: "C",
    explanation: "Since some employees with budget document access require background checks, and no interns require background checks, any intern with document access would be among those who don't require checks. But we can determine that some interns must not have access because if all interns had access, and some with access need checks, some interns would need checks - contradiction.",
    difficulty: "hard",
  },
  {
    id: "lr-bank67-043",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: My colleague argues that the new drug is ineffective because only 60% of patients showed improvement, compared to 55% in the placebo group. But this 5% difference, while seemingly small, is both statistically significant and clinically meaningful. A 5% improvement in outcomes across thousands of patients translates to hundreds of lives improved.`,
    questionStem: "The scientist responds to the colleague's argument by",
    answerChoices: [
      { letter: "A", text: "questioning the accuracy of the data presented by the colleague" },
      { letter: "B", text: "showing that the colleague has applied an inappropriate standard of evaluation" },
      { letter: "C", text: "providing additional research that contradicts the colleague's findings" },
      { letter: "D", text: "demonstrating that small percentage differences can represent substantial real-world impact" },
      { letter: "E", text: "arguing that placebo effects should not be used as a baseline for comparison" },
    ],
    correctAnswer: "D",
    explanation: "The scientist accepts the colleague's data but reframes its significance. By explaining that a 5% difference, when applied to thousands of patients, translates to hundreds of improved lives, the scientist shows that what seems like a small percentage difference has substantial real-world impact.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-044",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Architect: Green buildings, despite higher initial construction costs, are more economical over their lifespan. The energy savings from improved insulation, efficient systems, and sustainable materials more than offset the premium paid during construction.`,
    questionStem: "Which one of the following, if true, most strengthens the architect's argument?",
    answerChoices: [
      { letter: "A", text: "Green buildings often qualify for tax incentives that reduce their effective cost" },
      { letter: "B", text: "Energy prices are projected to increase significantly over the next several decades" },
      { letter: "C", text: "Many architects now specialize in sustainable building design" },
      { letter: "D", text: "Some green building materials require more maintenance than conventional materials" },
      { letter: "E", text: "Occupants of green buildings report higher satisfaction with their work environments" },
    ],
    correctAnswer: "B",
    explanation: "If energy prices increase, the value of energy savings grows over time, making green buildings even more economical compared to conventional buildings. Rising energy costs would amplify the savings from efficient systems, strengthening the case that green buildings are more economical over their lifespan.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-045",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `Literary scholar: Shakespeare must have had legal training. His plays contain numerous accurate legal references and use legal terminology correctly. Only someone with formal legal education could have such detailed knowledge of the law.`,
    questionStem: "Which one of the following, if true, most weakens the scholar's argument?",
    answerChoices: [
      { letter: "A", text: "Other playwrights of Shakespeare's era also included legal references in their works" },
      { letter: "B", text: "Shakespeare's father held civic positions that would have exposed the family to legal proceedings" },
      { letter: "C", text: "Legal knowledge in Elizabethan England could be acquired through attending public court sessions and reading widely available legal texts" },
      { letter: "D", text: "Some of Shakespeare's legal references contain minor inaccuracies" },
      { letter: "E", text: "Shakespeare's plays also contain accurate medical and nautical terminology" },
    ],
    correctAnswer: "C",
    explanation: "This directly challenges the assumption that formal legal education was the only way to acquire legal knowledge. If legal knowledge was accessible through public court sessions and available texts, Shakespeare could have learned law without formal training, eliminating the need to conclude he had legal education.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-046",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Columnist: The governor claims to support environmental protection, but she recently approved a pipeline project opposed by environmental groups. Politicians who truly support environmental protection would never approve projects that environmental groups oppose. Clearly, the governor does not actually support environmental protection.`,
    questionStem: "The reasoning in the columnist's argument is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "assumes that environmental groups are always correct in their assessments" },
      { letter: "B", text: "fails to consider that the governor might have approved the project for other valid reasons" },
      { letter: "C", text: "presumes that supporting environmental protection requires opposing all industrial development" },
      { letter: "D", text: "ignores the governor's overall environmental record" },
      { letter: "E", text: "relies on an unrealistic standard for what constitutes environmental support" },
    ],
    correctAnswer: "A",
    explanation: "The argument assumes that environmental groups' opposition is a reliable indicator that a project is environmentally harmful. However, environmental groups might oppose projects for various reasons, and a project they oppose might still be environmentally sound or represent a reasonable compromise. The argument treats their opposition as infallible.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-047",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Professor Blake: Students should be required to take a broad range of courses outside their major. Exposure to diverse disciplines creates well-rounded graduates who can think critically and adapt to various situations.

Professor Singh: Requiring students to take courses outside their major delays their career preparation. Students should be allowed to focus intensively on their chosen field so they can develop the expertise employers demand.`,
    questionStem: "Professor Blake and Professor Singh disagree about whether",
    answerChoices: [
      { letter: "A", text: "employers value specialized expertise in new graduates" },
      { letter: "B", text: "exposure to diverse disciplines improves critical thinking" },
      { letter: "C", text: "students should be required to take courses outside their major" },
      { letter: "D", text: "career preparation is an important function of higher education" },
      { letter: "E", text: "well-rounded graduates are better prepared for life after college" },
    ],
    correctAnswer: "C",
    explanation: "Blake explicitly argues students should be required to take broad courses, while Singh argues students should be allowed to focus on their field. Their direct disagreement is about whether such requirements should exist, not about the underlying values each emphasizes.",
    difficulty: "easy",
  },
  {
    id: "lr-bank67-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the defendant committed the crime, he would have had the victim's belongings. The defendant did not have the victim's belongings. Therefore, the defendant did not commit the crime.`,
    questionStem: "The pattern of reasoning in the argument is most similar to that in which one of the following?",
    answerChoices: [
      { letter: "A", text: "If it rained last night, the ground would be wet. The ground is wet. Therefore, it rained last night." },
      { letter: "B", text: "If the package was delivered, a signature would be on file. There is no signature on file. Therefore, the package was not delivered." },
      { letter: "C", text: "If the car won't start, the battery is dead. The car will start. Therefore, the battery is not dead." },
      { letter: "D", text: "If the plant receives sunlight, it will grow. The plant is not receiving sunlight. Therefore, it will not grow." },
      { letter: "E", text: "If the store is open, the lights are on. The lights are on. Therefore, the store is open." },
    ],
    correctAnswer: "B",
    explanation: "Both arguments use modus tollens: If P then Q. Not Q. Therefore, not P. The original: If committed crime, then had belongings. No belongings. Therefore, didn't commit. Answer B: If delivered, then signature. No signature. Therefore, not delivered. Both correctly deny the consequent to deny the antecedent.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-049",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The proposed law requiring photo identification to vote will prevent eligible citizens from exercising their right to vote. Studies show that millions of citizens lack government-issued photo identification. These citizens would effectively be disenfranchised if the law passes.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Some of those who lack photo ID would be unable or unwilling to obtain it before elections" },
      { letter: "B", text: "The primary purpose of the proposed law is to prevent eligible citizens from voting" },
      { letter: "C", text: "Government-issued photo identification is difficult to obtain" },
      { letter: "D", text: "All citizens without photo ID currently vote in elections" },
      { letter: "E", text: "Photo identification requirements have been struck down in other jurisdictions" },
    ],
    correctAnswer: "A",
    explanation: "The argument claims citizens without photo ID would be disenfranchised, but this only follows if they would not obtain ID before elections. If all affected citizens could and would get ID, no one would be prevented from voting. The argument assumes some would remain without ID.",
    difficulty: "medium",
  },
  {
    id: "lr-bank67-050",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Music critic: This composer's latest symphony is clearly derivative. Several passages strongly resemble works by Beethoven and Brahms. Any piece that borrows so heavily from earlier composers cannot be considered truly original or artistically valuable.`,
    questionStem: "The music critic's reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes that resemblance to earlier works necessarily indicates intentional borrowing" },
      { letter: "B", text: "fails to recognize that building on tradition is a legitimate artistic practice" },
      { letter: "C", text: "does not specify which passages resemble earlier works" },
      { letter: "D", text: "presumes that all listeners will recognize the similarities" },
      { letter: "E", text: "ignores the possibility that Beethoven and Brahms also borrowed from earlier composers" },
    ],
    correctAnswer: "B",
    explanation: "The critic assumes that borrowing from tradition precludes originality and artistic value. However, building on earlier works is a common and respected artistic practice. Many valuable and original works draw on tradition while adding new perspectives. The critic's standard would invalidate much of the classical music canon.",
    difficulty: "hard",
  },
];
