// Logical Reasoning Questions Bank - Set 35
import { Question } from "../lsat-types";

export const lrQuestionsSet35: Question[] = [
  {
    id: "lr-bank35-001",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `A recent study found that employees who take regular breaks during work hours are more productive than those who work continuously. Therefore, companies should mandate hourly breaks for all employees to maximize productivity.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to consider that some employees may already take breaks voluntarily" },
      { letter: "B", text: "assumes that what works when chosen voluntarily will work equally well when mandated" },
      { letter: "C", text: "does not define what constitutes a regular break" },
      { letter: "D", text: "ignores the costs of implementing a break policy" },
      { letter: "E", text: "relies on a single study rather than multiple sources" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that mandating breaks will have the same positive effect as voluntary breaks. However, the correlation in the study was with employees who chose to take breaks, not those who were forced to. Mandatory breaks might not produce the same productivity gains.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-002",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Professor Martinez argues that the university should not cut funding for the philosophy department because philosophy teaches critical thinking skills. But Professor Martinez is a philosophy professor, so of course she would say that. We should disregard her argument entirely.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to provide evidence that philosophy does not teach critical thinking" },
      { letter: "B", text: "attacks the person making the argument rather than addressing the argument itself" },
      { letter: "C", text: "assumes that all philosophy professors share the same opinions" },
      { letter: "D", text: "ignores other reasons the university might cut funding" },
      { letter: "E", text: "presumes that critical thinking skills are not valuable" },
    ],
    correctAnswer: "B",
    explanation: "This is an ad hominem fallacy. The argument dismisses Professor Martinez's claim solely based on her position as a philosophy professor, rather than evaluating the merits of her argument about critical thinking skills.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-003",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Every successful entrepreneur I have interviewed credits their success to hard work and determination. Therefore, anyone who works hard and shows determination will become a successful entrepreneur.`,
    questionStem: "The reasoning is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "relies on anecdotal evidence from a limited sample" },
      { letter: "B", text: "confuses a necessary condition with a sufficient condition" },
      { letter: "C", text: "fails to define what constitutes entrepreneurial success" },
      { letter: "D", text: "ignores the role of luck in business success" },
      { letter: "E", text: "assumes all entrepreneurs are equally hard-working" },
    ],
    correctAnswer: "B",
    explanation: "The argument confuses necessity with sufficiency. While hard work and determination may be necessary for entrepreneurial success (all successful entrepreneurs have these traits), this does not mean they are sufficient (that having these traits guarantees success).",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-004",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The city council should approve the new shopping mall development. After all, if we don't approve it, the developers will take their project to a neighboring city, we'll lose thousands of potential jobs, tax revenue will decline, and our city will fall into economic ruin.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "presents a chain of consequences without establishing the likelihood of each step" },
      { letter: "B", text: "fails to consider the environmental impact of the mall" },
      { letter: "C", text: "assumes the mall will definitely create thousands of jobs" },
      { letter: "D", text: "does not address concerns of local business owners" },
      { letter: "E", text: "relies on emotional appeals rather than facts" },
    ],
    correctAnswer: "A",
    explanation: "This is a slippery slope fallacy. The argument presents a chain of increasingly dire consequences without establishing that each step would actually lead to the next. The jump from not approving one mall to economic ruin is not justified.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-005",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Studies show that countries with higher chocolate consumption per capita have more Nobel Prize winners. Therefore, eating chocolate must improve cognitive function and increase the likelihood of winning a Nobel Prize.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "fails to specify which types of chocolate were consumed" },
      { letter: "B", text: "assumes a causal relationship based on a correlation" },
      { letter: "C", text: "ignores that Nobel Prizes are awarded in various fields" },
      { letter: "D", text: "does not account for population differences between countries" },
      { letter: "E", text: "relies on unverified studies" },
    ],
    correctAnswer: "B",
    explanation: "The argument commits the correlation-causation fallacy. Just because two variables are correlated (chocolate consumption and Nobel Prizes) does not mean one causes the other. Both could be related to a third factor, such as national wealth or education spending.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-006",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The defendant must be guilty of embezzlement. The prosecution presented financial records showing discrepancies, and the defendant refused to testify in their own defense. An innocent person would have nothing to hide and would eagerly take the stand.`,
    questionStem: "The reasoning in this argument is most vulnerable to criticism on the grounds that it",
    answerChoices: [
      { letter: "A", text: "fails to consider that financial discrepancies might have innocent explanations" },
      { letter: "B", text: "assumes that exercising a constitutional right is evidence of guilt" },
      { letter: "C", text: "does not establish that the defendant had access to the funds" },
      { letter: "D", text: "ignores the possibility that witnesses could testify on the defendant's behalf" },
      { letter: "E", text: "presumes the prosecution's financial records are accurate" },
    ],
    correctAnswer: "B",
    explanation: "The argument assumes that refusing to testify indicates guilt. However, the Fifth Amendment right against self-incrimination exists precisely because innocent people may have legitimate reasons not to testify, such as nervousness or the risk of being misunderstood.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-007",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `No one has ever proven that ghosts don't exist. Therefore, ghosts must exist. If scientists cannot demonstrate that something is impossible, we should accept it as real.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "assumes scientists are the only authorities on paranormal phenomena" },
      { letter: "B", text: "treats the absence of disproof as proof of existence" },
      { letter: "C", text: "fails to define what would constitute a ghost" },
      { letter: "D", text: "ignores testimonial evidence from people who claim to have seen ghosts" },
      { letter: "E", text: "presumes that all supernatural claims deserve equal consideration" },
    ],
    correctAnswer: "B",
    explanation: "This is an argument from ignorance (ad ignorantiam). The absence of proof that something doesn't exist is not the same as proof that it does exist. The burden of proof lies with those making the positive claim.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-008",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical company's new drug must be safe. The company conducted extensive internal testing and reported that the drug produced no significant side effects. These results were reviewed and approved by the company's own medical advisory board.`,
    questionStem: "The reasoning is most vulnerable to criticism because it",
    answerChoices: [
      { letter: "A", text: "fails to compare the drug's safety to existing treatments" },
      { letter: "B", text: "does not specify what side effects were considered significant" },
      { letter: "C", text: "relies on evidence from sources with a financial interest in the outcome" },
      { letter: "D", text: "assumes that internal testing is as rigorous as external testing" },
      { letter: "E", text: "ignores the long-term effects of the drug" },
    ],
    correctAnswer: "C",
    explanation: "The argument relies entirely on testing and review conducted by the pharmaceutical company itself. This creates a conflict of interest, as the company has a financial stake in the drug being approved, which could bias both the testing and the review.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-009",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `Either we implement strict environmental regulations that will destroy our economy, or we allow industries to pollute freely. Since we cannot afford economic devastation, we must allow industries to pollute without restriction.`,
    questionStem: "The reasoning in this argument is flawed because it",
    answerChoices: [
      { letter: "A", text: "exaggerates the economic impact of environmental regulations" },
      { letter: "B", text: "presents only two options when other alternatives may exist" },
      { letter: "C", text: "fails to consider the economic costs of environmental damage" },
      { letter: "D", text: "assumes that all environmental regulations are equally strict" },
      { letter: "E", text: "ignores the benefits of a clean environment to public health" },
    ],
    correctAnswer: "B",
    explanation: "This is a false dilemma (false dichotomy). The argument presents only two extreme options when moderate approaches exist, such as balanced regulations that protect the environment while minimizing economic disruption.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-010",
    type: "flaw",
    sectionType: "logical-reasoning",
    stimulus: `The Wilsons' marriage must be in trouble. I saw Mr. Wilson eating dinner alone at a restaurant last Tuesday, and Mrs. Wilson was at a different restaurant with her colleagues. Happily married couples always dine together.`,
    questionStem: "The reasoning is flawed because it",
    answerChoices: [
      { letter: "A", text: "bases a conclusion about a general pattern on a single observation" },
      { letter: "B", text: "assumes that dining separately is unusual for married couples" },
      { letter: "C", text: "fails to consider that the Wilsons might have different work schedules" },
      { letter: "D", text: "relies on an overgeneralization about the behavior of married couples" },
      { letter: "E", text: "ignores that the observer might have been mistaken about the identities" },
    ],
    correctAnswer: "D",
    explanation: "The argument relies on the false premise that happily married couples always dine together. This is an overgeneralization; many happy couples dine separately for various legitimate reasons including work obligations, different preferences, or social engagements.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-011",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Researchers studying a remote island population discovered that residents who regularly consume seaweed have significantly lower rates of thyroid disorders than mainland populations. The researchers hypothesize that compounds in the seaweed provide protection against thyroid problems.`,
    questionStem: "Which one of the following, if true, most strengthens the researchers' hypothesis?",
    answerChoices: [
      { letter: "A", text: "The island residents have lived on the island for many generations" },
      { letter: "B", text: "Laboratory analysis shows the seaweed contains high levels of iodine and selenium, nutrients essential for thyroid function" },
      { letter: "C", text: "The island has a mild climate with little temperature variation" },
      { letter: "D", text: "Island residents also have lower rates of heart disease" },
      { letter: "E", text: "Seaweed is harvested locally and forms a traditional part of the island diet" },
    ],
    correctAnswer: "B",
    explanation: "If the seaweed contains nutrients specifically needed for thyroid function, this provides a mechanism explaining why seaweed consumption would protect against thyroid disorders, strengthening the causal hypothesis.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-012",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A city's traffic department claims that installing roundabouts instead of traffic lights at intersections will reduce serious accidents. They point to a pilot program where three intersections with high accident rates were converted to roundabouts, and serious accidents at those locations dropped by 60 percent.`,
    questionStem: "Which one of the following, if true, most strengthens the traffic department's claim?",
    answerChoices: [
      { letter: "A", text: "The three intersections were selected because they had the highest accident rates in the city" },
      { letter: "B", text: "Similar roundabout installations in other cities have produced comparable reductions in serious accidents" },
      { letter: "C", text: "Minor fender-benders at the converted intersections remained at previous levels" },
      { letter: "D", text: "The roundabouts were installed with new lighting and signage" },
      { letter: "E", text: "Traffic volume at the three intersections remained constant after the conversion" },
    ],
    correctAnswer: "B",
    explanation: "Evidence that similar results occurred in other cities supports the claim that roundabouts themselves cause the reduction, rather than the reduction being due to unique factors at these three specific intersections.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-013",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Historians argue that the decline of the Roman Empire was primarily caused by lead poisoning from their water pipes and cooking vessels. They note that lead can cause neurological damage, reduced birth rates, and erratic behavior—symptoms that match historical accounts of Roman aristocracy in the later Empire.`,
    questionStem: "Which one of the following, if true, most strengthens the historians' argument?",
    answerChoices: [
      { letter: "A", text: "Roman writers complained about the poor quality of water in Rome" },
      { letter: "B", text: "Analysis of bones from Roman-era graves shows lead levels far exceeding those considered safe today" },
      { letter: "C", text: "The Roman Empire experienced several military defeats in its final centuries" },
      { letter: "D", text: "Other ancient civilizations also used lead in their infrastructure" },
      { letter: "E", text: "Modern lead poisoning cases show symptoms different from those described in Roman texts" },
    ],
    correctAnswer: "B",
    explanation: "Physical evidence of dangerous lead levels in Roman remains directly supports the claim that Romans were exposed to toxic amounts of lead, strengthening the hypothesis that lead poisoning contributed to the Empire's decline.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-014",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A wildlife biologist argues that reintroducing wolves to a national park will restore ecological balance. She claims that wolves will control the deer population, which has grown so large that deer are overgrazing vegetation and causing soil erosion along riverbanks.`,
    questionStem: "Which one of the following, if true, most strengthens the biologist's argument?",
    answerChoices: [
      { letter: "A", text: "Wolves are native to the region and were eliminated by hunting a century ago" },
      { letter: "B", text: "Parks that have reintroduced wolves have seen deer behavior change, with deer avoiding areas near rivers where they are vulnerable to wolf predation" },
      { letter: "C", text: "Some local ranchers oppose wolf reintroduction due to concerns about livestock predation" },
      { letter: "D", text: "The park currently has no large predators" },
      { letter: "E", text: "Deer populations in the park have doubled in the past twenty years" },
    ],
    correctAnswer: "B",
    explanation: "This shows that wolves not only reduce deer numbers but also change deer behavior, keeping them away from rivers—directly addressing the erosion problem. This demonstrates the mechanism by which wolves would restore balance.",
    difficulty: "hard",
  },
  {
    id: "lr-bank35-015",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A tech company argues that requiring all employees to work in the office five days a week will improve collaboration and innovation. They cite a survey showing that employees report having more spontaneous creative discussions when they are physically present in the office.`,
    questionStem: "Which one of the following, if true, most strengthens the company's argument?",
    answerChoices: [
      { letter: "A", text: "The company's main competitors have also returned to full-time office work" },
      { letter: "B", text: "Employee satisfaction surveys show that most employees prefer some remote work" },
      { letter: "C", text: "The company's most successful product in the past decade was developed during a period when all team members worked in the office daily" },
      { letter: "D", text: "Teams that work together in person file more joint patent applications than teams that work remotely" },
      { letter: "E", text: "The company has invested heavily in redesigning its office space" },
    ],
    correctAnswer: "D",
    explanation: "Patent applications are a measurable indicator of innovation. If in-person teams produce more patents, this provides concrete evidence that physical presence enhances innovation, directly supporting the company's argument.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-016",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `Economists predict that increasing the minimum wage will not lead to significant job losses in the retail sector. They argue that while labor costs will rise, retailers will offset this through modest price increases and reduced employee turnover, which is expensive to manage.`,
    questionStem: "Which one of the following, if true, most strengthens the economists' prediction?",
    answerChoices: [
      { letter: "A", text: "Some retail workers currently earn above the proposed minimum wage" },
      { letter: "B", text: "Retail profit margins have increased over the past five years" },
      { letter: "C", text: "Studies of previous minimum wage increases in similar economic conditions showed stable retail employment levels" },
      { letter: "D", text: "Consumer spending typically increases when lower-wage workers receive raises" },
      { letter: "E", text: "The retail sector has experienced job losses due to online competition" },
    ],
    correctAnswer: "C",
    explanation: "Historical evidence from similar situations provides the strongest support for a prediction. If previous minimum wage increases did not cause job losses, this strengthens the prediction that the current increase will not either.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-017",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A museum curator argues that the painting recently donated to the museum is an authentic work by the Dutch master Vermeer. She bases this on the painting's subject matter, composition, and use of light, all of which are consistent with Vermeer's known works.`,
    questionStem: "Which one of the following, if true, most strengthens the curator's argument?",
    answerChoices: [
      { letter: "A", text: "The painting was purchased from a dealer who specializes in Dutch Golden Age art" },
      { letter: "B", text: "Chemical analysis of the paint pigments shows materials consistent with those available in 17th-century Delft, where Vermeer worked" },
      { letter: "C", text: "Several art historians have expressed interest in studying the painting" },
      { letter: "D", text: "The painting's previous owner believed it to be a genuine Vermeer" },
      { letter: "E", text: "Vermeer is known to have painted more works than are currently attributed to him" },
    ],
    correctAnswer: "B",
    explanation: "Scientific evidence showing the paint materials match those from Vermeer's time and location provides objective support for authenticity that goes beyond subjective stylistic analysis.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-018",
    type: "strengthen",
    sectionType: "logical-reasoning",
    stimulus: `A public health official argues that banning flavored e-cigarettes will reduce teenage vaping. She notes that surveys show flavored products are overwhelmingly preferred by teenage vapers, with fruit and candy flavors being the most popular among this age group.`,
    questionStem: "Which one of the following, if true, most strengthens the official's argument?",
    answerChoices: [
      { letter: "A", text: "Many adults who use e-cigarettes to quit smoking also prefer flavored products" },
      { letter: "B", text: "Teenage smoking rates have declined since e-cigarettes became popular" },
      { letter: "C", text: "In regions that have banned flavored e-cigarettes, black market sales have remained minimal and teenage vaping rates have dropped significantly" },
      { letter: "D", text: "E-cigarette companies spend millions on advertising their flavored products" },
      { letter: "E", text: "Tobacco-flavored e-cigarettes are less appealing to teenagers than flavored options" },
    ],
    correctAnswer: "C",
    explanation: "Evidence from places that have already implemented similar bans showing reduced teenage vaping and no significant black market provides direct support that the proposed policy will achieve its intended effect.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-019",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A city councilmember argues against building a new public library, claiming it would be a waste of taxpayer money. She points out that library circulation numbers have declined 30 percent over the past decade, proving that fewer people are interested in using libraries.`,
    questionStem: "Which one of the following, if true, most weakens the councilmember's argument?",
    answerChoices: [
      { letter: "A", text: "The proposed library would include a community meeting space" },
      { letter: "B", text: "Digital resource usage, including e-book borrowing and online database access, has increased 200 percent over the same period" },
      { letter: "C", text: "The current library building is over fifty years old" },
      { letter: "D", text: "Other cities of similar size have built new libraries recently" },
      { letter: "E", text: "Library staff have received training in new technologies" },
    ],
    correctAnswer: "B",
    explanation: "If digital usage has dramatically increased while physical circulation decreased, people are still using library services—just in different ways. This undermines the claim that declining circulation proves reduced interest in libraries.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-020",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The owner of a coffee shop chain claims that offering free Wi-Fi increases profitability. He notes that since installing free Wi-Fi, his stores have seen a 15 percent increase in revenue compared to the previous year.`,
    questionStem: "Which one of the following, if true, most weakens the owner's claim?",
    answerChoices: [
      { letter: "A", text: "Some customers stay for hours using the Wi-Fi but only purchase one small coffee" },
      { letter: "B", text: "Coffee prices at the chain have not changed significantly" },
      { letter: "C", text: "Coffee shops nationwide experienced an average revenue increase of 18 percent during the same period due to changing consumer habits" },
      { letter: "D", text: "Installing and maintaining the Wi-Fi network costs the chain $50,000 annually" },
      { letter: "E", text: "Some customers have complained about the Wi-Fi connection speed" },
    ],
    correctAnswer: "C",
    explanation: "If the industry-wide increase was 18 percent while this chain only saw 15 percent, the chain actually underperformed its competitors. This suggests the Wi-Fi may not have increased profitability and might have even hurt it.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-021",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A fitness influencer claims that her new exercise program is responsible for her clients' weight loss. She presents testimonials from twenty clients who lost an average of fifteen pounds over three months while following her program.`,
    questionStem: "Which one of the following, if true, most weakens the influencer's claim?",
    answerChoices: [
      { letter: "A", text: "The exercise program requires expensive equipment" },
      { letter: "B", text: "The program also includes a strict calorie-restricted diet plan" },
      { letter: "C", text: "Some clients reported finding the exercises difficult" },
      { letter: "D", text: "The influencer is not a certified personal trainer" },
      { letter: "E", text: "Other exercise programs make similar claims about weight loss" },
    ],
    correctAnswer: "B",
    explanation: "If the program includes a strict diet, the weight loss could be due to the diet rather than the exercises. This provides an alternative explanation for the results, weakening the claim that the exercise program is responsible.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-022",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A school district superintendent argues that the district's new math curriculum is effective because standardized test scores have improved by 12 percent since its adoption two years ago. She concludes that other districts should adopt the same curriculum.`,
    questionStem: "Which one of the following, if true, most weakens the superintendent's argument?",
    answerChoices: [
      { letter: "A", text: "The new curriculum costs more than the previous one" },
      { letter: "B", text: "The district also hired additional math tutors and extended math instruction time by 30 minutes daily when implementing the new curriculum" },
      { letter: "C", text: "Some teachers initially resisted the new curriculum" },
      { letter: "D", text: "The state's standardized math test was unchanged during this period" },
      { letter: "E", text: "Students in the district perform better in math than in reading" },
    ],
    correctAnswer: "B",
    explanation: "If additional tutors and more instruction time were added simultaneously, the improvement could be due to these factors rather than the curriculum itself. This confounding variable undermines the conclusion that the curriculum is effective.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-023",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `An automotive company claims that its new electric vehicle is environmentally superior to gasoline-powered cars. The company emphasizes that the vehicle produces zero direct emissions while driving and will significantly reduce the owner's carbon footprint.`,
    questionStem: "Which one of the following, if true, most weakens the company's claim?",
    answerChoices: [
      { letter: "A", text: "The electric vehicle has a higher purchase price than comparable gasoline vehicles" },
      { letter: "B", text: "Battery production for the vehicle generates substantial carbon emissions, and the local electricity grid relies primarily on coal-fired power plants" },
      { letter: "C", text: "The vehicle can travel 300 miles on a single charge" },
      { letter: "D", text: "Some consumers prefer the driving experience of gasoline vehicles" },
      { letter: "E", text: "Charging infrastructure is not yet widely available in rural areas" },
    ],
    correctAnswer: "B",
    explanation: "If battery production creates significant emissions and the electricity comes from coal, the total carbon footprint may not be lower than gasoline vehicles. This challenges the claim of environmental superiority by revealing hidden emissions.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-024",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A pharmaceutical company argues that its new antidepressant is more effective than a placebo. In clinical trials, 60 percent of patients taking the drug reported significant improvement in symptoms, compared to 45 percent of those taking the placebo.`,
    questionStem: "Which one of the following, if true, most weakens the company's argument?",
    answerChoices: [
      { letter: "A", text: "The drug has some minor side effects such as dry mouth" },
      { letter: "B", text: "The difference in improvement rates is not statistically significant given the sample size of the study" },
      { letter: "C", text: "Other antidepressants on the market have similar efficacy rates" },
      { letter: "D", text: "The trial lasted only eight weeks" },
      { letter: "E", text: "Some patients in the placebo group were previously treated with other antidepressants" },
    ],
    correctAnswer: "B",
    explanation: "If the difference is not statistically significant, it could be due to chance rather than actual drug effectiveness. This directly challenges the conclusion that the drug outperforms the placebo.",
    difficulty: "hard",
  },
  {
    id: "lr-bank35-025",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `A business consultant argues that open-plan offices improve employee collaboration. She cites a study showing that companies with open-plan offices report 25 percent more cross-departmental projects than companies with traditional private offices.`,
    questionStem: "Which one of the following, if true, most weakens the consultant's argument?",
    answerChoices: [
      { letter: "A", text: "Many employees in open-plan offices report being distracted by noise" },
      { letter: "B", text: "Companies that adopt open-plan offices also tend to implement other collaboration-focused policies such as team-based incentives and project management software" },
      { letter: "C", text: "Open-plan offices are less expensive to build than traditional offices" },
      { letter: "D", text: "Some successful companies have maintained traditional office layouts" },
      { letter: "E", text: "The study was conducted by an architecture firm that designs open-plan offices" },
    ],
    correctAnswer: "B",
    explanation: "If companies adopting open-plan offices also implement other collaboration initiatives, the increased cross-departmental projects could be due to these other policies rather than the office layout itself.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-026",
    type: "weaken",
    sectionType: "logical-reasoning",
    stimulus: `The mayor claims that her administration's policies have reduced crime in the city. She points to statistics showing that reported crimes have decreased by 20 percent over her three-year term.`,
    questionStem: "Which one of the following, if true, most weakens the mayor's claim?",
    answerChoices: [
      { letter: "A", text: "The police department received a budget increase during the mayor's term" },
      { letter: "B", text: "Neighboring cities have not experienced similar crime reductions" },
      { letter: "C", text: "A survey shows that fewer residents are reporting crimes to police because they believe nothing will be done" },
      { letter: "D", text: "The mayor ran on a platform of reducing crime" },
      { letter: "E", text: "Violent crimes decreased more than property crimes" },
    ],
    correctAnswer: "C",
    explanation: "If fewer crimes are being reported because residents have lost faith in the system, the decrease in reported crimes doesn't reflect an actual decrease in crime. This undermines the mayor's claim by showing the statistics are misleading.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-027",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The committee should select Maria for the leadership position. She has fifteen years of experience in the industry, an MBA from a top business school, and a proven track record of increasing profits at her previous company.`,
    questionStem: "The argument depends on which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "No other candidate has as much experience as Maria" },
      { letter: "B", text: "Industry experience is more important than leadership skills" },
      { letter: "C", text: "The qualifications cited are relevant to success in the leadership position" },
      { letter: "D", text: "Maria wants the leadership position" },
      { letter: "E", text: "The committee has not already made a decision" },
    ],
    correctAnswer: "C",
    explanation: "The argument assumes that Maria's experience, education, and profit record are actually relevant to performing well in this leadership role. If these qualifications don't translate to success in the position, the argument fails.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-028",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Since the ancient Egyptians built the pyramids without modern technology, it is clear that they possessed advanced knowledge that has since been lost. No civilization using only simple tools could have constructed such precise and massive structures.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Modern technology is more advanced than ancient Egyptian technology" },
      { letter: "B", text: "The pyramids are the most impressive ancient structures" },
      { letter: "C", text: "Simple tools and sufficient time, labor, and ingenuity could not have built the pyramids" },
      { letter: "D", text: "Other ancient civilizations also possessed advanced knowledge" },
      { letter: "E", text: "The Egyptians recorded how they built the pyramids" },
    ],
    correctAnswer: "C",
    explanation: "The argument requires the assumption that simple tools alone could not have produced the pyramids. If simple tools, combined with abundant labor and clever techniques, could explain the construction, then no lost advanced knowledge need be posited.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-029",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Vegetarian diets are healthier than diets that include meat. Studies consistently show that vegetarians have lower rates of heart disease than non-vegetarians.`,
    questionStem: "Which one of the following is an assumption required by the argument?",
    answerChoices: [
      { letter: "A", text: "Heart disease is the leading cause of death" },
      { letter: "B", text: "Lower heart disease rates are a reliable indicator of a healthier diet overall" },
      { letter: "C", text: "All vegetarians follow healthy eating practices" },
      { letter: "D", text: "Meat consumption is the only factor affecting heart disease rates" },
      { letter: "E", text: "Non-vegetarians could reduce their heart disease risk by eating less meat" },
    ],
    correctAnswer: "B",
    explanation: "The argument moves from evidence about heart disease to a conclusion about overall health. This requires assuming that heart disease rates are a good indicator of overall dietary healthfulness.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-030",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The city should not build the proposed waterfront park. The project would cost $50 million, and taxpayers are already burdened with high property taxes. Spending this money on a park is fiscally irresponsible.`,
    questionStem: "The argument depends on the assumption that",
    answerChoices: [
      { letter: "A", text: "the city has other pressing financial obligations" },
      { letter: "B", text: "property taxes are higher in this city than in comparable cities" },
      { letter: "C", text: "the economic and social benefits of the park would not justify its cost" },
      { letter: "D", text: "taxpayers oppose the construction of the park" },
      { letter: "E", text: "the park project could not be funded through sources other than property taxes" },
    ],
    correctAnswer: "C",
    explanation: "The argument concludes spending on the park is irresponsible. This requires assuming that the park's benefits don't justify the cost. If the park's benefits exceeded $50 million in value, the expenditure could be fiscally responsible.",
    difficulty: "hard",
  },
  {
    id: "lr-bank35-031",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `Employee morale at our company must have improved. We implemented a new flexible scheduling policy six months ago, and employee turnover has decreased by 25 percent since then.`,
    questionStem: "The argument assumes which one of the following?",
    answerChoices: [
      { letter: "A", text: "Flexible scheduling is the most important factor in employee satisfaction" },
      { letter: "B", text: "The company had high employee turnover before implementing the policy" },
      { letter: "C", text: "Decreased turnover indicates improved morale rather than other factors such as a weak job market" },
      { letter: "D", text: "All employees have taken advantage of the flexible scheduling options" },
      { letter: "E", text: "Other companies have not implemented similar policies" },
    ],
    correctAnswer: "C",
    explanation: "The argument uses decreased turnover as evidence of improved morale. This requires assuming that lower turnover reflects better morale rather than external factors like fewer job opportunities elsewhere.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-032",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The defendant could not have committed the robbery. Security camera footage shows that he was at a gas station fifteen miles from the crime scene at 3:00 PM, and the robbery occurred at 3:15 PM.`,
    questionStem: "The argument requires which one of the following assumptions?",
    answerChoices: [
      { letter: "A", text: "The security camera footage has not been altered" },
      { letter: "B", text: "The defendant does not have an accomplice" },
      { letter: "C", text: "The robbery could not have occurred at a different time" },
      { letter: "D", text: "The defendant could not have traveled fifteen miles in fifteen minutes" },
      { letter: "E", text: "The gas station and crime scene are connected by only one route" },
    ],
    correctAnswer: "D",
    explanation: "The argument's logic depends on it being impossible for the defendant to cover the fifteen-mile distance in fifteen minutes. If he could have made that trip quickly enough, the alibi fails.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-033",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The critics are wrong to call the new art museum a failure. The museum has attracted over 500,000 visitors in its first year of operation, far exceeding initial projections.`,
    questionStem: "The argument assumes that",
    answerChoices: [
      { letter: "A", text: "the critics based their judgment solely on projected attendance figures" },
      { letter: "B", text: "high attendance is sufficient evidence that the museum is not a failure" },
      { letter: "C", text: "the museum will continue to attract large numbers of visitors" },
      { letter: "D", text: "other new museums have not attracted as many visitors" },
      { letter: "E", text: "visitors have expressed satisfaction with the museum" },
    ],
    correctAnswer: "B",
    explanation: "The argument uses attendance figures to refute the failure claim. This assumes that high attendance is enough to demonstrate success, ignoring other possible criteria for failure such as financial losses or artistic merit.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-034",
    type: "necessary-assumption",
    sectionType: "logical-reasoning",
    stimulus: `The pharmaceutical industry spends more on marketing than on research. Therefore, pharmaceutical companies are more interested in selling existing drugs than in developing new treatments that could help patients.`,
    questionStem: "Which one of the following is an assumption on which the argument depends?",
    answerChoices: [
      { letter: "A", text: "Marketing expenditures do not contribute to patient welfare" },
      { letter: "B", text: "The ratio of marketing to research spending indicates a company's priorities" },
      { letter: "C", text: "Pharmaceutical companies should spend equal amounts on marketing and research" },
      { letter: "D", text: "New drug development is always more beneficial to patients than marketing existing drugs" },
      { letter: "E", text: "Pharmaceutical companies are the only entities that develop new drugs" },
    ],
    correctAnswer: "B",
    explanation: "The argument infers priorities from spending patterns. This requires assuming that how money is allocated reflects what the companies care about most.",
    difficulty: "hard",
  },
  {
    id: "lr-bank35-035",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Some people argue that zoos are unethical because they confine animals. However, modern zoos play a crucial role in species conservation, educating the public about wildlife, and conducting important research. The animals in accredited zoos receive excellent veterinary care and live in carefully designed habitats. Therefore, the benefits of zoos outweigh the concerns about confinement.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Modern zoos contribute to conservation, education, and research" },
      { letter: "B", text: "Animals in accredited zoos receive high-quality care" },
      { letter: "C", text: "Concerns about animal confinement in zoos are misguided" },
      { letter: "D", text: "The benefits of zoos justify their existence despite concerns about confinement" },
      { letter: "E", text: "Zoos should continue to improve their animal habitats" },
    ],
    correctAnswer: "D",
    explanation: "The conclusion, signaled by 'therefore,' is that the benefits outweigh the concerns. The other points about conservation, education, research, and animal care are premises supporting this conclusion.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-036",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Historical evidence suggests that societies with greater income equality tend to have lower crime rates. Currently, income inequality in our country is at historic highs. Unless we take steps to reduce this inequality, we can expect crime rates to continue rising. The most effective way to reduce income inequality is through progressive taxation and investment in education and job training programs.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Income inequality in the country is currently at historic highs" },
      { letter: "B", text: "Crime rates will continue to rise if income inequality is not reduced" },
      { letter: "C", text: "Progressive taxation is the best way to reduce inequality" },
      { letter: "D", text: "Greater income equality leads to lower crime rates" },
      { letter: "E", text: "Investment in education reduces crime" },
    ],
    correctAnswer: "B",
    explanation: "The main conclusion is the predictive claim that crime will continue rising unless inequality is addressed. The historical correlation is evidence, the current inequality is context, and the policy suggestions are recommendations that follow from the conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-037",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Many people believe that artificial intelligence will eventually surpass human intelligence in all domains. But consider: human intelligence includes emotional understanding, creativity, moral reasoning, and consciousness—capacities that emerge from our biological nature and social experiences. Machines, however sophisticated their algorithms, process information without any genuine understanding or subjective experience. The notion that AI will fully replicate human intelligence is fundamentally mistaken.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Human intelligence encompasses more than just information processing" },
      { letter: "B", text: "Machines lack genuine understanding and subjective experience" },
      { letter: "C", text: "AI cannot fully replicate human intelligence" },
      { letter: "D", text: "Emotional understanding and creativity emerge from biological processes" },
      { letter: "E", text: "Many people have false beliefs about artificial intelligence" },
    ],
    correctAnswer: "C",
    explanation: "The final sentence states the main conclusion: the belief that AI will fully replicate human intelligence is mistaken. The points about human capacities and machine limitations serve as premises supporting this conclusion.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-038",
    type: "main-conclusion",
    sectionType: "logical-reasoning",
    stimulus: `Student evaluations of teaching are widely used in universities to assess instructor performance. However, studies show these evaluations are influenced by factors unrelated to teaching quality, such as the instructor's appearance, the difficulty of the course, and expected grades. Furthermore, students may lack the expertise to evaluate pedagogical effectiveness. Given these serious flaws, universities should not rely primarily on student evaluations when making decisions about faculty promotion and tenure.`,
    questionStem: "Which one of the following most accurately expresses the main conclusion of the argument?",
    answerChoices: [
      { letter: "A", text: "Student evaluations are influenced by factors unrelated to teaching quality" },
      { letter: "B", text: "Students lack expertise in evaluating teaching effectiveness" },
      { letter: "C", text: "Universities should minimize the role of student evaluations in tenure decisions" },
      { letter: "D", text: "Student evaluations have serious methodological flaws" },
      { letter: "E", text: "Course difficulty affects student evaluation scores" },
    ],
    correctAnswer: "C",
    explanation: "The conclusion, introduced by 'Given these serious flaws,' is the recommendation about how universities should use student evaluations. The flaws described are premises leading to this policy recommendation.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-039",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Critic: The new restaurant has received rave reviews for its innovative cuisine. But I am skeptical. The restaurant is owned by a celebrity chef whose previous restaurants were style over substance—beautiful presentations but mediocre flavors. Until proven otherwise, I will assume this restaurant follows the same pattern.`,
    questionStem: "The critic's reasoning most closely conforms to which one of the following?",
    answerChoices: [
      { letter: "A", text: "Rejecting a claim because the source has shown bias in the past" },
      { letter: "B", text: "Predicting future performance based on established patterns of past behavior" },
      { letter: "C", text: "Dismissing popular opinion as likely to be uninformed" },
      { letter: "D", text: "Concluding that initial impressions are usually misleading" },
      { letter: "E", text: "Assuming that style and substance are mutually exclusive" },
    ],
    correctAnswer: "B",
    explanation: "The critic bases the prediction about the new restaurant on the chef's track record with previous restaurants. This is reasoning from past patterns to predict future behavior.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-040",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Scientist: My colleague argues that we should abandon the current theory because it cannot explain certain anomalous observations. But she fails to offer any alternative theory that better explains both the anomalies and the vast body of evidence that the current theory explains well. Until a superior theory is proposed, we should retain the current one.`,
    questionStem: "The scientist responds to the colleague's argument by",
    answerChoices: [
      { letter: "A", text: "questioning the colleague's expertise in the relevant field" },
      { letter: "B", text: "demonstrating that the anomalous observations are not actually anomalous" },
      { letter: "C", text: "arguing that a theory should not be abandoned unless a better alternative exists" },
      { letter: "D", text: "showing that the current theory can in fact explain the anomalies" },
      { letter: "E", text: "suggesting that all theories have unexplained observations" },
    ],
    correctAnswer: "C",
    explanation: "The scientist's method is to argue that rejecting a theory requires having a better replacement. This is an argument about the standards for theory change, not an attack on the colleague or a defense of the theory's explanatory power.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-041",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Attorney: The prosecution claims my client had motive, opportunity, and means to commit the crime. But consider: millions of people had similar motives, many had opportunity, and the means were commonly available. If these factors were sufficient to establish guilt, we would have to conclude that millions of people committed this crime. Since that is absurd, my client's guilt has not been established.`,
    questionStem: "The attorney's argument proceeds by",
    answerChoices: [
      { letter: "A", text: "showing that the prosecution's evidence is fabricated" },
      { letter: "B", text: "demonstrating that the logical extension of the prosecution's reasoning leads to an absurd conclusion" },
      { letter: "C", text: "providing an alternative explanation for the evidence" },
      { letter: "D", text: "questioning the credibility of prosecution witnesses" },
      { letter: "E", text: "arguing that the burden of proof has not been met" },
    ],
    correctAnswer: "B",
    explanation: "The attorney uses reductio ad absurdum: if the prosecution's reasoning were valid, it would lead to the absurd conclusion that millions committed the crime. Since this is impossible, the reasoning must be flawed.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-042",
    type: "method-of-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `Philosopher: Some argue that free will is an illusion because all our actions are determined by prior causes. But this argument is self-defeating. If the argument is true, then the arguer's belief in it is itself determined by prior causes and not by rational evaluation of evidence. But if beliefs are not based on rational evaluation, we have no reason to accept any argument—including the argument against free will.`,
    questionStem: "The philosopher's reasoning proceeds by",
    answerChoices: [
      { letter: "A", text: "providing scientific evidence for the existence of free will" },
      { letter: "B", text: "showing that the argument against free will undermines the basis for accepting any argument" },
      { letter: "C", text: "demonstrating that determinism is compatible with free will" },
      { letter: "D", text: "appealing to the intuitive sense that we have free will" },
      { letter: "E", text: "arguing that prior causes do not fully determine actions" },
    ],
    correctAnswer: "B",
    explanation: "The philosopher argues that the determinist argument is self-undermining: if true, it removes the basis for rationally accepting any argument, including itself. This is a self-refutation argument.",
    difficulty: "hard",
  },
  {
    id: "lr-bank35-043",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Dr. Hayes: Clinical trials should prioritize patient safety above all else. Any treatment with significant risks should be carefully evaluated even if it shows promising results. The primary obligation of medical research is to avoid harming participants.

Dr. Santos: While safety is important, we must also consider the patients desperately awaiting new treatments. Overly cautious trial designs delay potentially life-saving therapies. The ethical calculus must include the harm of withholding beneficial treatments from suffering patients.`,
    questionStem: "The main point at issue between Dr. Hayes and Dr. Santos is",
    answerChoices: [
      { letter: "A", text: "whether clinical trials currently have adequate safety protocols" },
      { letter: "B", text: "how to balance trial participant safety against the urgency of developing new treatments" },
      { letter: "C", text: "whether pharmaceutical companies should fund clinical trials" },
      { letter: "D", text: "which diseases should receive priority for clinical research" },
      { letter: "E", text: "whether patients should be informed of all risks before participating in trials" },
    ],
    correctAnswer: "B",
    explanation: "Dr. Hayes emphasizes safety as the paramount concern, while Dr. Santos argues for weighing safety against the need for timely new treatments. Their disagreement centers on how to balance these competing considerations.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-044",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Traditionalist: Literature curricula should focus on the established canon of classic works that have stood the test of time. These works have proven their lasting value and provide a shared cultural foundation that educated people should have in common.

Reformer: This approach perpetuates the marginalization of voices from underrepresented groups. Literature education should include diverse contemporary works that reflect the experiences of all students and challenge the traditional power structures embedded in canon formation.`,
    questionStem: "The traditionalist and reformer disagree about",
    answerChoices: [
      { letter: "A", text: "whether students benefit from studying literature" },
      { letter: "B", text: "the criteria that should guide the selection of works for literature curricula" },
      { letter: "C", text: "whether classic works have any literary merit" },
      { letter: "D", text: "the current state of literature education in schools" },
      { letter: "E", text: "whether contemporary works can become classics" },
    ],
    correctAnswer: "B",
    explanation: "The disagreement is about what criteria should determine which works are taught: enduring value and cultural tradition (traditionalist) versus representation of diverse experiences and challenging power structures (reformer).",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-045",
    type: "point-at-issue",
    sectionType: "logical-reasoning",
    stimulus: `Urban Planner: Cities should prioritize public transportation over private vehicles. Expanding roads only induces more traffic, while robust transit systems reduce congestion, pollution, and inequality in access to mobility.

Developer: Public transit cannot meet the diverse mobility needs of modern metropolitan areas. People need the flexibility and convenience of personal vehicles for commuting, shopping, and family responsibilities. Road infrastructure remains essential for economic growth.`,
    questionStem: "The urban planner and developer most clearly disagree about whether",
    answerChoices: [
      { letter: "A", text: "traffic congestion is a problem in cities" },
      { letter: "B", text: "public transportation should receive priority over road expansion in urban planning" },
      { letter: "C", text: "personal vehicles cause pollution" },
      { letter: "D", text: "some people depend on cars for their daily activities" },
      { letter: "E", text: "economic growth is an important consideration in transportation planning" },
    ],
    correctAnswer: "B",
    explanation: "The urban planner explicitly argues for prioritizing transit over roads, while the developer argues that road infrastructure remains essential and transit cannot meet all needs. This is their central disagreement.",
    difficulty: "easy",
  },
  {
    id: "lr-bank35-046",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `All members of the orchestra have practiced for at least ten years. Sarah has practiced for twelve years. Therefore, Sarah is a member of the orchestra.`,
    questionStem: "The flawed reasoning in which one of the following is most similar to the flawed reasoning in the argument above?",
    answerChoices: [
      { letter: "A", text: "All licensed doctors have completed medical school. Jones completed medical school. Therefore, Jones is a licensed doctor." },
      { letter: "B", text: "All roses are flowers. This plant is a rose. Therefore, this plant is a flower." },
      { letter: "C", text: "No reptiles are mammals. This animal is not a reptile. Therefore, this animal is a mammal." },
      { letter: "D", text: "Some athletes are students. Mark is a student. Therefore, Mark is an athlete." },
      { letter: "E", text: "All squares are rectangles. All rectangles have four sides. Therefore, all squares have four sides." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments commit the fallacy of affirming the consequent. The original: if orchestra member, then 10+ years practice; Sarah has 12 years; therefore Sarah is a member. Answer A: if licensed doctor, then completed medical school; Jones completed medical school; therefore Jones is a licensed doctor.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-047",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `The museum's funding was cut, so it had to reduce its hours. Because of the reduced hours, fewer visitors came. With fewer visitors, the museum had less revenue from admissions and gift shop sales, which led to further budget shortfalls and additional cuts to hours.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "The restaurant raised its prices, which drove away customers. Fewer customers meant the restaurant couldn't afford quality ingredients, which drove away more customers, leading to eventual closure." },
      { letter: "B", text: "The student studied hard and earned good grades. Good grades led to a scholarship, which allowed the student to focus on academics instead of working." },
      { letter: "C", text: "The storm damaged the roof, so the homeowner filed an insurance claim. The insurance company paid for repairs, and the roof was fixed." },
      { letter: "D", text: "The company hired new employees to increase production. Production increased, and profits rose as a result." },
      { letter: "E", text: "The city built a new park, which attracted residents. More residents led to more tax revenue, which funded additional parks." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments describe a negative feedback loop or vicious cycle: an initial problem leads to consequences that worsen the original problem. The museum's cuts lead to fewer visitors, less revenue, and more cuts. The restaurant's price increase leads to fewer customers, lower quality, and even fewer customers.",
    difficulty: "hard",
  },
  {
    id: "lr-bank35-048",
    type: "parallel-reasoning",
    sectionType: "logical-reasoning",
    stimulus: `If the proposed merger is approved, it will either increase market competition or reduce consumer prices. But it will not reduce consumer prices. Therefore, if approved, the merger will increase market competition.`,
    questionStem: "The pattern of reasoning in which one of the following is most similar to that in the argument above?",
    answerChoices: [
      { letter: "A", text: "If the defendant is guilty, he either acted alone or had an accomplice. He did not act alone. Therefore, if guilty, he had an accomplice." },
      { letter: "B", text: "If it rains, the ground will be wet. The ground is wet. Therefore, it rained." },
      { letter: "C", text: "Either the train will arrive on time or passengers will miss their connections. The train arrived on time. Therefore, passengers did not miss connections." },
      { letter: "D", text: "If she studies, she will pass. She passed. Therefore, she studied." },
      { letter: "E", text: "All cats are mammals. Felix is a cat. Therefore, Felix is a mammal." },
    ],
    correctAnswer: "A",
    explanation: "Both arguments follow the same valid pattern: If X, then (Y or Z). Not Z. Therefore, if X, then Y. This is a conditional combined with disjunctive syllogism.",
    difficulty: "hard",
  },
  {
    id: "lr-bank35-049",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `Every employee in the marketing department has completed the new software training. Some employees who completed the training have already been promoted. All promoted employees receive a salary increase. Jessica is in the marketing department and has not received a salary increase.`,
    questionStem: "If all of the statements above are true, which one of the following must also be true?",
    answerChoices: [
      { letter: "A", text: "Jessica has not completed the software training" },
      { letter: "B", text: "Jessica will not be promoted" },
      { letter: "C", text: "Jessica has not yet been promoted" },
      { letter: "D", text: "Some marketing employees have been promoted" },
      { letter: "E", text: "All employees who completed training will be promoted" },
    ],
    correctAnswer: "C",
    explanation: "Since all promoted employees get salary increases, and Jessica hasn't received a salary increase, Jessica has not been promoted (yet). She has completed training (since she's in marketing), but the logic only shows some trained employees are promoted, not all.",
    difficulty: "medium",
  },
  {
    id: "lr-bank35-050",
    type: "inference",
    sectionType: "logical-reasoning",
    stimulus: `The city's new noise ordinance prohibits construction work before 7 AM or after 9 PM on weekdays. On weekends, construction is permitted only between 9 AM and 6 PM. Violations result in fines starting at $500. The ordinance does not apply to emergency repairs that are necessary to prevent imminent harm to persons or property.`,
    questionStem: "Based on the information above, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Construction work at 8 PM on a Sunday would violate the ordinance" },
      { letter: "B", text: "Construction work at 6 AM on a Tuesday would violate the ordinance unless it is an emergency repair" },
      { letter: "C", text: "All construction work on weekends is prohibited" },
      { letter: "D", text: "Emergency repairs are never subject to fines" },
      { letter: "E", text: "Fines for violations cannot exceed $500" },
    ],
    correctAnswer: "B",
    explanation: "Construction before 7 AM on weekdays violates the ordinance. The exception is for emergency repairs to prevent imminent harm. So 6 AM Tuesday construction would violate unless it qualifies as an emergency repair. Answer A is wrong because Sunday is a weekend and 8 PM falls outside weekend hours (after 6 PM), but this doesn't account for emergency exceptions.",
    difficulty: "hard",
  },
];
