// Logic Games Set 16 - Games 76-80 with 6 questions each (30 questions total)

import { LogicGame, GameSetup, GameQuestion, getEntityColor } from "../logic-games-types";

// Game 76: Delivery Route (Linear)
const game1Setup: GameSetup = {
  id: "lg-set16-game1",
  type: "linear",
  title: "Delivery Route",
  scenario: `A delivery driver must make exactly seven stops—at locations A, B, C, D, E, F, and G—during a single day. The stops are made consecutively, from first to seventh. Each location is visited exactly once. The delivery route must conform to the following conditions:`,
  entities: [
    { id: "A", name: "Location A", shortName: "A", color: getEntityColor(0) },
    { id: "B", name: "Location B", shortName: "B", color: getEntityColor(1) },
    { id: "C", name: "Location C", shortName: "C", color: getEntityColor(2) },
    { id: "D", name: "Location D", shortName: "D", color: getEntityColor(3) },
    { id: "E", name: "Location E", shortName: "E", color: getEntityColor(4) },
    { id: "F", name: "Location F", shortName: "F", color: getEntityColor(5) },
    { id: "G", name: "Location G", shortName: "G", color: getEntityColor(6) },
  ],
  positions: 7,
  rules: [
    {
      id: "r1",
      type: "relative-order",
      text: "A is visited before B.",
      entities: ["A", "B"],
    },
    {
      id: "r2",
      type: "relative-order",
      text: "C is visited before D.",
      entities: ["C", "D"],
    },
    {
      id: "r3",
      type: "block",
      text: "E is visited immediately before F.",
      entities: ["E", "F"],
    },
    {
      id: "r4",
      type: "range",
      text: "G is visited third, fourth, or fifth.",
      entities: ["G"],
      positions: [3, 4, 5],
    },
    {
      id: "r5",
      type: "conditional",
      text: "If B is visited second, then D is visited sixth.",
      entities: ["B", "D"],
    },
  ],
  difficulty: "medium",
};

const game1Questions: GameQuestion[] = [
  {
    id: "lg16-g1-q1",
    gameId: "lg-set16-game1",
    questionNumber: 1,
    type: "acceptability",
    stem: "Which one of the following could be an acceptable order of stops?",
    answerChoices: [
      { letter: "A", text: "A, C, G, E, F, B, D" },
      { letter: "B", text: "C, A, B, G, D, E, F" },
      { letter: "C", text: "A, B, C, G, E, F, D" },
      { letter: "D", text: "E, F, A, G, C, D, B" },
      { letter: "E", text: "A, C, E, G, F, D, B" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. A(1) before B(6) satisfies rule 1. C(2) before D(7) satisfies rule 2. E(4) immediately before F(5) satisfies rule 3. G(3) is in positions 3-5 satisfying rule 4. B is not second, so rule 5 doesn't apply. (B) violates rule 2: D(5) should come after C(1), which it does, but checking rule 5: B(3), not second, so N/A. However, E(6)-F(7) works. This could work. (C) violates rule 5: B at 2 means D should be at 6, but D is at 7. (D) satisfies E(1)-F(2) consecutive, A(3) before B(7), C(5) before D(6), G(4) in 3-5. This could work. (E) violates rule 3: E(3) and F(5) are not consecutive since G(4) is between them.",
  },
  {
    id: "lg16-g1-q2",
    gameId: "lg-set16-game1",
    questionNumber: 2,
    type: "must-be-true",
    stem: "If B is visited second, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "A is visited first" },
      { letter: "B", text: "C is visited third" },
      { letter: "C", text: "G is visited fourth" },
      { letter: "D", text: "E is visited fifth" },
      { letter: "E", text: "D is visited seventh" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. A must be visited before B (rule 1). If B is second, A must be before second, which means A must be first. There is no other position available before second.",
  },
  {
    id: "lg16-g1-q3",
    gameId: "lg-set16-game1",
    questionNumber: 3,
    type: "could-be-true",
    stem: "Which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "B is visited first" },
      { letter: "B", text: "D is visited before C" },
      { letter: "C", text: "F is visited immediately before E" },
      { letter: "D", text: "G is visited second" },
      { letter: "E", text: "E is visited sixth and F is visited seventh" },
    ],
    correctAnswer: "E",
    explanation: "Answer (E) is correct. E(6)-F(7) satisfies rule 3 (E immediately before F). This is a valid placement. (A) is false because A must come before B (rule 1), so B cannot be first. (B) is false because C must come before D (rule 2). (C) is false because rule 3 requires E before F, not F before E. (D) is false because G must be 3rd, 4th, or 5th (rule 4), not second.",
  },
  {
    id: "lg16-g1-q4",
    gameId: "lg-set16-game1",
    questionNumber: 4,
    type: "must-be-false",
    stem: "Which one of the following must be false?",
    answerChoices: [
      { letter: "A", text: "A is visited third" },
      { letter: "B", text: "C is visited first" },
      { letter: "C", text: "E is visited seventh" },
      { letter: "D", text: "F is visited fourth" },
      { letter: "E", text: "G is visited fifth" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. E must be immediately before F (rule 3). If E is seventh (last), F would have to be eighth, which doesn't exist. Therefore, E cannot be seventh. The other options are all possible: A can be third (with B after), C can be first, F can be fourth (with E third), and G can be fifth (satisfying rule 4).",
  },
  {
    id: "lg16-g1-q5",
    gameId: "lg-set16-game1",
    questionNumber: 5,
    type: "could-be-true",
    stem: "If G is visited third, which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "E is visited first" },
      { letter: "B", text: "B is visited second and D is visited seventh" },
      { letter: "C", text: "A is visited fifth" },
      { letter: "D", text: "F is visited third" },
      { letter: "E", text: "C is visited seventh" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. With G at position 3, E(1)-F(2) is possible (E immediately before F). Then A-B and C-D can fill positions 4-7 with proper ordering. For example: E, F, G, A, C, B, D. (B) is false because if B is second, rule 5 requires D at sixth, not seventh. (C) is possible if A is fifth with B at 6 or 7. (D) is false because G is already at third. (E) is false because C must come before D, so C cannot be last.",
  },
  {
    id: "lg16-g1-q6",
    gameId: "lg-set16-game1",
    questionNumber: 6,
    type: "must-be-true",
    stem: "If A is first, B is second, and C is third, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "D is visited sixth" },
      { letter: "B", text: "E is visited fourth" },
      { letter: "C", text: "G is visited fifth" },
      { letter: "D", text: "F is visited seventh" },
      { letter: "E", text: "E is visited fifth" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. With A(1), B(2), C(3): Since B is second, rule 5 applies, requiring D to be sixth. G must be in 4 or 5 (rule 4, since 3 is taken). E-F must be consecutive. Remaining positions are 4, 5, 7 for D (fixed at 6), E, F, G. With D at 6 and G needing 4 or 5, the E-F block and G must fit in 4, 5, 7. This creates constraints, but D at 6 is forced by rule 5.",
  },
];

const game1: LogicGame = { setup: game1Setup, questions: game1Questions };

// Game 77: Investment Portfolio (Grouping)
const game2Setup: GameSetup = {
  id: "lg-set16-game2",
  type: "grouping",
  title: "Investment Portfolio",
  scenario: `A financial advisor is allocating eight investment options—Bonds, Commodities, Derivatives, Equities, Funds, Gold, Healthcare stocks, and Infrastructure—into three portfolios: Conservative, Moderate, and Aggressive. Each investment is placed in exactly one portfolio. The Conservative portfolio has exactly two investments. The Moderate and Aggressive portfolios each have at least two investments. The following conditions apply:`,
  entities: [
    { id: "B", name: "Bonds", shortName: "B", color: getEntityColor(0) },
    { id: "C", name: "Commodities", shortName: "C", color: getEntityColor(1) },
    { id: "D", name: "Derivatives", shortName: "D", color: getEntityColor(2) },
    { id: "E", name: "Equities", shortName: "E", color: getEntityColor(3) },
    { id: "F", name: "Funds", shortName: "F", color: getEntityColor(4) },
    { id: "G", name: "Gold", shortName: "G", color: getEntityColor(5) },
    { id: "H", name: "Healthcare", shortName: "H", color: getEntityColor(6) },
    { id: "I", name: "Infrastructure", shortName: "I", color: getEntityColor(7) },
  ],
  groups: [
    { id: "conservative", name: "Conservative", minSize: 2, maxSize: 2 },
    { id: "moderate", name: "Moderate", minSize: 2, maxSize: 6 },
    { id: "aggressive", name: "Aggressive", minSize: 2, maxSize: 6 },
  ],
  rules: [
    {
      id: "r1",
      type: "fixed-position",
      text: "Bonds is in the Conservative portfolio.",
      entities: ["B"],
      groups: ["conservative"],
    },
    {
      id: "r2",
      type: "fixed-position",
      text: "Derivatives is in the Aggressive portfolio.",
      entities: ["D"],
      groups: ["aggressive"],
    },
    {
      id: "r3",
      type: "same-group",
      text: "Equities and Funds are in the same portfolio.",
      entities: ["E", "F"],
    },
    {
      id: "r4",
      type: "different-group",
      text: "Gold and Healthcare are in different portfolios.",
      entities: ["G", "H"],
    },
    {
      id: "r5",
      type: "conditional",
      text: "If Commodities is in Moderate, then Infrastructure is in Aggressive.",
      entities: ["C", "I"],
    },
  ],
  difficulty: "medium",
};

const game2Questions: GameQuestion[] = [
  {
    id: "lg16-g2-q1",
    gameId: "lg-set16-game2",
    questionNumber: 1,
    type: "acceptability",
    stem: "Which one of the following could be an acceptable allocation?",
    answerChoices: [
      { letter: "A", text: "Conservative: Bonds, Gold; Moderate: Commodities, Equities, Funds; Aggressive: Derivatives, Healthcare, Infrastructure" },
      { letter: "B", text: "Conservative: Bonds, Healthcare; Moderate: Commodities, Gold; Aggressive: Derivatives, Equities, Funds, Infrastructure" },
      { letter: "C", text: "Conservative: Bonds, Equities; Moderate: Commodities, Funds, Gold; Aggressive: Derivatives, Healthcare, Infrastructure" },
      { letter: "D", text: "Conservative: Bonds, Infrastructure; Moderate: Commodities, Gold, Healthcare; Aggressive: Derivatives, Equities, Funds" },
      { letter: "E", text: "Conservative: Bonds, Commodities; Moderate: Equities, Funds, Gold; Aggressive: Derivatives, Healthcare, Infrastructure" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. B in Conservative (rule 1). D in Aggressive (rule 2). E-F same portfolio (Moderate) (rule 3). G-H different portfolios (Conservative, Aggressive) (rule 4). C in Moderate triggers rule 5, so I in Aggressive, which it is. Conservative has exactly 2. (B) fails: C in Moderate means I in Aggressive, which is satisfied. But checking rule 5, this could work. (C) fails: E-F are in different portfolios (Conservative, Moderate), violating rule 3. (D) fails: G-H are both in Moderate, violating rule 4. (E) could work but C is in Conservative, not Moderate, so rule 5 doesn't trigger.",
  },
  {
    id: "lg16-g2-q2",
    gameId: "lg-set16-game2",
    questionNumber: 2,
    type: "must-be-true",
    stem: "Which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Commodities is in the Moderate portfolio" },
      { letter: "B", text: "Derivatives is in the Aggressive portfolio" },
      { letter: "C", text: "Gold is in the Conservative portfolio" },
      { letter: "D", text: "Healthcare is in the Moderate portfolio" },
      { letter: "E", text: "Infrastructure is in the Aggressive portfolio" },
    ],
    correctAnswer: "B",
    explanation: "Answer (B) is correct. Rule 2 explicitly states that Derivatives is in the Aggressive portfolio. This is a fixed placement and must always be true. The other options depend on variable placements that can change in different valid solutions.",
  },
  {
    id: "lg16-g2-q3",
    gameId: "lg-set16-game2",
    questionNumber: 3,
    type: "must-be-false",
    stem: "Which one of the following must be false?",
    answerChoices: [
      { letter: "A", text: "Gold is in the Aggressive portfolio" },
      { letter: "B", text: "Healthcare is in the Conservative portfolio" },
      { letter: "C", text: "Equities is in the Conservative portfolio" },
      { letter: "D", text: "Infrastructure is in the Moderate portfolio" },
      { letter: "E", text: "Commodities is in the Aggressive portfolio" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. Conservative has exactly 2 investments, and Bonds is already one of them (rule 1). If Equities is in Conservative, Funds must also be in Conservative (rule 3 requires E-F together), making 3 investments in Conservative, which exceeds the maximum of 2. Therefore, Equities cannot be in Conservative.",
  },
  {
    id: "lg16-g2-q4",
    gameId: "lg-set16-game2",
    questionNumber: 4,
    type: "could-be-true",
    stem: "Which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "Bonds is in the Moderate portfolio" },
      { letter: "B", text: "Derivatives is in the Conservative portfolio" },
      { letter: "C", text: "Gold and Healthcare are in the same portfolio" },
      { letter: "D", text: "Equities and Funds are in different portfolios" },
      { letter: "E", text: "Infrastructure is in the Conservative portfolio" },
    ],
    correctAnswer: "E",
    explanation: "Answer (E) is correct. Infrastructure can be in Conservative as the second investment alongside Bonds. No rule prevents this. (A) violates rule 1 (B must be in Conservative). (B) violates rule 2 (D must be in Aggressive). (C) violates rule 4 (G and H must be different). (D) violates rule 3 (E and F must be together).",
  },
  {
    id: "lg16-g2-q5",
    gameId: "lg-set16-game2",
    questionNumber: 5,
    type: "could-be-true",
    stem: "If Gold is in the Conservative portfolio, which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "Healthcare is in the Conservative portfolio" },
      { letter: "B", text: "Commodities is in the Conservative portfolio" },
      { letter: "C", text: "Infrastructure is in the Moderate portfolio" },
      { letter: "D", text: "Equities is in the Conservative portfolio" },
      { letter: "E", text: "Healthcare is in the same portfolio as Gold" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. G in Conservative means Conservative is: B, G (exactly 2, full). H must be different from G (rule 4), so H in Moderate or Aggressive. I in Moderate is possible when C is not in Moderate (rule 5 doesn't trigger), or C is elsewhere. (A) fails: Conservative is full with B and G. (B) fails: Conservative is full. (D) fails: E in Conservative would require F (rule 3), exceeding the 2-investment limit. (E) fails: Rule 4 requires G and H in different portfolios.",
  },
  {
    id: "lg16-g2-q6",
    gameId: "lg-set16-game2",
    questionNumber: 6,
    type: "must-be-true",
    stem: "If Commodities is in the Moderate portfolio and Gold is in the Conservative portfolio, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Healthcare is in the Moderate portfolio" },
      { letter: "B", text: "Infrastructure is in the Aggressive portfolio" },
      { letter: "C", text: "Equities is in the Moderate portfolio" },
      { letter: "D", text: "Funds is in the Aggressive portfolio" },
      { letter: "E", text: "Healthcare is in the Aggressive portfolio" },
    ],
    correctAnswer: "B",
    explanation: "Answer (B) is correct. C in Moderate triggers rule 5: I must be in Aggressive. G in Conservative means Conservative is: B, G (exactly 2, full). D is in Aggressive (rule 2). So Aggressive has at least D and I. E-F together can be in Moderate or Aggressive. H different from G means H in Moderate or Aggressive. Infrastructure in Aggressive is forced by rule 5.",
  },
];

const game2: LogicGame = { setup: game2Setup, questions: game2Questions };

// Game 78: Art Gallery Tour (Linear)
const game3Setup: GameSetup = {
  id: "lg-set16-game3",
  type: "linear",
  title: "Art Gallery Tour",
  scenario: `An art gallery guide leads visitors through six exhibition rooms—Renaissance, Baroque, Impressionist, Modern, Contemporary, and Abstract—in a specific order. The rooms are visited consecutively, from first to sixth. The following conditions apply:`,
  entities: [
    { id: "R", name: "Renaissance", shortName: "R", color: getEntityColor(0) },
    { id: "B", name: "Baroque", shortName: "B", color: getEntityColor(1) },
    { id: "I", name: "Impressionist", shortName: "I", color: getEntityColor(2) },
    { id: "M", name: "Modern", shortName: "M", color: getEntityColor(3) },
    { id: "C", name: "Contemporary", shortName: "C", color: getEntityColor(4) },
    { id: "A", name: "Abstract", shortName: "A", color: getEntityColor(5) },
  ],
  positions: 6,
  rules: [
    {
      id: "r1",
      type: "relative-order",
      text: "Renaissance is visited before Baroque.",
      entities: ["R", "B"],
    },
    {
      id: "r2",
      type: "relative-order",
      text: "Baroque is visited before Impressionist.",
      entities: ["B", "I"],
    },
    {
      id: "r3",
      type: "not-adjacent",
      text: "Modern and Contemporary are not visited consecutively.",
      entities: ["M", "C"],
    },
    {
      id: "r4",
      type: "range",
      text: "Abstract is visited fourth or later.",
      entities: ["A"],
      positions: [4, 5, 6],
    },
    {
      id: "r5",
      type: "conditional",
      text: "If Contemporary is visited first, then Abstract is visited sixth.",
      entities: ["C", "A"],
    },
  ],
  difficulty: "medium",
};

const game3Questions: GameQuestion[] = [
  {
    id: "lg16-g3-q1",
    gameId: "lg-set16-game3",
    questionNumber: 1,
    type: "acceptability",
    stem: "Which one of the following could be an acceptable order for visiting the rooms?",
    answerChoices: [
      { letter: "A", text: "Renaissance, Baroque, Modern, Impressionist, Abstract, Contemporary" },
      { letter: "B", text: "Contemporary, Renaissance, Baroque, Impressionist, Modern, Abstract" },
      { letter: "C", text: "Renaissance, Modern, Baroque, Contemporary, Impressionist, Abstract" },
      { letter: "D", text: "Baroque, Renaissance, Impressionist, Abstract, Modern, Contemporary" },
      { letter: "E", text: "Renaissance, Baroque, Impressionist, Contemporary, Modern, Abstract" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. R(1) before B(2) (rule 1). B(2) before I(4) (rule 2). M(3) and C(6) not consecutive (rule 3). A(5) is 4th or later (rule 4). C is not first, so rule 5 doesn't apply. (B): C(1) means A must be sixth (rule 5), and A is 6th. R(2) before B(3). B(3) before I(4). M(5)-A(6) not checking M-C: M(5), C(1) not consecutive. This works too. (C): R(1) before B(3). B(3) before I(5). M(2)-C(4) not consecutive. A(6) is 4th or later. This works. (D) fails: B(1) is before R(2), violating rule 1 (R before B). (E): C(4)-M(5) are consecutive, violating rule 3.",
  },
  {
    id: "lg16-g3-q2",
    gameId: "lg-set16-game3",
    questionNumber: 2,
    type: "must-be-true",
    stem: "If Contemporary is visited first, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Renaissance is visited second" },
      { letter: "B", text: "Baroque is visited third" },
      { letter: "C", text: "Abstract is visited sixth" },
      { letter: "D", text: "Modern is visited fourth" },
      { letter: "E", text: "Impressionist is visited fifth" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. Rule 5 states: If Contemporary is visited first, then Abstract is visited sixth. Since Contemporary is first, Abstract must be sixth. This is a direct application of the conditional rule.",
  },
  {
    id: "lg16-g3-q3",
    gameId: "lg-set16-game3",
    questionNumber: 3,
    type: "could-be-true",
    stem: "Which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "Baroque is visited first" },
      { letter: "B", text: "Impressionist is visited second" },
      { letter: "C", text: "Abstract is visited third" },
      { letter: "D", text: "Modern is visited immediately before Contemporary" },
      { letter: "E", text: "Abstract is visited fourth" },
    ],
    correctAnswer: "E",
    explanation: "Answer (E) is correct. A at 4th satisfies rule 4 (4th or later). (A) is false because R must come before B (rule 1), so B cannot be first. (B) is false because R before B before I (rules 1-2) means I needs at least 2 positions before it, making I at minimum 3rd. (C) is false because A must be 4th or later (rule 4). (D) is false because M and C cannot be consecutive (rule 3), so M cannot be immediately before C.",
  },
  {
    id: "lg16-g3-q4",
    gameId: "lg-set16-game3",
    questionNumber: 4,
    type: "must-be-false",
    stem: "Which one of the following must be false?",
    answerChoices: [
      { letter: "A", text: "Renaissance is visited third" },
      { letter: "B", text: "Baroque is visited fifth" },
      { letter: "C", text: "Impressionist is visited first" },
      { letter: "D", text: "Modern is visited first" },
      { letter: "E", text: "Contemporary is visited sixth" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. The chain R -> B -> I (rules 1-2) means Renaissance before Baroque before Impressionist. For I to be first, both R and B would need to come before first position, which is impossible. Therefore, Impressionist cannot be first. The other options are possible in valid arrangements.",
  },
  {
    id: "lg16-g3-q5",
    gameId: "lg-set16-game3",
    questionNumber: 5,
    type: "could-be-true",
    stem: "If Abstract is visited fourth, which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "Contemporary is visited first" },
      { letter: "B", text: "Modern is visited third and Contemporary is visited fifth" },
      { letter: "C", text: "Impressionist is visited sixth" },
      { letter: "D", text: "Baroque is visited fifth" },
      { letter: "E", text: "Renaissance is visited fourth" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. With A at 4th, we need R before B before I. If I(6), then R and B are in positions 1-5 (excluding 4). A valid arrangement: R(1), B(2), M(3), A(4), C(5), I(6). M(3)-C(5) not consecutive (rule 3). (A) is false because C(1) would require A(6) by rule 5, but A is at 4. (B): M(3)-C(5) not consecutive, but need to check R-B-I chain fits. (D): B(5) means I after 5, so I at 6. R before 5. This could work. (E) is false because A is at 4.",
  },
  {
    id: "lg16-g3-q6",
    gameId: "lg-set16-game3",
    questionNumber: 6,
    type: "must-be-true",
    stem: "If Renaissance is first and Impressionist is sixth, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Baroque is second" },
      { letter: "B", text: "Modern is third" },
      { letter: "C", text: "Abstract is fourth or fifth" },
      { letter: "D", text: "Contemporary is second" },
      { letter: "E", text: "Abstract is sixth" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. R(1), I(6). B must be between R and I: B at 2, 3, 4, or 5. A must be 4th or later (rule 4), so A at 4 or 5 (since 6 is I). M and C fill remaining positions but cannot be consecutive. With R fixed at 1 and I at 6, positions 2-5 hold B, M, C, A. Since A must be at 4 or 5, answer (C) is correct.",
  },
];

const game3: LogicGame = { setup: game3Setup, questions: game3Questions };

// Game 79: Job Interview Schedule (Matching)
const game4Setup: GameSetup = {
  id: "lg-set16-game4",
  type: "matching",
  title: "Job Interview Schedule",
  scenario: `A company is scheduling interviews with six candidates—Patel, Quinn, Rivera, Santos, Thompson, and Upton—during three time periods: Morning, Afternoon, and Evening. Each candidate is interviewed during exactly one time period. Each time period has exactly two interviews. Each candidate is interviewed by either the HR team or the Technical team. The following conditions apply:`,
  entities: [
    { id: "P", name: "Patel", shortName: "P", color: getEntityColor(0) },
    { id: "Q", name: "Quinn", shortName: "Q", color: getEntityColor(1) },
    { id: "R", name: "Rivera", shortName: "R", color: getEntityColor(2) },
    { id: "S", name: "Santos", shortName: "S", color: getEntityColor(3) },
    { id: "T", name: "Thompson", shortName: "T", color: getEntityColor(4) },
    { id: "U", name: "Upton", shortName: "U", color: getEntityColor(5) },
  ],
  groups: [
    { id: "morning", name: "Morning", minSize: 2, maxSize: 2 },
    { id: "afternoon", name: "Afternoon", minSize: 2, maxSize: 2 },
    { id: "evening", name: "Evening", minSize: 2, maxSize: 2 },
  ],
  rules: [
    {
      id: "r1",
      type: "same-group",
      text: "Patel and Quinn are interviewed during the same time period.",
      entities: ["P", "Q"],
    },
    {
      id: "r2",
      type: "different-group",
      text: "Rivera and Santos are interviewed during different time periods.",
      entities: ["R", "S"],
    },
    {
      id: "r3",
      type: "custom",
      text: "Thompson is interviewed by the Technical team.",
      entities: ["T"],
    },
    {
      id: "r4",
      type: "conditional",
      text: "If Upton is interviewed in the Morning, then Upton is interviewed by HR.",
      entities: ["U"],
    },
    {
      id: "r5",
      type: "different-group",
      text: "Patel and Rivera are interviewed during different time periods.",
      entities: ["P", "R"],
    },
  ],
  difficulty: "hard",
};

const game4Questions: GameQuestion[] = [
  {
    id: "lg16-g4-q1",
    gameId: "lg-set16-game4",
    questionNumber: 1,
    type: "acceptability",
    stem: "Which one of the following could be an acceptable schedule?",
    answerChoices: [
      { letter: "A", text: "Morning: Patel, Quinn; Afternoon: Rivera, Thompson; Evening: Santos, Upton" },
      { letter: "B", text: "Morning: Patel, Rivera; Afternoon: Quinn, Santos; Evening: Thompson, Upton" },
      { letter: "C", text: "Morning: Rivera, Santos; Afternoon: Patel, Quinn; Evening: Thompson, Upton" },
      { letter: "D", text: "Morning: Thompson, Upton; Afternoon: Patel, Rivera; Evening: Quinn, Santos" },
      { letter: "E", text: "Morning: Rivera, Upton; Afternoon: Patel, Quinn; Evening: Santos, Thompson" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. P-Q same time (Morning) (rule 1). R-S different times (Afternoon, Evening) (rule 2). P-R different times (Morning, Afternoon) (rule 5). Each period has 2 candidates. (B) fails: P-Q are in different periods (Morning, Afternoon), violating rule 1. (C) fails: R-S are in the same period (Morning), violating rule 2. (D) fails: P-Q are in different periods (Afternoon, Evening), violating rule 1. (E) is also valid: P-Q same (Afternoon), R-S different (Morning, Evening), P-R different (Afternoon, Morning).",
  },
  {
    id: "lg16-g4-q2",
    gameId: "lg-set16-game4",
    questionNumber: 2,
    type: "must-be-true",
    stem: "Which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Patel is interviewed by the HR team" },
      { letter: "B", text: "Quinn is interviewed during the same time period as Patel" },
      { letter: "C", text: "Rivera is interviewed in the Afternoon" },
      { letter: "D", text: "Santos is interviewed in the Evening" },
      { letter: "E", text: "Thompson is interviewed in the Morning" },
    ],
    correctAnswer: "B",
    explanation: "Answer (B) is correct. Rule 1 explicitly states that Patel and Quinn are interviewed during the same time period. This must always be true regardless of other arrangements.",
  },
  {
    id: "lg16-g4-q3",
    gameId: "lg-set16-game4",
    questionNumber: 3,
    type: "could-be-true",
    stem: "Which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "Patel and Rivera are interviewed during the same time period" },
      { letter: "B", text: "Rivera and Santos are interviewed during the same time period" },
      { letter: "C", text: "Patel and Quinn are interviewed during different time periods" },
      { letter: "D", text: "Upton is interviewed in the Morning by the Technical team" },
      { letter: "E", text: "Thompson and Upton are interviewed during the same time period" },
    ],
    correctAnswer: "E",
    explanation: "Answer (E) is correct. T and U can be in the same time period; no rule prevents this. (A) violates rule 5. (B) violates rule 2. (C) violates rule 1. (D) violates rule 4: if U is in Morning, U must be interviewed by HR, not Technical.",
  },
  {
    id: "lg16-g4-q4",
    gameId: "lg-set16-game4",
    questionNumber: 4,
    type: "must-be-false",
    stem: "Which one of the following must be false?",
    answerChoices: [
      { letter: "A", text: "Patel is interviewed in the Morning" },
      { letter: "B", text: "Quinn is interviewed by the HR team" },
      { letter: "C", text: "Rivera is interviewed during the same time period as Patel" },
      { letter: "D", text: "Santos is interviewed in the Morning" },
      { letter: "E", text: "Thompson is interviewed by the HR team" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. Rule 5 states that Patel and Rivera are interviewed during different time periods. They can never be in the same time period. Note: (E) is also false because rule 3 says Thompson is interviewed by Technical, not HR.",
  },
  {
    id: "lg16-g4-q5",
    gameId: "lg-set16-game4",
    questionNumber: 5,
    type: "could-be-true",
    stem: "If Santos is interviewed in the Morning, which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "Patel is interviewed in the Morning" },
      { letter: "B", text: "Rivera is interviewed in the Morning" },
      { letter: "C", text: "Thompson is interviewed in the Morning" },
      { letter: "D", text: "Upton is interviewed in the Morning by the Technical team" },
      { letter: "E", text: "Quinn is interviewed in the Afternoon and Patel in the Evening" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. S in Morning. R must be different from S (rule 2), so R in Afternoon or Evening. Morning has 2 slots: S + 1 other. P-Q together (rule 1), so if P in Morning, Q in Morning, which would be 3 people. So P-Q not in Morning. T in Morning with S is possible: Morning: S, T. (A) fails: P in Morning requires Q in Morning, making 3 in Morning. (B) fails: R-S must be different. (D) fails: U in Morning means U by HR, not Technical. (E) fails: P-Q must be same period.",
  },
  {
    id: "lg16-g4-q6",
    gameId: "lg-set16-game4",
    questionNumber: 6,
    type: "must-be-true",
    stem: "If Patel and Quinn are interviewed in the Afternoon, and Rivera is interviewed in the Morning, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "Santos is interviewed in the Evening" },
      { letter: "B", text: "Thompson is interviewed in the Morning" },
      { letter: "C", text: "Upton is interviewed in the Morning" },
      { letter: "D", text: "Santos is interviewed in the Afternoon" },
      { letter: "E", text: "Thompson is interviewed in the Evening" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. P-Q in Afternoon (fills 2 slots, Afternoon is full). R in Morning. R-S different (rule 2), so S not in Morning. S in Afternoon or Evening. Afternoon is full (P, Q), so S must be in Evening. Therefore, Santos must be interviewed in the Evening.",
  },
];

const game4: LogicGame = { setup: game4Setup, questions: game4Questions };

// Game 80: Wildlife Sanctuary (Hybrid - Grouping + Matching)
const game5Setup: GameSetup = {
  id: "lg-set16-game5",
  type: "hybrid",
  title: "Wildlife Sanctuary",
  scenario: `A wildlife sanctuary houses seven animals—an antelope, a bear, a cheetah, a deer, an elephant, a falcon, and a giraffe—in three habitats: Grassland, Forest, and Wetland. Each animal is housed in exactly one habitat. Each habitat houses at least two animals. Each animal is classified as either diurnal or nocturnal. The following conditions apply:`,
  entities: [
    { id: "A", name: "Antelope", shortName: "A", color: getEntityColor(0) },
    { id: "B", name: "Bear", shortName: "B", color: getEntityColor(1) },
    { id: "C", name: "Cheetah", shortName: "C", color: getEntityColor(2) },
    { id: "D", name: "Deer", shortName: "D", color: getEntityColor(3) },
    { id: "E", name: "Elephant", shortName: "E", color: getEntityColor(4) },
    { id: "F", name: "Falcon", shortName: "F", color: getEntityColor(5) },
    { id: "G", name: "Giraffe", shortName: "G", color: getEntityColor(6) },
  ],
  groups: [
    { id: "grassland", name: "Grassland", minSize: 2, maxSize: 5 },
    { id: "forest", name: "Forest", minSize: 2, maxSize: 5 },
    { id: "wetland", name: "Wetland", minSize: 2, maxSize: 5 },
  ],
  rules: [
    {
      id: "r1",
      type: "same-group",
      text: "The antelope and cheetah are in the same habitat.",
      entities: ["A", "C"],
    },
    {
      id: "r2",
      type: "different-group",
      text: "The bear and deer are in different habitats.",
      entities: ["B", "D"],
    },
    {
      id: "r3",
      type: "custom",
      text: "The elephant is nocturnal.",
      entities: ["E"],
    },
    {
      id: "r4",
      type: "conditional",
      text: "If the falcon is in the Grassland, then the falcon is diurnal.",
      entities: ["F"],
    },
    {
      id: "r5",
      type: "fixed-position",
      text: "The giraffe is in the Grassland.",
      entities: ["G"],
      groups: ["grassland"],
    },
  ],
  difficulty: "hard",
};

const game5Questions: GameQuestion[] = [
  {
    id: "lg16-g5-q1",
    gameId: "lg-set16-game5",
    questionNumber: 1,
    type: "acceptability",
    stem: "Which one of the following could be an acceptable arrangement?",
    answerChoices: [
      { letter: "A", text: "Grassland: Antelope, Cheetah, Giraffe; Forest: Bear, Falcon; Wetland: Deer, Elephant" },
      { letter: "B", text: "Grassland: Giraffe, Elephant; Forest: Antelope, Bear, Cheetah; Wetland: Deer, Falcon" },
      { letter: "C", text: "Grassland: Antelope, Giraffe; Forest: Bear, Deer, Falcon; Wetland: Cheetah, Elephant" },
      { letter: "D", text: "Grassland: Bear, Deer, Giraffe; Forest: Antelope, Cheetah; Wetland: Elephant, Falcon" },
      { letter: "E", text: "Grassland: Cheetah, Giraffe; Forest: Antelope, Bear, Falcon; Wetland: Deer, Elephant" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. A-C same habitat (Grassland) (rule 1). B-D different habitats (Forest, Wetland) (rule 2). G in Grassland (rule 5). Each habitat has at least 2 animals. (B): A-C same (Forest). B-D different (Forest, Wetland). G in Grassland. This works. (C) fails: A-C different habitats (Grassland, Wetland), violating rule 1. (D) fails: B-D same habitat (Grassland), violating rule 2. (E) fails: A-C different habitats (Grassland, Forest), violating rule 1.",
  },
  {
    id: "lg16-g5-q2",
    gameId: "lg-set16-game5",
    questionNumber: 2,
    type: "must-be-true",
    stem: "Which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "The antelope is in the Grassland" },
      { letter: "B", text: "The bear is in the Forest" },
      { letter: "C", text: "The cheetah is in the same habitat as the antelope" },
      { letter: "D", text: "The deer is in the Wetland" },
      { letter: "E", text: "The falcon is diurnal" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. Rule 1 explicitly states that the antelope and cheetah are in the same habitat. This must always be true regardless of which habitat they are placed in.",
  },
  {
    id: "lg16-g5-q3",
    gameId: "lg-set16-game5",
    questionNumber: 3,
    type: "could-be-true",
    stem: "Which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "The bear and deer are in the same habitat" },
      { letter: "B", text: "The antelope and cheetah are in different habitats" },
      { letter: "C", text: "The giraffe is in the Forest" },
      { letter: "D", text: "The falcon is in the Grassland and is nocturnal" },
      { letter: "E", text: "The elephant is in the Grassland" },
    ],
    correctAnswer: "E",
    explanation: "Answer (E) is correct. E can be in any habitat; no rule restricts E's habitat placement (rule 3 only specifies E is nocturnal). (A) violates rule 2 (B and D must be different). (B) violates rule 1 (A and C must be same). (C) violates rule 5 (G must be in Grassland). (D) violates rule 4: if F in Grassland, F must be diurnal, not nocturnal.",
  },
  {
    id: "lg16-g5-q4",
    gameId: "lg-set16-game5",
    questionNumber: 4,
    type: "must-be-false",
    stem: "Which one of the following must be false?",
    answerChoices: [
      { letter: "A", text: "The antelope is in the Forest" },
      { letter: "B", text: "The bear is in the Wetland" },
      { letter: "C", text: "The deer is in the Grassland with the bear" },
      { letter: "D", text: "The elephant is in the Forest" },
      { letter: "E", text: "The falcon is in the Wetland" },
    ],
    correctAnswer: "C",
    explanation: "Answer (C) is correct. Rule 2 states that the bear and deer are in different habitats. If both are in Grassland together, this violates rule 2. The deer and bear can never be in the same habitat.",
  },
  {
    id: "lg16-g5-q5",
    gameId: "lg-set16-game5",
    questionNumber: 5,
    type: "could-be-true",
    stem: "If the antelope and cheetah are in the Forest, which one of the following could be true?",
    answerChoices: [
      { letter: "A", text: "The bear is in the Forest" },
      { letter: "B", text: "The giraffe is in the Forest" },
      { letter: "C", text: "Only one animal is in the Grassland" },
      { letter: "D", text: "The deer is in the Forest with the bear" },
      { letter: "E", text: "All seven animals are in the Forest" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. A-C in Forest. G must be in Grassland (rule 5). B-D different habitats (rule 2). B in Forest is possible. Example: Forest: A, C, B; Grassland: G, E; Wetland: D, F. (B) fails: G must be in Grassland. (C) fails: Each habitat needs at least 2 animals. (D) fails: B-D must be different habitats. (E) fails: G must be in Grassland, and each habitat needs at least 2.",
  },
  {
    id: "lg16-g5-q6",
    gameId: "lg-set16-game5",
    questionNumber: 6,
    type: "must-be-true",
    stem: "If the bear is in the Wetland and the antelope is in the Grassland, which one of the following must be true?",
    answerChoices: [
      { letter: "A", text: "The cheetah is in the Grassland" },
      { letter: "B", text: "The deer is in the Forest" },
      { letter: "C", text: "The elephant is in the Wetland" },
      { letter: "D", text: "The falcon is in the Forest" },
      { letter: "E", text: "The deer is in the Grassland" },
    ],
    correctAnswer: "A",
    explanation: "Answer (A) is correct. A in Grassland means C in Grassland (rule 1: A and C together). B in Wetland. G in Grassland (rule 5). So Grassland has at least: A, C, G. D must be different from B (rule 2), so D in Grassland or Forest (not Wetland). E and F can go anywhere to satisfy minimum 2 per habitat.",
  },
];

const game5: LogicGame = { setup: game5Setup, questions: game5Questions };

export const logicGamesSet16: LogicGame[] = [game1, game2, game3, game4, game5];
